### ISSUE TITLE
Please add cookbook for howto use Pyenv and Supervisor

### ISSUE THREAD

**Issue by bbulkow** [pyenv/pyenv#1007]
I desire to use pyenv and supervisor together ( for my daemons ), yet I can't find a good cookbook for how to use them together. I think supervisor is often-used, thus is a very reasonable candidate for a quick two-line howto. I'd do the pull request myself except I don't know how to do it

**Comment by ipfans** [comment]
I think you have two ways to work with pyenv:

1. Working with interpreter path directly: call your python with /path/to/.pyenv/versions/version_you_want/bin/python
2. Working with Virtualenv: nothing new here.

**Comment by bbulkow** [comment]
Please don't close this., unless you are saying you aren't going to do this.

Using the direct path is bad. It doesn't do all the shimming right, and encodes the version of python in the supervisord conf file.

Using virtualenv is not the answer because it's not pyenv.

I believe there would be two actual ways:
* Create a separate bash script that includes the -init and the command
* Use some kind of eval (pyenv -init) && yourcommand

Given that python is often used for system daemons, I request adding the simple cookbook to the documentation.

**Comment by hemanth7787** [comment]
Sample supervisor configuration using pyenv
```
#THIS FILE /etc/supervisor/conf.d/test.conf
[program:testprogram]
user = ubuntu
command=/home/ubuntu/.pyenv/versions/2.7.3/bin/python -m SimpleHTTPServer 8080

stderr_logfile = /tmp/test_err.log
stdout_logfile = /tmp/test_out.log
stopsignal=INT

```

Sample supervisor configuration for virtualenv inside pyenv
```
[program:testprogram]
user = ubuntu
command=/home/ubuntu/.pyenv/versions/2.7.3/envs/my-virtual-env-2.7.3/bin/python -m SimpleHTTPServer 8080

stderr_logfile = /tmp/test_err.log
stdout_logfile = /tmp/test_out.log
stopsignal=INT
```

**Comment by yyuu** [comment]
This isn’t pyenv issue at all. Write some blog post by yourself.
