### ISSUE TITLE
python2.7.8 not working, but python3.6.2 is

### ISSUE THREAD

**Issue by 3rd3** [pyenv/pyenv#1008]
First, I ran this:

```
brew install pyenv
export CFLAGS="-I$(brew --prefix openssl)/include"
export LDFLAGS="-L$(brew --prefix openssl)/lib"
pyenv install 3.6.2
pyenv install 2.7.8
pyenv global 2.7.8
pyenv local 2.7.8
```
I added these three lines to `.zshenv`:

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```

At the end of the 2.7 install I got this: `pyenv: cannot rehash: /Users/me/.pyenv/shims/.pyenv-shim exists`

When I start a new terminal session, I get this:

```
→ ~ which python2.7
/usr/bin/python2.7
→ ~ which python2.7.8
python2.7.8 not found
→ ~ which python3
/Users/me/.pyenv/shims/python3
→ ~ python2.7 --version
Python 2.7.10
→ ~ python3 --version
Python 3.6.2
→ ~ ls .pyenv/bin
→ ~ ls .pyenv/versions
2.7.8  3.6.2
```

Am I overlooking something? It also seems curious that `.pyenv/bin` is empty, but added to `PATH` according to the installation instructions. I am running macOS Sierra 10.13 (17A365) and brew is up-to-date.

**Comment by joshfriend** [comment]
The `.pyenv-shim` file is generated to prevent multiple processes from running `pyenv rehash` simultaneously. You can manually remove this file and try to run rehash manually and see if that helps.

A couple of additional notes (probably unrelated):

1. shims are not generated down to the patch version of python, e.g. you get `python`, `python2` and `python2.7`, but **not** `python2.7.8`
2. The security content of the update to 2.7.9 is [very substantial](https://www.python.org/downloads/release/python-279/), you should use that one if you can, or even the latest (2.7.14).

**Comment by 3rd3** [comment]
Thanks, rehashing solved the issue.
