### ISSUE TITLE
macOS High Sierra: ERROR:  ModuleNotFoundError: No module named 'pyexpat'

### ISSUE THREAD

**Issue by bright-pan** [pyenv/pyenv#1011]
platform: macOS 10.13, xcode 9.0.1, macports
```
CFLAGS="-I/opt/local/include/" \
LDFLAGS="-L/opt/local/lib/" \
pyenv install -v 2.7.14
```
[python-build.20171017165051.35993.log](https://gist.github.com/bright-pan/47104ccdeab9cbabe25cb6ff1713b1aa)

can you help me ? @joshfriend  @nikolay @richardbowden

**Comment by richardbowden** [comment]
I am getting the same, I have being trying to debug, but cannot find a reason for it yet

**Comment by Nax** [comment]
I am getting the same issue.

**Comment by richardbowden** [comment]
I have been trying various commands to get it to work, still no go (I use macports), still looking

`CFLAGS="-I$(xcrun` --show-sdk-path)/usr/include" pyenv install 2.7.14`
`CFLAGS="-I$(xcrun --show-sdk-path)/usr/include -I/opt/local/include/" LDFLAGS="-L/opt/local/lib/"  pyenv install 2.7.14`
`CFLAGS="-I$(xcrun --show-sdk-path)/usr/include -I/opt/local/include/ -I/opt/local/include/readline/" LDFLAGS="-L/opt/local/lib/" pyenv install -k -v 2.7.14`

**Comment by htesgaard** [comment]
[Somehow CFLAGS and LDFLAGS might point to a wrong path](https://github.com/pyenv/pyenv/wiki/Common-build-problems#error-the-python-ssl-extension-was-not-compiled-missing-the-openssl-lib). Try this:
`CFLAGS="-I$(brew --prefix openssl)/include" \
LDFLAGS="-L$(brew --prefix openssl)/lib" \
pyenv install -v 3.6.3
`

**Comment by bright-pan** [comment]
i fix it ，using brew install pyenv

**Comment by sdcharle** [comment]
Ugh, I tried all these, still no joy.

**Comment by 0x783czar** [comment]
Getting the same issue.  Setting the CFLAGS and LDFLAGS doesn't appear to have any effect.

**Comment by johnlabarge** [comment]
I still have this issue as well .:/

**Comment by DavidGradwell** [comment]
I still have this issue as well.

Transcript as follows:

pyenv install 3.7.2
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.2.tar.xz...
-> https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
Installing Python-3.7.2...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 10.14.6 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/v_/p2zbbdxs7ln47_fdkb87g1y80000gn/T/python-build.20190731133344.39214
Results logged to /var/folders/v_/p2zbbdxs7ln47_fdkb87g1y80000gn/T/python-build.20190731133344.39214.log

Last 10 log lines:
  File "/var/folders/v_/p2zbbdxs7ln47_fdkb87g1y80000gn/T/tmpiebb8pfk/pip-18.1-py2.py3-none-any.whl/pip/_internal/cli/cmdoptions.py", line 20, in <module>
  File "/var/folders/v_/p2zbbdxs7ln47_fdkb87g1y80000gn/T/tmpiebb8pfk/pip-18.1-py2.py3-none-any.whl/pip/_internal/utils/hashes.py", line 10, in <module>
  File "/var/folders/v_/p2zbbdxs7ln47_fdkb87g1y80000gn/T/tmpiebb8pfk/pip-18.1-py2.py3-none-any.whl/pip/_internal/utils/misc.py", line 21, in <module>
  File "/var/folders/v_/p2zbbdxs7ln47_fdkb87g1y80000gn/T/tmpiebb8pfk/pip-18.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 35, in <module>
  File "/private/var/folders/v_/p2zbbdxs7ln47_fdkb87g1y80000gn/T/python-build.20190731133344.39214/Python-3.7.2/Lib/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "/private/var/folders/v_/p2zbbdxs7ln47_fdkb87g1y80000gn/T/python-build.20190731133344.39214/Python-3.7.2/Lib/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ModuleNotFoundError: No module named 'pyexpat'
make: *** [install] Error 1

**Comment by gpazo** [comment]
I resolved this by re-installing xcode command line tools: https://developer.apple.com/download/more/?=command%20line%20tools

**Comment by wpix** [comment]
> Like @gpazo, re-installing xcode command line tools fixed this for me.
> 
> Specifically:
> 
> ```
> sudo rm -rf /Library/Developer/CommandLineTools
> xcode-select --install
> ```

Tried every possible solution and this finally solved the problem. Thanks!
If this is the case for you, after reinstalling, no need to try other tricks from the building FAQ. Just run 
```shell
pyenv install X.X.X
```
