### ISSUE TITLE
../libexec/pyenv: No such file or directory

### ISSUE THREAD

**Issue by jules231** [pyenv/pyenv#1014]
I've installed pyenv both by manually cloning the repo described on the pytest github page and also by using the automatic installer. With both attempts I get the following whenever I try to use any pyenv command:
/c/Users/jukline/.pyenv/bin/pyenv: line 1: ../libexec/pyenv: No such file or directory

When I go directly to the libexec/pyenv directory and try to use pyenv commands, I am simply presented with the commands available.
![image](https://user-images.githubusercontent.com/32723951/31477127-1c8bc81a-aebf-11e7-9a50-f05745279df9.png)

I have seen the related post (pyenv/pyenv#332) and have verified my git config. There are two listings of core.symlinks, but my understanding is that the last one takes precedence.
$ git config --list
core.symlinks=false
core.autocrlf=false
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
credential.helper=manager
user.name=j
user.email=j@t.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=true
core.ignorecase=true
remote.origin.url=https://github.com/yyuu/pyenv.git
remote.origin.fetch=+refs/heads/master:refs/remotes/origin/master
branch.master.remote=origin
branch.master.merge=refs/heads/master

Anyone have ideas on how to resolve? Thanks

**Comment by fedorov** [comment]
Why don't you just open `~/.gitconfig` and remove `core.symlinks=false` to take the guessing out of the picture?

**Comment by evaldez89** [comment]
I tried this suggestion [#1195](https://github.com/pyenv/pyenv/issues/1195#issuecomment-410391523) and it worked nicely

**Comment by joshfriend** [comment]
Thanks for the suggestion @evaldez89. `pyenv` doesn't officially support windows so I'll be closing this issue for now.
