### ISSUE TITLE
PYENV_ROOT is assumed to exist by some, but pyenv-installer does not set it.

### ISSUE THREAD

**Issue by LunarLanding** [pyenv/pyenv#1016]
What the title says. This also makes the manual and automatic installation be at odds.
I was trying to make the setup below work when I hit this issue.
https://github.com/niligulmohar/pyenv-setup-fedora-python3

**Comment by blueyed** [comment]
Should get reported for https://github.com/pyenv/pyenv-installer then I guess?

**Comment by yyuu** [comment]
wrong repository to report issue
