### ISSUE TITLE
pyenv local --unset does nothing in sub directory

### ISSUE THREAD

**Issue by bendikro** [pyenv/pyenv#1018]
```
$ pwd
/home/user/test
$ pyenv version
2.7.14 (set by /home/user/.python-version)
$ pyenv local --unset
$ pyenv version
2.7.14 (set by /home/user/.python-version)
```

I realize that it's not meant to remove the .python-version in a parent directory, but maybe printing a message saying the local version cannot be unset from a sub directory?

**Comment by Sphinxs** [comment]
Some update ? this is not working in globa scope too

**Comment by chrahunt** [comment]
Hi @Sphinxs, if you're seeing some behavior that you think is a bug, please create a separate issue.
