### ISSUE TITLE
Set the pipenv venv automatically

### ISSUE THREAD

**Issue by bryant1410** [pyenv/pyenv#1020]
Apart from the fact that pipenv supports pyenv to install missing Python versions (#981), I think it should be cool if pyenv automatically calls `pipenv shell` if there's a Pipfile (or activates its environment).

The handling of the paths and the shell is not a responsibility for pipenv, so I think pyenv should do it.

**Comment by chrahunt** [comment]
Sorry if I'm misunderstanding, but this responsibility seems completely different than what pyenv currently does.

If you want some commands to run automatically or conveniently in your shell, then wouldn't an alias be better, or a tool like [direnv](https://direnv.net/) to automatically invoke and set environment variables?

**Comment by bryant1410** [comment]
I mean, pyenv already loads the python virtualenv when changing directory. As pipenv is now the recommended way to go, shouldn't it load its virtualenv when changing directory as well?

**Comment by chrahunt** [comment]
Ah, okay. The [`pyenv-virtualenv`](https://github.com/pyenv/pyenv-virtualenv) plugin is actually what does the virtualenv auto-loading. You could propose this over there?
