### ISSUE TITLE
Big Bug？

### ISSUE THREAD

**Issue by ProZoom** [pyenv/pyenv#1034]
MacOs  high Sierra
xcode9

[see bug Log](https://gist.github.com/ProZoom/f68b49f4c615133077c81b4c4cf9205b)

**Comment by blueyed** [comment]
```
if test "xupgrade" != "xno"  ; then \
		case upgrade in \
			upgrade) ensurepip="--upgrade" ;; \
			install|*) ensurepip="" ;; \
		esac; \
		 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi
Ignoring ensurepip failure: pip 9.0.1 requires SSL/TLS
```

**Comment by blueyed** [comment]
Looks like you are missing SSL libs/headers?!
There are similar issues already IIRC, so please try to search them and check the docs.
