### ISSUE TITLE
Python installed via pyenv NOT isolated from system Python on High Sierra

### ISSUE THREAD

**Issue by mrmachine** [pyenv/pyenv#1037]
On the latest High Sierra (10.13.1), with the latest `pyenv` (1.1.5) installed via Homebrew (everything updated/upgraded today), then installing 2.7.12 via pyenv, `python -m site` shows that `/Library/Python/2.7/site-packages` (and consequently, `/System/Library/Frameworks/Python/Versions/2.7/Extras/lib/python` and `/System/Library/Frameworks/Python/Versions/2.7/Extras/lib/python/PyObjC`) are in `sys.path`.

This means that `pip freeze` shows a tonne of old packages as already available in my 2.7.12 install and `python -c 'import setuptools; print setutools.__version__'` shows `18.5` (very old).

Now if I need to install anything that requires a newer version of setuptools or any of these other packages, I get errors because pip wants to first uninstall from the system site packages directory.

None of these was previously the case. I checked an older laptop which is also running High Sierra but which already had a version of Python installed by pyenv before upgrading to High Sierra, and the system `site-packages` directory is NOT in `sys.path`.

I've tried to debug this for a few hours on two different machines both running High Sierra and attempting to install Homebrew, pyenv and Python fresh, with help from #python on Freenode, but now it seems my only option is to abandon pyenv and use whatever version of Python is on offer by Homebrew, which also does not have this problem.

**Comment by Brawnd0** [comment]
I'm having a similar issue.  These upstream issues may be related.
https://bugs.python.org/issue4865
https://bugs.python.org/issue28440

**Comment by chrahunt** [comment]
Thanks @Brawnd0, this looks like it was fixed in 28440 (>=2.7.13). Please let us know if the updated version does not work for you as expected.
