### ISSUE TITLE
pyenv init - returns error

### ISSUE THREAD

**Issue by danieljaouen** [pyenv/pyenv#1042]
See below.  Note that I'm currently running fish shell.

```
○ pyenv init -
env: bash\r: No such file or directory
```

**Comment by danieljaouen** [comment]
This had to do with incorrect line endings in my working directory.  Not sure how it happened but I managed to fix it on my own.

Closing.

**Comment by myounus96** [comment]
> This had to do with incorrect line endings in my working directory. Not sure how it happened but I managed to fix it on my own.
> 
> Closing.

Can you guide how you solved it I am getting it on my ubuntu18.04.
@danieljaouen
