### ISSUE TITLE
Does not switch version MAC OSX

### ISSUE THREAD

**Issue by shierro** [pyenv/pyenv#1044]
Hi! I'm kind of new to python and I hope you can help me with my issue.

OS: OSX - 10.12.6

I want to install the latest version using this tool so I installed through homebrew.
```
$ brew install pyenv
```
Then install py 3.6.3 and 3.5.4 & rehash
```
$ pyenv install 3.6.3
$ pyenv install 3.5.4
$ pyenv rehash
```
Switch to 3.6.3
```
$ pyenv global 3.6.3
```
Then If I run `pyenv versions` i see 
<img width="642" alt="screen shot 2017-11-22 at 8 06 29 pm" src="https://user-images.githubusercontent.com/12129589/33126779-c0df11b6-cfc0-11e7-9239-faede763f487.png">

But if I show version or run python, i get this
<img width="507" alt="screen shot 2017-11-22 at 8 08 07 pm" src="https://user-images.githubusercontent.com/12129589/33126836-fa334676-cfc0-11e7-8c4b-1ef469c1996f.png">
 
any idea why this happens?
Thanks in advance!

**Comment by joshfriend** [comment]
You probably did not remember to add the required `pyenv init` to your shell config.

https://github.com/pyenv/pyenv#homebrew-on-mac-os-x

Homebrew no longer prompts you to do this after installing, because reasons 😕

**Comment by shierro** [comment]
ah! you're right. i assumed the link you provided was the 1st line after installation. 

Thanks for nailing it down for me!
