### ISSUE TITLE
Framework Build fails for 2.7.14 on macOS 10.13.1

### ISSUE THREAD

**Issue by FlorianKoegler** [pyenv/pyenv#1045]
Pyenv appears unable to correctly install a framework version of Python for 2.7.14 and 2.7.13, on macOS 10.13.1. However the same works for 3.6.3.

After installing Pyenv and Virtualenv with Homebrew, the following commands install a Pyenv for version X.X.X (i.e. 2.7.14 or 3.6.3) without errors, create a Virtualenv and install Matplotlib (which requires a framework build for using Pyplot).
```
$ env PYTHON_CONFIGURE_OPTS="--enable-framework" CFLAGS="-I$(brew --prefix openssl)/include" LDFLAGS="-L$(brew --prefix openssl)/lib" pyenv install X.X.X
$ pyenv virtualenv X.X.X testenv
$ pyenv activate testenv
$ pip install numpy matplotlib
```

Now if pyplot is imported, this raises an error for 2.7.13 and 2.7.14, but works as intended for 3.6.3: 
```
$ python
>> import matplotlib.pyplot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/florian/.pyenv/versions/v2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 113, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/florian/.pyenv/versions/v2/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/Users/florian/.pyenv/versions/v2/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 19, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
```

I am unsure if this is possibly a issue with Python itself or something else?

**Comment by gzagatti** [comment]
I am experiencing the same problem. `pyenv` won't allow me to install python with the `--enable-framework` flag on. The only workaround that I found is to install `conda` which install `python` with the framework on. This is not ideal, as I am using a package manager to manage another package manager. 

I needed python with framework to use `YouCompleteMe` with vim.

**Comment by programus** [comment]
Use the `pythonw` command instead might solve this problem. 
I had the same problem for `python`, while `pythonw` works good for me. 

```
$ pythonw
Python 2.7.10 (default, Jul 15 2017, 17:16:57)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> X = np.arange(0., 7., .1)
>>> Y = np.sin(X)
>>> plt.plot(X, Y)
[<matplotlib.lines.Line2D object at 0x10bd2ffd0>]
>>> plt.show()
```

**Comment by programus** [comment]
Use `pythonw` instead of `python` would solve this problem. At least solved my problem. 

```
$ ./pythonw
Python 2.7.14 (default, Mar  1 2018, 23:37:04)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> X = np.arange(0, 7, .1)
>>> Y = np.sin(X)
>>> plt.plot(X, Y)
[<matplotlib.lines.Line2D object at 0x10ac879d0>]
>>> plt.show()
```

**Comment by FlorianKoegler** [comment]
@programus I received the notification for your previous deleted answer via mail, where the `pythonw` output shows Version 2.7.10... it looked like you called the built-in version of Python that comes with macOS. 🙃
Is this now definitely the one installed through pyenv?

I personally moved from Homebrew to Nix, which works right out of the box and provides even better abilities to use separate environments for different projects.
So I cannot confirm your proposed solution.

**Comment by programus** [comment]
@FlorianKoegler Yes, this one is the one installed by pyenv. I ran it from the `bin` directory, so I added a `./` before the command. 

But, I tried just `python` later and it works good also. So, to be honest, I am confused now. 
I will try more and would get back if I made anything clearer.

**Comment by FlorianKoegler** [comment]
Okay, this is interesting.

The Python 2.7.10 that comes with macOS actually has Numpy 1.14.0 and Matplotlib 2.1.2 already installed, so maybe check if you're importing the right side-packages?

**Comment by andrew-christianson** [comment]
@programus might be a typo in `PYTHON_CONFIGURE_OPS` (should be `.._OPTS`) ?
