### ISSUE TITLE
844 Segmentation fault: 11  "$PYENV_COMMAND_PATH" "$@

### ISSUE THREAD

**Issue by Dr8g0n** [pyenv/pyenv#1048]
Keep getting below error when using pip install

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
```

bash-3.2$ pip install --upgrade google-api-python-client
/usr/local/Cellar/pyenv/1.1.5/pyenv.d/exec/pip-rehash/pip: line 20:  2844 Segmentation fault: 11  "$PYENV_COMMAND_PATH" "$@"
bash-3.2$

**Comment by native-api** [comment]
`pyenv` is a set of `bash` scripts. A segmentation fault means a fault at C level. So, not `pyenv`-related.

**Comment by apanzerj** [comment]
I'm getting this too but we can't find any solution. @Dr8g0n did you ever get this fixed? 

Max OS High Sierra

pyEnv 1.2.7

**Comment by DevneyHamilton** [comment]
We had to make sure the python version in `pip --version` matched the python version we had installed. We used pyenv, with `pyenv local 3.6.4` where 3.6.4 is the python version.

**Comment by bittudalal42** [comment]
> We had to make sure the python version in `pip --version` matched the python version we had installed. We used pyenv, with `pyenv local 3.6.4` where 3.6.4 is the python version.
And how to correct that ?

**Comment by Shobuj47** [comment]
I am getting the same error. I have installed the python 3.6.9 using below command: 
`pyenv install 3.6.9`
Then I have created a virtualenv :
`pyenv virtualenv 3.6.9 test-env`
I have activated the virtualenv:
`pyenv activate test-env`
Finally I have executed : 
`pip --version`
Then I have received the error: 
`~/.pyenv/pyenv.d/exec/pip-rehash/pip: line 20: 59797 Segmentation fault      (core dumped) "$PYENV_COMMAND_PATH" "$@"` 

I am using "Ubuntu 22.04.2 LTS" as my host machine and "pyenv-v2.3.25"

**Comment by native-api** [comment]
Since 3.6 is EOL, try using the last release in that line, 3.6.15 (or just "`3.6`", to use the new [auto-resolution feature](https://github.com/pyenv/pyenv#prefix-auto-resolution-to-the-latest-version)): it [has some user-provided patches that add extended support for some new environments](https://github.com/pyenv/pyenv#python-versions-with-extended-support).

**Comment by native-api** [comment]
In other tickets, Segmentation faults happened for MacOS users when they had migrated a Homebrew installation onto a new major MacOS version which it wasn't compatible with (each major MacOS release gets its own version of Homebrew libraries).

In this case, one needs to reinstall Homebrew, then reinstall all Pyenv-managed Python versions so that they are rebuilt against the new libs.

**Comment by Shobuj47** [comment]
The issue was solved after upgrading the python version 3.6.15.

**Comment by saad12150** [comment]
> In other tickets, Segmentation faults happened for MacOS users when they had migrated a Homebrew installation onto a new major MacOS version which it wasn't compatible with (each major MacOS release gets its own build of Homebrew libraries).
> 
> In this case, one needs to reinstall Homebrew, then reinstall all Pyenv-managed Python versions so that they are rebuilt against the new libs.

Had same issue when using pip to install any package, followed same steps 

1. Removed Homebrew completely from my Macbook M1
2. Installed Homebrew again
3. Reisntall pyenv
4. Reinstall any python version you need

and pip install should work as normal now. It could be because I recently updated my mac to 15.0.1

**Comment by rhinck** [comment]
> 1. Removed Homebrew completely from my Macbook M1
> 2. Installed Homebrew again
> 3. Reisntall pyenv
> 4. Reinstall any python version you need
> 
> and pip install should work as normal now. It could be because I recently updated my mac to 15.0.1

These steps worked for me when I ran into the same issue

**Comment by leportella** [comment]
Just FYI I just installed homebrew, pyenv and pyenv-virtualenv and still got this error. All in a space of 2 hours

**Comment by saad-edgedesign** [comment]
> Just FYI I just installed homebrew, pyenv and pyenv-virtualenv and still got this error. All in a space of 2 hours

@leportella  Can you confirm what macos version are you on? And could you try using pyenv and pip install in a directly without using virtualenv? And have you reinstalled python version you are using?

**Comment by leportella** [comment]
@saad-edgedesign  I just confirmed I was not using virtualenv and still getting the issue. I am on Sequoia 15.0.1 (formatted yesterday, installing things today). I did:

```
➜  ~ pyenv virtualenv 3.10 linkedin
➜  ~ pyenv activate linkedin
(linkedin) ➜  ~ which python
/Users/leportella/.pyenv/shims/python
(linkedin) ➜  ~ python --version
Python 3.10.15
```

then I ran `python -m pip install Django` and got the error.

I just removed Pyenv and I am updating/upgrading brew before trying again. I'll report back :)

**Comment by leportella** [comment]
Yeah, here's what I have:

```
➜  ~ python --version
Python 3.10.15
➜  ~ pyenv versions
  system
* 3.10.15 (set by /Users/leportella/.python-version)
➜  ~ python -m pip install Django
[1]    79419 segmentation fault  python -m pip install Django
➜  ~ pip install Django
/opt/homebrew/Cellar/pyenv/2.4.16/pyenv.d/exec/pip-rehash/pip: line 20: 79543 Segmentation fault: 11  "$PYENV_COMMAND_PATH" "$@"
➜  ~
```

**Comment by saad12150** [comment]
@leportella Actually updating/upgrading brew won't work in this situation, brew needs to be completely removed from the system (incuding all its directories) and pyenv and any of its installed python versions.

Try following these to completely get rid of pyenv and then brew
1. https://github.com/pyenv/pyenv?tab=readme-ov-file#uninstalling-pyenv
2. https://mac.install.guide/homebrew/5

After this install everything from scratch and hopefully it should work.

**Comment by leportella** [comment]
@saad-edgedesign  what I don't understand is how can I have just installed brew and still need to remove it completely and then install everything again. It makes no sense to me

**Comment by leportella** [comment]
I did remove everything and it worked but it makes no sense in my head. In the past few hours I did:

install homebrew > install pyenv > try pyenv > error > uninstall pyenv > uninstall homebrew > install homevbrew > install pyenv > works

**Comment by saad12150** [comment]
@leportella Glad to hear that it worked! While I'm not entirely certain of the specifics, it likely has to do with the C/C++ files or libraries that are installed with brew.

**Comment by aviau** [comment]
Just got the same error here. Uninstalling homebrew would be a pretty big deal for me as I have a lot of packages installed. I wish there was another way to fix this.

**Comment by leportella** [comment]
@aviau as far as I understand, uninstalling homebrew won't uninstall the packages you already have installed, so it shouldn't affect anything you have, just your ability to add new packages while you don't have homebrew installed

**Comment by aviau** [comment]
The homebrew uninstaller disagrees with that:
```
Are you sure you want to uninstall Homebrew? This will remove your installed packages! [y/N] y
```

**Comment by native-api** [comment]
> Just got the same error here, also using pants. Uninstalling homebrew would be a pretty big deal for me as I have a lot of packages installed. I wish there was another way to fix this.

```
brew list --installed-on-request >packages.lst
<...>
brew install $(cat packages.lst)
```

**Comment by pmontepagano** [comment]
I was having the same issue since upgrading to MacOS 15.0.1 and trying to install new Python executables (`pyenv install ...`).

The issue was that I had `openssl@1.1` with brew, and pyenv was selecting that version of openssl when building Python.

Uninstalling openssl@1.1 fixed the issue:

```
brew uninstall openssl@1.1
```

**Comment by akchaudhary6532** [comment]
I cannot uninstall openssl@1.1 since it is being used by `mongodb-community@5.0`. Is there any other way?

**Comment by FCncdn** [comment]
After upgrading to MacOS 15.1, I also encountered this issue. I resolved it by using the following command:

`CC=clang pyenv install 3.10`

Referencing a previous issue: https://github.com/pyenv/pyenv-virtualenv/issues/410#issuecomment-1546584374

**Comment by VamoBao** [comment]
> @leportella Actually updating/upgrading brew won't work in this situation, brew needs to be completely removed from the system (incuding all its directories) and pyenv and any of its installed python versions.
> 
> Try following these to completely get rid of pyenv and then brew
> 
> 1. https://github.com/pyenv/pyenv?tab=readme-ov-file#uninstalling-pyenv
> 2. https://mac.install.guide/homebrew/5
> 
> After this install everything from scratch and hopefully it should work.

that is work for me,thanks
remove pyenv root folder,then re-install pyenv by homebrew,it down

**Comment by markcallen** [comment]
> After upgrading to MacOS 15.1, I also encountered this issue. I resolved it by using the following command:
> 
> `CC=clang pyenv install 3.10`
> 
> Referencing a previous issue: [pyenv/pyenv-virtualenv#410 (comment)](https://github.com/pyenv/pyenv-virtualenv/issues/410#issuecomment-1546584374)

Had the same issue using Homebrew on a Mac running 15.0.1.  

Uninstalled the 3.10.15 I had with pyenv.  Use the above command to install 3.10 and now pip works.

````
pyenv uninstall 3.10.15
CC=clang pyenv install 3.10
pip install -r requirements.txt
````

Success.

**Comment by qianzhiyuan** [comment]
> > In other tickets, Segmentation faults happened for MacOS users when they had migrated a Homebrew installation onto a new major MacOS version which it wasn't compatible with (each major MacOS release gets its own build of Homebrew libraries).
> > In this case, one needs to reinstall Homebrew, then reinstall all Pyenv-managed Python versions so that they are rebuilt against the new libs.
> 
> @native-api Had same issue when using pip to install any package, followed same steps
> 
> 1. Removed Homebrew completely from my Macbook M1
> 2. Installed Homebrew again
> 3. Reisntall pyenv
> 4. Reinstall any python version you need
> 
> and pip install should work as normal now. It could be because I recently updated my mac to 15.0.1

This is great, it solved my problem. Also on M1, upgraded to version 15.

**Comment by sanjeethboddi** [comment]
> > In other tickets, Segmentation faults happened for MacOS users when they had migrated a Homebrew installation onto a new major MacOS version which it wasn't compatible with (each major MacOS release gets its own build of Homebrew libraries).
> > In this case, one needs to reinstall Homebrew, then reinstall all Pyenv-managed Python versions so that they are rebuilt against the new libs.
> 
> @native-api Had same issue when using pip to install any package, followed same steps
> 
> 1. Removed Homebrew completely from my Macbook M1
> 2. Installed Homebrew again
> 3. Reisntall pyenv
> 4. Reinstall any python version you need
> 
> and pip install should work as normal now. It could be because I recently updated my mac to 15.0.1

This worked for me. Not sure why.

**Comment by beala** [comment]
> After upgrading to MacOS 15.1, I also encountered this issue. I resolved it by using the following command:
> 
> `CC=clang pyenv install 3.10`
> 
> Referencing a previous issue: [pyenv/pyenv-virtualenv#410 (comment)](https://github.com/pyenv/pyenv-virtualenv/issues/410#issuecomment-1546584374)

Unfortunately, this did not solve the problem for me, but reinstalling homebrew did. I'm on MacOS 15.2.

FWIW, the homebrew reinstall was a lot less painful that I thought it would be. Took me about 15 minutes. But I also don't have an extensive list of homebrew packages installed.

**Comment by jelther** [comment]
> > After upgrading to MacOS 15.1, I also encountered this issue. I resolved it by using the following command:
> > `CC=clang pyenv install 3.10`
> > Referencing a previous issue: [pyenv/pyenv-virtualenv#410 (comment)](https://github.com/pyenv/pyenv-virtualenv/issues/410#issuecomment-1546584374)
> 
> Had the same issue using Homebrew on a Mac running 15.0.1.
> 
> Uninstalled the 3.10.15 I had with pyenv. Use the above command to install 3.10 and now pip works.
> 
> ```
> pyenv uninstall 3.10.15
> CC=clang pyenv install 3.10
> pip install -r requirements.txt
> ```
> 
> Success.

What worked for me:

- Uninstall homebrew (save all packages that you have by running `brew bundle dump`
- Remove folders that homebrew might have left behind (it will show to you on Terminal)
- Install homebrew by using your dump file `brew bundle install`
- Remove all installations that you have from pyenv using `rm -rf $(pyenv root)`
- Reinstall your python version (in my case, it was 3.10.16)
- Try installing your packages again

**Comment by Cayan** [comment]
> > > After upgrading to MacOS 15.1, I also encountered this issue. I resolved it by using the following command:
> > > `CC=clang pyenv install 3.10`
> > > Referencing a previous issue: [pyenv/pyenv-virtualenv#410 (comment)](https://github.com/pyenv/pyenv-virtualenv/issues/410#issuecomment-1546584374)
> > 
> > 
> > Had the same issue using Homebrew on a Mac running 15.0.1.
> > Uninstalled the 3.10.15 I had with pyenv. Use the above command to install 3.10 and now pip works.
> > ```
> > pyenv uninstall 3.10.15
> > CC=clang pyenv install 3.10
> > pip install -r requirements.txt
> > ```
> > 
> > 
> >     
> >   
> > Success.
> 
> What worked for me:
> 
> * Uninstall homebrew (save all packages that you have by running `brew bundle dump`
> * Remove folders that homebrew might have left behind (it will show to you on Terminal)
> * Install homebrew by using your dump file `brew bundle install`
> * Remove all installations that you have from pyenv using `rm -rf $(pyenv root)`
> * Reinstall your python version (in my case, it was 3.10.16)
> * Try installing your packages again
> 
> I'm using MacOS 15.x, Python 3.10.16

This solution worked for me

**Comment by PioCang** [comment]
> I was having the same issue since upgrading to MacOS 15.0.1 ...
> The issue was that I had `openssl@1.1` with brew, and pyenv was selecting that version of openssl when building Python.
> 
> Uninstalling openssl@1.1 fixed the issue:

I also had just upgraded, but to to MacOS 15.2.
Until that point, Pyenv installed by Homebrew worked on MacOS v12.x.y

Here's what worked for me.

```
brew uninstall openssl@1.1

pyenv virtualenv-delete <venv_name>
# It's important that you rebuild your Python executables
pyenv install <target_python_version>
pyenv virtualenv <target_python_version> <venvname>
```

**Comment by yeqianmen** [comment]
> > After upgrading to MacOS 15.1, I also encountered this issue. I resolved it by using the following command:
> > `CC=clang pyenv install 3.10`
> > Referencing a previous issue: [pyenv/pyenv-virtualenv#410 (comment)](https://github.com/pyenv/pyenv-virtualenv/issues/410#issuecomment-1546584374)
> 
> Had the same issue using Homebrew on a Mac running 15.0.1.
> 
> Uninstalled the 3.10.15 I had with pyenv. Use the above command to install 3.10 and now pip works.
> 
> ```
> pyenv uninstall 3.10.15
> CC=clang pyenv install 3.10
> pip install -r requirements.txt
> ```
> 
> Success.

thanks,it works for me
