### ISSUE TITLE
Wanting to add 3.7.0a3, but how to generate the hash?

### ISSUE THREAD

**Issue by kootenpv** [pyenv/pyenv#1052]
For the example change to version a2:

https://github.com/pyenv/pyenv/commit/7b9d1a40c2e05746330fabef7e3b93e1a552394d#diff-9285cd31a2e97dddfa194aced3612ba3

**Comment by yyuu** [comment]
It’s SHA256. Use sha256sum or something equivalent.

**Comment by joshfriend** [comment]
on mac, i use:

```sh
$ shasum -a 256 Python*
3432d3ddf97483339badda961f7d0564595460fee166dd8f106dc4201e68446e  Python-3.7.0a3.tar.xz
ef75398e6f978a4ead005b11d988ab2d871cf24afa4bdeef97fe09b506a76736  Python-3.7.0a3.tgz
```


also, 3.7.0a3 is added in 364fa7f
