### ISSUE TITLE
How to 'pip install' using pyenv

### ISSUE THREAD

**Issue by iceblu3710** [pyenv/pyenv#1054]
What is the proper procedure to install things when using pyenv?

I regularly use Python 2.7 and 3.6 and load different vmware virtual machines. I would love to just switch global versions whenever I want. My issue is if I install with `pip install -U package` sometimes it wants root which messes up the install.

What is the general package management procedure when using pyenv?

**Comment by blueyed** [comment]
> sometimes it wants root which messes up the install

Just don't use `sudo` / the root user then.. :)

Typically you should use virtualenvs for projects, and e.g. `pip install --user` or your package manager for tools to be installed globally (for your user).

**Comment by Chaaang** [comment]
pyenv local 3.6.3, and under current directory, `which pip` will be /Users/c/.pyenv/shims/pip. and all the pip installed package is under 3.6.3 environment

**Comment by iceblu3710** [comment]
Turns out my 3.6 install did not symlink `pip3 => pip` so when I was using `pip install -U package` it was a totally wrong everything. I went through all my `pipenv` versions and made sure `pip and python` pointed to their proper versions. Now switching versions works properly.

**Comment by joisonwk** [comment]
How to solve this problem, when I using the pip install any python libraries,  the error message all ways existed. Who has had the same problem?
Here are the error tips:
`Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2708, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pip==1.0`

**Comment by alecgerona** [comment]
For others who might stumble on this, restarting your terminal should let pyenv properly switch pips. Make sure to always run `which pip` and `which python` to checj.

**Comment by Issam-seghir** [comment]
i have problem when i use 

**in root path:**

`pyenv global 3.10`
`python --version` // 3.10

**in project path:** 

`pyenv local 3.9.6`
`python --version` //3.10
`pip install numpy` // installed in python 3.10/ site_package

**solution:**     use `sudo ` with every command in your project path:

` pyenv local 3.9.6`
`python --version `//3.10
`sudo  python --version` //3.9
`sudo pip install numpy` // installed in python 3.9/ site_package
this is work fine for me  💯
