### ISSUE TITLE
pyenv in zsh Autocomplete works wrong

### ISSUE THREAD

**Issue by C1tas** [pyenv/pyenv#1056]
after today brew update && upgrade

zsh 5.4.2 (x86_64-apple-darwin16.7.0)
in .zshrc
```
eval "$(pyenv init -)"
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
eval "$(pyenv virtualenv-init -)"
```

Autocomplete does not work

how can i fix it?

in mac pro 10.13.1

**Comment by C1tas** [comment]
i got that pyenv install by brew, but zsh do not auto load /usr/local/share/zsh/site-functions/pyenv.zsh

**Comment by henry0312** [comment]
I faced the same issue, too.

**Comment by Chaaang** [comment]
very badly, it should be work before,,and after I reinstall my whole OS,  the autocomplete doesn't work..AND I thought it might be something I did to my system, and I Install system again...what a sad story !

**Comment by C1tas** [comment]
@Chaaang just add "source /usr/local/share/zsh/site-functions/pyenv.zsh" in .zshrc can fix this problem

**Comment by Chaaang** [comment]
thanks @C1tas

**Comment by henry0312** [comment]
I found the cause in Homebrew and I'll fix.

**Comment by henry0312** [comment]
This issue has been solved.
