### ISSUE TITLE
All is normal,but pyenv can't change python version! 

### ISSUE THREAD

**Issue by hualidi123** [pyenv/pyenv#1057]
[root@rzx03 shims]# python -V 
Python 2.7.3
[root@rzx03 shims]# python verisons
python: can't open file 'verisons': [Errno 2] No such file or directory
[root@rzx03 shims]# python versions 
python: can't open file 'versions': [Errno 2] No such file or directory
[root@rzx03 shims]# pyenv versions
  system
* 2.7.3 (set by PYENV_VERSION environment variable)
  2.7.6
[root@rzx03 shims]# python -V 
Python 2.7.3
[root@rzx03 shims]# pyenv rehash
[root@rzx03 shims]# pyenv global 2.7.6
[root@rzx03 shims]# pyenv versions
  system
* 2.7.3 (set by PYENV_VERSION environment variable)
  2.7.6
[root@rzx03 shims]# python -V 
Python 2.7.3

picture upload failed! this is message of picture .help.
pvenv version 1.2.0

**Comment by yyuu** [comment]
You should find the meanung of normal first.

**Comment by hualidi123** [comment]
what's your mean？
