### ISSUE TITLE
pip nowhere to be found?

### ISSUE THREAD

**Issue by dieggsy** [pyenv/pyenv#1065]
I found a couple of old issues on this, but I think they were closed. I installed pyenv using the install script, but after doing `pyenv install 3.6.4`, the only `pip` command is the system python's pip. I think I tried `3.6.2` with the same results. This is on Manjaro Linux for whatever it's worth.

I ask cause I think this used to work for me.

**Comment by joshfriend** [comment]
https://github.com/pyenv/pyenv#choosing-the-python-version

**Comment by dieggsy** [comment]
@joshfriend you've linked to a section of the README that doesn't mention pip anywhere, and given no explanation, which isn't very helpful.

I think you're hinting at the fact that I should have switched to the correct python version - in fact, it was my mistake to omit that from the original bug report. I did `pyenv global 3.6.4`, and _after_ the correct python version is chosen, the pip corresponding to that python version is nowhere to be found. 

I didn't just start using pyenv (though I've admittedly not used python in some months), this problem only just started happening recently.

**Comment by dieggsy** [comment]
"Nowhere to be found" is probably too strong a wording, it's at least not on my PATH, and it used to be added automatically IIRC.

**Comment by dieggsy** [comment]
@joshfriend I apologize if i came across as a bit curt, wasn't my intention. The issue was apparently recently changing default shells and not initializing pyenv correctly, which led to an incorrect PATH.

In any case, thanks for pointing me to the README, as it led me to more closely examine what my PATH should be and what changed about my setup. :)
