### ISSUE TITLE
RFE: pyenv update should regenerate shims unconditionally

### ISSUE THREAD

**Issue by PAStheLoD** [pyenv/pyenv#1068]
I've bumped into the issue raised in #957, and the root cause seems to be that pyenv update does not regenerate the shims, and eventually incompatible shims are left intact.

**Comment by yyuu** [comment]
pyenv update is not a part of core pyenv. go https://github.com/pyenv/pyenv-update

**Comment by PAStheLoD** [comment]
Issues are disabled on that repo, so I was not able to file it there.

**Comment by ksze** [comment]
Yep, issues are disabled on that repo. @yyuu Please enable issues on the pyenv-update repo.

**Comment by ssbarnea** [comment]
Why is is this bug closed and the issue tracker disabled on pyenv-update? I would argue that fixing shims should be part of the main product itself and not an external (unsupported) plugin.

Clearly the upgrade from 1.2.10 to 1.2.11 did broke lots of shims that remained with old path and there is no documentation on how to fix. In order to provide a better UX we should assure that this does not happen, without asking users the install extra software to fix it.

**Comment by ssbarnea** [comment]
Even after running pyenv update I still have a broken python because of hardcoded path:
```
/Users/ssbarnea/.pyenv/shims/python: line 21: /usr/local/Cellar/pyenv/1.2.10/libexec/pyenv: No such file or directory
```

**Comment by PAStheLoD** [comment]
Wouldn't Pipenv work for you? I know it's not as convenient as simply using python everywhere and getting the right version/env, but on the upside it's well maintained and handles a lot more than just envs.

**Comment by yyuu** [comment]
Please open PR if you need something to be fixed in it. Clearly we don't always have enough resource to make everything complete and perfect. Just arguing does't help much.

**Comment by ssbarnea** [comment]
Sorted the issue locally doing a `pyenv rehash` but looking at the code inside it makes me wonder why rehashing is not done automatically when the import line fails. It would be easy to do a try/catch approach and attempt a rehash when the path gots broken.

**Comment by ssbarnea** [comment]
@PAStheLoD I really do not understand how pipenv could ever help here, my primary use of pyenv is to install additional python interpreters that are not available natively on the platforms that I use for testing, with tox in 99% of the cases. I really doubt pipenv address that.

**Comment by ssbarnea** [comment]
Can we first make this ticket open, so we can raise PRs to fix it? With it fixed it sends a wrong message to users, making them believe that this issue no longer exists or a fix is not desired.

As every other month I re-encounter this bug, I will probably endup making a PR to fix it.

**Comment by trollfred** [comment]
This is closed, yet it is still not fixed 😕

**Comment by scharfmn** [comment]
Still happens
