### ISSUE TITLE
Create release tag which includes Python 3.6.4 (for Homebrew, etc.)

### ISSUE THREAD

**Issue by jalessio** [pyenv/pyenv#1071]
pyenv added Python 3.6.4 in PR https://github.com/pyenv/pyenv/pull/1058 but there hasn't been a release tagged since that PR, so as far as I can tell it's difficult to integrate into a new Homebrew formula without a git tag in this repo.

I'd like to submit a PR to update this file:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/pyenv.rb

In #1064 @codeblooded ran into a similar issue and the suggestion was to `git pull` the pyenv repo, but if you've installed via Homebrew then that's not an option.

Could you tag / release a new version of pyenv which includes Python 3.6.4? Thank you!

**Comment by joshfriend** [comment]
Tagged b704c4242cc7370ddc6266b019caaaf53ab0dfcd

Homebrew/homebrew-core#22702

sorry for the wait
