### ISSUE TITLE
Creating environment using Intel® Distribution for Python

### ISSUE THREAD

**Issue by IamGianluca** [pyenv/pyenv#1072]
I was wondering if was possible to create a virtual environment using [Intel Distribution for Python](https://software.intel.com/en-us/distribution-for-python?cid=sem43700016247584407&intel_term=intel%20python%20distribution&gclid=EAIaIQobChMItoeIws3O2AIVF41-Ch1mxAEuEAAYASAAEgJ_tPD_BwE&gclsrc=aw.ds). I've installed `intelpython3` on my Ubuntu machine using `apt-get`, but I don't seem to find a way to create a new environment using `pyenv`.

**Comment by joshfriend** [comment]
pyenv isn't a tool for creating virtualenvs, it just installs python versions. Intel's python distribution is anaconda based, so regular [`conda create`](https://conda.io/docs/user-guide/tasks/manage-environments.html) commands should work as you would expect.

**Comment by IamGianluca** [comment]
Right, I'm using it in combination with the `virtualenvwrapper` plugin, hence the confusion. I'm going to ask there. Thanks for your reply Josh.
