### ISSUE TITLE
Provide argument which specifies the subname of the virtual environment folder instead of automatic hashname

### ISSUE THREAD

**Issue by rishatsharafiev** [pyenv/pyenv#1075]
Hello.
Assume that we in folder `~/dev/project/dummy`. let's create virtual environment with command and argument `pipenv shell --name=subname`. It should create path `~/.local/share/virtualenvs/dummy-subname`. Else it just uses old mechanism.
Thank you.

**Comment by joshfriend** [comment]
I think you are looking for [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv). pyenv by itself does not have anything to do with creation or management of virtualenvs.
