### ISSUE TITLE
PYENV_ROOT Install by Homebrew

### ISSUE THREAD

**Issue by Voleking** [pyenv/pyenv#1079]
I install pyenv by Homebrew `brew install pyenv` and I found `PYENV_ROOT` is `/usr/local/Cellar/pyenv/1.0.10_1`. 
However everytime I run `brew cleanup` I got `Removing: /usr/local/Cellar/pyenv/1.0.10_1...`, so I needed to reinstall python via pyenv!
I wander if there is any way change `PYENV_ROOT` installed by Homebrew.

`macOS: 10.13.2`
`pyenv: 1.2.1`
`Homebrew: 1.5.0`

**Comment by shawnbutts** [comment]
I don't see this issue on my setup.

/usr/local/Cellar/pyenv/1.0.10_1 seems to point to an older version that 1.2.1 that you have listed.  For me, `PYENV_ROOT` is pointing to `/usr/local/Cellar/pyenv/1.2.1`

Perhaps `PYENV_ROOT` is pointing to an old version that brew is removing.

**Comment by Voleking** [comment]
@shawnbutts Thx, I checked my .zshenv, that's all my faults.
