### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by moonso** [pyenv/pyenv#108]
Hello!

when i do 'pyenv install 2.7.6' I get a Import error that sqlite3 can not be found:

```
$pyenv install 2.7.6
Downloading Python-2.7.6.tgz...
-> http://yyuu.github.io/pythons/1d8728eb0dfcac72a0fd99c17ec7f386
Installing Python-2.7.6...

BUILD FAILED

Inspect or clean up the working tree at /tmp/python-build.20140129094951.27897
Results logged to /tmp/python-build.20140129094951.27897.log

Last 10 log lines:
    from dbapi2 import *
  File "/home/mans.magnusson/.pyenv/versions/2.7.6/lib/python2.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3

The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?

Please consult to the Wiki page to fix the problem.
https://github.com/yyuu/pyenv/wiki/Common-build-problems
```

But when i run the python interpreter there is no problem with this module:

```
$ python
Python 2.6.6 (r266:84292, Jul 10 2013, 22:48:45) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> from _sqlite3 import *
>>> 
```

Do you have any idea what could be the problem?

Best regards,

Måns Magnusson

**Comment by yaiba** [comment]
Hello, 
I have the same issue on my mac 10.11.6, and i goolged some answers but none of them work for mac, the  "Common build problem" have nothing to say about sqlite, and i tried set the same flags metioned in the "Common build problem/ssl" section and fix it.
Just for people who have same issue like me.

**Comment by cleocn** [comment]
run this:

CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install -v 3.4.7

in mac . it's work for me.
enjoy.

**Comment by excenter** [comment]
https://gist.github.com/excenter/48bb9b10aa77406b83c7752d79eb0b7d

**Comment by joeb1415** [comment]
https://github.com/pyenv/pyenv/issues/692#issuecomment-485632241

This link finally fixed it for me.
