### ISSUE TITLE
pyenv versions Warning: no Python detected on the system

### ISSUE THREAD

**Issue by camJWS** [pyenv/pyenv#1099]
Could I ask how, when typing `pyenv versions` pyenv gives me the warning:
`Warning: no Python detected on the system`
The /System/Library/Frameworks system python is still present, (and I imagine SIP would prevent its deletion anyway, no?)
I assume Pyenv must refer to a symlink of the system python somewhere, and if it is missing, Pyenv would give this warning. Is this correct?
If so, how would I go about restoring the normal response of 
`* system`
as is output when no other pyenv python versions are installed?
(Running MacOS10.13.3)
Thanks

**Comment by yyuu** [comment]
The meaning of the system version in pyenv is that “let pyenv to look up python executables from PATH”. 

pyenv can find the “system” as in the standard manner of PATH look up. If the system python was somehow not appeared in PATH, it will show the warning. Since system configuration is totally vary per systems, pyenv cannot deal with non-standard installations.

So the answer is, to restore system version working, put system python executable somewhere in PATH, or add system python’s location to PATH

**Comment by camJWS** [comment]
Thanks very much yyuu, problem sorted.

**Comment by DeT0m** [comment]
Hi, I have simillar problem. My fresh installed pyenv can't find system python with "pyenv versions"
`Warning: no Python detected on the system
`
But i have system Python in /usr/bin/python3 and also it is in my PATH
`➜ echo $PATH
/home/detom/.pyenv/shims:/home/detom/.pyenv/bin:/home/detom/.pyenv/shims:/home/detom/.pyenv/bin:/home/detom/.pyenv/shims:/home/detom/.pyenv/bin:/usr/bin/python3:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
`

**Comment by arkn98** [comment]
@DeT0m Currently `pyenv` only looks for `python` in the system PATH (see [here](https://github.com/pyenv/pyenv/blob/ae4d48932f49c77872ab10a1dbf29080fdda2df2/libexec/pyenv-versions#L105)).

If you're on Ubuntu, you can install the `python-is-python3` package using `apt` (maintained by the Ubuntu Core Developers; [link](https://packages.ubuntu.com/focal/python-is-python3)), which basically symlinks `/usr/bin/python` to `python3`. My `pyenv` properly detected the system version after installing this.

**Comment by dmig-alarstudios** [comment]
I'd reopen this because Ubuntu 20.xx doesn't have Python 2 installed by default and the error message `Warning: no Python detected on the system` is totally confusing.

**Comment by logicalbhanu** [comment]
I am using Linux Mint 20 which is also based on ubuntu 20.xx so to solve this issue I just add the binary /usr/bin/python3 to my terminal path in ~/.bashrc file via this command
echo 'export PATH="$PATH:/usr/bin/python3"' >> ~/.bashrc
try this.
