### ISSUE TITLE
Issue when I try to install the latest anaconda3 by pyenv

### ISSUE THREAD

**Issue by masafumiendo** [pyenv/pyenv#1105]
How to solve this situation?

I tried to install `anaconda3-4.4.0` by pyenv, but I cannot install it and my terminal shows below

```Downloading Anaconda3-4.4.0-Linux-x86_64.sh...
-> https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh
error: failed to download Anaconda3-4.4.0-Linux-x86_64.sh

BUILD FAILED (Ubuntu 16.04 using python-build 1.1.1-7-ge93b170)
```

I cannot understand the reason why some problems happened since there are no suggestions to solve this problem.

**Comment by yyuu** [comment]
> -> https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh
> error: failed to download Anaconda3-4.4.0-Linux-x86_64.sh

All I can tell is it somehow failed to download the archive. Generally speaking it's some issue in your networking environment. Please try downloading the file by your hand and see how it goes.
