### ISSUE TITLE
pyenv does not work

### ISSUE THREAD

**Issue by EvergreenHZ** [pyenv/pyenv#1108]
Actually, I used it yesterday and it worked fine. But I don't know why it doesn't work now. see below:

```
 ~$ ls .pyenv
bin           COMMANDS.md  CONDUCT.md  LICENSE   plugins  README.md  src                  test
CHANGELOG.md  completions  libexec     Makefile  pyenv.d  shims      terminal_output.png  versions
~$ which pyenv
~$ pyenv 
No command 'pyenv' found, did you mean:
 Command 'p7env' from package 'libnss3-tools' (universe)
 Command 'pyvenv' from package 'python3-venv' (universe)
pyenv: command not found
~$ cat .bash_profile 
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
```

**Comment by joshfriend** [comment]
Can you verify that you have added the `PYENV_ROOT` and `pyenv init` shell configuration to the correct profile for the shell you are using? See step 2 [here](https://github.com/pyenv/pyenv#basic-github-checkout). Depending on your OS and shell, you might need to put it somewhere other than `~/.bash_profile`

**Comment by EvergreenHZ** [comment]
Thank you for your time. I used it on Arch before and everything works fine. I just switched to Ubuntu and forgot to change the .bash_profile. But now it works fine.
