### ISSUE TITLE
pyenv local / global doesn't work on MacOS High Sierra

### ISSUE THREAD

**Issue by LHPavel** [pyenv/pyenv#1109]
pyenv version: 1.2.2
installed via homebrew
also tried to `brew remove python --purge` with no luck

Expected behavior: `pyenv [global or local] 2.7.5` changes python version to 2.7.5 (globally or locally)
Actual bahavior: Python version remains the same (system installed version)

```bash
XXX-MacBook-Pro:website YYY$ pyenv versions
  system
* 2.7.5 (set by /Users/YYY/dev/lh/website/.python-version)
XXX-MacBook-Pro:website YYY$ pyenv global 2.7.5
XXX-MacBook-Pro:website YYY$ pyenv global
2.7.5
XXX-MacBook-Pro:website YYY$ python -V
Python 2.7.10
XXX-MacBook-Pro:website YYY$ pyenv local 2.7.5
XXX-MacBook-Pro:website YYY$ pyenv local
2.7.5
XXX-MacBook-Pro:website YYY$ python -V
Python 2.7.10
```

When I add the executable to PATH manually, python works as expected:
```bash
XXX-MacBook-Pro:website YYY$ PATH="/Users/YYY/.pyenv/versions/2.7.5/bin/:${PATH}" 
XXX-MacBook-Pro:website YYY$ export PATH
XXX-MacBook-Pro:website YYY$ python --version
Python 2.7.5
```

**Comment by joshfriend** [comment]
Please make sure you have followed all of the [installation instructions](https://github.com/pyenv/pyenv#homebrew-on-mac-os-x) when installing via homebrew. Most people forget the step of adding `pyenv init` to their shell
