### ISSUE TITLE
Check for dependencies before attempting download/install

### ISSUE THREAD

**Issue by xerebz** [pyenv/pyenv#1114]
Pyenv would be more user friendly if it would detect missing dependencies before attempting an install. The functionality would be similar to a ./configure responding with missing deps before a make.

The current workflow for setting up pyenv on a new box:
Attempt pyenv install 3.6.4
Wait 5 minutes for the download and most of the install to complete.
Fail because of missing dependencies. Output shows build failed with link to the FAQ and missing dependencies listed.
Visit FAQ, install dependencies, start download and install over again from the beginning.

**Comment by yyuu** [comment]
In general pyenv is a tool for developers, not for users. And, they should have responsibility to maintain their systems for their purpose of development. I want to keep pyenv's core solid and simple as much as possible. In reality, pyenv (precisely, python-build plugin) is just invoking `./configure` script of CPython as usual CPython build and you can see the output if you want with supplying `-v` to `pyenv install`.

BTW, there's some plugin of pyenv https://github.com/pyenv/pyenv-doctor which tries to check if the system has dependencies to build Python variants. If you prefer, you can invoke similar as a `before_install` hook script of `pyenv install`. See also https://github.com/pyenv/pyenv/wiki/Authoring-plugins#pyenv-hooks

**Comment by joshfriend** [comment]
Given all the ways that you could install the required components (from homebrew, source, etc) and the various locations that those dependencies could be installed to, I think it would be very impractical to try to have pyenv decide how and where to install things like OpenSSL, zlib, etc.
