### ISSUE TITLE
pyenv blocks access to pip install into system python site lib

### ISSUE THREAD

**Issue by johnesher** [pyenv/pyenv#1119]
Having installed pyenv 1.2.2 in Ubuntu 16.04, I now wish to pip install a package into the system python, ie not into the venv.

I can run the system python with "python3" (when using a terminal outside a venv).

When I try to pip install, outside a venv, I get 
pyenv: pip3: command not found

The `pip3' command exists in these Python versions:
  3.6.4
  3.6.4/envs/venv-xxx2
  venv-xxx2

Surely this is not intended behaviour when not within a venv?

**Comment by joshfriend** [comment]
If your system python does not have a `pip3` command, pyenv will not automatically make one for you. virtualenv is probably creating that one for you. Try just using `pip` instead
