### ISSUE TITLE
Pyenv can't find the pip command but it's installed

### ISSUE THREAD

**Issue by binarykitchen** [pyenv/pyenv#1122]
$ python --version
Python 2.7.10

$ python ~/Downloads/get-pip.py
Requirement already up-to-date: pip in /Library/Python/2.7/site-packages

$ which pip
/Users/michael-heuberger/.pyenv/shims/pip

$ pip
pyenv: pip: command not found

The `pip' command exists in these Python versions:
  2.7.10

Hmmm, what is wrong here?

**Comment by joshfriend** [comment]
1. You installed pip into your system python (`/Library/Python`)
2. Pyenv automatically installs pip for you so this should be unnecessary
3. The exception to the above is system python. In this case, all pythons since 2.7.9 have [the `ensurepip` module](https://docs.python.org/2/library/ensurepip.html), which you can use to get Pip instead of the `get-pip.py` script
4. You probably didn't finish setting up pyenv. Please read through the [installation steps](https://github.com/pyenv/pyenv#installation). Like many other people, you probably are missing the step of adding `pyenv init` to your shell

**Comment by binarykitchen** [comment]
ok thanks, already had it ensured fine:

```
$ python -m ensurepip
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): setuptools in /Users/michael-heuberger/Library/Python/2.7/lib/python/site-packages
Requirement already satisfied (use --upgrade to upgrade): pip in /Library/Python/2.7/site-packages
```

and it's in my .zshenv

```
$ cat .zshenv
#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export PATH="$PATH:node_modules/.bin"

# needed for non interactive sessions
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
```

restarted zsh again, yet it can't find pip

```
$ pip
pyenv: pip: command not found

The `pip' command exists in these Python versions:
  2.7.10
```

**Comment by binarykitchen** [comment]
oh man, i got it. had to switch from system version to 2.7.10, then all is good.

i think the DX should be improved here. say something like "pip not found in system version. maybe you should switch to 2.7.10?" or so

**Comment by bonsoirval** [comment]
These steps worked for me.

1- Uninstall the pip update from python.
2- Uninstall pip package from your Ubuntu.
3- Check that pip binary is not longer in your system.

python -m pip uninstall pip
apt remove python-pip
whereis pip
4- Download and install pip. 
wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py
sudo python3 /tmp/get-pip.py
pip install --user pipenv
pip3 install --user pipenv
echo "PATH=$HOME/.local/bin:$PATH" >> ~/.profile
source ~/.profile
whereis pip
Now you should be able to install any pip package you want.

From [https://stackoverflow.com/questions/49964093/file-usr-bin-pip-line-9-in-module-from-pip-import-main-importerror-canno](url)

**Comment by BarnabasSzabolcs** [comment]
> $ python --version Python 2.7.10
> 
> $ python ~/Downloads/get-pip.py Requirement already up-to-date: pip in /Library/Python/2.7/site-packages
> 
> $ which pip /Users/michael-heuberger/.pyenv/shims/pip
> 
> $ pip pyenv: pip: command not found
> 
> The `pip' command exists in these Python versions: 2.7.10
> 
> Hmmm, what is wrong here?

`pyenv help global` is your friend.
You need to set the global pyenv version.
For me it was  `pyenv global 3.9.4`
