### ISSUE TITLE
How to get Python built against outdated OS version

### ISSUE THREAD

**Issue by webknjaz** [pyenv/pyenv#1134]
Hello,

There's two macOS installers at https://www.python.org/downloads/release/python-365/
I'm wondering whether it's possible to tell pyenv to install version for macOS built for 10.6.
This is needed for building binary OS-specific wheels which target wider range of OS versions, so that when building wheel under 10.12 it would still work for 10.6+. Just like `manylinux1` containers for GNU/Linux-based distros.

Any hints?

While it's not supported, the only CI-friendly way to do this is smth like this: https://github.com/wolfSSL/wolfcrypt-py/blob/fbbe880/make/osx/install_python.sh

**Comment by joshfriend** [comment]
pyenv builds CPython from source and does not use the pkg installers. I think if you need a 32 bit compatible version, you need to pass some flags to the `./configure` script. 64 bit seems to be the default if supported, if I run `python -c "import struct; print(8*struct.calcsize('P'))"` in any pyenv built python on my 10.13 mac, it prints 64.

**Comment by webknjaz** [comment]
I don't really care about 32 bit vs. 64 bit now. Was curious about python linked against older xcode/whatever.
Thanks for your reply :)
