### ISSUE TITLE
Homebrew Config location

### ISSUE THREAD

**Issue by Yicong-Huang** [pyenv/pyenv#1138]
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/yicong/.pyenv/shims/python2-config
  /Users/yicong/.pyenv/shims/python3.6m-config
  /Users/yicong/.pyenv/shims/python2.7-config
  /Users/yicong/.pyenv/shims/python-config
  /Users/yicong/.pyenv/shims/python3-config
  /Users/yicong/.pyenv/shims/python3.6-config

### Description
- Mac OS High Sierra 10.13.4
- pyenv 1.2.3
- system(2.7.10), 2.7.14, 3.6.3
- Apple LLVM version 9.1.0 (clang-902.0.39.1)

**Comment by yyuu** [comment]
duplicated https://github.com/pyenv/pyenv/issues/106
