### ISSUE TITLE
Create new pyenv-pip-migrate release

### ISSUE THREAD

**Issue by dkav** [pyenv/pyenv#1152]
Can the team create a new release of pyenv-pip-migrate based on the latest head? The [current release](https://github.com/pyenv/pyenv-pip-migrate/releases/tag/v20130527) is built off the initial commit and doesn't include later commits. The release also includes a [bug](http://blog.maartenpaauw.com/2017/05/28/mktemp-mkstemp-failed-on-tmp-requirements-xxxx-txt-file-exists.html) that was fixed in a subsequent commit.

I would have posted this to  pyenv-pip-migrate project but there is no Issues page, which is true for many of the plugins.

**Comment by chrahunt** [comment]
The issues page for the plug-in is now available. Please feel free to raise this over there.

**Comment by dkav** [comment]
> The issues page for the plug-in is now available. Please feel free to raise this over there.

Per your suggestion, this issue has now been raised in https://github.com/pyenv/pyenv-pip-migrate/issues/6.
