### ISSUE TITLE
PyPy install fails on OSX if PYTHON_CONFIG_OPTS=*--enable-framework*

### ISSUE THREAD

**Issue by andrew-christianson** [pyenv/pyenv#1155]
It appears that installation of pypy fails on macOS if `PYTHON_CONFIGURE_OPTS` contains `--enable-framework`. With that variable so set, I get:

```
t % pyenv install -kfv pypy3.5-6.0.0                                                                ~
~/.pyenv/sources/pypy3.5-6.0.0 ~
~/.pyenv/sources/pypy3.5-6.0.0/pypy3-v6.0.0-osx64 ~/.pyenv/sources/pypy3.5-6.0.0 ~
Installing pypy3-v6.0.0-osx64...
ERROR: invalid Python executable: /Users/achristianson/.pyenv/versions/pypy3.5-6.0.0/bin/python

The python-build could not find proper executable of Python after successful build.
Please open an issue for future improvements.
https://github.com/pyenv/pyenv/issues

BUILD FAILED (OS X 10.13.4 using 0000000000)
```

Running 

```
export PYTHON_CONFIGURE_OPTS="" 
pyenv install -kfv pypy3.5-6.0.0                 
```

builds successfully.  

I believe this is the root cause for #763, and also possible #911 and #573, though the other two will be difficult to confirm.

### Description 
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS 10.13.4
- [x] OS architecture (e.g. amd64): amd 64
- [x] pyenv version: 1.2.4
- [x] Python version: pypy3.5-6.0.0, pypy2.7-6.0.0
- [x] C Compiler information (e.g. gcc 7.3): NA
- [x] Please attach verbose build log as gist: https://gist.github.com/andrew-christianson/dd08fc7d4e6f7830bdacbbb8622a9342

**Comment by YJiWei** [comment]
Can you help me, please? I met this problem, too. Using pyenv installed Python, when using pyinstaller, it was reported that the error was as follows:
OSError: Python library not found: libpython3.6.so.1.0, libpython3.6m.so.1.0, libpython3.6mu.so.1.0

**Comment by weaming** [comment]
This issue bother me for almost two days!

**Comment by native-api** [comment]
`PYTHON_CONFIGURE_OPTS` are only applicable to versions built from source (`pypy*` without `-src` are precompiled), and `--enable-framework` is only applicable to CPython.

Pyenv has no way to tell which version is which so I'm ruling this a GIGO.

If someone wishes to write a maintainable guard, contributions are welcome.
