### ISSUE TITLE
pyenv install fails silently when downloader not found

### ISSUE THREAD

**Issue by eedwards-sk** [pyenv/pyenv#1156]
discovered a bug which causes pyenv install to exit with a non-helpful message when it's missing the downloaders (e.g. curl, wget, etc.)

this is the only output:

```
Downloading Python-3.6.5.tar.xz...
-> https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tar.xz
```

after running, confirming exit code was non-zero:

```
$ echo $?
1
```

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu Linux 18.04
- [X] OS architecture (e.g. amd64): amd64
- [X] pyenv version: pyenv 1.2.4
- [X] Python version: 3.6.5
- [X] C Compiler information (e.g. gcc 7.3): n\a
- [X] Please attach verbose build log as gist: https://gist.github.com/eedwards-sk/c747520d51d789c2307da9cf27b99d4a

bug in https://github.com/pyenv/pyenv/blob/master/plugins/python-build/bin/python-build

line 474

```
if http get "$package_url" "$package_filename" >&4 2>&1; then
```

which calls `http get`

line 336

```
  else
    if type aria2c &>/dev/null; then
      http_client="http_${method}_aria2c"
    elif type curl &>/dev/null; then
      http_client="http_${method}_curl"
    elif type wget &>/dev/null; then
      http_client="http_${method}_wget"
    else
      echo "error: please install \`aria2c\`, \`curl\` or \`wget\` and try again" >&2
      exit 1
    fi
```

I believe `set -E` is messing with this flow

If I change `exit 1` to `return 1` then I get slightly further output:

```
root@a48661993e92:~/.pyenv/plugins/python-build/bin# pyenv install -v 3.6.5
Downloading Python-3.6.5.tar.xz...
-> https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tar.xz
error: failed to download Python-3.6.5.tar.xz

BUILD FAILED (Ubuntu 18.04 using python-build 1.2.4)
```

However, the message `"error: please install aria2c, curl or wget and try again"` is never printed.

**Comment by thekalinga** [comment]
Or when downloader has any issues. I had `aria2c` in the path & the binary does not have all the libraries in the system. `pyenv` silently fails by giving the user no info on what happened

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/commit/b551fed8d5e5aa49207c11f9df7df5255044e4e4
