### ISSUE TITLE
[pyenv v1.2.4] - when installed globally (users cannot write) 'cannot rehash' error on activation

### ISSUE THREAD

**Issue by draeath** [pyenv/pyenv#1157]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): RHEL 7.5
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: tags/v1.2.4
- [x] Python version: N/A: not a python issue
- [x] C Compiler information (e.g. gcc 7.3): N/A: not a python issue
- [x] Please attach verbose build log as gist (N/A: not a python issue)

I have set up pyenv into a root-owned tree, with the intention that users activate the environment via a script in `/etc/profile.d/` - this has been working flawlessly until I bumped from pyenv 1.2.3 to 1.2.4.

Now, when the activation script is run, the following output prints:
```
pyenv: cannot rehash: /opt/REDACTED/pyenv/shims isn't writable
```

I do not expect (nor want) pyenv to write anything when users are utilizing the pythons provided by this environment. They will be managed (sparingly) via configuration management.

Is there some means to run pyenv in a read-only mode? Or at least tell it to stop trying to rehash on execution? If not, there should be a switch to do so.

The profile snippet looks like this:
```
case "${-}" in
  *i*) # interactive shell
    if [ -n "${BASH_VERSION}" ]; then
      if [ -t 0 ]; then
        if [ "${PYENV_ROOT}" != "/opt/REDACTED/pyenv" ]; then
          if [ -x "/opt/REDACTED/pyenv" ]; then
            export PYENV_ROOT="/opt/REDACTED/pyenv"
            export PATH=${PYENV_ROOT}/bin:${PATH}
            export PYENV_VIRTUALENV_DISABLE_PROMPT=1
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
          fi
        fi
      fi
    fi
    ;;
  *) # non-interactive shell
    return
    ;;
esac
```

It's got an ugly set of if statements around it - these are intended to ensure it is only loaded when in an interactive *bash* shell with an allocated TTY.

**Comment by draeath** [comment]
This was introduced by #1092 I believe?

**Comment by Igonato** [comment]
Seeing this as well on Ubuntu 16.04. Wasn't an issue in v1.2.3

**Comment by alem0lars** [comment]
I'm having the same error with `v1.2.5`.. Any solutions or workarounds?

**Comment by andrewyatz** [comment]
I think it was caused by this change https://github.com/pyenv/pyenv/commit/7973e5947395b3def52ca623e7571ec57e2393f9. `pyenv-rehash` now checks `$SHIM_PATH` if it is writable and aborts if it is not.

**Comment by draeath** [comment]
I don't suppose there's any way to squelch the assert output, there?

**Comment by draeath** [comment]
This may do the trick: https://github.com/pyenv/pyenv/blob/d08c9cfb362c5a7e18a92acd2253a16935ad9a99/test/init.bats#L59-L63

**Comment by draeath** [comment]
Indeed! This does squelch the output. Since you won't be changing the contents of pyenv in this scenario, disabling the rehash shouldn't have any side effects.

You can implement this by tweaking your pyenv init call to look like this:

`eval "$(pyenv init - --no-rehash)`
