### ISSUE TITLE
Confusing error message `pyenv: python2: command not found`

### ISSUE THREAD

**Issue by ORESoftware** [pyenv/pyenv#1159]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS Sierra
- [x] OS architecture (e.g. amd64):  
- [x] pyenv version: pyenv 1.2.2
- [x] Python version: that is the question isn't it

I see this in my terminal:

```bash
$ python2 --version
pyenv: python2: command not found

The `python2' command exists in these Python versions:
  2.7.5
  2.7.8
```

surely this is a confusing error message? Does anyone know what state I am in and how to fix?
I am looking for `python` and `python2` to point to python version 2.7.8, and `python3` to point to the latest python3 version.

**Comment by joshfriend** [comment]
when you run `pyenv version` is the system python the active one? if so, you get the "command not found" error because the system python (on OSX at least) doesn't provide a `python2` executable, so pyenv wont generate a shim for it.

**Comment by james-turner** [comment]
So try `pyenv local 2.7.8` followed by `python2` and see what you get. Chances are `pyenv version` is showing something other than 2.7 (for me it was 3.6.2)

**Comment by tgunr** [comment]
I tried peen 2.7.8 and 2.7.14 and 2.7.5, all result in same error message. Where is python2?

**Comment by elock37** [comment]
I ran into this while trying to install a node module after I had set `pyenv global 3.6.5`. The `npm` install called python2 which brought me here.

@tgunr What you are doing will determine which `pyenv` command to use. You likely want to use `pyenv shell 2.7.14`. This will set your shell temporarily to Python 2 until you close it.

**Comment by carrchr** [comment]
I had this same error when trying to install an npm package globally (Node.js managed with nodenv). Following the recommendation of elock37 allowed me to get the nom package installed
`pyenv shell 2.7.14` - substitute which actual version of Python that you're using

**Comment by IamGianluca** [comment]
An application (`gcloud`) is trying to run `python2` while inside a `python3` virtual environment. Following the [documentation](https://github.com/pyenv/pyenv/blob/master/COMMANDS.md#pyenv-local), I've tried to activate both python2 and 3. 

```
$ pyenv global
system
2.7.15
$ pyenv virtualenvs
  3.6.5/envs/dotfiles (created from /home/gianluca/.pyenv/versions/3.6.5)
  3.6.5/envs/neovim3 (created from /home/gianluca/.pyenv/versions/3.6.5)
  3.7.0/envs/search (created from /home/gianluca/.pyenv/versions/3.7.0)
  dotfiles (created from /home/gianluca/.pyenv/versions/3.6.5)
  neovim3 (created from /home/gianluca/.pyenv/versions/3.6.5)
  search (created from /home/gianluca/.pyenv/versions/3.7.0)
```

```
$ pyenv activate search
$ python --version
Python 3.7.0
$ python2 --version
pyenv: python2: command not found

The `python2' command exists in these Python versions:
  2.7.15
```

```
$ pyenv local search 2.7.15
$ python2
pyenv: python2: command not found

The `python2' command exists in these Python versions:
  2.7.15
```

Am I misinterpreting the documentation?

**Comment by denningsrogue** [comment]
Try this:

 pvenv shell 3.7.2 2.7.15.

After that python2 --version  will give you 2.7.15 and python --version and python3 --version will each give you 3.7.2

**Comment by denningsrogue** [comment]
pyenv global 3.6.4 2.7.15

**Comment by taichi-jp** [comment]
`pyenv global 3.6.4 2.7.15` is set too :(
This maybe because of `gcloud` command. `npm` works fine even if it requires python2 too

**Comment by JavierFuentes** [comment]
Thanks @denningsrogue ,

I have this in my `.bash_profile`

```ts
# Python Version Manager
export PATH="$PATH:$HOME/.pyenv/bin"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```
and 

```ts
$ pyenv global 3.7.2 2.7.16
``` 
has worked for me **permanently**.

```ts
iMac:~ javier$ pyenv versions
  system
* 2.7.16 (set by /Volumes/Datos/Users/javier/.pyenv/version)
* 3.7.2 (set by /Volumes/Datos/Users/javier/.pyenv/version)
```

```ts
iMac:~ javier$ python2
Python 2.7.16 (default, Mar  9 2019, 20:36:25) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
```

```ts
iMac:~ javier$ python3
Python 3.7.2 (default, Mar  9 2019, 20:49:03) 
[Clang 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
```

```ts
iMac:~ javier$ python
Python 3.7.2 (default, Mar  9 2019, 20:49:03) 
[Clang 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit();
```

I think this should be more clear in directly in README.md, because it is documented but a little hidden perhaps [here](https://github.com/pyenv/pyenv/blob/master/COMMANDS.md#pyenv-global-advanced)

**Comment by derekhh** [comment]
@taichi-jp Hopefully you fixed your gcloud issue already but I've found a not-too-ideal solution to this problem in https://github.com/pyenv/pyenv-virtualenv/issues/267.

Basically we can just add:

```
export CLOUDSDK_PYTHON=/Users/<user>/.pyenv/shims/python
```

to change the Python version gcloud uses.

**Comment by juanpabloaj** [comment]
> ```
> export CLOUDSDK_PYTHON=/Users/<user>/.pyenv/shims/python
> ```

In my case, I need to add to my ~/.bashrc

```
export CLOUDSDK_PYTHON=/usr/bin/python
```

**Comment by rgutierrez-cotech** [comment]
For anyone experiencing this error while inside a virtualenv with python 3: you need to specify a python 2 version to run along with python 3. Like this:
```
pyenv local <virtualenv name> <python 2 version>
```

**Comment by douglasjunior** [comment]
In my case it set `python2.7` and not `python2`, how to solve?

When I run`pyenv global` it returns:
```
Usage: pyenv global <version> <version2> <..>

Sets the global Python version(s). You can override the global version at
any time by setting a directory-specific version with `pyenv local'
or by setting the `PYENV_VERSION' environment variable.

<version> can be specified multiple times and should be a version
tag known to pyenv.  The special version string `system' will use
your default system Python.  Run `pyenv versions' for a list of
available Python versions.

Example: To enable the python2.7 and python3.7 shims to find their
         respective executables you could set both versions with:

'pyenv global 3.7.0 2.7.15'
```

When run `pyenv versions`:
```
  system
* 2.7.13 (set by PYENV_VERSION environment variable)
* 3.8.2 (set by PYENV_VERSION environment variable)
```

**Comment by bleepster** [comment]
I found out that if `PYENV_VERSION` takes precedence over `python global <version 1> <version2>`.  This isn't obvious in the docs.

**Comment by segevofer** [comment]
In macOS Monterey I used `system` instead of the python3 version.

This worked for me:

```pyenv global system 2.7.18```

**Comment by jisidehuli** [comment]
> Unfortunately it looks like since Monterey 12.3 system points to nothing because `/usr/bin/python` doesn't exists anymore and if, like in my case you are on a corporate laptop and you cannot disable SIP you cannot even create a symlink.

hello, I have the same question and wondering what you do to solve it, I appreciate your help. ❤️

**Comment by chuckweiss** [comment]
> I found out that `PYENV_VERSION` takes precedence over `python global <version 1> <version2>`. This isn't obvious in the docs.

Running on a Mac M1. I needed python2 for some npm package. Nothing in this thread worked but above clued me into adding `export PYENV_VERSION=""` to my `~/.bash_profile` and now `python` `python3` `python2` and `pyenv which python2` works as you'd expect.

 For reference 

```bash
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export PYENV_VERSION=""
pyenv global 3.11.1 2.7.18
```

**Comment by Enkumicahel** [comment]
@chuckweiss can you elaborate a little more on the reference, please? I am also struggling with that.

**Comment by chuckweiss** [comment]
> @chuckweiss can you elaborate a little more on the reference, please? I am also struggling with that.

Don't really know what you mean. Below is the basic init stuff you do for pyenv and can be found in the docs
```bash
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```

The rest is what ended up fixing my problem (`python2 -V` working just fine but `pyenv which python2` not working EVEN THO `whereis python2` resulted in `~/.pyenv/shims/python2`)
```bash
export PYENV_VERSION=""
pyenv global 3.11.1 2.7.18
```

You could also do `pyenv global 3 2` if you just want whatever pyenv servers up

**Comment by debo** [comment]
> > Unfortunately it looks like since Monterey 12.3 system points to nothing because `/usr/bin/python` doesn't exists anymore and if, like in my case you are on a corporate laptop and you cannot disable SIP you cannot even create a symlink.
> 
> hello, I have the same question and wondering what you do to solve it, I appreciate your help. ❤️
I updated the scripts to not point to an absolute path.
