### ISSUE TITLE
shebang seems to confuse pyenv

### ISSUE THREAD

**Issue by rbutleriii** [pyenv/pyenv#1162]
### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu Linux 18.04 LTS
- [ ] OS architecture (e.g. amd64): amd64
- [ ] pyenv version: 1.2.4
- [ ] Python version: system versions (2.7.15rc1 and 3.6.5), pyenv installed versions (2.7.15, 3.4.8, 3.5.5, 3.6.5)
- [ ] C Compiler information (e.g. gcc 7.3): gcc 7.3 

I have been having trouble with a script that contains a shebang: `#!/usr/bin/env python` 
Namely, when I set the pyenv version to any of the other versions, it has no problem seeing the correct version, with modules installed:
```
user01@computer:~$ pyenv versions
system
2.7.15
3.4.8
3.5.5
* 3.6.5 (set by /home/user01/.pyenv/version)
user01@computer:~$ python --version
Python 3.6.5
user01@computer:~$ /usr/bin/env python --version
Python 3.6.5
```
Except when I run the script with the shebang, it points to the system python 2.7.15rc1.
```
user01@computer:~$ clinotator.py 
Traceback (most recent call last):
  File "/opt/github/Clinotator/clinotator/clinotator.py", line 29, in <module>
    import Bio.Entrez as Entrez
ImportError: No module named Bio.Entrez
``` 
I know this because I have installed the module and removed it in each version. The error goes away when I install in system python (2.7.15rc1). I also have tox set up, and the pyenv/tox virtual environments work perfectly, for all versions of pyenv installed software, where the version reports itself as the correct one. My ~.bash_profile is modifed as suggested:
```
# pyenv installation
export PATH="~/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```
my $PATH is:
``` 
user01@computer:~$ echo $PATH
/home/user01/.pyenv/plugins/pyenv-virtualenv/shims:/home/user01/.pyenv/shims:~/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/user01/bin:/home/user01/.local/bin:/media/sf_Linux/scripts:/opt/Komodo-Edit-11.0.2/bin:/media/sf_Linux/opt/edirect:/media/sf_Linux/opt/annovar:/opt/clinvar_parse-v0.4.3:/opt/github/Clinotator/clinotator
```

**Comment by yyuu** [comment]
The shebang line of "#!/usr/bin/env python" should let sh to pick up "python" executable from PATH. At least the shebang just working fine in my environment with pyenv. And, it looks like you have sane PATH configuration at least for pyenv. At moment I have no idea :(

**Comment by rbutleriii** [comment]
Ah dammit, I figured it out. `system` was in the `.python-version` file in the folder of that script, which I was calling from a different folder. On my 16.04 build, system was my py27, but on 18.04 I have a pyenv 2.7.15. Even though 18.04 doesn't come with python(2), I had previously installed it via `sudo apt install python`. So long story short, it was defaulting to system 2.7. And I should never ever put `system` in my `.python-version`.

Interestingly though, 18.04 paired with pyenv seems like it is going to be much more efficient. The system version will be kept entirely separate as `python3`, and all pyenv versions can then easily be controlled with `python`. Pyenv cannot even see the system version of python3, unless you explicitly link `python` to `/usr/bin/python3`, or `apt install python` (don't do that, just use pyenv).
