### ISSUE TITLE
Can't install 3.0.1

### ISSUE THREAD

**Issue by chan15** [pyenv/pyenv#1167]
### Description
- Platform information Ubuntu 18.04
- x86_64
- pyenv version: 1.2.4
- Python version: 3.0.1
- C Compiler information 7.3.0

Always shows

> ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?
> 
> Please consult to the Wiki page to fix the problem.
> https://github.com/pyenv/pyenv/wiki/Common-build-problems
> 
> 
> BUILD FAILED (Ubuntu 18.04 using python-build 20180424)
> 
> Inspect or clean up the working tree at /root/src/python-build.20180604113610.5615
> Results logged to /root/src/python-build.20180604113610.5615.log

I already installed 2.6.9, 2.7, 3.2, 3.3.0, and finished what [Common-build-problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems) recommends, have no idea how to fix it

**Comment by joshfriend** [comment]
It is likely because 3.0.1 was released 10 years ago and doesn't work with new versions of openssl

https://github.com/pyenv/pyenv/issues/910#issuecomment-340262824

**Comment by chan15** [comment]
but how come 2.x all works
