### ISSUE TITLE
Unable to build a libpython2.7.dylib on Mac OS X

### ISSUE THREAD

**Issue by sillyfrog** [pyenv/pyenv#1170]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems). (I have stepped through all of these, and installed everything listed for brew)
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too. (I have looked here and the rest of the internet, but couldn't find something matching "this" - I'm not sure what this is unfortunately :( )
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc. (I believe this maybe a latest release type thing, as the system is clean, and freshly updated to the latest Mac OS and xCode, which has had a big update recently).
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc. (done, and followed steps on a clean system).
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here. (No plugins added)

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04):
- [ ] OS architecture (e.g. amd64):
ProductName:	Mac OS X
ProductVersion:	10.13.5
BuildVersion:	17F77
- [ ] pyenv version:
pyenv 1.2.4
and
pyenv 1.2.4-7-gcbf3983

- [ ] Python version:
Attempting to install 2.7.15 (but 2.7.11 also fails) with --enable-shared

- [ ] C Compiler information (e.g. gcc 7.3): 
$ clang --version
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

- [ ] Please attach verbose build log as gist

The output of my build is here, built with:
`PYTHON_CONFIGURE_OPTS="--enable-shared"     LDSHARED="clang -bundle"     LDCXXSHARED="clang++ -bundle"     BLDSHARED="clang -bundle -lpython2.7"  pyenv install -v 2.7.15`
https://gist.github.com/sillyfrog/944e41d7f2c635523da06267ec9181de

The environment I'm configuring is from: https://github.com/macvim-dev/macvim/wiki/Python-2.x-and-Python-3.x

I _can_ build Python 3.5.6 just fine (with a similar environment, including `--enable-shared`), and I can also build Python 2.7.x OK if I don't add `--enable-shared` etc to the environment to build the `.dylib`. I have tried this on 2 freshly installed Mac's (one just formatted and re-installed yesterday, the other was reinstalled a few weeks ago). They are right up to date, and I suspect the issue is something to do with the latest xCode/Mac OS X.

As this is a clean install, the `.bash_profile` is just:
```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
```

Unfortunately I have not done much with `clang` (or `c` and `c++` generally), so maybe missing an obvious error. However given I'm having similar issues on two systems, I think this maybe an issue for others as well in the future.

Please let me know you need anything else, I have exhausted everything I can figure out from the internet.

Thanks!

**Comment by sillyfrog** [comment]
Further to this, I have found that this combination works (repeatably, on both Mac's):

First I run:
```
PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 2.7.15
```

Then, once that's complete, I run:
```
PYTHON_CONFIGURE_OPTS="--enable-shared"     LDSHARED="clang -bundle"     LDCXXSHARED="clang++ -bundle"     BLDSHARED="clang -bundle -lpython2.7"  PYENV_DEBUG=1   pyenv install 2.7.15
```

And when prompted to continue (to overwrite), I say yes, it will successfully build... So that's... confusing, as best I can tell each build should be in isolation.

**Comment by cryptoeraser** [comment]
I am trying to do exactly the same thing, and I have exactly the same issue! This is driving me crazy!

**Comment by cryptoeraser** [comment]
I am still not getting the `otool -L` output that is on the Python2.x-Python3.x page.

Mine looks like this:
```
otool -L _ctypes.so
_ctypes.so:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

The example on that page looks like this:

```
$ otool -L $HOME/.pyenv/versions/2.7.11/lib/python2.7/lib-dynload/_ctypes.so
/Users/foo/.pyenv/versions/2.7.11/lib/python2.7/lib-dynload/_ctypes.so:
    /Users/foo/.pyenv/versions/2.7.11/lib/libpython2.7.dylib (compatibility version 2.7.0, current version 2.7.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

Any ideas about why I am not seeing the dynlib linked? Has the environment described there worked for you? Did you get both py2 and py3 working? Thanks.
