### ISSUE TITLE
BUILD FAILED ERROR: invalid Python executable

### ISSUE THREAD

**Issue by oquidave** [pyenv/pyenv#1174]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04):Ubuntu Linux 16.04
- [ ] OS architecture (e.g. amd64):amd64
- [ ] pyenv version: pyenv 1.2.4
- [ ] Python version: 2.7.12
- [ ] C Compiler information (e.g. gcc 7.3):  gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

Hello, I have a Vagrant VM with Ubuntu 16.04 running. I have managed to install pyenv 1.2.4, however, I have failed to install Python 3.6.x. The build is successful, but it can't find a valid Python executable at .pyenv path. I have no idea what's wrong. 

```
vagrant@ubuntu-xenial:~$ pyenv install 3.6.0
Downloading Python-3.6.0.tar.xz...
-> https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
Installing Python-3.6.0...
ERROR: invalid Python executable: /home/vagrant/.pyenv/versions/3.6.0/bin/python3.6

The python-build could not find proper executable of Python after successful build.
Please open an issue for future improvements.
https://github.com/pyenv/pyenv/issues

BUILD FAILED (Ubuntu 16.04 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20180622201132.14475
Results logged to /tmp/python-build.20180622201132.14475.log

Last 10 log lines:
		install|*) ensurepip="" ;; \
	esac; \
	 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0
make: warning:  Clock skew detected.  Your build may be incomplete.
```

Build log output is  [here](https://gist.github.com/oquidave/e853fd63026006bc1014219c7d42010f)

**Comment by joshfriend** [comment]
When you say "i have failed to install Python 3.6.x", do you mean that you are unable to install any variant of 3.6? Does the newest release (3.6.5) work?

**Comment by oquidave** [comment]
Yes, I tried to install python 3.6.0, 3.6.2 and 3.6.5 all of Which failed.

**Comment by chrahunt** [comment]
This seems solved, but if I'm wrong please let me know.

**Comment by shubhamoli** [comment]
Vagrant users if you're seeing this error then please make sure you haven't installed `pyenv` on a shared directory.

Thanks a ton! @oquidave for this.
