### ISSUE TITLE
mac  brewed pyenv: failed to download Python-x.x.x. Build failed.

### ISSUE THREAD

**Issue by avermaet** [pyenv/pyenv#1187]
Hi, seems like some kind of a problem with curl, but how to resolve it?
`pyenv install 3.6.5` results in (but it doesn't work for any other version either):
![screen shot 2018-07-18 at 15 52 28](https://user-images.githubusercontent.com/41374691/42885758-24419dcc-8aa2-11e8-82f1-a5b56bb1a2d2.png)
Used homebrew to install newest curl, pyenv, openssl, and ofcourse `brew install curl --with-ssl`

Is it possible to resolve this pyenv/curl issue? if yes, how?

Thanks

**Comment by joshfriend** [comment]
Please follow the steps in the template when reporting an issue.

**Comment by avermaet** [comment]
Ok, will do next time. Thanks. Already resolved anyway.... was just about to close.
