### ISSUE TITLE
pyenv 1.2.6 osx 10.13.6 cannot install python 3.6.6

### ISSUE THREAD

**Issue by morenoh149** [pyenv/pyenv#1188]
### Description
- [ ] Platform information: osx
- [ ] OS architecture: 10.13.6
- [ ] pyenv version: 1.2.6
- [ ] Python version: 3.6.6
- [ ] C Compiler information:
 gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Found CUDA installation: /usr/local/cuda, version 7.0
 
- [ ] Please attach verbose build log as gist: https://gist.github.com/morenoh149/e466703eaeb1bc87c22fef7b1353f9d3 I cut out most of the lines in the middle

the final error reads
```
 File "/private/var/folders/6y/kf699bqj2sgcgjshb20fr5zh0000gn/T/python-build.20180721180716.86347/Python-3.6.6/Lib/xmlrpc/client.py", line 138, in <module>
    from xml.parsers import expat
  File "/private/var/folders/6y/kf699bqj2sgcgjshb20fr5zh0000gn/T/python-build.20180721180716.86347/Python-3.6.6/Lib/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ModuleNotFoundError: No module named 'pyexpat'
make: *** [install] Error 1

BUILD FAILED (OS X 10.13.6 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/6y/kf699bqj2sgcgjshb20fr5zh0000gn/T/python-build.20180721180716.86347
Results logged to /var/folders/6y/kf699bqj2sgcgjsh
```
I followed the suggestions at https://github.com/pyenv/pyenv/wiki/Common-build-problems#build-failed-error-the-python-zlib-extension-was-not-compiled-missing-the-zlib

**Comment by y2k-shubham** [comment]
I was able to get away with above error by referring to [Common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems)
 - `brew install readline xz`
 - `xcode-select --install`
 - `brew install openssl`

----

After this, I installed and initialized `pyenv`
 - `brew install pyenv`
 - `pyenv init` (inside project directory)

Install and activate required `python` version
 - `pyenv install 3.6.6`
 - `pyenv local 3.6.6` (inside project directory)

**Comment by y2k-shubham** [comment]
**@morenoh149** I've [posted it](https://stackoverflow.com/questions/51551557) to `StackOverflow` for reference. Please consider adding your own resolution to help others.

**Comment by morenoh149** [comment]
@y2k-shubham works. However I'm not able to use the pyenv python within a pipenv. Any idea how to make this work?

**Comment by solancer** [comment]
linuxsavvy:galep srinivas$ pyenv install 3.7.1
python-build: use openssl from homebrew
python-build: use readline from homebrew
Installing Python-3.7.1...
python-build: use readline from homebrew

BUILD FAILED (OS X 10.14 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/3n/vpg5bnks45n75nd91qh7sy3c0000gn/T/python-build.20190107043912.77667
Results logged to /var/folders/3n/vpg5bnks45n75nd91qh7sy3c0000gn/T/python-build.20190107043912.77667.log

Last 10 log lines:
  File "/private/var/folders/3n/vpg5bnks45n75nd91qh7sy3c0000gn/T/python-build.20190107043912.77667/Python-3.7.1/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/private/var/folders/3n/vpg5bnks45n75nd91qh7sy3c0000gn/T/python-build.20190107043912.77667/Python-3.7.1/Lib/ensurepip/__init__.py", line 204, in _main
    default_pip=args.default_pip,
  File "/private/var/folders/3n/vpg5bnks45n75nd91qh7sy3c0000gn/T/python-build.20190107043912.77667/Python-3.7.1/Lib/ensurepip/__init__.py", line 117, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/private/var/folders/3n/vpg5bnks45n75nd91qh7sy3c0000gn/T/python-build.20190107043912.77667/Python-3.7.1/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip._internal
zipimport.ZipImportError: can't decompress data; zlib not available
make: *** [install] Error 1

**Comment by innocarpe** [comment]
@solancer It solved my problem too. Thanks a lot 😃

**Comment by rafa2000** [comment]
Still can't compile, I have a log file of 30 thousand lines and can't see anything that I can fix. This issue shouldn't be closed yet. It all happened after installing Mojave.

Here is an excerpt of the compilation log for Python 3.7.1 (similar to any other version):

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/_stdio.h:insert '_Nullable' if the pointer may be null
138:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/_stdio.h:140        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
                                          ^
                                           _Nullable
:40: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
46:In file included from Parser/listnode.c:4:
In file included from ./Include/pgenheaders.h:10:
In file included from ./Include/Python.h:25:
In file included from  warning: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/_stdio.h        int     (* _Nullable _read) (void *, char *, int);
                                                  ^
:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/stdio.hpointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
:139/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/_stdio.h:138:40: note: insert '_Nullable' if the pointer may be null
:64        int     (* _Nullable _write)(void *, const char *, int);

... more lines
... final lines
  "__Py_FatalInitError", referenced from:
      _test_init_from_config in _testembed.o
      _test_init_dev_mode in _testembed.o
      _test_init_isolated in _testembed.o
  "__Py_InitializeFromConfig", referenced from:
      _test_init_from_config in _testembed.o
      _test_init_dev_mode in _testembed.o
      _test_init_isolated in _testembed.o
ld: symbol(s) not found for architecture x86_64
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [python.exe] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Programs/_testembed] Error 1

**Comment by johnwyles** [comment]
@solancer your solution works and this issue should not be closed - `3.7.2` just installed fine using this solution but same results as everyone else when not using his solution and just performing a `pyenv install -v 3.7.2` in a fresh shell environment without these environment variables set.

**Comment by johnwyles** [comment]
Some interesting things I found along the way:
```shell
checking for clang++... no
configure:

  By default, distutils will build C++ extension modules with "clang++".
  If this is not intended, then set CXX on the configure command line.
```

Not sure if that means anything or not but does pertain somewhat to my previous comment

**Comment by timmyjose** [comment]
Yup, I really wanted to like it, but none of the suggestions here really works on macOS (Mojave) for me. `rbenv` is so much easier to use by comparison.

**Comment by Apek09** [comment]
> Yup, I really wanted to like it, but none of the suggestions here really works on macOS (Mojave) for me. `rbenv` is so much easier to use by comparison.

@timmyjose I was facing the same problem on my MacOS Mojave. 
pyenv threw the following error while install python : 
`zipimport.ZipImportError: can't decompress data; zlib not available`

Not sure if you faced the same error but seems like pyenv does not find zlib for decompressing the package. I tried installing zlib via brew and brew gave me a warning stating:

`zlib is keg-only, which means it was not symlinked into /usr/local, because macOS already provides this software and installing another version in parallel can cause all kinds of trouble.`

It also provides a solution for that:

`For compilers to find zlib you may need to set:
  export LDFLAGS="-L/usr/local/opt/zlib/lib"
  export CPPFLAGS="-I/usr/local/opt/zlib/include"

For pkg-config to find zlib you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"`

After exporting these variables I was able to install python using pyenv.

**Comment by hrdchz** [comment]
For OSX Mojave the answers seem to be in #1066
