### ISSUE TITLE
Multiple system  versions

### ISSUE THREAD

**Issue by CdeMills** [pyenv/pyenv#1189]
### Description
- Platform information : CentOS 7
- OS architecture : amd64
- pyenv version: 1.2.6
- Python version: 2.7.5 3.4.5 3.6.6 :: Anaconda custom (64-bit)
- C Compiler information (e.g. gcc 7.3): .8.5 20150623 (Red Hat 4.8.5-28) (GCC)

Hello,
there are two versions of python in base CentOS;  I installed anaconda3 under /opt and I am building Sage which comes with its own version of Python. Is there some way to configure things in such a way that pyenv locate all those versions ? Is it possible in particular to have pyenv explore the PATH environment variable element by element and detect any python version ?

I'm aware of issue  #316 -- but I don't understand how to apply this solution.

Regards

Pascal

**Comment by chrahunt** [comment]
Please follow the discussion in #1244, including your use case if it is not represented.

**Comment by jayvdb** [comment]
I feel that this is quite different from #1244 , as this is about the existing `system` capability, but whatever.

Worth noting here https://github.com/doloopwhile/pyenv-register automatically uses names `system-*` for system pythons.
