### ISSUE TITLE
Similar tool to pyenv but for docker/docker-compose

### ISSUE THREAD

**Issue by namgivu** [pyenv/pyenv#1194]
Not an issue for pyenv but an open discussion only. 
My google search for "dockerenv similar to pyenv" results nothing which means we don't have such pyenv-alike tool for docker/docker-compose right?

And why I raised this topic? Well, after tried and applied it, I have fallen in love with pyenv! And that also triggered my thoughts about the difficulty in installation and configuration and configuration when using docker/docker-compose. 

Some sample scenario. I want to have mysql/postgres/mongo/redis/etc. so many services to run to work as a developer. With docker/docker-compose, the pain of installation and configuration and version incompatible gone! Everything is about the image file/name and the version.

Similar to installing python right - we just get the name from the list printed by pyenv and then have it installed by pyenv via just the name.

Similar "just by the name" with **dockerenv** exists will get us there e.g. we can have postgres/redis installed *just by the name*.

**Comment by chrahunt** [comment]
Hi @namgivu. I don't think this is the right place for this discussion. The Docker [community forum](https://forums.docker.com/) might be a better place if you want to try posting there. Someone there may be able to point you towards existing tools or give feedback. Thanks!
