### ISSUE TITLE
pyenv install 2.7 on macos inconsistently reports that it is "32bit" when it isn't

### ISSUE THREAD

**Issue by asottile** [pyenv/pyenv#1198]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04):

```
$ uname -a
Darwin Macbook-Pro 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,4 Darwin
```
- [x] OS architecture (e.g. amd64): see above
- [x] pyenv version:
```
$ git rev-parse HEAD
97f244fbb5156ef70ad4133aa9b46b96c24825d6
```
- [x] Python version: see below
- [x] C Compiler information (e.g. gcc 7.3): 
```
$ cc --version
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

(I left this out because I found the issue below)

Here's the core of the problem:

```console
$ # via `pyenv install 2.7`
$ ./versions/2.7/bin/python -c 'import struct;print(8 * struct.calcsize("P"))'
64
$ ./versions/2.7/bin/python -c 'import platform; print(platform.mac_ver())'
('10.13.6', ('', '', ''), 'i386')
$ # via `pyenv install 2.7.15`
$ ./versions/2.7.15/bin/python -c 'import struct;print(8 * struct.calcsize("P"))'
64
$ ./versions/2.7.15/bin/python -c 'import platform; print(platform.mac_ver())'
('10.13.6', ('', '', ''), 'x86_64')
```

This causes real problems when installing wheels from pip ([which uses `mac_ver` to determine appropriate wheels](https://github.com/pypa/pip/blob/09f68728f8b33bbc70a9216d072df94a5c1d44e3/src/pip/_internal/pep425tags.py#L123))

### root cause / analysis

`pyenv install 2.7` installs `2.7.0` which is really old and probably has a bug itself.  seems this was fixed in later versions -- perhaps `pyenv` should warn about _old_ versions? or automatically select new versions?

**Comment by chrahunt** [comment]
Will be tracked by #1282. Thanks!
