### ISSUE TITLE
cpython 3.5.6 still missing

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyenv/pyenv#1199]
thanks for adding it!

https://www.bountysource.com/issues/62020440-cpython-3-5-6-still-missing

**Comment by joshfriend** [comment]
Should be landing in homebrew soon (https://github.com/Homebrew/homebrew-core/pull/31025). Thanks for pointing out that it was missing!

**Comment by ThomasWaldmann** [comment]
Thanks for fixing. Claim the bounty and have a beer (or whatever). :)

**Comment by ThomasWaldmann** [comment]
$8 are still waiting to be claimed (sorry if it is not much, but you know, poor FOSS projects...).

**Comment by ThomasWaldmann** [comment]
Looks like @joshfriend does not want to claim, so I'll transfer the bounty back to borgbackup general funds.

Thanks much for fixing it! :)
