### ISSUE TITLE
Bad advice in Common Build Problems on Wiki

### ISSUE THREAD

**Issue by vjancik** [pyenv/pyenv#1202]
### Description
Platform information (e.g. Ubuntu Linux 16.04): **Ubuntu Linux 18.04**
OS architecture (e.g. amd64): **amd64**
pyenv version: **1.2.7**
Python version: **3.7.0**

> Make your pythons a little faster
> 
> You can set your CFLAGS to accepted safe values to help get a little more speed.
> 
> `CFLAGS='-O2'`

These are the default `CFLAGS` as given by:
```python
import sysconfig
print(sysconfig.get_config_vars())
```
after installation:
`'CFLAGS': '-fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-nbjU53/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security  ',`
`'CONFIGURE_CFLAGS': '-Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-nbjU53/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security',`

However, if you build python using `CFLAGS="-O2" python-build` then the final `CFLAGS` are:
`'CFLAGS': '-Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O2 -O2'`
`'CONFIGURE_CFLAGS': '-O2'`
Completely overwriting the previous default `CONFIGURE_CFLAGS` values.

The resultant `PY_CFLAGS` are constructed as given here:
https://github.com/python/cpython/blob/6c785c0ebdadc84d80a53d896c38fd7ada8ae1f6/Makefile.pre.in#L93

Therefore, I suspect additional user-defined `CFLAGS` should be passed as `EXTRA_CFLAGS`, however it seems that when building with `python-build`, this env variable doesn't get passed to the actual config / make script, even if I `export` it in a previous command.

There may be some other issue at play here as the comment at:
https://github.com/python/cpython/blob/6c785c0ebdadc84d80a53d896c38fd7ada8ae1f6/Makefile.pre.in#L90-L92
would suggest that overwriting `CFLAGS` is okay, but it appears it's not.

It also appears that the `-O2` flag is used by default for Python 3.7.0 (not sure about others), though oddly, when I overwrote `CFLAGS` with `-O2` an `-O3` appeared in the resultant `PY_CFLAGS` for some reason.

**Comment by native-api** [comment]
Done.
