### ISSUE TITLE
Typo in `pyenv init -` for fish?

### ISSUE THREAD

**Issue by qpwo** [pyenv/pyenv#1203]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
* [x] Make sure your problem is not derived from plugins.

### Description
- [x] Platform information: mac
- [x] OS architecture: x86_64
- [x] pyenv version: 1.2.7
- [x] Python version: not applicable
- [x] C Compiler information: gcc Apple LLVM version 9.0.0 (clang-900.0.39.2)
- [x] Please attach verbose build log as gist: not applicable

### Main Issue

Here is what I see for `pyenv init -`:

```
set -gx PATH '/Users/lhm/.pyenv/shims' $PATH
set -gx PYENV_SHELL fish
source '/usr/local/Cellar/pyenv/1.2.7/libexec/../completions/pyenv.fish'
command pyenv rehash 2>/dev/null
function pyenv
  set command $argv[1]
  set -e argv[1]

  switch "$command"
  case rehash shell
    source (pyenv "sh-$command" $argv|psub)
  case '*'
    command pyenv "$command" $argv
  end
end
```

And fish does not like it:

```
$ eval (pyenv init -)
pyenv: no such command `sh-'
```

Is this indeed a typo in the output of `pyenv init -`?

**Comment by bittner** [comment]
Could you try `source <(pyenv init -)` instead of `eval (pyenv init -)`? Does that work with fish?

What happens? Just curious.

**Comment by bicycle1885** [comment]
I don't know why `eval` doesn't work, but `pyenv init - | source` seems to work well.

**Comment by bicycle1885** [comment]
Ah, fish's `eval` normalizes newlines to space characters:
```
~/.c/fish $ eval (echo -e "echo foo\necho bar")
foo echo bar
~/.c/fish $ eval (echo -e "echo foo;echo bar")
foo
bar
```

So, multiple commands must be separated by semicolons, not by newlines.
