### ISSUE TITLE
Config to install default packages for all versions

### ISSUE THREAD

**Issue by LeonardoGentile** [pyenv/pyenv#1205]
Hello,
sorry for skipping the issue template but this is not really a problem but more a suggestion/improvement. 

I guess this is still not available but it would be useful whenever we download a new python version to have some default packages installed automatically for that version.

An example of this is implemented in nvm: https://github.com/creationix/nvm#default-global-packages-from-file-while-installing

I guess in the .pyenv folder we could drop a requirements.txt with a list of packages that should be globally available for all python versions. As soon as the new versions is installed then pip would kick in and fetch those packages from requirements.txt.

Would this make sense?

Cheers

**Comment by joshfriend** [comment]
I could see this being a plugin for pyenv, but not part of the core. Pyenv core is just for getting python installed, then the official and 3rd party plugins (e.g. pyenv-virtualenv) add support for related tools. 

Dependency management is a huge can of worms that I don't think the core functionality of pyenv should open 😉. For example, how are the packages installed? With pip? with Pipenv? or perhaps poetry?

**Comment by LemonAndroid** [comment]
I won't install it if it's a plugin. Unless it comes with it's own installer script and is an all-in-one installation of pyenv plus the to-be-developed plugin.
