### ISSUE TITLE
Wrong Python Version Being Used but 'which python' correct

### ISSUE THREAD

**Issue by TensorTom** [pyenv/pyenv#1208]
I'm trying to get setup on my AWS instance. This is a very strange series of output from the terminal that makes no sense:

```
user:~/environment/project $ python --version
Python 2.7.14
user:~/environment/project $ pyenv version
3.7.0 (set by /home/ec2-user/environment/project/.python-version)
user:~/environment/project $ which python
/home/ec2-user/.pyenv/shims/python
user:~/environment/project $ /home/ec2-user/.pyenv/shims/python --version
Python 3.7.0
user:~/environment/project $ wtf???
```

**Comment by joshfriend** [comment]
Please check that you've done step 3 of the install mentioned in the README: ["Add pyenv init to your shell"](https://github.com/pyenv/pyenv#basic-github-checkout)

**Comment by TensorTom** [comment]
Instructions were followed exactly. This looks to be a centos install at its base. I've installed pyenv on several such installs in the past. Idk what's going on here. I don't see how running what `which python` reports could show 3.7.0 (What I want) when running `python --version` shows the system version.

**Comment by EscapeLife** [comment]
@TensorTom  Please check `~/environment/project` has `.python-version` file. If normal, you can check that you have executed the `pyenv local 3.7.0` command. Good luck for you

**Comment by bertjwregeer** [comment]
@TensorTom instead of using `which`, could you output `type python` please? This will show you what the current shell thinks `python` is. This may not match what is in the `$PATH` (which is what `which` shows you) if for example you have an alias setup for `python`.

**Comment by egor-ryashin** [comment]
I have the same issue
```
macbook:bin$ pyenv versions
  system
* 3.6.2 (set by /usr/local/var/pyenv/version)
macbook:bin$ python -V
Python 2.7.13
macbook:bin$ type python
python is hashed (/Users/egorryashin/.pyenv/shims/python)
```

**Comment by ameliariely** [comment]
I am having this same issue with the same outputs and checked the same things. Were you able to fix it @egor-ryashin ?

**Comment by ameliariely** [comment]
@TensorTom were you able to resolve this?

**Comment by andriyShevtsov** [comment]
I have the same issue

**Comment by andriyShevtsov** [comment]
I don't now how it works but this helped me 
`eval "$(pyenv init -)"`

Taken this suggstion [here]( https://github.com/pyenv/pyenv/issues/849#issuecomment-579301646)
Thanks @rollno55044

**Comment by ianbenlolo** [comment]
I have the same issue

**Comment by pcoccoli** [comment]
Same issue.  Here's the output of a shell script that demonstrates the problem.  It creates 2 virtualenvs, and puts a CSV file in one and python script in the other.  The it goes into the second virtualenv and tries to run that script, passing in the relative path to the data file in the other virtualenv.  For reasons I do not understand, pyenv is using the directory of the data file argument to choose which .python-version file it reads.  This results in the the wrong virtualenv, and a ModuleNotFoundError (in this case, tabulate).

Link to gist with the script: https://gist.github.com/pcoccoli/6f13219d48bec9394aaf38003d94e78c

Output of `sh -x pyenv_wrong_version.sh`:
```
+ version=3.6.8
+ mkdir ve_1
+ cd ve_1
+ pyenv virtualenv 3.6.8 ve_1
Looking in links: /tmp/tmpxkrnjee8
Requirement already satisfied: setuptools in /home/pcoccoli/.pyenv/versions/3.6.8/envs/ve_1/lib/python3.6/site-packages (40.6.2)
Requirement already satisfied: pip in /home/pcoccoli/.pyenv/versions/3.6.8/envs/ve_1/lib/python3.6/site-packages (18.1)
+ pyenv local ve_1
+ pyenv version
ve_1 (set by /home/pcoccoli/tmp/test/ve_1/.python-version)
+ cd ..
+ mkdir ve_2
+ cd ve_2
+ pyenv virtualenv 3.6.8 ve_2
Looking in links: /tmp/tmp8jp_zdha
Requirement already satisfied: setuptools in /home/pcoccoli/.pyenv/versions/3.6.8/envs/ve_2/lib/python3.6/site-packages (40.6.2)
Requirement already satisfied: pip in /home/pcoccoli/.pyenv/versions/3.6.8/envs/ve_2/lib/python3.6/site-packages (18.1)
+ pyenv local ve_2
+ pyenv version
ve_2 (set by /home/pcoccoli/tmp/test/ve_2/.python-version)
+ pip install tabulate
Collecting tabulate
  Using cached https://files.pythonhosted.org/packages/ca/80/7c0cad11bd99985cfe7c09427ee0b4f9bd6b048bd13d4ffb32c6db237dfb/tabulate-0.8.9-py3-none-any.whl
Installing collected packages: tabulate
Successfully installed tabulate-0.8.9
You are using pip version 18.1, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+ cd ..
+ cat
+ cat
+ cd ve_2
+ tabulate ../ve_1/test.csv
----------
name,value
"a",1.0
"b",0.1
"a",0.2
----------
+ pyenv which python
/home/pcoccoli/.pyenv/versions/ve_2/bin/python
+ pyenv which pip
/home/pcoccoli/.pyenv/versions/ve_2/bin/pip
+ pip show tabulate
Name: tabulate
Version: 0.8.9
Summary: Pretty-print tabular data
Home-page: https://github.com/astanin/python-tabulate
Author: Sergey Astanin
Author-email: s.astanin@gmail.com
License: MIT
Location: /home/pcoccoli/.pyenv/versions/3.6.8/envs/ve_2/lib/python3.6/site-packages
Requires: 
Required-by: 
+ python tab.py ../ve_1/test.csv
Traceback (most recent call last):
  File "tab.py", line 4, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
```

**Comment by native-api** [comment]
Debug trace was not provided as required by the issue template.

Causes can be: incorrect shell setup, shell aliases, failing to restart the shell session after setting up Pyenv as required by the README.

**Comment by alysenkoThumbtack** [comment]
Also faced the same problem. Adding these lines to bash_profile resolved the issue:
```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

It correlates with the documentation, but you need to call `pyenv init` command twice: with and without `--path` parameter.

**Comment by itsbart** [comment]
> Also faced the same problem. Adding these lines to bash_profile resolved the issue:
> 
> ```
> export PYENV_ROOT="$HOME/.pyenv"
> export PATH="$PYENV_ROOT/bin:$PATH"
> eval "$(pyenv init --path)"
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```
> 
> It correlates with the documentation but not at all: you need to call `pyenv init` command twice: with and without `--path` parameter.

Thank you !

**Comment by aiqc** [comment]
```bash
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

this still works in late 2021

**Comment by gnarizzy** [comment]
> ```shell
> export PYENV_ROOT="$HOME/.pyenv"
> export PATH="$PYENV_ROOT/bin:$PATH"
> ```

Confirming in 2023 for a zshell/zsh environment as well!

**Comment by koushikyadav-klvin** [comment]
If anyone is still facing this issue, lets say after maybe moving your .pyenv folder. The best and hassle free way would be to reinstall your python and all other dependencies again via pyenv uninstall, install. That seemed to work for me.
