### ISSUE TITLE
pyenv and macports WORKING

### ISSUE THREAD

**Issue by stasiek** [pyenv/pyenv#1212]
@yyuu You no longer need to recommend using hipster's macports (brew). : P
To get pyenv building those pythons just set:

```
export LDFLAGS=-L/opt/local/lib/
export CPPFLAGS="-I/opt/local/include -L/opt/local/lib"
export C_INCLUDE_PATH=/opt/local/include
export LIBRARY_PATH=/opt/local/lib
```

**Comment by lins05** [comment]
Yes it works, but seems it still has to build its own version of openssl instead of using the openssl already installed by macports.

**Comment by native-api** [comment]
The READMEs now recommend Homebrew over Macports so no longer relevant, I guess.
https://github.com/pyenv/pyenv/wiki/Common-build-problems mentions Macports in passing, giving enough info to figure out what to do to use it.
