### ISSUE TITLE
Suggest `source <(...)` instead of `eval $(...)` in README

### ISSUE THREAD

**Issue by bittner** [pyenv/pyenv#1214]
In the [installation instructions](https://github.com/pyenv/pyenv#installation) of the README we suggest using `eval` to activate `pyenv` in a shell.
```bash
eval "$(pyenv init -)"
```
An (arguably) more elegant alternative way to write this is using `source` and redirection. It could look like this:
```bash
source <(pyenv init -)
```
This syntax is used in other popular projects, such as the [Kubernetes CLI](https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion).

May there be reasons to favor `eval` over `source`? Would you accept a PR that changes the setup instructions accordingly?

**Comment by chrahunt** [comment]
The `eval "$(...)"` syntax seems more portable. For example,

```
$ docker run -it busybox
/ # echo "$(seq 1 3)"
1
2
3
/ # cat <(seq 1 3)
sh: syntax error: unexpected "("
```

or when using `/bin/sh` (dash) on latest Ubuntu 18.04

```
$ docker run -it ubuntu:18.04 /bin/sh
# echo "$(seq 1 3)"
1
2
3
# cat <(seq 1 3)
/bin/sh: 2: Syntax error: "(" unexpected
```

Likewise, `source` does not work in `/bin/sh`.
