### ISSUE TITLE
Install fails on Ubuntu 18 linux subsystem for windows.

### ISSUE THREAD

**Issue by dmikov** [pyenv/pyenv#1225]
### Description
- [ ] Platform information: Ubuntu 18.04 subsystem on Windows 10 Creative Edition
- [ ] OS architecture (e.g. amd64): AMD64, i7 6700K
- [ ] pyenv version: latest
- [ ] Python version: 2.7.15
- [ ] C Compiler information (e.g. gcc 7.3):  7.3.0

Maybe confusing which OS it is running on. If not 100% linux then it's Mac? When in fact it is linux?

Short version
```
dmikov@DavieHyperV:~$ pyenv install 2.7.15
Downloading Python-2.7.15.tar.xz...
-> https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tar.xz
Installing Python-2.7.15...
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
ERROR: The Python zlib extension was not compiled. Missing the zlib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (Ubuntu 18.04 using python-build 1.2.7-7-g21c75c19)

Inspect or clean up the working tree at /tmp/python-build.20181008085510.188
Results logged to /tmp/python-build.20181008085510.188.log

Last 10 log lines:
rm -f /home/dmikov/.pyenv/versions/2.7.15/share/man/man1/python.1
(cd /home/dmikov/.pyenv/versions/2.7.15/share/man/man1; ln -s python2.1 python.1)
if test "xno" != "xno"  ; then \
        case no in \
                upgrade) ensurepip="--upgrade" ;; \
                install|*) ensurepip="" ;; \
        esac; \
         ./python -E -m ensurepip \
                $ensurepip --root=/ ; \
fi
```

Long verbose version [https://gist.github.com/dmikov/21f12755dbfa744edfacc3b9410a59cd](https://gist.github.com/dmikov/21f12755dbfa744edfacc3b9410a59cd)

**Comment by garytyler** [comment]
I think installing the Ubuntu/Debian requirements mentioned on the Installation Wiki [here](https://github.com/pyenv/pyenv/wiki/Common-build-problems) should clear this up. Just run this in your shell: 
```
sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
xz-utils tk-dev libffi-dev liblzma-dev
```

**Comment by wottpal** [comment]
Same issue and @garytyler solution helped. Thanks!

**Comment by michidk** [comment]
@garytyler solution did't work for me. tested on both Debian and Ubuntu Subsystem on Windows, Also tested on Debian on a dedicated machine.

**Comment by chrahunt** [comment]
@michidk, please create a separate issue and make sure to include the build logs and all details requested in the default issue text. That will help us help you!

@dmikov, please see the suggestion from @garytyler and the link to the wiki which may have an updated list of requirements. The issues that appear in your log seem directly related to the build of modules that require the sorts of packages that running the command above will install. If you still have problems please let us know.

**Comment by shaunbarney** [comment]
@michidk I had the same issue, then when I ran the command from @garytyler it didn't seem to work, but after running sudo apt-get update and sudo apt-get upgrade and then rerunning that command it fixed it and I was then able to install a specific Python version using pyenv version.
