### ISSUE TITLE
osx installed with brew,  should I modify ~/.bash_profile as step 2 told?

### ISSUE THREAD

**Issue by liqt91** [pyenv/pyenv#1226]
maybe this is a stupid question, but I just engage with it .

I first run 
**$ brew install pyenv**
to install pyenv, then as instructed I gonna to modify the ~/.bash_profile file like:
**$ echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bash_profile**
from step 3.

but actually the .bash_profile lack path setting code which mentioned in step 2, which is:
**export PYENV_ROOT="$HOME/.pyenv
export PATH="$PYENV_ROOT/bin:$PAT**

so should I add it to the bash_profile? if not, I wonder witch file did that work instead.

**Comment by joshfriend** [comment]
>should I add it to the bash_profile?

No because homebrew puts pyenv's `bin` in the rest of the homebrew stuff that's already in your `$PATH`.
