### ISSUE TITLE
pyenv seems to break conda environments

### ISSUE THREAD

**Issue by panta** [pyenv/pyenv#1230]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): OS X El Capitan 10.11.6
- [x] OS architecture (e.g. amd64): intel i7
- [x] pyenv version: pyenv 1.2.7 (and pyenv-virtualenv 1.1.3) installed using Homebrew
- [x] Python version: latest Homebrew python (3.7.0 )and python@2 (2.7.15)
- [x] C Compiler information (e.g. gcc 7.3): cc -v: "Apple LLVM version 8.0.0 (clang-800.0.42.1)"
- [NA] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

Using e.g. with anaconda3-5.2.0, after creating and activating a conda environment, I still get python , pip, ... from the outer anaconda, not from the environment. So if I pip install something, it ends up inside the pyenv-managed anaconda, not inside the environment. The environment is reported as active though:

```bash
$ mkdir mytest ; cd mytest
$ pyenv install anaconda3-5.2.0
$ pyenv local anaconda3-5.2.0
$ conda create --mkdir --copy --name myenv
$ conda activate myenv
$ conda info --envs
# conda environments:
#
base                  /Volumes/UsersHD/Users/panta/.pyenv/versions/anaconda3-5.2.0
myenv              *  /Volumes/UsersHD/Users/panta/.pyenv/versions/anaconda3-5.2.0/envs/myenv

$ which python
/Volumes/UsersHD/Users/panta/.pyenv/shims/python
$ which pip
/Volumes/UsersHD/Users/panta/.pyenv/shims/pip

$ pip install numpy==1.15.2
```

then numpy 1.14.3 get uninstalled from the global anaconda installation, and 1.15.2 is installed in its place.
I've noticed that the `~/.pyenv/versions/anaconda3-5.2.0/envs/myenv` only contains a `conda-meta` directory, and not a `bin` one, which I would have expected among others.

The PATH seems to be correct:
```bash
$ echo $PATH
/Volumes/UsersHD/Users/panta/.pyenv/versions/anaconda3-5.2.0/envs/myenv/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.3/shims:/Volumes/UsersHD/Users/panta/.pyenv/shims:...
```

The very same thing happens if I use `pyenv activate anaconda3-5.2.0` instead of `pyenv local anaconda3-5.2.0`, and/or if I do `source activate myenv` instead of `conda activate myenv`.
I've also tried `conda create -n myenv` without the other options.

In any case, if I try to do `pyenv activate anaconda3-5.2.0/envs/myenv`, I get an error that `myenv` is not a virtualenv.

**Comment by lmmarsano** [comment]
I may have closed this prematurely.
#290 was recently merged into pyenv-virtualenv.
Does the issue persist?
