### ISSUE TITLE
Failed install on MacOS Mojave

### ISSUE THREAD

**Issue by sepulworld** [pyenv/pyenv#1232]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): MacOS 10.14.1 Mojave
- [ ] OS architecture (e.g. amd64): 1.3 GHz Intel Core m7
- [ ] pyenv version: 1.2.7
- [ ] Python version: 3.7.0
- [ ] C Compiler information (e.g. gcc 7.3):  x86_64-apple-darwin18.2.0
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

I am getting the following error 

```CPPFLAGS="-I/usr/local/opt/zlib/include" pyenv install -v 3.7.0```

Error:

```
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Could not install packages due to an EnvironmentError: [Errno 1] Operation not permitted: '/bin/easy_install-3.7'

make: *** [install] Error 1

BUILD FAILED (OS X 10.14.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/p5/6h8nvhms23l8ml5cy_5qjnhw0000gn/T/python-build.20181024170525.32944
Results logged to /var/folders/p5/6h8nvhms23l8ml5cy_5qjnhw0000gn/T/python-build.20181024170525.32944.log

Last 10 log lines:
		 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi
Looking in links: /var/folders/p5/6h8nvhms23l8ml5cy_5qjnhw0000gn/T/tmpcgee3vky
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Could not install packages due to an EnvironmentError: [Errno 1] Operation not permitted: '/bin/easy_install-3.7'

make: *** [install] Error 1
```

**Comment by ShaohongBai** [comment]
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

install SDK file manually will resolve the issue.

**Comment by Mpatidar059** [comment]
Its works fine.
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

**Comment by chandraprakashsoni** [comment]
It worked for me too. ✌️

**Comment by joshfriend** [comment]
Please follow the main thread for this issue at #1219
