### ISSUE TITLE
There is no tag for 1.2.8 version

### ISSUE THREAD

**Issue by Nklya** [pyenv/pyenv#1235]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
Hello.

Could you tag / release a 1.2.8 version of pyenv?

In https://github.com/pyenv/pyenv/blob/master/CHANGELOG.md latest version is 1.2.8, but in releases - 1.2.7 https://github.com/pyenv/pyenv/releases

Thank you!

**Comment by joshfriend** [comment]
https://github.com/Homebrew/homebrew-core/pull/33515

**Comment by Nklya** [comment]
Thanks!
