### ISSUE TITLE
Failed install on MacOS Mojave

### ISSUE THREAD

**Issue by n8henrie** [pyenv/pyenv#1236]
I'm failing to install multiple versions on Mojave (tried installing 3.7.1 and 3.6.6, both fail).

I use Homebrew, so my install command is:

```
PYENV_DEBUG=1 CFLAGS="-I$(brew --prefix openssl)/include" LDFLAGS="-L$(brew --prefix openssl)/lib" pyenv install 3.7.1
```

Debug output: https://pastebin.com/EHLh6hMR
Logfile: https://pastebin.com/QNG3Q93e

I've been using homebrew / pyenv for a few years now and this has usually worked.

After running into the issue, I followed the instructions for the missing SDK headers [from the wiki](https://github.com/pyenv/pyenv/wiki/Common-build-problems) -- no change.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS 10.4
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 1.2.8
- [x] Python version: Fails trying to install 3.7.1 and 3.6.6
- [x] C Compiler information (e.g. gcc 7.3): See below
- [x] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

```shellsession
$ clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ clang++ --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by n8henrie** [comment]
Same error with 10.14.1 (and XCode 10.1).

**Comment by punjab** [comment]
Same here on OS X 10.14.1. The issue however seem not to be with pyenv, but with the way new command line tools may have changed in the upgrade. `rbenv` for ruby is failing to install same way.

**Comment by caipre** [comment]
I was running into this as well, and noticed that my `ar` was `/usr/local/bin/ar` rather than the system `ar`. I ran `brew remove binutils` and was finally able to run `pyenv install 2.7.15` and `pyenv install 3.7.1` without problems . I had also upgraded to Xcode 10.1, but I think it was `binutils` that was giving me trouble. YMMV.

**Comment by n8henrie** [comment]
Removing `binutils` seems to have solved the issue. Thanks @caipre and @binbjz!

**Comment by chaitanya11** [comment]
I am facing issue with 10.14.3 mojave, 
Command : 
```
PYENV_DEBUG=1 CFLAGS="-I$(brew --prefix openssl)/include" LDFLAGS="-L$(brew --prefix openssl)/lib" pyenv install 3.5.0
```
[log file](https://pastebin.com/qNvv4Xv1)
[debug file](https://pastebin.com/tsvCbN8c)


```
$ clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ clang++ --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```


I tried removing 
```
$ brew remove binutils
Error: No such keg: /usr/local/Cellar/binutils
```

I have Xcode 10.1, Command Line tools 10.1

**Comment by rezhajulio** [comment]
Wow, amazing! This solved my issued that has been happening for months. Thanks guys!

**Comment by flyjump** [comment]
`brew install zlib`  
`ln -s /usr/local/Cellar/zlib/1.2.11/include/* /usr/local/include`
`brew install 3.7.2`
### 1.2.21 is your zlib version that is your installed zlib version
