### ISSUE TITLE
`pyenv global system` does not change global pip version

### ISSUE THREAD

**Issue by NatTupper** [pyenv/pyenv#1238]
### Description
- Platform information: Arch Linux
- OS architecture: x86_64
- pyenv version: 1.2.8
- Python version: 3.7.1
- C Compiler information: 8.2.1+20180831
- Problem: `pyenv global system` does not revert pip and pip3 to the system version of pip.

Here's some outputs of pyenv commands:

```
$ pyenv versions
* system (set by /home/nat/.pyenv/version)
  3.5.3
  3.6.6
$ pyenv global system
$ python --version
Python 3.7.1
$ pip --version
pip 18.0 from /home/nat/.local/lib/python3.6/site-packages/pip (python 3.6)
$ pip3 --version
pip 18.0 from /home/nat/.local/lib/python3.6/site-packages/pip (python 3.6)
```

As you can see, the python binary is correctly set to the system version but pip and pip3 versions remain at 3.6.6. It does correctly set the pip and pip3 paths on 3.6.6 and 3.5.3, but `pyenv global system` always sets pip and pip3 at the 3.6.6 installations.

**Comment by ntrepid8** [comment]
Are you sure those are not just user installed versions of `pip`? I think if you install a user copy of pip like this:
```
$ pip install --user pip
```

You'll get an executable in your `~/.local/bin` and if that's part of your `PATH` then it will still show up there when you switch away from a `pyenv` managed version. If your paths had not reverted back to system standard I think your path to `pip` would be something like this:
```
~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pip
```

**Comment by damon-kwok** [comment]
+1 
I recommend removing the built-in pip, which is installed by the user.

**Comment by ryanermita** [comment]
> Are you sure those are not just user installed versions of `pip`? I think if you install a user copy of pip like this:
> 
> ```
> $ pip install --user pip
> ```
> 
> You'll get an executable in your `~/.local/bin` and if that's part of your `PATH` then it will still show up there when you switch away from a `pyenv` managed version. If your paths had not reverted back to system standard I think your path to `pip` would be something like this:
> 
> ```
> ~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pip
> ```

is there a way to remove the user installed pip? i tried `pip uninstall pip` but it does not fixed the issue. currently the workaround for this is to use python command to install the package to the local pyenv versionL: `python -m pip install <package>`

**Comment by ryanermita** [comment]
on my case, I solved this by moving this code snippet below from `.zshenv` to `.zshrc`
```
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
```

**Comment by LounisBou** [comment]
Manage to do it by overriding pip command with alias.

pip="python -m pip"

If it can help some of you dudes.
