### ISSUE TITLE
`pyenv update` does not fetch tags, causing `pyenv` to display the wrong version number.

### ISSUE THREAD

**Issue by ksze** [pyenv/pyenv#1243]
This seems to be a bug with the pyenv update plugin. However, the github repo for the update plugin does not allow opening issues, so I'm reporting here.

### Description
Platform: Raspbian (armv7 based on Debian 9 Stretch) and Ubuntu 18.04 (x86_64)
pyenv version: actually 1.2.8, but the `pyenv` command keeps displaying an old version number
pyenv plugin: commit `86dc16f841b2520c872945464d709cf8fdb40cf9`

`pyenv update` pulls the commits of the master branch for the main pyenv repo, and for each of the plugin repos. However, tags are not fetched. The end result is that `pyenv` keeps displaying an old version number like `1.2.2-84-g80414b1`, even though `~/.pyenv` is actually already fast-forwarded to commit `80414b1b5b231faecdb0795a9aa81ba5bfc1d487`, which corresponds to version 1.2.8.

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv-update/blob/0f5bc93811be86e129ceb5fa01e0400f3d81aa19/bin/pyenv-update#L57
