### ISSUE TITLE
Cannot install/build any Python version on macOS High Sierra

### ISSUE THREAD

**Issue by cjbischoff** [pyenv/pyenv#1245]
### Description
- [x] Platform information: `OS X 10.13.6 using python-build 20180424`
- [x] OS architecture: `Darwin platform.local 17.7.0 Darwin Kernel Version 17.7.0: Wed Oct 10 23:06:14 PDT 2018; root:xnu-4570.71.13~1/RELEASE_X86_64 x86_64 & i386`
- [x] pyenv version: `pyenv 1.2.8`
- [x] Python version: `3.6.7`
- [x] C Compiler information:

   ```
   Apple LLVM version 10.0.0 (clang-1000.11.45.5)
   Target: x86_64-apple-darwin17.7.0
   Thread model: posix
   InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
   ```

- [x] Please attach verbose build log as gist :https://gist.github.com/cjbischoff/7a6e742f489e671f670f88528e8c1855

**Comment by adonig** [comment]
Same problem here on OS X 10.14.1 Mojave. Cannot build any Python version. Build process fails with missing symbols even after installing [the additional SDK headers](https://github.com/pyenv/pyenv/wiki/Common-build-problems) and reinstalling binutils :-(

**Comment by mmerickel** [comment]
> EDIT: Removing binutils solved the problem for me: brew remove binutils

This also worked for me.

**Comment by socketbox** [comment]
> Same problem here on OS X 10.14.1 Mojave. Cannot build any Python version. Build process fails with missing symbols even after installing [the additional SDK headers](https://github.com/pyenv/pyenv/wiki/Common-build-problems) and reinstalling binutils :-(
> 
> **EDIT: Removing binutils solved the problem for me: `brew remove binutils`**

Very interested in how @adonig came to discover that this was the problem. Could you give some insight as to how you tracked the issue back to `binutils`? I had thought it was an issue with flags being passed to the "native" `ld` (ie. the one at `/usr/bin/ld`).

**Comment by fpatz** [comment]
Root cause for this is that the system `ar` is shadowed by binutils. The `libpythonX.Ym.a` produced by binutils' `ar` cannot be used for linking. Verified by building with `AR=/usr/bin/ar`. I'd suggest explicitly   setting `AR` for macOS builds or at least placing a hint in the installation instructions (... or marking binutils incompatible with pyenv, if that can be done with Homebrew?).

**Comment by dmhenry** [comment]
@fpatz, I've seen references to building with `AR=/usr/bin/ar` in other places as well, but I'm not clear on how to do that. Can you tell me? I'm new to Python and trying to figure out the tooling. I'm trying to `pyenv install 3.6.8`. Can I pass this here somehow? Thanks in advance!

**Comment by fpatz** [comment]
Simply prefix the command: `AR=/usr/bin/env pyenv install ...`. This sets `AR` for that invocation of `pyenv`. Or (temporarily) `brew uninstall binutils`, if that is where `ar` is coming from (you can check with `which ar` -- if it says `/usr/local/bin/ar` you probably have binutils installed).

**Comment by cjbischoff** [comment]
brew remove binutils that worked also

**Comment by DavidAntliff** [comment]
FWIW, `AR=/usr/bin/ar pyenv install 3.7.2` worked for me (avoided having to uninstall binutils).

**Comment by purp** [comment]
`AR=...` was not successful for me. 

My steps:

* `brew uninstall binutils`
* download and install [Mac OS 10.14 command line tools for Xcode 10.2](https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_macOS_10.14_for_Xcode_10.2/Command_Line_Tools_macOS_10.14_for_Xcode_10.2.dmg) manually (for some reason `xcode-select --install` didn't do the magic for me)
* `sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /` after installing command line tools, per [Common Build Problems](https://github.com/pyenv/pyenv/wiki/common-build-problems) 

All better now.

**Comment by crazymeng4586** [comment]
> Same problem here on OS X 10.14.1 Mojave. Cannot build any Python version. Build process fails with missing symbols even after installing [the additional SDK headers](https://github.com/pyenv/pyenv/wiki/Common-build-problems) and reinstalling binutils :-(
> 
> **EDIT: Removing binutils solved the problem for me: `brew remove binutils`**

THANKS BRO,This also worked for me. :)👍👍👍👍👍

**Comment by haydenk** [comment]
Uninstalling `binutils` works on macOS 10.15 (Catalina)  as well, were we do not have the `macOS_SDK_headers_for_macOS_10.14.pkg` available.

**Comment by XxUnkn0wnxX** [comment]
for Catalina the headers are located somewhere noted here: https://bbqsoftwares.com/blog/xdebug-catalina-issue

since the "macOS_SDK_headers_for_macOS_10.15" doesnt exsist & /usr/include has been removed
the new location is `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include` as of xcode 11.

**Comment by matzeschmo** [comment]
Thanks a lot @fpatz. Had the same problem today with MacOS Mojave (10.14.4).
`export AR=/usr/bin/ar` solved the problem and installing with `pyenv install 3.8.2` finally worked! 👍

**Comment by weaming** [comment]
Same for https://github.com/pyenv/pyenv/issues/2441 , incorrect `ar`, aha
