### ISSUE TITLE
pyenv points Qt to the system libraries instead of the libraries inside virtualenv

### ISSUE THREAD

**Issue by rominf** [pyenv/pyenv#1249]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): openSUSE Tumbleweed 20181126
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: pyenv 1.2.2-1845-gec9fb549
- [x] Python version: Python 3.6.7
- [x] C Compiler information (e.g. gcc 7.3): gcc 8.2.1
- [x] Please attach verbose build log as gist: Irrelevant
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

I'm using `pyinstaller` to package my application. I faced problems with PyQt5: https://github.com/pyinstaller/pyinstaller/issues/3891, https://github.com/pyinstaller/pyinstaller/issues/3894.

The reason is that `pyenv` points Qt to system libraries instead of the libraries inside virtualenv.

**Comment by chrahunt** [comment]
If anywhere this belongs in the issues for [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv), as pyenv itself does not manage virtual environments.

I will offer a few words that may help you debug:

1. Make sure before you run pyinstaller that the virtual environment is actually activated
2. Make sure that PyQt is installed in the virtual environment
3. Try manually activating the virtual environment (`. /home/rominf/.pyenv/versions/kama-vault/bin/activate`) and then running the script provided in pyinstaller/pyinstaller#3894 and see if that helps (that may indicate an issue in how pyenv-virtualenv activates the virtual environment).
