### ISSUE TITLE
Removing pyenv does not update $PATH

### ISSUE THREAD

**Issue by siddhantgoel** [pyenv/pyenv#1251]
I'm using `zsh` and have been trying to uninstall `pyenv`. As per the README, I removed the `export PATH=...` and `pyenv init` lines from my `.zshenv`, and deleted the `~/.pyenv` folder completely.

I've restarted the shell a couple of times, just to be safe, but the following paths are still present in the `$PATH` variable.

```
/home/siddhant/.pyenv/plugins/pyenv-virtualenv/shims
/home/siddhant/.pyenv/shims
/home/siddhant/.pyenv/bin
```

There are no references to `pyenv` anymore in the `.zshenv` and `.zshrc` files, so I'm curious if I missed a step? Thank you!

**Comment by chrahunt** [comment]
This looks like an environment issue (something leftover in an init file) not a pyenv one, but to help debug:

1. Trace environment variables as early in the init process as possible. The man page indicates that `/etc/zshenv` is the first file read so at the top of that put `env | sort > ~/env.txt`. Check that the `PATH` does not have the indicated paths. If it does then the environment under which your shell is executing already has the path (so it might be coming from something like e.g. .xinit).
2. Invoke your shell like `zsh --login -x` which should source init files and trace each line as it executed. Search for instances of `pyenv` in the output. If it helps you can also `echo` at the top of each file that gets sourced at started so you can narrow down at least which file the command is in.

**Comment by siddhantgoel** [comment]
I tried those steps but couldn't find any `pyenv` related output. But then I restarted the system and now `$PATH` seems to be clean. No idea what happened there, but please feel free to close this issue. Thanks for the help anyway!

**Comment by sannawag** [comment]
> I tried those steps but couldn't find any `pyenv` related output. But then I restarted the system and now `$PATH` seems to be clean. No idea what happened there, but please feel free to close this issue. Thanks for the help anyway!

Thanks, this worked for me, too! I just had to restart the terminal, not the whole system.
