### ISSUE TITLE
pyenv install 3.6.4 error   ubuntu18

### ISSUE THREAD

**Issue by peiyanyan** [pyenv/pyenv#1252]
Last 10 log lines:
    sys.exit(ensurepip._main())
  File "/tmp/python-build.20181205191917.2485/Python-3.6.4/Lib/ensurepip/__init__.py", line 204, in _main
    default_pip=args.default_pip,
  File "/tmp/python-build.20181205191917.2485/Python-3.6.4/Lib/ensurepip/__init__.py", line 117, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/tmp/python-build.20181205191917.2485/Python-3.6.4/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip
zipimport.ZipImportError: can't decompress data; zlib not available
Makefile:1099: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by agibalov** [comment]
I had the same issue with Python 3.7.1 and Ubuntu 18.04. Installing the dependencies listed here: https://github.com/pyenv/pyenv/wiki/common-build-problems made it work.

**Comment by ziofil** [comment]
Same issue here, but on macOS 10.14.1, so it could be unrelated to the operating system.
I installed zlib with homebrew, but it didn't help

**Comment by jcrben** [comment]
Same - with NixOS things like this are a bit tricker. CPPFLAGS="-I/nix/store/nkpciwh3zkjvl8nm1a9hx3zy2vz7z4qn-zlib-1.2.11/lib" pyenv install 3.6.6` did not work.

**Comment by chrahunt** [comment]
@peiyanyan, please ensure the dependencies listed [here](https://github.com/pyenv/pyenv/wiki/common-build-problems) are satisfied (thanks @agibalov). If you still experience issues, please feel free to create a new issue and include verbose logs.

@ziofil, please see the information [here](https://github.com/pyenv/pyenv/wiki/common-build-problems#build-failed-error-the-python-zlib-extension-was-not-compiled-missing-the-zlib) for getting correct zlib on macOS. Specifically, you need to execute the install like `CPPFLAGS="-I$(brew --prefix zlib)/include"`. Also check out #1219 which may be related.
