### ISSUE TITLE
Can't install Python 3.7.0+: implicit declaration of function 'utimensat' is invalid in C99

### ISSUE THREAD

**Issue by kirillzh** [pyenv/pyenv#1253]
Command used: `env PYENV_DEBUG=1 pyenv install 3.7.0`
However, I am able to successful to install any Python version lower than `3.7.0`, for example `3.6.7`.

Error message:
```
Last 10 log lines:
./Modules/posixmodule.c:4527:12: error: implicit declaration of function 'utimensat' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return utimensat(DEFAULT_DIR_FD, path, time, AT_SYMLINK_NOFOLLOW);
           ^
./Modules/posixmodule.c:4543:12: error: implicit declaration of function 'utimensat' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return utimensat(DEFAULT_DIR_FD, path, time, 0);
           ^
```

### Description
- Platform information: macOS 10.14.2 (18C54)
- OS architecture: i386
- pyenv version: 1.2.8
- Python version: 2.7.10 (built-in)
- C Compiler information: 4.2.1 (comes from Xcode)

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

### Logs:
[pyenv_output.log](https://github.com/pyenv/pyenv/files/2692054/pyenv_output.log)
[pyenv_full_logs.log](https://github.com/pyenv/pyenv/files/2692058/pyenv_full_logs.log)

**Comment by Mat001** [comment]
Hey @kirillzh have you manage to resolve this? I'm getting the same error. Thx

**Comment by kirillzh** [comment]
Hey @Mat001,
I haven't attempted to solve this, ended up using Python 3.6.7.

**Comment by native-api** [comment]
Same as https://github.com/pyenv/pyenv/issues/1737, these MacOS versions aren't supported by older Pythons.
