### ISSUE TITLE
Pyenv picks OpenSSL version which is too new from Linuxbrew

### ISSUE THREAD

**Issue by thedrow** [pyenv/pyenv#1261]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu Linux 18.04
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 1.2.8
- [x] Python version: Any below 3.7.x
- [x] C Compiler information (e.g. gcc 7.3): gcc (Homebrew gcc 5.5.0_4) 5.5.0
- [x] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

https://gist.github.com/thedrow/5420b3f477151d77542ec1df79301297#file-gistfile1-txt-L1212

Linuxbrew has 1.0.2q_1 installed which is far too new for for anything other than Python 3.7.x.
Pyenv should prefer the system OpenSSL in that case.

**Comment by thedrow** [comment]
This is possibly related to #1241 but I'm not sure.

**Comment by al45tair** [comment]
@thedrow No, #1241 is Mac specific.

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/wiki/Common-build-problems#2-your-openssl-version-is-incompatible-with-the-python-version-youre-trying-to-install

**Comment by thedrow** [comment]
@native-api I don't understand why we can't just fix this to pick the right OpenSSL version.

**Comment by native-api** [comment]
@thedrow Pyenv doesn't know which OpenSSL version(s) your Python needs.

**Comment by native-api** [comment]
I don't see any realistic way to "fix that". We're already doing the best we can do so AFAICS there's nothing to "fix".

We basically look in some OS-specific default locations and pick the first one we find. If the user wishes for something else or it's not there, we require a user to supply the path to it manually. This is what all builds do when they search for dependencies.

* If we search anywhere else, there'll be no way to say if what we find is binary-compatible or is a good pick for the system setup (note that Python will be dynamically linked to it -- so wherever it is, it must stay there, undefinitely and largely unchanged)
* Python doesn't provide a good way to find out which OpenSSL releases a specific Python release is compatible with. Even if it's from the right version line, there may be unfixed bugs or missing features.
* Even if the library version number is right, it might've been configured without some features that Python needs ([one example](https://github.com/pyenv/pyenv/issues/1529))

As you can see, even if we implement some "intelligent" picking logic, it would still not be sufficient to guarantee that the pick would be good and the setup with it maintainable. So all the added complexity will be for nothing and a recipe for disaster.

**Comment by al45tair** [comment]
@native-api Certainly on macOS, pyenv grabs and builds a newer OpenSSL. Or used to (I haven't checked recently). It then fails to actually use it, and then the build fails unless you have something else installed, which is what my changeset was all about. That probably should be fixed — it makes no sense downloading and building a newer OpenSSL only to then ignore it and fail unless the user already has a newer version installed somewhere with e.g. brew.

**Comment by native-api** [comment]
@al45tair Your PR has nothing to do with this issue. I've commented there.
