### ISSUE TITLE
PYENV_ROOT disabling pyenv install command

### ISSUE THREAD

**Issue by gleopoldo** [pyenv/pyenv#1264]
### Description
- [x] Platform information: Debian Wheezy 7.11
- [x] OS architecture: amd64
- [x] pyenv version: 1.2.8
- [x] Python version: (installing yet)
- [x] C Compiler information (e.g. gcc 7.3): gcc 7.3.0 

Hello!

I'm experiencing an curious issue, and I want to ask you guys if this is a desired behavior. I'm attempting to install a python binary on a specific folder so that I can ship my python application as a debian package. Following the project's docs I've used the `PYENV_ROOT` variable in order to set them.

Hovewer, setting it seems to disable the "install" option. Is that a bug or I'm making a mistake? 

```
$ pyenv
pyenv 1.2.8
Usage: pyenv <command> [<args>]

Some useful pyenv commands are:
   commands    List all available pyenv commands
   local       Set or show the local application-specific Python version
   global      Set or show the global Python version
   shell       Set or show the shell-specific Python version
   install     Install a Python version using python-build
   uninstall   Uninstall a specific Python version
   rehash      Rehash pyenv shims (run this after installing executables)
   version     Show the current Python version and its origin
   versions    List all Python versions available to pyenv
   which       Display the full path to an executable
   whence      List all Python versions that contain the given executable

See `pyenv help <command>' for information on a specific command.
For full documentation, see: https://github.com/pyenv/pyenv#readme

$ export PYENV_ROOT=.venv
$ pyenv
pyenv 1.2.8
Usage: pyenv <command> [<args>]

Some useful pyenv commands are:
   commands    List all available pyenv commands
   local       Set or show the local application-specific Python version
   global      Set or show the global Python version
   shell       Set or show the shell-specific Python version
   rehash      Rehash pyenv shims (run this after installing executables)
   version     Show the current Python version and its origin
   versions    List all Python versions available to pyenv
   which       Display the full path to an executable
   whence      List all Python versions that contain the given executable

See `pyenv help <command>' for information on a specific command.
For full documentation, see: https://github.com/pyenv/pyenv#readme
```

**Comment by chrahunt** [comment]
This is expected, as mentioned in the [installation instructions](https://github.com/pyenv/pyenv/tree/6309aaf295b05fece4abb52ba1000f98e40390e7#basic-github-checkout) `$PYENV_ROOT` is meant to represent the root of the cloned repository.

If you want to compile Python and specify the output directory, then look at [`python-build`](https://github.com/pyenv/pyenv/tree/6309aaf295b05fece4abb52ba1000f98e40390e7/plugins/python-build), which `pyenv install` uses internally.

**Comment by gleopoldo** [comment]
Nice! Tks @chrahunt. I'm going to look at it.
