### ISSUE TITLE
"ar: internal ranlib command failed" building 3.6.8 on MacOS Mojave

### ISSUE THREAD

**Issue by colwem** [pyenv/pyenv#1267]
I have googled this error and found nothing.  I've followed all the troubleshooting steps in the wiki.  I've searched all your issues for either "ar" or "ranlib" or "libpython3.6.m.a".  I have found nothing.  Do you have any idea what could be happening here.  I've also tried building 3.6.7 and the same kind of error.  This "ar: internal ranlib command failed" error on "Libpython3.6m.a"

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [?] Make sure you are not asking us to help solving your specific issue. *Maybe?*
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [?] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [?] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information: MacOS Mojave Version 10.14.2
- [x] OS architecture: x86_64 (I think this is what you want?)
- [x] pyenv version: 1.2.9
- [x] Python version: 3.6.8
- [x] C Compiler information: I'm thinking it's clang version 10.0.0 
- [x] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

[Verbose Log](https://gist.github.com/colwem/9ca4e0f672f29d568a03b141757f6a8c)

Regular output from running command.

```
❯ pyenv install 3.6.8
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.6.8.tar.xz...
-> https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tar.xz
Installing Python-3.6.8...
python-build: use readline from homebrew

BUILD FAILED (OS X 10.14.2 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/9d/d6bmpjk13zs7jp1r2mhl20d80000gn/T/python-build.20190113193000.98851
Results logged to /var/folders/9d/d6bmpjk13zs7jp1r2mhl20d80000gn/T/python-build.20190113193000.98851.log

Last 10 log lines:
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall    -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes   -I. -I./Include -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/Users/colwem/.pyenv/versions/3.6.8/include  -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/Users/colwem/.pyenv/versions/3.6.8/include   -DPy_BUILD_CORE \
	      -DGITVERSION="\"`LC_ALL=C `\"" \
	      -DGITTAG="\"`LC_ALL=C `\"" \
	      -DGITBRANCH="\"`LC_ALL=C `\"" \
	      -o Modules/getbuildinfo.o ./Modules/getbuildinfo.c
rm -f libpython3.6m.a
ar rcs libpython3.6m.a Modules/getbuildinfo.o Parser/acceler.o Parser/grammar1.o Parser/listnode.o Parser/node.o Parser/parser.o Parser/bitset.o Parser/metagrammar.o Parser/firstsets.o Parser/grammar.o Parser/pgen.o Parser/myreadline.o Parser/parsetok.o Parser/tokenizer.o Objects/abstract.o Objects/accu.o Objects/boolobject.o Objects/bytes_methods.o Objects/bytearrayobject.o Objects/bytesobject.o Objects/cellobject.o Objects/classobject.o Objects/codeobject.o Objects/complexobject.o Objects/descrobject.o Objects/enumobject.o Objects/exceptions.o Objects/genobject.o Objects/fileobject.o Objects/floatobject.o Objects/frameobject.o Objects/funcobject.o Objects/iterobject.o Objects/listobject.o Objects/longobject.o Objects/dictobject.o Objects/odictobject.o Objects/memoryobject.o Objects/methodobject.o Objects/moduleobject.o Objects/namespaceobject.o Objects/object.o Objects/obmalloc.o Objects/capsule.o Objects/rangeobject.o Objects/setobject.o Objects/sliceobject.o Objects/structseq.o Objects/tupleobject.o Objects/typeobject.o Objects/unicodeobject.o Objects/unicodectype.o Objects/weakrefobject.o Python/_warnings.o Python/Python-ast.o Python/asdl.o Python/ast.o Python/bltinmodule.o Python/ceval.o Python/compile.o Python/codecs.o Python/dynamic_annotations.o Python/errors.o Python/frozenmain.o Python/future.o Python/getargs.o Python/getcompiler.o Python/getcopyright.o Python/getplatform.o Python/getversion.o Python/graminit.o Python/import.o Python/importdl.o Python/marshal.o Python/modsupport.o Python/mystrtoul.o Python/mysnprintf.o Python/peephole.o Python/pyarena.o Python/pyctype.o Python/pyfpe.o Python/pyhash.o Python/pylifecycle.o Python/pymath.o Python/pystate.o Python/pythonrun.o Python/pytime.o Python/random.o Python/structmember.o Python/symtable.o Python/sysmodule.o Python/traceback.o Python/getopt.o Python/pystrcmp.o Python/pystrtod.o Python/pystrhex.o Python/dtoa.o Python/formatter_unicode.o Python/fileutils.o Python/dynload_shlib.o   Python/thread.o  Modules/config.o Modules/getpath.o Modules/main.o Modules/gcmodule.o Modules/_threadmodule.o  Modules/posixmodule.o  Modules/errnomodule.o  Modules/pwdmodule.o  Modules/_sre.o  Modules/_codecsmodule.o  Modules/_weakref.o  Modules/_functoolsmodule.o  Modules/_operator.o  Modules/_collectionsmodule.o  Modules/itertoolsmodule.o  Modules/atexitmodule.o  Modules/signalmodule.o  Modules/_stat.o  Modules/timemodule.o  Modules/_localemodule.o  Modules/_iomodule.o Modules/iobase.o Modules/fileio.o Modules/bytesio.o Modules/bufferedio.o Modules/textio.o Modules/stringio.o  Modules/zipimport.o  Modules/faulthandler.o  Modules/_tracemalloc.o Modules/hashtable.o  Modules/symtablemodule.o  Modules/xxsubtype.o Python/frozen.o
/opt/local/bin/ranlib: object: libpython3.6m.a(getbuildinfo.o) malformed object (unknown load command 1)
ar: internal ranlib command failed
make: *** [libpython3.6m.a] Error 1
```

**Comment by joshfriend** [comment]
I [googled your error message](https://www.google.com/search?q=ranlib%3A+object%3A+libpython3.6m.a(getbuildinfo.o)+malformed+object+(unknown+load+command+1)) and the results suggest that your xcode command line tools is old or broken and you should try reinstalling it.

**Comment by yyuu** [comment]
closing as this is not a pyenv's issue

**Comment by playpauseandstop** [comment]
I ran into similar problem on macOS 10.14.3 and managed to fix it with,

1. Upgrade [brew](https://github.com/Homebrew/homebrew-core) to latest version with `brew upgrade`
2. Remove `cctools`, which was recently [removed](https://github.com/Homebrew/homebrew-core/commit/4e21da591aaffc9021a4d5ccdb4ee64c40b724a5) from `brew`, with `brew uninstall -f cctools`

----

@colwem 

I understand from your message that you didn't use `ranlib` from brew as it points to,

- `/opt/local/bin/ranlib`

not to,

- `/usr/local/Cellar/cctools/855/bin/ranlib` (_as it was in my case_)

but maybe removing `ranlib` from `/opt/local/bin` and using system `/usr/bin/ranlib` fix the issue for you as well.

**Comment by colwem** [comment]
Yes, sorry, I should have commented that I eventually solved this.  the problem was an old macports installation.  That's why it was using `/opt/local/bin/ranlib` turns out everything in `/opt/local/bin` comes from macports.  You really shouldn't be using macports and homebrew at the same time apparently haha.

**Comment by mehsanib** [comment]
I get similar error "internal ranlib command failed " when getting parallelism for blis installation: running "make -j8".  I have brew installed but I don't know about macports or cctools....  How did you solve the problem?

**Comment by qihboy** [comment]
> I ran into similar problem on macOS 10.14.3 and managed to fix it with,
> 
> 1. Upgrade [brew](https://github.com/Homebrew/homebrew-core) to latest version with `brew upgrade`
> 2. Remove `cctools`, which was recently [removed](https://github.com/Homebrew/homebrew-core/commit/4e21da591aaffc9021a4d5ccdb4ee64c40b724a5) from `brew`, with `brew uninstall -f cctools`
> 
> @colwem
> 
> I understand from your message that you didn't use `ranlib` from brew as it points to,
> 
> * `/opt/local/bin/ranlib`
> 
> not to,
> 
> * `/usr/local/Cellar/cctools/855/bin/ranlib` (_as it was in my case_)
> 
> but maybe removing `ranlib` from `/opt/local/bin` and using system `/usr/bin/ranlib` fix the issue for you as well.

This saved my life!!!
envs:
MacOS Big Sur 11.3
