### ISSUE TITLE
SONAME bump in readline.so requires recompiling all python versions

### ISSUE THREAD

**Issue by fofoni** [pyenv/pyenv#1270]
(I'm listing my info here because it's required, but I believe this problem happens in pretty much any pyenv installation that aims to survive an OS upgrade.)
- [x] Platform information (e.g. Ubuntu Linux 16.04): Arch Linux
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 1.2.9
- [x] Python version: 3.7.2
- [x] C Compiler information (e.g. gcc 7.3): `[GCC 8.2.1 20181127] on linux`

Whenever the OS pushes a soname bump in readline (e.g., Arch Linux recently dropped `readline.so.7` in favor of `readline.so.8`), all python versions/virtualenvs must be recompiled against the new library if the interactive REPL is expected to provide [command-line editing and history][1]. If the user tries to use the python binary that was compiled against the old soname, up and down keys, as well as other history related features, won't work:
```
>>> ^[[A^[[A^[[B^[[B
>>> ^R
```
It's easy to check that the soname bump is the problem:
```
$ python -c 'import readline'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libreadline.so.7: cannot open shared object file: No such file or directory
$ ls /lib/libreadline.so*
/lib/libreadline.so  /lib/libreadline.so.8  /lib/libreadline.so.8.0
```

By the very nature of pyenv, I don't think that this is an easy problem to solve. However, there's also no mention to this problem anywhere in the documentation (at least, I haven't seen it). I believe that it should be mentioned in the README and explained in the wiki, or something like that.

[1]: https://docs.python.org/3.7/tutorial/interactive.html

**Comment by jaymzcd** [comment]
I had the same problem after major `brew update`s on my local packages on Mac OS. I "solved" it by removing `pyenv` entirely and just re-installing the versions I needed after reading your comment.

i.e.

```
rm -fr ~/.pyenv/
pyenv install 3.5.2
```

Then I was able to get `pytest --pdb` working again. Thanks for the heads up as to what the solution could be 👍

**Comment by fofoni** [comment]
No need to remove the whole pyenv installation, though. Just `pyenv uninstall 3.7.2` and `pyenv install 3.7.2` worked for me.

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/wiki/Common-build-problems#python-cannot-find-a-dependent-dynamic-library-even-though-its-installed
