### ISSUE TITLE
Beginner Issue: Coloring misguiding

### ISSUE THREAD

**Issue by niccokunzmann** [pyenv/pyenv#1271]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): Debian 6
- [ ] OS architecture (e.g. amd64): amd64
- [ ] pyenv version: 
- [ ] Python version:
- [ ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

```
pipenv install --dev
Warning: Python 3.7 was not found on your system…
Would you like us to install CPython 3.7.2 with pyenv? [Y/n]: Y
Installing CPython 3.7.2 with pyenv (this may take a few minutes)…
✘ Failed... 
Something went wrong…
Downloading Python-3.7.2.tar.xz...
-> https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
Installing Python-3.7.2...
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (Debian 8.11 using python-build 1.2.9-2-g6309aaf)

Inspect or clean up the working tree at /tmp/python-build.20190122213603.7692
Results logged to /tmp/python-build.20190122213603.7692.log

Last 10 log lines:
		install|*) ensurepip="" ;; \
	esac; \
	 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
Looking in links: /tmp/tmp2ob0e76h
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-18.1 setuptools-40.6.2

Warning: The Python you just installed is not available on your PATH, apparently.
```

**Problem**: The last and the first line of the text is red. The helpful text "https://github.com/pyenv/pyenv/wiki/Common-build-problems" however is embedded in source code below and paths above.
**Consequence**: I install it several times until I read what is important.
**Possible Solution**: The link could also be red. OR the warning below mentions the install problem.

**Comment by native-api** [comment]
The Wiki message is right after the errors and separated by blank lines -- so prominent enough in my book.

Submit a PR is you can think of something better...
