### ISSUE TITLE
Security: Automatically update pip as a post-install step

### ISSUE THREAD

**Issue by mcandre** [pyenv/pyenv#1272]
### Summary

When pyenv installs a version of Python and pip, it often leaves that pip version alone, including any vulnerabilities it may have. As a security practice, pyenv could go ahead and perform `pip install --upgrade pip` as a post-install step, to ensure that a more secure edition of pip is available by default.

### Prerequisite

* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description

- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS Mojave
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 3.4.3
- [x] Python version: 3.4.3
- [x] C Compiler information (e.g. gcc 7.3): Apple LLVM version 10.0.0 (clang-1000.10.44.4)

**Comment by chrahunt** [comment]
This would not do anything for the pip installed in virtual environments by `venv`/`ensurepip`. Users would still be required to manually upgrade pip after creating a virtual environment.

**Comment by chrahunt** [comment]
From [this](https://stackoverflow.com/a/28210626/1698058) SO post there's an example of how we may ensure that the upgrade also applies to new virtual environments:

```diff
diff -ru Python-3.7.1/Lib/ensurepip/__init__.py Python-3.7.1.new/Lib/ensurepip/__init__.py
--- Python-3.7.1/Lib/ensurepip/__init__.py  2018-10-20 06:04:19.000000000 +0000
+++ Python-3.7.1.new/Lib/ensurepip/__init__.py  2018-11-27 02:36:19.301655008 +0000
@@ -8,9 +8,9 @@
 __all__ = ["version", "bootstrap"]
 
 
-_SETUPTOOLS_VERSION = "39.0.1"
+_SETUPTOOLS_VERSION = "40.6.2"
 
-_PIP_VERSION = "10.0.1"
+_PIP_VERSION = "18.1"
 
 _PROJECTS = [
     ("setuptools", _SETUPTOOLS_VERSION),
Only in Python-3.7.1/Lib/ensurepip/_bundled: pip-10.0.1-py2.py3-none-any.whl
Only in Python-3.7.1.new/Lib/ensurepip/_bundled: pip-18.1-py2.py3-none-any.whl
Only in Python-3.7.1/Lib/ensurepip/_bundled: setuptools-39.0.1-py2.py3-none-any.whl
Only in Python-3.7.1.new/Lib/ensurepip/_bundled: setuptools-40.6.2-py2.py3-none-any.whl
```

However these are `_`-prefixed so may change at any time - we would need to keep a Python-specific implementation around.

@yyuu, WDYT?

**Comment by yyuu** [comment]
Generally speaking, management of libraries (including a tool that manages libraries) is a responsibility of users. I think, doing too much into ensurepip would be overkill, or, it will come up as extra maintainance cost which we cannot pay for. Let's ask users to do upgrade of pip as needed.

**Comment by chrahunt** [comment]
pip itself warns on each usage when an upgraded version is available, that should be enough.

Thanks @mcandre for the suggestion!
