### ISSUE TITLE
Add LC_ALL=C to suggested env vars for debugging

### ISSUE THREAD

**Issue by chrahunt** [pyenv/pyenv#1280]
### Description

When troubleshooting issues it would be good to ensure that the locale does not impact error messages. See the logs from #1279 [here](https://gist.github.com/MikHulk/8229e36a33f9ae958a86ae5d84d08449) for an example.

This should just need to be updated in `.github/ISSUE_TEMPLATE.md`.

**Comment by native-api** [comment]
You sure about that?
* It affects error messages but it could just as well affect application behavior which is a no-no when you're diagnosing it.
* With Google Translate, it's not too hard to decipher error messages even if you don't speak the language.
* And tracing provides enough info to see which code they're coming from.
