### ISSUE TITLE
Problem installing in MacOs Mojave

### ISSUE THREAD

**Issue by chaitanya11** [pyenv/pyenv#1281]
I am facing issue with 10.14.3 mojave, 
Command : 
```
PYENV_DEBUG=1 CFLAGS="-I$(brew --prefix openssl)/include" LDFLAGS="-L$(brew --prefix openssl)/lib" pyenv install 3.5.0
```
[log file](https://pastebin.com/qNvv4Xv1)
[debug file](https://pastebin.com/tsvCbN8c)

```
$ clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ clang++ --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I tried removing 
```
$ brew remove binutils
Error: No such keg: /usr/local/Cellar/binutils
```

I have Xcode 10.1, Command Line tools 10.1

**Comment by davemo** [comment]
Hi @chaitanya11, I had this exact same problem today and was able to fix it by removing my manually installed version of `pyenv` using git, and reinstalling with `brew install pyenv`.

Once I had the homebrew version of pyenv installed my installation commands worked.

I think the bug must be with assuming some context on the homebrew installation even for git cloned versions of pyenv.

**Comment by ThomasPaugam** [comment]
Hi, after many manipulation i find this and it's worked form me : 
https://github.com/pyenv/pyenv/issues/1201#issuecomment-415349344

**Comment by chaitanya11** [comment]
I am still facing the same problem, even after removing manually install pyenv from machine.

**Comment by by-axis41** [comment]
Also getting pyenv install errors with homebrew on Mojave  ...   8-)

clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

clang++ --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

brew install pyenv
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/pyenv-1.2.11.mojave.bottle.tar.gz
Already downloaded: /Users/byih/Library/Caches/Homebrew/downloads/679ddf95a8f168d21ddc143a110f02e8a13c9675c9afd661c95736869dadacf5--pyenv-1.2.11.mojave.bottle.tar.gz
==> Pouring pyenv-1.2.11.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/pyenv/1.2.11: 643 files, 2.4MB

env | grep FLAG
LDFLAGS=-L/usr/local/opt/zlib/lib -L/usr/local/opt/readline/lib 
CPPFLAGS=-I/usr/local/opt/zlib/include -I/usr/local/opt/readline/include 

BUILD FAILED (OS X 10.14.4 using python-build 20180424)

 **ld: warning: ignoring file libpython3.7m.a, file was built for archive which is not the architecture being linked (x86_64): libpython3.7m.a** 

Undefined symbols for architecture x86_64:
  "__Py_UnixMain", referenced from:
      _main in python.o
Ld: symbol(s) not found for architecture x86_64
Undefined symbols for architecture x86_64:
  "_PyDict_New", referenced from:


last 10 log lines:
      _dump_config in _testembed.o
  "__Py_InitializeFromConfig", referenced from:
      _test_init_from_config in _testembed.o
      _test_init_dev_mode in _testembed.o
      _test_init_isolated in _testembed.o
ld: symbol(s) not found for architecture x86_64
make: *** [python.exe] Error 1
make: *** Waiting for unfinished jobs....
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Programs/_testembed] Error 1

**Comment by jbskytap** [comment]
FWIW this worked for me:
PYENV_DEBUG=1 CFLAGS="-I$(brew --prefix zlib)/include" LDFLAGS="-L$(brew --prefix zlib)/lib" pyenv install 3.5.0

**Comment by native-api** [comment]
Same as #1737, these MacOS versions aren't supported by older Pythons.
