### ISSUE TITLE
pyenv-virtualenvwrapper: Install common tools on a new environment

### ISSUE THREAD

**Issue by benmezger** [pyenv/pyenv#1288]
`Virtualenvwrapper` allows to set a default `requirements.txt` that will `pip install` every time we create a new virtual environment to [install common tools](https://virtualenvwrapper.readthedocs.io/en/latest/tips.html#installing-common-tools-automatically-in-new-environments). How can I archive this with `pyenv virtualenvwrapper`?

**Comment by native-api** [comment]
Looking at https://github.com/pyenv/pyenv-virtualenvwrapper/blob/2d11af824f5b8eee8e3cbdc0119c52ee8fc4a33e/bin/pyenv-virtualenvwrapper, it's still `source <path-to-virtualencwrapper.sh>` at its core  -- so all its facilities should be the same.
