### ISSUE TITLE
pyenv install anaconda3-2018.12 doesn't install from local  ~/.pyenv/cache

### ISSUE THREAD

**Issue by zrfrank** [pyenv/pyenv#1292]
Everything is the latest up to the date of this post.

System: MacOS latest, brew pyenv

I've downloaded the file from anaconda archive "Anaconda3-2018.12-MacOSX-x86_64.sh" and created the folder and put into the` ~/.pyenv/cache`. Then run `pyenv install anaconda3-2018.12`.

The downloading process is always initiated.

**Comment by chrahunt** [comment]
Can you please provide the output of your command with `PYENV_DEBUG=1` set?
