### ISSUE TITLE
readline-6.3 for x86_64-apple-darwin18.0.0 error

### ISSUE THREAD

**Issue by p0sec** [pyenv/pyenv#1293]
➜  ~ pyenv install 2.6.6
python-build: use openssl from homebrew
Downloading readline-6.3.tar.gz...
-> https://pyenv.github.io/pythons/56ba6071b9462f980c5a72ab0023893b65ba6debb4eeb475d7a563dc65cafd43
Installing readline-6.3...

BUILD FAILED (OS X 10.14 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/_3/hhn87rmx7554wnvgwfbhdtj00000gn/T/python-build.20190226110925.11756
Results logged to /var/folders/_3/hhn87rmx7554wnvgwfbhdtj00000gn/T/python-build.20190226110925.11756.log

Last 10 log lines:

Beginning configuration for readline-6.3 for x86_64-apple-darwin18.0.0

checking whether make sets $(MAKE)... no
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/var/folders/_3/hhn87rmx7554wnvgwfbhdtj00000gn/T/python-build.20190226110925.11756/readline-6.3':
configure: error: C compiler cannot create executables
See `config.log' for more details
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by yyuu** [comment]
> configure: error: C compiler cannot create executables

This isn't pyenv's issue. It seems *your* installation of Command Line Tools for Xcode is somehow corrupted. I'd recommend you to (re)?install it to fix the compilation issue (especially if you upgraded your macOS recently).
