### ISSUE TITLE
pyenv init support for csh

### ISSUE THREAD

**Issue by vinodrajkonda** [pyenv/pyenv#1294]
Is there pyenv init support csh? How do I get pyenv working in csh? It works fine on bash, please suggest.

$ echo $SHELL
/bin/csh

$ which python
/bin/python

$ echo $PYENV_ROOT
/root/.pyenv

$ echo $PATH
.:/root/.pyenv/bin:************ (extra values masked)

$ pyenv init -
export PATH="/root/.pyenv/shims:${PATH}"
export PYENV_SHELL=csh
command pyenv rehash 2>/dev/null
pyenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(pyenv "sh-$command" "$@")";;
  *)
    command pyenv "$command" "$@";;
  esac
}

$ pyenv shell
pyenv: shell integration not enabled. Run `pyenv init' for instructions.

$ bash

$ which python
/root/.pyenv/shims/python

Thanks.

**Comment by yyuu** [comment]
As you can find from pyenv-init itself, it only supports POSIX sh, bash, ksh and fish. It'd be theoretically possible to extend the script to support*csh, but it doesn't have any code for the shell so far.

https://github.com/pyenv/pyenv/blob/v1.2.9/libexec/pyenv-init#L47

**Comment by vinodrajkonda** [comment]
Thank you.
