### ISSUE TITLE
[macOS zsh] broken pyenv()

### ISSUE THREAD

**Issue by chrisduong** [pyenv/pyenv#1295]
### Description

- [ ] pyenv version: **1.2.9** (Homebrew)
- [ ] Python version: **3.6.8**
- Zsh version: **5.7.1**

- Issue: I put `eval "$(pyenv init -)"` into my `.zshrc`. When I open new Shell, I got this error

> zsh: parse error near `)'

It turned out **pyenv()** has not been expanded correctly.

```
❯ pyenv init -
export PATH="/Users/cduong/.pyenv/shims:${PATH}"
export PYENV_SHELL=zsh
source '/usr/local/Cellar/pyenv/1.2.9/libexec/../completions/pyenv.zsh'
command pyenv rehash 2>/dev/null
pyenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  )
    eval "$(pyenv "sh-$command" "$@")";;
  *)
    command pyenv "$command" "$@";;
  esac
}
```

The Case statement with empty **)** has been causing the problem.

**Comment by chrisduong** [comment]
I had discovered the culprit. I had accidentally install the `sort` command from Go package, which overrider the default  `sort` command

**Comment by Sasquiche** [comment]
I'm currently receiving the same issue as above, although my pyenv version is 1.2.11 from homebrew:

`which pyenv
zsh: correct 'pyenv' to '.pyenv' [nyae]? n
pyenv () {
	local command
	command="${1:-}"
	if [ "$#" -gt 0 ]
	then
		shift
	fi
	case "$command" in
		(rehash | shell) eval "$(pyenv "sh-$command" "$@")" ;;
		(*) command pyenv "$command" "$@" ;;
	esac
}`

While `pyenv doctor` gives this result:

`pyenv doctor
Cloning /Users/Vili/.pyenv/plugins/pyenv-doctor/bin/.....
Installing python-pyenv-doctor...
python-build: use readline from homebrew

BUILD FAILED (OS X 10.14.4 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/cy/nd0kr7s53_g02k0kvw0zkm1h0000gn/T/python-build.20190506194315.48234
Results logged to /var/folders/cy/nd0kr7s53_g02k0kvw0zkm1h0000gn/T/python-build.20190506194315.48234.log

Last 10 log lines:
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking openssl/ssl.h usability... no
checking openssl/ssl.h presence... no
checking for openssl/ssl.h... no
configure: error: OpenSSL development header is not installed.
make: *** No targets specified and no makefile found.  Stop.
Problem(s) detected while checking system.

See https://github.com/pyenv/pyenv/wiki/Common-build-problems for known solutions.`
