### ISSUE TITLE
Won't install python 2.7.4 if /tmp is mounted noexec

### ISSUE THREAD

**Issue by ferhtgoldaraz** [pyenv/pyenv#13]
The error was...

``` bash
:~$ pyenv install 2.7.4
Installing Python-2.7.4...

BUILD FAILED

Inspect or clean up the working tree at /tmp/python-build.20130416221217.21910
Results logged to /tmp/python-build.20130416221217.21910.log

Last 10 log lines:
Python-2.7.4/Misc/indent.pro
Python-2.7.4/Misc/ACKS
Python-2.7.4/Misc/README.valgrind
Python-2.7.4/Misc/RPM/
Python-2.7.4/Misc/RPM/README
Python-2.7.4/Misc/RPM/python-2.7.spec
Python-2.7.4/Misc/valgrind-python.supp
Python-2.7.4/Misc/README.klocwork
/tmp/python-build.20130416221217.21910/Python-2.7.4 /tmp/python-build.20130416221217.21910 ~
/home/$USER/.pyenv/plugins/python-build/bin/python-build: line 373: ./configure: Permission denied
```

This would probably happen for any version. Fixed it by doing...

``` bash
:~$ sudo mount -o remount,exec /tmp
```

I'm in ubuntu 12.10 64, though I can't remember if I changed default behaviour of /tmp.

A possible solution could be to check if /tmp is being mounted noexec and ask for an alternative if it is...

**Comment by nathan-stewart** [comment]
Removing noexec from /tmp is not the correct solution. There are reasons it is done and those reasons may be beyond the control of the person installing.  It should probably instruct the user to change TMPDIR instead as the default solution.

**Comment by coolboole** [comment]
> Removing noexec from /tmp is not the correct solution. There are reasons it is done and those reasons may be beyond the control of the person installing. It should probably instruct the user to change TMPDIR instead as the default solution.

I created a tmp directory under $HOME/.pyenv/ and set `export TMPDIR=$HOME/.pyenv/tmp`, just before the `eval "$(pyenv init - bash)"` line in my .bashrc and .bash_profile files. That seems to have fixed the issue.
