### ISSUE TITLE
subprocess.call PYENV_VERSION behaves differently than shell

### ISSUE THREAD

**Issue by robnagler** [pyenv/pyenv#1300]
### Description

I would expect setting PYENV_VERSION to behave the same from the shell as well as `subprocess.check_output`. What I think is happening is that `$PATH` contains the explicit version, not just `shims/bin` which is removed in lookup_from_path.bash. I think the explicit version bin (`versions/2.7.14/bin` in this case) in PATH has to be removed, too, in lookup_from_path.bash.

Here's the failure demonstrated with `pyenv which` executed from bash and `subprocess` ([gist](https://gist.github.com/robnagler/f18ab75b57bee820f5b03753b2871005)):

```sh
$ curl pyenv.run | bash
$ pyenv install 2.7.14
$ pyenv install 3.6.6
$ pyenv global 2.7.14
$ echo $PATH
/home/vagrant/.pyenv/plugins/pyenv-virtualenv/shims:/home/vagrant/.pyenv/shims:/home/vagrant/.pyenv/bin:/home/vagrant/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
$ pip install pytest
$ PYENV_VERSION=3.6.6 pyenv which py.test
pyenv: py.test: command not found

The `py.test' command exists in these Python versions:
  2.7.14
$ python -c 'import os, subprocess as s; os.environ["PYENV_VERSION"] = "3.6.6"; print s.check_output("pyenv which py.test", shell=1)'
/home/vagrant/.pyenv/versions/2.7.14/bin/py.test
$
```

- [x] Platform information (e.g. Ubuntu Linux 16.04): Vagrant fedora/27-cloud-base VirtualBox 5.2.20r125813

- [x] OS architecture (e.g. amd64): x86_64

- [x] pyenv version: pyenv 1.2.9

- [x] Python version: 2.7.14 and 3.6.6

- [x] C Compiler information (e.g. gcc 7.3):  7.3.1 20180712 (Red Hat 7.3.1-6)

- [x] Please attach verbose build log as gist: https://gist.github.com/robnagler/f18ab75b57bee820f5b03753b2871005

**Comment by yyuu** [comment]
At first glance, I thought it might be because modification on [os.environ](https://docs.python.org/2/library/os.html#os.environ) was read-only because of platform's restriction, however, it seems it's not the case 🤔  I guess, there's some weird shell configuration in shell's configuration file and it is causing some issue, but I'm not sure. I don't believe this is really an issue of pyenv itself.

```
$ python -c 'import os, subprocess as s; os.environ["PYENV_VERSION"] = "3.6.6"; print s.check_output(["pyenv", "which", "py.test"], shell=False)'
```

**Comment by robnagler** [comment]
I think the bug is related to #98, which [added `$PYENV_BIN_PATH` to `$PATH`](https://github.com/pyenv/pyenv/blob/d01fa09a7/libexec/pyenv-exec#L46):

```bash
# CPython's `sys.executable` requires the `PYENV_BIN_PATH` to be at the top of the `PATH`.
# https://github.com/pyenv/pyenv/issues/98
export PATH="${PYENV_BIN_PATH}:${PATH}"
```

The following demonstrates a patch to pyenv an pyenv-which-ext that handles this case correctly, and I believe is backwards compatible:

```bash
mkdir x
cd x
vagrant init fedora/27-cloud-base
vagrant up
vagrant ssh
sudo dnf install -y bzip2-devel git openssl-devel patch readline-devel sqlite-devel
curl pyenv.run | bash
export PATH="/home/vagrant/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
pyenv install 2.7.14
pyenv install 3.6.6
pyenv global 2.7.14
pip install pytest
t1() {
     [[ $(python -c 'import os, subprocess as s; os.environ["PYENV_VERSION"] = "3.6.6"; print s.check_output("pyenv which py.test", shell=1)' 2>/dev/null) =~ 2.7.14 ]]
}
t1 && echo INCORRECT py.test
(cd ~/.pyenv && patch libexec/pyenv-exec) <<'EOF'
diff --git a/libexec/pyenv-exec b/libexec/pyenv-exec
index 51c668e..a6e1fe9 100755
--- a/libexec/pyenv-exec
+++ b/libexec/pyenv-exec
@@ -31,7 +31,7 @@ fi

 export PYENV_VERSION
 PYENV_COMMAND_PATH="$(pyenv-which "$PYENV_COMMAND")"
-PYENV_BIN_PATH="${PYENV_COMMAND_PATH%/*}"
+export PYENV_BIN_PATH="${PYENV_COMMAND_PATH%/*}"

 OLDIFS="$IFS"
 IFS=$'\n' scripts=(`pyenv-hooks exec`)
EOF
(cd ~/.pyenv/plugins/pyenv-which-ext && patch etc/pyenv.d/which/lookup_from_path.bash) <<'EOF'
diff --git a/etc/pyenv.d/which/lookup_from_path.bash b/etc/pyenv.d/which/lookup_from_path.bash
index fda76b8..13d99f7 100644
--- a/etc/pyenv.d/which/lookup_from_path.bash
+++ b/etc/pyenv.d/which/lookup_from_path.bash
@@ -1,17 +1,19 @@
 remove_from_path() {
-  local path_to_remove="$1"
+  local path_to_remove
   local path_before
   local result=":$PATH:"
-  while [ "$path_before" != "$result" ]; do
-    path_before="$result"
-    result="${result//:$path_to_remove:/:}"
+  for path_to_remove in "$@"; do
+    while [ "$path_before" != "$result" ]; do
+      path_before="$result"
+      result="${result//:$path_to_remove:/:}"
+    done
+    result="${result%:}"
   done
-  result="${result%:}"
   echo "${result#:}"
 }

 lookup_from_path() {
-  PATH="$(remove_from_path "${PYENV_ROOT}/shims")" command -v "$1" || true
+  PATH="$(remove_from_path "${PYENV_ROOT}/shims" "${PYENV_BIN_PATH}")" command -v "$1" || true
 }

 # If the "$PYENV_COMMAND_PATH" does not exist,
EOF
t1 || echo PASS
```

**Comment by blueyed** [comment]
Is this still an issue with `$PATH` only being changed for non-system versions anymore?  (#1169)

**Comment by robnagler** [comment]
The failure case doesn't seem to occur in 1.2.12 so I'd call it fixed.
