### ISSUE TITLE
An error occurred in the secure channel support 

### ISSUE THREAD

**Issue by fritsderaad** [pyenv/pyenv#1303]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): Windows 7 professional
- [ ] OS architecture (e.g. amd64): 64 bit
- [ ] pyenv version: 1.1.2
- [ ] Python version: current 3.6.2 32 bit
- [ ] C Compiler information (e.g. gcc 7.3):  ?
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

Hi ,
Installed pyenv 1.1.2 succesfully. Now wanted to create new environment 3.7.2-amd64 but failed. Tried different versions including 32 bit and 3.7.0 but all same failure:
It starts downloading but within a second new line shows up: An error occurred in the secure channel support. Browsed the internet for two hours to find solution, no luck. Did not find anything related to this on you git, so now I'm posting the question. Thanks

**Comment by joshfriend** [comment]
Please follow the issue template and provide the items requested

**Comment by fritsderaad** [comment]
Sorry, bit of a newby, filled out the template with everything I knew. How do I determine the C Compiler on my Windows 7 pro machine? is that Visual Studio 2017? Tried to put on debugging but on suggested code I got PYENV_DEBUG is not recognized as internal or external command, operable program or batch file

**Comment by chrahunt** [comment]
It looks like you're trying to build a native Python on Windows, which I don't believe is supported. We would try to support compiling with Windows Subsystem for Linux as a target. @yyuu can you confirm?

**Comment by yyuu** [comment]
pyenv doesn't support Windows _natively_ as it is totally depending on bash and C compiler toolchain for *nix.

However, Windows 10 now supports WSL and it is allowing users to install Linux subsystem into their installation (w/ some limitations especially for daemons). I have already confirmed that pyenv can just work as is on WSL Ubuntu 18.04 image at least. What is necessary to use pyenv on WSL is equivalent to what is necessary on ordinary GNU/Linux, in general. Anyway without pasting full (debug)? output, no one would be able to find out the cause of the issue.

**Comment by chrahunt** [comment]
@fritsderaad, to summarize: pyenv is supported on WSL on Windows. You can read about WSL [here](https://docs.microsoft.com/en-us/windows/wsl/faq). For instructions, just follow any instructions you see in the pyenv README or the [wiki](https://github.com/pyenv/pyenv/wiki) for "Ubuntu" and  you should be OK.
