### ISSUE TITLE
Python 3.7.* install errors.

### ISSUE THREAD

**Issue by grabear** [pyenv/pyenv#1304]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04):
- [x] OS architecture (e.g. amd64):
- [x] pyenv version:
- [x] Python version:
- [x] C Compiler information (e.g. gcc 7.3): 
- [x] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

I've been trying to install python 3.7 and I can't seem to get it to install correctly.  ALl of the other versions have installed (3.6, 3.5, 3.4).

THe first issue I was having with 3.7 was with CURL.  So I switched the if statement in the pyenv-build script per the comment in [this issue.](https://github.com/pyenv/pyenv/issues/303#issuecomment-238027760)  This bypassed the download error that I was getting until I reached another error listed below:

![image](https://user-images.githubusercontent.com/20953530/54705804-9d762580-4b0b-11e9-9dc5-25a4d410780e.png)

What's going on here?

**Comment by grabear** [comment]
```
[~ $ ]uname -a
Linux 4.4.162-94.72-default #1 SMP Mon Nov 12 18:57:45 UTC 2018 (9de753f) x86_64 x86_64 x86_64 GNU/Linux
```
```
[~ $] gcc --version
gcc (SUSE Linux) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Here is my log https://gist.github.com/grabear/5ac56caa40d5096cd9a0839e60b0df31

**Comment by grabear** [comment]
I'm using pyenv 1.2.9

**Comment by grabear** [comment]
This also occurs on my centos machine:

```shell
pyenv install 3.4.9; pyenv install 3.5.6; pyenv install 3.6.8; pyenv install 3.7.2
Downloading Python-3.4.9.tar.xz...
-> https://www.python.org/ftp/python/3.4.9/Python-3.4.9.tar.xz
Installing Python-3.4.9...
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
Installed Python-3.4.9 to /home/rgilmore/.pyenv/versions/3.4.9

Downloading Python-3.5.6.tar.xz...
-> https://www.python.org/ftp/python/3.5.6/Python-3.5.6.tar.xz
Installing Python-3.5.6...
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
Installed Python-3.5.6 to /home/rgilmore/.pyenv/versions/3.5.6

Downloading Python-3.6.8.tar.xz...
-> https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tar.xz
Installing Python-3.6.8...
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
Installed Python-3.6.8 to /home/rgilmore/.pyenv/versions/3.6.8

Downloading Python-3.7.2.tar.xz...
-> https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
Installing Python-3.7.2...

BUILD FAILED (CentOS release 6.9 (Final) using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20190320140820.11167
Results logged to /tmp/python-build.20190320140820.11167.log

Last 10 log lines:
  File "/tmp/tmppb2pd8qd/pip-18.1-py2.py3-none-any.whl/pip/_internal/cli/main_parser.py", line 12, in <module>
  File "/tmp/tmppb2pd8qd/pip-18.1-py2.py3-none-any.whl/pip/_internal/commands/__init__.py", line 6, in <module>
  File "/tmp/tmppb2pd8qd/pip-18.1-py2.py3-none-any.whl/pip/_internal/commands/completion.py", line 6, in <module>
  File "/tmp/tmppb2pd8qd/pip-18.1-py2.py3-none-any.whl/pip/_internal/cli/base_command.py", line 18, in <module>
  File "/tmp/tmppb2pd8qd/pip-18.1-py2.py3-none-any.whl/pip/_internal/download.py", line 38, in <module>
  File "/tmp/tmppb2pd8qd/pip-18.1-py2.py3-none-any.whl/pip/_internal/utils/glibc.py", line 3, in <module>
  File "/tmp/python-build.20190320140820.11167/Python-3.7.2/Lib/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
make: *** [install] Error 1

```

**Comment by grabear** [comment]
```bash
Linux uxpi-guytappp01.umsmed.edu 2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by chrahunt** [comment]
The log [here](https://gist.github.com/grabear/5ac56caa40d5096cd9a0839e60b0df31#file-pyenv-mcsr-build-log-txt-L1132) indicates that libffi cannot be found. Can you confirm that you have `libffi-devel` or equivalent installed per the [suggested build environments](https://github.com/pyenv/pyenv/wiki#suggested-build-environment)?

**Comment by jpmondet** [comment]
> The log [here](https://gist.github.com/grabear/5ac56caa40d5096cd9a0839e60b0df31#file-pyenv-mcsr-build-log-txt-L1132) indicates that libffi cannot be found. Can you confirm that you have `libffi-devel` or equivalent installed per the [suggested build environments](https://github.com/pyenv/pyenv/wiki#suggested-build-environment)?

Nice catch ! I had the same issue and your suggestion resolved it, thanks ! :1st_place_medal:

**Comment by chrahunt** [comment]
@grabear, please let us know if the above does not resolve your issue. Thanks!
