### ISSUE TITLE
python-build does not properly find ssl library :: pyenv doctor fails caused python-build fail

### ISSUE THREAD

**Issue by AlyssonOliveira** [pyenv/pyenv#1311]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): GNU/Linux Debian, Independent
- [x] OS architecture (e.g. amd64): Independent
- [x] pyenv version: 1.2.7-59-gdae256f
- [x] Python version: 3.7.x
- [x] C Compiler information (e.g. gcc 7.3): gcc 8.3 and all
- [x] Please attach verbose build log as gist

```
pyenv doctor 
Cloning /home/username/.pyenv/plugins/pyenv-doctor/bin/.....
Installing python-pyenv-doctor...

BUILD FAILED (Debian testing using python-build 1.2.7-59-gdae256f)

Inspect or clean up the working tree at /tmp/python-build.20190326210727.25763
Results logged to /tmp/python-build.20190326210727.25763.log

Last 10 log lines:
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for rl_gnu_readline_p in -lreadline... yes
checking for readline/readline.h... no
checking for SSL_library_init in -lssl... no
configure: error: OpenSSL is not installed.
Problem(s) detected while checking system.

See https://github.com/pyenv/pyenv/wiki/Common-build-problems for known solutions.
```

`python-build` plugin is called by `doctor` plugin. The libssl is not found because `python-build ` uses a default `configure` script. Run `autoreconf` solves it and python-build already has a script to do it `gen.sh`, it would be called by `python-build` before call `configure`

**Comment by skewty** [comment]
I see `python-openssl` is listed as a package to apt install on the common problems page.  Is python2 really required?  `python-*` packages are (legacy) python2 in Debian.  `python3-*` are obviously python3.

On Ubuntu (since at least 16.04) only python3 is installed by default.  To bring in python2 seems a bit much.  Is it really required?

**Comment by skewty** [comment]
@AlyssonOliveira Have you tried `sudo apt install python3-openssl python3-openssl-dev`?
