### ISSUE TITLE
pyenv install  3.7.2 failed

### ISSUE THREAD

**Issue by UniqueSimon** [pyenv/pyenv#1317]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04):`MacOS 10.14.3`
- [ ] OS architecture (e.g. amd64):
- [x] pyenv version:`1.2.9`
- [x] Python version:`3.7.2`,`3.7.1`
- [x] C Compiler information (e.g. gcc 7.3): `Mac Mojave Default /usr/include/c++/4.2.1`
- [x] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`
[https://gist.github.com/UniqueSimon/70a775ba61181cc79790afe81d257a35](https://gist.github.com/UniqueSimon/70a775ba61181cc79790afe81d257a35)

**Comment by ThomasWaldmann** [comment]
your gist is 404.

**Comment by chrahunt** [comment]
If you are still experiencing issues, please don't hesitate to let us know. Thanks!
