### ISSUE TITLE
3.7.3 fails to install

### ISSUE THREAD

**Issue by denningsrogue** [pyenv/pyenv#1319]
### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): **macOS 10.14.4**
- [ ] OS architecture (e.g. amd64):
- [ ] pyenv version: **1.2.10**
- [ ] Python version: **3.7.3 2.7.15**
- [ ] C Compiler information (e.g. gcc 7.3): **Apple LLVM version 10.0.1 (clang-1001.0.46.3)**
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

**Installation of 3.7.3 fails with this message:**

pyenv install 3.7.3                                                                                                                                                [07:02:24]
python-build: use openssl 1.0 from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.3.tar.xz...
-> https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz
Installing Python-3.7.3...
python-build: use readline from homebrew

BUILD FAILED (OS X 10.14.4 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/83/8ydmlqc50lx6zs48b2nx49lh0000gn/T/python-build.20190404081104.30826
Results logged to /var/folders/83/8ydmlqc50lx6zs48b2nx49lh0000gn/T/python-build.20190404081104.30826.log

Last 10 log lines:
  File "/private/var/folders/83/8ydmlqc50lx6zs48b2nx49lh0000gn/T/python-build.20190404081104.30826/Python-3.7.3/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/private/var/folders/83/8ydmlqc50lx6zs48b2nx49lh0000gn/T/python-build.20190404081104.30826/Python-3.7.3/Lib/ensurepip/__init__.py", line 204, in _main
    default_pip=args.default_pip,
  File "/private/var/folders/83/8ydmlqc50lx6zs48b2nx49lh0000gn/T/python-build.20190404081104.30826/Python-3.7.3/Lib/ensurepip/__init__.py", line 117, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/private/var/folders/83/8ydmlqc50lx6zs48b2nx49lh0000gn/T/python-build.20190404081104.30826/Python-3.7.3/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip._internal
zipimport.ZipImportError: can't decompress data; zlib not available
make: *** [install] Error 1

[python-build.20190404082102.53680.log](https://github.com/pyenv/pyenv/files/3043955/python-build.20190404082102.53680.log)

**Comment by denningsrogue** [comment]
The install failure has left the entire environment broken:

/Users/denningsrogue/.pyenv/shims/python: line 21: /usr/local/Cellar/pyenv/1.2.9/libexec/pyenv: No such file or directory

**Comment by denningsrogue** [comment]
The problem is that the shims refer to the old version of peen (1.2.9).  You have to modify the shims to refer to 1.2.10.  3.7.3 and 2.7.16 still fail to install though.

**Comment by joshfriend** [comment]
https://github.com/pyenv/pyenv/issues/1219#issuecomment-428793012
