### ISSUE TITLE
2.7.16 fails to install 

### ISSUE THREAD

**Issue by denningsrogue** [pyenv/pyenv#1320]
### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): **macOS 10.14.4**
- [ ] OS architecture (e.g. amd64):
- [ ] pyenv version: **1.2.10**
- [ ] Python version: 3.7.2 2.7.15
- [ ] C Compiler information (e.g. gcc 7.3): **Apple LLVM version 10.0.1 (clang-1001.0.46.3)
[python-build.20190404083756.66264.log](https://github.com/pyenv/pyenv/files/3044005/python-build.20190404083756.66264.log)
**
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

**The installation of 2.7.16 fails with the following message:**

pyenv install 2.7.16                                                                                                                                             1 [08:12:57]
python-build: use openssl 1.0 from homebrew
python-build: use readline from homebrew
Downloading Python-2.7.16.tar.xz...
-> https://www.python.org/ftp/python/2.7.16/Python-2.7.16.tar.xz
Installing Python-2.7.16...
python-build: use readline from homebrew
ERROR: The Python zlib extension was not compiled. Missing the zlib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems

BUILD FAILED (OS X 10.14.4 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/83/8ydmlqc50lx6zs48b2nx49lh0000gn/T/python-build.20190404081318.43182
Results logged to /var/folders/83/8ydmlqc50lx6zs48b2nx49lh0000gn/T/python-build.20190404081318.43182.log

Last 10 log lines:
rm -f /Users/richardpeters/.pyenv/versions/2.7.16/share/man/man1/python.1
(cd /Users/richardpeters/.pyenv/versions/2.7.16/share/man/man1; ln -s python2.1 python.1)
if test "xno" != "xno"  ; then \
		case no in \
			upgrade) ensurepip="--upgrade" ;; \
			install|*) ensurepip="" ;; \
		esac; \
		 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi

**Comment by joshfriend** [comment]
please search open issues and the common build issues wiki _as described in the issue template_ before opening multiple issues about the same problem

https://github.com/pyenv/pyenv/issues/1219#issuecomment-428793012
