### ISSUE TITLE
macOS: no ssl support with py352 if openssl11 installed

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyenv/pyenv#1325]
Likely due to my recent PR, on macOS, python < 3.5.3 is now built without ssl support if openssl 1.1 is present - because python < 3.5.3 is not compatible with openssl 1.1. This happens even if openssl 1.0 is also present because 1.1 is preferred by current pyenv code.

I just found that myself on travis-ci as I was using 3.5.2.

I'm sorry for any inconvenience this may have caused.

I'm trying to fix this for borg there: https://github.com/borgbackup/borg/pull/4499

For pyenv in general, another fix is needed as there should be ssl support for py < 3.5.3.

**Comment by ThomasWaldmann** [comment]
Guess the right fix is to adjust the preference depending on the python version.

**Comment by ThomasWaldmann** [comment]
https://github.com/pyenv/pyenv/blob/v1.2.10/plugins/python-build/bin/python-build#L1494

can somebody with better shell scripting skills than me please help?

**Comment by chrahunt** [comment]
Given the desired outcome is:

1. < 3.5.3: Work by default using homebrew openssl 1.0 or downloading and compiling a local version
2. >= 3.5.3: Work by default with openssl 1.1 if present in homebrew, or downloading and compiling a local version (may be 1.0)

One solution could be:

1. Split `has_broken_mac_openssl` into `has_broken_mac_openssl_prefer_10` and `has_broken_mac_openssl_prefer_11`
2. In `*_10` only check for homebrew openssl 1.0
3. In `*_11` check for homebrew openssl 1.1 with fallback to 1.0
4. Change all relevant python version packages to use one of the above.

**Comment by yyuu** [comment]
I've checked some of CPython issues e.g. https://bugs.python.org/issue32947, but it wasn't clear enough to me which CPython versions support OpenSSL 1.1. I've checked release notes as well, and now I believe that CPython versions newer than these versions support OpenSSL 1.1+.

* [2.7.14](https://raw.githubusercontent.com/python/cpython/84471935ed2f62b8c5758fd544c7d37076fe0fa5/Misc/NEWS)
* [3.6.7](https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-7-release-candidate-1)
* [3.5.3](https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-3)

**Comment by gagelarsen** [comment]
Is there any sort of work around for this until the fix above is released?

**Comment by ThomasWaldmann** [comment]
@gagelarsen not having brew openssl@1.1 installed.

**Comment by ThomasWaldmann** [comment]
@yyuu as openssl support is listed as "new in 3.6", i would expect it works with 3.6.0:

https://docs.python.org/3/whatsnew/3.6.html

**Comment by ThomasWaldmann** [comment]
https://github.com/bear/python-twitter/issues/555 see there.

**Comment by yyuu** [comment]
I guess my fix wouldn't be perfect, but would work sufficiently. Also, it supports switching brew's formula for OpenSSL based on environment variable. We can tweak the build definitions to support more versions to _prefer_ OpenSSL 1.1, but at least we can defer the resolution until someone claims it as some real problem.

BTW, I've cut new release https://github.com/pyenv/pyenv/releases/tag/v1.2.11 after my fix of #1328. Hopefully it will be rolled out to brew sometime sooner.
