### ISSUE TITLE
Errors when using site package package in pyenv

### ISSUE THREAD

**Issue by JohnHerry** [pyenv/pyenv#1330]
### Description
- [ ] Platform information (CentOS7.2):
- [ ] OS architecture (X86-64):
- [ ] pyenv version(1.1.3):
- [ ] Python version(3.6.2):
- [ ] C Compiler information (gcc 4.8.5): 
- [ ] Detail:
  -  When I import the site package in my program and access site.USER_SITE, It is a string like `${HOME}/.local/XXXX   `instead of `${HOME}/.pyenv/versions/XXXX`, And, If I call `site.getusersitepackages() i`n the env created by `pyenv virtualenv XXX` , It will report exception about no such attribute in the site package. Why? How to slove it. I want to get the lib path of this python running.
- [ ] Recurrent:
  - `import site`
    `print(site.USER_SITE)`

**Comment by chrahunt** [comment]
What you put lines up with the documentation on [`site.USER_SITE`](https://docs.python.org/3/library/site.html#site.USER_SITE). If you want the `site-packages` directory that is within the Python install, you can try one of the directories returned by `site.getsitepackages()`.
