### ISSUE TITLE
Get stuck in installing python when using "--enable-framework" options

### ISSUE THREAD

**Issue by yaocanwei** [pyenv/pyenv#1331]
![image](https://user-images.githubusercontent.com/4312268/56008799-08340e80-5d10-11e9-8099-0d94420bff8d.png)

**Comment by chrahunt** [comment]
Please create a new issue and follow the issue template, providing verbose build logs in a separate gist/pastebin along with system information.

It also helps to copy the terminal text instead of putting an image, where possible.
