### ISSUE TITLE
No C-headers in pyenv

### ISSUE THREAD

**Issue by meddnepr** [pyenv/pyenv#1332]
In the last pyenv at building Docker Image ubuntu:16.04 no headers in /usr/bin/pyenv/versions/3.5.2/include after:

RUN pyenv install 2.7.6 \
 && PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.5.2 \
 && pyenv global  3.5.2 \
 && pyenv rehash

Because of it boost build fails:
pyconfig.h: no such files.

apt-get install python-dev fixes in non-pyenv Python

**Comment by joshfriend** [comment]
Please provide the info requested in the issue template
