### ISSUE TITLE
pyenv: no such command `virtualenv'

### ISSUE THREAD

**Issue by kylefoley76** [pyenv/pyenv#1340]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

Platform MacOs Mojave
pyenv version: 1.2.11
python version 3.6.8

When I input the command 
`pyenv virtualenv 3.6.8 myproject`

I get the error message:
`pyenv: no such command`

Other commands are working such as 
`pyenv shell 3.6.8`
`pyenv versions`

Because this claim is rather improbable I'm attaching a screenshot
<img width="430" alt="Screen Shot 2019-05-04 at 8 38 40 AM" src="https://user-images.githubusercontent.com/16620676/57181408-20e3a000-6e48-11e9-81db-73c4b31b9b8f.png">

**Comment by kylefoley76** [comment]
Problem solved:
`brew install pyenv-virtualenv`

**Comment by gheja** [comment]
On Linux:
```
git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
```

As per https://github.com/pyenv/pyenv-virtualenv

**Comment by NabunyaLilian** [comment]
> Problem solved:
> `brew install pyenv-virtualenv`

Worked for me, Thanks!

**Comment by jo3yzhu** [comment]
> > `brew install pyenv-virtualenv`

that works for me, too

**Comment by lagayundato08** [comment]
> Problem solved: `brew install pyenv-virtualenv`

not work on me, I'm windows user and stuck in setting up environment :(

**Comment by lagayundato08** [comment]
any alternative from windows user perspective?
