### ISSUE TITLE
How do I get readline support in the python interactive interpreter on MacOS?

### ISSUE THREAD

**Issue by fields** [pyenv/pyenv#1341]
On MacOS (Mojave), I've installed pyenv with homebrew. I've also installed readline with homebrew. But the python interpreter that was installed with pyenv does not seem to have readline support (no history). I've tried `pip install readline`, but that fails. Is there something special I need to do in order to configure this properly?

**Comment by joshfriend** [comment]
Please use the issue template and provide the requested information
