### ISSUE TITLE
Pip not using shims

### ISSUE THREAD

**Issue by robertdefilippi** [pyenv/pyenv#1342]
# System Information
      System Version: macOS 10.14.4 (18E226)
      Kernel Version: Darwin 18.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal

Hello,

My `pyenv` is working correctly, however my pip is not being shimmed to the correct location. How can I update the path, or do I need to `rehash` my `pyenv` ?

I would show you the version of `pyenv` I have installed, however whenever I run `pip freeze` it defaults to my system version of python, rather than the one installed with `pyenv`

```
$ which python
/Users/me/.pyenv/shims/python

$ pyenv versions
  system
* 3.6.1 (set by /Users/me/.pyenv/version)

$ which pip
/usr/local/bin/pip

$ which pip3
/usr/local/bin/pip3
```
Thanks
I'm fairly sure my pip should be at `/Users/me/.pyenv/shims/pip` and I'm not sure how to update their path.

**Comment by joshfriend** [comment]
I suspect you might have missed one of the [install steps](https://github.com/pyenv/pyenv#basic-github-checkout), particularly the "Add pyenv init to your shell" one. Without `pyenv init`, the pyenv command will be available, but the shims wont work. If you confirm that you added it to your shell and it's still not working, remember that you have to restart your shell, or run `source ~/.zshenv` (or whatever file you used to setup your prefered shell)

**Comment by robertdefilippi** [comment]
Hey @joshfriend I can confirm the steps were followed.

```
# .zshrc

export PATH="/Users/me/.pyenv/bin:$PATH"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

I've also restarted my shell. Any ideas on what to do next?

**Comment by robertdefilippi** [comment]
I ended up just reinstalling pyenv from scratch, and everything went back to normal. Seems odd that my pip path would change.

Any suggestions on troubleshooting next time (if) this occurs?

**Comment by joshfriend** [comment]
You tried `pyenv rehash` right? Other than that and the other things I mentioned, I don't have a clear idea of what went wrong the first time, sorry 😕

**Comment by robertdefilippi** [comment]
Thanks for helping me debug it @joshfriend!
If it happens again, I'll try to have a clearer explanation.

Cheers

**Comment by applecargo** [comment]
this happened for me.
my .profile was like this (ubuntu 18.04)

`# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
`

and PATH="$HOME/.local/bin:$PATH" was the trouble maker.
because I had another 'pip' in there.

**Comment by thomassantosh** [comment]
Hi,
Facing a similar issue, though after reinstalling, it still persists. 

I'm on a MacBook Air, with the M1 chip. 

Current versions:
```
<me>:~:$ pyenv versions
* system (set by /Users/<me>/.pyenv/version)
  3.9.4
```
At my $HOME prompt:
```
<me>:~:$ python -V
Python 2.7.16
<me>:~:$ which pip
/opt/homebrew/bin/pip
<me>:~:$ pip -V
pip 21.1 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)
```

Within <project 1>, I have a .python_version file which is for 3.9.4
```
<me>:~:$ cd ~//<project 1>/
<me>:~//<project 1>:$ python -V
Python 3.9.4
<me>:~//<project 1>:$ pyenv versions
  system
* 3.9.4 (set by /Users/<me>/<project 1>/.python-version)
```
However, when I do a "which pip" or a "pip -V" it shows the system pip binary:
```
<me>:~/<project 1>:$ which pip
/opt/homebrew/bin/pip

<me>:~//<project 1>:$ pip -V
pip 21.1 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)
```

Any thoughts on how to get this working with the 'pip' under the pyenv version?

**Comment by taz77** [comment]
I just had this exact problem. Two reinstalls later and it still would not fix the problem. Python use pyenv but pip would not.

My problem was my path.  `echo $PATH` and scrutinize it. The .pyenv/shims should be before /usr/local/bin

**Comment by dylanwilder** [comment]
I had this issue.  I tracked it down to the following:

Seems like all instructions say to add the following to your *rc file
```zsh
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```
which is what i had, but at some point i think `$PYENV_ROOT/bin` was removed and everything was moved to `$PYENV_ROOT/shims`. Updating my rc file accordingly did the trick

**Comment by KrGil** [comment]
> this happened to me. my .profile was like this (ubuntu 18.04)
> 
> ```
> # if running bash
> if [ -n "$BASH_VERSION" ]; then
>     # include .bashrc if it exists
>     if [ -f "$HOME/.bashrc" ]; then
> 	. "$HOME/.bashrc"
>     fi
> fi
> 
> # set PATH so it includes user's private bin if it exists
> if [ -d "$HOME/bin" ] ; then
>     PATH="$HOME/bin:$PATH"
> fi
> 
> # set PATH so it includes user's private bin if it exists
> if [ -d "$HOME/.local/bin" ] ; then
>     PATH="$HOME/.local/bin:$PATH"
> fi
> ```
> 
> and PATH="$HOME/.local/bin:$PATH" was the trouble maker. because I had another 'pip' in there.

so how did you solve it? delete another `pip`? what did you do???

**Comment by cheng3100** [comment]
I find the same issue and found it just because after the ~/.bashrc there is something else who change the $PATH again to let the `~/.local/bin` before the pyenv's shim path, In my case it is the ~/.profile file who did this.
![图片](https://github.com/pyenv/pyenv/assets/25582840/f588a415-e604-4061-a204-c38f7456220f)

So I modify the ~/.profile like the pic and issue solved.

**Comment by native-api** [comment]
@cheng3100 See https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv . It specifically says to add the `pyenv init` call to `~/.profile` as well -- specifically for this case.
