### ISSUE TITLE
-bash: /Users/XXX/.pyenv/shims/python: No such file or directory

### ISSUE THREAD

**Issue by CodeMasterYi** [pyenv/pyenv#1346]
```
XXX's MacBook-Air:~ XXX$ python
-bash: /Users/XXX/.pyenv/shims/python: No such file or directory
```

i want to re-install the pyenv
but after i uninstall pyenv, i try to execute python,    it shows something above~~~

i would like to locate which configuration contains `/Users/XXX/.pyenv/shims/python`

**Comment by joshfriend** [comment]
please provide the info requested in the issue template

**Comment by CodeMasterYi** [comment]
heng! wo xin ni ge gui, ni ge zao lao tou zi! huai de hen!
