### ISSUE TITLE
Cannot install 3.8-dev

### ISSUE THREAD

**Issue by T-101** [pyenv/pyenv#1351]
Installing 3.8-dev fails. Tested on Lubuntu 18.04 and Mac OS 10.14.5. Same error message:

```
$ pyenv install 3.8-dev
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Cloning https://github.com/python/cpython...
Installing Python-3.8-dev...
python-build: use readline from homebrew
ERROR: invalid Python executable: /Users/[REDACTED]/.pyenv/versions/3.8-dev/bin/python3.8

The python-build could not find proper executable of Python after successful build.
Please open an issue for future improvements.
https://github.com/pyenv/pyenv/issues

BUILD FAILED (OS X 10.14.5 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/zc/m7c_hq2s03j4180qph6gb11h0000gn/T/python-build.20190605160615.415
Results logged to /var/folders/zc/m7c_hq2s03j4180qph6gb11h0000gn/T/python-build.20190605160615.415.log

Last 10 log lines:
		 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi
/var/folders/zc/m7c_hq2s03j4180qph6gb11h0000gn/T/tmpfglvyyn1/pip-19.0.3-py2.py3-none-any.whl/pip/_vendor/pyparsing.py:3068: SyntaxWarning: invalid escape sequence \w
/var/folders/zc/m7c_hq2s03j4180qph6gb11h0000gn/T/tmpfglvyyn1/pip-19.0.3-py2.py3-none-any.whl/pip/_vendor/pyparsing.py:3068: SyntaxWarning: invalid escape sequence \w
Looking in links: /var/folders/zc/m7c_hq2s03j4180qph6gb11h0000gn/T/tmpfglvyyn1
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-19.0.3 setuptools-40.8.0
```

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information: Lubuntu 18.04, Mac OS 10.14.5
- [ ] OS architecture (e.g. amd64):
- [x] pyenv version: 1.2.11
- [ ] Python version: 
- [ ] C Compiler information (e.g. gcc 7.3): 
- [x] Please attach verbose build log as gist
[https://gist.github.com/T-101/8bb32f389eb687f8841bd91d72c5b7f8](https://gist.github.com/T-101/8bb32f389eb687f8841bd91d72c5b7f8)

**Comment by joshfriend** [comment]
There's a seemingly related issue from pyparsing here: https://github.com/pyparsing/pyparsing/issues/80

With the first 3.8.0 beta released yesterday, the python core team split 3.8-dev onto a new branch and 3.9-dev is now on master. If you haven't updated to the version of pyenv from git as of last night, or are using a homebrew install, you will be trying to install the 3.9 dev version.

I think the issue here is that they finally removed deprecation warnings for something and made it an error in 3.9 and that's why your ensurepip step fails

**Comment by T-101** [comment]
Thanks for the quick reply.

`git pull` in ~/.pyenv did the trick on Lubuntu, was able to install. Stupid of me not to try that first.

MacOS not so lucky, though. Tried `brew upgrade pyenv` which tells me that I am already on the latest version. Then tried `pyenv update` via the pyenv-update plugin, which apparently only tries to update itself:
```
$ pyenv update
Updating /Users/[REDACTED]/.pyenv/plugins/pyenv-update...
From git://github.com/pyenv/pyenv-update
 * branch            master     -> FETCH_HEAD
Already up to date.
```
Any other way to update a brew installed pyenv in MacOS? The ~/.pyenv/ has no git repo.

**Comment by joshfriend** [comment]
> Stupid of me not to try that first

Unless you have news alerts for python git branch breaking news, you can easily be forgiven for this 😜 

There hasn't been a new pyenv release tagged since the 3.8/3.9 branch changes last night, so the homebrew version won't be updated yet. The branch changes theoretically affect services like Travis CI, so I should maybe prioritize tagging a new release and pushing to homebrew soon. I'll reopen as a reminder to do so.

**Comment by joshfriend** [comment]
https://github.com/Homebrew/homebrew-core/pull/40880

**Comment by suryaajha** [comment]
git pull in ~/.pyenv/ in ubuntu works, thanks @T-101

**Comment by cheng10** [comment]
> Thanks for the quick reply.
> 
> `git pull` in ~/.pyenv did the trick on Lubuntu, was able to install. Stupid of me not to try that first.
> 
> MacOS not so lucky, though. Tried `brew upgrade pyenv` which tells me that I am already on the latest version. Then tried `pyenv update` via the pyenv-update plugin, which apparently only tries to update itself:
> 
> ```
> $ pyenv update
> Updating /Users/[REDACTED]/.pyenv/plugins/pyenv-update...
> From git://github.com/pyenv/pyenv-update
>  * branch            master     -> FETCH_HEAD
> Already up to date.
> ```
> 
> Any other way to update a brew installed pyenv in MacOS? The ~/.pyenv/ has no git repo.

as of today, `brew upgrade pyenv` fix the issue on MacOS:

**Comment by RodPaDev** [comment]
I still have this issue, I installed pyenv by git clone, although different versions currently I can't install any version

```
 pyenv install 3.7.9
Downloading Python-3.7.9.tar.xz...
-> https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tar.xz
Installing Python-3.7.9...
ERROR: invalid Python executable: /home/rodpadev/.pyenv/versions/3.7.9/bin/python3.7

The python-build could not find proper executable of Python after successful build.
Please open an issue for future improvements.
https://github.com/pyenv/pyenv/issues

BUILD FAILED (Ubuntu 20.04 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20210305171353.830
Results logged to /tmp/python-build.20210305171353.830.log

Last 10 log lines:
  Templates:
    ava                Generate ava setup (ava)
    cli                Generate cli setup (minimist, tabtab, ge...)
    default            Generate default setup (babel-cli, babel-plu...)
    eslint             Generate eslint setup (eslint, eslint-confi...)
    livereactload      Generate livereactload setup (babel-plugin-react-t...)
    mocha              Generate mocha setup (mocha)
    simple             Generate simple setup
```
