### ISSUE TITLE
"No rule to make target 'pyconfig.h'"

### ISSUE THREAD

**Issue by EmilStenstrom** [pyenv/pyenv#1354]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
Platform information: macOS 10.14.5 (18F203)
OS architecture: x86_64
pyenv version: 1.2.11
Python version: 2.7.15 (but this happens with multiple versions
C Compiler information): Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Please attach verbose build log as gist: https://gist.github.com/EmilStenstrom/c0c2be063fb0a595c4639ea950d4421b

When I run `pyenv install 2.7.15` i get:

```
make: *** No rule to make target 'pyconfig.h', needed by 'Modules/python.o'.  Stop.
```

When I run `pyenv install 3.7.0` i get:

```
make: *** No rule to make target 'pyconfig.h', needed by 'Programs/python.o'.  Stop.
```

**Comment by creallfluharty** [comment]
The cause of issues (relating to "Pyconfig.h" existing, not a build target) on [this thread](https://github.com/okfn/piati/issues/65) (entirely different project) occurred when there were certain system packages that had not been installed. Have you verified that you have `python-dev` installed on your system?

**Comment by EmilStenstrom** [comment]
Hi, thanks for taking the time!

There seems to be no python-dev/python-devel-packages on macOS. [This thread](https://stackoverflow.com/questions/33843313/cant-find-a-way-to-install-python-dev-on-mac-os-x) suggests that those headers are installed automatically when installing python via brew (which I have).

**Comment by EmilStenstrom** [comment]
Note, this also happens when I try to install Python directly from the tarball.

```bash
wget https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tar.xz
tar xvf Python-2.7.15.tar.xz
cd Python-2.7.15
./configure && make
```

```make: *** No rule to make target `pyconfig.h', needed by `Modules/python.o'. Stop.```

**Comment by EmilStenstrom** [comment]
If I rename the file in the Python root from `pyconfig.h.in` to `pyconfig.h`, I get further in the installation process:

```
If you want a release build with all optimizations active (LTO, PGO, etc),
please run ./configure --enable-optimizations


gcc -c -fno-strict-aliasing -Qunused-arguments -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include -I/usr/local/opt/icu4c/include  -DPy_BUILD_CORE -o Modules/python.o ./Modules/python.c
gcc -c -fno-strict-aliasing -Qunused-arguments -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include -I/usr/local/opt/icu4c/include  -DPy_BUILD_CORE -o Parser/acceler.o Parser/acceler.c
gcc -c -fno-strict-aliasing -Qunused-arguments -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include -I/usr/local/opt/icu4c/include  -DPy_BUILD_CORE -o Parser/grammar1.o Parser/grammar1.c
gcc -c -fno-strict-aliasing -Qunused-arguments -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include -I/usr/local/opt/icu4c/include  -DPy_BUILD_CORE -o Parser/listnode.o Parser/listnode.c
gcc -c -fno-strict-aliasing -Qunused-arguments -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include -I/usr/local/opt/icu4c/include  -DPy_BUILD_CORE -o Parser/node.o Parser/node.c
gcc -c -fno-strict-aliasing -Qunused-arguments -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include -I/usr/local/opt/icu4c/include  -DPy_BUILD_CORE -o Parser/parser.o Parser/parser.c
gcc -c -fno-strict-aliasing -Qunused-arguments -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include -I/usr/local/opt/icu4c/include  -DPy_BUILD_CORE -o Parser/parsetok.o Parser/parsetok.c
gcc -c -fno-strict-aliasing -Qunused-arguments -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include -I/usr/local/opt/icu4c/include  -DPy_BUILD_CORE -o Parser/bitset.o Parser/bitset.c
gcc -c -fno-strict-aliasing -Qunused-arguments -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include -I/usr/local/opt/icu4c/include  -DPy_BUILD_CORE -o Parser/metagrammar.o Parser/metagrammar.c
gcc -c -fno-strict-aliasing -Qunused-arguments -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include -I/usr/local/opt/icu4c/include  -DPy_BUILD_CORE -o Parser/firstsets.o Parser/firstsets.c
gcc -c -fno-strict-aliasing -Qunused-arguments -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include -I/usr/local/opt/icu4c/include  -DPy_BUILD_CORE -o Parser/grammar.o Parser/grammar.c
Parser/grammar.c:186:13: warning: implicit declaration of function 'btowc' is invalid in C99
      [-Wimplicit-function-declaration]
        if (isalpha(Py_CHARMASK(lb->lb_str[1])) ||
            ^
Include/pyport.h:729:29: note: expanded from macro 'isalpha'
#define isalpha(c) iswalpha(btowc(c))
                            ^
Parser/grammar.c:186:13: warning: this function declaration is not a prototype [-Wstrict-prototypes]
Include/pyport.h:729:29: note: expanded from macro 'isalpha'
#define isalpha(c) iswalpha(btowc(c))
                            ^
2 warnings generated.
gcc -c -fno-strict-aliasing -Qunused-arguments -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include -I/usr/local/opt/icu4c/include  -DPy_BUILD_CORE -o Parser/pgen.o Parser/pgen.c
gcc -c -fno-strict-aliasing -Qunused-arguments -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include -I/usr/local/opt/icu4c/include  -DPy_BUILD_CORE -o Parser/myreadline.o Parser/myreadline.c
Parser/myreadline.c:50:9: error: use of undeclared identifier 'errno'
        errno = 0;
        ^
Parser/myreadline.c:204:10: warning: implicit declaration of function 'isatty' is invalid in C99
      [-Wimplicit-function-declaration]
    if (!isatty (fileno (sys_stdin)) || !isatty (fileno (sys_stdout)))
         ^
Parser/myreadline.c:204:10: warning: this function declaration is not a prototype [-Wstrict-prototypes]
2 warnings and 1 error generated.
make: *** [Parser/myreadline.o] Error 1
```

Which to me seems to be that it tries to use it's own readline instead of the one in brew.

**Comment by EmilStenstrom** [comment]
hmm... it seems the pyconfig.h file isn't created by `./configure`?

```
~/tmp/Python-2.7.15 $ ./configure
...
config.status: creating pyconfig.h
config.status: pyconfig.h is unchanged
creating Modules/Setup
creating Modules/Setup.local
creating Makefile
~/tmp/Python-2.7.15 $ find pyconfig.h
find: pyconfig.h: No such file or directory
```

**Comment by EmilStenstrom** [comment]
Here's a full log of running ´./configure --with-pydebug´: https://gist.github.com/EmilStenstrom/6300655c46b1640de1b720be732a4652

And here's one running `make -d`: https://gist.github.com/EmilStenstrom/8eb1185fba582058e562c66d5fbf2a07

**Comment by EmilStenstrom** [comment]
Problem solved. I had overridden the `diff` command in my `.bash_profile`. Uncommenting those lines make the `./configure` step detect that pyconfig.h needed to be created!

Thanks for chiming in to this two people display of "never override basic unix tools with your own versions". 🎊
