### ISSUE TITLE
pyenv uses wrong version of pip when system is default environment

### ISSUE THREAD

**Issue by ssbarnea** [pyenv/pyenv#1355]
I faced a really annoying issue where system is the implicit python version but pyenv shimming is hiding the correct pip version and makes it use pip from another environment
```
# pyenv versions
* system (set by /root/.pyenv/version)
* 3.4.9 (set by /root/.pyenv/version)
* 3.5.6 (set by /root/.pyenv/version)
* 3.6.8 (set by /root/.pyenv/version)
* 3.7.2 (set by /root/.pyenv/version)
* 3.8-dev (set by /root/.pyenv/version)
```

```
root@n0:~/rdo # /root/.pyenv/shims/pip --version
pip 19.0.3 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
```

```
root@n0:~/rdo # python --version
Python 2.7.5
```

As you can see pip goes to py36 instead of system py27 version and obviously that this is going to break lots of tools that assume that `pip` command uses the same interpreter as `python` command. 
```
root@n0:~/rdo # pip --version
pip 19.0.3 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
```

```
root@n0:~/rdo # which pip
/root/.pyenv/shims/pip
root@n0:~/rdo # which -a pip
/root/.pyenv/shims/pip
/usr/local/bin/pip
/usr/bin/pip
```

Any idea on how to fix this?

**Comment by marcingrabda** [comment]
Same issue here.

**Comment by MJGTwo** [comment]
Also have this!

**Comment by Etherealflux** [comment]
My default pip appears to be the first version listed when I ran `pyenv global`

e.g. `pyenv global 3.7.4 2.7.16` makes `pip` go to `pip3`, whilst `pyenv global 2.7.16 3.7.4` makes `pip` go to `pip2`.

**Comment by mhemeryck** [comment]
For me, the issue was when I had pip installed at user-level for python v2; when I ran `pip3 install --user -u pip` I think it did reinstall pip3 instead of pip2 over `~/.local/bin/pip`, fixing it for me.

**Comment by cruinh** [comment]
This is happening to me now as well

**Comment by mayank-ptl** [comment]
Same issue I can to access pip3  of default python 3.8.5 on system when I installed python 3.6.11 via Pyenv ,

**Comment by native-api** [comment]
"`system`" means that Pyenv just picks whatever is first further on PATH.

**Comment by shivdhar** [comment]
> For me, the issue was when I had pip installed at user-level for python v2; when I ran `pip3 install --user -u pip` I think it did reinstall pip3 instead of pip2 over `~/.local/bin/pip`, fixing it for me.

Thanks, this worked for me!
