### ISSUE TITLE
Discussion: Determinism of *conda builds

### ISSUE THREAD

**Issue by clbarnes** [pyenv/pyenv#1360]
Context: I'm writing a script to automate populating miniconda versions in pyenv-build (which are currently several years behind). It likely won't be hard to generalise it to anaconda, too.

It would be nice if calling `pyenv install miniconda-{version}` produced the same result every time. Pyenv obviously can't guarantee that the upstream artifacts won't change, but there are two situations where pyenv could, but does not, try to mitigate potential issues:

1. Fix versions (e.g. `4.3.30.1`, which is in the script for `4.3.30`). These tend to be OS/arch specific.
2. miniconda-latest

Miniconda-latest is a problem mainly because the resulting version ends up named `miniconda-latest` on the user's machine. Without the context of when that was installed, the user doesn't actually know what version it is. It would add complexity for the maintainers, but it may be more intuitive for the users if `pyenv install miniconda-latest` did not just grab the "Miniconda-latest" artifact, but was treated specially, like the 3.x-latest aliases. Installing miniconda-latest could find the latest available release; activating miniconda-latest could find the latest installed release.

IMHO, the current miniconda-latest adds more potential for confusion than it does convenience. Even if we don't choose to do *-latest handling ourselves, I would consider a policy which recommends they not be added to the pyenv-build list.

Fix versions are a bit more tricky. Obviously it's best to encourage users to use the patched version, but for every obsolete version of python, there's some person or company intentionally trying to use it. Determinism would be great, but introducing a bunch of OS/arch-specific fix versions is likely to be more confusing than it's worth.

There isn't necessarily a solution; just a strategy to be discussed. What do you think?

**Comment by MrPowers** [comment]
@clbarnes - thanks for the great contributions to this library and sorry in advance for the somewhat off topic comment.

Looks like [the current miniconda code is written in Python](https://github.com/pyenv/pyenv/blob/df9fa1dc30b6448ef8605e2c2d4dfc2a94d6a35d/plugins/python-build/scripts/add_miniconda.py).  It's the only Python file in this project.

From the README: "pyenv was made from pure shell scripts. There is no bootstrap problem of Python."

I'm a bit surprised to see conda stuff in this repo because I thought the sole purpose of this project was to switch between Python versions.  

Let me know your thoughts.  I am a Python noob, so feel free to educate me on why it's important to have Python code in this repo :)

**Comment by clbarnes** [comment]
Pyenv is a shell script utility which only requires a POSIX-ish shell to run. The script you've identified is not part of the tool, pyenv: it is purely for developers who *work* on pyenv. In exactly the same way, bats is not a requirement of pyenv, the tool: it's an additional dependency which contributors use during the development of pyenv.

Look at what that script actually does. It has nothing to do with the building of python versions, switching between them etc; it's purely to scrape from the web the commands one would need to run in a shell script in order to build particular versions of a particular distribution of python.

That script could have been written in any language. It could have been in bash, but that would have been much harder to read/write/maintain than the python version you see. Plus, anyone working on pyenv is likely to be familiar with, and have access to, python.

When minicoda releases new versions, one developer has to run that script once, which generates shell script code to be committed and PR'd. Nobody else, and no downstream users of pyenv, ever have to run that python script.

**Comment by native-api** [comment]
> IMHO, the current miniconda-latest adds more potential for confusion than it does convenience.

Not any more that `X.Y-dev` AFAICS. The name clearly indicates that this is a rolling release.

So in the light of https://github.com/pyenv/pyenv/pull/1361, the current situation is fine in my book.
