### ISSUE TITLE
pip still installs packages into ~/.local when `pyenv global my-custom-python-version`

### ISSUE THREAD

**Issue by jingw222** [pyenv/pyenv#1363]
I've installed Python 3.6.8 via `pyenv` and set it as the global interpreter by `pyenv global 3.6.8`. But when I try to pip install packages, they always sit somewhere inside `~/.local` instead of `~/.pyenv/versions/3.6.8/`. Is there anything misconfigured? By the way, that's not the case with some other Python version installed by `pyenv`, say 3.7.3, etc. Pretty weird.

**Comment by joshfriend** [comment]
Please provide the info requested by the issue template.
