### ISSUE TITLE
System Python does not exist

### ISSUE THREAD

**Issue by omenos** [pyenv/pyenv#1366]
### System Info
- [ ] Platform information: __RHEL 8.0__
- [ ] OS architecture: __x86_64__
- [ ] pyenv version: __1.2.12-2-geb68ec94__
- [ ] Python version: __3.7.3, 2.7.16__
- [ ] C Compiler information: __8.2.1__

## Description
Starting with RHEL 8, there is no system level Python distribution by default. There is only a platform specific one not intended to be used by anything but system tools (like `dnf`). This python version is stored in `/usr/libexec`. This is to help prevent users from being locked into a system level Python they don't want to use, and instead install the Python version they want from the AppStreams (like modules in Fedora). Currently that's 3.6.8 and 2.7.15.

On my system I had yet to install either of those global python versions before install `pyenv` and Python 3.7.3 and 2.7.16. A package I installed pulled in the python36 stream and thus installed the `python3` binary and its associated files in `/usr/bin`. If called directly it works just fine, as intended. However, `pyenv` does not seem to recognize its existence.

```bash
$ pyenv versions
* 2.7.16 (set by /home/mrochefort/.pyenv/version)
* 3.7.3 (set by /home/mrochefort/.pyenv/version)

$ pyenv global system
pyenv: system version not found in PATH
```

It would appear from this (not sure how else to debug this) that global python versions installed post-`pyenv` installation aren't picked up by default. I've tried rehashing to no avail.. I can try a uninstall/reinstall of `pyenv`, but just not at the moment.

**Comment by native-api** [comment]
You can set `$PYENV_DEBUG` and [`export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'`](https://wiki-dev.bash-hackers.org/scripting/debuggingtips#making_xtrace_more_useful) to debug.

The error is at https://github.com/pyenv/pyenv/blob/610346802358780ebccafdf112ba0c92b6cbaef0/libexec/pyenv-prefix#L37. But for "`system`", prefix shouldn't matter...

**Comment by draeath** [comment]
This still occurs on RHEL 8.2 (not that I expected that to change)

I believe this is because it is only looking for 'python' and not 'python3' - there is no python installed at all by default on RHEL8, let alone python2.

```
+ [pyenv-versions:105] PYENV_VERSION=system
+ [pyenv-versions:105] pyenv-which python
+ [pyenv-versions:109] shopt -s nullglob
+ [pyenv-versions:126] shopt -u nullglob
+ [pyenv-versions:128] '[' 0 -eq 0 ']'
+ [pyenv-versions:128] '[' -n 1 ']'
+ [pyenv-versions:129] echo 'Warning: no Python detected on the system'
```

```
[draeath@rhel8 ~]$ pyenv which python
pyenv: python: command not found

[draeath@rhel8 ~]$ pyenv which python3
/usr/bin/python3

[draeath@rhel8 ~]$ which python
/usr/bin/which: no python in (/home/draeath/.pyenv/plugins/pyenv-virtualenv/shims:/home/draeath/.pyenv/shims:/home/draeath/.pyenv/bin:/home/draeath/.local/bin:/home/draeath/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)

[draeath@rhel8 ~]$ which python3
/usr/bin/python3

[draeath@rhel8 ~]$ which python3.8
/usr/bin/python3.8
```

Code that would likely need to change to fix this:
https://github.com/pyenv/pyenv/blob/366c980166c86b2d376421051da7462cb04a099e/libexec/pyenv-versions#L104-L107
https://github.com/pyenv/pyenv/blob/366c980166c86b2d376421051da7462cb04a099e/libexec/pyenv-prefix#L32-L39

And maybe (unsure):
https://github.com/pyenv/pyenv/blob/366c980166c86b2d376421051da7462cb04a099e/test/which.bats#L136

**Comment by draeath** [comment]
PR #1655 should fix this

**Comment by omenos** [comment]
> PR #1655 should fix this

This should probably also account for `python2`, as installing the python27 stream will not install a `/usr/bin/python` binary/link. Python is expressly unversioned in RHEL 8, so the user decides using `alternatives` if they want a global `python` command.

**Comment by draeath** [comment]
I considered handling python2 as well, but the way that I saw to fix it duplicates more than I'd like - and this would include another duplication of that.

I figured, as python 2.x is now EOL, to leave that be. But it could easily be added as an additional boolean.

**Comment by native-api** [comment]
Since Pyenv supports handling EOL versions, too, it needs to be able to operate `python2` as the system version as well.

**Comment by longavailable** [comment]
I have the same problem. While I want to know how to get my system python back after the setup of `pyenv global 3.8.x`.
