### ISSUE TITLE
pyenv 3.7.3 fails but brew 3.7.3 has no error (flags = _re.IGNORECASE)

### ISSUE THREAD

**Issue by georgalis** [pyenv/pyenv#1367]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. 
    * https://stackoverflow.com/questions/56892696/attributeerror-module-re-has-no-attribute-ignorecase-only-in-pyenv-build
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): `macOS 10.14.5 (18F132)`
- [x] OS architecture (e.g. amd64): `Darwin sullen.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`
- [x] pyenv version: `pyenv 1.2.12` from brew
- [x] Python version: `3.7.3`
- [x] C Compiler information (e.g. gcc 7.3): `xcode-select version 2354.` 
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

## Issue
I have carefully updated and reinstalled pyenv, and 3.7.3, yet the following error only occurs with the pyenv 3.7.3 build of python.

``` pyenv install 3.7.3
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.3.tar.xz...
-> https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz
Installing Python-3.7.3...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.7.3 to /Users/geo/.pyenv/versions/3.7.3
```
Here is verbose invocation of `d2b.py 17 16`, with each python version. The program converts 17 to hexadecimal, `11` is the correct answer and the code follows. 
```
for p in /usr/bin/python /usr/local/bin/python /Users/geo/.pyenv/versions/3.7.3/bin/python /Users/geo/.pyenv/versions/2.7.16/bin/python ; do \
 echo "===" ; $p -V ; echo $p  ; $p lang/py/d2b.py 17 16
done
echo === ; cat lang/py/d2b.py
===
Python 2.7.10
/usr/bin/python
11
===
Python 2.7.16
/usr/local/bin/python
11
===
Python 3.7.3
/Users/geo/.pyenv/versions/3.7.3/bin/python
0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,Traceback (most recent call last):
  File "lang/py/d2b.py", line 2, in <module>
    import string
  File "/Users/geo/.pyenv/versions/3.7.3/lib/python3.7/string.py", line 78, in <module>
    class Template(metaclass=_TemplateMetaclass):
  File "/Users/geo/.pyenv/versions/3.7.3/lib/python3.7/string.py", line 88, in Template
    flags = _re.IGNORECASE
AttributeError: module 're' has no attribute 'IGNORECASE'
===
Python 2.7.16
/Users/geo/.pyenv/versions/2.7.16/bin/python
11
===
import sys
import string

digs = string.digits + string.ascii_letters

def d2b(x, b):
    if x < 0:
        sign = -1
    elif x == 0:
        return digs[0]
    else:
        sign = 1
    x *= sign
    digits = []
    while x:
        digits.append(digs[int(x % b)])
        x = int(x / b)
    if sign < 0:
        digits.append('-')
    digits.reverse()
    return ''.join(digits)

print(d2b(int(sys.argv[1]),int(sys.argv[2])))
```
I can only reproduce the error in the pyenv 3.7.3 build, not sure why.

**Comment by SnowOnion** [comment]
Did you place a `re.py` in the working directory?

**Comment by native-api** [comment]
The `_re` extension was probably not compiled.

Can't say anything else without seeing the build's debug trace as required by the issue template.

**Comment by native-api** [comment]
Debug that problem to see why the attribute is missing. I can't do that for you.
