### ISSUE TITLE
add tauthon interpreter

### ISSUE THREAD

**Issue by graingert** [pyenv/pyenv#1369]
Add tauthon: https://github.com/naftaliharris/tauthon/issues/111 a python 2 source compatible interpreter with support for some py3 syntax

**Comment by joshfriend** [comment]
I think that Tauthon is harmful to the python ecosystem, so we will likely not be adding it to pyenv

**Comment by graingert** [comment]
I don't see tauthon as harmful, I'm planning on using it to help transition a code base to Python 3

**Comment by graingert** [comment]
@joshfriend regardless of whether or not "tauthon is harmful to the python ecosystem", it is just as much a valid Python 2.7 implementation as jython-2.7 or pypy2 2.7
