### ISSUE TITLE
Support for pull-through cache-mirror of python packages

### ISSUE THREAD

**Issue by DenverJ** [pyenv/pyenv#1377]
We would like to configure pyenv to use an internal pull-through cache like Artifactory for downloading the python install files. Artifactory is configured with remote URLs and handles caching of objects locally on first request by a client.

PYTHON_BUILD_MIRROR_URL doesn't work for this purpose because it computes the hash of the file and tries to download that. This does not fit with the above use-case because artifactory preserves the original path and filename.

Perhaps another option - PYTHON_BUILD_CACHE_URL which simply replaces http://www.python.org with the specified value (which could be a hostname + path)?

**Comment by guyskk** [comment]
For example download python tarball from https://npm.taobao.org/mirrors/python, it's very useful in China mainland.

**Comment by gitfourteen** [comment]
> For example download python tarball from https://npm.taobao.org/mirrors/python, it's very useful in China mainland.

China is ZERO speed for now.

➜  ~ pyenv install 3.8.0
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.8.0.tar.xz...
-> https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tar.xz
error: failed to download Python-3.8.0.tar.xz

BUILD FAILED (OS X 10.15.1 using python-build 20180424)
