### ISSUE TITLE
Long paths break pyenv shebangs

### ISSUE THREAD

**Issue by sbienkow** [pyenv/pyenv#1383]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Mint 19.1
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 1.2.13

### Background
Kernel has a limit set for shebang / hashbang length. In Linux, it's usually 127 characters, as per: https://www.in-ulm.de/~mascheck/various/shebang/#results

Minimal reproduction:
```
# 13:18:59 sbienkow@Hostname pyenv_bug $ :)
./test.sh 
123456789a123456789b123456789c123456789d123456789e123456789f123456789g123456789h123456789i123456789j123456789k12345 ./test.sh
# 13:19:00 sbienkow@Hostname pyenv_bug $ :)
cat test.sh 
#!/bin/echo 123456789a123456789b123456789c123456789d123456789e123456789f123456789g123456789h123456789i123456789j123456789k12345done
```
Notice that `done` wasn't printed -it was cut right before it.

### Issue
It's an issue since pyenv relies on shebangs to use specific version of python when executing commands:

```
+ [pyenv-exec:47] exec -a howdoi /home/myuser/.pyenv/versions/my-super-long-virtualenv-name-that-comes-probably-from-some-CI-CD-system-or-was-created-for-a-different-reason/bin/howdoi
/home/myuser/.pyenv/libexec/pyenv-exec: /home/myuser/.pyenv/versions/my-super-long-virtualenv-name-that-comes-probably-from-some-CI-CD-system-or-was-created-for-a-different-reason/bin/howdoi: /home/myuser/.pyenv/versions/3.7.3/envs/my-super-long-virtualenv-name-that-comes-probably-from-some-CI-CD-system-or-was-creat: bad interpreter: No such file or directory
/home/myuser/.pyenv/libexec/pyenv-exec: line 47: /home/myuser/.pyenv/versions/my-super-long-virtualenv-name-that-comes-probably-from-some-CI-CD-system-or-was-created-for-a-different-reason/bin/howdoi: Success
```

Try it yourself:

```
pyenv virtualenv 3.7.3 my-super-long-virtualenv-name-that-comes-probably-from-some-CI-CD-system-or-was-created-for-a-different-reason
pyenv activate my-super-long-virtualenv-name-that-comes-probably-from-some-CI-CD-system-or-was-created-for-a-different-reason
pip install howdoi
PYENV_DEBUG=1 howdoi 
```

Notice that I used virtualenv package for this reproduction, since it's easiest, but it can be reproduced with a plain pyenv - i.e. have PYENV_ROOT somewhere deep in the filesystem.

### Solution
There's a few solutions that work around this, most common is just running the script as shell script, then exec itself, passing a correct version. 

For example, virtualenv uses:
```
$ head -n3 /tmp/my/super-duper/long-directory-structure/oneoneoneoneoneoneone/hdfsjksdjhfjksdhkadsjhfjshdjkfdsfjkdsf/i-like-cats/venv/bin/howdoi 
#!/bin/sh
'''exec' /tmp/my/super-duper/long-directory-structure/oneoneoneoneoneoneone/hdfsjksdjhfjksdhkadsjhfjshdjkfdsfjkdsf/i-like-cats/venv/bin/python3 "$0" "$@"
' '''
```

This causes shell to interpret the line with exec (will just combine the empty string and the string with `exec` to create the name to call with arguments following), and python just treats it as docstring, so it continues.

Related virtualenv issue: https://github.com/pypa/virtualenv/issues/596#issuecomment-150390548

**Comment by native-api** [comment]
>  pyenv relies on shebangs to use specific version of python when executing commands

Don't understand what this means. Probably was fixed since because Pyenv does not rely on shebangs at the moment.
