### ISSUE TITLE
Add link to the installer in the GitHub title

### ISSUE THREAD

**Issue by rogerdahl** [pyenv/pyenv#1387]
It's a bit hard to find the link to the automatic installer in the README. GitHub has the option of adding a link to a website in the top title. I think a link to the installer would fit nicely there :)

**Comment by native-api** [comment]
Automatic installer is not a link, it's an invocation (that doenloads a script and passes it to `bash`). Moreover, it's a different project so linking to it as an official website is inappropriate.

A quick start guide would help in your use case, see https://github.com/pyenv/pyenv/issues/1677.
