### ISSUE TITLE
OSX generate-posix-vars Failed

### ISSUE THREAD

**Issue by Knoose** [pyenv/pyenv#1388]
Platform information: macOS 10.14.6
OS architecture: intel
pyenv version: pyenv 1.2.13
Python version: Python 3.7.1
C Compiler information:  /usr/include/c++/4.2.1

I am having issues trying to build python on my OSX machine. I was having the same issue under 10.12.x but I thought it might have been ab OS issue. I updated to 10.14.x but the issues seems to persist. 

Does anyone know how I can get past this? It looks as if it's trying to build python with python.exe, which obviously will not work on OSX. 

> Last 10 log lines:
> ./python.exe -E -S -m sysconfig --generate-posix-vars ;\
> 	if test $? -ne 0 ; then \
> 		echo "generate-posix-vars failed" ; \
> 		rm -f ./pybuilddir.txt ; \
> 		exit 1 ; \
> 	fi
> /bin/sh: line 1: 56592 Killed: 9               ./python.exe -E -S -m sysconfig --generate-posix-vars
> generate-posix-vars failed
> make: *** [pybuilddir.txt] Error 1
> make: *** Waiting for unfinished jobs....
> 

edit:
I installed pyenv doctor and I can get it to work successfully. 

[python-build.20190829165237.45181.gist.zip](https://github.com/pyenv/pyenv/files/3557737/python-build.20190829165237.45181.gist.zip)

**Comment by albireox** [comment]
Same problem here but with 10.15 beta. Both pyenv and homebrew seem to fail with the message above when trying to install Python. I have been able to successfully compile Python 3.8.0b4 manually by exporting the variables

```
CPPFLAGS="-I/opt/X11/include -I/usr/local/opt/zlib/include -I/usr/local/opt/sqlite3/include -I/usr/local/opt/openssl/include"
LDFLAGS="-L/opt/X11/lib -L/usr/local/lib -L/usr/local/opt/openssl/lib"
```
