### ISSUE TITLE
Include beta versions

### ISSUE THREAD

**Issue by Juanlu001** [pyenv/pyenv#1389]
Two days ago CPython 3.8.0b4 was released:

https://www.python.org/downloads/release/python-380b4/

However, pyenv will only allow `3.8-dev`, which has two disadvantages:

* It requires cloning the full CPython repository, which is much slower than downloading the source tarball
* At this moment it's two commits ahead of 3.8.0b4, and will be more separated in the future

There was a commit claiming to add CPython 3.8.0b1 (https://github.com/pyenv/pyenv/commit/2350e57b00f0003e156f65b0555d823c96c069c9) but in fact it was adding the git install from the `3.8` branch.

**Comment by KevOrr** [comment]
Was there a fix for this? It'd be nice to be able to install any tag of cpython
