### ISSUE TITLE
Documentation: Zsh should modify zshrc instead of zshenv 

### ISSUE THREAD

**Issue by ryanermita** [pyenv/pyenv#1400]
# Description
- macOS Mojave
- pyenv version: 1.2.13
- Python version: 2.7.16 (system default)
- z shell version: zsh 5.3 (x86_64-apple-darwin18.0)
- homebrew version: 2.1.11

In the [installation guide](https://github.com/pyenv/pyenv#installation), for the step 3 it says that:
```
Zsh note: Modify your ~/.zshenv file instead of ~/.bash_profile.
```

this step makes `pyenv` unable to use shims properly and I encounter this issue #1238 . this is solved (https://github.com/pyenv/pyenv/issues/1238#issuecomment-533856021) by moving this code snippet below from `.zshenv` to `.zshrc`
```
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
```
Is this a documentation issue or related specifically to zsh version?

**Comment by mazzma12** [comment]
and what about `~/.zprofile` (It is sourced at the login session) ? I have it this way and no problems at the moment.

**Comment by hsnusonic** [comment]
* zsh version: 5.7.1
* Homebrew version: 2.1.11

I used `brew install pyenv` and followed the installation guide. I also found that `.zshenv` not worked for me, so I use `.zprofile` instead.

**Comment by ryanermita** [comment]
@mazzma12 @hsnusonic I include the zsh and homebrew version in the issue description, this might be helpful for this issue.

**Comment by joshfriend** [comment]
`.zshrc` is only sourced for interactive shells, whereas `.zshenv` is always sourced. Moving the init could cause you other problems.

**Comment by ryanermita** [comment]
ohh. thanks for the info @joshfriend

**Comment by kekhuay** [comment]
i can confirm that `.zshenv` doesn't work on Arch Linux and OSX but `.zshrc` and `.zprofile` does.

**Comment by tekumara** [comment]
I've also encountered this problem on macOS Mojave with `brew install pyenv`.

brew installs pyenv into `/usr/local/bin`. However when `command -v pyenv` runs inside `.zshenv`, the path does not yet contain `/usr/local/bin` and so pyenv isn't initialised.

`/etc/zprofile` adds `/usr/local/bin` to the path but runs ***after*** `.zshenv`.

The execution order is:
```
.zshenv → [.zprofile if login] → [.zshrc if interactive] → [.zlogin if login] → [.zlogout sometimes]
```

So on systems where pyenv is installed into `/usr/local/bin` either

1. Run the following in `~/.zprofile` or `~/.zshrc` 
```
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
```
2. Run the following in `~/.zshenv`
```
if [[ -f /usr/local/bin/pyenv ]]; then
    eval "$(/usr/local/bin/pyenv init -)"
fi
```

`.zshenv` is always sourced by zsh, even when running a single command (eg: `zsh -c ...`). If that's important to you, use option 2. I've used option 1 with `~/.zshrc` (as have my colleagues) successfully without issue.

@ryanermita @joshfriend  can the `README.md` be updated to reflect this?

**Comment by tekumara** [comment]
After further testing updating `~/.zshenv` as per option 2 above ☝️doesn't work on macOS Mojave.

The problem is `/etc/zprofile/` runs after `~/.zshenv` and prefixes the path with `/usr/bin/python` and so the `pyenv/.shims` path ends up with lower precedence.

Instead update `~/.zshrc`

**Comment by leochoo** [comment]
So will the README.md every get fixed from `zshenv` to `zshrc`?

**Comment by joshfriend** [comment]
@tekumara thanks for the helpful walkthrough.
