### ISSUE TITLE
`pip` installations don't seem to work

### ISSUE THREAD

**Issue by farzadmf** [pyenv/pyenv#1403]
### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04):
Manjaro and kernel information: `Linux 5.2.17-1-MANJARO`
- [x] OS architecture (e.g. amd64): `amd64`
- [x] pyenv version: `1.2.13`
- [x] Python version: `3.7.4` (installed with `pyenv`
- [x] C Compiler information (e.g. gcc 7.3): `gcc (GCC) 9.1.0`

Hi, I recently re-installed my OS (Manjaro), and I'm having all sorts of confusing problems with `pyenv`.

# What I used to see

I would do this:

```bash
pyenv install 3.7.4
pyenv global 3.7.4
pyenv virtualenv 3.7.4 neovim-python3
pyenv activate neovim-python3
pip install -q upgarde pip neovim
```

- When I did `pip list` in my `virtualenv`, I saw my list of packages (`pynvim`, `neovim`, etc)
- Then I could do `pyenv deactivate`, followed by `pip list`. I would not see any of the installed packages in my `virtualenv`, and I would install the packages I want in my main environment

# What's happening now

I do the same:

```bash
pyenv install 3.7.4
pyenv global 3.7.4
pyenv virtualenv 3.7.4 neovim-python3
```

The output I see is a bit confusing for me (why does it say "requirement already satisfied"?)
```
Looking in links: /tmp/tmpgcrfoa22
Requirement already satisfied: setuptools in /home/farzad/.pyenv/versions/3.7.4/envs/python3-neovim/lib/python3.7/site-packages (40.8.0)
Requirement already satisfied: pip in /home/farzad/.pyenv/versions/3.7.4/envs/python3-neovim/lib/python3.7/site-packages (19.0.3)
```

I activate my `virtualenv` and install some packages:

```bash
pyenv activate neovim-python3
pip install -q upgarde pip neovim
```

I see traces of messages indicating that packages are being installed:
```
Requirement already up-to-date: pip in /usr/lib/python3.7/site-packages (19.2.3)
Collecting neovim
  Using cached ...
Collecting pynvim>=0.3.1 (from neovim)
  Using cached ...
Requirement already satisfied, skipping upgrade: msgpack>=0.5.0 in /usr/lib/python3.7/site-packages (from pynvim>=0.3.1->neovim) (0.6.1)
Collecting greenlet (from pynvim>=0.3.1->neovim)
  Using cached ...
Installing collected packages: greenlet, pynvim, neovim
  Running setup.py install for pynvim ... done
  Running setup.py install for neovim ... done
Successfully installed greenlet-0.4.15 neovim-0.3.1 pynvim-0.3.2
```

When I do `pip list` (in my `virtualenv`), I see list of packages:
```
Package  Version
-------- -------
greenlet 0.4.15 
neovim   0.3.1  
pynvim   0.3.2  
```

I do `pip --version`:
```
pip 19.2.3 from /usr/lib/python3.7/site-packages/pip (python 3.7)
```

I'm pretty sure this is not right; shouldn't `pip` point to something inside my `$HOME/.pyenv`?

I do:
```
pyenv deactivate
pip list
```

And I see the same list of packages, which makes sense because `pip --version` shows the same thing:
```
pip 19.2.3 from /usr/lib/python3.7/site-packages/pip (python 3.7)
```

Can you please tell me what's happening. I didn't use to have any sorts of problem with `pyenv` whatsoever, but I'm not sure what I'm missing here 😥

**Comment by scrazycarl** [comment]
I am having the same confusion....all my packages I wanted to install locally ended up globally..Do you have any update on this?

**Comment by CelestialGuru** [comment]
`which python` returns:
```
/home/brian/.pyenv/shims/python
```
`which pip` returns:
```
/home/brian/.local/bin/pip
```
Why doens't `which pip` return something like `.pyenv/.../pip`?

**Comment by native-api** [comment]
Can't say anything without a debug trace as required by the issue teamplate.
My guess is either Pip failed to install for 3.7.4 or PATH is wrong.
