### ISSUE TITLE
conda interposes between system python

### ISSUE THREAD

**Issue by matiasbattocchia** [pyenv/pyenv#1407]
### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Arch Linux 5.2.8-arch1-1-ARCH 
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 1.2.13-17-g38de38e3
- [x] Python version: 3.7.4
- [x] C Compiler information (e.g. gcc 7.3): gcc 9.1.0
- [x] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

---

With **miniconda3** (installed through `pyenv install`) it seems that a conda **base** environment is active by default, whenever I launch a terminal.

```
(base)  matias@vapor$ pyenv global
system
(base)  matias@vapor$ pyenv which python
/home/matias/.pyenv/versions/miniconda3-4.3.30/bin/python
```

I can fix this temporally with `conda deactivate` or permanently with `pyenv uninstall miniconda3`.

```
(base)  matias@vapor$ conda deactivate
 matias@vapor$ pyenv which python
/usr/bin/python
```

However if I set a global (or local) version different than system the binary is correct. Conda base environment remains active, though.

```
(base)  matias@vapor$ pyenv global 3.7.3
(base)  matias@vapor$ pyenv which python
/home/matias/.pyenv/versions/3.7.3/bin/python
(base)  matias@vapor$ pyenv global system
(base)  matias@vapor$ pyenv which python 
/home/matias/.pyenv/versions/miniconda3-4.3.30/bin/python
```

**Comment by connerxyz** [comment]
I'm new to pyenv and seeing this as well. Trying to figure out if it's a feature or a bug.

**Comment by Holi0317** [comment]
Write this line to `~/.condarc` file:

```
auto_activate_base: False
```
