### ISSUE TITLE
GCC Can Not Find "Python.h" When Using Pyenv

### ISSUE THREAD

**Issue by FifteenOUC** [pyenv/pyenv#1408]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04):MacOS 10.12.6
- [x] OS architecture (e.g. amd64):Intel Core i7
- [x] pyenv version:1.2.13
- [x] Python version:Python3.7-dev
- [x] C Compiler information (e.g. gcc 7.3): gcc Apple LLVM version 9.0.0
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

---

Hi, there

I have installed Pyenv and Python3.9-dev suceessfully. It works. Unfortunately, when I try to include Python.h in my C files, GCC can not find "Python.h" like this:
``` shell
$ pyenv version
3.7-dev (set by /Volumes/D/hello_world/.python-version)

$ gcc hello.c -o hello
hello.c:3:10: fatal error: 'Python.h' file not found
#include "Python.h"
         ^~~~~~~~~~
1 error generated.
```

It seems that pyenv only change the python verson when using Shell so that GCC can not find Python Libs. 
Please tell me if there is a way way to fix that.

**Comment by ttllttttlltt** [comment]
Tell GCC where to find the .h file with "-I":

gcc -c -I/Volumes/D/hello_world/.python-version hello.c -o hello
Replace the path with where your .h file is

**Comment by FifteenOUC** [comment]
I worked out this issue. According to what @ttllttttlltt said, I found that Pyenv also changed Python-config. So we can complie it by `gcc hello.c -o hello  $(python-config --includes) $(python-config --libs) $(python-config --ldflags)`.
