### ISSUE TITLE
error /usr/local/bin/python-build: line 251: /usr/bin/ "shasum": Permission denied

### ISSUE THREAD

**Issue by Justsoos** [pyenv/pyenv#1414]
macos high sierra 10.13.6
Homebrew 2.1.11-151-g5354ba8
pyenv 1.2.13 homebrew
error prompt occur at pyenv install procedure 
```
-rw-rw-rw-  37 root  wheel  /usr/bin/shasum
```
check `/usr/bin/shasum`, it is a script of perl, but never did anything with the permissions of this file for MacOS in mind

**Comment by joshfriend** [comment]
please provide all the information requested in the issue template
