### ISSUE TITLE
Patch CPython to search compiler output for include/library paths

### ISSUE THREAD

**Issue by Flamefire** [pyenv/pyenv#1415]
I wanted to use pyenv on a HPC system using LMod modules. Basically: Packages are not installed system-wide but can be loaded via commands that modify environment variables such as CPATH, LD_LIBRARY_PATH, LIBRARY_PATH, PATH.

The problem: A [change](https://github.com/python/cpython/commit/cc5addd3b64919af67d25a1c4d577008b05e0967#diff-2eeaed663bd0d25b7e608891384b7298R442) in CPython from ages ago made the build process not pick up the libraries which fails the build with hints:
```
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
```
Note I use "failed" because bz2 is often required in python modules.

A solution is to patch `setup.py`:
1. Remove the `if cross_compiling:` to always add paths from the compiler
2. Force the sub-processes to run with `LC_ALL=C` (or pyenv-build in general)

Without 2. the build still fails due to localizing "gcc version" -> "gcc-Version" and "#include <...>" ->" Suche für »#include <...>"

Such a patch needs to be applied to all currently supported Python versions. Not sure how to best approach this.

**Comment by native-api** [comment]
As you can see from that commit, [that change was made because it was causing issues](https://github.com/python/cpython/commit/cc5addd3b64919af67d25a1c4d577008b05e0967#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R441).

Compiler output is not designed to be machine-readable so a technique like this is bound to be unreliable.

You can already pass custom flags to a build if they are needed on your system as per https://github.com/pyenv/pyenv/blob/master/plugins/python-build/README.md#special-environment-variables

**Comment by Flamefire** [comment]
> Compiler output is not designed to be machine-readable so a technique like this is bound to be unreliable.

I know, however this is what is done: https://github.com/python/cpython/blob/cc5addd3b64919af67d25a1c4d577008b05e0967/setup.py#L416

One method to make it a lot more reliable would be to disable localization of the compiler output. This is what e.g. CMake does for parsing such output.
Is there any downside to this or why will this not be done?

As for the issues, you mean the comment "only change this for cross builds for 3.3, issues on Mageia"? I haven't found what that issue is and if there would have been another solution neither in the linked Github PR nor in the there-linked Python bug entry.
IMO users installing dependencies into non-system directories (like /opt) and setting CPATH, LIBRARY_PATH and LD_LIBRARY_PATH so that those are found is a quite common use case which works out-of-the-box with pretty much everything but projects who decide to ignore the user environment (Bazel is a prime example here, while automake, cmake, ... all take those into account)

**Comment by Queuecumber** [comment]
@Flamefire Did you find any solution to this? I have a very similar situation to what you described and I install headers and libraries to `~/.local/include` and `~/.local/lib` and I was surprised that none of the standard env vars seem to be picked up by the pyenv build.

As you mentioned these variables are standard tools which should not be overridden

**Comment by native-api** [comment]
This is an upstream issue. All we can do is accept a patch to CPython that fixes it. But it must not break the build in any of the supported environments as per https://github.com/pyenv/pyenv/blob/master/CONTRIBUTING.md#adding-version-specific-fixespatches .

So the most fool-proof way probably is to fix it upstream, then we can backport the fix to affected versions.
