### ISSUE TITLE
Add python-build-standalone pre-built redistributable Python releases

### ISSUE THREAD

**Issue by jayvdb** [pyenv/pyenv#1417]
https://github.com/indygreg/python-build-standalone [releases](https://github.com/indygreg/python-build-standalone/releases) contain the following assets

- `cpython-3.7.4-linux64-<isodate>.tar.zst` (24 MB)
- `cpython-3.7.4-linux64-musl-<isodate>.tar.zst` (23.1 MB)
- `cpython-3.7.4-macos-<isodate>.tar.zst` (20.9 MB)
- `cpython-3.7.4-windows-amd64-<isodate>.tar.zst` (18.3 MB)
- `cpython-3.7.4-windows-x86-<isodate>.tar.zst` (16.5 MB)

These are pre-built as the environment and configuration to build them is quite specific to ensure that output is suitable for redistributable builds of Python.  i.e. it uses static links against the dependencies, and therefore it needs to choose dependencies to avoids static linkages where the license doesnt permit them, such as removing GPL dependencies (GDBM and readline).

Notably it provides musl builds.

**Comment by native-api** [comment]
I guess as long as you're willing to write and maintain the necessary installation scripts yourself... What do other team members think?

For starters, how likely are these builds to have incompatibilities (since it's here where users are going to go with their problems and we have no idea what to respond to them)?
Since these are prebuilt, they must be built with some assumptions about the system in mind. You'll likely need to insert some kind of guard into the insallation script (like [`require_distro()`](https://github.com/pyenv/pyenv/blob/debf1abd8bd624ba8f9f902f00e5c9098e99dede/plugins/python-build/bin/python-build#L1264-L1277)) to make sure the user's system is compatible.

**Comment by anton-petrov** [comment]
Personally, I do not support this idea of ​​depending on an external source of dubious origin. What is the need for this, especially with regard to standard CPython? Standard python-build works well and that's more than enough.  So, I see no reason to invest additional resources in development of this feature.

**Comment by native-api** [comment]
@jayvdb Spelunking in `python-build`, I discovered that you don't even need to fork!

Just place your definitions into `$PYENV_ROOT/plugins/*/share/python-build` -- [and `pyenv install` will see them](https://github.com/pyenv/pyenv/blob/d02b929d07182578bc16eb256b6b9a5e4c7a2db8/plugins/python-build/bin/pyenv-install#L33)!

So you can add them with a plugin.

**Comment by ketozhang** [comment]
> Personally, I do not support this idea of ​​depending on an external source of dubious origin. 

Good point. Although the indygreg's project isn't unpopular, I can't validate it's security.

> What is the need for this, especially with regard to standard CPython? Standard python-build works well and that's more than enough. 

Compiling CPython can be hard for users. The first issue user commonly face is either not having a compiler, an outdated OpenSSL, `pyenv` doesn't really help with that.

**Comment by tekumara** [comment]
+1 compiling CPython can be hard, and also really slow to build with optimisations. It also isn't the default, so typically this doesn't happen. Whereas [indygreg/python-build-standalone](https://github.com/indygreg/python-build-standalone) provides builds with optimisations (PGO and LTO).

**Comment by newbery** [comment]
> [@jayvdb](https://github.com/jayvdb) Spelunking in `python-build`, I discovered that you don't even need to fork!
> 
> Just place your definitions into `$PYENV_ROOT/plugins/*/share/python-build` -- [and `pyenv install` will see them](https://github.com/pyenv/pyenv/blob/d02b929d07182578bc16eb256b6b9a5e4c7a2db8/plugins/python-build/bin/pyenv-install#L33)!
> 
> So you can add them with a plugin.

Is there a plugin already to add build definitions from the python-build-standalone repository? This would be very handy.
For context, lacking this capability, I've instead been using uv to handle my python installs with some pyenv-lile shims to handle python discovery. I seem to have mostly abandoned pyenv as a result.
