### ISSUE TITLE
Filter list of installable versions

### ISSUE THREAD

**Issue by JayPalm** [pyenv/pyenv#1428]
It would be great to be able to filter the list of installed versions. 

When you type this: `pyenv install -l` you get a long list of options. 

It would be handy to have a way to filter that down, perhaps something like `pyenv install -l 3.7.*` to only show 3.7.* releases, or `pyenv install -l anaconda3-*` to only show the relevant anaconda3 versions available.

**Comment by joshfriend** [comment]
using the pyenv plugin for OhMyZsh will let you tab complete available versions: 

https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/pyenv/pyenv.plugin.zsh
