### ISSUE TITLE
Debian Package

### ISSUE THREAD

**Issue by rosieeyes** [pyenv/pyenv#1429]
Hi, this isn't an issue as such, but I wanted to ask if it would be okay for me to build and maintain a Debian package for pyenv? I don't have any experience with packaging, but I'd like to try, and it doesn't seem all that hard (looking through the Debian packaging instructions here: https://wiki.debian.org/Packaging/Intro).

**Comment by curradium** [comment]
Update: Under the assumption that it's okay to do so, I filed an ITP with the Debian BTS, and will work on the package now. :) Hope to package it for Ubuntu soon after!

**Comment by rodelrod** [comment]
This would be great! How did it go @curradium ? I see a separate ITP here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978476

**Comment by curradium** [comment]
I had a working .deb built, but my ITP didn't get any traction. Unfortunately, I had to put it on my backlog of various projects, and I'm not sure when I'll be coming back to it. Hopefully by the summer or sooner, but my work might not even be needed at that point!

You can see the progress I made here; specifically, all of the work in the debian/ dir. It still needs some work, but it's mostly ready to go.

**Comment by native-api** [comment]
Closing this ticket since this is not a task for this upstream project (if we ever do that, it's probably going to be a separate repo) -- but if someone wants to continue the effort, you're welcome!

Apparently, @karthek-git is also working on a Debian package: https://github.com/pyenv/pyenv/pull/1790#issuecomment-780877312

**Comment by karthek-git** [comment]
There is already a Debian package you can download it from here https://mentors.debian.net/package/pyenv/ .
Will be in Debian repo for next stable release(not Bullseye)
