### ISSUE TITLE
pyenv can't install python versions / "Missing SSL lib ?"

### ISSUE THREAD

**Issue by Cbhihe** [pyenv/pyenv#1432]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04):
- [X] OS architecture (e.g. amd64):
- [X] pyenv version:
- [X] Python version:
- [X] C Compiler information (e.g. gcc 7.3): 
- [X] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

==========================================

Platform: Arch Linux  5.3.7-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 18 00:17:03 UTC 2019
OS architecture: x86_64
pyenv version: 1.2.14-6-gddc56ebe
Global Python version: 3.7.4
Attempt to install python version: 3.1.0
C Compiler version: gcc 9.2.0
... with 2 build logs attached.

==========================================

Hello,<BR>
0) I am not sure I am not asking you to solve my own very particular issue. If it turns out to be the case, I will definitely turn to SO or SE. Tx.
1) Title is similar to that of closed issue #1378 but the log looks different. <BR>
2) I did consult https://github.com/pyenv/pyenv/wiki/common-build-problems
in particular section "_ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?_",  where for Arch linux it is recommended to issue:

`$ LDFLAGS="-L/usr/lib/openssl-1.0" CFLAGS="-I/usr/include/openssl-1.0" pyenv install -v 3.1.0`

**Verbose build log attached.**<BR>
[python-build.20191019180717.89795.log](https://github.com/pyenv/pyenv/files/3746909/python-build.20191019180717.89795.log)

I also the explicit vebose flag for debugging with result as follows:

`$ env PYENV_DEBUG=1  LDFLAGS="-L/usr/lib/openssl-1.0" CFLAGS="-I/usr/include/openssl-1.0" pyenv install -v 3.1.0`

**Verbose build log attached.**<BR>
[python-build.20191019181649.102844.log](https://github.com/pyenv/pyenv/files/3746904/python-build.20191019181649.102844.log)

The error was always:  "_ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?_".  The logs indicate that first warnings occur at gcc compilation (line 545 in log).

This seems to affect all versions I try to install, except for the current ones (/usr/bin/python3 v3.7.4 and /usr/bin/python2 v2.7.16).

**Comment by jgsinn** [comment]
@Cbhihe were you able to find a fix for this issue?

**Comment by Cbhihe** [comment]
Solved. With successive updates.

**Comment by rpedigoni** [comment]
If you need Python < 3.5.1:
```
brew uninstall --ignore-dependencies openssl@1.1
pyenv install -v 2.7.1
```
Then reinstall `openssl` using brew: 
```
brew install openssl@1.1
```
See https://github.com/pyenv/pyenv/issues/950#issuecomment-624131159
