### ISSUE TITLE
Pyenv ValueError: unknown locale: UTF-8 

### ISSUE THREAD

**Issue by johannhuang** [pyenv/pyenv#1437]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ x ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ x ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ x ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ x ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ x ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ x ] Platform information (e.g. Ubuntu Linux 16.04): macOS Mojave
- [ x ] OS architecture (e.g. amd64): macos
- [ x ] pyenv version: pyenv 1.2.8
- [ x ] Python version: 3.7.0
- [ ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

I'm sorry that I am not really sure this is a pyenv issue or not!

But I have really tried the Environment solution `export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8` found at <https://stackoverflow.com/questions/38916461/valueerror-unknown-locale-utf-8-when-importing-pandas-in-python-2-7>, but it doesn't work.
I have also tested with `python  -c 'import locale; print(locale.getdefaultlocale());'` and it says `('en_US', 'UTF-8')` under pyenv python 3.7.0.
In the same shell terminal, I have also run `locale` and it gives perfect result as following:
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```
seems to be perfect.

However, the only clue I get get is as the following:

```
Traceback (most recent call last):
  File "/Users/johann/.pyenv/versions/3.7.0/lib/python3.7/site-packages/wx/core.py", line 2202, in OnPreInit
    self.InitLocale()
  File "/Users/johann/.pyenv/versions/3.7.0/lib/python3.7/site-packages/wx/core.py", line 2262, in InitLocale
    loc, enc = locale.getlocale()
  File "/Users/johann/.pyenv/versions/3.7.0/Python.framework/Versions/3.7/lib/python3.7/locale.py", line 587, in getlocale
    return _parse_localename(localename)
  File "/Users/johann/.pyenv/versions/3.7.0/Python.framework/Versions/3.7/lib/python3.7/locale.py", line 495, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

So I guess, does pyenv python using a different way to read my environment variables?

**Comment by native-api** [comment]
[For some reason, `_parse_localename` gets just "UTF-8" as locale](https://github.com/python/cpython/blob/v3.7.0/Lib/locale.py#L467-L495) rather than the full "en_US.UTF8".

Pyenv doesn't touch locale stuff so this isn't Pyenv-related.

I suggest you to run the faulty progran under debugger to find out where the erroneous value is coming from.
