### ISSUE TITLE
[Question] on command 'which pyenv'

### ISSUE THREAD

**Issue by gitfourteen** [pyenv/pyenv#1443]
MacOs Mojave `brew install` pyenv and check with `which pyenv`. Below is the result. Is this a standard output for pyenv? If not, will you help explain what's this about?
```
➜  ~ which pyenv
pyenv () {
	local command
	command="${1:-}" 
	if [ "$#" -gt 0 ]
	then
		shift
	fi
	case "$command" in
		(rehash | shell) eval "$(pyenv "sh-$command" "$@")" ;;
		(*) command pyenv "$command" "$@" ;;
	esac
}
```

and when I use this command:
`echo $PATH | grep --color=auto "$(pyenv root)/shims"`
it successfully identified the `pyenv root` path.

`/Users/user_name/.pyenv/shims:/Users/user_name/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

other info:

```
➜  ~ brew list
autoconf	libidn2		openssl@1.1	python		telnet
gdbm		libunistring	pkg-config	readline	wget
gettext		openssl		pyenv		sqlite		xz
➜  ~ brew info python
python: stable 3.7.4 (bottled), HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python/3.7.4_1 (3,934 files, 61MB) *
  Poured from bottle on 2019-10-28 at 19:41:22
......
```

**Comment by joshfriend** [comment]
Yes, this is expected. It comes from [`pyenv-init`](https://github.com/pyenv/pyenv/blob/master/libexec/pyenv-init)
