### ISSUE TITLE
Tag new release for 3.7.5?

### ISSUE THREAD

**Issue by jalessio** [pyenv/pyenv#1444]
Could you tag a release which includes Python 3.7.5? I'd like to update the [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pyenv.rb) but need a tag in this repo to do so.

Here's the current diff between the latest release, v1.2.14 and master:
https://github.com/pyenv/pyenv/compare/v1.2.14...master

Thanks!

**Comment by joshfriend** [comment]
https://github.com/pyenv/pyenv/commit/b5f69fe58a58f3d2d59511c4630c96aafe5ad2b0

**Comment by jalessio** [comment]
@joshfriend thx for the quick attention to this, but we didn't end up with an actual tag in the repo so I can't proceed with the Homebrew update quite yet. Can you please add the `v1.2.15` tag at commit b5f69fe? Thank you!

**Comment by joshfriend** [comment]
oops, fixed
