### ISSUE TITLE
`pyenv help realpath.dylib' results in "sed: RE error: illegal byte sequence"

### ISSUE THREAD

**Issue by ericvw** [pyenv/pyenv#1454]
This recently came to my attention since the [v1.2.15](https://github.com/pyenv/pyenv/blob/master/CHANGELOG.md#1215) release which enabled showing text for all `pyenv` commands.

Due to `realpath.dylib` being a compiled binary, the normal shell routines for extracting the help text won't work.

### Details
- Platform information (e.g. Ubuntu Linux 16.04): macOS 10.14.6
- OS architecture (e.g. amd64): amd64
- pyenv version: 1.2.15

Relevant DEBUG output:
```shell
> env PYENV_DEBUG=1 pyenv help realpath.dylib
[...]
+ [pyenv:118] case "$command" in
++ [pyenv:131] command -v pyenv-help
+ [pyenv:131] command_path=/usr/local/Cellar/pyenv/1.2.15/libexec/pyenv-help
+ [pyenv:132] '[' -z /usr/local/Cellar/pyenv/1.2.15/libexec/pyenv-help ']'
+ [pyenv:140] shift 1
+ [pyenv:141] '[' realpath.dylib = --help ']'
+ [pyenv:148] exec /usr/local/Cellar/pyenv/1.2.15/libexec/pyenv-help realpath.dylib
+ [pyenv-help:19] '[' realpath.dylib = --complete ']'
+ [pyenv-help:143] unset usage
+ [pyenv-help:144] '[' realpath.dylib = --usage ']'
+ [pyenv-help:149] '[' -z realpath.dylib ']'
+ [pyenv-help:149] '[' realpath.dylib == pyenv ']'
+ [pyenv-help:159] command=realpath.dylib
++ [pyenv-help:160] command_path realpath.dylib
++ [pyenv-help:25] local command=realpath.dylib
++ [pyenv-help:26] command -v pyenv-realpath.dylib
+ [pyenv-help:160] '[' -n /usr/local/Cellar/pyenv/1.2.15/libexec/pyenv-realpath.dylib ']'
+ [pyenv-help:161] '[' -n '' ']'
+ [pyenv-help:164] print_help realpath.dylib
+ [pyenv-help:114] local command=realpath.dylib
+ [pyenv-help:115] local summary usage help
++ [pyenv-help:116] documentation_for realpath.dylib
++ [pyenv-help:90] local filename
+++ [pyenv-help:91] command_path realpath.dylib
+++ [pyenv-help:25] local command=realpath.dylib
+++ [pyenv-help:26] command -v pyenv-realpath.dylib
++ [pyenv-help:91] filename=/usr/local/Cellar/pyenv/1.2.15/libexec/pyenv-realpath.dylib
++ [pyenv-help:92] '[' -n /usr/local/Cellar/pyenv/1.2.15/libexec/pyenv-realpath.dylib ']'
++ [pyenv-help:93] extract_initial_comment_block
++ [pyenv-help:30] sed -ne '
    /^#/ !{
      q
    }

    s/^#$/# /

    /^# / {
      s/^# //
      p
    }
  '
++ [pyenv-help:93] collect_documentation
+++ [pyenv-help:86] type -p gawk awk
+++ [pyenv-help:86] head -1
sed: RE error: illegal byte sequence
[...]
+ [pyenv-help:131] echo 'Sorry, this command isn'\''t documented yet.'
Sorry, this command isn't documented yet.
+ [pyenv-help:132] return 1
```

I was thinking of either submitting a patch to either `grep -v '^realpath'` from `pyenv-commands` or `pyenv-help` if this seems like a reasonable path forward.

**Comment by ericvw** [comment]
After digging into this further, it seems like the `bash` built-in extension should not be made available from `pyenv-commands`.  I'll submit a PR to address it there with an associated test.

**Comment by jonstorer** [comment]
is this resolved? I just installed pyenv on OSX and got this error with `pyenv --help`.

**Comment by marksherman** [comment]
> is this resolved? I just installed pyenv on OSX and got this error with `pyenv --help`.

@jonstorer there hasn't been a version release since this fix was merged. Not yet.

**Comment by gatspy** [comment]
pyenv version: 1.2.18
this version still has this problem under osx 10.14.6

**Comment by marksherman** [comment]
the bug appears to be gone on pyenv 1.2.18 on Mac OS 10.15.4. But negative proof isn't really  proof.

**Comment by lesterlo** [comment]
I still have this issue on pyenv 1.2.18 on macos 10.15.5.

**Comment by gwww** [comment]
I have this issue. pyenv 1.2.20; MacOS 10.15.5

**Comment by hw-1** [comment]
just replace sed to gsed in /usr/local/Cellar/pyenv/1.2.20/libexec/pyenv-help

**Comment by lesterlo** [comment]
@hw-1 

Adding `/usr/local/opt/gnu-sed/libexec/gnubin` to your PATH is also work fine.

```bash
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
```

**Comment by tuzi3040** [comment]
pyenv 1.2.21 MacOS 10.15.7
with `export LC_CTYPE=en_US.UTF-8` set in `~/.zshrc`
This error shows up after i upgrade pyenv from 1.2.20 to 1.2.21.

**Comment by zhaowb** [comment]
Same error, in environment:
pyenv 1.2.21
macOs Big Sur Version 11.0.1 (20B50)
pyenv is installed through `brew upgrade pyenv`

**Comment by tuzi3040** [comment]
pyenv 1.2.23
MacOS Big Sur 11.2.1
pyenv installed through `brew upgrade pyenv`

It seems okay now.
`pyenv help realpath.dylib` now shows `Sorry, this command isn't documented yet.`, and exit code 1 is returned.
`pyenv help` used to print `sed: RE error: illegal byte sequence` among normal help output, now it's gone.
