### ISSUE TITLE
Fresh Install of pyenv has error in help

### ISSUE THREAD

**Issue by ThePlasmaGuy** [pyenv/pyenv#1457]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ ] Make sure your problem is not derived from packaging - I did use homebrew to install, but it seems like it installed successfully, so I don't think it's an issue with homebrew

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): macOS Catalina 10.15.1
- [ ] OS architecture (e.g. amd64): x64
- [ ] pyenv version: 1.2.15
- [ ] Python version: N/A (Fresh install, no versions of python installed)
- [ ] C Compiler information (e.g. gcc 7.3): N/A
- [ ] Please attach verbose build log as gist - https://gist.github.com/ThePlasmaGuy/0273b8d65d3a79172d9e5e81734ad3be

On a fresh install of macOS Catalina with a fresh install of homebrew, I installed the latest version of pyenv.  Then, to make sure I was running commands correctly when I went to install my versions of Python, I ran `pyenv` to check the help message, only to be greeted with `sed: RE error: illegal byte sequence` between prefix and rehash in the help message.  So I tried uninstalling it and reinstalling it to make sure that it wasn't installed incorrectly.  And the issue persisted.  So hopefully it's nothing too major.

May be related to #1454, but since it's with a completely different portion of the help message, I submitted a new issue.

**Comment by joshfriend** [comment]
Yes, this appears to be the same issue as #1454
