### ISSUE TITLE
PyEnv breaks reset

### ISSUE THREAD

**Issue by TheRijn** [pyenv/pyenv#1459]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS Catalina and Ubuntu 19.10
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 1.2.15(-1)
- [x] Python version: miniconda3-latest
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 11.0.0
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

When miniconda3-latest is installed, but not activated as the current python version. `reset` breaks, the currently activated python version is 3.7.5

Shells used, Fish and bash.

```
$ reset
pyenv: reset: command not found

The `reset' command exists in these Python versions:
  miniconda3-latest
```

**Comment by joshfriend** [comment]
ugh conda is so annoying.

they include their own versions of commands like `clear` and `reset`. pyenv has [a blacklist](https://github.com/pyenv/pyenv/blob/49bf595266866958501d4567fd2e76cfe538a51a/pyenv.d/rehash/conda.d/default.list) of these commands to avoid generating shims for them, but now and again, conda adds a new command and the blacklist has to be updated.
