### ISSUE TITLE
pip shim incorrectly installs packages to multiple python versions at same time

### ISSUE THREAD

**Issue by caleb15** [pyenv/pyenv#1460]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [?] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [?] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): ubuntu 18
- [NA] OS architecture (e.g. amd64):
- [X] pyenv version: 1.2.13
- [ 3.6.4 / 3.6.8] Python version:
- [NA] C Compiler information (e.g. gcc 7.3): 
- [NA] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

**Replication Steps:**

1. install latest brew (2.1.16 at the time of writing this)
2. install python via brew, or a package that requires python. For example, `brew install cheat`
(not sure if above steps are needed, but it's what I did when I setup my environment)
3. install pyenv
4. install python 3.6.4 and python 3.6.8 via pyenv
5. alias pip to pip3 (not needed, it's just how I have my home env set up)
6. Switch to python 3.6.4
7. run `pip install pre-commit`
8. run `pre-commit -h` in python 3.6.4 - you should get back pre-commit help
9. Switch to python 3.6.8
10. run `pre-commit -h` in python 3.6.8

Expected result: 
```
pyenv: pre-commit: command not found

The `pre-commit' command exists in these Python versions:
  3.6.4
```

Actual result: pre-commit runs, despite me installing it **only** in 3.6.4 :grimacing: 

The workaround to this is to run `python -m pip install pre-commit` and then it will install in the right place.

Might be related to https://github.com/pyenv/pyenv/issues/1204

**Comment by kuanb** [comment]
Would love an update on this - as someone who works on a number of repos simultaneously all with different python versions, this gets me every time.

**Comment by native-api** [comment]
Looks like you somehow end up installing the package for the Homebrew Python rather than the currently selected one. Maybe the alias breaks the selection somehow, maybe you didn't perform Pyenv instlalation steps according to the README properly before using it.

Can't say anything without seeing a debug trace as required by the issue template anyway.
