### ISSUE TITLE
OSX - Install in custom Applications directory

### ISSUE THREAD

**Issue by vikas027** [pyenv/pyenv#1468]
By default `pyenv` installs in `/Applications` directory. I have a work laptop in which I can only install applications in `/Users/vikas027/Applications`.

Is there an option to install in `/Users/vikas027/Applications` rather than `/Applications` directory.

```bash
➜  ~ pyenv install -v 3.7.3
<redacted>
Last 10 log lines:
cp ./../Icons/PythonLauncher.icns  "Python Launcher.app/Contents/Resources"
cp ./../Icons/PythonSource.icns  "Python Launcher.app/Contents/Resources"
cp ./../Icons/PythonCompiled.icns  "Python Launcher.app/Contents/Resources"
cp ./factorySettings.plist  "Python Launcher.app/Contents/Resources"
cp -R ./English.lproj "Python Launcher.app/Contents/Resources"
test -d "/Applications/Python 3.7" || mkdir -p "/Applications/Python 3.7"
mkdir: /Applications/Python 3.7: Permission denied
make[2]: *** [install] Error 1
make[1]: *** [install_PythonLauncher] Error 2
make: *** [frameworkinstallapps] Error 2
➜  ~
```

**Comment by vikas027** [comment]
Anyone?

**Comment by DilumAluthge** [comment]
Bump. I would also really like this feature.

**Comment by pombredanne** [comment]
Are you using Homebrew https://github.com/pyenv/pyenv#homebrew-on-macos?

**Comment by vikas027** [comment]
> Are you using Homebrew https://github.com/pyenv/pyenv#homebrew-on-macos?

Yes, I am. Ah, it looks like `PYENV_ROOT` is something that is needed, right?

**Comment by native-api** [comment]
> Is there an option to install in `/Users/vikas027/Applications` rather than `/Applications` directory.

Working on https://github.com/pyenv/pyenv/pull/1935, I found out that it's only possible to set the application prefix to either `/Applications`, or `<install prefix>/Applications`.

So if you want it directly under `HOME`, you'll need to install Python outside of Pyenv.

Or you can try checking out the PR branch, installing normally and symlinking `/Applications/Python X.Y` to where you need it -- I don't know if that will work.
