### ISSUE TITLE
how to install from a local python source package like Python-3.8.0.tar.xz ?

### ISSUE THREAD

**Issue by scil** [pyenv/pyenv#1476]
I have a  Python-3.8.0.tar.xz downloaded on my local machine. how can I install python from it?

**Comment by cdfuller** [comment]
I found the solution here:
https://github.com/pyenv/pyenv/issues/754#issuecomment-262232181

Copy Python-3.8.0.tar.xz to the pyenv cache.

`cp Python-3.8.0.tar.xz $(pyenv root)/cache
