### ISSUE TITLE
readline extension was not compiled, installed pyenv by Linuxbrew on Ubuntu 16

### ISSUE THREAD

**Issue by mrchi** [pyenv/pyenv#1479]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): `Ubuntu Linux 16.04 LTS`
- [x] OS architecture (e.g. amd64): `amd64`
- [x] pyenv version:  `1.2.15`
- [x] Python version: `3.7.5`
- [x] C Compiler information (e.g. gcc 7.3): `5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) `
- [x] Please attach verbose build log as gist [here](https://gist.github.com/chiqj/c679f7d753a201af8757f8b56fde9da2)

Hi, I'm using Ubuntu 16.04 LTS, I installed pyenv by Linuxbrew. When I tried to install Python 3.7.5, I got this:

```
Downloading Python-3.7.5.tar.xz...
-> https://www.python.org/ftp/python/3.7.5/Python-3.7.5.tar.xz
Installing Python-3.7.5...
python-build: use readline from homebrew
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Installed Python-3.7.5 to /home/chi/.pyenv/versions/3.7.5
```
Python installed by pyenv DO lack readline. 

But both Linuxbrew and apt-tool already installed readline:
```
$ sudo apt list libreadline-dev
libreadline-dev/xenial,now 6.3-8ubuntu2 amd64 [installed]
$ brew info readline
readline: stable 8.0.1 (bottled)
Library for command-line editing
https://tiswww.case.edu/php/chet/readline/rltop.html
/home/linuxbrew/.linuxbrew/Cellar/readline/8.0.1 (50 files, 1.9MB) *
  Poured from bottle on 2019-12-01 at 01:20:43
From: https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/readline.rb
==> Dependencies
Required: ncurses ✔
==> Analytics
install: 19,272 (30 days), 48,452 (90 days), 118,711 (365 days)
install-on-request: 91 (30 days), 263 (90 days), 885 (365 days)
build-error: 0 (30 days)
```

So I'm confused if pyenv really uses readline from homebrew?

**Comment by thedrow** [comment]
A possible workaround is to only allow to compile with readline from homebrew on OS X.
Can we use that in the meantime until we find a solution?

**Comment by viniciusban** [comment]
Is there any way to overcome this?

The same problem in Ubuntu 18.04. The console python shell doesn't repeat last command with arrow up.

**Comment by sevens-ef** [comment]
I got the same/a similar issue on Ubuntu 18.04.  I installed `pyenv` manually, have `brew` installed and have `readline` installed via `brew` as well.  Also got the `readline-dev` Ubuntu package installed.

```
$  pyenv install 3.8.1
Downloading Python-3.8.1.tar.xz...
-> https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tar.xz
Installing Python-3.8.1...
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Installed Python-3.8.1 to /home/me/env/pyenv/versions/3.8.1
python-build: use readline from homebrew
```

Temp removing brew's `readline` fixes it:
```
$  brew uninstall --ignore-dependencies readline
$  pyenv install 3.8.1
Installing Python-3.8.1...
Installed Python-3.8.1 to /home/me/env/pyenv/versions/3.8.1
$  brew install readline
```

Disabling the `use_homebrew_readline` function (add `return 0` as first line) in `pyenv/plugins/python-build/bin/python-build` also fixes it.

**Comment by thedrow** [comment]
@sevens-ef I guess a good workaround to contribute is to skip `use_homebrew_readline` on Linux.
How would we do that?

**Comment by sevens-ef** [comment]
Was thinking that as well.  I did a quick read of the code earlier and it wasn't easily clear to me how to safely do this, so for now I opted for this quick workaround instead :)

`pyenv` may have some existing code (var/function) to check if you're on Linux that could be used?  I didn't look that far (I'm not really familiar with the codebase, only did a few scans/quick reads of some of its parts before).  Probably better to ask a `pyenv` developer/contributor ;)

Also it may have to get changed in `rbenv` instead, I saw this function existing there as well ( https://github.com/rbenv/ruby-build/blob/4dbdc0b6acf3789edd238a609ff1ab22d50b8498/bin/ruby-build#L1009 ).

**Comment by network-shark** [comment]
Any news on this ?

**Comment by mvanderlee** [comment]
This is a larger issue. pyenv should ignore linuxbrew entirely.
If it doesn't `import _curses` will fail, causing a lot of libraries to stop working.

I tried manually editing out the homebrew readline usage from my local python-build. But `_curses` was still broken. 
Then I re-exported my PATH without linuxbrew, reinstalled my python version, and everything worked like a charm.

```shell
# Save so we can revert
OLD_PATH="$PATH"
# Remove linuxbrew from the path
export PATH="$(echo $PATH | tr : '\n' | grep -v linuxbrew | paste -s -d:)"
# Install Python
pyenv install 3.8.2
# revert path
export PATH=$OLD_PATH
```

**Comment by thedrow** [comment]
Why should linuxbrew be a problem?

**Comment by mvanderlee** [comment]
@thedrow That's my conclusions, because removing linuxbrew from the path fixed the issue.
It might be that using linuxbrew's gcc is the issue, but I haven't dove into it further. 

Installation detail:
I didn't install pyenv via brew, but instead simply followed the basic git clone instructions.

**Comment by thedrow** [comment]
I agree it's a good workaround and maybe it should be included for now but we need to figure out the root cause of the issue.

**Comment by thedrow** [comment]
The workaround doesn't work if you installed pyenv using homebrew.

**Comment by tony-bony** [comment]
I installed pyenv-virtualenv using linuxbrew on Ubuntu 16.04.

Adding `return 0` as the first line in the `use_homebrew_readline` function in `/home/linuxbrew/.linuxbrew/Cellar/pyenv/1.2.16_1/plugins/python-build/bin/python-build` like @sevens-ef  suggested solved my problem.  

Now `pyenv install` command executes without any warning. 
Thanks

**Comment by mswezey23** [comment]
Ugh, this is still a thing in August on CentOS!?

Thanks everyone for going through the hard work and providing the work around! :)

**Comment by toguko** [comment]
I solved this problem on ubuntu 20.04 installing the lib **libreadline-dev**

**Comment by scottwn** [comment]
Hi, I'm stuck on this same issue.

I tried @mvanderlee's workaround, this broke pyenv https://github.com/pyenv/pyenv/issues/1479#issuecomment-610683526

I tried @tony-bony's workaround, it had no effect https://github.com/pyenv/pyenv/issues/1479#issuecomment-636400707

I then uninstalled pyenv entirely, confirmed all the [prerequisites](https://github.com/pyenv/pyenv/wiki/Common-build-problems) are installed, and reinstalled using the [auto installer](https://github.com/pyenv/pyenv-installer).

The issue persists:
```
scott@oc5862681154 ~> pyenv install 3.9.0
Downloading Python-3.9.0.tar.xz...
-> https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tar.xz
Installing Python-3.9.0...
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
Installed Python-3.9.0 to /home/scott/.pyenv/versions/3.9.0
```

As expected, many libraries are broken:
```
scott@oc5862681154 ~/macys-scripts (dedicated-esx)> pip install openpyxl
Collecting openpyxl
  Using cached openpyxl-3.0.5-py2.py3-none-any.whl (242 kB)
Collecting et-xmlfile
  Using cached et_xmlfile-1.0.1.tar.gz (8.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/scott/.pyenv/versions/3.9.0/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3bwvzpvb/et-xmlfile/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3bwvzpvb/et-xmlfile/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-d7os55vc
         cwd: /tmp/pip-install-3bwvzpvb/et-xmlfile/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/scott/.pyenv/versions/3.9.0/lib/python3.9/site-packages/setuptools/__init__.py", line 23, in <module>
        from setuptools.dist import Distribution
      File "/home/scott/.pyenv/versions/3.9.0/lib/python3.9/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/home/scott/.pyenv/versions/3.9.0/lib/python3.9/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/home/scott/.pyenv/versions/3.9.0/lib/python3.9/ctypes/__init__.py", line 8, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I'm on RHEL 7.8. Any other suggestions on how to fix this?

**Comment by SdotVdot** [comment]
MacOS Big Sur - Readline

I Installed pyenv in MacOS Catalina and MacOS Big Sur and the result was:
Catalina - No problem ...
Big Sur - Installing Python-3.8.5...
python-build: use zlib from xcode sdk
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?

After that I tried to use Macports to install readline but the problem remained.

**Comment by jyhuang91** [comment]
I am using a Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-88-generic x86_64) server.
But I don't have sudo privilege.

When I tried to install `pyenv install 3.9.0`, I still got `WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?` even though I have `readline` installed locally at `$HOME/.local`

I have set `CPATH, C_INCLUDE_PATH, CPLUS_INCLUDE_PATH, LIBRARY_PATH, LD_LIBRARY_PATH`, but it still failed.

Any help?

**Comment by jkedra** [comment]
Weird stuff with Ubuntu 16.04 indeed. Nothing from above worked for me but at least gave me some tips what could be wrong with that. There was no `libreadline.so` . Indeed, installing just `libreadline-dev` did not work. That was a metapackage which subsequently shall install `libreadline6-dev`. So I went and examined the files it delivers `(dpkg -L libreadline6-dev`) the declared `/usr/lib/x86_64-linux-gnu/libreadline.so` was not in place. Nothing at all. So I uninstalled `libreadline-dev` (`apt remove libreadline-dev`) and its dependent `libreadline6-dev`. Then installed specifically `libreadline6-dev`. And it finally works. Here is the full procedure:

```
apt remove libreadline-dev libreadline6-dev
apt install aptitude
apt install libreadline6-dev
pyenv uninstall 3.9.1
pyenv install 3.9.1

```
This time no issues with readline. 
Good luck with that!

**Comment by fharper** [comment]
@mvanderlee workaround worked for me also.

**Comment by thedrow** [comment]
Why is this closed? This has to be fixed.

**Comment by Grey2k** [comment]
Please reopen, it is still broken by default

**Comment by jwhite007** [comment]
@mrchi 
Linuxbrew on RHEL 8.4
```
$ brew install gcc@5 pyenv bzip2 libffi libxml2 libxmlsec1 openssl readline sqlite xz zlib
$ env CFLAGS="-I$(brew --prefix)/include" CPPFLAGS="-I$(brew --prefix)/include"  LDFLAGS="-L$(brew --prefix)/lib" PYTHON_CONFIGURE_OPTS="CC=gcc-5" pyenv install 3.7.5
Downloading Python-3.7.5.tar.xz...
-> https://www.python.org/ftp/python/3.7.5/Python-3.7.5.tar.xz
Installing Python-3.7.5...
python-build: use readline from homebrew
Installed Python-3.7.5 to /home/linuxbrew/.linuxbrew/opt/pyenv/versions/3.7.5
```

**Comment by jwhite007** [comment]
@mrchi 

Update:
I had installed gcc@5 because I thought the build with the system version, /usr/bin/gcc, was a problem due to 3.7.5 needing an older build because /usr/bin/gcc was not building pyexpat properly and the pyenv build would fail.
```
$ /usr/bin/gcc --version
gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
```
Apparently something else is the problem with the system build tools as the latest gcc (gcc@11) from Linuxbrew works as well.
```
$ brew install gcc

$ gcc-11 --version
gcc-11 (Homebrew GCC 11.2.0) 11.2.0

$ env CFLAGS="-I$(brew --prefix)/include" CPPFLAGS="-I$(brew --prefix)/include"  LDFLAGS="-L$(brew --prefix)/lib" PYTHON_CONFIGURE_OPTS="CC=gcc-11" pyenv install 3.7.5
Downloading Python-3.7.5.tar.xz...
-> https://www.python.org/ftp/python/3.7.5/Python-3.7.5.tar.xz
Installing Python-3.7.5...
python-build: use readline from homebrew
Installed Python-3.7.5 to /home/linuxbrew/.linuxbrew/opt/pyenv/versions/3.7.5
```

**Comment by tedmiston** [comment]
Per @thedrow + @Grey2k - Confirmed this is still broken / still an issue by replicating the commands from @sevens-ef in https://github.com/pyenv/pyenv/issues/1479#issuecomment-587044749 (temporarily uninstalling readline via linuxbrew [now just `brew` technically]).

IMO this issue should be reopened since the problem persists.

I have other packages in brew which depend on the GNU readline package being installed, so removing it just for pyenv isn't a viable long-term solution vs pyenv ignoring the version installed via brew and using the one installed via apt instead.

**Comment by tedmiston** [comment]
The errors seen below re `libxmlsec1` when re-installing readline via brew could potentially be related to the error seen via pyenv when the brew version of GNU readline is installed.

```shell
tedmiston@penguin:~$ brew install readline
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
reshape
==> Updated Casks
Updated 2 casks.

==> Downloading https://ghcr.io/v2/homebrew/core/readline/manifests/8.1.2
Already downloaded: /home/tedmiston/.cache/Homebrew/downloads/e30c06196d2408e5d0630f9ebd7ab315f29656f1e3f5e0de4e3d08222a1c3c3a--readline-8.1.2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/readline/blobs/sha256:2b46aff4f720e0f15601aecb2efd4ae7c2a3454b2fad91b196728ed4ee4f12c3
Already downloaded: /home/tedmiston/.cache/Homebrew/downloads/23bb84489d3ea1133dd83273664299b210ca961ea112a114f1efeb714f159dab--readline--8.1.2.x86_64_linux.bottle.tar.gz
==> Pouring readline--8.1.2.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/readline/8.1.2: 48 files, 1.9MB
==> Running `brew cleanup readline`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> No outdated dependents to upgrade!
==> Checking for dependents of upgraded formulae...
Disable this behaviour by setting HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Reinstalling 2 dependents with broken linkage from source:
gnutls, libxmlsec1
==> Downloading https://ghcr.io/v2/homebrew/core/automake/manifests/1.16.5
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/automake/blobs/sha256:59808c20f7dc565f106b432941b43c52f3d7f46a8d562ab27a4aabd424783158
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:59808c20f7dc565f106b432941b43c52f3d7f46a8d562ab27a4aabd424783158?se=2022-01-25T23%3A55%3A00Z&sig=%2FugHW92Ks2pbz
######################################################################## 100.0%
==> Downloading https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/gnutls-3.6.16.tar.xz
######################################################################## 100.0%
==> Reinstalling gnutls 
==> Installing dependencies for gnutls: automake
==> Installing gnutls dependency: automake
==> Pouring automake--1.16.5.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/automake/1.16.5: 131 files, 3.5MB
==> Installing gnutls
==> ./configure --disable-static --prefix=/home/linuxbrew/.linuxbrew/Cellar/gnutls/3.6.16_1 --sysconfdir=/home/linuxbrew/.linuxbrew/etc --with-default-trust-store-file=/home/linuxbrew/.linuxbrew/et
==> make LDFLAGS= install
==> Caveats
If you are going to use the Guile bindings you will need to add the following
to your .bashrc or equivalent in order for Guile to find the TLS certificates
database:
  export GUILE_TLS_CERTIFICATE_DIRECTORY=/home/linuxbrew/.linuxbrew/etc/gnutls/
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/gnutls/3.6.16_1: 1,254 files, 10.7MB, built in 4 minutes 23 seconds
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/03cf8088210822aa2c1ab544ed58ea04c897d9c4/libtool/configure-big_sur.diff
Already downloaded: /home/tedmiston/.cache/Homebrew/downloads/195208ba31cadc265ea97bb8aad4e78caab1200daf4d855e6c839b5f987f92db--configure-big_sur.diff
==> Downloading https://www.aleksey.com/xmlsec/download/xmlsec1-1.2.33.tar.gz
######################################################################## 100.0%
==> Reinstalling libxmlsec1 
==> Patching
==> Applying configure-big_sur.diff
patching file configure
Hunk #1 succeeded at 8289 (offset -444 lines).
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/libxmlsec1/1.2.33 --disable-crypto-dl --disable-apps-crypto-dl --with-openssl=/home/linuxbrew/.linuxbrew/opt/openssl@1.1
==> make install
Last 15 lines from /home/tedmiston/.cache/Homebrew/Logs/libxmlsec1/02.make:
app.c:22:10: fatal error: nspr.h: No such file or directory
   22 | #include <nspr.h>
      |          ^~~~~~~~
compilation terminated.
bignum.c:23:10: fatal error: secitem.h: No such file or directory
   23 | #include <secitem.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:626: libxmlsec1_nss_la-app.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:633: libxmlsec1_nss_la-bignum.lo] Error 1
make[2]: Leaving directory '/tmp/libxmlsec1-20220125-27078-vy7bho/xmlsec1-1.2.33/src/nss'
make[1]: *** [Makefile:688: install-recursive] Error 1
make[1]: Leaving directory '/tmp/libxmlsec1-20220125-27078-vy7bho/xmlsec1-1.2.33/src'
make: *** [Makefile:742: install-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting


==> Caveats
==> gnutls
If you are going to use the Guile bindings you will need to add the following
to your .bashrc or equivalent in order for Guile to find the TLS certificates
database:
  export GUILE_TLS_CERTIFICATE_DIRECTORY=/home/linuxbrew/.linuxbrew/etc/gnutls/
tedmiston@penguin:~$ 
```

**Comment by thedrow** [comment]
I'm really glad we could get this reopened. @tedmiston Would you like to contribute a workaround that refers pyenv to the system's readline library for now?

**Comment by native-api** [comment]
If Linuxbrew libraries can't be used out of the box -- unlike MacOS Homebrew's libraries, -- we should probably not search Homebrew for libraries in Linux.

**Comment by caal-15** [comment]
Agreed, having the workaround is fine, but you should at least have an official option to tell pyenv not to use the Homebrew/linuxbrew libraries.

**Comment by native-api** [comment]
[The Homebrew team has told me how to link against Homebrew-provided libraries](https://github.com/Homebrew/discussions/discussions/2945):

> Homebrew GCC is configured to add the correct RPATHs. We may add this to `.pc` files we ship too so that it works with `pkg-config` and a non-Homebrew GCC too.
> 
> If you want to avoid the need for a Homebrew GCC, adding
> 
> ```
> LDFLAGS="-Wl,-rpath,$(brew --prefix)/lib"
> ```
> 
> should help.

---

Still, should we make use on Homebrew outside of MacOS?
* In Linux, the primary way of supplying dependencies is the system's package manager
* By using Homebrew, we open ourselves up to its rolling-release nature which gradually breaks older Python versions which can't work with never versions of libraries.
