### ISSUE TITLE
What's the difference between anaconda python installed with pyenv and the one by anaconda install package.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyenv/pyenv#1484]
Hi,

I installed the anaconda python with:

https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh

In this case, what's the differences between the anaconda python installed by pipenv and the one installed by Anaconda3-2019.10-Linux-x86_64.sh?

Furthermore, while installing the anaconda with Anaconda3-2019.10-Linux-x86_64.sh, how to let pyenv manage the corresponding anaconda python version?

Regards

**Comment by joshfriend** [comment]
closing this one since you have the same question, but with a problem description in #1489
