### ISSUE TITLE
Additional SDK headers actually break pyenv install for OSX 10.14.6 (Mojave) instead of fixing it.

### ISSUE THREAD

**Issue by francis-whitesell-earnest** [pyenv/pyenv#1487]
Additional SDK headers actually break pyenv install for OSX 10.14.6 (Mojave) instead of fixing it.

https://github.com/pyenv/pyenv/wiki/common-build-problems
The instructions here state that the following command should be run on OSX 10.14+:

`sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`

However running OSX 10.14.16 (Mojave), installing these additional SDK headers breaks my build. Reinstalling the command line tools without installing those headers allows a successful install. I believe this instruction should be amended to be limited to 10.14.0-10.14.5.

**Comment by joshfriend** [comment]
Looks like we forgot to update the wiki after merging #1353. I removed that section to avoid further confusion.

**Comment by Hathoney** [comment]
Many thanks @francis-whitesell-earnest for your suggestion. After many hours of trawling the issues and about to give up on pyenv (which I really didn't want to do) I came across #1487 .

Installation of Python 3.9.0 done!

**Comment by francis-whitesell-earnest** [comment]
Glad to help! Seemed like an unusual edge case at the time, but I overlooked the fact that of course someone else must be experiencing a similar issue at some point.
