### ISSUE TITLE
How can I recompile a python version without having to uninstall and reinstall it and all its modules

### ISSUE THREAD

**Issue by ishandutta2007** [pyenv/pyenv#1488]
easy option is
```
pip freeze > req.txt
pyenv uninstall 3.6.0
pyenv install 3.6.0
pyenv local 3.6.0
pip install -r req.txt

```
But I have lots of heavy modules installed , can I just recompile my python 3.6.0 without having to uninstall those ?

**Comment by goiosunsw** [comment]
Hello, I had a similar problem with module tkinter. After installing the devel dependencies on ubuntu (`apt install tk-dev`) I just had to run

`pyenv install 3.7.5`

and it picked up the `tk` requirement. All the dependent environments were apparently untouched.

**Comment by joshfriend** [comment]
I don't know of a way to reliably recreate the list of dependencies for a python environment besides using a tool like Poetry and a requirements lockfile.

**Comment by echuber2** [comment]
What happens if one simply reinstalls the same version in-place without uninstalling it first? I suppose OP was thinking about getting security updates from upstream and so on. Is it best to reinstall everything including the pip packages?
