### ISSUE TITLE
``pyenv install anaconda3-4.3.0 '' gives the following: WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?

### ISSUE THREAD

**Issue by hongyi-zhao** [pyenv/pyenv#1489]
Hi,

I've installed all of the dependent libraries for building python and try to install anaconda3-4.3.0 with the following command:

`$ pyenv install anaconda3-4.3.0`

But I meet the following problem:

`WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?`

Then I try to use a self compiled version of gnu readline as follows and still meet the following warning:

```
$ LDFLAGS="-L$HOME/readline/lib/ -Wl,-rpath,$HOME/readline/lib" CFLAGS="-I$HOME/readline/include -I$HOME/readline/include/readline" pyenv install anaconda3-4.3.0
pyenv: /home/werner/.pyenv/versions/anaconda3-4.3.0 already exists
continue with installation? (y/N) y
Installing Anaconda3-4.3.0-Linux-x86_64...
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Installed Anaconda3-4.3.0-Linux-x86_64 to /home/werner/.pyenv/versions/anaconda3-4.3.0
```

But, if I install the  Anaconda3-4.3.0-Linux-x86_64 without using pyenv as follows, the problem will disappear:

`$ bash Anaconda3-4.3.0-Linux-x86_64.sh`

Any hints for this issue?

Regards

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/wiki/Common-build-problems

Can't say anything else without a full debug trace as required by the issue template.
