### ISSUE TITLE
``pyenv init -'' and ``pyenv virtualenv-init -''  should be splitted into two parts.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyenv/pyenv#1490]
Hi,

I issued the following discussion of c.u.s, 

```
From: Helmut Waitzmann <nn.throttle@xoxy.net>
Newsgroups: comp.unix.shell
Subject: Re: use eval in .profile
```

As for the following commands:
```

  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
```

It seems that neither putting them in ~/.profile  nor
 ~/.basrc is appropriate.   The reason are as follows ( I excerpted  Helmut Waitzmann <nn.throttle@xoxy.net> 's reply here ):

```
It does make sense and it doesn't make sense to run those "eval" 
commands from the file “~/.profile”:

The commands 


“eval "$(pyenv init -)"”

and

“eval "$(pyenv virtualenv-init -)"”

both prepend something to the PATH environment variable.  
Therefore it's not very useful to let them run from “~/.bashrc”, 
because then they will be run from each interactive (subshell) 
bash.  For example, imagine, you have an interactive shell running 
in a terminal or terminal emulator, then start an editor out of 
it.  In the editor, you start an interactive shell.  Then this 
shell will have the PATH environment variable extended twice by 
the pyenv‐initializing commands.

=> The “eval "$(pyenv …)"” commands should better be run from 
“~/.profile” rather than from „~/.bashrc“.

But now you'll get into another problem: 


These initializing commands not only prepend something to the PATH 
environment variable, but also define some functions.  But 
functions (by default) are not exported to the environment.

=> If you put these commands for example into “~/.xinitrc”, the 
environment will be initialized and then be inherited by any shell 
running in a terminal window.  That's fine.  But the defined 
functions will not be inherited by any shell running in a terminal 
window.

=> The problem is, that the task done by the “eval "$(pyenv …)"” 
commands should be split: into the environmental part, which 
should be run from “~/.profile” or “~/.xinitrc”, and the function 
definition part, which should be run from “~/.bashrc”.

As far as I can see you cannot do much to solve that problem 
(apart from filing a bug report to the developers of the python 
environment).

```

Could you please touch up these scripts?

**Comment by joshfriend** [comment]
> Could you please touch up these scripts?

I don't know what you are asking pyenv maintainers to do here or where these quotes of conversations are coming from.

**Comment by hongyi-zhao** [comment]
Run the following two commands under terminal, and you will see what I want to say:

$ pyenv init -
$ pyenv virtualenv-init -

**Comment by muuvmuuv** [comment]
Just had similar thoughts @joshfriend and I will quote what he things that should be done here:

> => The problem is, that the task done by the “eval "$(pyenv …)"” 
commands should be split: into the environmental part, which 
should be run from “~/.profile” or “~/.xinitrc”, and the function 
definition part, which should be run from “~/.bashrc”.

The point here is to remove the PATH extending from the init script to prevent it beeing twice executed. If I run `code something.py` and open the VS Code terminal I would have it called twice. Same goes for virtualenv.
