### ISSUE TITLE
pyenv-implicit: found multiple pipenv in pyenv. Use version 3.5.9.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyenv/pyenv#1491]
When I try to start my terminal, I meet the following info:

pyenv-implicit: found multiple pipenv in pyenv. Use version 3.5.9.

How to deal with it?

**Comment by joshfriend** [comment]
pyenv-implicit is not an official pyenv plugin and you will have to ask for help with your issue on the tracker for that plugin: https://github.com/concordusapps/pyenv-implict

**Comment by hongyi-zhao** [comment]
Thanks, I noted that the last commit was done in 2016.  So basically I can say, it is dead.  Discard it simply.

Thanks again.
