### ISSUE TITLE
pyenv can not change the python version

### ISSUE THREAD

**Issue by qiulang** [pyenv/pyenv#1492]
### Description
- [ ] Platform information : macOS 10.15.2
- [ ] pyenv version: 1.2.9
- [ ] Python version: 3.7.2

```
re35 ➤ pyenv versions                                                                                                                                    
  system
* 3.5.3 (set by /Users/qiulang/Dev/learning_python/re35/.python-version)
re35 ➤ python3 --version                                                                                                                                 
Python 3.7.2
re35 ➤ python --version                                                                                                                                  
Python 2.7.16
re35 ➤ pyenv --version                                                                                                                                   
pyenv 1.2.9
```

When I installed 3.5.3 I got this warning but I guess that is not the reason pyenv can't change my python version.

```
test ➤ pyenv install  3.5.3                                                                                                                   
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.5.3.tar.xz...
-> https://www.python.org/ftp/python/3.5.3/Python-3.5.3.tar.xz
Installing Python-3.5.3...
python-build: use readline from homebrew
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
Installed Python-3.5.3 to /Users/qiulang/.pyenv/versions/3.5.3
```

**Comment by joshfriend** [comment]
Please make sure you've followed the installation steps (https://github.com/pyenv/pyenv#installation)

You are probably missing the "add pyenv init to your shell" step

Also see the common build problems wiki (https://github.com/pyenv/pyenv/wiki/Common-build-problems) for your other issue.

These resources are listed in the issue template, please make sure you've read carefully before opening an issue

**Comment by qiulang** [comment]
No I added pyenv init to my shell and that was why I opened this issue.

**Comment by qiulang** [comment]
OK I figure why. 
After upgrade macOS to the latest Catalina, zsh is the default shell! But I still modified my .bash_profile
