### ISSUE TITLE
Add CPython 3.8.1, 3.7.6, 3.6.10

### ISSUE THREAD

**Issue by bersbersbers** [pyenv/pyenv#1496]
I believe the title says it all :)

**Comment by bersbersbers** [comment]
See #1497 for 3.8.1

**Comment by darkn3rd** [comment]
Not just CPython, but regular Python too.

**Comment by sdyalor** [comment]
Run ```pyenv update``` I dont know how to install cpython but after that I got 3.8.1

**Comment by joshfriend** [comment]
@darkn3rd ["CPython" is "regular python"](https://github.com/python/cpython)

@sdyalor no new versions have been tagged and released on homebrew yet, if you installed via the "Basic github checkout" method, you can just `cd $PYENV_ROOT && git pull` to update.

The versions mentioned in OP have been added, so I'm going to close this now.

**Comment by chenrui333** [comment]
@joshfriend it looks like this does not quite work for me as brew user.
`cd $PYENV_ROOT && git pull`

When should I expect to see a new release for the brew formula? Thanks!
