### ISSUE TITLE
Failed to Install Python 3.7.0 on macOS Catalina

### ISSUE THREAD

**Issue by johannhuang** [pyenv/pyenv#1503]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS Catalina 10.15.2 (19C57)
- [ ] OS architecture (e.g. amd64): 
- [x] pyenv version: pyenv 1.2.15
- [ ] Python version: 3.7.0
- [ ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

```
BUILD FAILED (OS X 10.15.2 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/rc/5qdy5tt92y70m0r5kv22gx8h0000gn/T/python-build.20191227105353.40361
Results logged to /var/folders/rc/5qdy5tt92y70m0r5kv22gx8h0000gn/T/python-build.20191227105353.40361.log

Last 10 log lines:
renaming build/scripts-3.7/idle3 to build/scripts-3.7/idle3.7
renaming build/scripts-3.7/2to3 to build/scripts-3.7/2to3-3.7
renaming build/scripts-3.7/pyvenv to build/scripts-3.7/pyvenv-3.7
if test "no-framework" = "no-framework" ; then \
		/usr/bin/install -c python.exe /Users/johann/.pyenv/versions/3.7.0/bin/python3.7m; \
	else \
		/usr/bin/install -c -s Mac/pythonw /Users/johann/.pyenv/versions/3.7.0/bin/python3.7m; \
	fi
install: /Users/johann/.pyenv/versions/3.7.0/bin/python3.7m: Too many levels of symbolic links
make: *** [altbininstall] Error 71
+ [pyenv-install:246] STATUS=1
+ [pyenv-install:249] '[' 1 == 2 ']'
+ [pyenv-install:277] '[' 1 == 0 ']'
+ [pyenv-install:280] cleanup
+ [pyenv-install:239] '[' -z 1 ']'
```

**Comment by mcstrassell09** [comment]
I'm having good success with installing python3.x with pyenv using the flags I adapted from "Common Build problems" page.  The "-I$(xcrun --show-sdk-path)/usr/include" flag didn't spit out the full path so I just type the path directly.

```shell
CFLAGS="-I$(brew --prefix openssl@1.1)/include -I$(brew --prefix readline)/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include" CPPFLAGS="-I$(brew --prefix zlib)/include -I$(brew --prefix openssl@1.1)/include -I/usr/local/opt/sqlite/include" LDFLAGS="-L$(brew --prefix openssl@1.1)/lib -L$(brew --prefix readline)/lib -L/usr/local/opt/sqlite/lib" pyenv install
```

Still no success installing any version of python@2. I suspect has something to do with recent deprecation of python@2.

**Comment by cyphus** [comment]
Thanks @mcstrassell09 I was having similar build issues and trying to force python-build to pick up my homebrew installed ssl libs instead of the one from xcode SDK. Your set of environment variables got it to work for me. It still says that it's using ssl from xcode SDK but at least the build completes successfully.

**Comment by mcstrassell09** [comment]
Nice. I've actually abandonded pyenv for the moment. seeing that I'm being cornered by what version of python I can use having multiple versions only clutters my hard-drive and ~/.zshrc file. Homebrew is no better. As a package manager it offers very few options and it steal places for symlinks like a hog. I installed python3.7 with homebrew (the only version you can get) and it install symlinkes into /usr/local under names "python", "python3" and "python@3." Greedy.

**Comment by native-api** [comment]
Need a debug trace as required by the issue template to diagnose.
