### ISSUE TITLE
Pyinstaller can't find libpython3.7* under pyenv

### ISSUE THREAD

**Issue by tbhaxor** [pyenv/pyenv#1504]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Manjaro 5.4
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version:  1.2.15
- [x] Python version: 3.7.5
- [x] C Compiler information (e.g. gcc 7.3):  9.2
- [x] Please attach verbose build log as gist: https://gist.github.com/tbhaxor/a0183b38743aa7040b2c2970eb121d98

### More Information

I had tried the recommended solution from pyinstaller's document i.e setting the LD_LIBRARY_PATH
```
→ echo $LD_LIBRARY_PATH 
/home/terabyte/.pyenv/versions/3.7.5/lib
```

**Comment by Legorooj** [comment]
@tbhaxor as bjones1 has done, and I'm forced to agree, this is the right place to do this. I did manage to reproduce the issue, and it's pyenv, not PyInstaller.

**Comment by ErikBjare** [comment]
I got this working with: `env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.7.8`

Removed my old virtualenv, created a new one, and reinstalled everything.

The library files were in `/home/erb/.pyenv/versions/3.7.8/lib`, as expected. No modifying $LD_LIBRARY_PATH needed.

**Comment by Legorooj** [comment]
Please use the above solution from @ErikAGriffin if you encounter this problem.

**Comment by ysangkok** [comment]
I also ran into this. I wonder if shared libraries are purposefully disabled? Seems like a weird default to not build them. I noticed there is a static library there. Is the argument that if people build their own Python they may as well statically link everything and maximize performance? Since you'd be rebuilding all modules even for a minor upgrade, so ABI compatibility doesn't matter.

**Comment by eric-burel** [comment]
I hit this issue with `pipenv` which weirdly enough doesn't seem to pick the installed version (3.7.0) but 3.7.10+, which doesn't even seem to be installable via pyenv.

I am not sure what version it picks.
