### ISSUE TITLE
Installing additional SDK headers does not work on MacOS 10.15 Catalina

### ISSUE THREAD

**Issue by stinaq** [pyenv/pyenv#1505]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04):
- [ ] OS architecture (e.g. amd64): I don't know how to answer this question, but I have intel core i5, 64 bit
- [x] pyenv version: 1.2.15
- [x] Python version: 2.7.15
- [x] C Compiler information (e.g. gcc 7.3):  Apple clang version 11.0.0 (clang-1100.0.33.8)
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

When trying to install the additional SDK headers in MacOS Catalina 10.15 i get the following error:
`installer: Error - the package path specified was invalid: '/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg'.`

Which makes sense, since this is not 10.14. I found [this issue](https://github.com/pyenv/pyenv/issues/1425) and tried to follow the instructions there.
 Running `xcrun --sdk macosx --show-sdk-path` gives `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk` so then I tried to run the installer with that path:

`sudo installer -pkg /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -target /`

But that gives the following error: `installer: Error - the package path specified was invalid: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk'.`

The instructions in the guide to setting up the environment does not work on MacOS 10.15, and I can't figure out what to do instead. Am I misunderstanding the instructions that is closing the issue #1425 ? Or are the instructions still wrong?

**Comment by satchelfrench** [comment]
I am having the same issue here on Catalina – however only with Python 2.X.X. 

running the following resolved the issue for 3.X.X

`rm -rf /Library/Developer/CommandLineTools`
`xcode-select --install`

I've tried all the suggestions for MacOS, but continuously get the openssl missing error. Tried the CMAKE headers, and openssl is installed.

**Comment by mcstrassell09** [comment]
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib? 

Yes. The problem is listed in the pyenve "common build problems wiki" but the solution listed DOES NOT WORK. 

% CFLAGS="-I$(brew --prefix openssl)/include" \
LDFLAGS="-L$(brew --prefix openssl)/lib" \
peen install 2.7.7

results in the same error! PLEASE DEAR GOD

**Comment by joshfriend** [comment]
> PLEASE DEAR GOD ... tell me to consult the Wiki page one more time...

It's there because people _really don't check_. Take a deep breath and calm down.

I've removed the sdk header install suggestion from the wiki as it was a temporary crutch anyways and I believe based on this issue and other things I have read that it no longer works on Catalina because the headers package was deprecated and removed
