### ISSUE TITLE
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?

### ISSUE THREAD

**Issue by Tylersuard** [pyenv/pyenv#1508]
### Prerequisite
* [x] My problem IS listed in the common build problems, but only a solution for MacOS is given, and not a solution for Ubuntu 16.

- [x] Platform information (Ubuntu Linux 16.04):
- [ ] pyenv version:
- [ ] Python version:
- [ ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

**Comment by joshfriend** [comment]
Installing required packages on **ubuntu**, including `readline` is _literally the first thing listed_ in the "Common build problems" wiki.

**Comment by Tylersuard** [comment]
AND I followed those directions, to the letter, and it still does not work.

**Comment by DownTownScarf7** [comment]
In case you still want to fix this issue and have not yet fixed it, I had the same problem on Debian 10, having followed the same instructions

```bash
sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
xz-utils tk-dev libffi-dev liblzma-dev python-openssl git
```

This did not fix it for me and I still got the error. However using aptitude to install `libreadline-dev`...

```bash
sudo aptitude install libreadline-dev
pyenv uninstall 3.8.1
pyenv install 3.8.1
```

Did get rid of the issue, still not really sure what caused `libreadline-dev` to not be installed properly with `apt-get`.

**Comment by Tylersuard** [comment]
Thank you :)

**Comment by tony-bony** [comment]
Having the same issue on Ubuntu 16.04:
```
~$ pyenv install 3.8.1
Downloading Python-3.8.1.tar.xz...
-> https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tar.xz
Installing Python-3.8.1...
python-build: use readline from homebrew
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Installed Python-3.8.1 to /home/andre/.pyenv/versions/3.8.1
```

Installing the `libreadline-dev` and reinstalling Python 3.8.1 doesn't help:

```
~$ sudo aptitude install libreadline-dev
libreadline-dev is already installed at the requested version (6.3-8ubuntu2)
libreadline-dev is already installed at the requested version (6.3-8ubuntu2)
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
```

**Comment by mvanderlee** [comment]
@tony-bony Try my solution here: https://github.com/pyenv/pyenv/issues/1479#issuecomment-610683526

**Comment by tony-bony** [comment]
@mvanderlee Thanks, I will try it.

**Comment by yanpanlau** [comment]
The solution by @tony-bony works for me! Thanks

**Comment by seanlindo** [comment]
_The instructions literally could have been written better_ @joshfriend

**Comment by seanlindo** [comment]
@mvanderlee you're a wizard, thank you!

**Comment by jyoo** [comment]
@tony-bony Thank you! Also, for someone who encountered this issue on AWS ec2 AND see these lines
```
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
```

try the following as well and reinstall your Python version:
```
sudo yum install readline-devel
sudo yum install sqlite-devel
```

**Comment by SdotVdot** [comment]
MacOS Big Sur - Readline

I Installed pyenv in MacOS Catalina and MacOS Big Sur and the result was:
Catalina - No problem ...
Big Sur - Installing Python-3.8.5...
python-build: use zlib from xcode sdk
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?


After that I tried to use Macports to install readline but the problem remained.

**Comment by github-yxb** [comment]
MacOS Big Sur same issue
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Installing Python-3.8.6...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Installed Python-3.8.6 to /Users/xxx/.pyenv/versions/3.8.6

**Comment by binary-signal** [comment]
macOS Big Sur same issue

before running the command I had to export some env variables

evan in /  took 2m 27s
❯ export LDFLAGS="-L/usr/local/opt/zlib/lib"
evan in / 
❯ export CPPFLAGS="-I/usr/local/opt/zlib/include"
evan in / 
❯ export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"

❯ pyenv install 3.9.0
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.9.0.tar.xz...
-> https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tar.xz
Installing Python-3.9.0...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
Installed Python-3.9.0 to /Users/evan/.pyenv/versions/3.9.0

**Comment by hyusetiawan** [comment]
having the same problem, I installed other versions before in previous mac versions so it sounds like the issue is Big Sur

**Comment by zhangyegem** [comment]
$ brew info readline bzip2
then you'll get the showing export path in your .zshrc or bashpofile

**Comment by maztak** [comment]
If you are using macOS m1 chip, install xcode13-bata and setting Preference>Locations>Command Line Tools to xcode13.0, and `brew install readline` and add below sentence in `.bash_profile` or `.bashrc` is perhaps solution.

```bash
  export LDFLAGS="-L/opt/homebrew/opt/readline/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/readline/include"

  export PKG_CONFIG_PATH="/opt/homebrew/opt/readline/lib/pkgconfig"
```

**Comment by liudonghua123** [comment]
> If you are on RHEL based distro(e.g. Oracle Linux), install those first
> 
> ```
> dnf install bzip2-devel readline-devel libffi-devel readline-devel sqlite-delve
> ```

```
# Update yum first
yum update
yum upgrade
# Install development tools - great for programmers
yum groupinstall -y development
yum install -y zlib-devel openssl-devel sqlite-devel bzip2-devel readline-devel tk-devel
```

**Comment by Gems** [comment]
In my case on macOS Sonoma the following two instructions helped:
```
export CPPFLAGS="$(pkg-config --cflags openssl) $(pkg-config --cflags readline)"
export LDFLAGS="$(pkg-config --libs openssl) $(pkg-config --libs readline)"
```

Check the libs that the build script is missing and make sure you get their corresponding `cflags` and `libs`. They are defined space-separated in the corresponding environment variables.

**Comment by ForsakenRei** [comment]
> > If you are on RHEL based distro(e.g. Oracle Linux), install those first
> > ```
> > dnf install bzip2-devel readline-devel libffi-devel readline-devel sqlite-delve
> > ```
> 
> ```
> # Update yum first
> yum update
> yum upgrade
> # Install development tools - great for programmers
> yum groupinstall -y development
> yum install -y zlib-devel openssl-devel sqlite-devel bzip2-devel readline-devel tk-devel
> ```

you are right, forgot I already had the development group.

**Comment by MSK61** [comment]
I have the same exact problem, trying to install python 3.9.22 on ubuntu 16.04. I've installed `libreadline-dev` from ubuntu repos with apt and I'm not using homebrew on linux, just plain pyenv and system libraries. None of the solutions suggested above worked for me.

**Comment by luchomtv** [comment]
i had a similar issue on Fedora 42. After installing pyenv and all dependencies:
```
sudo dnf group install "development-tools" -y
sudo dnf install zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel xz xz-devel libffi-devel findutils -y
```

i stll got the missing readline warning. After browsing the pyenv build docs and chatting with LLMs i managed to build python 3.13.3 using this flags:

```
READLINE_CFLAGS="-I/usr/include/readline" \
READLINE_LDFLAGS="-L/usr/lib64 -lreadline -lncursesw" \
pyenv install 3
```

i'm not sure what the issue with readline is. Pyenv always downloads it and installs it in the specific version folder inside .pyenv but does not seem to be able to use it. So these flags point to the system's readline installation. Again, not 100% sure why, but it worked for me.

**Comment by andrewnryan** [comment]
I am having the same issue on a fresh Ubuntu 24.04 installation with any python version 3.12.0 or higher (below python 3.12.0 seems to work as intended).  Similar to what @luchomtv mentioned, doing a pyenv install does a local installation of readline, but it seems as though it can't be found during the python installation step.  

the issue being highlighted on 3.12.4
```
$ pyenv install 3.12.4
Downloading readline-8.2.tar.gz...
-> https://ftpmirror.gnu.org/readline/readline-8.2.tar.gz
Installing readline-8.2...
Installed readline-8.2 to /home/<redacted_username>/.pyenv/versions/3.12.4
Downloading Python-3.12.4.tar.xz...
-> https://www.python.org/ftp/python/3.12.4/Python-3.12.4.tar.xz
Installing Python-3.12.4...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'readline'
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Installed Python-3.12.4 to /home/<redacted_username>/.pyenv/versions/3.12.4
```
Working as intended on 3.11.12
```
$ pyenv install 3.11.12
Downloading readline-8.2.tar.gz...
-> https://ftpmirror.gnu.org/readline/readline-8.2.tar.gz
Installing readline-8.2...
Installed readline-8.2 to /home/<redacted_username>/.pyenv/versions/3.11.12
Downloading Python-3.11.12.tar.xz...
-> https://www.python.org/ftp/python/3.11.12/Python-3.11.12.tar.xz
Installing Python-3.11.12...
Installed Python-3.11.12 to /home/<redacted_username>/.pyenv/versions/3.11.12
```

**Comment by native-api** [comment]
Without providing the diagnostic information as per the [issue template](https://github.com/pyenv/pyenv/blob/master/.github/ISSUE_TEMPLATE.md), you are wasting your time.
Just an excerpt of the output is not sufficient to diagnose a problem.

The titular problem could be caused by any number of reasons. Look through the build log to try to find the first error message and rather search for it in the issues.

**Comment by MSK61** [comment]
@luchomtv Thanks for the hint. I've tried your approach(adapting paths to fit ubuntu 16.04) but it didn't work and I still got the same error. The point is that building the readline extension always succeeds but importing it(during testing) still fails, since the special readline library built by pyenv can't be located at runtime. I think something needs to be added to the runtime settings of the produced extension(like the `-rpath` option to point to the path of the readline library) or - to a lesser extent - `LD_LIBRARY_PATH`(although that latter approach can't be a permanent solution).
