### ISSUE TITLE
Python 3.8.1 not available from homebrew pyenv 1.2.15

### ISSUE THREAD

**Issue by markliederbach** [pyenv/pyenv#1510]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
Python version 3.8.1 is not yet available from the homebrew version of pyenv (1.2.15).

Short of reinstalling from source, a new brew version is needed.

Related issues:
https://github.com/pyenv/pyenv/issues/1496#issuecomment-569074597

**Comment by m-aciek** [comment]
It looks like it is on master, but waiting for a release. https://github.com/pyenv/pyenv/pull/1497

**Comment by chenrui333** [comment]
Thanks opening this issue, I wonder when we can expect a new release for pyenv?

**Comment by puremourning** [comment]
you can do this `brew unlink pyenv && brew install --HEAD pyenv`

**Comment by joshfriend** [comment]
https://github.com/Homebrew/homebrew-core/pull/48577

**Comment by markliederbach** [comment]
Thank you!
