### ISSUE TITLE
pyenv install fails on .python-version with multiple versions

### ISSUE THREAD

**Issue by ergoithz** [pyenv/pyenv#1512]
### Description
```pyenv install``` does not understand multi-version **.python-version** files as generated by ```pyenv local 3.5.9 3.6.9 3.7.6 3.8.1```, like:

```
3.5.9
3.6.9
3.7.6
3.8.1
```
Output:

```
$ pyenv install
python-build: definition not found: 3.5.9
3.6.9
3.7.6
3.8.1

The following versions contain `3.5.9
3.6.9
3.7.6
3.8.1' in the name:
  3.5.9
  3.6.9
  3.7.6
  3.8.1

See all available versions with `pyenv install --list'.

If the version you need is missing, try upgrading pyenv:

  cd /home/orpheus/.pyenv/plugins/python-build/../.. && git pull && cd -
```
- Arch Linux (as in 2020.01.05).
- Amd64
- pyenv 1.2.15
- Python 3.8.1
- gcc (GCC) 9.2.0
- Verbose output: https://gist.github.com/ergoithz/da11c71e4c78bd9b4e46fd9c7ea4f55c

For those wondering, setting multiple python versions makes pythonX.Y shims to work on tools like **tox** (which is becoming somewhat standard due setuptools dropping its test command).

**Comment by samuelhwilliams** [comment]
I have the same problem and the same use-case. I can probably work around this by doing something like `pyenv local | xargs -L1 pyenv install`, but it would be nice to have native support for this.

**Comment by prokher** [comment]
JFYI: Looks like a duplicate of #919.

**Comment by ergoithz** [comment]
@prokher indeed
