### ISSUE TITLE
Update Mac build environment instructions for Catalina (macOS 10.15+)

### ISSUE THREAD

**Issue by AdamLombard** [pyenv/pyenv#1515]
**The [Mac build environment instructions in the wiki](https://github.com/pyenv/pyenv/wiki#suggested-build-environment) currently read:**

...

When running Mojave or higher (10.14+) you will also [need to install the additional SDK headers:](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035624)

```
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
```

**With changes made in macOS Catalina, they should now read something more like:**

When running Mojave (10.14.x) you will also [need to install the additional SDK headers:](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035624)

```
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
```

Installing additional SDK headers is not necessary [when running Catalina (10.15.x)](https://forums.developer.apple.com/thread/122762).

**Comment by native-api** [comment]
Done in https://github.com/pyenv/pyenv/wiki
