### ISSUE TITLE
Add to wiki steps for building Python 3.7 and up on Ubuntu 14.04

### ISSUE THREAD

**Issue by danielguardicore** [pyenv/pyenv#1516]
As documented in the [wiki](https://github.com/pyenv/pyenv/wiki/Common-build-problems#error-the-python-ssl-extension-was-not-compiled-missing-the-openssl-lib), compiling on Ubuntu 14.04 leads to a failure because of too old openSSL version.
As the wiki points out, the problem can be solved by compiling your own version of openSSL.
I'd like to add to the wiki a conclusive answer on doing so.

You need two steps, one is building your own version of OpenSSL and the second is instructing pyenvto use it.

To install OpenSSL, run the following commands.
```
mkdir openssl 
cd openssl 
wget https://www.openssl.org/source/openssl-1.0.2u.tar.gz 
tar -xzvf openssl-1.0.2u.tar.gz 
cd openssl-1.0.2u 
./config --prefix=$HOME/openssl --openssldir=$HOME/openssl shared zlib 
make 
make
make install
```
This installs the latest version on OpenSSL 1.0.2 (no more patches will be released) to your home directory. Now to install Python 3.7 using pyenv.

After you configure pyenv, run the following command

`PATH="$HOME/openssl:$PATH"  CPPFLAGS="-I$HOME/openssl/include" CFLAGS="-I$HOME/openssl/include/" LDFLAGS="-L$HOME/openssl/lib -Wl,-rpath,$HOME/openssl/lib" LD_LIBRARY_PATH=$HOME/openssl/lib:$LD_LIBRARY_PATH LD_RUN_PATH="$HOME/openssl/lib" CONFIGURE_OPTS="--with-openssl=$HOME/openssl" PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.7.5`

You may add -O2 if you want faster run times.

# Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu Linux 14.04
- [ ] OS architecture (e.g. amd64): Irrelevant
- [ ] pyenv version: 1.2.16
- [ ] Python version: 3.7.5
- [ ] C Compiler information (e.g. gcc 7.3): Irrelevant

**Comment by KptnKMan** [comment]
The source of this issue has wasted a significant amount of time for me.

This really does need to get fixed ASAP.

**Comment by clbarnes** [comment]
Ubuntu 14.04 has been EOL for nearly a year.

**Comment by danielguardicore** [comment]
@clbarnes Correct, I want to build on the oldest possible machine using the oldest sane glibc.
The reason is I'm building python and pyinstaller and using it to deploy a one file python program to users, rather than requiring them to install a specific version of python.

Some of these users run modern Ubuntu, some run old RHEL, etc.

**Comment by clbarnes** [comment]
If you're including unsupported OSs, why stop at 14.04? It's no more supported than 12.04, or indeed 4.10. If your users are on unsupported OSs, they can't expect support, by definition.

**Comment by danielguardicore** [comment]
1 - Because it's already documented in the Wiki and I can easily improve the documentation.
2 - Same solution also works on 12.04. Prior versions have not been requested by my users, nor is it as easy, because we start running into kernel version issues.

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/wiki/Common-build-problems#2-your-openssl-version-is-incompatible-with-the-python-version-youre-trying-to-install
