### ISSUE TITLE
Question: does pyenv depend on a baseline Python3 interpreter?

### ISSUE THREAD

**Issue by Integralist** [pyenv/pyenv#1517]
Hello,

I'm just curious to know, when installing pyenv, if pyenv requires there to already be either a Python2 or Python3 interpreter available on the OS?

I checked the [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pyenv.rb) and it didn't look to depend on any version of Python (which would kinda make sense considering it's a tool for _installing_ Python versions).

I only ask because the state of my OS at the moment is that it already had Python3 installed via `brew install python3` and so I didn't know if it was strictly necessary to have that installed (would be great if I could remove that brew and _just_ rely on pyenv).

Thanks!

**Comment by joshfriend** [comment]
pyenv does not use python itself, so no pre-existing python install is required to use pyenv

**Comment by Integralist** [comment]
Apologies, I've only just noticed that this is covered in the README ([here](https://github.com/pyenv/pyenv#in-contrast-with-pythonbrew-and-pythonz-pyenv-does-not)) 🤦‍♂ 

So thank you for clarifying here as well ❤️
