### ISSUE TITLE
checking Tcl version... pyenv: tclsh8.5: command not found

### ISSUE THREAD

**Issue by hongyi-zhao** [pyenv/pyenv#1522]
Hi,

I use pyenv to manage python versions, and I've installed some
python's versions as follows:

$ pyenv versions
  system
  2.7.17
  3.5.9
* 3.6.9 (set by /home/werner/.pyenv/version)
  3.7.5
  3.8.0
  anaconda3-2019.10
  anaconda3-4.3.0
  anaconda3-5.3.0
  anaconda3-5.3.1

In this case, I try to compile vim from the git version, but failed at
the configure stage:

```
$ ./configure     --enable-fail-if-missing     --enable-autoservername
    --enable-cscope     --enable-fontset     --enable-multibyte
--enable-luainterp     --enable-perlinterp
--enable-pythoninterp=yes     --enable-python3interp=yes
--enable-rubyinterp     --enable-tclinterp     --enable-gui=gtk3
--enable-terminal     --enable-xim     --with-x     --with-luajit
--with-lua-prefix=/usr/local     --with-features=huge
[...]
checking for tclsh8.5... /home/werner/.pyenv/shims/tclsh8.5
checking Tcl version... pyenv: tclsh8.5: command not found

The `tclsh8.5' command exists in these Python versions:
  anaconda3-4.3.0

too old; need Tcl version 8.0 or later
configure: error: could not configure Tcl
```

Any hints for solving this issue?

**Comment by joshfriend** [comment]
I think this is the same thing you've already asked in #1507 and #1506. Please stop repeatedly posting the same issue. If you aren't getting a response, it's not because you are being ignored. Either nobody currently knows the answer or they don't have time to help find a solution.
