### ISSUE TITLE
/usr/local/Cellar/pyenv/1.2.16/pyenv.d/exec/pip-rehash/pip: line 20: 54195 Abort trap: 6           "$PYENV_COMMAND_PATH" "$@"

### ISSUE THREAD

**Issue by dhcn** [pyenv/pyenv#1524]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04):
mac
- [ ] OS architecture (e.g. amd64):
- [ ] pyenv version:
1.2.16
- [ ] Python version:
3.7.6
- [ ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`
/usr/local/Cellar/pyenv/1.2.16/pyenv.d/exec/pip-rehash/pip: line 20: 54195 Abort trap: 6           "$PYENV_COMMAND_PATH" "$@"

**Comment by kwiromeo** [comment]
Not sure if this would help here, but I've been dealing with a similar issue of a message responding with abort trap 6.

**Some background to how my issue was occurring**:

- I needed to install Python 3.6.5, so I used pyenv to do that. The project is a Flask application
- During the start stage, the application stops and appears to have loaded (there's output that Flask's debugger starts, but the abort error occurs.
- I traced it to the import of a library using a debugger, but it didn't fix the issue. 
- I tried different versions of Python through pyenv and that didn't fix the issue.

**The insight and what fixed the issue:**
- my work colleague installed the project and it worked fine. He was using an macOS Python build, not the pyenv version.
- I found this [issue](https://github.com/ludwigschwardt/python-gnureadline/issues/50) on Github that mentions something about a possible issue with gnureadline
- I also noticed that in the installation of Python through pyenv, there's a call to brew to install gnureadline
- I removed all pyenv installations of python, and used the native install to create the venv, and there was no issue.

----
Not sure how useful this is, but this abort trap 6 might be a gnureadline issue. Not sure how to verify this though.

**Comment by g-golden** [comment]
Try this https://github.com/pypa/pip/issues/7254#issuecomment-546119909

**Comment by scottrbaxter** [comment]
I just came across this for the 2nd time, as i previously fixed this by using this symlink (in place of copying the files and linking the copied versions, as suggested above):

`sudo ln -s /usr/local/Cellar/openssl/1.0.2t/lib/libcrypto.1.0.0.dylib /usr/local/lib/libcrypto.dylib`

Just did a brew update, and now have `openssl@1.1` installed... so my symlink broke.

This new symlink resolved my issue (but this is clearly not portable... at best this is a band-aid):

`sudo ln -s /usr/local/Cellar/openssl@1.1/1.1.1g/lib/libcrypto.1.1.dylib /usr/local/lib/libcrypto.dylib`

I checked the fix posted by @g-golden above, but copying (and/or linking) the current `libssl.<version>` to `libcrypto.<version>` is clearly a workaround for this problem. I did also try the [export suggestion](https://github.com/pypa/pip/issues/7254#issuecomment-562096707) on the post above, using the current openssl version: `export DYLD_LIBRARY_PATH=/usr/local/Cellar/openssl@1.1/1.1.1g/lib/`, however this did not work at all.. even if this variable could work, directly specifying the current version will also be a workaround.

Is there a long-term solution for macOS/pyenv users?

**Comment by scottrbaxter** [comment]
On further inspection, there was a [reply](https://github.com/pypa/pip/issues/7254#issuecomment-554801464) from @g-golden's URL that did in fact solve this issue long-term.

This is what I did to fix this issue long-term.

```
sudo ln -s /usr/local/Cellar/openssl@1.1/1.1.1g/lib/libcrypto.1.1.dylib /usr/local/lib/libcrypto.dylib # required to make pip work
pip uninstall cryptography # removed cryptography==2.7
sudo rm /usr/local/lib/libcrypto.dylib # the symlink that i had manually created
pip install --upgrade cryptography # install the latest version, which is currently 2.9.2
```

**Comment by native-api** [comment]
> sudo ln -s /usr/local/Cellar/openssl@1.1/1.1.1g/lib/libcrypto.1.1.dylib /usr/local/lib/libcrypto.dylib # required to make pip work

This is likely to break things since OpenSSL in Homebrew is deliberately keg-only so as not to conflict with Apple's LibreSSL.

Most likely, this has been caused by Homebrew migrating from `openssl` to `openssl@1.1`.
If this case, better rebuild affected versions against the new OpenSSL: https://github.com/pyenv/pyenv/wiki/Common-build-problems#error-the-python-ssl-extension-was-not-compiled-missing-the-openssl-lib
