### ISSUE TITLE
Fresh pyenv, fails to install any version of python on macOS Catalina 10.15.2

### ISSUE THREAD

**Issue by theRogueDev** [pyenv/pyenv#1526]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information: macOS Catalina 10.15.2
- [X] OS architecture: Darwin
- [X] pyenv version: 1.2.16
- [X] Python version: 3.8.0
- [X] C Compiler information: gcc 4.2.1
- [X] Please attach verbose build log as gist [Log file](https://gist.github.com/theRogueDev/abd048197237bf51ccc00615a8f8297b)

This is a fresh install of pyenv through homebrew. Presumably all versions fail to install, though I've only tried 5 (3.8.0 3.6.4 3.4.3 2.7.0 2.7.5).

**Comment by joshfriend** [comment]
try running `xcode-select --install` as suggested [here](https://github.com/pyenv/pyenv/wiki#suggested-build-environment)

**Comment by jgsinn** [comment]
I've been experiencing the same issue for months.  Just now circling back around.  xcode command line tools are installed and still seem to have the issue.

**Comment by theRogueDev** [comment]
@joshfriend 
I already have the xcode command line tools, running `xcode-select --install` gives me
> xcode-select: error: command line tools are already installed, use "Software Update" to install updates
@jgsinn Did your issue come from updating to Catalina 10.15.2 as well? I suspect that is the issue as everything was fine a couple days ago.

**Comment by theRogueDev** [comment]
Okay, so I fixed it. I ran `pyenv rehash`, and that seemed to fix it. I don't know why this worked, I had a fresh install of pyenv.
