### ISSUE TITLE
Missing (8) commands documentation

### ISSUE THREAD

**Issue by aviyadeveloper** [pyenv/pyenv#1527]
These are all of the commands listed when running `$ pyenv commands`. Those that are check are also found in the `COMMANDS.md` documentation. The rest are missing.

- [x] commands
- [ ] completions
- [ ] exec
- [x] global
- [ ] help
- [ ] hooks
- [ ] init
- [x] install
- [ ] local
- [ ] prefix
- [x] rehash
- [ ] root
- [x] shell
- [ ] shims
- [x] uninstall
- [x] version
- [ ] --version
- [ ] version-file
- [ ] version-file-read
- [ ] version-file-write
- [ ] version-name
- [ ] version-origin
- [x] versions
- [x] whence
- [x] which

Ignoring the various `versions` and `help` command this leaves 8 missing commands:

1. completions
2. exec
3. hooks
4. init
5. local
6. prefix
7. root
8. shims

**Comment by sjvrijn** [comment]
`local` is actually listed: https://github.com/pyenv/pyenv/blob/master/COMMANDS.md#pyenv-local

**Comment by sandipanpanda** [comment]
Hi, I am interested to help to add these commands documentation.

**Comment by native-api** [comment]
Sure, please submit a PR.
