### ISSUE TITLE
Still having issues with "pyenv init" with fish shell using omf

### ISSUE THREAD

**Issue by DWinterfell** [pyenv/pyenv#1530]
Guys, I have read **plenty** on how to get `pyenv init` to work, but alias, I think I've tried nearly everything.  I've even gone here:
https://github.com/pyenv/pyenv/issues/32 

So, in a way, I guess I'm looking for more step-by-step ways to fix this - I think I've tried nearly every suggestion and I still get the same problem:
```
pyenv init                                                         00:00:00
# Load pyenv automatically by appending
# the following to ~/.config/fish/config.fish:

status --is-interactive; and source (pyenv init -|psub)
```
I've also tried `omf install pyenv` and that still does not fix the problem.  Below, you should have all the info you need, if I am missing something, please let me know.  I have no idea why this isn't working.

Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): macOS 10.12.6
- [ ] OS architecture (e.g. amd64): intel i5
- [x] pyenv version: 1.2.16
- [x] Python version: 2.8.1
- [ ] C Compiler information (e.g. gcc 7.3):  4.2.1, Apple LLVM version 9.0.0 (clang-900.0.39.2)
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

**Comment by joshfriend** [comment]
I'm sorry, I don't see what your issue is, there's no shell output that seems to indicate a problem and you have not described at all what your "issues with pyenv init" are.

When running `pyenv init` printed the following:

```sh
# Load pyenv automatically by appending
# the following to ~/.config/fish/config.fish:

status --is-interactive; and source (pyenv init -|psub)
```

did you actually do what it said?

**Comment by xsteadfastx** [comment]
i have the problem that `status --is-interactive; and source (pyenv init -|psub)` kills fish in tmux-xpanes. there is a error about too many open pipes

    <W> fish: Fehler beim Einrichten der Pipe aufgetreten
    pipe: Zu viele offene Dateien

i kicked the complete other config of fish just to be sure its this part.

**Comment by DWinterfell** [comment]
@joshfriend I've tried editing `~/.config/fish/config.fish` multiple times, and taking several different kinds of suggestions to make the change, and it still no effect.  I would still type in `pyenv init` and get the same error output.

**Comment by joshfriend** [comment]
@DWinterfell to reiterate, _you have not posted any "error output"_. I'm going to close this but will reopen if you post some info about what problem you are having.

**Comment by DWinterfell** [comment]
@xsteadfastx what are you doing to get a different error output.  As I've said, I've tried to enter in `status --is-interactive; and source (pyenv init -|psub)` several times, but I keep getting the same error output: 

```
pyenv init                                                         00:00:00
# Load pyenv automatically by appending
# the following to ~/.config/fish/config.fish:

status --is-interactive; and source (pyenv init -|psub)
```

**Comment by DWinterfell** [comment]
@joshfriend please put this back to open, I posted the error output in the first part of the ticket.  You've closed it prematurely.

**Comment by joshfriend** [comment]
what part of that message is an error?

**Comment by DWinterfell** [comment]
that after I've edited the `~/.config/fish/config.fish` I **still** get: 
```
pyenv init                                                         00:00:00
# Load pyenv automatically by appending
# the following to ~/.config/fish/config.fish:

status --is-interactive; and source (pyenv init -|psub)
```

**Comment by DWinterfell** [comment]
@joshfriend so please keep this open until there is a resolution.

**Comment by DWinterfell** [comment]
@joshfriend It's kinda like getting "bad command or file name" but I've edited that file multiple times.  So clearly that's an error output that's not giving me enough info, and not solving the problem.  Please reopen.

**Comment by DWinterfell** [comment]
> what part of that message is an error?

Josh, can you please help me?  I've edited that file (with the suggested script command), and I'm not getting anywhere.  If this is just marked "closed" without anyone addressing the issue, I'll probably have to create a new ticket. 
:-)
