### ISSUE TITLE
Automatically pick highest minor version when not specified during install

### ISSUE THREAD

**Issue by flip111** [pyenv/pyenv#1532]
Could `pyenv install 3.8` detect the highest minor version (at the moment `3.8.1`) and install this one? Possibly with a confirmation before installation.

**Comment by joshfriend** [comment]
Please search the open issues list before creating duplicate issues

**Comment by flip111** [comment]
i don't know what to search for.

For example when i search https://github.com/pyenv/pyenv/issues?utf8=%E2%9C%93&q=is%3Aissue+highest+version+
