### ISSUE TITLE
initialization status message for pyenv in fish shell is required.

### ISSUE THREAD

**Issue by jdsjdk** [pyenv/pyenv#1534]
Hello guys, 

So after **really** thinking about what the issue is, I've finally concluded as to what needs to be done.  Here is the issue:

```
⋊> ~cat ~/.config/fish/config.fish                                     00:00:00
set -g fish_user_paths "/usr/local/opt/ncurses/bin" $fish_user_paths
thefuck --alias | source
set -x PYENV_ROOT $HOME/.pyenv
set -x PATH $PYENV_ROOT/bin $PATH
status --is-interactive; and . (pyenv init -|psub)
status --is-interactive; and . (pyenv virtualenv-init -|psub)
set -gx PKG_CONFIG_PATH "/usr/local/opt/openssl@1.1/lib/pkgconfig"
set -gx CPPFLAGS "-I/usr/local/opt/openssl@1.1/include"
set -gx LDFLAGS "-L/usr/local/opt/openssl@1.1/lib"

⋊> ~ pyenv shell                                                      00:00:00
3.8.1

⋊> ~ pyenv init                                                         00:00:00
# Load pyenv automatically by appending
# the following to ~/.config/fish/config.fish:

status --is-interactive; and source (pyenv init -|psub)
```
So there is no status message to tell if you if `pyenv init` is working or not.  If you have `status --is-interactive; and source (pyenv init -|psub)` placed in ` ~/.config/fish/config.fish` or not, it still says the same thing.  You need a status message for when it is properly initialized..... something like "pyenv is already running" or something like that.  Because there is no way to know if it's working otherwise.

Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
*Platform information (e.g. Ubuntu Linux 16.04): macOS 10.12.6
 OS architecture (e.g. amd64): intel i5
 pyenv version: 1.2.16
 Python version: 3.8.1
 C Compiler information (e.g. gcc 7.3): 4.2.1, Apple LLVM version 9.0.0 (clang-900.0.39.2)

**Comment by native-api** [comment]
First, since https://github.com/pyenv/pyenv/pull/1898 repeated eval "$(`pyenv init -`") invocations no longer have an adverse effect.
Second, if you need it, you can check if `pyenv` has benn initialized by checking if `pyenv` is a shell function (I don't know how to do that in `fish`; in `bash`, it's `[[ $(type -t pyenv) == "function" ]]`).

So there's no real need for any kind of messages.
