### ISSUE TITLE
[Wiki] OpenSUSE missing libbz2-devel package

### ISSUE THREAD

**Issue by raabf** [pyenv/pyenv#1535]
The wiki page https://github.com/pyenv/pyenv/wiki has a list of required packages, so that python can compile.
Currently, the OpenSUSE point is missing packages, which are required to build the `bz2` and `lzma` python modules, namely `libbz2-devel` and `bzip2` as well as `xz` and `xz-devel`.
So the “OpenSUSE” point should be replaced by:

    zypper install gcc automake bzip2 libbz2-devel xz xz-devel openssl-devel ncurses-devel readline-devel zlib-devel tk-devel libffi-devel sqlite3-devel

**Comment by joshfriend** [comment]
updated!
