### ISSUE TITLE
U18.04.3 LTS system python3.6 not seen by pyenv versions

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [pyenv/pyenv#1536]
Running `pyenv versions` does not show the fact that system `python 3.6.9` exists and can be invoked using `python3.6` regardless of the `pyenv version` setting.
I'm not a python power user, so I can't judge how significant this issue is, but it still looks like an omission to me.

Cheers

**Comment by joshfriend** [comment]
Please provide the info requested by the issue template.
