### ISSUE TITLE
Python 3.8.2

### ISSUE THREAD

**Issue by bersbersbers** [pyenv/pyenv#1541]
Python 3.8.2. has just been tagged, https://github.com/python/cpython/releases/tag/v3.8.2

Looking forward to support from pyenv - thanks!

**Comment by joshfriend** [comment]
thanks for the heads up. looks like it has been tagged but not actually released

https://www.python.org/ftp/python/3.8.2/

No prebuilt binaries are available yet and i don't see any activity about a final release on `python-dev`: https://mail.python.org/archives/list/python-dev@python.org/

**Comment by bersbersbers** [comment]
Agreed, so ... should this issue really be closed, or maybe remain open until 3.8.2 has actually been released and supported?

**Comment by bersbersbers** [comment]
> i don't see any activity about a final release on `python-dev`: https://mail.python.org/archives/list/python-dev@python.org/

Not true any more: "Python 3.8.2 and 3.9.0a4 are now available"
https://mail.python.org/archives/list/python-dev@python.org/thread/YLMHMKLQB23XBMQGSG6HOTK6URA2FB5L/

**Comment by bersbersbers** [comment]
> https://www.python.org/ftp/python/3.8.2/
> 
> No prebuilt binaries are available yet

Also not true any more. While some of them are not showing for me on 
https://www.python.org/ftp/python/3.8.2/
for example, this file does exist:
https://www.python.org/ftp/python/3.8.2/python-3.8.2-amd64.exe

**Comment by joshfriend** [comment]
I added 3.8.2 in a0a1ae89ab652d8b4c0cfa1b80e7efd2c6cb56a7

**Comment by pascal-de-ladurantaye** [comment]
Hi @joshfriend , thanks for adding 3.8.2! Can we expect a new release of pyenv soon on homebrew?

**Comment by thomaspsk** [comment]
Hey @joshfriend!

Great to hear you've added 3.8.2 support! I'm also wondering when a new homebrew version might make its way to end-users. Would be great to be able to run the same version of python on local dev environments as our cloud infrastructure without jumping through hoops.

Cheers and happy Friday!

**Comment by joshfriend** [comment]
Back from vacation tomorrow, will try to do it then 🚀
