### ISSUE TITLE
Python 3.7.7

### ISSUE THREAD

**Issue by bersbersbers** [pyenv/pyenv#1552]
Python 3.7.7 has been released.

By the way, would there be a way to automate discovery of new Python releases, at least minor ones? I suspect that installing 3.7.7 is not too different from installing 3.7.6, except for the source URL and the hashes.

**Comment by JesterOrNot** [comment]
Any updates on this?

**Comment by bersbersbers** [comment]
> Any updates on this?

You mean, like, since 5 hours ago?

**Comment by joshfriend** [comment]
added in #1553

@JesterOrNot I'm just one of a few people who works on this project for ~fun~ free, I already have a full-time job. When interacting with open source projects, please assume that if there is no update posted, _there is no update_. You aren't paying anyone for same business day response time, so you should not expect that level of interaction. Also, pinging "any updates?" on github threads just annoys everyone else who may be subscribed to the issue.
