### ISSUE TITLE
Generate the python-build scripts based on the hashes for the installer supplied the official site.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyenv/pyenv#1557]
Say, for anaconda/miniconda based installers, the hashes can be found here: 

https://docs.anaconda.com/anaconda/install/hashes/all/
https://docs.conda.io/en/latest/miniconda_hashes.html

So, it should be possible to automatically generate the corresponding scripts here: plugins/python-build/share/python-build

Regards

**Comment by native-api** [comment]
I believe https://github.com/pyenv/pyenv/pull/1361 does this?
