### ISSUE TITLE
About the verify_py* function used in python-build scripts.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyenv/pyenv#1560]
Hi,

I noted that pyenv's python-build plugin defined many functions named as verify_py* which are used to verify the installer's checksum.  Where the * is python's version numbers.

But I don't think this is a good idea.  Due to you want to check the checksums of the installer, why not define the functions based on the checksum algorithms used to calculate the checksum, say, verify_md5, verify_sha256, and so on.

This way, the functions will not treat the version numbers which are always changing time to time.

Regards

**Comment by joshfriend** [comment]
`verify_py*` has nothing to do with checksums

**Comment by hongyi-zhao** [comment]
@joshfriend Then what's job done by them?  I've inspected the source and cannot figure out it.
