### ISSUE TITLE
pyenv install 3.7.0 fails.

### ISSUE THREAD

**Issue by Jeklah** [pyenv/pyenv#1562]
[python-build.20200318130512.18924.log](https://github.com/pyenv/pyenv/files/4349164/python-build.20200318130512.18924.log)
Windows 10

When running pyenv install 3.7.0, the build fails with this error log.

**Comment by joshfriend** [comment]
Please check the README and common build problems wiki before creating a new issue, as stated in the issue template.

It is clearly stated in the README that pyenv does not work on windows outside the WSL: https://github.com/pyenv/pyenv#installation
