### ISSUE TITLE
Change the ``pyenv versions'' display format for symlink of the env name.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyenv/pyenv#1563]
Hi,

Currently, the pyenv versions command will display as follows:

```
werner@ubuntu-01:~/Desktop$ pyenv versions | grep hpc
  3.8.1/envs/hpc
  hpc
```

Here, we have a env named as 3.8.1/envs/hpc and symlinked it as hpc.  So, I think the following display format maybe more intuitive:
  
    hpc --> 3.8.1/envs/hpc 
Regards

**Comment by native-api** [comment]
How did you "symlink it"?

**Comment by hongyi-zhao** [comment]
This the default behavior of `pyenv` when virtrualenvs are created, as shown below:
```
$ ls .pyenv/versions/ -l | grep ^l
lrwxrwxrwx 1 werner werner   45 May 25  2020 aiida -> /home/werner/.pyenv/versions/3.8.3/envs/aiida
lrwxrwxrwx 1 werner werner   47 Jul 23  2020 datasci -> /home/werner/.pyenv/versions/3.8.3/envs/datasci
lrwxrwxrwx 1 werner werner   46 Feb 10 15:51 firedm -> /home/werner/.pyenv/versions/3.9.1/envs/firedm
lrwxrwxrwx 1 werner werner   54 May 25  2020 socks5-haproxy -> /home/werner/.pyenv/versions/3.8.3/envs/socks5-haproxy

```

**Comment by native-api** [comment]
Pyenv doesn't create `envs/*`, Conda does, or maybe Pyenv-virtualenv.

Could you give some sample reproduction steps?

If Pyenv-Virtualenv creates those, perhaps this belongs in that plugin's codebase rather than Pyenv proper.

**Comment by hongyi-zhao** [comment]
```
$ pyenv shell 3.9.1
$ pyenv virtualenv --system-site-packages datasci
```
