### ISSUE TITLE
No stackless module in stackless-3.7.4

### ISSUE THREAD

**Issue by pjz** [pyenv/pyenv#1564]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 18.04
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: pyenv 1.2.17-1-g89786b90
- [x] Python version: stackless-3.7.4
- [x] C Compiler information (e.g. gcc 7.3): gcc 7.5.0
- [x] Please attach verbose build log as gist  : https://gist.github.com/2267704b255c43db2b7c385b9c650459
  * is the output of: `env PYENV_DEBUG=1 pyenv install -v stackless-3.7.4 >/tmp/debuglog-pyenv.log 2>&1`

Simple test:
```
$ pyenv local stackless-3.7.4 
$ python
Python 3.7.4 (default, Mar 20 2020, 15:52:40) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stackless
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'stackless'
>>> 
```

**Comment by native-api** [comment]
WFM with `stackless-3.7.5` and the latest head in Ubuntu 18.04.
I see "`WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?`" in your log so maybe you're missing some build dependencies.
