### ISSUE TITLE
'set by' info not showing for `pyenv versions --skip-aliases` if PYENV_VERSION is a virtualenv

### ISSUE THREAD

**Issue by nkpro2000sr** [pyenv/pyenv#1569]
If PYENV_VERSION is not a virtualenv then `pyenv versions --skip-aliases` works fine.  
But if PYENV_VERSION is a virtualenv then `pyenv versions --skip-aliases` not showing 'set by' info, since `python versions` shows 'set by' info next to aliases.
##### Sample
```
nkpro@SR:~$ pyenv shell venv37
(venv37) nkpro@SR:~$ pyenv versions
  system
  3.6.10
  3.7.7
  3.7.7/envs/venv37
* venv37 (set by PYENV_VERSION environment variable)
(venv37) nkpro@SR:~$ pyenv versions --skip-aliases
  system
  3.6.10
  3.7.7
  3.7.7/envs/venv37
```

**Comment by native-api** [comment]
Why should it? What did you expect? With `--skip-aliases`, you're skipping the current environment -- so there's no version that is "set" in the list, just what you see!
