### ISSUE TITLE
ssl compile errors in 3.5.2 install but not 3.6.9

### ISSUE THREAD

**Issue by Zeesy** [pyenv/pyenv#1571]
pyenv version: 1.2.17
MacOS Mojave 10.14.6
python-build version: 20160602

and

pyenv version: pyenv 1.2.17-2-ga8ca63fc
Ubuntu 18.04
python-build version: 1.2.17-2-ga8ca63fc
python version 3.6.9

I am able to install any version of python using pyenv on Ubuntu and Mac OS, **except 3.5.2**. This error on Mac:

```
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

...

BUILD FAILED (OS X 10.14.6 using python-build 20180424)
```

And this error on Ubuntu:
```
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

...

BUILD FAILED (Ubuntu 18.04 using python-build 1.2.17-2-ga8ca63fc)
```

Both errors have been referenced numerous times in issues.  I have followed the instructions in Common Build Problems but no luck.

When I follow these suggestions:
> ```
> SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/ pyenv install 3.6.9
> ```

This worked for me. On 10.14.6 Mojave with Xcode 10.3. Pyenv version 1.2.13. Fresh system - all freshly installed.

_Originally posted by @gitsteveno in https://github.com/pyenv/pyenv/issues/1066#issuecomment-524836221_

I am able to install 3.6.9, but not 3.5.2. Suggestions from https://github.com/pyenv/pyenv/issues/1188 don't work either.

On Ubuntu, this suggested command: https://github.com/pyenv/pyenv/issues/950#issuecomment-320913602
results in these errors (same as before):
```ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (Ubuntu 18.04 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20200325140339.29492
Results logged to /tmp/python-build.20200325140339.29492.log```

**Comment by victor-yunenko** [comment]
I also encountered a similar issue on the latest macos, probably after running `brew upgrade`.

Installing the latest 3.6.10 instead of 3.6.8 resolved the problem

### Details:

The errors that were appearing on pip install using 3.6.8 from pyenv were:
```
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/django-cms/
```

While it the system level python3 was working fine.

On the internet there are advices about recompiling python in that case, after making sure that the openssl library is installed and linked correctly. Installing the latest 3.6.10 instead of 3.6.8 resolved the problem as well though. I'm assuming openssl library might have been updated and the linking dropped, or vice versa.

**Comment by lokesh1729** [comment]
#950 openssl version 1.1 is supported from 3.5.3 hence it's expected that build will fail on 3.5.2 same for me

**Comment by saadali5997** [comment]
@Zeesy were you able to fix the issue and install `Python 3.5.2`?
@lokesh1729 is there anything you can suggest we do?
I tried uninstalling `openssl` using 
```
$ brew uninstall openssl
``
and then let `pyenv` install whichever version of `openssl` it wants to install using
```
$ pyenv install 3.5.2
```
but it still did NOT work.
It seems like it is impossible.
All the flags etc are set properly as suggested.

**Comment by lokesh1729** [comment]
@saadali5997 it's impossible because support for openssl 1.1 was added from 3.5.3 please install 3.5.3 it's working

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/wiki/Common-build-problems#2-your-openssl-version-is-incompatible-with-the-python-version-youre-trying-to-install
