### ISSUE TITLE
Homebrew upgraded OpenSSL and Python; now my pyenvs are hosed

### ISSUE THREAD

**Issue by tripleee** [pyenv/pyenv#1572]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.<br/>
... I checked this to the best of my ability; sorry if this is already reported.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.<br/>
Again, I hope this is actually a bug, though it's possible that I misunderstand some aspect of how this is supposed to work.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.<br/>
... Once more, I may have an incomplete understanding of the interactions here.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): MacOS Catalina
- [X] OS architecture (e.g. amd64): x86_64
- [X] pyenv version: 1.2.13
- [X] Python version: system 2.7.16, pre this issue 3.7.2, post this issue 3.7.7
- [X] C Compiler information (e.g. gcc 7.3): Apple clang version 11.0.0 (clang-1100.0.33.17)
- [X] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`<br/>
    I don't see how that's relevant here; which version should I try to install or run?<br/>
   Anyway, https://gist.github.com/tripleee/b719ee752460772517c063f47f58b55f contains the output from `PYENV_DEBUG=1 pip download pep8`. The beef is this snippet:
   ```
      Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pep8/
      Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pep8/
      Could not fetch URL https://pypi.org/simple/pep8/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pep8/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
      Could not find a version that satisfies the requirement pep8 (from versions: )
    No matching distribution found for pep8
   ```

### Brief background

I have installed Homebrew and `pyenv` back when this system was set up, when I was on MacOS Mojave. I relatively recently upgraded to Catalina and now finally needed to install something in Homebrew yesterday. I vaguely expected some fallout from after the upgrade.

I run Homebrew from a privileged account `admin` which is separate from my own. I simply `su admin` and then at the prompt run `brew`.

I wanted to install `ffmpeg` and so I tried `brew install ffmpeg`. It seemed to get stuck in "Updating Homebrew" so I finally cancelled that and ran `brew doctor`, which sternly suggested that I run `brew upgrade` and `brew install openssl@1.1`. I did those things, and was then able to finish installing `ffmpeg` (though it took basically forever -- sheesh, I just wanted to merge a few audio files).

I vaguely noticed that Homebrew also installed a new Python version while it was going about its business, but assumed this would be fine.

### Problem statement

Now when I run `python` (basically any `pyenv`-controlled version of Python I have) I get SSL errors.

I tried to troubleshoot those for a while, until I noticed that `/usr/local/bin/python3` works fine. My conclusion is that the actual problem is with `pyenv` here.

There are two, possibly related, issues here, I'm nor sure if they should be classified as problems with the Homebrew packaging of `pyenv`, or with Homebrew, or with `pyenv` itself. But for `pyenv`, this at the very least means

* `pyenv` should notice when Homebrew updates Python, and offer the new system Python as an option. If the old one goes away, that needs to register within `pyenv`, too.
* `pyenv` documentation should mention this scenario at least in broad terms in the section about installing and maintaining `pyenv` with Homebrew on MacOS. Specifically, my current understanding is that I will basically need to purge all `pyenv`-installed Python versions and reinstall them. Is this correct? This procedure should be documented.

**Comment by JohnSpeno** [comment]
Is the issue here that the ssl module in the affected Python installations are linked with a previous version of the openssl library, which homebrew removed/replaced with a new version recently? It seems that is the behavior I have observed myself on April 1, 2020. After running a `brew upgrade` command which installed `openssl 1.1.1f` and presumably altered the symlink `/usr/local/opt/openssl` to point to `/usr/local/Cellar/openssl@1.1/1.1.1f` which used to point to `/usr/local/Cellar/openssl/1.0.2t`.
