### ISSUE TITLE
Fedora Silverblue requires different commands for installation

### ISSUE THREAD

**Issue by skewty** [pyenv/pyenv#1574]
# Current Wiki Text
- Fedora/CentOS/RHEL(aws ec2):
```shell
sudo yum install @development zlib-devel bzip2 bzip2-devel readline-devel sqlite \
sqlite-devel openssl-devel xz xz-devel libffi-devel findutils
```
# Proposed Addition to Wiki Text (something like)
- Fedora Silverblue
```shell
toolbox enter
sudo dnf update vte-profile  # https://github.com/containers/toolbox/issues/390
sudo dnf install "@Development Tools" zlib-devel bzip2 bzip2-devel readline-devel sqlite \
sqlite-devel openssl-devel xz xz-devel libffi-devel findutils
```

NOTE: Fedora Silverblue doesn't like `sudo yum install @development`.

**Comment by jchkoch** [comment]
Just wanted to note a similar change to the ***Current Wiki Text*** for _openSUSE_:

- the package `openssl-devel` is explicitly called `libopenssl-devel` under openSUSE Leap 15.1 os; however, `zypper` seems intelligent enough to catch this and install the required capabilities anyway.

**Comment by joshfriend** [comment]
Thanks for the note, wiki is updated!

https://github.com/pyenv/pyenv/wiki#suggested-build-environment
