### ISSUE TITLE
Specify install path to python tar 

### ISSUE THREAD

**Issue by alaverty** [pyenv/pyenv#1575]
I am trying to use pyenv from behind a corporate firewall :
```
[root@xxxxxxxxx plays]# pyenv install 2.7.8
Downloading Python-2.7.8.tar.xz...
-> https://www.python.org/ftp/python/2.7.8/Python-2.7.8.tar.xz
Installing Python-2.7.8...
```

Is there any way we can specify the path to the python tar for installation? Say for example  :

```
pyenv install https://myserver/Python-2.7.8.tar.xz
```

**Comment by joshfriend** [comment]
You can use `PYTHON_BUILD_MIRROR_URL` as described [here](https://github.com/pyenv/pyenv/blob/089b828b0f92c40ee510e1aafbea29c189bd96e6/plugins/python-build/README.md#special-environment-variables), though there are several other issue reports that this environment variable is not working currently. I have not confirmed these reports myself so I'd encourage you to try anyways 😄 

If you do encounter a bug, please search for the open issues related to this and follow them for updates

**Comment by alaverty** [comment]
Awesome, thanks will give it a go!
