### ISSUE TITLE
The April 9th commit  is missing a " in the README, causing issues.

### ISSUE THREAD

**Issue by juan-aquino** [pyenv/pyenv#1582]
In the installation instructions, under the 'for bash' section:

`echo 'export PYENV_ROOT="$HOME/.pyenv' >> ~/.bash_profile`

needs a " after .pyenv. My profile couldn't load cause of this.

Also, the 'for bash' and 'for Ubuntu Desktop' in the install instructions is misleading for two reasons.
1. Ubuntu has bash so...both will work right? (No.) Make it more clear.
2. Say 'Ubuntu' not 'Ubuntu Desktop' since it applies to the server version too.

**Comment by joshfriend** [comment]
closed by  #1583
