### ISSUE TITLE
Include libffi information for macOS section of Common build problems wiki page

### ISSUE THREAD

**Issue by george-hawkins** [pyenv/pyenv#1588]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS 10.14.6 (Mojave)
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 1.2.18-3-ge497945
- [x] Python version: 3.8.2
- [x] C Compiler information (e.g. gcc 7.3): clang 4.2.1
- [x] Please attach verbose build log as gist

The build output is available in this [gist](https://gist.github.com/george-hawkins/61bd344eeb6da9e10a584c22f2bd2ee1). The important lines are:

```
modffi.c:32:10: fatal error: 'ffi.h' file not found
#include <ffi.h>
```

On my Mac `libffi` is installed but it is *not* available by default without setting some environment variables:

```
$ brew info libffi
libffi: stable 3.2.1 (bottled), HEAD [keg-only]
...
==> Caveats
libffi is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

For compilers to find libffi you may need to set:
  export LDFLAGS="-L/usr/local/opt/libffi/lib"

For pkg-config to find libffi you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
```

Despite the claim that "macOS already provides this software", the build process does not find any natively installed version and I have to take the suggested steps and set `LDFLAGS` and `PKG_CONFIG_PATH`. Then everything works perfectly:

```
$ export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
$ export LDFLAGS="-L/usr/local/opt/libffi/lib"
$ pyenv install micropython-1.12
Downloading micropython-1.12.tar.gz...
-> https://github.com/micropython/micropython/releases/download/v1.12/micropython-1.12.tar.gz
Installing micropython-1.12...
Installed micropython-1.12 to /Users/georgehawkins/.pyenv/versions/micropython-1.12
$ pyenv shell micropython-1.12
$ micropython
MicroPython v1.12 on 2020-04-13; darwin version
>>>
```

So perhaps the macOS steps on the [Common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems) wiki page need to be expanded to include:

> You may also need to install `pkg-config` and `libffi`:
> ```
> $ brew install pkg-config libffi
> ```
> And then set `LDFLAGS` and `PKG_CONFIG_PATH` according to the instructions shown by:
> ```
> $ brew info libffi
> ```

It may be that this problem hasn't shown up previously as MicroPython is probably not a very common install target and perhaps most people who are installing it are installing it on platforms other than macOS.

**Comment by native-api** [comment]
Latest versions of Homebrew have a "shim" `libffi.pc` that redirects into the XCode SDK. So no action needed unless you wish to specifically use the Homebrew copy (in which case, settings envvars is the way to go).

```
admin@Mac-Admin ~ % pkg-config --libs libffi --debug
Error printing enabled by default due to use of output options besides --exists, --atleast/exact/max-version or --list-all. Value of --silence-errors: 0
Error printing enabled
Adding virtual 'pkg-config' package to list of known packages
Looking for package 'libffi'
Looking for package 'libffi-uninstalled'
Reading 'libffi' from file '/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/11.0/libffi.pc'
Parsing package file '/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/11.0/libffi.pc'
  line>homebrew_sdkroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
 Variable declaration, 'homebrew_sdkroot' has value '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
  line>prefix=${homebrew_sdkroot}/usr
 Variable declaration, 'prefix' has value '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr'
  line>exec_prefix=/usr
 Variable declaration, 'exec_prefix' has value '/usr'
  line>libdir=${exec_prefix}/lib
 Variable declaration, 'libdir' has value '/usr/lib'
  line>toolexeclibdir=${libdir}
 Variable declaration, 'toolexeclibdir' has value '/usr/lib'
  line>includedir=${prefix}/include/ffi
 Variable declaration, 'includedir' has value '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/ffi'
  line>
  line>Name: libffi
  line>Description: Library supporting Foreign Function Interfaces
  line>Version: 3.3-rc0
  line>Libs: -L${toolexeclibdir} -lffi
  line>Cflags: -I${includedir}
Path position of 'libffi' is 4
Adding 'libffi' to list of known packages
Package libffi has -L /usr/lib in Libs
Removing -L /usr/lib from libs for libffi
 post-recurse: libffi
 original: libffi
   sorted: libffi
adding LIBS_L string ""
 post-recurse: libffi
adding LIBS_OTHER | LIBS_l string "-lffi "
returning flags string "-lffi"
-lffi
```
