### ISSUE TITLE
Python 2.7.18

### ISSUE THREAD

**Issue by bitnovus** [pyenv/pyenv#1595]
Python 2.7.18 was released on April 20, 2020 (https://www.python.org/downloads/release/python-2718/). Looking forward to 2.7.18 getting added! Thank you!

I believe binaries are here: https://www.python.org/ftp/python/2.7.18/

(I've tried to include information requested in https://github.com/pyenv/pyenv/issues/1541 for previous work for adding a newly released version.)

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS 10.15.4
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: pyenv 1.2.18
- [x] Python version: 2.7.18
- [x] C Compiler information (e.g. gcc 7.3): gcc 4.2.1

**Comment by joshfriend** [comment]
already done in #1593

**Comment by achinth** [comment]
When is the next release? No releases since 2 months now.

**Comment by joshfriend** [comment]
Just install pyenv by cloning the github repo, then you dont have to wait for someone to find the time to tag and update homebrew

**Comment by tedmiston** [comment]
2.7.18 is available now if you use the pyenv-installer route.

https://github.com/pyenv/pyenv-installer#installation--update--uninstallation

Not sure what the deal is with the Homebrew formula.
