### ISSUE TITLE
Let pyenv install accept cpython's configure options as args.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyenv/pyenv#1597]
Hi,

For shared compiling of cpython, I must use the following commands:

` $ env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.8.2`

Could you please let pyenv install accept cpython's configure options as args, so that it can installed like the following:

`$ pyenv install --enable-shared 3.8.2`

Regards

**Comment by native-api** [comment]
Looks too confusing and problematic.

* [There are a whole bunch of ways to pass flags to the build](https://github.com/pyenv/pyenv/tree/master/plugins/python-build#special-environment-variables). Why should `PYTHON_CONFIGURE_OPTS` have a preference and be the default? That seems arbitrary.
* Being an _implicit_ default also removes the "`PYTHON_CONFIGURE_OPTS`" piece of information from the command line, making it unclear where exactly those switches go.
* This makes it unclear which options are processed by Pyenv itself and which are passed to the build. Plus, conflicts are asking to happen if both Pyenv and the build would accept some argument -- if they aren't already.
