### ISSUE TITLE
failed to compile py2cairo when using pyenv

### ISSUE THREAD

**Issue by hrzhu** [pyenv/pyenv#16]
When I try to compile py2cairo-1.10.0:

> ./waf configure
>   ./options()
> Setting top to                           : /home/nitro/src/py2cairo-1.10.0
> Setting out to                           : /home/nitro/src/py2cairo-1.10.0/build_directory
>   ./configure()
> Checking for 'gcc' (c compiler)          : ok 
> Checking for program python              : /home/nitro/.pyenv/shims/python 
> Checking for python version              : (2, 7, 3, 'final', 0) 
> Checking for library python2.7           : yes 
> Checking for program python2.7-config    : /home/nitro/.pyenv/shims/python2.7-config 
> command ['/home/nitro/.pyenv/shims/python', '/home/nitro/.pyenv/shims/python2.7-config', '--includes'] returned 1

And I try to compile an old version pycairo 1.8.10, I got another error:

> ./waf configure  
>   ./set_options
>   ./init
>   ./configure
> Checking for program gcc or cc           : /usr/bin/gcc 
> Checking for program cpp                 : /usr/bin/cpp 
> Checking for program ar                  : /usr/bin/ar 
> Checking for program ranlib              : /usr/bin/ranlib 
> Checking for gcc                         : ok  
> Checking for program python              : /home/nitro/.pyenv/shims/python 
> Checking for Python version >= 2.6.0     : ok 2.7.3 
> Checking for library python2.7           : yes 
> Checking for program python2.7-config    : /home/nitro/.pyenv/shims/python2.7-config 
>   File "/home/nitro/.pyenv/shims/python2.7-config", line 3
>     [ -n "$PYENV_DEBUG" ] && set -x
>                       ^
> SyntaxError: invalid syntax
> Traceback (most recent call last):
>   File "./waf", line 158, in <module>
>     Scripting.prepare(t, cwd, VERSION, wafdir)
>   File "/home/nitro/src/pycairo-1.8.10/.waf-1.5.16-264215ab3a9d1657aa677dbfa7c8e3f2/wafadmin/Scripting.py", line 105, in prepare
>     prepare_impl(t,cwd,ver,wafdir)
>   File "/home/nitro/src/pycairo-1.8.10/.waf-1.5.16-264215ab3a9d1657aa677dbfa7c8e3f2/wafadmin/Scripting.py", line 98, in prepare_impl
>     main()
>   File "/home/nitro/src/pycairo-1.8.10/.waf-1.5.16-264215ab3a9d1657aa677dbfa7c8e3f2/wafadmin/Scripting.py", line 133, in main
>     fun(ctx)
>   File "/home/nitro/src/pycairo-1.8.10/.waf-1.5.16-264215ab3a9d1657aa677dbfa7c8e3f2/wafadmin/Scripting.py", line 172, in configure
>     conf.sub_config([''])
>   File "/home/nitro/src/pycairo-1.8.10/.waf-1.5.16-264215ab3a9d1657aa677dbfa7c8e3f2/wafadmin/Configure.py", line 140, in sub_config
>     self.recurse(k,name='configure')
>   File "/home/nitro/src/pycairo-1.8.10/.waf-1.5.16-264215ab3a9d1657aa677dbfa7c8e3f2/wafadmin/Utils.py", line 461, in recurse
>     f(self)
>   File "/home/nitro/src/pycairo-1.8.10/wscript", line 32, in configure
>     conf.check_python_headers()
>   File "/home/nitro/src/pycairo-1.8.10/.waf-1.5.16-264215ab3a9d1657aa677dbfa7c8e3f2/wafadmin/Tools/python.py", line 184, in check_python_headers
>     for incstr in Utils.cmd_output("%s %s --includes"%(python,python_config)).strip().split():
>   File "/home/nitro/src/pycairo-1.8.10/.waf-1.5.16-264215ab3a9d1657aa677dbfa7c8e3f2/wafadmin/Utils.py", line 337, in cmd_output
>     raise ValueError(msg)
> ValueError: command execution failed: /home/nitro/.pyenv/shims/python /home/nitro/.pyenv/shims/python2.7-config --includes -> ''

waf configure succeed when I do them without pyenv enabled, the python version are the same, namely my system python installation 2.7.

I've also tried with a python installed by pyenv, it runs into another problem:

> ./waf configure  
>   ./options()
> Setting top to                           : /home/nitro/src/py2cairo-1.10.0 
> Setting out to                           : /home/nitro/src/py2cairo-1.10.0/build_directory 
>   ./configure()
> Checking for 'gcc' (c compiler)          : ok 
> Checking for program python              : /home/nitro/.pyenv/versions/2.7.4/bin/python 
> Checking for python version              : (2, 7, 4, 'final', 0) 
> Traceback (most recent call last):
>   File "/home/nitro/src/py2cairo-1.10.0/.waf-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Scripting.py", line 93, in waf_entry_point
>     run_commands()
>   File "/home/nitro/src/py2cairo-1.10.0/.waf-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Scripting.py", line 145, in run_commands
>     run_command(cmd_name)
>   File "/home/nitro/src/py2cairo-1.10.0/.waf-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Scripting.py", line 138, in run_command
>     ctx.execute()
>   File "/home/nitro/src/py2cairo-1.10.0/.waf-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Configure.py", line 124, in execute
>     super(ConfigurationContext,self).execute()
>   File "/home/nitro/src/py2cairo-1.10.0/.waf-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Context.py", line 87, in execute
>     self.recurse([os.path.dirname(g_module.root_path)])
>   File "/home/nitro/src/py2cairo-1.10.0/.waf-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Context.py", line 127, in recurse
>     user_function(self)
>   File "/home/nitro/src/py2cairo-1.10.0/wscript", line 29, in configure
>     ctx.check_python_headers()
>   File "/home/nitro/src/py2cairo-1.10.0/.waf-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Configure.py", line 214, in fun
>     return f(_k,_*kw)
>   File "/home/nitro/src/py2cairo-1.10.0/.waf-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Tools/python.py", line 123, in check_python_headers
>     if dct[x]:
> KeyError: 'MACOSX_DEPLOYMENT_TARGET'

I don't where the `MACOSX_DEPLOYMENT_TARGET` comes from, I'm using Ubuntu Precise.

**Comment by TensorTom** [comment]
This is still a thing that happens so take my solution as well:

use direnv or just add to your profile/rc:

```
export PKG_CONFIG_PATH="/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH"
```
