### ISSUE TITLE
Quick edit for "Common build problems" wiki page

### ISSUE THREAD

**Issue by lapinvert** [pyenv/pyenv#1600]
In pyenv wiki, the "common build problems" page here: 
https://github.com/pyenv/pyenv/wiki/common-build-problems

There's this line:
```
sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
xz-utils tk-dev libffi-dev liblzma-dev python-openssl git
```

`build-essential` already includes `make` as you can see [here](https://packages.ubuntu.com/focal/build-essential) (Ubuntu), and [here](https://packages.debian.org/jessie/build-essential) (Debian).

So I think we can remove `make` and keep `build-essential`.

**Comment by joshfriend** [comment]
thanks for the suggestion!
