### ISSUE TITLE
I cannot use pyenv in virtualenv

### ISSUE THREAD

**Issue by pwittchen** [pyenv/pyenv#1604]
Hi,

This project is a cool idea, but I cannot use pyenv in virtualenv.

For example, I installed pyenv, installed different python versions and tried to create virtualenv with virtualenvwrapper:

```
mkvirtualenv -p ~/.pyenv/versions/3.7.0 myenv
```

I got response that I don't have appropriate permissions. Then, I tried to execute it with `sudo` and tried to change chmod in the `~/.pyenv/versions/*` dirs and subdirs and then after no luck, I gave up, because I had no idea why it doesn't work and says that I don't have permissions even when I gave permissions for the dirs with python.

When I installed two python versions, with pacman from aur on arch linux, I could easily create virtualenvs with different python versions, but with this tool, I couldn't.

Regards,
Piotr

**Comment by joshfriend** [comment]
[Please read the instructions](https://github.com/pyenv/pyenv#choosing-the-python-version)
