### ISSUE TITLE
Stricter POSIX sh compliance

### ISSUE THREAD

**Issue by mcandre** [pyenv/pyenv#1609]
Please write the installer and runtime in terms of POSIX sh, so that more developers can enjoy pyenv!

* POSIX sh users
* ksh users
* ash
* dash
* posh
* oil shell
* yash

**Comment by joshfriend** [comment]
Please follow the issue template instructions and perform a search of existing issues before submitting a new one.

https://github.com/pyenv/pyenv/issues/499#issuecomment-163419865
