### ISSUE TITLE
error with recursive calls to shimmed sed

### ISSUE THREAD

**Issue by jhcarb** [pyenv/pyenv#1618]
The current pyenv (5a96d9f2cd8b068a0be1baca9c7c77386f03d047) has an issue when you have a conda [sed](https://anaconda.org/conda-forge/sed) installed in a virtual environment. `pyenv local` or `.python-version` does not work, hanging the whole system by a recursive call to `pyenv-version-file-read` to find shimmed sed. `pyenv-help` and `pyenv-which` also seem to have the same issue since they also use sed.

**Comment by native-api** [comment]
Please include a sample debug trace as required by the issue template.
