### ISSUE TITLE
pyenv installation issue on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by moldach** [pyenv/pyenv#1621]
Here is the description information:

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): **Ubuntu Linux 20.04**
- [x] OS architecture (e.g. amd64):  **5.4.0-29-generic**
- [x] pyenv version: **pyenv 1.2.18-17-g2c32a6be**
- [x] Python version: **Python 3.7.6**
- [x] C Compiler information (e.g. gcc 7.3): **gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0**
- [x] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

When trying to install `Python 3.5.0` I get an error 

```
env PYENV_DEBUG=1 pyenv install -v 3.5.0`


...

ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems

```

[_I've attached the link to the log/gist here_](https://gist.github.com/moldach/54904258d65bae2113cf9f04d437ddc6)

I followed the Wiki but that did not solve the issue:

```
sudo apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
xz-utils tk-dev libffi-dev liblzma-dev python-openssl git
```

and 

```
CFLAGS=-I/usr/include/openssl \
LDFLAGS=-L/usr/lib64 \
pyenv install -v 3.5.0
```

**Comment by moldach** [comment]
Add OS architecture via `uname -r`

**Comment by mukul-mehta** [comment]
Hi. 
Could you try running `sudo apt-get install libssl1.0-dev`. Once `pyenv` installs, you could reinstall `libssl-dev`.

**Comment by moldach** [comment]
Hi @mukul-mehta I tried the following but I get an error...

```
(base) mtg@mtg-ThinkPad-P53:~$ sudo apt-get install -y libssl1.0-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libssl1.0-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'libssl1.0-dev' has no installation candidate
```

I'm on Ubuntu 20.04

**Comment by moldach** [comment]
To download `libssl1.0-dev` from Ubuntu 18.04 onward you need to do:

```
(base) mtg@mtg-ThinkPad-P53:~$ sudo bash -c "echo 'deb http://security.debian.org/debian-security jessie/updates main' >> /etc/apt/sources.list"

(base) mtg@mtg-ThinkPad-P53:~$ sudo apt-get update -y && apt-get install -y --no-install-recommends \
>     libssl1.0.0
Hit:1 http://dl.google.com/linux/chrome/deb stable InRelease
Get:2 http://security.debian.org/debian-security jessie/updates InRelease [44.9 kB]                
Hit:3 https://dl.yarnpkg.com/debian stable InRelease                                               
Hit:4 https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease                         
Hit:6 http://ca.archive.ubuntu.com/ubuntu focal InRelease                                          
Err:2 http://security.debian.org/debian-security jessie/updates InRelease                          
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9D6D8F6BC857C906 NO_PUBKEY AA8E81B4331F7F50
Hit:7 http://ca.archive.ubuntu.com/ubuntu focal-updates InRelease                                  
Hit:8 http://ca.archive.ubuntu.com/ubuntu focal-backports InRelease                                
Hit:9 http://security.ubuntu.com/ubuntu focal-security InRelease                                   
Hit:5 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease                      
Hit:10 https://packages.microsoft.com/repos/ms-teams stable InRelease                              
Reading package lists... Done
W: GPG error: http://security.debian.org/debian-security jessie/updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9D6D8F6BC857C906 NO_PUBKEY AA8E81B4331F7F50
E: The repository 'http://security.debian.org/debian-security jessie/updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```


But still the installation fails for me:

```
(base) mtg@mtg-ThinkPad-P53:~$ pyenv install 3.5.0
Downloading Python-3.5.0.tar.xz...
-> https://www.python.org/ftp/python/3.5.0/Python-3.5.0.tar.xz
Installing Python-3.5.0...
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (Ubuntu 20.04 using python-build 1.2.18-17-g2c32a6be)

Inspect or clean up the working tree at /tmp/python-build.20200526102113.16794
Results logged to /tmp/python-build.20200526102113.16794.log

Last 10 log lines:
(cd /home/mtg/.pyenv/versions/3.5.0/share/man/man1; ln -s python3.5.1 python3.1)
if test "xupgrade" != "xno"  ; then \
	case upgrade in \
		upgrade) ensurepip="--upgrade" ;; \
		install|*) ensurepip="" ;; \
	esac; \
	 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
Ignoring ensurepip failure: pip 7.1.2 requires SSL/TLS
```

**Comment by moldach** [comment]
The `libssl1.0-dev` issue I think I took care of.

The issue with `pyenv install` not working *may* have been due to `4. Restart your shell so the path changes take effect.` - I can't be sure now. 

What I do know, is that *now* `pyenv install` works and it places them into `$(pyenv root)/versions`.

```
(base) mtg@mtg-ThinkPad-P53:~/bin/GenESysV$ pyenv install 3.6.0
pyenv: /home/mtg/.pyenv/versions/3.6.0 already exists
continue with installation? (y/N) n
(base) mtg@mtg-ThinkPad-P53:~/bin/GenESysV$ /home/mtg/.pyenv/versions/3.6.0/bin/python3.6
Python 3.6.0 (default, May 28 2020, 09:03:33) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

However, I have a `PATH` issue:

```
(base) mtg@mtg-ThinkPad-P53:~/bin/GenESysV$ python3.6
pyenv: python3.6: command not found

The `python3.6' command exists in these Python versions:
  3.6.0

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
```

This is what my `/.bashrc` looks like:

```
export PYENV_ROOT="/home/mtg/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
```

**Comment by moldach** [comment]
I solved this via:

```
pyenv local 3.6.0
```

**Comment by gamesguru** [comment]
It's conflated to `libssl-dev` for 20.04 in recent release.

**Comment by pand-oly** [comment]
> The `libssl1.0-dev` issue I think I took care of.
> 
> The issue with `pyenv install` not working _may_ have been due to `4. Restart your shell so the path changes take effect.` - I can't be sure now.
> 
> What I do know, is that _now_ `pyenv install` works and it places them into `$(pyenv root)/versions`.
> 
> ```
> (base) mtg@mtg-ThinkPad-P53:~/bin/GenESysV$ pyenv install 3.6.0
> pyenv: /home/mtg/.pyenv/versions/3.6.0 already exists
> continue with installation? (y/N) n
> (base) mtg@mtg-ThinkPad-P53:~/bin/GenESysV$ /home/mtg/.pyenv/versions/3.6.0/bin/python3.6
> Python 3.6.0 (default, May 28 2020, 09:03:33) 
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> 
> ```
> 
> However, I have a `PATH` issue:
> 
> ```
> (base) mtg@mtg-ThinkPad-P53:~/bin/GenESysV$ python3.6
> pyenv: python3.6: command not found
> 
> The `python3.6' command exists in these Python versions:
>   3.6.0
> 
> Note: See 'pyenv help global' for tips on allowing both
>       python2 and python3 to be found.
> ```
> 
> This is what my `/.bashrc` looks like:
> 
> ```
> export PYENV_ROOT="/home/mtg/.pyenv"
> export PATH="$PYENV_ROOT/bin:$PATH"
> 
> if command -v pyenv 1>/dev/null 2>&1; then
>   eval "$(pyenv init -)"
> fi
> ```

for a layman what would be "(Base)"

**Comment by moldach** [comment]
> for a layman what would be "(Base)"

The prefix (base) on the `CLI` is showing that I have a [base `Conda` environment activated](https://askubuntu.com/questions/1026383/why-does-base-appear-in-front-of-my-terminal-prompt)

You can [manage virtual environments created with `Conda` with `pyenv`, _see the README_]:(https://github.com/pyenv/pyenv#managing-virtual-environments)

**Comment by JREAM** [comment]
```sh
sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
  libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
  xz-utils tk-dev                                                                  
```
