### ISSUE TITLE
New plugin for pyenv. Request to add it to Wiki/Pages. (pyenv-choice)

### ISSUE THREAD

**Issue by fizista** [pyenv/pyenv#1623]
I've written a new plugin, which has more advanced features than https://github.com/concordusapps/pyenv-implict. It can even completely replace it.

It would be good to add it to Wiki/Plugins page.

Unlike pyenv-implict, we can define which version of python is to be used for a given command. 

The plugin is here:
https://github.com/fizista/pyenv-choice

**Comment by joshfriend** [comment]
Done!
