### ISSUE TITLE
${PYENV_ROOT}/versions/<python version>/bin/ not added to PATH with no venv

### ISSUE THREAD

**Issue by bsolomon1124** [pyenv/pyenv#1626]
## Summary

It seems that on MacOS, in the absence of a virtual environment, the path

```
${PYENV_ROOT}/versions/$(pyenv version-name)/bin/
```

is _not_ added to `PATH`, and so "console scripts" are not callable after installation by pip.

## Description

- Platform information (e.g. Ubuntu Linux 16.04): MacOS 10.15.4
- OS architecture (e.g. amd64): x86_64
- pyenv version: pyenv 1.2.18-17-g2c32a6b
- Python version: 3.8.3
- C Compiler information (e.g. gcc 7.3): Apple clang version 11.0.0 (clang-1100.0.33.12)

## Example

Using [`delocate`]():

```
$ python -m pip install -U delocate
$ command -v delocate-wheel
$ ls -1 "${PYENV_ROOT}/versions/$(pyenv version-name)/bin/"
2to3
2to3-3.8
delocate-addplat
delocate-fuse
delocate-listdeps
delocate-patch
delocate-path
delocate-wheel
easy_install
easy_install-3.8
idle
idle3
idle3.8
pip
pip3
pip3.8
pydoc
pydoc3
pydoc3.8
python
python-config
python3
python3-config
python3.8
python3.8-config
python3.8-gdb.py
wheel
```

PATH is (prettified with newlines):

```
/bin
/sbin
/Users/brad/.pyenv/bin
/Users/brad/.pyenv/plugins/pyenv-virtualenv/shims
/Users/brad/.pyenv/shims
/Users/brad/bin
/usr/bin
/usr/local/bin
/usr/local/sbin
/usr/sbin
```

**Comment by bsolomon1124** [comment]
Update: it looks like installing without the `-m` flag will put the scripts directly into `/Users/brad/.pyenv/shims/` so that they are findable.  However, I am curious if this aligns with the intended behavior.

**Comment by native-api** [comment]
This is by design.

Pyenv only adds `$(pyenv root)/shims` to `PATH`.

You need to run `pyenv rehash` to update shims if you install executables in a way other than the `pip` shim (which does this automatically after the underlying Pip returns).
