### ISSUE TITLE
System python installations are not detected by pyenv

### ISSUE THREAD

**Issue by aspiers** [pyenv/pyenv#1628]
Several major Linux distributions have been providing simultaneous installs of Python 2 and 3 for quite a long time now, including Ubuntu, openSUSE, RHEL, and Mint.  According to #1585, the same holds true for Mac OS 10.15.4, and probably many other Mac OS versions too.  In these cases, typically:

- `/usr/bin/python` symlinks to either `python2` or `python3`, or may not exist at all
- `/usr/bin/python2` provides some version of Python 2
- `/usr/bin/python3` provides some version of Python 3

However, typically `pyenv` will only support use of `/usr/bin/python` as the single system version, so if the symlink is missing it doesn't find any system `python` **[UPDATE: this bit will be fixed if #1655 is merged]**, and even if it's not missing, if both 2 and 3 are present, it will only find one of them.  This has led to bug reports such as #1029, #1366, #1585, and #1613, the number of which alone suggests to me that this is worth addressing.  But in addition to these, there are valid use cases for **[UPDATED to clarify]** pyenv supporting the choice between at least two different *simultaneously installed* system versions:

In #1613 [**@b12thompson**](https://github.com/b12thompson) commented on [June 7, 2020 3:09 AM](https://github.com/pyenv/pyenv/issues/1613#issuecomment-640145379 "2020-06-07T02:09:05Z - Replied by Github Reply Comments"):
> 1.  **System python installations are not detected by pyenv**:
> 
> I was able to partially replicate the error in Linux Mint 19.3. The system Python 2 install was detected but the Python 3 version was not, which for me isn't a big deal. In my opinion, system installations of Python should be reserved for internal OS libraries and third-party packages. The user shouldn't really care about using the system installations of Python.
> 
> I'm not trying to nullify the error by saying that "you shouldn't be using the system installation anyway". Perhaps there are good use cases that I'm missing and don't completely understand. If someone is willing to clarify then we can proceed with an appropriate bug fix.

As a developer, if I clone a git repo into my home directory which contains some scripts which depend on Python 3 being the `python` on `$PATH` (e.g. they start with `#!/usr/bin/env python`), I want to be able to set up a valid environment for them, without messing with my global Python environment.  And since I already have Python 3 installed system-wide, I really don't want to waste time / disk / bandwidth installing a new `python3` locally for this user unless there is a good reason for it, because my system `python3` is already perfectly good enough, and even often already has the required modules installed via distribution packages.  Instead it would be great if I could just run `pyenv local system3` or similar to use pyenv to point this repo directly at `/usr/bin/python3`.

This is one class of use cases, but I'm fairly sure there will be others.

**[UPDATED to clarify]** However in the case where there are two or more system Pythons simultaneously installed, enhancing pyenv in this way should not be done in a way which simply switches `pyenv local system` to mean a different version; it should offer the user the choice of which system version they want to use.

**Comment by b12thompson** [comment]
>  And since I already have Python 3 installed system-wide, I really don't want to waste time / disk / bandwidth installing a new python3 locally for this user unless there is a good reason for it, because my system python3 is already perfectly good enough

I completely agree with that statement.  The recommendation I was making in the quote you referenced was aimed towards more seasoned Python developers.  If you want to ensure that you are developing, testing, and deploying "bug-free" you'll want to test against many versions of Python.  In that case, the system install just doesn't cut it most times.

**Comment by rohitsuratekar** [comment]
I can confirm this on openSUSE Tumbleweed (20200614). Since last 2 hours I am trying to set up `pyenv` without installing new _python3_. openSUSE TW do not have any symlink to `python`. In addition,  _python2_ is not installed by default. `pyenv` is not searching for _python3_ in the PATH and returning error/warning as `no Python detected on the system`. Ideally, it should be able to search both _python2_ and _python3_ binary instead just _python_. 

I tried creating symlink with `ln -s /usr/bin/python3 /usr/bin/python`. Using this symlink works but it broke many other things (for example, YouCompleteMe plugin in vim). Is there any workaround for this for now?

**Comment by draeath** [comment]
PR #1655 should fix this

**Comment by aspiers** [comment]
@draeath Thanks a lot for working on this and referencing this issue!  I just realised that my original issue description was somewhat ambiguous.  I did not make it clear enough that I believe pyenv should be able to detect multiple system pythons *simultaneously*.  So if Python 2 and 3 are *both* installed, it should not just pick one, but allow the user to choose which system Python they want to use, e.g. via `pyenv local system2` or `pyenv local system3`.  

Consequently, while #1655 is a great step in the right direction, it does not resolve this issue.  I'll edit the description to clarify.

**Comment by draeath** [comment]
Ah, my apologies!

**Comment by aspiers** [comment]
Absolutely no apology needed! ;-)

**Comment by qiulang** [comment]
Hi is there a defined date/schedule to fix this problem ?  https://github.com/doloopwhile/pyenv-register claims to do the job, but it fails to detect my system installed python.

I really hope pyenv can do the job by itself.

**Comment by ClintEsteMadera** [comment]
> https://github.com/doloopwhile/pyenv-register

Thanks a lot for this reference! This plugin worked for me!
