### ISSUE TITLE
Update "prerequisite" wiki page

### ISSUE THREAD

**Issue by demus** [pyenv/pyenv#1633]
I hit two issues installing python with pyenv on Ubuntu 20.0.4 LTS on WSL that might be worth adding to the common build problems sections on the prerequisite wiki page.

1. no acceptable C compiler found in $PATH

     - Fix: install GCC with `sudo apt-get install build-essentials`

2. zipimport.ZipImportError: can't decompress data; zlib not available

     - Fix: install zlib dev with `sudo apt-get install zlib1g-dev`

Also, I suggest moving from a wiki to markdown files in repository so that people can make PRs updating the docs directly.

Thanks!

**Comment by enyrgy** [comment]
Both of those are covered in the wiki, but I do agree that the wiki should move to the repository since that's where developers look first.

**Comment by demus** [comment]
Oops, I see. For some reason I had to install `build-essential` and `zlib1g-dev` separately even though I ran the one-liner listed on that page.

Nvm -- thanks for looking
