### ISSUE TITLE
./Include/fileutils.h:108:12: warning: ‘struct stat’ declared inside parameter list will not be visible outside of this definition or declaration   108 |     struct stat *status);

### ISSUE THREAD

**Issue by rsugumar** [pyenv/pyenv#1634]
After installing `pyenv` using `git clone`, attempted to install bunch of python versions using pyenv. However `Build Failed` with errors (as seen in the gist link mentioned below).

_Additional Info:_
I also added this in my `~/.zshrc` file:
```
# pyenv root
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi
```

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 20.04 LTS
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: pyenv 1.2.18
- [x] Python version: 3.7.7 (actually tried 2.7.7, 3.8.0, etc., - same issue)
- [x] C Compiler information (e.g. gcc 7.3): 9.2.1
- [x] Please attach verbose build log as gist: [Verbose log](https://gist.github.com/rsugumar/2ce9d6c22b747a1e47f46d5c81777e0c)

**Comment by rsugumar** [comment]
This issue got resolved I attempted to `pyenv install 3.7.7` after:

```
    - sudo apt-get update
    - sudo apt-get install gcc --only-upgrade
```
So it's **NOT** a pyenv issue. Sorry for the noise

**Comment by enyrgy** [comment]
No worries, glad you found a resolution!  Since your issue is resolved could you close it please?

**Comment by native-api** [comment]
You are missing `sys/stat.h`
