### ISSUE TITLE
pyenv install --list not showing python 3.8.3

### ISSUE THREAD

**Issue by SmithSamuelM** [pyenv/pyenv#1635]
MacOS 10.15.5
zsh

% pyenv --version
pyenv 1.2.18
~ % pyenv install --list | grep 3.8
  3.8.0
  3.8-dev
  3.8.1
  3.8.2
  miniconda-3.8.3
  miniconda3-3.8.3

**Comment by enyrgy** [comment]
I can confirm this:

```zsh
~ % pyenv install --list | grep 3.8.3
  miniconda-3.8.3
  miniconda3-3.8.3
~ %
```
