### ISSUE TITLE
please tag a new release

### ISSUE THREAD

**Issue by wbolster-eiq** [pyenv/pyenv#1636]
with the current version:

```
$ pyenv --version
pyenv 1.2.18
```

it is not possible to install python3.9 (dev):

```
$ pyenv install 3.9-dev
[...]

ERROR: invalid Python executable: /home/wbolster/.pyenv/versions/3.9-dev/bin/python3.9

The python-build could not find proper executable of Python after successful build.
Please open an issue for future improvements.
https://github.com/pyenv/pyenv/issues

BUILD FAILED (Arch Linux using python-build 20180424)
```

it's actually installing `python3.10` binaries, as indicated by (many) lines like this in the build output:

```
	/usr/bin/install -c python /home/wbolster/.pyenv/versions/3.9-dev/bin/python3.10; \
```

**Comment by wbolster-eiq** [comment]
seems like the root cause was addressed in #1619 already, but there's not been a `pyenv` release since, which is unfortunate since `pyenv` is a fantastic tool to keep up with the latest (and hopefully greatest) in-development versions of python.

**Comment by joshfriend** [comment]
https://github.com/Homebrew/homebrew-core/pull/56451

**Comment by wbolster-eiq** [comment]
awesome, thanks!
