### ISSUE TITLE
Missing the OpenSSL lib? on installing pypy3.6-v7.3.1 by pyenv 1.2.19

### ISSUE THREAD

**Issue by droxer** [pyenv/pyenv#1639]
Hey guys, I got a error on installing pypy3.6-v7.3.1 by pyenv 1.2.19。And I tried all solutions listed in (https://github.com/pyenv/pyenv/wiki/Common-build-problems), none of them helps.

Installing pypy3.6-v7.3.1-osx64...
/usr/local/bin/python-build: line 1590: 20383 Abort trap: 6           "$PYTHON_BIN" -c "import $1" > /dev/null 2>&1
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
/usr/local/bin/python-build: line 1590: 20384 Abort trap: 6           "$PYTHON_BIN" -c "import $1" > /dev/null 2>&1
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
/usr/local/bin/python-build: line 1599: 20385 Abort trap: 6           "$PYTHON_BIN" -c "import $1" > /dev/null 2>&1
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems

BUILD FAILED (OS X 10.15.5 using 0000000000)

Inspect or clean up the working tree at /var/folders/zc/t2zzk0m508qb0dz5pz58kb0c0000gn/T/python-build.20200623091323.20300
Results logged to /var/folders/zc/t2zzk0m508qb0dz5pz58kb0c0000gn/T/python-build.20200623091323.20300.log

Last 10 log lines:
/var/folders/zc/t2zzk0m508qb0dz5pz58kb0c0000gn/T/python-build.20200623091323.20300 ~/Workspace/python-projects
/var/folders/zc/t2zzk0m508qb0dz5pz58kb0c0000gn/T/python-build.20200623091323.20300/pypy3.6-v7.3.1-osx64 /var/folders/zc/t2zzk0m508qb0dz5pz58kb0c0000gn/T/python-build.20200623091323.20300 ~/Workspace/python-projects

**Comment by brechtm** [comment]
I think this may be caused by the fact that the downloaded [PyPy binary doesn't work on macOS](https://foss.heptapod.net/pypy/pypy/issues/3229).

**Comment by droxer** [comment]
> I think this may be caused by the fact that the downloaded [PyPy macOS binary is currently broken](https://foss.heptapod.net/pypy/pypy/issues/3229).

Not sure, it works in homebrew.

**Comment by brechtm** [comment]
> Not sure, it works in homebrew.

The PyPy3 from Homebrew is not using the binary provided by the PyPy team, but is built from source (which is also available from a pre-built "bottle").

**Comment by adammenges** [comment]
FWIW I see something similar which I try to install anything:

```bash
⇒  pip3 install flask
/usr/local/Cellar/pyenv/1.2.18/pyenv.d/exec/pip-rehash/pip: line 20: 46827 Abort trap: 6           "$PYENV_COMMAND_PATH" "$@"
⇒  which pip3
/Users/adammenges/.pyenv/shims/pip3
```

**Comment by techouse** [comment]
Same issue here on macOS Catalina

```bash
pyenv install -v pypy3.6-7.3.1
/var/folders/py/p2g8slts11bggsq2sfzbjf3m0000gn/T/python-build.20200726110946.88980 ~
/var/folders/py/p2g8slts11bggsq2sfzbjf3m0000gn/T/python-build.20200726110946.88980/pypy3.6-v7.3.1-osx64 /var/folders/py/p2g8slts11bggsq2sfzbjf3m0000gn/T/python-build.20200726110946.88980 ~
Installing pypy3.6-v7.3.1-osx64...
/usr/local/bin/python-build: line 1590: 89158 Abort trap: 6           "$PYTHON_BIN" -c "import $1" > /dev/null 2>&1
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
/usr/local/bin/python-build: line 1590: 89159 Abort trap: 6           "$PYTHON_BIN" -c "import $1" > /dev/null 2>&1
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
/usr/local/bin/python-build: line 1599: 89160 Abort trap: 6           "$PYTHON_BIN" -c "import $1" > /dev/null 2>&1
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (OS X 10.15.6 using 0000000000)

Inspect or clean up the working tree at /var/folders/py/p2g8slts11bggsq2sfzbjf3m0000gn/T/python-build.20200726110946.88980
Results logged to /var/folders/py/p2g8slts11bggsq2sfzbjf3m0000gn/T/python-build.20200726110946.89014.log

Last 10 log lines:
/var/folders/py/p2g8slts11bggsq2sfzbjf3m0000gn/T/python-build.20200726110946.88980 ~
/var/folders/py/p2g8slts11bggsq2sfzbjf3m0000gn/T/python-build.20200726110946.88980/pypy3.6-v7.3.1-osx64 /var/folders/py/p2g8slts11bggsq2sfzbjf3m0000gn/T/python-build.20200726110946.88980 ~
```

**Comment by karolhor** [comment]
Hi. Is there any update with this issue? I have same error message like above (with bz2 and ssl). I'm running `pyenv` from master (58c776a, with new `pypy` binary sources from python.org)

**Comment by native-api** [comment]
Can't say anything without a debug trace as required by the issue template.
