### ISSUE TITLE
The setup for fish env appends pyenv path every login.

### ISSUE THREAD

**Issue by kobayashi** [pyenv/pyenv#1642]
Setup for fish env described in `README` appends pyenv path to fish_variables in every fish-shell starting.

```
set -Ux PYENV_ROOT $HOME/.pyenv
set -Ux fish_user_paths $PYENV_ROOT/bin $fish_user_paths
```

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): OSX 10.14.5 (18F132)
- [ ] OS architecture (e.g. amd64): 
- [ ] pyenv version: pyenv 1.2.19-1-gece59ca8
- [ ] Python version:  3.7.7

This is because universal variables are stored in the file .config/fish/fish_variables. The set command should be like this.
```
set -Ux fish_user_paths $PYENV_ROOT/bin
```

**Comment by berislavlopac** [comment]
The problem with the solution suggested above is that it will overwrite the value of `$fish_user_paths` if it already exists. I would recommend using the following line instead:

```
contains $PYENV_ROOT/bin $fish_user_paths; or set -Uax fish_user_paths $PYENV_ROOT/bin
```
