### ISSUE TITLE
Install: very slow and spend a long time

### ISSUE THREAD

**Issue by grtfou** [pyenv/pyenv#165]
I really like **pyenv**. But when I install Python on AWS EC2.
(t1.micro, Ubuntu 12.04.4 LTS)
It spent a long time **(~30 min.)**.
And it use heavy CPU cost to let the machine freeze.

```
Memory: 0.6 GB
```

Is my machine issue or others?
Have any solution?

Thank you :)

```
$ pyenv install 2.7.6

Downloading Python-2.7.6.tgz...
-> http://yyuu.github.io/pythons/1d8728eb0dfcac72a0fd99c17ec7f386
Installing Python-2.7.6...
patching file ./Modules/readline.c
```

```
$ top
```

| PID | USER | PR | NI | VIRT | RES | SHR | S | %CPU | %MEM | TIME+ | COMMAND |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 8390 | xxxx | 20 | 0 | 47124 | 78m | 7596 | R | 99.2 | 4.2 | 0:25.26 | cc1 |

**Comment by thelou1s** [comment]
slow in vultr.com VPS Server too

**Comment by simon-friedberger** [comment]
> Please try with larger instance types during `pyenv install`. Because the `pyenv install` will build CPython from source, it consumes bunch of memory and CPU cycles.

Why does it build from source? Is there a version which simply installs a pre-built version?
