### ISSUE TITLE
Wiki update request: Python requirements on void linux

### ISSUE THREAD

**Issue by llimllib** [pyenv/pyenv#1653]
I had to figure out the build requirements for python on void linux, and I wanted to add to the wiki but I'm not able to update it. Can somebody add Void Linux to the Suggested Build Environments page for me? https://github.com/pyenv/pyenv/wiki#suggested-build-environment

Here's what's required on Void:

`sudo xbps-install bzip2-devel libffi-devel libressl-devel libxml2-devel readline readline-devel sqlite-devel zlib-devel`

**Comment by native-api** [comment]
Duplicate of https://github.com/pyenv/pyenv/issues/1923
