### ISSUE TITLE
pyenv cannot find python in shims

### ISSUE THREAD

**Issue by jm33-m0** [pyenv/pyenv#1657]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): macos 10.15.5
- [ ] OS architecture (e.g. amd64): amd64
- [ ] pyenv version: 1.2.19
- [ ] Python version: python3.7.7
- [ ] C Compiler information (e.g. gcc 7.3):
- [ ] Please attach verbose build log as gist

I have 3.7.7 version installed as default python, and installed 3.8.3 for test, both have this issue:

`pyenv which python` says I don't have python. I checked `~/.pyenv/shims`, `python` is not there

This issue makes system `python` default

**Comment by jm33-m0** [comment]
I have to add the `python` soft link manually as it's not present in the python installation.
I think pyenv somehow forgets to add such link

**Comment by native-api** [comment]
Looks like you didn't configure the shell properly or didn't restart it as per the README. An automatic `pyenv rehash` should've taken care of the shims.
Can't say anything without a debug log as required by the issue template anyway.
