### ISSUE TITLE
Can't set version of OpenSSL to be used in Python compilation.

### ISSUE THREAD

**Issue by Urahara** [pyenv/pyenv#1659]
I installed **OpenSSL 1.0.2g** and i want pyenv use this version when build my Python 3.6.2 because i have some libs that i need backward compatibility, i set these flags:

```sh
CFLAGS="-I/usr/local/ssl/include"
LDFLAGS="-L/usr/local/ssl/lib"
```

When i run to check what version of openssl python is using 

```sh
python -c "import ssl; print(ssl.OPENSSL_VERSION)"
```

I get:
OpenSSL 1.1.1  11 Sep 2018

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description

- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 18.04.3 LTS
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 1.2.20
- [x] Python version: 3.6.2
- [x] C Compiler information (e.g. gcc 7.3): 7.5.0
- [x] Please attach verbose build log as gist: https://gist.github.com/Urahara/a1825318b9ab31eb50de31cfd766f398

**Comment by awfabian-rs** [comment]
Seconded. I tried a few more things. like exporting LIBRARY_PATH and C_INCLUDE_DIR and env PYTHON_CONFIGURE_OPTS="--with-openssl=/usr/pkg" pyenv install 3.8.4 . as far as I can see, nothing works.

**Comment by Urahara** [comment]
@joshfriend @yyuu @chrahunt Can you guys help us?

**Comment by Urahara** [comment]
I used this [article](https://www.howtoforge.com/tutorial/how-to-install-openssl-from-source-on-linux/) to build my own openSSL.

**Comment by Urahara** [comment]
I build python without pyenv and its works:

```sh
curl https://www.openssl.org/source/openssl-1.0.2g.tar.gz | tar xz && cd openssl-1.0.2g && ./config shared --prefix=/usr/local/ && make && make install
LDFLAGS="-L/usr/local/lib/"
LD_LIBRARY_PATH="/usr/local/lib/"
CFLAGS="-I/usr/local/include -I/usr/local/include/openssl"
RUN curl https://www.python.org/ftp/python/3.6.2/Python-3.6.2.tgz | tar xz && cd Python-3.6.2 && ./configure --prefix=/usr/local/ && make install
```

**Comment by native-api** [comment]
The gist gives a 404
