### ISSUE TITLE
pyenv install fails with gcc 9.3

### ISSUE THREAD

**Issue by thierrybo** [pyenv/pyenv#1660]
On my Debian testing (11 / bullseye) with gcc 9.3, some gcc command line options have changed and the command 'pyenv install' fails. For example from config.log:

```
gcc version 9.3.0 (Debian 9.3.0-14) 
configure:3876: $? = 0
configure:3865: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3876: $? = 1
configure:3865: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
```

**Comment by Centurix** [comment]
Came across the same issue with a fresh Linux Mint install with gcc 9.3. Further down the log I found:

```
/usr/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
```

Installed `musl-dev` and `libc-dev` which moved me forward. However, the base Mint install didn't have `zlib1g-dev` which stopped it from being able to unzip portions of the Python install later. Once these were on-board, `pyenv install x.x.x` worked fine.

**Comment by native-api** [comment]
@thierrybo This is an autotools issue. Newer Python releases in the 3.8 line should have a `configure` generated by newer Autotools.
Unless there are some compelling reasons to want to install such old releases with unfixed bugs on such a cutting-edge system, I think this isn't worth the effort.
