### ISSUE TITLE
pyenv does not create python executable

### ISSUE THREAD

**Issue by djcunningham0** [pyenv/pyenv#1678]
pyenv is not creating a `python` executable. It *is* creating a `python3` executable.

I installed pyenv, added the appropriate lines to `~/.bash_profile`, and then followed the basic setup to install a new version of python and set it as the global version:
```bash
$ pyenv install 3.7.3
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.3.tar.xz...
-> https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz
Installing Python-3.7.3...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.7.3 to /Users/Daniel/.pyenv/versions/3.7.3

$ pyenv global 3.7.3
```

This doesn't update the path of my `python` executable, but it *does* update the path of the `python3` executable:
```bash
$ which python
/usr/bin/python

$ which python3
/Users/Daniel/.pyenv/shims/python3
```

Here are the full contents of my `~/.pyenv/shims/` directory:
```bash
$ ls -la ~/.pyenv/shims/
total 144
drwxr-xr-x  20 Daniel  staff  640 Aug 16 02:57 .
drwxr-xr-x   5 Daniel  staff  160 Aug 16 02:51 ..
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 2to3
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 2to3-3.7
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 easy_install-3.7
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 idle3
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 idle3.7
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 pip3
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 pip3.7
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 pydoc3
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 pydoc3.7
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 python3
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 python3-config
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 python3.7
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 python3.7-config
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 python3.7-gdb.py
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 python3.7m
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 python3.7m-config
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 pyvenv
-rwxr-xr-x   1 Daniel  staff  416 Aug 16 02:50 pyvenv-3.7
```

Why isn't `~/.pyenv/shims/python` getting created? I can always use `python3`, or copy `python3` into `python` or use a symbolic link or something, but those don't seem like good solutions.

I have tried installing pyenv several different ways (Homebrew, pyenv-installer, cloning from GitHub) and I have tried multiple versions (1.2.20, 1.2.19, 1.2.18). I always have the same problem.

---

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS Catalina 10.15.3
- [ ] OS architecture (e.g. amd64):
- [x] pyenv version: 1.2.20, 1.2.19, 1.2.18
- [x] Python version: 3.7.3
- [ ] C Compiler information (e.g. gcc 7.3): 
- [x] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

**Comment by joshfriend** [comment]
Please re-read the instructions in the readme and make sure you have added `pyenv init` to your shell

**Comment by djcunningham0** [comment]
Requesting to reopen. Sorry I didn't include that detail, but when I said I added the appropriate lines to ~/.bash_profile that includes `pyenv init`. Here are the last few lines of my `~/.bash_profile`:

```bash
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
```

I've also tried it without the if statement, and I've tried executing `eval "$(pyenv init -)"` directly from my shell. Still experiencing the same issue.

**Comment by ryanclark** [comment]
Seeing the same over here on a fresh installation of pyenv, `~/.pyenv/shims/python3` exists but `~/.pyenv/shims/python` doesn't.

![image](https://user-images.githubusercontent.com/7922109/91720826-a9cf3080-eb8f-11ea-84f4-487913865ce2.png)

`which python` -> `/usr/bin/python`
`which python3` -> `~/.pyenv/shims/python3`

This is at the end of `~/.zshrc`.

```bash
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```

**Comment by mprat** [comment]
Requesting a reopen here; seeing the same issue on a fresh installation of pyenv. Ubuntu 20.04, after activating a pyenv virtualenv `which python` doesn't link to anything

**Comment by native-api** [comment]
We need a debug trace that reproduces the problem as required by the issue template so tell if it's a real bug in Pyenv.

Does a `pyenv rehash` fix the problem?

Also check if there's `python` in `$PYENV_ROOT/versions/<your version>` -- if not, show the trace of the problematic version's installation.

**Comment by djcunningham0** [comment]
`pyenv rehash` does not fix the problem. There is *not* a `python` executable in `$PYENV_ROOT/versions/<your version>`.

I'm attaching the trace of the installation as requested. I captured stdout and stderr separately. Here are those logs: 
[pyenv_install_3.9.1.stdout.log](https://github.com/pyenv/pyenv/files/7256885/pyenv_install_3.9.1.stdout.log)
[pyenv_install_3.9.1.stderr.log](https://github.com/pyenv/pyenv/files/7256886/pyenv_install_3.9.1.stderr.log)

Here are the exact commands I ran:
```zsh
brew update
brew install pyenv > brew_install_pyenv.stdout.log 2>brew_install_pyenv.stderr.log
echo 'eval "$(pyenv init --path)"' >> ~/.zprofile
echo 'eval "$(pyenv init -)"' >> ~/.zshrc

# then I started a new shell
env PYENV_DEBUG=1 pyenv install -v 3.9.1 > pyenv_install_3.9.1.stdout.log 2>pyenv_install_3.9.1.stderr.log
pyenv global 3.9.1
```

After that, `which python` still returns `/usr/bin/python`. There is no python executable in `$HOME/.pyenv/shims` or `$HOME/.pyenv/versions/3.9.1/bin`.

Please let me know if you need any more information.

**Comment by djcunningham0** [comment]
@joshfriend @native-api Please review my previous comment with the build log attached and consider reopening the issue.

**Comment by native-api** [comment]
When running on a case-insensitive FS, Python's build erroneously produces `python.exe` instead of `python`.

The logic was introduced in https://github.com/python/cpython/commit/1999ef4973fb0e02872c2d970e9690061b65412d . apparently, it was intended as a temporary name due to being installed under a normal name, but apparently they never added that part of the logic...

**Comment by native-api** [comment]
The logic is present all the way since 2.2 so I guess we can add a workaround... if your system is actually an officially supported configuration.

**Comment by native-api** [comment]
Scratch that, it does install the executable under the correct name.

**Comment by native-api** [comment]
```
++(/usr/local/Cellar/pyenv/2.0.7/plugins/python-build/bin/python-build:1663): build_package_symlinklocal 'version_bin=/Users/Daniel/.pyenv/versions/3.9.1/bin/python3.[01;31m[K9[m[K'
```

Looks like you have forced Grep to output colors somehow, even when not outputting to a terminal. This is not supported.

**Comment by native-api** [comment]
Look for `GREP_OPTIONS` in your configuration and change `--color=always` to `--color=auto`.

**Comment by djcunningham0** [comment]
Great find, thank you! I was setting `GREP_OPTIONS="--color=always"`. I changed it to `GREP_OPTIONS="--color=auto"` and now pyenv is working correctly.
