### ISSUE TITLE
Pyenv Cannot Install python3 versions ≤3.5.0

### ISSUE THREAD

**Issue by dvfeinblum** [pyenv/pyenv#1688]
Hey folks; sorry if this has been reported before or is a known issue. I looked at open issues and tried doing some searching but as y'all are probably aware, there are quite a few open issues! I also tried asking in the gitter but didn't get an answer.

While working on a legacy project, I needed to use an older version of python (3.4.X) so I tried to install it using pyenv, but ran into openSSL complaints. I spent about a day debugging that issues, as well as trying to install 3.5.0, hoping that perhaps I could install that and my app would still work.

After that didn't work (and after reinstalling almost every piece of tech associated with using pyenv), I tried 3.6.0 and suddenly pyenv had no complaints or issues. Obviously, we really shouldn't be using an older version of python but thems the breaks.

Here are my details:
Platform Info: MacOS 10.14.6 (18G103)
Kernel Info: Darwin 18.7.0
Pyenv Version: 1.2.20
Python Version: ≤3.5.0
C Compiler: gcc 4.2.1
Gist Link to Verbose Logging [here](https://gist.github.com/dvfeinblum/085933e96164ffd9834a8df35ab48b53).

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04):
- [x] OS architecture (e.g. amd64):
- [x] pyenv version:
- [x] Python version:
- [x] C Compiler information (e.g. gcc 7.3): 
- [x] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

**Comment by HacKanCuBa** [comment]
Well, I'm not sure if its related but yesterday I tried installing cpython 3.7 but it explode (I'm on Debian testing). I think it's not exactly a pyenv issue but the problem resides in your (and mine!) OS libraries: older python version requires older libraries which your OS might no longer have.
Whereas this issue would not be solvable by pyenv, a nice workaround would be to list version lib deps and check your OS first, so it may guide you through the road of installing old libs in your OS. Yeah, this would mean a whole new big feature. And all in all, you may not be able to install them anyway so usually *my* way to go is use Docker (or podman, whichever containerization solution you prefer) for those cases.

Cheers!

**Comment by native-api** [comment]
Pyenv has ways to install older libraries if needed. You need to alter the corresponding install script in `plugins/python-build/share/python-build`. Search that dir for "openssl" for an example.

If that's a binary release, you may indeed be out of luck if it has hardcoded paths in it that now point to something else. That's why scripts for binary releases display a warning if your OS version is not what it was intended for.

**Comment by native-api** [comment]
-your-openssl-version-is-incompatible-with-the-python-version-youre-trying-to-install
