### ISSUE TITLE
Unable to install python 3.4.10 with pyenv

### ISSUE THREAD

**Issue by metinsenturk** [pyenv/pyenv#1705]
I am not able to install python 3.4.10 with `pyenv`, but I can install other versions. Below is the list of versions I am able to install.

```
 me@MacBook-Pro  ~  pyenv versions
* system (set by /Users/me/.pyenv/version)
  3.5.9
  3.7.3
  3.8.3
  3.8.5
```

I did the `brew upgrade` and after that installed the `pyenv`. I have python@3.8 installed with `brew` as a dependency of `pipenv` and `pipx`, and this python is added to my `.zshrc` script, if this means anything.
```
 me@MacBook-Pro  ~  brew list
autoconf		node			pkg-config		zsh
gdbm			openssl@1.1		pyenv			zsh-autosuggestions
gettext			pcre			python@3.8		zsh-syntax-highlighting
git			pcre2			readline
icu4c			pipenv			sqlite
ncurses			pipx			xz
```
 
I feel this issue can be related to #844, however, I don't have anything like `CLOCK_REALTIME` in my logs. It may also be related to #1688.

------

Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04):
```
System Software Overview:

  System Version:	macOS 10.15.7 (19H2)
  Kernel Version:	Darwin 19.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	        Normal
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	6:05

```
- [x] OS architecture (e.g. amd64):
```
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2
```
- [x] pyenv version:
```
pyenv 1.2.20
```
- [x] Python version:
```
Python 3.8.5
```
- [x] C Compiler information (e.g. gcc 7.3): 
```
Apple clang version 12.0.0 (clang-1200.0.26.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
- [x] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

https://gist.github.com/metinsenturk/0cb38a6db051c434cec96bef23610cbb

**Comment by JMMarchant** [comment]
I think it's related to [this](https://bugs.python.org/issue28676), which is a problem with Python itself on Mac OS X. It was patched in later versions of Python but I'm guessing 3.4.10 was too old to get the fix.

> Pushed for release in 2.7.13, 3.5.3, 3.6.0b4, and 3.7.0.

**Comment by ryansobol** [comment]
Also having a the same issue. Here's a link to my [build log](https://gist.github.com/ryansobol/6b0c7efc3edd98c41fe5f294da6cdd13).

**Comment by krizsx** [comment]
same problem, any solution ?

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/wiki/Common-build-problems#2-your-openssl-version-is-incompatible-with-the-python-version-youre-trying-to-install
