### ISSUE TITLE
Error installing pypy3.6-7.3.0

### ISSUE THREAD

**Issue by mnanduri** [pyenv/pyenv#1710]
Getting below error when installing on a mac. Any ideas?

mac1-mac:configs $ pyenv install -v pypy3.6-7.3.0
/var/folders/ky/wsqtllb13f9bdbnfkpdpg1qc0000gn/T/python-build.20201006143050.46758 /var/tmp/etc/ztpserver/files/configs
Downloading pypy3.6-v7.3.0-osx64.tar.bz2...
-> https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v7.3.0-osx64.tar.bz2
curl: (22) The requested URL returned error: 404
error: failed to download pypy3.6-v7.3.0-osx64.tar.bz2

BUILD FAILED (OS X 10.15.6 using 0000000000)

**Comment by fizyk** [comment]
pypy has moved it's development  as in this blogpost: https://morepypy.blogspot.com/2020/09/pypy-732-triple-release-python-27-36.html

They moved to https://foss.heptapod.net/pypy/pypy 
BUT the downloads are on python.org from what I see:

https://downloads.python.org/pypy/

**Comment by joshfriend** [comment]
fixed in v1.2.21
