### ISSUE TITLE
python-build: option to disable Homebrew library usage

### ISSUE THREAD

**Issue by uranusjr** [pyenv/pyenv#1715]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS Mojave
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 1.2.21
- [x] Python version: none
- [x] C Compiler information (e.g. gcc 7.3): clang-1200.0.32.2
- [x] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`
  * *(not relevent)*

Homebrew installs each version of a library under different subdirectories (named after the version), and only links the lib into place. [It also automatically removes old versions when installing new ones.](https://docs.brew.sh/FAQ#how-can-i-keep-old-versions-of-a-formula-when-upgrading) This makes it problematic to link against unversioned libraries (say readline), since the .so linked against at compile time may disappear at any time, causing the functionality to be broken once Homebrew packages are upgraded.

The proposal here is to introduce a way for users to choose not using Homebrew’s library when they’re found. It’s probably best if this can be done in a per-library basis (e.g. openssl can be used since it takes a lot of time to build and does not change version that often, while readline is less desired since it changes more often and is quite fast to build), but I wouldn’t mind needing to build everything from scratch, as long as Homebrew’s installation can be avoided.

**Comment by native-api** [comment]
Pyenv links against the "active" version of the library in `$(brew --prefix <formula>)` (which is typically `/usr/local/opt/<formula>`) which does _not_ change when upgrading the formula to a new version -- so an upgrade won't break anything.

**Comment by uranusjr** [comment]
The prefix does not change, but the *content* does, and that’s what matters. What makes matter worse is that CPython (or is it how pyenv builds CPython, I didn’t check) uses the fully resolved dynamic library path, so a minor version upgrade would break library load. I gave up one Homebrew entirely so maybe they’ve changed that since, but when I was using it `readline` and `ssl` version upgrades was a constant pain since I either needed to fish out the old .so files or re-compile all pyenv versions to link against the new .so files.

**Comment by native-api** [comment]
You can already disable Homebrew by deleting `brew` from `PATH` (or making it a no-op) this way or another. Or pass envvars with compiler flags to `pyenv install` to link against smth else.
But that won't fix your problem -- if you aren't getting deps from Homebrew -- where from then?

Moreover, there haven't been widespread similar reports or upvotes, so I suspect that you're just falling another victim to Homebrew having migrating from OpenSSL 1.0 to 1.1. See https://github.com/pyenv/pyenv/issues/1686 for that

**Comment by native-api** [comment]
Duplicate of #1686

**Comment by uranusjr** [comment]
> if you aren't getting deps from Homebrew -- where from then?

From python-build. It automatically fetches and builds some of the dependencies if Homebrew is not found.

> Moreover, there haven't been widespread similar reports or upvotes, so I suspect that you're just falling another victim to Homebrew having migrated from OpenSSL 1.0 to 1.1.

Homebrew migrating to OpenSSL 1.1 is the symptom, not the cause. Fundamentally, python-build should provide an ergonomical way to override detection heuristic, because every heuristic can run into edge cases. In fact, the main issue I have is not with OpenSSL, but Readline. Homebrew likes to upgrade Readline, and whenever it bumps a major version, the `readline` module in a python-build-compiled Python installation is broken and needed to be relinked or recompiled. It is extremely annoying.

Moreover, neither of your suggestions resolve the request.

> deleting `brew` from `PATH` (or making it a no-op)

This disables all Homebrew packages, but I want to only disable some libraries. Specifically, OpenSSL takes forever to build from source, so I want python-build to still use the Homebrew for that, but not Readline.

> pass envvars with compiler flags to `pyenv install` to link against smth else

This means I can't rely on python-build's auto-fetch feature on those dependencies and need to manage them myself. I guess that is a solution, but far from perfect (it's essentially punting the issue).

> Moreover, there haven't been widespread similar reports or upvotes

Because people tend to attemp fixing this on the Homebrew side (don't let Homebrew upgrade Readline). But freezing Readline version is not a very good solution if… well, you actually want the new versions in some cases. (And unlike the case with OpenSSL, CPython actually works fine with those new Readline versions).

Here are some of the people having issues with Readline:

https://superuser.com/questions/1419104
https://stackoverflow.com/questions/54776971
https://www.py4u.net/discuss/207906
https://linuxtut.com/en/546a7945b0ce566a80ee/

Search `pyenv readline image not found` on any search engine for more.

Please consider reopen this issue since while #1686 is a syompton to this, it is fundamentally a different issue.

**Comment by native-api** [comment]
> Here are some of the people having issues with Readline:

Okay, so this only happens on _major_ version updates. Not on _every_ update as you claimed.

This we can consider, but we need to focus on the core problem and consider all possible solutions, not only this one.

**Comment by native-api** [comment]
Please open a new issue focusing on the problem rather than a specific solution. Do specify:

* How often does this happen? (Please stick to the facts. What exact updates break Pyenv-installed Pythons? How often do they happen and are expected to happen going further?)
* How many users are affected?
* What solutions have been considered/proposed? How are they inadequate? (Link to previous discussions when referring.)
