### ISSUE TITLE
BUILD FAILED (Ubuntu 19.04 using python-build 1.2.21). ERROR: ssl not compiled, while it is installed

### ISSUE THREAD

**Issue by Stanislavx** [pyenv/pyenv#1717]
Ubuntu 19.04
openssl version 
OpenSSL 1.1.1b  26 Feb 2019
on trying      sudo apt-get install zlib1g-dev:
zlib1g-dev of the newest version is installed: (1:1.2.11.dfsg-1ubuntu2)
Made everything according to: https://realpython.com/intro-to-pyenv/
and this: https://github.com/pyenv/pyenv/wiki
last lines of .bashrc:
export PATH="/home/user/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

whatever version I try to install, get the outcome like this:
root@user-Lenovo-ideapad-330S-15IKB:~# pyenv install 3.6.4
Downloading Python-3.6.4.tar.xz...
-> https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tar.xz
Installing Python-3.6.4...
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?
Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems
BUILD FAILED (Ubuntu 19.04 using python-build 1.2.21)
Inspect or clean up the working tree at /tmp/python-build.20201015204036.8696
Results logged to /tmp/python-build.20201015204036.8696.log
Last 10 log lines:
	esac; \
	 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0

Thank you for the help

**Comment by native-api** [comment]
Missing diagnotic info as required by the issue template.
So can only suggest to do as the message says and check the wiki.
