### ISSUE TITLE
How to compile Python and solve the "This program needs access to the screen. Please run with a Framework build of python" error

### ISSUE THREAD

**Issue by andreamoro** [pyenv/pyenv#1720]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Description
- Mac OS X 10.15.7 
- pyenv version:  1.2.21
- Python version: the problem is here
- C Compiler information (e.g. gcc 7.3): 12.0.0

I'm trying to build an app that contains a GUI, based on wx. However, by the time I reference the library and create the app itself, the compiler quits returning the following message:
```
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
```

I've built a fresh Python 3.9.0 into the pyenv root folder both manually as well as with the pyenv as detailed [here](https://github.com/pyenv/pyenv/issues/99) without success.

Is there anybody that has faced a similar issue and know how to solve?

Thanks

**Comment by native-api** [comment]
1st in Google on _"Please run with a Framework build of python":_

https://stackoverflow.com/questions/48531006/wxpython-this-program-needs-access-to-the-screen

https://wiki.wxpython.org/wxPythonVirtualenvOnMac

**Comment by hcientist** [comment]
hey there team, I keep seeing these same links to the ancient days of wxpython, but none what's mentioned on https://wiki.wxpython.org/wxPythonVirtualenvOnMac seems remotely recent (eg python2??) anyone know for python3?
