### ISSUE TITLE
Installing pypy3 on macOS 10.13.6: "dyld: Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib"

### ISSUE THREAD

**Issue by amotl** [pyenv/pyenv#1721]
Hi there,

first things first: Thank you so much for conceiving and maintaining pyenv. We found an issue with installing pypy3 through pyenv but also have been able to find a solution we would like to share with you.

With kind regards,
Andreas.

### Environment
- macOS 10.13.6 (High Sierra)
- pyenv 1.2.21

### Description
We had problems installing pypy3 through pyenv by using `pyenv install -v pypy3.6-7.3.1`. It croaked with
```
Installing pypy3.6-v7.3.1-osx64...
/usr/local/Cellar/pyenv/1.2.21/plugins/python-build/bin/python-build: line 1600:  9348 Abort trap: 6           "$PYTHON_BIN" -c "import $1" > /dev/null 2>&1
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
/usr/local/Cellar/pyenv/1.2.21/plugins/python-build/bin/python-build: line 1600:  9349 Abort trap: 6           "$PYTHON_BIN" -c "import $1" > /dev/null 2>&1
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
/usr/local/Cellar/pyenv/1.2.21/plugins/python-build/bin/python-build: line 1609:  9350 Abort trap: 6           "$PYTHON_BIN" -c "import $1" > /dev/null 2>&1
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?
```

despite having all prerequisites satisfied. Also, the wiki page about [common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems) didn't help.

However, invoking `pypy3` from the intermediary build directory gave us some idea.
```
$ /var/folders/06/w9pzygdj7vx53n_0l9q_lhph0000gn/T/python-build.20201023114741.6523/pypy3.6-v7.3.1-osx64/bin/pypy3
dyld: Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib
  Referenced from: /private/var/folders/06/w9pzygdj7vx53n_0l9q_lhph0000gn/T/python-build.20201023114741.6523/pypy3.6-v7.3.1-osx64/bin/libpypy3-c.dylib
  Reason: image not found
Abort trap: 6
```

### Workaround
@freeslugs reported at https://github.com/platformio/platform-lattice_ice40/issues/7#issuecomment-621462843:

> This will do the trick
>
> ```
> cd /usr/local/opt/libffi/lib
> ln -s libffi.7.dylib libffi.6.dylib
> ```

Thank you so much!

### Solution

@bertjwregeer added at https://github.com/pyenv/pyenv/issues/1721#issuecomment-734464301:
> The major version from libffi was changed, generally it is not a good idea to symlink that to an older major version because there are likely incompatibilities in the API's.
>
> PyPy should be recompiled against the newer version of libffi or include the library in its download.

**Comment by cvicente** [comment]
THANK YOU!!!

**Comment by guyarad** [comment]
Thanks for this issue! saved me!
I was trying to add this one to the Wiki to common build errors. How do I do that? couldn't find a way to create a PR against the Wiki repo.

**Comment by bertjwregeer** [comment]
The major version from libffi was changed, generally it is not a good idea to symlink that to an older major version because there are likely incompatibilities in the API's.

pypy should be recompiled against the newer version of libffi or include the library in its download.

**Comment by amotl** [comment]
Thanks Bert, I've updated the topmost thread item to include your suggestion and downgraded my suggestion to be just a workaround and not a solution.

**Comment by freeslugs** [comment]
Oh wow I had no idea my random comment on some homebrew error was helping people. Glad y'all found it and found it helpful! Even if it's just a workaround :P 

Happy Thanksgiving, grateful for this community :)

**Comment by josix** [comment]
Thank you all guys for the information. It helps a lot.

**Comment by native-api** [comment]
Precompiled versions are precompiled for a specific environment.

The only thing that Pyenv can do if the current environment is different is issue a warning such as what the `require_distro` command does.
