### ISSUE TITLE
`/usr/bin/env: ‘bash\r’: No such file or directory`: Incompatible line-endings (WSL?)

### ISSUE THREAD

**Issue by alexpovel** [pyenv/pyenv#1725]
Hi,

running on a Debian inside WSL2, I ran into the following error upon installation:

```bash
$ pyenv --help
/usr/bin/env: ‘bash\r’: No such file or directory
```

This happened both using the [installer](https://github.com/pyenv/pyenv-installer) as well as, after starting over, the [manual steps](https://github.com/pyenv/pyenv#basic-github-checkout). The installations themselves ran fine.

The issue seems to be no `LF` Unix-style line-endings, but `CR+LF` DOS-style line-endings (`\r` as `CR`). This leads to `bash\r` not being found in some Shell script's shebang.

Is this maybe specific to WSL? In this case, the issue is maybe too specific. On the other hand, plenty of people use WSL nowadays.

For now, I solved it by [replacing all carriage return characters (`\r`) with nothing](https://stackoverflow.com/a/29045187/11477374):

```bash
$ pyenv --version
/usr/bin/env: ‘bash\r’: No such file or directory
$ cd ~/.pyenv && find . -type f | xargs sed -i $'s/\r$//' && cd -
$ pyenv --version
pyenv 1.2.21
```

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): WSL2: Debian bullseye/sid
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 1.2.21
- [x] Python version: 2.7.18/3.8.6
- [x] C Compiler information (e.g. gcc 7.3): gcc (Debian 9.3.0-18) 9.3.0
- [x] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

**Comment by bromps** [comment]
I'm assuming the output of `echo $PYENV_SHELL` is "bash\r". Can you confirm this?

**Comment by alexpovel** [comment]
This is installed on `zsh` and the output of that command is `zsh`.

**Comment by thec0sm0s** [comment]
I am having the same issue as well. Even running it using `~/.pyenv/bin/pyenv --help` spits out the same issue. What could be possibly wrong? Does the `\r` char exists in the pyenv source itself or somehow my environment/git configs messes it up while cloning it?

**Comment by thec0sm0s** [comment]
Just disovered why it was happening for me in first place. So somehow my value of core.autocrlf was set to true. I changed it to true   using `git config --global core.autocrlf false` and made git clone again and it worked.

**Comment by alexpovel** [comment]
Also worked for me. The same issue has since occurred with other `git clone`-based installations. So possibly a wide-spread issue for all vanilla WSL2-setups, but nothing `pyenv` can do anything about, sorry to bother.

**Comment by joric** [comment]
Check your path, echo $PATH. WSL2 normally imports Windows path there. To fix this create file `/etc/wsl.conf` in WSL2:
```bash
[interop]
appendWindowsPath = false
```
Then restart WSL2 with `wsl --shutdown`
Then check your path is shorter now and doesn't include any Windows dependencies:
`echo $PATH`

Worked for me.

Also see [How to remove Windows paths from WSL path](https://gist.github.com/ilbunilcho/4280bd55a10cefef75e74986b6bff936)

**Comment by fsarter** [comment]
I hit the same issue, after install nodejs and npm, just restart my wsl with `wsl --shutdown` solved the issue, you can try this.

**Comment by arpneto2005** [comment]
Thanks fsarter

**Comment by hellodit** [comment]
Still have this problem, I've used @fsarter steps but keeps showing @joric approach also fails in my device. 

Been using WSL2 with ubuntu 20 distro
```
╰─○ pyenv             
/usr/bin/env: ‘bash\r’: No such file or directory
```

**Comment by dredom** [comment]
I ran dos2unix on cryptr.bash and that resolved the error.  (I had copied it from Windows into my WSL2 session.)

**Comment by sunnyokoroawa** [comment]
@fsarter your approach worked for me.

I ran the 2 commands to install npm and nodejs

sudo apt update
sudo apt install nodejs npm

After which I restarted my WSL (using win 10 PC) using the cmd below on Windows Power shell running as an administrator

wsl --shutdown

**Comment by ShivamTyagi12345** [comment]
> sudo apt install nodejs npm

This worked Thanks

**Comment by Mamdouh93Murad** [comment]
> @fsarter your approach worked for me.
> 
> I ran the 2 commands to install npm and nodejs
> 
> sudo apt update sudo apt install nodejs npm
> 
> After which I restarted my WSL (using win 10 PC) using the cmd below on Windows Power shell running as an administrator
> 
> wsl --shutdown

Thanks, that solved it for me

**Comment by iuriguilherme** [comment]
This is happening because pyenv is defaulting to installing bash scripts with carriage returns (windows-style line endings), even on linux boxes. So no, `wsl --shutdown` is not solving or fixing anything

**Comment by iuriguilherme** [comment]
Here something that actually works and fixes the problem (need [dos2unix](https://sourceforge.net/projects/dos2unix/)):

```bash
find ${HOME}/.pyenv -name '*.sh' -exec dos2unix '{}' \;
```

**Comment by native-api** [comment]
@iuriguilherme Pyenv has no files with the `.sh` extension (except a single old unused script).
You must be dealing with some other product.

**Comment by iuriguilherme** [comment]
```bash
iuri@tartaruga:~$ find ~/.pyenv -name '*.sh'
/home/iuri/.pyenv/plugins/pyenv-virtualenv/install.sh
/home/iuri/.pyenv/plugins/pyenv-which-ext/install.sh
/home/iuri/.pyenv/plugins/python-build/install.sh
/home/iuri/.pyenv/plugins/pyenv-installer/bin/download-pyenv-package.sh
/home/iuri/.pyenv/plugins/pyenv-doctor/gen.sh
```

Yes it has, and that is what's causing this issue

Maybe the bash scripts in libexec should pass through dos2unix as well just to make sure

**Comment by ZahidGalea** [comment]
> For now, I solved it by [replacing all carriage return characters (`\r`) with nothing](https://stackoverflow.com/a/29045187/11477374):
> 
> ```shell
> $ pyenv --version
> /usr/bin/env: ‘bash\r’: No such file or directory
> $ cd ~/.pyenv && find . -type f | xargs sed -i $'s/\r$//' && cd -
> $ pyenv --version
> pyenv 1.2.21
> ```

Thanks for this

**Comment by RikSchoonbeek** [comment]
I had the same issue, probably due to using WSL, and the command that @alexpovel suggested fixed it for me:

`cd ~/.pyenv && find . -type f | xargs sed -i $'s/\r$//' && cd -`

Also asked ChatGPT to explain what this command does, before I executed it. The summary of that:

The command changes the current directory to ~/.pyenv, searches for regular files within that directory and its subdirectories, removes carriage return characters at the end of each line in those files using the sed command, and then changes the current directory back to the previous one. This command is commonly used to convert text files from DOS/Windows format to Unix format by removing the carriage return characters.

**Comment by ngraymon** [comment]
Same issue, and same fix for version 2.3.25. 
```
$ pyenv --version
/usr/bin/env: ‘bash\r’: No such file or directory
$ cd ~/.pyenv && find . -type f | xargs sed -i $'s/\r$//' && cd -
$ pyenv --version
pyenv 2.3.25
```

Running wsl `1.2.5.0` with Ubuntu `20.04.6` (focal).

**Comment by inspire22** [comment]
This should probably be reopened since it's a problem for a significant number of new users and basically makes the whole idea of a pyenv "installer" worthless imo since debugging it takes so long.

**Comment by flatline-studios** [comment]
> This should probably be reopened since it's a problem for a significant number of new users and basically makes the whole idea of a pyenv "installer" worthless imo since debugging it takes so long. Git's autoclrf is moderately common for folks developing cross-platform (i.e. suffering with windows) so pyenv should somehow disable it when installing or deal with it afterwards.

This ~~could~~ **should** absolutely be implemented in to the shell install script, and reset to its initial value after pyenv has been installed.
