### ISSUE TITLE
error: implicit declaration of function 'getentropy' is invalid

### ISSUE THREAD

**Issue by salmanul** [pyenv/pyenv#1729]
### Description
- Mac OS Catalina 10.15.7
- OS architecture : x86_64
- pyenv version: 1.2.21
- Python version: 2.7.1,3.5.2
- C Compiler information (e.g. gcc 7.3): gcc 4.2.1 , Apple clang version 12.0.0
- verbose build log as gist : https://gist.github.com/salmanul/010895e52b8267dfcbab3df3e0f3bc0d

unable to install python older versions using pyenv (3.5.2, 2.7.1), installation failed due to python build error. see the attached build logs for more info.

**Comment by will-peloton** [comment]
I have the same problem. been googling for hours...

**Comment by ARUNKUMARE** [comment]
I have same problem, not found a solution yet. My machine runs with Mac OS Catalina 10.15.6

**Comment by JMMarchant** [comment]
That was a bug in the actual CPython code that was fixed in 2.7.13 and 3.5.3 (see [here](https://bugs.python.org/issue28676); don't know if there's a workaround for pyenv but hopefully this helps people hone in on the issue.

**Comment by orip** [comment]
Here's a patch and a workaround to build with pyenv - basically the same as the fix for 2.7.x
https://gist.github.com/orip/00142a498cf6d0c536b5d38771ad6249

**Comment by salmanul** [comment]
> That was a bug in the actual CPython code that was fixed in 2.7.13 and 3.5.3 (see [here](https://bugs.python.org/issue28676)); don't know if there's a workaround for pyenv but hopefully this helps people hone in on the issue.

**Comment by NoraGithub** [comment]
> ted

may i ask something about this issue? as a result, there's no way to build the specific version of python on related osx system ?
