### ISSUE TITLE
ERROR: No matching distribution found for X_PACKAGE on macOS Big Sur (no issues with non-pyenv python installs)

### ISSUE THREAD

**Issue by ben-xD** [pyenv/pyenv#1735]
Dear friends :)

When using python 3.8.6 installed by pyenv, no packages are found for tensorflow. These can be found in the normal 
(non-pyenv) python 3.8.6. See screenshot (left is pyenv, right is python3.8.6 installed from python's website). Also happens for all 3.7.6, 3.8.0, 3.8.1, 3.8.2 etc.

![Screenshot 2020-11-16 at 19 16 41](https://user-images.githubusercontent.com/24711048/99298298-6a84b780-2841-11eb-82a8-bb01e278f385.png)

I installed python using the temporary workaround: `LDFLAGS="-L$(xcrun --show-sdk-path)/usr/lib" pyenv install 3.8.6`

### Description
Platform information (e.g. Ubuntu Linux 16.04): macOS Big Sur 11.0.1 (20B28)
OS architecture (e.g. amd64): amd64 (intel i7-10700K)
pyenv version: pyenv 1.2.21
Python version: 3.8.6 (occurs for other python versions too)
C Compiler information (e.g. gcc 7.3): clang 12

Build log was generated with `yes | env PYENV_DEBUG=1 LDFLAGS="-L$(xcrun --show-sdk-path)/usr/lib" pyenv install -v 3.8.6 2&>1 > output.txt`

[output.txt](https://github.com/pyenv/pyenv/files/5549208/output.txt)
and as a gist (is this what you meant?): https://gist.github.com/ben-xD/a214b0f146cb3c34406578b689835fd9

**Comment by bertjwregeer** [comment]
This is because macOS Big Sur is a new major version upgrade and is now at version 11.0, and according to pip and friends is no longer backwards compatible with 10.x.

You will have to wait for people to upload new wheels that are built for macOS Big Sur.

**Comment by nwh** [comment]
Might be worth trying `pip install --upgrade pip setuptools wheel` in the `pyenv` managed Python.

**Comment by ben-xD** [comment]
@bertjwregeer Thanks for explaining, but I'm not sure why it only doesn't work in pyenv though. Are you suggesting pip is checking dependencies and preventing me from installing? `pip install tensorflow==2.3.1 --no-dependencies` doesn't solve it either. I think when you say "people", you mean the developers of the library (not its dependencies?). In that case, it should not work outside of pyenv either.

Thanks for the suggestion @nwh, it didn't work unfortunately.

**Comment by bertjwregeer** [comment]
@ben-xD if you look at the tensorflow download page on PyPI you can see what platforms they have published wheels for: https://pypi.org/project/tensorflow/#files

The `pyenv` installed Python is compiled for the latest version of macOS, which identifies itself as 11.0. Whereas the Python installed by brew has been built with a macOS deployment target of 10.14.

If you want, you can try this:

```
env MACOS_DEPLOYMENT_TARGET=10.14 pyenv install 3.8.6
```

I believe that this will build the pyenv version of Python with the deployment target set to 10.14 at which point you will be able to install tensorflow.

**Comment by ben-xD** [comment]
Oh thank you for the explanation. I was looking at the `cp38`, instead of the `macosx_10_14`. I guess this would've been a problem with Catalina too then, because there is no `macosx_10_15` on this files list.

**Comment by bertjwregeer** [comment]
@ben-xD the 10_xx are backwards compatible.

So a deployment target of 10_15 can install 10_14 binary wheels without issues. You just can't go the other way. A python compiled for 10_9 can't run binary wheels for 10_14.
