### ISSUE TITLE
BUILD FAILED (OS X 11.0.1 using python-build 20180424)

### ISSUE THREAD

**Issue by 0xSeanll** [pyenv/pyenv#1738]
I ran `pyenv install 3.6.9` and here is what I got

```
Status Legend:
(OK):download completed.
/var/folders/39/f_dqz3415x31mq7x8r9hmnww0000gn/T/python-build.20201122092410.69684/Python-3.6.9 /var/folders/39/f_dqz3415x31mq7x8r9hmnww0000gn/T/python-build.20201122092410.69684 ~
checking build system type... x86_64-apple-darwin20.1.0
checking host system type... x86_64-apple-darwin20.1.0
checking for python3.6... no
checking for python3... python3
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... darwin
checking for --without-gcc... no
checking for --with-icc... no
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/var/folders/39/f_dqz3415x31mq7x8r9hmnww0000gn/T/python-build.20201122092410.69684/Python-3.6.9':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.
```

and config.log

```
## ----------- ##
## Core tests. ##
## ----------- ##

configure:2801: checking build system type
configure:2815: result: x86_64-apple-darwin20.1.0
configure:2835: checking host system type
configure:2848: result: x86_64-apple-darwin20.1.0
configure:2878: checking for python3.6
configure:2908: result: no
configure:2878: checking for python3
configure:2894: found /usr/local/bin/python3
configure:2905: result: python3
configure:3005: checking for --enable-universalsdk
configure:3052: result: no
configure:3075: checking for --with-universal-archs
configure:3090: result: no
configure:3240: checking MACHDEP
configure:3449: result: darwin
configure:3470: checking for --without-gcc
configure:3493: result: no
configure:3496: checking for --with-icc
configure:3516: result: no
configure:3640: checking for gcc
configure:3667: result: clang
configure:3896: checking for C compiler version
configure:3905: clang --version >&5
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
configure:3916: $? = 0
configure:3905: clang -v >&5
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
configure:3916: $? = 0
configure:3905: clang -V >&5
clang: error: unsupported option '-V -Wno-objc-signed-char-bool-implicit-int-conversion'
clang: error: no input files
configure:3916: $? = 1
configure:3905: clang -qversion >&5
clang: error: unknown argument '-qversion'; did you mean '--version'?
clang: error: no input files
configure:3916: $? = 1
configure:3936: checking whether the C compiler works
configure:3958: clang -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include   -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl@1.1/include -I/Users/democles/.pyenv/versions/3.6.9/include  -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl@1.1/lib -L/Users/democles/.pyenv/versions/3.6.9/lib  conftest.c  >&5
clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=11.0'
configure:3962: $? = 1
configure:4000: result: no
configure: failed program was:
| /* confdefs.h */
| #define _GNU_SOURCE 1
| #define _NETBSD_SOURCE 1
| #define __BSD_VISIBLE 1
| #define _BSD_TYPES 1
| #define _DARWIN_C_SOURCE 1
| #define _XOPEN_SOURCE 700
| #define _XOPEN_SOURCE_EXTENDED 1
| #define _POSIX_C_SOURCE 200809L
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:4005: error: in `/var/folders/39/f_dqz3415x31mq7x8r9hmnww0000gn/T/python-build.20201122092410.69684/Python-3.6.9':
configure:4007: error: C compiler cannot create executables
See `config.log' for more details
```

Guess something is wrong with clang compiler. Any help is appreciated.

**Comment by 0xSeanll** [comment]
So, I solved this by myself.

Previously I was using Xcode Command Line Tools 12.2 (that corresponds to clang 11.0.3) and the problem occurred. After I updated to 12.3 Beta (clang 12.0.0), the problem has gone. However, the problems mentioned in #1737 ensued.

**Comment by ewypych** [comment]
I faced the same issue. Installing [XCode Command Line Tools 12.3 Beta](https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_12.3_beta/Command_Line_Tools_for_Xcode_12.3_beta.dmg) helped, but I cannot install Python `3.7.X` – it works with `3.8.X`, but also I needed to add the following exports before installing:

```shell
$ export LDFLAGS="-L/usr/local/opt/zlib/lib"
$ export CPPFLAGS="-I/usr/local/opt/zlib/include"
```

**Comment by Kjaer** [comment]
Xcode Command Line Tools 12.3 Release Candidate available to download now. FYI

**Comment by brntsllvn** [comment]
This post helped me... https://apple.stackexchange.com/a/375535

re-installing xcode command line tools should fix:
```
$ sudo rm -rf /Library/Developer/CommandLineTools
$ xcode-select --install
$ /usr/bin/xcodebuild -version
```
xcode-select version 2384. as of this writing

**Comment by disciture** [comment]
Doing `export`s such as 
```
export LDFLAGS="-L/usr/local/opt/zlib/lib"
export CPPFLAGS="-I/usr/local/opt/zlib/include"
```
and others suggested elsewhere did not work for me.

I followed @brntsllv with
```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
/usr/bin/xcodebuild -version
```
but the last command resulted in
```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```
This led me to [this other issue](https://github.com/nodejs/node-gyp/issues/569) which suggested
```
sudo xcode-select --switch /Library/Developer/CommandLineTools
```
and now `pyenv install 3.9.1` went through without a problem.

I suspected that this last command is the only thing I needed to have done.

**Comment by drinkbeer** [comment]
`pyenv install 3.6.8` still fails in my machine.

**Comment by RomaA2000** [comment]
BUILD FAILED (OS X 11.2.3 using python-build 20180424)
pyenv install 3.8.5 still fails on mac

**Comment by Ruslan-Skira** [comment]
pyenv install 3.6.9 still fails in my machine.

**Comment by mikkhait** [comment]
Just to keep this rolling

`~ xcodebuild -version
Xcode 12.4
Build version 12D4e`

`pyenv install 3.9.1`

and 

`BUILD FAILED (OS X 11.2.3 using python-build 20180424)`

**Comment by Ruslan-Skira** [comment]
> Just to keep this rolling
> 
> `~ xcodebuild -version Xcode 12.4 Build version 12D4e`
> 
> `pyenv install 3.9.1`
> 
> and
> 
> `BUILD FAILED (OS X 11.2.3 using python-build 20180424)`

How I found info that problems occur because I use Mac on M1 chip. And I do not use Rosseta. 
I started working through Docker. It is not convenient but maybe in the future on the  project will be a new Python .
Thank you for your answer.

**Comment by Temirtator** [comment]
@drinkbeer did you solve this issue?

**Comment by Temirtator** [comment]
I found a solutions from this issue. Hope will be helpful

https://github.com/pyenv/pyenv/issues/1643

**Comment by dulcineapena1** [comment]
I am unable to install any python version with pyenv and homebrew....

OSX 11.0.1 Big Sur
I got 
```
configure: error: Unexpected output of 'arch' on OSX
make: *** No targets specified and no makefile found.  Stop.

BUILD FAILED (OS X 11.0.1 using python-build 1.2.24.1)
```

**Comment by ghost-develop** [comment]
I'm unable to installl any version of Python. Im at a loss!

```
BUILD FAILED (OS X 11.3 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/tb/v22mjktd65n_9m2wn446l57c0000gn/T/python-build.20210429103055.74457
Results logged to /var/folders/tb/v22mjktd65n_9m2wn446l57c0000gn/T/python-build.20210429103055.74457.log

Last 10 log lines:
checking size of _Bool... 1
checking size of off_t... 8
checking whether to enable large file support... no
checking size of time_t... 8
checking for pthread_t... yes
checking size of pthread_t... 8
checking size of pthread_key_t... 8
checking whether pthread_key_t is compatible with int... no
configure: error: Unexpected output of 'arch' on OSX
```

**Comment by bhushanyavagal** [comment]
Same issue with me! Please help

`➜  ~/Desktop/Projects/my_webapp pyenv install 3.9.0
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Installing Python-3.9.0...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
^C
BUILD FAILED (OS X 11.3.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/1p/86ttk8cd03n7f9p0q25yfzv40000gn/T/python-build.20210511000700.93359
Results logged to /var/folders/1p/86ttk8cd03n7f9p0q25yfzv40000gn/T/python-build.20210511000700.93359.log

Last 10 log lines:
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include   -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal  -I. -I./Include -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/Users/bhushan/.pyenv/versions/3.9.0/include -I/usr/local/opt/zlib/include -I/usr/local/opt/bzip2/include -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/Users/bhushan/.pyenv/versions/3.9.0/include -I/usr/local/opt/zlib/include -I/usr/local/opt/bzip2/include  -DPy_BUILD_CORE -I. -o Python/importdl.o ./Python/importdl.c
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include   -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal  -I. -I./Include -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/Users/bhushan/.pyenv/versions/3.9.0/include -I/usr/local/opt/zlib/include -I/usr/local/opt/bzip2/include -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/Users/bhushan/.pyenv/versions/3.9.0/include -I/usr/local/opt/zlib/include -I/usr/local/opt/bzip2/include  -DPy_BUILD_CORE \
		-DPLATLIBDIR='"lib"' \
		-o Python/initconfig.o ./Python/initconfig.c
make: *** [Python/hamt.o] Interrupt: 2
make: *** [Python/initconfig.o] Interrupt: 2
make: *** [Objects/unicodeobject.o] Interrupt: 2
make: *** wait: Interrupted system call.  Stop.
make: *** Waiting for unfinished jobs....`

**Comment by purneshgali** [comment]
For me (OSX 11.2), it was the Python version that fixed the issue. 3.5.x or 3.6.x resulted in the same error, but 3.8.8 fixed the issue. 3.9.x worked as well, but something else I needed isn't supported so settled on 3.8.8

**Comment by tatianafrank** [comment]
None of the above solutions worked for me, trying to install 3.7.1 and getting 
`BUILD FAILED (OS X 11.2 using python-build 20180424)`

**Comment by Viswahs** [comment]
For me 
BUILD FAILED (OS X 11.2 using python-build 20180424)

**Comment by Jacksonluang** [comment]
For me

Installing Python-3.8.0...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 11.4 using python-build 20180424)

**Comment by Jacksonluang** [comment]
> For me
> 
> Installing Python-3.8.0...
> python-build: use readline from homebrew
> python-build: use zlib from xcode sdk
> 
> BUILD FAILED (OS X 11.4 using python-build 20180424)

This is for me working!!
> pyenv install --patch 3.8.3 < <(curl -sSL https://github.com/python/cpython/commit/8ea6353.patch)

**Comment by wongpenghong** [comment]
for me, still getting error

installing Python-3.6.9
`BUILD FAILED (OS X 11.4 using python-build 2.0.4)`

**Comment by ricefice** [comment]
I had to use python 3.7: ```python3 -m pip install virtualenv```

**Comment by romcab** [comment]
still getting error. below is my setup.

HOMEBREW_VERSION: 3.2.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 09b7ab2c1de3ab32f385aac922b2cd644fdd7c79
Last commit: 34 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2238dbfcab84adab4981c1fc3bac240796ee2d5e
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 13.0.0 build 1300
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-x86_64
CLT: 13.0.0.0.1.1630607135
Xcode: 13.0



pyenv 2.1.0-7-g88c34049


Logs.
BUILD FAILED (OS X 11.6 using python-build 2.1.0-7-g88c34049)

Inspect or clean up the working tree at /var/folders/0b/f0z5stys5537871_70d4gsjm0000gn/T/python-build.20211013055652.41562
Results logged to /var/folders/0b/f0z5stys5537871_70d4gsjm0000gn/T/python-build.20211013055652.41562.log

Last 10 log lines:
	if test $? -ne 0 ; then \
		echo "generate-posix-vars failed" ; \
		rm -f ./pybuilddir.txt ; \
		exit 1 ; \
	fi
 CC='clang' LDSHARED='clang -bundle -undefined dynamic_lookup -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/romcabral/.pyenv/versions/3.10.0/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/zlib/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/romcabral/.pyenv/versions/3.10.0/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/zlib/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib  ' OPT='-DNDEBUG -g -fwrapv -O3 -Wall' 	_TCLTK_INCLUDES='' _TCLTK_LIBS='' 	./python.exe -E ./setup.py  build
running build
running build_ext
error: [Errno 13] Permission denied: '/tmp/_osx_support.51044'
make: *** [sharedmods] Error 1

**Comment by btilongnguyen** [comment]
Installing Python 3.8.10 works in my Apple M1 Mac.

**Comment by juliabulia245** [comment]
In case it helps anyone else, I ran `pyenv install 3.7.3` and received the following error on my 2020 Apple M1 MacBook Pro running Monterey:
```
python-build: use zlib from xcode sdk
BUILD FAILED (OS X 12.0.1 using python-build 20180424)
```

I tried `pyenv install 3.8.10` after reading @btilongnguyen's comment, and that was successful!

**Comment by AasthaSinha2002** [comment]
This worked for 3.9.1 as you mentioned but still facing issues with 3.8.7, if you have a solution do let me know

**Comment by thomasender** [comment]
Having the same issue. BigSur 11.6.1
Did try to update xcode but no success installing python 3.8.1.
Anyone still on this issue?

**Comment by siddhant-pradhan** [comment]
I'm having the same issue on BigSur 11.6

**Comment by thomasender** [comment]
For MacOs BigSur users, I managed to get it to work by setting the python version for the current shell session via `asdf shell python 3.8.11 `.

**Comment by aysjkn-meli** [comment]
> For MacOs BigSur users, I managed to get it to work by setting the python version for the current shell session via `asdf shell python 3.8.11 `.

At MacOS BigSur, I need python 3.7.x and doesn't works... =[

**Comment by dingyunxing** [comment]
For MacOs BigSur `version 11.6.3` users, I am still getting trouble to install python 3.6.X

**Comment by WDuan-Poppulo** [comment]
for Mac M1, I am still getting the below error for pyenv install 3.7.7

BUILD FAILED (OS X 11.6 using python-build 20180424)

**Comment by FernandoLuizNemeChibli** [comment]
Isn't there any clean solution for that?

**Comment by shriyanshk128T** [comment]
This is what worked for me.

- sudo rm -rf /Library/Developer/CommandLineTools (This step is to remove the CLT)
- xcode-select --install (Reinstall xcode)
- /usr/bin/xcodebuild -version (I tried this it gave me an error)
- so I did this - sudo xcode-select --switch /Library/Developer/CommandLineTools
- Final step => pyenv install --patch 3.6.5 < <(curl -sSL https://github.com/python/cpython/commit/8ea6353.patch)

It seems after reinstalling the CLT System Update Wants me to install CLT for XCode 13.2, 13.3, and 13.4 but I haven't updated that yet. 

I was trying to install python 3.6.5 on macOS Monterey version 12.4. Hopefully it helps.

**Comment by dingyunxing** [comment]
> This is what worked for me.
> 
> * sudo rm -rf /Library/Developer/CommandLineTools (This step is to remove the CLT)
> * xcode-select --install (Reinstall xcode)
> * /usr/bin/xcodebuild -version (I tried this it gave me an error)
> * so I did this - sudo xcode-select --switch /Library/Developer/CommandLineTools
> * Final step => pyenv install --patch 3.6.5 < <(curl -sSL https://github.com/python/cpython/commit/8ea6353.patch)
> 
> It seems after reinstalling the CLT System Update Wants me to install CLT for XCode 13.2, 13.3, and 13.4 but I haven't updated that yet.
> 
> I was trying to install python 3.6.5 on macOS Monterey version 12.4. Hopefully it helps.

This works for me on Monterey version 12.4 , be attention to the final step which is the most critical that the whole command to install is 
```
pyenv install --patch 3.6.5 < <(curl -sSL https://github.com/python/cpython/commit/8ea6353.patch)
```
And a similar post [here](https://koji-kanao.medium.com/install-python-3-8-0-via-pyenv-on-bigsur-b4246987a548)

**Comment by jaredwideman** [comment]
My issue was that my xcode-select path was pointing to my Xcode 11.4 app. This fixed it for me:

`sudo xcode-select -s /Applications/Xcode-12.5.1.app/Contents/Developer`

**Comment by courtneyaschwartz** [comment]
Worked for me in MacOS 13.0 Ventura, with this slight change:
> `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

**Comment by mirasa29** [comment]
I've updated to MacOs Ventura 13.2 today. 
Updated my Xcode to 14.2 as well as CLT. 
Brew is up-to-date
Fresh installation of pyenv
Tried all the possible fixes I could search including the latest in this thread, but build still failing with the same issue:

![image](https://user-images.githubusercontent.com/41274086/215118332-1f9cc938-4352-4632-8f3d-88d43a47ab35.png)

Tried different version of python as well as trying the --patch but no luck.

I did a similar update of brew and installation of pyenv on my old Mac running on Monterey 3 weeks ago and I didn't have any issues. 

Wondering if this is an issue with 13.2...

**Comment by Aphelmion** [comment]
@mirasa29 The same for me. Nothing helps. MacOs Ventura 13.2

**Comment by foxman333** [comment]
I had the same problem on MacBook Pro A2141 (intel) macOS 12.5.1 21G83, then after upgrade on macOS 13.2.1 22D68 too.
Everything was up-to-date including brew and pyenv.

```
$ pyenv install 3.11
...
Downloading Python-3.11.1.tar.xz...
-> https://www.python.org/ftp/python/3.11.1/Python-3.11.1.tar.xz
Installing Python-3.11.1...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 13.2.1 using python-build 20180424)
...
```

The workaround described above worked for me:
```
$ sudo rm -rf /Library/Developer/CommandLineTools
$ xcode-select --install
$ xcode-select -v
$ xcode-select version 2396.
$ pyenv install 3.11
...
Downloading Python-3.11.1.tar.xz...
-> https://www.python.org/ftp/python/3.11.1/Python-3.11.1.tar.xz
Installing Python-3.11.1...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.11.1 to /Users/*****/.pyenv/versions/3.11.1
```

**Comment by mirasa29** [comment]
update: 
- updated MacOS to 13.2.1
- main fix: moved homebrew installation from /usr/loca/lib/homebrew to /opt/homebrew
- made sure homebrew is included to $PATH

figured out my issue from https://github.com/pyenv/pyenv/issues/1877#issuecomment-836115970

**Comment by charlieforward9** [comment]
> ```
> $ sudo rm -rf /Library/Developer/CommandLineTools
> $ xcode-select --install
> $ xcode-select -v
> $ xcode-select version 2396.
> $ pyenv install 3.11
> ...

Is the `xcode-select version` number the same for 3.12?
