### ISSUE TITLE
pyenv shims fail with concurrent processes in a build system

### ISSUE THREAD

**Issue by rocktavious** [pyenv/pyenv#174]
There appears to be a race condition if there is a pyenv installation on a build machine that runs multiple processes which create virtualenv's via the command :
pyenv virtualenv _name of env_

When there are two concurrently running processes that try to create a virtualenv for each process there is a race condition when the second process runs the command to create a new virtualenv it eventually makes a call to rehash and errors because of:
pyenv: cannot rehash: /var/lib/jenkins/.pyenv/shims/.pyenv-shim exists

I fully understand if this is a limitation of the way pyenv shims work, but i'm wondering if there is a workaround for this.  Since shim's are path based and each process can have its own environment variables, it would be nice if each process could specify a location for its set of shims so multiple processes on the same machine using pyenv won't collide when the shims are rehashed.

I would think something much like the PYENV_ROOT env var.   It could be PYENV_SHIM_ROOT env var that tells pyenv where to place the shims and if not specified it could default to the standard location.

Let me know if there is anyway i can help make this a reality.

**Comment by columbusmonkey** [comment]
Where is the issue tracker for the jenkins-pyenv-plugin? (As it looks like it may remove the lock directory, even if it did not manage to create it.)
