### ISSUE TITLE
PowerShell Core Profile

### ISSUE THREAD

**Issue by m1nkeh** [pyenv/pyenv#1741]
Is it possible to run pyenv under PowerShell core at all?

Currently i manage my envs in bash, which is ok, but be nice to stay only in the same terminal while working..

Thanks

**Comment by native-api** [comment]
See the guidance text in the shell configuration section and the Advanced configuration section in the README. It now explains what Pyenv expects to be done in the environment and what parts of it need what.
If you can replicate that under Powershell, it should work.
