### ISSUE TITLE
Update "Missing the OpenSSL lib" instructions in "Common build problems"

### ISSUE THREAD

**Issue by alexpulver** [pyenv/pyenv#1742]
[ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?](https://github.com/pyenv/pyenv/wiki/Common-build-problems#error-the-python-ssl-extension-was-not-compiled-missing-the-openssl-lib) in Common build problems doesn't suggest to set `CPPFLAGS` in addition to `CFLAGS`. This seems to be source of people reporting issues like #1184 and #993. Adding `CPPFLAGS` solved the issue for me.

Is it possible to add `CPPFLAGS="-I$(brew --prefix openssl)/include" \` to the instructions?

**Comment by native-api** [comment]
That's strange. Python doesn't use C++. Why would `CPPFLAGS` be possibly needed?

**Comment by native-api** [comment]
Okay, accordng to https://stackoverflow.com/questions/2754966/cflags-vs-cppflags , `CPPFLAGS` is for the proprocessor, not compiler, and include paths should go there regardless of whether C or C++ is used.

Done
