### ISSUE TITLE
Openssl build fails on Apple Silicon: compiling with -arch i386

### ISSUE THREAD

**Issue by GJKrupa** [pyenv/pyenv#1744]
# Description

As the title says. pyenv was installed using pyenv-installer; homebrew is not installed on the system. On the first attempt to install a version of Python it tries to build/install openssl from source and fails due to trying to link with i386 libraries.

Platform: macOS Big Sur 11.0.1
OS architecture: arm64
pyenv version: 1.2.21
Python version: 3.9.0
C compiler: Apple clang version 12.0.0 (clang-1200.0.32.27)

[Build log](https://gist.github.com/GJKrupa/39c0a78f75ae5a8d9b27b1f2378789dd)

**Comment by GJKrupa** [comment]
Looks like there's a PR to back-port the fix in OpenSSL to 1.1.1 (https://github.com/openssl/openssl/pull/13476) that's still open but it would preumably still require additional work to produce x86-64/arm64 universal binaries instead of i386/x86_64.

**Comment by david-shortman** [comment]
openssl support has been merged as of https://github.com/openssl/openssl/pull/12369

**Comment by native-api** [comment]
@GJKrupa Please test OpenSSL building in https://github.com/pyenv/pyenv/pull/1902 (all affected versions). I cannot do that 'cuz I don't have Apple hardware.
