### ISSUE TITLE
`BUILD FAILED` Error: mkdir "Permission denied" due to embedded spaces in username?

### ISSUE THREAD

**Issue by LandonRGeorge** [pyenv/pyenv#1756]
Checked common build issues and issues but couldn't find anything to resolve.

- OS X version: 10.15.7
- pyenv version: 1.2.21

I am trying to use `pyenv install` but am receiving a BUILD FAILED error. It appears `mkdir` is getting hung up on the space in my username, "landon george", and is attempting to make the directory at /Users/landon (which results in "Permission denied"). Unfortunately, this is a work computer and I won't be able to have the username changed.

![image](https://user-images.githubusercontent.com/48839396/101975207-6d848500-3c00-11eb-9d35-097bebf36392.png)

In case it's needed, here is `PATH:`

![image](https://user-images.githubusercontent.com/48839396/101975239-9c9af680-3c00-11eb-85a7-9f632f790fd0.png)

Here is the contents of ~/.zshrc. It doesn't show here, but I have also experimented with throwing escaped quotes around the `PYENV_ROOT` value of "$HOME/.pyenv". This made it so that the individual paths with embedded spaces in `PATH` were surrounded by quotes, but `pyenv install` resulted in the same build error.

![image](https://user-images.githubusercontent.com/48839396/101975252-bb00f200-3c00-11eb-8061-0b60be7c845c.png)

**Comment by Topology1225** [comment]
I faced on the same issue,,,,
Can anyone solve this?

**Comment by MrJanssen** [comment]
Same issue.
My home folder is situated on volume `Data SSD 512GB`.
While installing python **pyenv** fails with message: `mkdir: /Volumes/Data: Permission denied`.
Help!

**Comment by native-api** [comment]
No diagnostic data provided as required by the issue template
