### ISSUE TITLE
Unable to delete PYENV_ROOT

### ISSUE THREAD

**Issue by aktaseren** [pyenv/pyenv#1757]
I unfortunately use MacOS Big Sur. I uninstalled pyenv since I needed it but I can not delete **PYENV_ROOT** and delete the related pyenv parts in **PATH** variables from my environment variables. I tried even nano .bash_profile method but it did not work. I use zsh terminal. 

How can I solve this issue?

**Comment by thecocoa** [comment]
https://github.com/pyenv/pyenv#uninstalling-pyenv
