### ISSUE TITLE
Not all official versions available 

### ISSUE THREAD

**Issue by evil-shrike** [pyenv/pyenv#1758]
Hi,
Why is pyenv lagging behind in terms of available versions comparing to https://www.python.org/downloads/?

Currently, at 18th of Dec, there are two 3.9 releases: 3.9.0 and 3.9.1 while pyenv provides only 3.9-dev. Same for 3.8: Python 3.8.6 is the latest while pyenv contains only 3.8.3.
Such a gap in available versions make pyenv so not cool as it should be.
Is there anything that can be done in this area?
Thanks.

**Comment by xrisk** [comment]
It is not "lagging behind", there has just not been a release yet.

https://github.com/pyenv/pyenv/blob/master/plugins/python-build/share/python-build/3.9.1

If you want bleeding-edge python, you can always clone the repository and use it instead of using the pyenv version provided by your package manager.

**Comment by cclauss** [comment]
My sense is that CPython 3.9.0 is available by the current release https://github.com/pyenv/pyenv/releases

A CPython 3.9.1 would be appreciated because that natively supports the new Apple Silicon Macs
https://www.python.org/downloads/release/python-391/

**Comment by ulgens** [comment]
@yyuu Is it possible to release a new version with Python 3.9.1?

**Comment by evil-shrike** [comment]
>If you want bleeding-edge python

I wouldn't say 3.8.4 - 3.8.6 is bleeding edge (3.8.3 was released July 13, 2020) but thanks, I understood the issue now - each supported in pyenv version requires a new plugin and as such a new release of pyenv.

Sorry if it sound silly or discussed many times before (I've start working with pyenv only recently) but don't you think Python supported versions and plugins for them should be detached from the main tool (pyenv)? The cli tool could fetch them from repo for example (maybe be a label with its major version). Surely it would require tracking compatibility between plugins and main cli tool. Just an idea.

**Comment by cclauss** [comment]
https://github.com/pyenv/pyenv/releases shows that 3.8.4 and 3.8.6 shipped months ago.

**Comment by native-api** [comment]
Pyenv doesn't automatically support new versions as soon as they are published -- it requires installation scripts added to the codebase.
Theoretically, these can be added automatically by a bot based on existing scripts (as long as the generated script works and produces a usable result) but no-one has done this yet.
