### ISSUE TITLE
pyenv local does not set PYENV_VERSION

### ISSUE THREAD

**Issue by rbpatt2019** [pyenv/pyenv#1759]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information: Ubuntu 20.10, Kernel: 5.8.0-33-generic
- [x] OS architecture: amd64
- [x] pyenv version: pyenv 1.2.19-38-g2bf6111f
- [x] Python version: Tested with 3.8.4 and 3.9.0
- [x] C Compiler information: (Ubuntu 10.2.0-13ubuntu1) 10.2.0 
- [ ] Please attach verbose build log as gist: Not included, as this is not a build question.

### Issue
When issuing `pyenv shell`, the environment variable *PYENV_VERSION* gets set, as documented. I only recently noticed today while troubleshooting another issue [here](https://github.com/fannheyward/coc-pyright/issues/184) that `pyenv local` does not do this. Is this intended behaviour? And if so, why? 

It seems some software in the Python universe (pyright in the aforementioned bug, or at least the vim plugin for pyright) specifically search for the *PYENV_VERSION* variable when sourcing python environments for things like completion, etc. While that's certainly not pyenv's problem, it got me wondering if there would be any downsides to having `pyenv` set the *PYENV_VERSION* variable when moving in and out of directories that contain *.python-version* files set by `pyenv local`.

**Comment by native-api** [comment]
This is by design. `PYENV_VERSION` exists to _override_ the version inferred from the CWD.
