### ISSUE TITLE
New release of pyenv to support Python 3.9.1

### ISSUE THREAD

**Issue by bryanculbertson** [pyenv/pyenv#1760]
There has only been `6` commits since `v1.2.21`, but crucially one of them is support for Python `3.9.1`. Would it be possible to cut a release and push to pypi?

https://github.com/pyenv/pyenv/compare/v1.2.21...master

**Comment by 00willo** [comment]
This would be fantastic, this also impacts those who have installed pyenv via homebrew.

**Comment by quantumferret** [comment]
Yes please! It's frustrating to not have access to the latest python release through pyenv.

**Comment by ZeeD26** [comment]
You can always do `brew reinstall --HEAD pyenv` when using homebrew :)

**Comment by cclauss** [comment]
@joshfriend Can you please help us understand how to achieve this release?

**Comment by bryanculbertson** [comment]
Hi @yyuu 👋 since you have managed previous releases I am tagging you to see if we could get a `v1.2.22` release for CPython `3.9.1`. Thanks!

**Comment by Achimh3011** [comment]
> You can always do `brew reinstall --HEAD pyenv` when using homebrew :)

Actually it is 

```
$ brew unlink pyenv
$ brew install --HEAD pyenv
```

**Comment by cclauss** [comment]
Yeah @Achimh3011 THe HEAD hack is fine for individual developers but is not really recommended for production projects.

**Comment by Esgrove** [comment]
Is there something blocking this? Python 3.9.1 has already been out for a full month so it is sad to see this has still not been added.

**Comment by bryanculbertson** [comment]
Hi @poad 👋 I am tagging you since you submitted the PR to add support for Python `3.9.1`. Could you assist in assembling a `v1.2.22` release of `pyenv` to release your change to PyPi. Thanks!

**Comment by poad** [comment]
Hi @bryanculbertson.
I would like to assist, what exactly do I need to do?

**Comment by bryanculbertson** [comment]
Hi @poad thank you for responding!

I don't know how to conduct a release, and if you don't know how to either, then we are probably stuck waiting on one of the pyenv maintainers to chime in @yyuu @joshfriend or @blueyed 

From a little bit of research of looking at a previous release (https://github.com/pyenv/pyenv/compare/v1.2.12...v1.2.13), it looks like you update https://github.com/pyenv/pyenv/blob/master/CHANGELOG.md and https://github.com/pyenv/pyenv/blob/master/libexec/pyenv---version and then create a new github release.

This all seems simple, but probably need a maintainer to do the steps.

**Comment by poad** [comment]
Hi @bryanculbertson thank you for responding!

I don't know either, so I'll wait for a response from pyenv maintainers.

Thanks for letting me know.

**Comment by cclauss** [comment]
Well done @yyuu Thanks!

**Comment by ssbarnea** [comment]
Something is wrong here as 1.2.21 does not list 3.9.1
```
pyenv --version
pyenv 1.2.21
```
Both `pytenv-update` and `brew upgrade` do not bring a newer version and `pyenv install --list|grep 3.9` still does not list 3.9.1

**Comment by dbowring** [comment]
@ssbarnea This issue was resolved for 1.2.2**2**:

```console
$ pyenv --version
pyenv 1.2.22

$ pyenv install --list | grep 3.9
  3.9.0
  3.9-dev
  3.9.1
  miniconda-3.9.1
  miniconda3-3.9.1
  ```

**Comment by cclauss** [comment]
https://github.com/pyenv/pyenv/releases

**Comment by muthukumars** [comment]
my pyenv is 2.0.7.  python 3.9.1 is not available in pyenv install --list. any help?

**Comment by native-api** [comment]
@muthukumars [It's available in 2.0.7.](https://github.com/pyenv/pyenv/blob/v2.0.7/plugins/python-build/share/python-build/3.9.1) Check which Pyenv you're using, you might have two copies on your system.

**Comment by muthukumars** [comment]
@native-api  thank you for responding. I have checked pyenv --version. it shows 2.0.7. 

when I do pyenv install --list | grep 3.9 

I get

3.9.0a4
  3.9-dev
  miniconda-3.9.1
  miniconda3-3.9.1

for some reason, I do not see 3.9.1

Please suggest

**Comment by native-api** [comment]
Check the contents of `$(pyenv root)/plugins/pyenv-build/share/pyenv-build` and `$(which pyenv)/../plugins/pyenv-build/share/pyenv-build` (if exists). There should be script files for all versions available for install.

**Comment by native-api** [comment]
> I get
> 
> 3.9.0a4

This definitely means that you have an older version installed -- most probably, one via Homebrew and another via Git checkout in `~/.pyenv`. Assuming the more recent version is the Homebrew one, clean out everything from `~/.pyenv` (except `~/.pyenv/versions` if you wish to preserve the alt versions) and restart the terminal.

**Comment by muthukumars** [comment]
Super.. @native-api  - Yes. I did that now I am able to see it. you are right.  after cleaning, I am able to see it. thank you so much. I am just wondering what has happened in my laptop.  thank you so much for helping. 

if you can let me know after cleaning up ~./.pyenv - I am able to get the options. wondering what is happening in my laptop. 

thank you
Muthukumar
