### ISSUE TITLE
pyenv update for 3.8.7

### ISSUE THREAD

**Issue by telemmaite** [pyenv/pyenv#1765]
There are some important GC fixes , would you add it to the pyenv index.
https://docs.python.org/release/3.8.7/whatsnew/changelog.html#python-3-8-7-final

**Comment by ushuz** [comment]
There's already a PR adding 3.8.7 waiting for merge
https://github.com/pyenv/pyenv/pull/1762

**Comment by mphelp** [comment]
@ushuz looks like that merge #1762 was completed. please close this ticket thanks!
