### ISSUE TITLE
@thecocoa while homebrew on M1 is still being worked on: One can install python 3.9.1 via an brew installation for arm64. It's even bottled since recently: https://formulae.brew.sh/formula/python@3.9#default and there is official support from python since 3.9.1

### ISSUE THREAD

**Issue by stevesuh** [pyenv/pyenv#1767]
@thecocoa while homebrew on M1 is still being worked on: One can install python 3.9.1 via an brew installation for arm64. It's even bottled since recently: https://formulae.brew.sh/formula/python@3.9#default and there is official support from python since 3.9.1
```
❯ file /opt/homebrew/Cellar/python@3.9/3.9.1_2/bin/python3
/opt/homebrew/Cellar/python@3.9/3.9.1_2/bin/python3: Mach-O 64-bit executable arm64
```

I reverted to installing python directly via brew instead of via pyenv, since I cloud not get the build to work

_Originally posted by @benjaminbauer in https://github.com/pyenv/pyenv/issues/1764#issuecomment-751390646_

**Comment by stevesuh** [comment]
```
Steves-Mac-mini:~ stevesuh$ pyenv install 3.9.0
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.9.0.tar.xz...
-> https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tar.xz
Installing Python-3.9.0...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 11.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/zv/59d6fy6s3jz94zq598f0rvrc0000gn/T/python-build.20201231180810.12027
Results logged to /var/folders/zv/59d6fy6s3jz94zq598f0rvrc0000gn/T/python-build.20201231180810.12027.log

Last 10 log lines:
checking size of long double... 8
checking size of _Bool... 1
checking size of off_t... 8
checking whether to enable large file support... no
checking size of time_t... 8
checking for pthread_t... yes
checking size of pthread_t... 8
checking size of pthread_key_t... 8
checking whether pthread_key_t is compatible with int... no
configure: error: Unexpected output of 'arch' on OSX
```

I'd still like to manage python versions via pyenv on M1.  For now I also directly installed the formula for python3.9.

**Comment by rybodiddly** [comment]
I was able to install python 3.8.6 with pyenv using the following method: (make sure you have xcode, xcode commandline tools and necessary brew packages installed)

`CFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix bzip2)/include -I$(brew --prefix readline)/include -I$(xcrun --show-sdk-path)/usr/include" LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix readline)/lib -L$(brew --prefix zlib)/lib -L$(brew --prefix bzip2)/lib" pyenv install --patch 3.8.6 <<(curl -sSL https://raw.githubusercontent.com/Homebrew/formula-patches/113aa84/python/3.8.3.patch\?full_index\=1)`

Here's my PATH in .zshrc:
`export PATH="/opt/homebrew/bin:/Users/rybo/Library/Python/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:$PATH"`

**Comment by anton-petrov** [comment]
Please, use this [gist](https://gist.github.com/anton-petrov/53eb5c5b29a473ba618f9926eb06c92a) to install homebrew for M1 natively. Then, you can install ptyhon 3.9.1 as follows: pyenv install 3.9.1/
This worked for me very well. Also, check my pull request to pyenv at https://github.com/pyenv/pyenv/pull/1766 - will give an opportunity to use Miniforge distribution (miniconda with native compiled packages for different platforms, python 3.9, arm64 for OSX too)

**Comment by rybodiddly** [comment]
> Please, use this [gist](https://gist.github.com/anton-petrov/53eb5c5b29a473ba618f9926eb06c92a) to install homebrew for M1 natively. Then, you can install ptyhon 3.9.1 as follows: `pyenv install 3.9.1`
> This worked for me very well on my Macbook Air M1!
> 
> Also, check my pull request to pyenv at #1766 - will give an opportunity to use Miniforge distribution (miniconda with native compiled packages for different platforms, python 3.9, arm64 for OSX too)

@anton-petrov pyenv The gist you referenced is the current installation method most are currently using to install brew on their M1's, but brew's current installation of pyenv (which is 1.2.21 at the time of this posting) doesn't include python 3.9.1. It only includes up to 3.9.0, 3.9-dev and 3.10-dev. An attempted installation with your supposed method results in the following error on 3.9.0:

```
rybo@Rybos-MacBook-Air-M1 ~ % pyenv install 3.9.0
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.9.0.tar.xz...
-> https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tar.xz
Installing Python-3.9.0...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 11.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/vm/_fqh0r7d6l1145z61qk98ybm0000gn/T/python-build.20210102112128.55104
Results logged to /var/folders/vm/_fqh0r7d6l1145z61qk98ybm0000gn/T/python-build.20210102112128.55104.log

Last 10 log lines:
checking size of _Bool... 1
checking size of off_t... 8
checking whether to enable large file support... no
checking size of time_t... 8
checking for pthread_t... yes
checking size of pthread_t... 8
checking size of pthread_key_t... 8
checking whether pthread_key_t is compatible with int... no
configure: error: Unexpected output of 'arch' on OSX
make: *** No targets specified and no makefile found.  Stop.
```

Any insight into how you got it working would be appreciated. Also agree that conda, particularly [minoforge3](https://github.com/conda-forge/miniforge) is an excellent option atm and has numpy, scikit etc. all working on the M1 natively.

**Comment by anton-petrov** [comment]
> > Please, use this [gist](https://gist.github.com/anton-petrov/53eb5c5b29a473ba618f9926eb06c92a) to install homebrew for M1 natively. Then, you can install ptyhon 3.9.1 as follows: `pyenv install 3.9.1`
> > This worked for me very well on my Macbook Air M1!
> > Also, check my pull request to pyenv at #1766 - will give an opportunity to use Miniforge distribution (miniconda with native compiled packages for different platforms, python 3.9, arm64 for OSX too)
> 
> @anton-petrov The gist you referenced is the installation method most are currently using to install brew on their M1's, but brew's current installation of pyenv (which is 1.2.21 at the time of this posting) doesn't include python 3.9.1. It only includes up to 3.9.0, 3.9-dev and 3.10-dev. An attempted installation with your supposed method results in the following error on 3.9.0:
> 
> ```
> rybo@Rybos-MacBook-Air-M1 ~ % pyenv install 3.9.0
> python-build: use openssl@1.1 from homebrew
> python-build: use readline from homebrew
> Downloading Python-3.9.0.tar.xz...
> -> https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tar.xz
> Installing Python-3.9.0...
> python-build: use readline from homebrew
> python-build: use zlib from xcode sdk
> 
> BUILD FAILED (OS X 11.1 using python-build 20180424)
> 
> Inspect or clean up the working tree at /var/folders/vm/_fqh0r7d6l1145z61qk98ybm0000gn/T/python-build.20210102112128.55104
> Results logged to /var/folders/vm/_fqh0r7d6l1145z61qk98ybm0000gn/T/python-build.20210102112128.55104.log
> 
> Last 10 log lines:
> checking size of _Bool... 1
> checking size of off_t... 8
> checking whether to enable large file support... no
> checking size of time_t... 8
> checking for pthread_t... yes
> checking size of pthread_t... 8
> checking size of pthread_key_t... 8
> checking whether pthread_key_t is compatible with int... no
> configure: error: Unexpected output of 'arch' on OSX
> make: *** No targets specified and no makefile found.  Stop.
> ```
> 
> Any insight into how you got it working would be appreciated. Also agree that conda, particularly [miniforge3](https://github.com/conda-forge/miniforge) is an excellent option atm and has numpy, scikit, virtual environments etc. all working on the M1 natively.

I recommend to install pyenv using https://github.com/pyenv/pyenv-installer, and that method works great!
So, the formula is: install native homebrew for M1, then install **pyenv** by **pyenv-installer**. This worked for me.

**Comment by rybodiddly** [comment]
@anton-petrov thanks! using the [pyenv installer](https://github.com/pyenv/pyenv-installer) method provided a viable 3.9.1 installation. Still had to use the patch method I posted above to install 3.8.6, but I now have a fairly stable and functional python environment.

**Comment by stevesuh** [comment]
This worked for me too.  I'm gonna close the issue.

**Comment by NatanMish** [comment]
@anton-petrov your solution with the pyenv installer + installing homebrew natively worked great for me. I have been looking for a solution for this all day!

**Comment by stevesuh** [comment]
```
Steves-Mac-mini:~ stevesuh$ pyenv install 3.9.1
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.9.1.tar.xz...
-> https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tar.xz
Installing Python-3.9.1...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 11.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/zv/59d6fy6s3jz94zq598f0rvrc0000gn/T/python-build.20210107111954.58915
Results logged to /var/folders/zv/59d6fy6s3jz94zq598f0rvrc0000gn/T/python-build.20210107111954.58915.log

Last 10 log lines:
  "_libintl_textdomain", referenced from:
      _PyIntl_textdomain in libpython3.9.a(_localemodule.o)
      _PyIntl_textdomain in libpython3.9.a(_localemodule.o)
ld: symbol(s) not found for architecture arm64
ld: symbol(s) not found for architecture arm64
clang: clangerror: linker command failed with exit code 1 (use -v to see invocation)
: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Programs/_testembed] Error 1
make: *** Waiting for unfinished jobs....
make: *** [python.exe] Error 1
```

I have command line tools.  Do I need XCode?

**Comment by stevesuh** [comment]
I did `brew uninstall pyenv` but I'm wondering if it's not cleaning up properly.   @NatanMish or @rybodiddly did you install the homebrew version of pyenv and uninstall it before using pyenv installer?

**Comment by NatanMish** [comment]
Yes, I did exactly that. Make sure it actually removes pyenv when you do
that.

**Comment by rybodiddly** [comment]
@stevesuh , as @NatanMish  above mentioned, I also had pyenv installed using brew, then uninstalled using `brew uninstall pyenv`. Then just ran the pyenv installer. I documented my process [here](https://github.com/rybodiddly/Poetry-Pyenv-Homebrew-Numpy-TensorFlow-on-Apple-Silicon-M1).

**Comment by stevesuh** [comment]
@rybodiddly that was it.  I needed XCode as well as command line tools(which is normally enough for homebrew).  I also needed to export the SDK path.  Thanks for your help!
