### ISSUE TITLE
PYTHONHOME not configured after setting a shell Python version

### ISSUE THREAD

**Issue by thompsbrian** [pyenv/pyenv#1777]
### Prerequisite
* [ X ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ X ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ X ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ X ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ X ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ X ] Platform information (e.g. Ubuntu Linux 16.04): Debian 10 buster
- [ X ] OS architecture (e.g. amd64): amd64
- [ X ] pyenv version: 1.2.21
- [ X ] Python version: 3.9.0
- [ X ] C Compiler information (e.g. gcc 7.3): gcc 5.5.0_7
- [ X ] Please attach verbose build log as gist: https://gist.github.com/bthompson90/516df8304f0bdaa6135341cf813561f1

### Problem

After installing Python 3.9.0 with pyenv and setting it with `pyenv shell 3.9.0`, whenever I try to open vim or use Python, the error in the gist appears.

### Solution

The solution I found was to set PYTHONHOME in my `.zshrc` like so:

```sh
export PYTHONHOME=$PYENV_ROOT/versions/"$(python -V | cut -d' ' -f 2)"
```

**Comment by native-api** [comment]
The gist link gives a 404.

**Comment by native-api** [comment]
Why does `PYTHONHOME` need to be set?
https://docs.python.org/3/using/cmdline.html?highlight=pythonhome#envvar-PYTHONHOME describes it as optional, existing to manually override the location of the standard library.
Certainly not something that should be present in a stock environment -- which is what Pyenv creates.

**Comment by thompsbrian** [comment]
No worries, I completely lost track of this issue anyway.  Don't mind it being closed.
