### ISSUE TITLE
ARMv8 support for Linux

### ISSUE THREAD

**Issue by anton-petrov** [pyenv/pyenv#1779]
May be, it's time to add ARMv8 64bit support for Linux also? For now, we have only ARMv7 32 bit option, but no modern aarch64.
If anyone has a device on this processor (Raspberry Pi 4, for example), please, leave a message in this thread and post result of `uname -m` command.

**Comment by cclauss** [comment]
https://www.raspberrypi.org/forums/search.php?keywords=uname

**Comment by maxthomas** [comment]
```
max@qqq:~$ uname -a
Linux qqq 5.9.0-0.bpo.5-arm64 #1 SMP Debian 5.9.15-1~bpo10+1 (2020-12-31) aarch64 GNU/Linux
```

**Comment by maxthomas** [comment]
pyenv seems to work fine on this arch for what it's worth (running `3.9.2` successfully)
