### ISSUE TITLE
Weird pyenv completion character

### ISSUE THREAD

**Issue by benmezger** [pyenv/pyenv#1787]
For some reasons, when I tab on the install options, this weird `input\` appears. Tried reinstalling `pyenv` but got the same result. 

Running `pyenv completions install` also outputs the `input\` before the version name. 

![image](https://user-images.githubusercontent.com/915606/105107720-6ff7bb80-5a97-11eb-89e5-a1eeca7ccee4.png)

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): `Darwin seds.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64`
- [ ] OS architecture (e.g. amd64):
- [ ] pyenv version: `pyenv 1.2.20`
- [ ] Python version: `3.9.0`
- [ ] C Compiler information (e.g. gcc 7.3):  `Apple clang version 12.0.0 (clang-1200.0.32.28)`
- [ ] Shell:  `zsh 5.8 (x86_64-apple-darwin20.1.0)`
- [ ] Term: `xterm-256color`

**Comment by native-api** [comment]
Without debug output as required by the issue template, impossible to say what's happening.

**Comment by native-api** [comment]
Since it's completions that you need to provide the trace of, enter the following into the interactive shell:

```
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -x
```

Then invoke the faulty completion.
