### ISSUE TITLE
Can I change the source of downloading python?

### ISSUE THREAD

**Issue by simlegate** [pyenv/pyenv#18]
it is too slow now !

**Comment by huntzhan** [comment]
@yyuu I tried to make a local mirror by cloning `yyuu/yyuu.github.com`, but it doesn't work. It's seems that https://github.com/yyuu/yyuu.github.com/tree/master/pythons doesn't contains any Python source package, am I right?

**Comment by huntzhan** [comment]
https://github.com/yyuu/yyuu.github.com/blob/master/pythons/update.sh#L50

```
for file in source/*; do
  base="$(basename "$file")"
  md5="$(compute_md5 < "$file")"
  sha="$(compute_sha2 < "$file")"
  ln -f "$file" "$md5"
  ln -f "$file" "$sha"
  sed -i -e "/>$base</s/^.*$/<li><a href=\"$sha\">$base<\/a><\/li>/" index.html
done
```

Maybe I could just create a `source` directory and download the packages manually, then run the `update.sh` script.

**Comment by yyuu** [comment]
@huntzhan I've removed CPython sources from http://yyuu.github.io in https://github.com/yyuu/yyuu.github.com/commit/391c0d10609a5bd61f30d0529ef2e34b58fe3e6e since CPython sources are distributed via fast.ly nowadays. You can add CPython sources in your clone if needed.

**Comment by huntzhan** [comment]
Thanks.
