### ISSUE TITLE
Huge $PATH variable

### ISSUE THREAD

**Issue by quantum-booty** [pyenv/pyenv#1801]
Any idea why this is happening? It is slowing down my terminal. I'm using Fish.
![image](https://user-images.githubusercontent.com/28958399/106842532-1cdb5680-669c-11eb-9ee0-a42b20abe7b9.png)

**Comment by yedpodtrzitko** [comment]
how does your `.zshrc` / `.bashrc` / etc look like?

**Comment by quantum-booty** [comment]
> how does your `.zshrc` / `.bashrc` / etc look like?

```

set -Ux PYENV_ROOT $HOME/.pyenv
set -Ux fish_user_paths $PYENV_ROOT/bin $fish_user_paths

status --is-interactive; and pyenv init - | source
status --is-interactive; and pyenv virtualenv-init - | source


# pyenv init
if command -v pyenv 1>/dev/null 2>&1
  pyenv init - | source
end

source (pyenv root)/completions/pyenv.fish

```

**Comment by yedpodtrzitko** [comment]
see #1642, looks like the same issue and there's a workaround mentioned.

**Comment by quantum-booty** [comment]
Thank you @yedpodtrzitko
