### ISSUE TITLE
Run pyenv shell automatically when pyenv local is set

### ISSUE THREAD

**Issue by quantum-booty** [pyenv/pyenv#1802]
When I set `pyenv local my_virtual_env`, it seems like although it activates the virtualenv, pyenv shell is not pointing to the virtualenv and is still pointing to the global interpreter, and this causes problems with neovim lsp. see: https://github.com/neovim/nvim-lspconfig/issues/717
So my question is, how can I run `pyenv shell my_virtual_env` automatically?

**Comment by steakhutzeee** [comment]
> When I set `pyenv local my_virtual_env`, it seems like although it activates the virtualenv, pyenv shell is not pointing to the virtualenv and is still pointing to the global interpreter, and this causes problems with neovim lsp. see: [neovim/nvim-lspconfig#717](https://github.com/neovim/nvim-lspconfig/issues/717) So my question is, how can I run `pyenv shell my_virtual_env` automatically?

Hi, actually pyenv shell is needed when running pyenv local? I thought not. I'm facing the same issue. Opened a discussion here https://github.com/pyenv/pyenv/discussions/2589
