### ISSUE TITLE
Slightly different build environment instructions in wiki

### ISSUE THREAD

**Issue by ajfriend** [pyenv/pyenv#1804]
There are two slightly different build environment recommendations/instructions for Ubuntu/Debian in two different locations in the wiki:

- https://github.com/pyenv/pyenv/wiki#suggested-build-environment
- https://github.com/pyenv/pyenv/wiki/Common-build-problems

It isn't clear to me which is the "correct" bit of advice I should follow. Would it make sense to combine them into a single recommendation?

# Differences

## Command

The [suggested-build-environment instructions](https://github.com/pyenv/pyenv/wiki#suggested-build-environment) have a command like

```
sudo apt-get update; sudo apt-get install --no-install-recommends
```

while the [Common-build-problems instructions](https://github.com/pyenv/pyenv/wiki/Common-build-problems) have

```
sudo apt-get install -y
```

I suppose the only significant difference is with the `--no-install-recommends`, but I'm not sure what consequences that has with respect to `pyenv`.

## Packages

The lists of packages differ between the two commands. The (sorted) lists are below, with a `#` indicating a package that is absent from one list, but present in the other.

[suggested-build-environment](https://github.com/pyenv/pyenv/wiki#suggested-build-environment):

```
build-essential
curl
# git
libbz2-dev
libffi-dev
liblzma-dev
libncurses5-dev
# libncursesw5-dev
libreadline-dev
libsqlite3-dev
libssl-dev
libxml2-dev
libxmlsec1-dev
llvm
make
# python-openssl
tk-dev
wget
xz-utils
zlib1g-dev
```

[Common-build-problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems):

```
build-essential
curl
git
libbz2-dev
libffi-dev
liblzma-dev
libncurses5-dev
libncursesw5-dev
libreadline-dev
libsqlite3-dev
libssl-dev
# libxml2-dev
# libxmlsec1-dev
llvm
# make
python-openssl
tk-dev
wget
xz-utils
zlib1g-dev
```

**Comment by ajfriend** [comment]
@joshfriend @nyuszika7h, it looks like you all have touched these instructions recently. If you have any thoughts... 😃

**Comment by native-api** [comment]
To me, it looks like the base instructions shoud remain at https://github.com/pyenv/pyenv/wiki#suggested-build-environment -- while https://github.com/pyenv/pyenv/wiki/Common-build-problems should delegate for them but follow that with alternatives and special cases -- i.e. the things that you have to resort to when the base instructions don't work for you.

**Comment by native-api** [comment]
Done.
