### ISSUE TITLE
"Using script's directory as PYENV_DIR if shim is invoked with a script argument" feature is undocumented and broken

### ISSUE THREAD

**Issue by native-api** [pyenv/pyenv#1813]
Closes https://github.com/pyenv/pyenv/issues/1807

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): all
- [x] OS architecture (e.g. amd64): all
- [x] pyenv version: 1.2.22-61-ga0b02db7
- [x] Python version: all
- [x] C Compiler information (e.g. gcc 7.3): N/A
- [x] Please attach verbose build log as gist: see https://github.com/pyenv/pyenv/issues/1807#issue-803346431

#### Background

As of now, if a Pyenv shim is invoked with a script parameter, Pyenv uses that script's directory to determine the Python version to use rather than the current directory. The feature was initially added in Rbenv in https://github.com/rbenv/rbenv/commit/283e67b57e8ab0bbbe504aab6866729b0035186a .
**The problems with this feature are:**
* **It's undocumented and thus surprising**
* **It's broken and it's unclear if it can be fixed at all**

---

#### It's undocumented and thus surprising

* The use case seems to be:
  * If a script is under a project tree with `.python-version`, the user probably intends to use that Python version whenever they run scripts from that project, even if they invoke them from elsewhere

* **It's surprising** since normally, by invoking `python <path/to/script>`, the script is fed to whatever `python` currently is, regardless of the version that script is intended for. I.e. **it violates the standard practice of using Python.** If you wish to use the version that the script is designed for, you need to invoke `<path/to/script>` directly and rely on its shebang.

* But there seems to be no other way to specify a "default" Pyenv-based Python version to use for a script:
  * A shebang appears to be unusable in this case because
    * [a shebang only allows a single argument](https://unix.stackexchange.com/questions/399690/multiple-arguments-in-shebang) while a Pyenv invocation would likely need more
    * there's currently no Pyenv subcommand to invoke an explicitly specificed version (akin to `rvm do`) rather than the currently selected one

---

#### It's broken and it's unclear if it can be fixed at all

**It parses the command line very crudely** and as a result, **sometimes detects the script argument incorrectly:** https://github.com/pyenv/pyenv/issues/1807

To fix it and detect the script argument reliably in all cases, we have to effectively duplicate the command line parsing logic -- and somehow, of all Python versions and implementations at once!!

The algorithm's objective is to:
* see if there is an "alternative source" switch (`-c`,`-m`,`-`). If yes, there's no script parameter
* otherwise, get the first non-option argument

Key challenges are:
* when seeing a switch, we need to know if it accepts an argument -- if it does, we need to skip its argument from consideration as a script
  * different Python versions/implementations have a different set of switches that accept an argument. E.g.:
    * [PyPy adds `--jit`](https://doc.pypy.org/en/latest/man/pypy.1.html#options)
    * some of the current switches are absent in old versions
    * new versions/implementations may change that set
* arguments can be combined according to standard GNU syntax: `-abc`, `--foo=arg` vs `--foo arg`, `-sarg` vs `-s arg`
  * [`getopt(1)`](https://linux.die.net/man/1/getopt) can transform those different variants into a canonical form (`-a -b -c --foo arg -- positional args`) -- but it needs to be passed a full list of possible switches, both short and long -- which we don't know.

---

#### Questions for discussion

Main question: **What should we do with this feature?**
* **Delete it?**
* **Fix it somehow?**
* **Change it to some other form?**
   * e.g. smth that would conform to the principle of the least surprise _and_ wouldn't randomly break things

Sub-questions:
* How valid is the use case?
  * If it is, could it be made into some other form that better conforms to standard Linux and Python practices?
* Is it at all possible to fix it as it is -- **in a maintainable, future-proof way?**

**Comment by native-api** [comment]
>     * Is it at all possible to fix it as it is -- **in a maintainable, future-proof way?**

My only idea of a future-proof way is to make version scripts be able to provide a list of their command line switches and which of them accept arguments. Pyenv would then be able to combine that information (**and hope there are no contradictions -- in which case, we're stuck in a chicked-and-egg problem:** without knowing the version to use, we can't parse the command line, without parsing the command line, we can't know the version to use) and use `getopt` with the combined set of switches.

**Looks like lots of complication for a niche/uncommon use case.**

* In particular, it will force Pyenv to breach into Python-Build's internals.
  * But this could be avoided by having Python-Build provide this info via public interface, e.g. via a subcommand.

**Comment by native-api** [comment]
@sstephenson , could ytou comment on why this feature was added and if the crude command line parsing is sufficient for Ruby?
E.g. https://github.com/rbenv/rbenv/commit/283e67b57e8ab0bbbe504aab6866729b0035186a has the same bug: `ruby script.rb path/to/file` would also misdetect the script argument.

**Comment by native-api** [comment]
> **Change it to some other form?**
> 
>     * e.g. smth that would conform to the principle of the least surprise _and_ wouldn't randomly break things

Another drawback of the current solution is that it only works from within a shell with activated Pyenv, not e.g. if invoking the script from elsewhere.

**The only solution that I see that would work from anywhere is a shebang.** So we have to invent smth here if we wish to go this path, whether we like it or not.

* Since "a shebang only allows a single argument", and we'll have to use `/usr/bin/env`, **the only possible shebang for us it `!/usr/bin/env <smth>`**
   * So I envision **we can add an executable named e.g. `pyenv-exec-script` that would call `pyenv` with `PYENV_DIR` set to the directory of its first argument.
     * Then **we recommend users to use it in shebang for the use case when a user wishes to invoke scripts with the project's Python version from elsewhere.**

**Comment by bersbersbers** [comment]
For the record, I guess #1814 explains the following behavior that I am seeing after updating from abcbf6e1 to 80e418ec. Basically, I have lost the ability to invoke a script from another directory using the script's own local environment.

```
user@host:~/.pyenv> more ~/project/subproject/.python-version
subproject-3.8.8

user@host:~/.pyenv> head -2 ~/project/subproject/main.py
#!/usr/bin/env python3
import textract

user@host:~/.pyenv> git checkout abcbf6e1
Previous HEAD position was 80e418ec Merge pull request #1838 from cclauss/patch-1
HEAD is now at abcbf6e1 Merge pull request #1794 from cclauss/patch-3

user@host:~/.pyenv> pyenv rehash

user@host:~/.pyenv> ~/project/subproject/main.py

user@host:~/.pyenv> git pull
Updating abcbf6e1..80e418ec
Fast-forward
 .github/workflows/ubuntu_tests.yml                             | 10 +++++++---
 libexec/pyenv                                                  | 18 ------------------
 libexec/pyenv-rehash                                           | 13 -------------
 plugins/python-build/bin/python-build                          | 12 ++++++------
 plugins/python-build/share/python-build/{3.10.0a5 => 3.10.0a6} |  4 ++--
 plugins/python-build/test/pyenv_ext.bats                       |  6 +++---
 test/pyenv_ext.bats                                            | 25 -------------------------
 7 files changed, 18 insertions(+), 70 deletions(-)
 rename plugins/python-build/share/python-build/{3.10.0a5 => 3.10.0a6} (60%)

user@host:~/.pyenv> pyenv rehash

user@host:~/.pyenv> ~/project/subproject/main.py
Traceback (most recent call last):
  File "/home/user/project/subproject/main.py", line 11, in <module>
    import textract
ModuleNotFoundError: No module named 'textract'
```

**Comment by martingd** [comment]
> For the record, I guess #1814 explains the following behavior that I am seeing after updating from [abcbf6e](https://github.com/pyenv/pyenv/commit/abcbf6e11222a96e1c72805f1c779761368a9156) to [80e418e](https://github.com/pyenv/pyenv/commit/80e418eca535b9c7cbdd0f8557586eaaf872000d). Basically, I have lost the ability to invoke a script from another directory using the script's own local environment.

I am seeing the exact same problem after upgrading from 1.2.22 to 1.2.24 (on macOS). Really annoying because this feature allowed controlling exactly which version of python to use for different script relying on the `.python_version` set in the directory of each script.

I am pretty sure this was the use case for many users – which wasn't taken into consideration before removing this feature.

**Comment by native-api** [comment]
@bersbersbers I started making an alternative implementation of this feature as described in https://github.com/pyenv/pyenv/issues/1813#issuecomment-778755503 to https://github.com/native-api/pyenv/tree/exec_script .
It needs tests and documentation before it can be submitted.

You can finish my work if you need this feature.

**Comment by bersbersbers** [comment]
@native-api thanks, I don't really need another solution since essentially, I can fix the thing for me with a single `cd`. @martingd may be interested.

**Comment by martingd** [comment]
@native-api I don't think the proposed solution will work for me as it seems the solution is to use a different shebang than the usual `/usr/bin/env python3`. In my case the scripts are shared with colleagues and checked out from a repo and used across macOS, Linux and Windows and the shebang can and should not be altered.

**Comment by native-api** [comment]
@martingd If you use `#!/usr/bin/env python3`, you sign on the botton line that you want to use whatever Python 3 is currently the default.
If you actually want something different, you need to use some different shebang, or your requirements are self-contradictory:
how do you expect the exact same command to do different things depending on what your current _intent_ is (aka [Do What I Mean](http://www.catb.org/~esr/jargon/html/D/DWIM.html))?

Specifically: how are you going to distinguish between cases where you want to use the Python inferred from the script's dir, and where you don't? The shebang you gave gives the invoked program no indication whatsoever what your intent is: whether you invoke `python3 prog.py` or `./prog.py`, the same command line is executed.

**Comment by martingd** [comment]
@native-api Maybe I am wrong, but I would expect this:

1. `#!/usr/bin/env python` means: give me the currently installed Python 2 version
2. `#!/usr/bin/env python3` means: give me the currently installed Python 3 version

At least, that's the way it works on all Linux, macOS and Windows (using the `py` launcher) systems I have encountered so far.

`pyenv` seems to honour that:

- If my `.python-version` file contains a Python 2 version number, it will affect scripts with a shebang like 1), but not 2).
- Likewise, if the `.python-version` specified contains a Python 3 version number, it will affect the scripts with a shebang like  2), but not 1).
- If it contains both a Python 2 and 3 version number, it will affect both scripts with a shebang like 1) and like 2).

(I have just tested that the above behaviour is how `pyenv` works on my macOS machine.)

> Specifically: how are you going to distinguish between cases where you want to use the Python inferred from the script's dir, and where you don't? The shebang you gave gives the invoked program no indication whatsoever what your intent is: whether you invoke `python3 prog.py` or `./prog.py`, the same command line is executed.

I don't want to distinguish. I believe, it is utterly inconsistent that the same script invoked in the exact same way but with different cwd works differently. I think `pyenv` behaves more inconsistent than before.

Example:

    ~/tmp/pyenv/test % cat .python-version 
    3.8.7
    ~/tmp/pyenv/test % cat py3test 
    #!/usr/bin/env python3
    
    import sys
    print("Python version")
    print (sys.version)
    print("Version info.")
    print (sys.version_info)

Now, running the script from the directory where the `.python-version` file is located gives me Python 3.8.7:

    ~/tmp/pyenv/test % ./py3test 
    Python version
    3.8.7 (default, Jan 25 2021, 16:21:17) 
    [Clang 11.0.3 (clang-1103.0.32.29)]
    Version info.
    sys.version_info(major=3, minor=8, micro=7, releaselevel='final', serial=0)

Going to the parent dir and running the exact same script gives me Python 3.9.1:

    ~/tmp/pyenv/test % cd ..
    ~/tmp/pyenv % test/py3test 
    Python version
    3.9.1 (default, Jan  8 2021, 17:17:17) 
    [Clang 12.0.0 (clang-1200.0.32.28)]
    Version info.
    sys.version_info(major=3, minor=9, micro=1, releaselevel='final', serial=0)
    ~/tmp/pyenv % 

IMHO that is inconsistent – and more inconsistent than before removing this feature.

**Comment by native-api** [comment]
> @native-api Maybe I am wrong, but I would expect this:
> 
>     1. `#!/usr/bin/env python` means: give me the currently installed Python 2 version
> 
>     2. `#!/usr/bin/env python3` means: give me the currently installed Python 3 version
> 

Yes, and that's exactly what you're getting with `#!/usr/bin/env python3`.
 
> > Specifically: how are you going to distinguish between cases where you want to use the Python inferred from the script's dir, and where you don't? The shebang you gave gives the invoked program no indication whatsoever what your intent is: whether you invoke `python3 prog.py` or `./prog.py`, the same command line is executed.
> 
> I don't want to distinguish. I believe, it is utterly inconsistent that the same script invoked in the exact same way but with different cwd works differently. I think `pyenv` behaves more inconsistent than before.

It's Pyenv's feature to use different Python versions when you invoke `python` depending on cwd -- so it's hardly something unexpected or "inconsistent". **This feature makes the shebang `#!/usr/bin/env python3` inherently cwd-dependent** -- so I fail to see how you're using a cwd-sensitive shebang and make a surprised Pikachu face when this sensitivity suddenly comes into effect.

> IMHO that is inconsistent – and more inconsistent than before removing this feature.

I fail to see how you expect a consistent behavior in your scenario at all. On your machine, you want the codebase to enforce a specific Python version -- but on others, you want the exact same codebase to suddenly be fine with whatever happens to be installed? How does that make sense? And how does it make sense to call _that_ "consistent behavior" while using the currently selected version everywhere "inconsistent"?

Either use a Pyenv shebang to enforce it everywhere (since regular Python doesn't provide any facilities to enforce a specific version other than `#!/usr/bin/env pythonX.Y` which only enforces up to a minor version), or don't enforce it everywhere and take it upon yourself to watch which version is currently selected on your machine.

In fact, if you use `#!/usr/bin/env pythonX.Y` as shebang, you can select multiple versions with Pyenv and the first one in the list that satisfies "`pythonX.Y`" will be used.

**Comment by martingd** [comment]
@native-api First of all: When people write things like “_make a surprised Pikachu face_” I am out of here. I don't talk like that to others and when other's talk like that to me, I don't see any reason to continue discussing, so let's finish here.

Thanks for the suggestion regarding `#!/usr/bin/env pythonX.Y`. However, it has the same problem when using `pyenv` and only works if the cwd is the dir where the script and the `.python-version` file exists.

> I fail to see how you expect a consistent behavior in your scenario at all. On your machine, you want the codebase to enforce a specific Python version -- but on others, you want the exact same codebase to suddenly be fine with whatever happens to be installed? How does that make sense? And how does it make sense to call _that_ "consistent behavior" while using the currently selected version everywhere "inconsistent"?

I don't get your argument at all. Normally, people use the `#!/usr/bin/env python3` shebang to say: “Please, give me Python3 – whatever minor version that may be.” So on different machines, the exact same codebase will already get different Python versions because it depends on what version is installed. With`pyenv`you extend that to: “…but in this directory, give me specifically this version of Python 3.”

I understand perfectly well that `pyenv`'s feature is to make `#!/usr/bin/env python3` (and similar shebangs) cwd dependent. I find it a consistent extension of that behaviour to be extended to the location of the script. This way the semantics of the shebang is not _current working dir_ dependent but _dir_ dependent, which is what I would expect. We seem to disagree on that point, so let's stop here.

**Comment by martingd** [comment]
@native-api For the record: I sincerely appreciate the work put into this project by you and others and my intention commenting on this issue was not to offend you or anyone else but simply to provide input to this issue. Have a good day. :)

**Comment by martingd** [comment]
The feature that has been removed is exactly how `rbenv` works – which `pyenv` (according to the docs) has been forked from. It seems that `rbenv` has had this functionality documented for 8 years – since commit [1cc7536](https://github.com/rbenv/rbenv/commit/1cc75362d6e5ffcff3e610def863049717734292) on 7 Aug 2013.

I understand the feature was undocumented and possibly broken. However, it was a very important feature of `pyenv` that is now gone.

**Comment by native-api** [comment]
@martingd I apologise if I offended you, that never was my intention. (That phrase is typically used to emphasize the comedic effect of people acting ignorant and getting genuinely surprised by what is a logical consequence of their actions. I've seen it being used many times without any ill effects which lead me to think it's no big deal.)


> With`pyenv`you extend that to: “…but in this directory, give me specifically this version of Python 3.”
> 
> I understand perfectly well that `pyenv`'s feature is to make `#!/usr/bin/env python3` (and similar shebangs) cwd dependent. I find it a consistent extension of that behaviour to be extended to the location of the script.

Correct. The only problem is that Pyenv's `local` feature is supposed to make Python version dependent on the _current directory,_ not _the location of the script._
Having it suddenly switch to the location of the script instead was an inconsistency. Moreover, it was impossible to _not_  switch -- which people do sometimes want.

So **going forward, we have to invent some way to allow to _both_ switch and not switch, in some more-or-less intuitive way.**
https://github.com/pyenv/pyenv/issues/1813#issuecomment-778755503 allows that, with semantics consistent with what you get when you invoke `python prog,py` vs `./prog,py` without Pyenv -- making it a very intuitive and expected behavior.
If you're dead set on using `#!/usr/bin/env python3` no matter what, you'll need to invent some other indicator that'd hopefully be not counterintuitive.

> The feature that has been removed is exactly how rbenv works <...> I understand the feature was undocumented and possibly broken.

See above. It's not "possibly" broken, it's broken and has actually caused problems in real use. And it's broken in Rbenv just as well.

**Comment by martingd** [comment]
@native-api Apology accepted. I was probably a bit too sensitive there. Sorry about that. :)

> If you're dead set on using #!/usr/bin/env python3 no matter what, you'll need to invent some other indicator that'd hopefully be not counterintuitive.

The way I used `pyenv` was to be able to use a specific Python version for scripts that are not necessarily under my control – e.g., scripts maintained by others. It was very convenient simply to drop a `.python-version` file with the desired Python version in the folder of the script. That's why I am not in favour of having to change the shebang – or anything else in the script itself for that matter.

When invoking a script with `scriptname` (no absolute or relative path provided) and the script being picked up via the PATH (or via a symlink in the PATH) I find the no longer existing functionality not only useful but also intuitive – and not surprising. I understand it is broken and difficult to fix – nevertheless I will missing this functionality which was my main reason to use `pyenv`.

**Comment by native-api** [comment]
@martingd Maybe [this feature request of a separate configurable set of "static shims"](https://github.com/pyenv/pyenv/issues/1918#issuecomment-841888379) will make you feel better?
If you're using a tool from inside some codebase elsewhere, you're probably interested to see it in `PATH` -- which lends itself nicely to that feature.

The proposer implemented it as a plugin -- however, they were fine with breaking most of Pyenv's functionality in the process (in particular, they only need one Python version active for everything) so it'll probably need work to be fit for general-purpose use.

**Comment by martingd** [comment]
@native-api Sounds interesting. However, seems like a lot of work for something I can accomplish with a simple alias setting `PYENV_VERSION` to launch my python script in the right environment. Thanks for the pointer. I will take a closer look.
