### ISSUE TITLE
Consider Homebrew OpenSSL and readline broken if built for the wrong architecture and use built-in builds

### ISSUE THREAD

**Issue by FiloSottile** [pyenv/pyenv#1816]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS 11.2
- [x] OS architecture (e.g. amd64): arm64
- [x] pyenv version: 1.2.22
- [x] Python version: 3.9.1
- [ ] C Compiler information (e.g. gcc 7.3): 
- [x] Please attach verbose build log as gist
  * https://gist.githubusercontent.com/FiloSottile/331b649bd552124cee6ef3f5b5456b52/raw/e49482bfdc4b382b55e11ff666e6fcd1fa21b853/gistfile1.txt

I tried building a version of Python under Rosetta 2 in the most naive possible way.

That failed, presumably because my Homebrew install is a native install, meaning the OpenSSL and readline libraries it installs are built for arm64, while this Python is being built for x86_64.

```
$ arch -x86_64 pyenv install 3.9.1
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.9.1.tar.xz...
-> https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tar.xz
Installing Python-3.9.1...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (OS X 11.2 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/_j/hq4ytn1n4b94fhrpvvb9tktr0000gn/T/python-build.20210215035921.19142
Results logged to /var/folders/_j/hq4ytn1n4b94fhrpvvb9tktr0000gn/T/python-build.20210215035921.19142.log

Last 10 log lines:
	fi
Looking in links: /var/folders/_j/hq4ytn1n4b94fhrpvvb9tktr0000gn/T/tmphis28s01
Processing /private/var/folders/_j/hq4ytn1n4b94fhrpvvb9tktr0000gn/T/tmphis28s01/setuptools-49.2.1-py3-none-any.whl
Processing /private/var/folders/_j/hq4ytn1n4b94fhrpvvb9tktr0000gn/T/tmphis28s01/pip-20.2.3-py2.py3-none-any.whl
Installing collected packages: setuptools, pip
  WARNING: The script easy_install-3.9 is installed in '/Users/filippo/.pyenv/rosetta/versions/3.9.1/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts pip3 and pip3.9 are installed in '/Users/filippo/.pyenv/rosetta/versions/3.9.1/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-20.2.3 setuptools-49.2.1
```

I could have installed a whole Homebrew tree under Rosetta and have pointed pyenv at that, but I realized python-build has the ability to build the two libraries by itself.

I modified the definition to remove `--if has_broken_mac_readline` and `--if has_broken_mac_openssl`

```
#require_gcc
prefer_openssl11
export PYTHON_BUILD_CONFIGURE_WITH_OPENSSL=1
install_package "openssl-1.1.0j" "https://www.openssl.org/source/old/1.1.0/openssl-1.1.0j.tar.gz#31bec6c203ce1a8e93d5994f4ed304c63ccf07676118b6634edded12ad1b3246" mac_openssl
install_package "readline-8.0" "https://ftpmirror.gnu.org/readline/readline-8.0.tar.gz#e339f51971478d369f8a053a330a190781acb9864cf4c541060f12078948e461" mac_readline
if has_tar_xz_support; then
    install_package "Python-3.9.1" "https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tar.xz#991c3f8ac97992f3d308fefeb03a64db462574eadbff34ce8bc5bb583d9903ff" ldflags_dirs standard verify_py39 copy_python_gdb ensurepip
else
    install_package "Python-3.9.1" "https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tgz#29cb91ba038346da0bd9ab84a0a55a845d872c341a4da6879f462e94c741f117" ldflags_dirs standard verify_py39 copy_python_gdb ensurepip
fi
```

and installed it with python-build.

```
$ arch -x86_64 python-build 3.9.1-rosetta2 ~/.pyenv/versions/3.9.1-rosetta2
Downloading openssl-1.1.0j.tar.gz...
-> https://www.openssl.org/source/old/1.1.0/openssl-1.1.0j.tar.gz
Installing openssl-1.1.0j...
Installed openssl-1.1.0j to /Users/filippo/.pyenv/versions/3.9.1-rosetta2

Downloading readline-8.0.tar.gz...
-> https://ftpmirror.gnu.org/readline/readline-8.0.tar.gz
Installing readline-8.0...
Installed readline-8.0 to /Users/filippo/.pyenv/versions/3.9.1-rosetta2

Downloading Python-3.9.1.tar.xz...
-> https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tar.xz
Installing Python-3.9.1...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Installed Python-3.9.1 to /Users/filippo/.pyenv/versions/3.9.1-rosetta2
```

It went almost perfectly!

However, for some reason, it still reached for the Homebrew readline in the build.

1. Can `--if has_broken_mac_readline` and `--if has_broken_mac_openssl` be considered automatically true when they are built for the wrong architecture?
2. Shouldn't python-build use the readonly it built?

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/issues/1877#issuecomment-832973181: 

> Logically speaking. if you have two Homebrew installations for different architectures (thus different software ecosystems), you should have a separate Pyenv installation in each of them, and there should be some facility to choose which of these Homebrew installations you want to use -- so that you get the `pyenv` instance that corresponds to it.
