### ISSUE TITLE
pyenv init ignored in ZSH

### ISSUE THREAD

**Issue by aartek** [pyenv/pyenv#1819]
### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information: OSX Big Sur 11.2.1
- [ ] OS architecture (e.g. amd64):
- [X] pyenv version: 1.2.22
- [X] Python version: every 
- [ ] C Compiler information (e.g. gcc 7.3)
- [ ] Please attach verbose build log as gist

===

Hi, when I use `pyenv shell` in the script it always fails with 
```
pyenv: shell integration not enabled. Run `pyenv init' for instructions.
```
Of course I've followed the instruction and put `eval "$(pyenv init -)"` in `~/.zshrc` and when I execute `pyenv shell` directly in the terminal it gives an expected output `pyenv: no shell-specific version configured`

Script:
```
#!/bin/zsh

echo "\$SHELL env variable = $SHELL"

cat ~/.zshrc | grep 'eval "$(pyenv init -)"' > /dev/null
if [[ $? -gt 0 ]]; then
    echo "Adding pyenv initialization to ~/.zshrc"
    echo 'eval "$(pyenv init -)"' >> ~/.zshrc
    eval "$(pyenv init -)"
fi

pyenv shell 2.7.17
```

Output:
```
$SHELL env variable = /bin/zsh
pyenv: shell integration not enabled. Run `pyenv init' for instructions.
```

My `~/.zshrc`
```
export PATH="/usr/local/opt/libpq/bin:$PATH"
export PATH="/usr/local/Cellar/python/3.7.6_1/bin:$PATH"

eval "$(pyenv init -)"
```

**Comment by native-api** [comment]
> if [[ $? -gt 0 ]]; then

This condition is only true if Grep _failed_ to find the corresponding line. So that block is never executed.

**Comment by native-api** [comment]
You can't use `pyenv shell` in a script. That's because the interpreter running the script does not inherit shell functions from your interactive interpreter, and this command only works if `pyenv` is a shell function.

Instead, run `PYENV_VERSION=<version> pyenv exec <command>`.

**Comment by aartek** [comment]
This helps. Thanks.
