### ISSUE TITLE
Pulls Chinese language  README-zh-cn.md

### ISSUE THREAD

**Issue by pgy866** [pyenv/pyenv#1821]
Pulls Chinese language  README-zh-cn.md

https://github.com/pgy866/pyenv/blob/master/README-zh-cn.md

**Comment by anton-petrov** [comment]
@pgy866, please, make a PR.

**Comment by pgy866** [comment]
I’m sorry. I don’t know how to conduct PR？ I don’t seem to have permission.

**Comment by defp** [comment]
@pgy866
1 fork first   
2 update fork repo 
3 open pull request

**Comment by native-api** [comment]
Is this such a good idea? Who's going to maintain it?

Any change in the `README.md` would need to be reflected in the translation, and whoever would be proposing a change likely doesn't speak Chinese so they won't be able to do that.

**Comment by native-api** [comment]
And if the translation gets out of sync, it would me inaccurate thus misleading and harmful -- so only synchronizing it from time to time is not an option.

**Comment by pgy866** [comment]
@native-api Please add automatically synchronized multi-language documents to solve the problem that cannot be synchronized in time, so that the community can maintain the translation in time

**Comment by pgy866** [comment]
> @ pgy866
> 1个叉子优先
> 2个更新叉子回购
> 3个打开请求

抱歉，我好像没有学会如何操作，其他的项目，只需要点PULLs提交即可，这个我点了不行呢

**Comment by native-api** [comment]
> automatically synchronized multi-language documents

I've no idea what you're talking about. If something like this is an actual thing, please give some details of how you envision this to work.
Otherwise, since it's impossible for us to maintain, we're getting nowhere.

**Comment by pgy866** [comment]
Is it possible to use ”.po“ files for multi-language markup translation projects，https://crowdin.com/project

**Comment by native-api** [comment]
> 
> 
> Is it possible to use ”.po“ files for multi-language markup translation projects，https://crowdin.com/project

No, it's not. `.po` files are for the [Gettext](https://en.wikipedia.org/wiki/Gettext) library. Thery are only good to localize messages in programs, there's no way to utilize it here, when viewing markdown files at Github.

**Comment by native-api** [comment]
There's a proposed feature to automatically switch to a localized README: https://github.com/github/markup/issues/899 . The closure notice says that that ticket is misplaced and suggests writing to Github Support proposing it. Judging by thr thread, using `README-<locale>.md` does seem to be the standard as of now.

**Comment by native-api** [comment]
I have to close this because no-one stepped up and offered to keep the translation up to date. And there'd been no traction for the general idea, either.

In technical documentation, factual accuracy is more important than the convenience of reading stuff in your native language.
