### ISSUE TITLE
`pyenv which` regression: now returns non-pyenv results

### ISSUE THREAD

**Issue by philpennock** [pyenv/pyenv#1827]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
* [x] Make sure your problem is not derived from plugins.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu Linux 20.04
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 1.2.23
- [x] Python version: 3.9.2
- [x] C Compiler information (e.g. gcc 7.3): gcc 9.3.0-17ubuntu1~20.04
- [x] Please attach verbose build log as gist: _n/a_

#### Regression

There has been a change in behavior of `pyenv which`: it can now return executables not provided by pyenv itself, but instead from `$PATH`.

For some commands, I unfortunately need to shim in front of pyenv.  Eg, if I have a command only available in some pyenvs which needs to be available always.  (Think "make `aws` available as a command, always").

My shim prefix used `pyenv which "$exe_name"` as a way to detect if the current pyenv had the relevant executable shim.  This previously worked, as it would fail (returning non-zero) when there was no such `$exe_name` in the current pyenv.  Now, this can return the non-pyenv executable shim.

If `pyenv which` is no longer appropriate and this regression is expected/desired behavior, what is the _correct_ way to detect if the current env provides a given executable, please?

**Comment by anton-petrov** [comment]
Hi @philpennock , please, provide an example, when 
> Now, this can return the non-pyenv executable shim.

**Comment by anton-petrov** [comment]
@philpennock 
Yes, that happens due to this [PR](https://github.com/pyenv/pyenv/pull/1797), and that is expected behavior. Please, give me some time to decide how to add the required functionality. Best regards.
