### ISSUE TITLE
not found pip

### ISSUE THREAD

**Issue by lisonge** [pyenv/pyenv#1828]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 20.04.2 LTS
- [ ] OS architecture (e.g. amd64): Linux Lisonge 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- [ ] pyenv version: 1.2.23
- [ ] Python version: 3.8.8
- [ ] C Compiler information (e.g. gcc 7.3): gcc  4:9.3.0-1ubuntu2
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

```shell
❯ pyenv -v
pyenv 1.2.23
❯ pyenv versions
* system (set by /home/lisonge/.pyenv/version)
❯ pyenv install 3.8.8
Downloading Python-3.8.8.tar.xz...
-> https://www.python.org/ftp/python/3.8.8/Python-3.8.8.tar.xz
Installing Python-3.8.8...
Installed Python-3.8.8 to /home/lisonge/.pyenv/versions/3.8.8

❯ cd /home/lisonge/.pyenv/versions/3.8.8
❯ ls .
bin  include  lib  share
❯ ls /home/lisonge/.pyenv/versions/3.8.8/bin
2to3      easy_install      idle   idle3.8  pydoc3    python         python3         python3.8         python3.8-gdb.py
2to3-3.8  easy_install-3.8  idle3  pydoc    pydoc3.8  python-config  python3-config  python3.8-config
```

where is pip ?

**Comment by Sapphire64** [comment]
The latest supported version of Python 3.8 in 1.2.23 is 3.8.7:
`python-build: Add CPython 3.8.7`
How did you add 3.8.8?

**Comment by lisonge** [comment]
> The latest supported version of Python 3.8 in 1.2.23 is 3.8.7:
> `python-build: Add CPython 3.8.7`
> How did you add 3.8.8?

```shell
cd $(pyenv root)
git pull
```

**Comment by cclauss** [comment]
@yyuu Can we please get a [pyenv release](https://github.com/pyenv/pyenv/releases) that supports CPython v3.8.8 and CPython v3.9.2?  Our project would like to have the [security fixes](https://pythoninsider.blogspot.com/2021/02/python-392-and-388-are-now-available.html) in these recent versions of CPython.

**Comment by john-sandall** [comment]
@cclauss [v1.2.24](https://github.com/pyenv/pyenv/releases/tag/1.2.24) added support for 3.8.8 and 3.9.2, so hopefully `brew update && brew upgrade pyenv` solves your problem.

I also had the issue of needing to update my xcode cli tools, so running the following was also required:

```bash
xcode-select --install
brew update && brew upgrade pyenv
pyenv install 3.8.8
```
