### ISSUE TITLE
macos 11.2  pip install  packages  error /usr/local/Cellar/pyenv/1.2.15/pyenv.d/exec/pip-rehash/pip: line 20:  1387 Illegal instruction: 4  "$PYENV_COMMAND_PATH" "$@"

### ISSUE THREAD

**Issue by qiusheng2011** [pyenv/pyenv#1836]
macos 11.2 pip install packages error /usr/local/Cellar/pyenv/1.2.15/pyenv.d/exec/pip-rehash/pip: line 20: 1387 Illegal instruction: 4 "$PYENV_COMMAND_PATH" "$@

**Comment by anton-petrov** [comment]
Please, install latest pyenv 1.2.23.

**Comment by qiusheng2011** [comment]
when inter macbook to m1 book  ,upgrade pyenv then reinstall python
