### ISSUE TITLE
How to install pyenv system-wide

### ISSUE THREAD

**Issue by albireox** [pyenv/pyenv#1843]
I was wondering if there are recommendations on how to setup pyenv as a system-wide service. The default pyenv installation assumes a single user which clones/installs pyenv in `~/.pyenv`. But I think a normal use-case is to have multiple users that want to access the same Python installations, virtual environments, etc. This introduces a problem with permissions, since by default a user cannot install new packages in a given version.

My approach to this issue has been to install pyenv in a global location (e.g. `/opt/pyenv`), adjusting the value of `$PYENV_ROOT` and accoladed, and then change the default permissions of that directory so that a given user group `mygroup` can use it

```
sudo chown -R <myuser>:<mygroup> /opt/pyenv
chmod -R g+s /opt/pyenv
setfacl -R -d -m g:<mygroup>:rwx /opt/pyenv/
setfacl -R -m g:<mygroup>:rwx /opt/pyenv/
```

This mostly works but it's a bit cumbersome and has some caveats. Is there a better way to achieve this, and if so, could that be added to the installation/wiki documentation?

**Comment by native-api** [comment]
> I was wondering if there are recommendations on how to setup pyenv as a system-wide service.

There are none as this is not a typical setup and the codebase isn't designed with it in mind (e.g. it doesn't contain any user-friendly error messages if a user tries to execute privileged commands: they would see the raw permission errors).

> This introduces a problem with permissions, since by default a user cannot install new packages in a given version.

With virtualenvs, you don't need to install any packages globally in the course of daily work. Shared virtualenvs would only make users step on each other's toes.

For a project-centric setup, I would recommend `pipenv`: it creates virtualenvs on demand and ensures that they conform to specification files in the project tree.

**Comment by huydhoang** [comment]
> This mostly works but it's a bit cumbersome and has some caveats. 

What caveats did you face specifically?

**Comment by albireox** [comment]
Sorry for the delayed reply. Most things work or when they fail is because some other utility such as poetry doing weird things with the permissions. One thing that pyenv does is to not respect the default permissions in `$PYENV_ROOT/versions` when a new version is installed (virtual environment are ok). For example, I have the ACL permissions in that directory set to `rwx` for the group, but when pyenv installs a new version the permissions default to `r-x`. Not terribly annoying but I wonder if there's a good reason for that.

**Comment by native-api** [comment]
> For example, I have the ACL permissions in that directory set to `rwx` for the group

What do you mean? In basic Linux, there's no such thing as "default permission for directory", there's just umask which is directory-independent.

**Comment by albireox** [comment]
You can use [setfacl](https://linux.die.net/man/1/setfacl) to set directory dependent permissions. That's independent of the sticky bit or umask, as far as I understand it.

**Comment by JoeJasinski** [comment]
Hi, I'm looking to do the same thing. Basically install pyenv in /opt/pyenv/, but then give each user the ability to create their own pyenv virtualenvs in their home directory. But this seems seems to want to use the PYENV_ROOT and seems klinda hard-coded, if I'm seeing correctly.

https://github.com/pyenv/pyenv-virtualenv/blob/294f64f76b6b7fbf1a22a4ebba7710faa75c21f7/bin/pyenv-virtualenv#L356

Effectively, I want to give users the ability to create virtualenvs based on pyenv-installed python versions. But I'm not able to have users privately install pyenv in their home directories, install and compile pyenv python versions in their home directories as well, and then create pyenv virtualenvs off of that. Instead, I'd like users to be able to create virtualenvs in their home directories, based on existing python versions installed in /opt/pyenv/. 

Is this possible with pyenv?

**Comment by albireox** [comment]
I wonder if for that case (wanting to create virtual environments that are not managed/co-located with pyenv) you would be better using `virtualenv` directly. I haven't had problems doing that:

1. You set the pyenv version that you want the virtual environment (e.g., `pyenv shell 3.6.3`)
2. Create the virtual environment `virtualenv ~/venvs/my_venv_3`.
3. Load the environment `source ~/venvs/my_venv_3/bin/activate`

That will make `python` point to the pyenv version you used to create the environment, even if later you change the pyenv version.

Unfortunately I do want pyenv to manage my virtual environments for multiple users, but that's were some problems appear :)

**Comment by JoeJasinski** [comment]
Thank you @albireox for your feedback. That's a good idea to just use good old virtualenv (without the pyenv plugin). I'll play around with that and see if it will work for my use-case. Thanks again

**Comment by native-api** [comment]
> But this seems seems to want to use the PYENV_ROOT and seems klinda hard-coded, if I'm seeing correctly.
> 
> https://github.com/pyenv/pyenv-virtualenv/blob/294f64f76b6b7fbf1a22a4ebba7710faa75c21f7/bin/pyenv-virtualenv#L356
> 

That's Pyenv-Virtualenv's problem, create an issue there.

Strictly speaking. `PYENV_ROOT` doesn't need to be where the `pyenv` executable is installed. E.g. in MacOS Homebrew, Pyenv is installed into `$(brew --prefix)` while user files are still under `~/.pyenv`.
However, alternative Python versions and shims are expected to be found under `PYENV_ROOT` -- so if you set it to `~/.pyenv`, you won't see the alternative versions installed system-wide.
