### ISSUE TITLE
infocmp shim still exists after installing miniconda3-latest and rehashing

### ISSUE THREAD

**Issue by ackalker** [pyenv/pyenv#1848]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Void Linux (rolling release)
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: pyenv 1.2.23-75-g80e418ec
- [x] Python version: Python 3.8.5
- [x] C Compiler information (e.g. gcc 7.3): gcc version 10.2.1 20201203 (GCC)
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

After installing miniconda3-latest using pyenv, there is still a shim for `infocmp` executable, even after #1358 was merged. My `$HOME/.pyenv/pyenv.d/rehash/conda.d/default.list` does contain an entry for `infocmp`.

### Steps to reproduce (with output)
```
$ pyenv install miniconda3-latest
[...]
$ pyenv rehash
$ hash -r
$ pyenv shell miniconda3-latest
$ which infocmp
/home/$USER/.pyenv/shims/infocmp
$ pyenv which infocmp 
/home/$USER/.pyenv/versions/miniconda3-latest/bin/infocmp
$ pyenv whence infocmp 
miniconda3-latest
$ pyenv shims | grep infocmp
/home/$USER/.pyenv/shims/infocmp
$ grep -r infocmp ~/.pyenv/pyenv.d/
/home/$USER/.pyenv/pyenv.d/rehash/conda.d/default.list:infocmp
```

While the infocmp shim appears to work on my setup for now, I'd rather not have other programs use infocmp and such installed by miniconda, given previous mishaps such as those mentioned in #1085.

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/issues/1085#issuecomment-835902980
