### ISSUE TITLE
Trouble Switching Python Versions

### ISSUE THREAD

**Issue by jackmaney** [pyenv/pyenv#185]
I'm using OSX Mavericks (10.9.3) on pyenv version 0.4.0-20140602. I'm finding that pyenv rarely switches installed versions of python. Somehow, I got pyenv to switch from the system python to 2.7.7, but I can't switch it to anything else:

```
jackmaney@Jacks-Mac-mini:~$ python --version
Python 2.7.7
jackmaney@Jacks-Mac-mini:~$ pyenv versions
  system
* 2.7.7 (set by /Users/jackmaney/.python-version)
  3.4.1
```

Okay, so far, so good...pyenv recognizes both versions that it installed (2.7.7 and 3.4.1). Let's try to switch to 3.4.1:

```
jackmaney@Jacks-Mac-mini:~$ pyenv global 3.4.1
jackmaney@Jacks-Mac-mini:~$ python --version
Python 2.7.7
jackmaney@Jacks-Mac-mini:~$ pyenv versions
  system
* 2.7.7 (set by /Users/jackmaney/.python-version)
  3.4.1
```

No dice... The same thing happens if I try to switch back to the system Python:

```
jackmaney@Jacks-Mac-mini:~$ pyenv global system
jackmaney@Jacks-Mac-mini:~$ python --version
Python 2.7.7
jackmaney@Jacks-Mac-mini:~$ pyenv versions
  system
* 2.7.7 (set by /Users/jackmaney/.python-version)
  3.4.1
```

I've set up the `eval` command and have `$PYENV_ROOT` set to the correct directory:

```
jackmaney@Jacks-Mac-mini:~$ echo $PYENV_ROOT
/usr/local/opt/pyenv
```

Also, both of `$PYENV_ROOT/bin` and `$PYENV_ROOT/shims` are in my `$PATH`.

My apologies if I'm missing something obvious.

**Comment by fphilipe** [comment]
Just ran into this issue. I followed the installation instruction from `brew info pyenv`:

```
To enable shims and autocompletion add to your profile:
  if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

To use Homebrew's directories rather than ~/.pyenv add to your profile:
  export PYENV_ROOT=/usr/local/var/pyenv
```

So I had the `export` after the `if`, which caused it to not work. Having the export *before* the pyenv initialization fixes it and, in hindsight, is obvious that the var should be set before. It might be a good idea to update the installation instruction on the homebrew package to say:

> To use Homebrew's directories rather than ~/.pyenv add to your profile before the line above:
