### ISSUE TITLE
Support for python 3.8.8 and 3.9.2 not released

### ISSUE THREAD

**Issue by giucataldi16** [pyenv/pyenv#1852]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ x Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS Catalina 10.15.7
- [ ] OS architecture (e.g. amd64):
- [x] pyenv version: 1.2.23
- [x] Python version: ideally, 3.8.8 and 3.9.2, but they are not listed by pyenv
- [ ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`
  
  When running `pyenv install --list` these two versions are missing.
  The support is present in pyenv master branch, but it wasn't released.

**Comment by anton-petrov** [comment]
Pyenv [1.2.24](https://github.com/pyenv/pyenv/releases/tag/1.2.24) released.
