### ISSUE TITLE
Handle arm64 and x86_64 versions on m1 silicon

### ISSUE THREAD

**Issue by louisabraham** [pyenv/pyenv#1853]
I first installed pyenv with brew for arm64. However, I needed some python packages that are not yet easily installable for arm64 so I reinstalled pyenw with brew for  x86_64 and compiled a python version (I had to use custom CFLAGS and LDFLAGS for openssl because I have 2 brew installations). After upgrading pip (I don't get why I needed to), it can finally download and install prebuilt binaries. However, this comes at a performance cost.

I would like to be able to have two different python versions, a native one and a x86_64 one and switch between them using pyenv. I think this won't need a lot of changes in pyenv per se as it is mostly bash code that can be run on both architectures. However, I need to be able to select what architecture I want to compile python for and this setting to be stored for `pyenv versions` to be useful.

**Comment by joshfriend** [comment]
is invoking python with `arch -x86_64` before it an option? e.g. `arch -x86_64 pyenv install ...`

theoretically that starts the process off inside rosetta and everything that happens after that would also be in x86_64 mode, but I don't have an M1 mac available to test.

**Comment by louisabraham** [comment]
This *might* work, although I have to manually change the compilation flags (maybe because I have two brew installs)

```
alias brew86='arch -x86_64 /usr/local/bin/brew'
 CFLAGS="-I$(brew86 --prefix openssl)/include" \
LDFLAGS="-L$(brew86 --prefix openssl)/lib" \
pyenv install 3.8.8
```

The problem is that pyenv doesn't _understand_ that I could have two times the same version, but for different architectures. Also, it won't put the architecture in the name of the version.

**Comment by joshfriend** [comment]
Someone made a pyenv plugin that allows you to install the same python multiple times with different options: https://github.com/s1341/pyenv-alias

I agree this might be a good thing to support in pyenv itself though.

**Comment by native-api** [comment]
With 2 Homebrew installs, you should have 2 Pyenv installs, too -- each with its own set of Python installations for the corresponding architecture.

https://stackoverflow.com/questions/64951024/how-can-i-run-two-isolated-installations-of-homebrew has some advice on how to use both as needed and not go bonkers in the process.

**Comment by louisabraham** [comment]
Thanks @native-api !
I'm already doing that for brew. However pyenv always uses the same install directory (`~/.pyenv`) so two install would clash, wouldn't they? Did you test this method yourself?

**Comment by native-api** [comment]
Yes, they would. I was planning to propose a feature to install Python under an alias to circumvent this (there are also other use cases, too).

But you don't really need two installations of the same version of Python in the common use case, do you?

**Comment by berendkleinhaneveld** [comment]
> However pyenv always uses the same install directory (`~/.pyenv`) so two install would clash, wouldn't they? Did you test this method yourself?

I have both arm64 and x86_64 versions of brew installed and I have pyenv use another install directory by having something like this in your .bashrc/zshrc:
```sh
if [[ $(arch) != arm64* ]]
then
	eval "$(/usr/local/bin/brew shellenv)"
	export PYENV_ROOT="$HOME/.pyenv-x86"
else
	eval "$(/opt/homebrew/bin/brew shellenv)"
	# default PYENV_ROOT => $HOME/.pyenv
fi
```

**Comment by native-api** [comment]
@berendkleinhaneveld Actually, how do you start terminals for different architectures? I presume that would be the main problem for an average user.

**Comment by berendkleinhaneveld** [comment]
I use iTerm2 and have different profiles. One profile is simple configured with the 'login shell' (which on my system is `/bin/zsh`) which is the native shell (running `arch` echoes: `arm64`).
The other profile uses a custom command: 
```sh
arch -x86_64 /bin/zsh
```
which makes it so that `arch` gives me `i386`.

**Comment by louisabraham** [comment]
I copied the terminal.app, renamed one of them to "Intel Terminal" and ticked "Open with Rosetta" in the Finder "Get Info" menu.

**Comment by native-api** [comment]
> I use iTerm2 and have different profiles. One profile is simple configured with the 'login shell' (which on my system is /bin/zsh) 
> The other profile uses a custom command: `arch -x86_64 /bin/zsh`

> I copied the terminal.app, renamed one of them to "Intel Terminal" and ticked "Open with Rosetta" in the Finder "Get Info" menu.

In this case, you can set a different `PYENV_ROOT` for one of the architectures in `~/.zprofile` so that installed Python versions are separated:

```
if [[ $(arch) == "i386" ]];then
  export PYENV_ROOT=~/.pyenv-i386
fi
```

**Comment by bhrutledge** [comment]
I was able to install Python 3.6 on my M1 MacBook Air running macOS Big Sur 11.3.1. First, [create a second Homebrew installation for `x86_64`](https://www.wisdomgeek.com/development/installing-intel-based-packages-using-homebrew-on-the-m1-mac/), then use that to install a second pyenv for `x86_64`:

```
% arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"                                         

% eval "$(/usr/local/bin/brew shellenv)"

% arch -x86_64 brew install pyenv
```

The `eval` ensures that `brew` and `pyenv` will run from `/usr/local/bin` and that `HOMEBREW_PREFIX`, etc. points to `/usr/local`.

In the same shell, install Python 3.6 with the necessary patch for Big Sur:

```
% arch -x86_64 pyenv install --patch 3.6.13 < <(curl -sSL https://github.com/python/cpython/commit/8ea6353.patch\?full_index\=1)
```

In a fresh shell (i.e., where `pyenv` runs from `/opt/homebrew/bin/`, which means `arm64`):

```
% pyenv shell 3.6.13

% pyenv which python3
/Users/bhrutledge/.pyenv/versions/3.6.13/bin/python3

% python3 --version
Python 3.6.13
```

So, it looks like as long as you `pyenv install` in an `x86_64` Homebrew environment, you can still use that version in an `arm64` environment. 🎉 

Note that I didn't set `CFLAGS`, `CPPFLAGS`, or `LDFLAGS`, nor did I run a shell under `x86_64`. I tried all of those things first, but still got errors about OpenSSL. The trick seems to be setting up the environment with `eval`.

This all comes with the caveat that I haven't used this install of Python 3.6 for anything real yet. I was able to create a virtual environment and `pip install pandas`, so I'm cautiously optimistic. 🤞

**Comment by native-api** [comment]
I guess we could use a wiki page or something on how to use Pyenv under Apple M1.

The current advice boils down to https://github.com/pyenv/pyenv/issues/1853#issuecomment-834002669 and https://github.com/pyenv/pyenv/issues/1853#issuecomment-851718442

**Comment by native-api** [comment]
If someone interested in seeing such a wiki page can compose one, we'll gladly accept it.

**Comment by native-api** [comment]
I've recently allowed non-members to edit wikis as an experiment -- so If anyone is interested, you can compose the page yourself now.

**Comment by AdrianDAlessandro** [comment]
> Someone made a pyenv plugin that allows you to install the same python multiple times with different options: https://github.com/s1341/pyenv-alias
> 
> I agree this might be a good thing to support in pyenv itself though.

This alias plugin is now broken and the developer is unwilling to fix it. See here https://github.com/s1341/pyenv-alias/issues/3

If someone is able to look into this I will write up a wiki page for how to use Pyenv with Apple Silicon
