### ISSUE TITLE
How to make preinstalled versions of python recognizable to pyenv?

### ISSUE THREAD

**Issue by jkbhagatio** [pyenv/pyenv#1862]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 20.04
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 1.2.24
- [x] Python version: 3.7.3
- [x] C Compiler information (e.g. gcc 7.3):  gcc 7
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`
 
------------------------------------------------------------------------------------------------------------------------

The title basically says it all. I've installed some python versions from source and now I want to use pyenv, and I want pyenv to recognize these already installed python versions without me having to reinstall them with `pyenv install`. I assume I have to do something like set shims manually, but am unsure of how to do so and couldn't find relevant documentation.

**Comment by idwpan** [comment]
If you build from a tarball like

```
$ wget https://www.python.org/ftp/python/3.9.4/Python-3.9.4.tar.xz
$ tar xf Python-3.9.4.tar.xz
$ cd Python-3.9.4
$ mkdir build
$ ./configure --prefix=`pwd`/build
$ make
$ make install
```

Now `Python-3.9.4/build` will contain a few directories. Most important are `bin/`, `include/`, `lib/`, and `share/`. If you copy, or symbolically link these directories to `$(pyenv root)/versions/3.9.4` they should be detected in `pyenv`. See the other directories in `$(pyenv root)/versions` to see how they should be structured.

**Comment by jkbhagatio** [comment]
cool thanks! will close now
