### ISSUE TITLE
create tag for new python versions (3.8.9, 3.9.3)?

### ISSUE THREAD

**Issue by andrkhr** [pyenv/pyenv#1864]
What's wrong guys?
Embed the new version of python into the master, make a tag.
Why wait several weeks until you remember to do this?

**Comment by idwpan** [comment]
They are merged to master. I just tested a new VM with a fresh install from https://github.com/pyenv/pyenv-installer and 3.9.3 was available out of the box.

**Comment by cclauss** [comment]
Waiting 24 hours would not have hurt in this case because Python 3.9.4 is already released.

https://www.python.org/downloads/release/python-394/

**Comment by andrkhr** [comment]
I apologize for the slightly emotional issue. 
I am using brew and having a tag to get the latest version is very important. 
This is certainly not an excuse and I totally agree that you need to be more restrained. 
I apologize again. 
You are making a really cool product. Thank you!

**Comment by anton-petrov** [comment]
3.9.4 is a hotfix release, @cclauss , could you add this one? So I (or someone else) merge it and will publish new hotfix release a little later today.
Currently busy at work, sorry...
Thanks for patience🤗

**Comment by cclauss** [comment]
Can this issue be closed?
