### ISSUE TITLE
Limit the number of PIDs pyenv consumes

### ISSUE THREAD

**Issue by snejus** [pyenv/pyenv#1883]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): Arch 5.11.15-arch1-2
- [ ] OS architecture (e.g. amd64): x86_64
- [ ] pyenv version: 1.2.26
- [ ] Python version: Unrelated
- [ ] C Compiler information (e.g. gcc 7.3): Unrelated
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

My issue isn't related to building pythons - that's working fine. But there's something else - the ridiculous amount of processes that pyenv requires. `pyenv` command alone consumes 350 (!), see `strace -f pyenv 2>&1 | sed -rn '/\[pid ([0-9]+).*/s//\1/p' | sort -u | wc -l` and printing of the help page is very slow: 

```sh
 $ ps aux | grep grep
sarunas  3393092  0.0  0.0   9576  2448 pts/6    S+   22:20   0:00 grep --color=auto grep
 $ hyperfine 'pyenv || true'
Benchmark #1: pyenv || true
  Time (mean ± σ):     356.5 ms ±   1.5 ms    [User: 368.3 ms, System: 98.2 ms]
  Range (min … max):   354.1 ms … 358.7 ms    10 runs

hyperfine 'pyenv || true'  4.30s user 1.20s system 125% cpu 4.395 total
 $ ps aux | grep grep
sarunas  3396836  0.0  0.0   9576  2484 pts/6    S+   22:21   0:00 grep --color=auto grep
```

Having a brief look at `pyenv-help` script it does look like it's something that could be optimised. I'd probably be able to have a go at it once we confirm that this is happening not just on my machine (it may as well be some weird issue on my side but I'd doubt so).

**Comment by snejus** [comment]
Comparison between running python executables with and without pyenv:
```sh
$ which pip
/home/sarunas/.pyenv/shims/pip
$ which pipx
/home/sarunas/.pyenv/shims/pipx
$ strace -f pip 2>&1 | sed -rn '/\[pid ([0-9]+).*/s//\1/p' | sort -u | wc -l
64
$ strace -f pip list 2>&1 | sed -rn '/\[pid ([0-9]+).*/s//\1/p' | sort -u | wc -l
88
$ strace -f pipx 2>&1 | sed -rn '/\[pid ([0-9]+).*/s//\1/p' | sort -u | wc -l
47
$ pyenv version
3.6.13 (set by /home/sarunas/.pyenv/version)
$ strace -f ~/.pyenv/versions/3.6.13/bin/pip 2>&1 | sed -rn '/\[pid ([0-9]+).*/s//\1/p' | sort -u | wc -l
0
$ strace -f ~/.pyenv/versions/3.6.13/bin/pip list 2>&1 | sed -rn '/\[pid ([0-9]+).*/s//\1/p' | sort -u | wc
-l
25
$ strace -f ~/.pyenv/versions/3.6.13/bin/pipx 2>&1 | sed -rn '/\[pid ([0-9]+).*/s//\1/p' | sort -u | wc -l
3
```

**Comment by native-api** [comment]
And what's the problem with that? All shell scripts spawn lots of processes since every command line that's not a shell builtin is a separate process.
Moreover, not many processes run _at the same time:_ most of the commands finish before a script run the next command.

**Comment by snejus** [comment]
Of course - however if it takes 350 subshells to print a help page there's probably an issue somewhere. The problem is that a single tool is responsible for the majority of pids - if you have a look at the logs above you'll find that I managed to reach `3396836` in an hour or two of heavier than normal `pyenv` usage. Considering that the limit on a 64bit system is just above 4M, this was pretty near. 

Of course, this isn't a bug and most people won't realise that this is happening. Though in my case most of the day is spent in the command line relying on many python tools, so this quickly adds up.

**Comment by native-api** [comment]
Pyenv checks all the installed commands and plugins (if any) -- they are all implemented as separate scripts -- to generate the overall help so I'm not too surprised at 350.

**Comment by native-api** [comment]
Maybe I wasn't clear the first time, but I stress that this is not a problem because however many processes Pyenv starts _in total,_ only a few run _at a time._ since PIDs of processes that no longer exist are eventually reused, this is not a problem as all.

**Comment by snejus** [comment]
https://asciinema.org/a/9ICw5Q6H5aJexRFFpsFqU7HPm

Had a quick go at the help - see above. 


> Maybe I wasn't clear the first time, but I stress that this is not a problem because however many processes Pyenv starts in total, only a few run at a time. Since PIDs of processes that no longer exist are eventually reused, this is not a problem at all.

The issue talk about the former indeed. We'd be having a bit of a bigger problem if every command hung with 350 running processes :D

Though in any case, I don't think we're on the same page here - imo the nature of how linux deals with maxed pid space isn't a good reason to justify fork bombs.

**Comment by native-api** [comment]
> https://asciinema.org/a/9ICw5Q6H5aJexRFFpsFqU7HPm
> 
> Had a quick go at the help - see above.

What's `countproc`? What did you change in the codebase?

> I don't think we're on the same page here

That's true. You insist that 350 processes are running at a time -- but your data rather shows that this is the number of processes that have started (and finished) in total throughout the invocation  -- it doesn't measure how many of them were running at each moment of time. So the comparison to a fork bomb looks baseless.

If you think you can improve something without sacrificing functionality, feel free to submit a PR -- then we'll see what exactly the effect is. So far, the discussion is matterless.

**Comment by native-api** [comment]
> https://asciinema.org/a/9ICw5Q6H5aJexRFFpsFqU7HPm
> 
> Had a quick go at the help - see above.

What's `countproc`? What did you change in the codebase?

> I don't think we're on the same page here

That's true. Your data shows that this is the number of processes that have started (and finished) in total throughout the invocation  -- it doesn't measure how many of them were running at each moment of time. So the comparison to a fork bomb looks baseless. I don't see a problem with running however many processes in total needed to do the job as long as they don't strain system resources -- especially in UNIX which is specifically designed to make spawning new processes a cheap operation.

If you think you can improve something without sacrificing functionality, feel free to submit a PR -- then we'll see what exactly the effect is and if it eiminates some kind of a fork bomb or whatever. So far, the discussion is matterless: you raise some accusations but fail to support them with evidence.

**Comment by snejus** [comment]
My bad here - was meant to `which countproc` in the recording but forgot:
```sh
countproc () {
	local pre=$(zsh -c 'echo $$') 
	local pretime=($epochtime) 
	$*
	local posttime=($epochtime) 
	local post=$(zsh -c 'echo $$') 
	local sdiff=$(( posttime[1] - pretime[1] )) 
	local nsdiff=$(( posttime[2] - pretime[2] )) 
	local msdiff=$(( nsdiff / 1000000 )) 
	local usdiff=$(( (nsdiff - (msdiff * 1000000)) / 1000 )) 
	printf '%d pids, %d s / %d ms / %d us\n' $(( post - pre - 1 )) $sdiff $msdiff $usdiff
}
```

Diff for what's been done in vid:
```diff
diff --git a/libexec/pyenv-help b/libexec/pyenv-help
index c7ff6124..8c6bf5b9 100755
--- a/libexec/pyenv-help
+++ b/libexec/pyenv-help
@@ -26,68 +26,6 @@ command_path() {
   command -v pyenv-"$command" || command -v pyenv-sh-"$command" || true
 }
 
-extract_initial_comment_block() {
-  LC_ALL= \
-  LC_CTYPE=C \
-  sed -ne "
-    /^#/ !{
-      q
-    }
-
-    s/^#$/# /
-
-    /^# / {
-      s/^# //
-      p
-    }
-  "
-}
-
-collect_documentation() {
-  # shellcheck disable=SC2016
-  $(type -p gawk awk | head -1) '
-    /^Summary:/ {
-      summary = substr($0, 10)
-      next
-    }
-
-    /^Usage:/ {
-      reading_usage = 1
-      usage = usage "\n" $0
-      next
-    }
-
-    /^( *$|       )/ && reading_usage {
-      usage = usage "\n" $0
-      next
-    }
-
-    {
-      reading_usage = 0
-      help = help "\n" $0
-    }
-
-    function escape(str) {
-      gsub(/[`\\$"]/, "\\\\&", str)
-      return str
-    }
-
-    function trim(str) {
-      sub(/^\n*/, "", str)
-      sub(/\n*$/, "", str)
-      return str
-    }
-
-    END {
-      if (usage || summary) {
-        print "summary=\"" escape(summary) "\""
-        print "usage=\"" escape(trim(usage)) "\""
-        print "help=\"" escape(trim(help)) "\""
-      }
-    }
-  '
-}
-
 documentation_for() {
   local filename
   filename="$(command_path "$1")"
@@ -107,9 +45,22 @@ print_summary() {
 }
 
 print_summaries() {
-  for command; do
-    print_summary "$command"
-  done
+    mapfile commands
+    tabs 26
+    B=$'\e[1m'
+    R=$'\e[0m'
+    sed -nr '
+        /^# Summary: (.*)/{
+            s//\1/
+            h
+        }
+        /^# Usage: pyenv ([-a-z]+).*/{
+            s//\1/
+            H
+            x
+            s/(.*)\n(.*)/'"$B"'\2'"$R"'\t\1/p
+        }
+    ' $(command -v ${commands[@]/#/pyenv-} || true)
 }
 
 print_help() {
@@ -144,7 +95,7 @@ print_usage() {
 
 unset usage
 if [ "$1" = "--usage" ]; then
-  usage="1"
+  usage=1
   shift
 fi
 
@@ -153,20 +104,18 @@ if [ -z "$1" ] || [ "$1" == "pyenv" ]; then
   [ -z "$usage" ] || exit
   echo
   echo "Some useful pyenv commands are:"
-  print_summaries $(exec pyenv-commands | sort -u)
+  pyenv-commands | print_summaries
   echo
   echo "See \`pyenv help <command>' for information on a specific command."
   echo "For full documentation, see: https://github.com/pyenv/pyenv#readme"
 else
   command="$1"
-  if [ -n "$(command_path "$command")" ]; then
+  command_path "$command" && {
     if [ -n "$usage" ]; then
       print_usage "$command"
     else
       print_help "$command"
     fi
-  else
-    echo "pyenv: no such command \`$command'" >&2
+  } || echo "pyenv: no such command \`$command'" >&2
     exit 1
-  fi
 fi```

Just to clarify - this is just about optimising shell usage, stuff like using a single command (for example `sed` above) instead of looping and forking.

**Comment by native-api** [comment]
I see a number of drawbacks and functionality sacrifices made in the patch.
While the new code is simpler, it lacks some abilites like extracting full help, filtering oput internal commands, escaping special characters in output etc.
OTOH `tabs` is probably an improvement but the magic number looks jank.

**Comment by native-api** [comment]
I see a number of drawbacks and functionality sacrifices made in the patch.
While the new code is simpler, it lacks some abilites like extracting full help, filtering out internal commands, escaping special characters in output etc. All these would increase the invocation count when added back.
OTOH `tabs` is probably an improvement but the magic number looks jank.

**Comment by native-api** [comment]
All in all, I still fail to see any evidence that the current situation is detrimental for practical use so I rule this as not a bug until some conclusive evidence to the contrary is presented.

Feel free to submit a PR if you can think of a simplification of existing code or whatever, it will be judged on its own merits.
