### ISSUE TITLE
jupyter notebook not open in pyenv-virtualenv

### ISSUE THREAD

**Issue by alesss78** [pyenv/pyenv#1885]
OS version: Mac OS Big Sur 11.2.3
pyenv version: 1.2.24
python version installed with pyenv:
                                                              system (MacOS default python2)
                                                              3.7.8
                                                              3.9.0

I installed pyenv (1.2.24), virtualenv (20.4.3), and pyenv-virtualenv (1.1.5)

I edited my .zshrc file as following (don't know if this is correct, cannot understand syntax):
```Bash
alias brew='env PATH="${PATH//$(pyenv root)/shims:/}" brew'

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

if command -v pyenv &>/dev/null; then
    eval "$(pyenv init -)"
fi
if command -v pyenv-virtualenv &>/dev/null; then
    eval "$(pyenv virtualenv-init -)"
fi

eval "$(pyenv virtualenv-init -)"
```

I installed through pyenv, python versions 3.7.8 and 3.9.0 and activated globally the latter
At this stage python versions are the following
```Bash
 pyenv versions
  system
  3.7.8
* 3.9.0 (set by /Users/alesss78/.pyenv/version)
```

I installed Jupiter notebook (6.3.0) through pip with global python  
At this stage Jupyter notebook starts normally after typing "jupyter notebook" 
 
Then I tried to create a new env with: 
```Bash 
pyenv virtualenv 3.9.0 nexgen
pyenv activate nexgen 3.9.0
```
When I check "pyenv versions" this is the output:

```Bash 
  system
  3.7.8
  3.9.0
  3.9.0/envs/nexgen
* nexgen (set by PYENV_VERSION environment variable)
```

but then when I launch Jupiter notebook, it does not launch and the following outoput returns:

```Bash 
pyenv: jupyter: command not found

The `jupyter' command exists in these Python versions:
  3.9.0

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
```

I don't understand why I can't launch Jupyter notebook
Can someone help me understanding the issue and also tell me if my  .zshrc file is correctly edited?

**Comment by anton-petrov** [comment]
You must install jupyter in your virtual environment^
```
pyenv virtualenv 3.9.0 nexgen
pyenv activate nexgen 3.9.0
pip install jupyter
```
