### ISSUE TITLE
'which python' still points to system python even after activating pyenv's python

### ISSUE THREAD

**Issue by narudarurarasya** [pyenv/pyenv#1886]
Hello everyone. I have problem with my python symlink after activating new venv with pyenv.

```
❯ which python
/usr/bin/python
❯ python -V
Python 3.9.4
❯ which pyenv
/home/user/.pyenv/bin/pyenv
❯ pyenv versions
* system (set by /home/user/.pyenv/version)
  3.8.9
❯ pyenv which python
/usr/bin/python
❯ pyenv global
system
❯ pyenv global 3.8.9
❯ pyenv global
3.8.9
❯ which python
/usr/bin/python
❯ pyenv which python
/home/user/.pyenv/versions/3.8.9/bin/python
❯ gcc --version
gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

As you see, I still get my original system python version when I do which python even after activating `3.8.9`.

I'm on Ubuntu `21.04` and default python version is `3.9.4`.
Prior to installing `pyenv`, I have installed `python-is-python3` package to get around using `python` instead of `python3`

**Comment by native-api** [comment]
This means you didn't install Pyenv according to the official instructions (or didn't restart the shell after that).
With Pyenv installed properly, `which python` should be always pointing to Pyenv's shim rather than `/usr/bin/python`.

**Comment by sagnikrc** [comment]
I faced this issue as well. Simply close the terminal & open a new terminal window. `python --version` should work & point to the right version.
