### ISSUE TITLE
Requesting privileges

### ISSUE THREAD

**Issue by native-api** [pyenv/pyenv#1899]
Subj.
Specifically, I'd like to be able to:

* close invalid/resolved/duplicate issues and PRs
* merge PRs -- primarily those that add new versions, in particular of CPython.

AFAICS, you could use a hand here.

**Comment by yyuu** [comment]
Sorry to be late. And, thanks for all your contributions so far :bow: I will add you as a contributor to this project shortly.

**Comment by native-api** [comment]
Thanks, @yyuu ! Let's get going!
