### ISSUE TITLE
Support for Pyston 2.2

### ISSUE THREAD

**Issue by systemime** [pyenv/pyenv#1901]
Pyston 2.2 Has been fully open sourced, Is there a support plan for pyenv?

see [https://github.com/pyston/pyston/releases/tag/pyston_2.2](https://github.com/pyston/pyston/releases/tag/pyston_2.2)

**Comment by native-api** [comment]
There are no "support plans" AFAIK. Rather, interested parties submit PRs to support new releases that they want support for.

**Comment by anton-petrov** [comment]
Just added support for Pyston 2.2 and removed the old ones (https://github.com/pyenv/pyenv/commit/58b09b7461a7a859474b911dbe617889d3bbcf9a, https://github.com/pyenv/pyenv/commit/328fd42c3a2fbf14ae46dae2021a087fe27ba7e2)

Enjoy! 😇
