### ISSUE TITLE
Auto-close questionable issues if no feedback provided

### ISSUE THREAD

**Issue by native-api** [pyenv/pyenv#1903]
Many feature requests are very questionable. I handle these by adding critique -- but don't close them right away, giving the author (or others) a chance to defend the idea.

There's a stock Github bot, https://github.com/probot/no-response , to auto-close issues if the issue is marked with a certain label and there's no reply within a set time. **IMO It'd be very convenient to use it for these kind of issues.**

**Comment by native-api** [comment]
The same process can be used for user problems that someone has proposed a solution for: if there's no feedback for a long time, we can assume that either the solution worked, or the problem is no lonfer relevant.

**Comment by anton-petrov** [comment]
It's time to put things in order , so I propose:
```
daysUntilClose: 30
responseRequiredLabel: discussion
```

**Comment by anton-petrov** [comment]
I connected bot to repositories, let's try it.

**Comment by native-api** [comment]
"Discussion" looks like a type of issue to me (like bug report or feature request) so it looks confusing (I thought that this was the reason it was put on this issue - to separate it from issues about the software).

I see that [there's a label "awaiting-response"](https://github.com/pyenv/pyenv/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen+label%3A%22awaiting+response%22) but it looks condescending to me.

I'd suggest some less intimidating and more task-specific names that make it clear to the user what specifically we want of them, e.g. : "requested-info", "proposed-solution", "requested-feedback".

**Comment by anton-petrov** [comment]
I agree with you. "need-feedback" should be ok
