### ISSUE TITLE
pyenv install -v 3.10-dev  fails

### ISSUE THREAD

**Issue by fxpoignart** [pyenv/pyenv#1904]
### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): OS X 10.13.6 using python-build 20180424
- [ ] OS architecture (e.g. amd64):
- [x] pyenv version: 1.2.21
- [x] Python version: 3.9
- [x] C Compiler information (e.g. gcc 7.3): Apple LLVM version 10.0.0 (clang-1000.10.44.4)
- [x] Please attach verbose build log as gist

install 3.10-dev fails. It happens that https://github.com/python/cpython has no master branch. It seems that this repository use a branch named main instead.

See logs below:

PYENV_DEBUG=1 pyenv install -v 3.10-dev
+ [pyenv:22] enable -f /usr/local/bin/../libexec/pyenv-realpath.dylib realpath
+ [pyenv:29] '[' -z '' ']'
++ [pyenv:31] type -p greadlink readlink
++ [pyenv:31] head -1
+ [pyenv:31] READLINK=/usr/local/bin/greadlink
+ [pyenv:32] '[' -n /usr/local/bin/greadlink ']'
+ [pyenv:57] '[' -z '' ']'
+ [pyenv:58] PYENV_ROOT=/Users/fx/.pyenv
+ [pyenv:62] export PYENV_ROOT
+ [pyenv:65] '[' -z '' ']'
+ [pyenv:66] '[' -n '' ']'
+ [pyenv:82] '[' -z '' ']'
+ [pyenv:83] PYENV_DIR=/Users/fx/sidework/poetry
+ [pyenv:86] '[' '!' -d /Users/fx/sidework/poetry ']'
+ [pyenv:86] '[' '!' -e /Users/fx/sidework/poetry ']'
++ [pyenv:90] cd /Users/fx/sidework/poetry
++ [pyenv:90] echo /Users/fx/sidework/poetry
+ [pyenv:90] PYENV_DIR=/Users/fx/sidework/poetry
+ [pyenv:91] export PYENV_DIR
+ [pyenv:94] shopt -s nullglob
++ [pyenv:96] abs_dirname /usr/local/bin/pyenv
++ [pyenv:39] local path=/usr/local/bin/pyenv
++ [pyenv:43] '[' -n /usr/local/bin/pyenv ']'
++ [pyenv:44] cd_path=/usr/local/bin
++ [pyenv:45] [[ /usr/local/bin != \/\u\s\r\/\l\o\c\a\l\/\b\i\n\/\p\y\e\n\v ]]
++ [pyenv:46] cd /usr/local/bin
++ [pyenv:48] name=pyenv
+++ [pyenv:49] resolve_link pyenv
+++ [pyenv:35] /usr/local/bin/greadlink pyenv
++ [pyenv:49] path=../Cellar/pyenv/1.2.21/bin/pyenv
++ [pyenv:43] '[' -n ../Cellar/pyenv/1.2.21/bin/pyenv ']'
++ [pyenv:44] cd_path=../Cellar/pyenv/1.2.21/bin
++ [pyenv:45] [[ ../Cellar/pyenv/1.2.21/bin != \.\.\/\C\e\l\l\a\r\/\p\y\e\n\v\/\1\.\2\.\2\1\/\b\i\n\/\p\y\e\n\v ]]
++ [pyenv:46] cd ../Cellar/pyenv/1.2.21/bin
++ [pyenv:48] name=pyenv
+++ [pyenv:49] resolve_link pyenv
+++ [pyenv:35] /usr/local/bin/greadlink pyenv
++ [pyenv:49] path=../libexec/pyenv
++ [pyenv:43] '[' -n ../libexec/pyenv ']'
++ [pyenv:44] cd_path=../libexec
++ [pyenv:45] [[ ../libexec != \.\.\/\l\i\b\e\x\e\c\/\p\y\e\n\v ]]
++ [pyenv:46] cd ../libexec
++ [pyenv:48] name=pyenv
+++ [pyenv:49] resolve_link pyenv
+++ [pyenv:35] /usr/local/bin/greadlink pyenv
+++ [pyenv:49] true
++ [pyenv:49] path=
++ [pyenv:43] '[' -n '' ']'
++ [pyenv:52] echo /usr/local/Cellar/pyenv/1.2.21/libexec
+ [pyenv:96] bin_path=/usr/local/Cellar/pyenv/1.2.21/libexec
+ [pyenv:97] for plugin_bin in '"${bin_path%/*}"/plugins/*/bin'
+ [pyenv:98] PATH=/usr/local/Cellar/pyenv/1.2.21/plugins/python-build/bin:/Users/fx/.poetry/bin:/Users/fx/.pyenv/shims:/usr/local/opt/libpq/bin:/Users/fx/.yarn/bin:/Users/fx/.config/yarn/global/node_modules/.bin:/usr/local/opt/node@12/bin:/usr/local/opt/python/libexec/bin:/Users/fx/Library/Python/3.7/bin:/Users/fx/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
+ [pyenv:103] export PATH=/usr/local/Cellar/pyenv/1.2.21/libexec:/usr/local/Cellar/pyenv/1.2.21/plugins/python-build/bin:/Users/fx/.poetry/bin:/Users/fx/.pyenv/shims:/usr/local/opt/libpq/bin:/Users/fx/.yarn/bin:/Users/fx/.config/yarn/global/node_modules/.bin:/usr/local/opt/node@12/bin:/usr/local/opt/python/libexec/bin:/Users/fx/Library/Python/3.7/bin:/Users/fx/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
+ [pyenv:103] PATH=/usr/local/Cellar/pyenv/1.2.21/libexec:/usr/local/Cellar/pyenv/1.2.21/plugins/python-build/bin:/Users/fx/.poetry/bin:/Users/fx/.pyenv/shims:/usr/local/opt/libpq/bin:/Users/fx/.yarn/bin:/Users/fx/.config/yarn/global/node_modules/.bin:/usr/local/opt/node@12/bin:/usr/local/opt/python/libexec/bin:/Users/fx/Library/Python/3.7/bin:/Users/fx/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
+ [pyenv:105] PYENV_HOOK_PATH=:/Users/fx/.pyenv/pyenv.d
+ [pyenv:106] '[' /usr/local/Cellar/pyenv/1.2.21 '!=' /Users/fx/.pyenv ']'
+ [pyenv:108] PYENV_HOOK_PATH=:/Users/fx/.pyenv/pyenv.d:/usr/local/Cellar/pyenv/1.2.21/pyenv.d
+ [pyenv:110] PYENV_HOOK_PATH=:/Users/fx/.pyenv/pyenv.d:/usr/local/Cellar/pyenv/1.2.21/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks
+ [pyenv:114] PYENV_HOOK_PATH=/Users/fx/.pyenv/pyenv.d:/usr/local/Cellar/pyenv/1.2.21/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks
+ [pyenv:115] export PYENV_HOOK_PATH
+ [pyenv:117] shopt -u nullglob
+ [pyenv:120] command=install
+ [pyenv:121] case "$command" in
++ [pyenv:134] command -v pyenv-install
+ [pyenv:134] command_path=/usr/local/Cellar/pyenv/1.2.21/plugins/python-build/bin/pyenv-install
+ [pyenv:135] '[' -z /usr/local/Cellar/pyenv/1.2.21/plugins/python-build/bin/pyenv-install ']'
+ [pyenv:143] shift 1
+ [pyenv:144] '[' -v = --help ']'
+ [pyenv:151] exec /usr/local/Cellar/pyenv/1.2.21/plugins/python-build/bin/pyenv-install -v 3.10-dev
+ [pyenv-install:32] shopt -s nullglob
+ [pyenv-install:36] export PYTHON_BUILD_DEFINITIONS
+ [pyenv-install:37] shopt -u nullglob
+ [pyenv-install:40] '[' -v = --complete ']'
++ [pyenv-install:53] python-build --lib
+ [pyenv-install:53] eval 'lib () 
{ 
    function parse_options () 
    { 
        OPTIONS=();
        ARGUMENTS=();
        local arg option index;
        for arg in "$@";
        do
            if [ "${arg:0:1}" = "-" ]; then
                if [ "${arg:1:1}" = "-" ]; then
                    OPTIONS[${#OPTIONS[*]}]="${arg:2}";
                else
                    index=1;
                    while option="${arg:$index:1}"; do
                        [ -n "$option" ] || break;
                        OPTIONS[${#OPTIONS[*]}]="$option";
                        index=$(($index+1));
                    done;
                fi;
            else
                ARGUMENTS[${#ARGUMENTS[*]}]="$arg";
            fi;
        done
    };
    if [ "$1" == "--$FUNCNAME" ]; then
        declare -f "$FUNCNAME";
        echo "$FUNCNAME \"\$1\";";
        exit;
    fi
}
lib "$1";'
++ [pyenv-install:84] lib -v
++ [pyenv-install:78] '[' -v == --lib ']'
+ [pyenv-install:69] unset FORCE
+ [pyenv-install:70] unset SKIP_EXISTING
+ [pyenv-install:71] unset KEEP
+ [pyenv-install:72] unset VERBOSE
+ [pyenv-install:73] unset HAS_PATCH
+ [pyenv-install:74] unset DEBUG
+ [pyenv-install:76] parse_options -v 3.10-dev
+ [pyenv-install:57] OPTIONS=()
+ [pyenv-install:58] ARGUMENTS=()
+ [pyenv-install:59] local arg option index
+ [pyenv-install:60] for arg in '"$@"'
+ [pyenv-install:62] '[' - = - ']'
+ [pyenv-install:63] '[' v = - ']'
+ [pyenv-install:66] index=1
+ [pyenv-install:67] option=v
+ [pyenv-install:68] '[' -n v ']'
+ [pyenv-install:69] OPTIONS[${#OPTIONS[*]}]=v
+ [pyenv-install:70] index=2
+ [pyenv-install:67] option=
+ [pyenv-install:68] '[' -n '' ']'
+ [pyenv-install:68] break
+ [pyenv-install:60] for arg in '"$@"'
+ [pyenv-install:62] '[' 3 = - ']'
+ [pyenv-install:74] ARGUMENTS[${#ARGUMENTS[*]}]=3.10-dev
+ [pyenv-install:77] for option in '"${OPTIONS[@]}"'
+ [pyenv-install:78] case "$option" in
+ [pyenv-install:97] VERBOSE=-v
+ [pyenv-install:114] '[' 1 -le 1 ']'
+ [pyenv-install:116] unset VERSION_NAME
+ [pyenv-install:122] DEFINITION=3.10-dev
+ [pyenv-install:123] '[' -n 3.10-dev ']'
+ [pyenv-install:124] '[' -n 3.10-dev ']'
+ [pyenv-install:129] declare -a before_hooks after_hooks
+ [pyenv-install:141] OLDIFS=' 	
'
+ [pyenv-install:142] IFS='
'
+ [pyenv-install:142] scripts=(`pyenv-hooks install`)
++ [pyenv-install:142] pyenv-hooks install
+ [pyenv-hooks:9] '[' install = --complete ']'
+ [pyenv-hooks:18] PYENV_COMMAND=install
+ [pyenv-hooks:19] '[' -z install ']'
+ [pyenv-hooks:24] enable -f /usr/local/Cellar/pyenv/1.2.21/libexec/pyenv-realpath.dylib realpath
+ [pyenv-hooks:55] IFS=:
+ [pyenv-hooks:55] hook_paths=($PYENV_HOOK_PATH)
+ [pyenv-hooks:57] shopt -s nullglob
+ [pyenv-hooks:58] for path in '"${hook_paths[@]}"'
+ [pyenv-hooks:58] for path in '"${hook_paths[@]}"'
+ [pyenv-hooks:58] for path in '"${hook_paths[@]}"'
+ [pyenv-hooks:58] for path in '"${hook_paths[@]}"'
+ [pyenv-hooks:58] for path in '"${hook_paths[@]}"'
+ [pyenv-hooks:63] shopt -u nullglob
+ [pyenv-install:143] IFS=' 	
'
+ [pyenv-install:149] '[' -n '' ']'
+ [pyenv-install:149] VERSION_NAME=3.10-dev
+ [pyenv-install:150] '[' -n '' ']'
+ [pyenv-install:151] PREFIX=/Users/fx/.pyenv/versions/3.10-dev
+ [pyenv-install:153] '[' -d /Users/fx/.pyenv/versions/3.10-dev ']'
+ [pyenv-install:157] '[' -d /Users/fx/.pyenv/versions/3.10-dev/bin ']'
+ [pyenv-install:175] '[' -n '' ']'
+ [pyenv-install:182] '[' -z '' ']'
+ [pyenv-install:182] '[' -d /Users/fx/.pyenv/cache ']'
+ [pyenv-install:186] '[' -z '' ']'
+ [pyenv-install:187] case "${VERSION_NAME}" in
+ [pyenv-install:193] for version_info in '"${VERSION_NAME%-dev}"' '"${VERSION_NAME%.*}"' '"${VERSION_NAME%%.*}"'
++ [pyenv-install:193] pyenv-whence python3.10
++ [pyenv-install:193] true
+ [pyenv-install:193] for version_info in '"${VERSION_NAME%-dev}"' '"${VERSION_NAME%.*}"' '"${VERSION_NAME%%.*}"'
++ [pyenv-install:193] pyenv-whence python3
+ [pyenv-install:195] for version in '$(pyenv-whence "python${version_info}" 2>/dev/null || true)'
+ [pyenv-install:196] [[ 3.8.6 != \a\n\a\c\o\n\d\a* ]]
+ [pyenv-install:196] [[ 3.8.6 != \m\i\n\i\c\o\n\d\a* ]]
+ [pyenv-install:197] PYENV_BOOTSTRAP_VERSION=3.8.6
+ [pyenv-install:198] break 2
+ [pyenv-install:230] '[' -n 3.8.6 ']'
+ [pyenv-install:231] export PYENV_VERSION=3.8.6
+ [pyenv-install:231] PYENV_VERSION=3.8.6
+ [pyenv-install:242] trap cleanup SIGINT
+ [pyenv-install:245] STATUS=0
+ [pyenv-install:246] python-build -v 3.10-dev /Users/fx/.pyenv/versions/3.10-dev
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
/var/folders/nm/j0hzc5ds5tg07yvycygv4lr00000gp/T/python-build.20210507104425.22979 ~/sidework/poetry
Cloning https://github.com/python/cpython...
Cloning into 'Python-3.10-dev'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin

BUILD FAILED (OS X 10.13.6 using python-build 20180424)

**Comment by native-api** [comment]
WFM in Linux and MacOS 11 x64 with the latest head.

**Comment by anton-petrov** [comment]
@fxpoignart install latest pyenv version.
