### ISSUE TITLE
WARNING: `pyenv init -` no longer sets PATH.

### ISSUE THREAD

**Issue by strongbrent** [pyenv/pyenv#1906]
After running `pyenv update` today, now every time I launch a terminal, I get the following error message:  
```
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
```

This occurs in both Ubuntu 20.04 and Fedora 34. Try as I might, there doesn't seem to be anything I can do with my `.zshrc` file to make the behavior go away. Did something change recently? 

If you need any additional information, I will happily supply it.

**Comment by andreww35t** [comment]
I saw the similar message on an RH derivative Linux using bash 4.4.19. I had the same issue at first, but i just changed the `eval "$(pyenv init -)"` in my ~/.bashrc  to `eval "$(pyenv init --path)"` and it stopped puking this error.  I don't use ~/.profile for bash.  the ~/.bashrc update was sufficient for me:

`
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi
`
The instructions to "Run pyenv init ..."  could optionally be clarified IMHO.

**Comment by strongbrent** [comment]
Thanks very much for the solution! It worked like a charm.

**Comment by native-api** [comment]
> I just changed the `eval "$(pyenv init -)"` in my ~/.bashrc to `eval "$(pyenv init --path)"`

This will stop `pyenv` from being a shell function which will break some commands, e.g. `pyenv shell`.

Please heed the instructions unless you know what you're doing.

This change is a solution to https://github.com/pyenv/pyenv/issues/1649.

**Comment by native-api** [comment]
> I just changed the `eval "$(pyenv init -)"` in my ~/.bashrc to `eval "$(pyenv init --path)"`

This will stop `pyenv` from being a shell function which will break some commands, e.g. `pyenv shell`.

---

This change is a solution to https://github.com/pyenv/pyenv/issues/1649 -- `PATH` manipulations need to be done in `~/.profile`.

So (as of this writing) these need to be in `~/.profile`:

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```

and this in `~/.bashrc`:

```
eval "$(pyenv init -)"
```

As the `pyenv init` output also says, you need to fully log out of your session and back in for changes to `~/.profile` to take effect.a

**Comment by Justin1904** [comment]
It seems that if I put
```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
```
in `.profile` instead of `.bashrc`, I'll get
```
-bash: pyenv: command not found
```
and pyenv won't work at all.

**Comment by starliiit** [comment]
> ```
> export PYENV_ROOT="$HOME/.pyenv"
> export PATH="$PYENV_ROOT/bin:$PATH"
> if command -v pyenv 1>/dev/null 2>&1; then
>   eval "$(pyenv init --path)"
> fi
> ```

If you're using zsh, put these lines in `.zprofile`. It works for me.

reference: https://superuser.com/questions/187639/zsh-not-hitting-profile

**Comment by j3pic** [comment]
Why would not setting the path ever be a desirable thing to do?

**Comment by IvanVinitskyi** [comment]
After changing .profile (only) I got

**Comment by cornfeedhobo** [comment]
Has anyone noticed the drift though? `init --path` doesn't include the completion that used to be available with `init -`

**Comment by kevnm67** [comment]
FYI anyone using homebrew:

`MacOS note: If you installed Pyenv with Homebrew, you don't need to add the PYENV_ROOT= and PATH= lines. You also don't need to add commands into ~/.profile if your shell doesn't use it.`

**Comment by HaidarZ** [comment]
> FYI anyone using homebrew:
> 
> `MacOS note: If you installed Pyenv with Homebrew, you don't need to add the PYENV_ROOT= and PATH= lines. You also don't need to add commands into ~/.profile if your shell doesn't use it.`

How can we handle the warning ?

**Comment by kevnm67** [comment]
@HaidarZ adding `eval "$(pyenv init --path)" ` to my .zprofile worked.  

Note: Not sure how your dotfiles are configured but, and I need to verify whether this is still necessary, I also check for pyenv in my .zshrc and, when true, `eval "$(pyenv init -)`.

**Comment by rohansatapathy** [comment]
@kevnm67 I also use oh-my-zsh and noticed this error today. Does someone need to update the [plugin script at oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/pyenv/pyenv.plugin.zsh) so that this doesn't happen again or does this change need to be made on a user-by-user basis?

**Comment by native-api** [comment]
> 
> 
> @kevnm67 I also use oh-my-zsh and noticed this error today. Does someone need to update the [plugin script at oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/pyenv/pyenv.plugin.zsh) so that this doesn't happen again or does this change need to be made on a user-by-user basis?

Yes, that script needs to be updated to reflect the changes. Moreover, now the commands need to be run at 2 different moments, so that product may need additional features as well.

**Comment by SeanRavenhill** [comment]
Apologies if this has already been answered, but I've been going over all the comments and various branches here and I can't seem to get a handle on exactly which files need to be changed. Rather confused, to be honest.

Hopefully, someone can clarify for me. Please.

For those of us on Mac/Linux systems and running a .zsh shell... particularly Oh-My-Zsh configuration and a brew installation of pyenv.

My understanding is... That we need to add the below lines to our .zshrc file. As I don't have a .zprofile nor a .profile file

`if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
fi`

*Just to note this has resolved the warning message being thrown when I restart my shell. And pyenv appears to run fine. Just can't be sure if I've resolved the issue correctly and just blindly done some sort of workaround.

Thanks for the assistance.

**Comment by rohansatapathy** [comment]
@SeanRavenhill I have a similar setup to yours, and here's what I did to fix it. All you have to do is to create a .zprofile file in your home directory, then add the line `eval "$(pyenv init --path))"` to it. Save the file and restart your terminal session. Note that you should keep the pyenv plugin enabled in oh-my-zsh so that the line `eval "$(pyenv init -)"` still runs, as both commands must be run for pyenv to be configured properly.

**Comment by SeanRavenhill** [comment]
@rohansatapathy thanks for the quick response and assistance. Greatly appreciated. 

I also thought that may be how it was being explained in the pyenv README.md

My confusion starts at that .zprofile dot file. As I can seem to find much else reference to it or why it is now required. A bit of googling though does show that a .zprofile dot file has to be manually created.

Not very clear in the pyenv README.md though. 

Or am I perhaps being a bit "dense"?

**Comment by rohansatapathy** [comment]
I'm still new to pyenv, so I'm also not sure why the new init commands need to be placed in two different files. However, I did find [this post](https://apple.stackexchange.com/questions/388622/zsh-zprofile-zshrc-zlogin-what-goes-where) helpful for explaining the purpose of the different zsh startup files. Hope this is helpful.

**Comment by kevnm67** [comment]
> I'm still new to pyenv, so I'm also not sure why the new init commands need to be placed in two different files. However, I did find [this post](https://apple.stackexchange.com/questions/388622/zsh-zprofile-zshrc-zlogin-what-goes-where) helpful for explaining the purpose of the different zsh startup files. Hope this is helpful.

`.zprofile` is to ensure `pyenv init --path` is run only once per session by its login shell.  `.zshrc` is loads pyenv's autocompletions.  You can use the `pyenv` plugin or `eval "$(pyenv init -)"`.  
Note: I updated my original comment above to append `pyenv` to my plugins for autocompletions.

**Comment by G33KatWork** [comment]
Are you guys sure that the `.zprofile` approach works on Linux when logging in using display managers like GDM? In this case it seems that `.zprofile` is ignored and more or less rightfully so, because there is no login shell that could load it.
I added the proposed evals to a `.zprofile` in my home directory, but I still get the warning message that my configuration is wrong.

**Comment by native-api** [comment]
> Are you guys sure that the `.zprofile` approach works on Linux when logging in using display managers like GDM?

In Linux, you need to add login-time command into both `.zprofile` and `.profile` for this reason. https://github.com/pyenv/pyenv/issues/1906#issuecomment-835027647

**Comment by fbarez** [comment]
For MacOs users: 
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration. <> once you have run pyenv init you should get the following:

# (The below instructions are intended for common
# shell setups. See the README for more guidance
# if they don't apply and/or don't work for you.)

# Add pyenv executable to PATH and
# enable shims by adding the following
# to ~/.profile and ~/.zprofile:

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# Load pyenv into the shell by adding
# the following to ~/.zshrc:

eval "$(pyenv init -)"

# Make sure to restart your entire logon session
# for changes to profile files to take effect.

Since zsh or my zsh  do not come with .profile nor .zprofile you would have to create one and that should work.

**Comment by hamzahi-ps** [comment]
I tried to make the changes above but was exporting the oh-my-zsh pyenv [plugin](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/pyenv/pyenv.plugin.zsh) after that. This caused the init to not work. 

Adding to `.zprofile` also did not work for me. After adding the following to my `.zshrc`:
```
export PYENV_ROOT=$HOME/.pyenv
export PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
```

and removing the pyenv zsh plugin, it started working for me. Not sure if there is an easier way

**Comment by mcaay** [comment]
Final update for people with Mac OS, who installed pyenv with homebrew and using oh-my-zsh.

.zprofile
```
export PATH=/opt/homebrew/bin:$PATH
eval "$(pyenv init --path)"
```

.zshrc
```
...
plugins=(git pyenv)
...
```

How can you confirm if this is good? Basically in `.zprofile` you need to do the same path export for homebrew stuff as in `.zshrc`.
So if you have homebrew working you can type in the shell `which pyenv` to confirm that it is a binary within homebrew folder. If you have a different path than me to homebrew - use that. 

Otherwise you will get the following error:
```
/Users/mcaay/.zprofile:1: command not found: pyenv
```

**Comment by mromero-convoso** [comment]
Made a change to `/etc/profile.d/pyenv.sh` which corrected this behavior for me: ```root@default-ubuntu-2004:~# cat /etc/profile.d/pyenv.sh
# Prefer a user pyenv over a system-wide install
if [ -s "${HOME}/.pyenv/bin" ]; then
    pyenv_root="${HOME}/.pyenv"
    pyenv_init="pyenv init -"
elif [ -s "/usr/local/pyenv" ]; then
    pyenv_root="/usr/local/pyenv"
    export PYENV_ROOT=${pyenv_root}
    # Rehashing will fail in a system install
    pyenv_init="pyenv init - --no-rehash"
fi

pyenv_init_path="${pyenv_root}/bin/pyenv init --path"

if [ -n "$pyenv_root" ]; then
    export PATH="${pyenv_root}/bin:$PATH"
    eval "$($pyenv_init_path)"
    eval "$($pyenv_init)"
fi
root@default-ubuntu-2004:~#```

**Comment by execptionerror** [comment]
[Already solved WARNING: `pyenv init -` no longer sets PATH. Run `pyenv init` to see the necessary changes to make to your configuration.](https://exerror.com/warning-pyenv-init-no-longer-sets-path-run-pyenv-init-to-see-the-necessary-changes-to-make-to-your-configuration/)

**Comment by cameronw-cn** [comment]
g
