### ISSUE TITLE
Changes after tag 1.2.27 break pyenv-virtualenv

### ISSUE THREAD

**Issue by notmyrealhandle** [pyenv/pyenv#1909]
I had a working pyenv/pyenv-virtualenv on ubuntu 20.04 lts, bash, python 3.9.4 and have been using pyenv and pyenv-virtualenv for some time now.

Today, after
```
...
git -C /home/ul/.pyenv pull
pyenv rehash
...
```
I got the warning
```
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
```
and my pyenv/virtualenv was non-functional (i.e. system python is used instead the virtualenv python)

I already had 
```
...
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
...
``` 
in .bashrc and after adding the line
```
eval "$(pyenv init --path)"
```
to my .profile (and logging out and back in) my environment was still non functional.

```
git reset --hard 1.2.27
```
Returns my pyenv virtualenv to a fully functional state.

Perhpas [#383](https://github.com/pyenv/pyenv-virtualenv/issues/383#issue-879494087) is related but I don't use .bash_profile.

Looking at [commit 7838707](https://github.com/pyenv/pyenv/commit/783870759566a77d09b426e0305bc0993a522765) perhaps I should add the PYENV_ROOT & PATH export lines currently in my .bashrc to my .profile but there is nothing in the warning statement about that... My pyenv config was set up   several years ago and has not changed (has it become obsolete or just wrong from the start?).

Is this just a temporary bug and if i wait a bit it will be fixed shortly?

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/issues/1906#issuecomment-835027647: 

> So (as of this writing) these need to be in ~/.profile:
> 
> ```
> export PYENV_ROOT="$HOME/.pyenv"
> export PATH="$PYENV_ROOT/bin:$PATH"
> eval "$(pyenv init --path)"
> ```
> 
> and this in ~/.bashrc:
> 
> ```
> eval "$(pyenv init -)"
> ```
> 

@notmyrealhandle , I guess it was unclear from the hint that you need to move `export PYENV_ROOT=<...>` and `export PATH=` to `~/.profile` as well?

**Comment by nihilismus** [comment]
I don't make use of `~/.bashrc` or `~/.profile` to configure my environment but a custom Bash function which loads a custom script <https://git.sr.ht/~nihilismus/dotfiles/tree/main/home/nihilipster/.config/bash/environments/python.bash>:

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)" 2>&1 >/dev/null
eval "$(pyenv init --path)"
```

Maybe `eval "$(pyenv init --path)"` is pyenv's old behavior 🤔

**Comment by notmyrealhandle** [comment]
@native-api 

>  I guess it was unclear from the hint that you need to move export PYENV_ROOT=<...> and export PATH= to ~/.profile as well?

Not so much unclear as "unsaid."  I set this up several years ago and its worked fine since.  In short, I forgot (and I can't remember/find the link to the instructions for adding the additional exports).  

For a better UX, perhaps remind users that more may be required to get the additional .profile entry to work as intended?

FWIW adding the exports to my .profile does resolve the issue and I can close this issue unless you would like to keep it open for a bit.

ty for responding

**Comment by jpmckinney** [comment]
Not sure if the same issue, but hopefully helpful to anyone else searching this repo:

I'm on macOS Big Sur 11.2.3 and upgraded to pyenv 1.2.27 using Homebrew (brew). I started getting the same warning.

The instruction to add `pyenv init --path | source` to `~/.profile` did not work. Instead, add it to `~/.config/fish/config.fish` before `pyenv init - | source`.

Similarly, in Bash, add `eval "$(pyenv init --path)"` before `eval "$(pyenv init -)"` in `~/.bashrc`.
