### ISSUE TITLE
The instructions for adding pyenv to the load path result in command not found errors

### ISSUE THREAD

**Issue by jack1142** [pyenv/pyenv#1911]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Debian Buster, same should apply to most if not all popular distros
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: current master (https://github.com/pyenv/pyenv/commit/f0a8e72c3672e4f694fb7da7cdc1849f175a1c07)
- [x] Python version: N/A
- [x] C Compiler information (e.g. gcc 7.3): N/A

This is what is currently shown after running `pyenv-installer` (most of this message is coming from output of `pyenv init` so this repo should be appropriate):
```
WARNING: seems you still have not added 'pyenv' to the load path.

# Add pyenv executable to PATH by adding
# the following to ~/.profile:

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# Load pyenv automatically by appending
# the following to ~/.bashrc:

eval "$(pyenv init -)"

# and the following to ~/.profile:

eval "$(pyenv init --path)"

# Make sure to restart your entire logon session
# for changes to ~/.profile to take effect.

# Load pyenv-virtualenv automatically by adding
# the following to ~/.bashrc:

eval "$(pyenv virtualenv-init -)"
```

So by following this, I end up with these contents appended to the end of the listed files:
- `~/.profile`
```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```
- `~/.bashrc`
```
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

This will result in the new bash shells giving this output on startup of interactive login shell (meaning that the commands from `.bashrc` failed to run):
```
-bash: pyenv: command not found
-bash: pyenv: command not found
```

This is because in the default contents of `~/.profile` (in case of Debian-based distros), `~/.bash_profile` (in case of RHEL-based distros), or `/etc/profile` (in case of openSUSE) file, `~/.bashrc` is sourced at the beginning of it and so when user appends these commands at the end, it doesn't work because `.bashrc` pretty much always runs *before* `.profile`.

### Additional context
https://github.com/pyenv/pyenv-virtualenv/issues/383 and #1909 address somewhat similar issues but neither of the bug fixes are fixing what I'm reporting in this issue.

**Comment by native-api** [comment]
Okay, I see.

This can only be seen in _text_ sessions -- so I couldn't see it in a GUI session.
(Of course, the errors messages still happen, but they are hidden from the user and do not affect interactive shells run in windows -- even if they are login shells.

So, **all we need to do is move the code in ~/.profile to before the chunk that sources `~/.bashrc`.**

* I've checked that we cannot just move all the code to `~/.bashrc` and detect a login shell -- OSX `~/.profile` does not source it.

**Comment by native-api** [comment]
Okay, I see.

This can only be seen in _text_ sessions -- so I couldn't see it in a GUI session.
(Of course, the errors messages still happen, but they are hidden from the user and do not affect interactive shells run in windows -- even if they are login shells.

So, **all we need to do is move the code in ~/.profile to before the chunk that sources `~/.bashrc`.**
@jack1142 , could you check if that fixes the problem?

* I've checked that we cannot just move all the code to `~/.bashrc` and detect a login shell -- OSX `~/.profile` does not source it.
