### ISSUE TITLE
path manipulations need to be placed in ~/.zprofile for zsh user

### ISSUE THREAD

**Issue by hrzhu** [pyenv/pyenv#1913]
I'm using zsh on Ubuntu 20.04. I need to place the following path manipulations in ~/.zprofile instead of ~/.profile to make pyenv work and suppress the recently added warning.

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```

**Comment by europ** [comment]
After pyenv update, I had the same problem. @hrzhu who shared the solutions that can suppress the warning(s). Thanks!

#### Problem
```
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
```

#### Solution
You just need to create a `~/.zprofile` with the following content (see below).

#### ~/.zshrc
```bash
# kept content in ~/.zshrc
export PYENV_ROOT="$HOME"/.pyenv
export PATH="$PYENV_ROOT"/bin:"$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

#### ~/.zprofile
```bash
# added content to ~/.zprofile
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```

#### Question
How can I configure pyenv using only `~/.zshrc` (without `~/.zprofile`)?

**Comment by native-api** [comment]
See https://github.com/pyenv/pyenv/issues/1914#issuecomment-836607473 for what needs to be done at startup.
I don't have any experience with `zsh` outside of OSX so can't say how it's best to implement this for Zsh.

Doesn't it read `~/.profile` like Sh and Bash do? Maybe it should since it's Sh-compatible?
Is it your login shell or not? If it is, what happens if you enter a GUI session -- do any of Zsh-specific files have an effect on it?

**Comment by native-api** [comment]
Okay. Then, I see that if I run `zsh` in a GUI session in a terminal window in OSX, it thinks that it's a login shell -- even though it's technically not.

Does it behave the same way in Linux? (If it doesn't, we'll need to put commands into _both_ `~/.profile` and `~/.zprofile`.)

**Comment by native-api** [comment]
> I don't quite clear about your question. What do you mean by "it thinks that it's a login shell"?

I means that `[[ -o login ]]` succeeds.

What I want to know is:
If you start a GUI session and then run Zsh in a terminal window in it -- does it run commands from `~/.zprofile`?
With default settings in Ubuntu, shells run this way are interactive but not login -- so they don't run their `~/.<shell>profile` files in this case.
Is this the same with Zsh or not?

**Comment by hrzhu** [comment]
Sorry my previous comment is wrong. I had a working pyenv because I left the path manipulations  in ~/.zshrc as well.
If I put the following path manipulations in ~/.profile, and `eval "$(pyenv init -)"` in zshrc, I got `/home/h/.zshrc:99: command not found: pyenv` when I start a gui terminal.
```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```
If I put everything in zshrc, pyenv works but I get the warning.
I need to place the path manipulations in ~/.zprofile to get a working pyenv and suppress the warning.

**Comment by europ** [comment]
@native-api this can help you - https://superuser.com/questions/187639/zsh-not-hitting-profile.

**Comment by native-api** [comment]
I've made a PR with updated instructions for Bash and Zsh based on feedback: https://github.com/pyenv/pyenv/pull/1920.

Please review it and tell me:
* If the instructions (both README and `pyenv init`) are clear
* If they work
* If there's a better way

**Comment by native-api** [comment]
AFAICS, we do need to put PATH manipulations into `~/.profile` and `~/.zprofile`.

However, https://superuser.com/questions/187639/zsh-not-hitting-profile mentions that we can avoid duplication:
`emulate sh; source ~/.profile; emulate zsh`.
Should we recommend this way?

**Comment by europ** [comment]
> Please review

Later (in a few days), I will answer you in this issue after I have tried it.

> Should we recommend this way as the standard setup?

It´s hard to answer.
1. First of all, everybody has to know the consequence of incompatibility to avoid future problems related to pynev when switching shells, especially for ZSH users. You should add an important note for that somewhere.
1. Next, if you can fix this problem from root using the "emulate" method you mentioned, then you may recommend / implement such a solution like this. But, it needs to be tested thoroughly.
1. Yet, I do not know what´s the "ideal" solution for this. In my opinion, this should be discussed with the maintainers of pyenv who will approve or disapprove this solution proposal. But, when it works (it was tested), I do not have a problem with that.

**Comment by YUMEYA** [comment]
I'm using zsh and oh-my-zsh on Ubuntu. After upgrading pyenv and follow the hints by `pyenv init`, it seems like broken. I cannot switch python version or venv by executing `pyenv shell <version or venv>`, and automatic venv switching is not working, either.
After editing `~/.zprofile` and `~/.zshrc` like @europ said, problem solved, thank you very much!

**Comment by europ** [comment]
@native-api


> If the instructions (both README and pyenv init) are clear

Instructions are clear.

> If they work

It works for me (HEAD = https://github.com/native-api/pyenv/commit/e504424d88bc0232d07c489b4805a439f46cb00e).

> If there's a better way

Yet, I don't know.

**Comment by native-api** [comment]
>     2\. if you can fix this problem from root using the "emulate" method you mentioned, then you may recommend / implement such a solution like this. But, it needs to be tested thoroughly.

I didn't include the `emulate` method since you say its workability is so uncertain.

If someone wants to add it, they can make a separate PR, at which point we'll give it due consideration.

**Comment by evdcush** [comment]
May I ask why updates were made to pyenv such that it now requires having lines in both shell config and `.profile`?

 

Was it not simpler before with just having the three lines in the shell config? 👀 

 

I was not able to get things functional with the `pyenv init` message. I had to find this issue 😕
