### ISSUE TITLE
pyenv-init introduced soft dependency on `perl`

### ISSUE THREAD

**Issue by bouktin** [pyenv/pyenv#1921]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): alpine linux
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: latest
- [x] Python version: 3.7.10 (but this is independent of python version)
- [ ] C Compiler information (e.g. gcc 7.3): 
- [x] Please attach verbose build log as gist: not needed
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

Pyenv commit 3e3f40fefcdf2060b421a688168f3dd2f03811ef introduced a soft dependency on `perl` in [pyenv-init](https://github.com/pyenv/pyenv/blob/3e3f40fefcdf2060b421a688168f3dd2f03811ef/libexec/pyenv-init#L137): https://github.com/pyenv/pyenv/commit/3e3f40fefcdf2060b421a688168f3dd2f03811ef#diff-f60dcfddce314f1037b9b26a4b52b1684af36566775312c77239752cd24f0b54R137

In docker containers, perl is not available by default. `awk` is a better alternative as more ubiquitous.

Example of issue:
```
FROM docker.io/library/alpine:latest@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
[...]
bash-5.1# bash
/usr/local/pyenv/libexec/pyenv-init: line 159: perl: command not found
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
```

Solution with awk:
Replace line [137](https://github.com/pyenv/pyenv/blob/3e3f40fefcdf2060b421a688168f3dd2f03811ef/libexec/pyenv-init#L137) with:
```
if ! echo $PATH | awk -F':' -v path="${PYENV_ROOT}/shims" '{for(i=1; i<=NF; i++) { if ($i == path) {exit 1 ;} } }' ; then
```

Example in action:
```
> echo $PATH | awk -F':' -v path="${PYENV_ROOT}/shims" '{for(i=1; i<=NF; i++) { if ($i == path) {print "found it in "i" : "$i ; exit 1 ;} else { print "not found in : "i" : "$i ; } } }' ; echo $?
not found in : 1 : /usr/local/Cellar/pyenv-virtualenv/1.1.5/shims
found it in 2 : /Users/(obfuscated)/.pyenv/shims
1

> echo $PATH | awk -F':' -v path="doe-not-exist" '{for(i=1; i<=NF; i++) { if ($i == path) {print "found it in "i" : "$i ; exit 1 ;} else { print "not found in : "i" : "$i ; } } }' ; echo $?
not found in : 1 : /usr/local/Cellar/pyenv-virtualenv/1.1.5/shims
not found in : 2 : /Users/(obfuscated)/.pyenv/shims
not found in : 3 : /usr/local/bin
not found in : 4 : /usr/bin
not found in : 5 : /bin
not found in : 6 : /usr/sbin
not found in : 7 : /sbin
0


> echo $PATH | awk -F':' -v path="doe-not-exist" '{for(i=1; i<=NF; i++) { if ($i == path) {exit 1 ;} } }' ; echo $?
0
> echo $PATH | awk -F':' -v path="${PYENV_ROOT}/shims" '{for(i=1; i<=NF; i++) { if ($i == path) {exit 1 ;} } }' ; echo $?
1

```

**Comment by bouktin** [comment]
Relates to https://github.com/pyenv/pyenv/issues/1649

**Comment by native-api** [comment]
> In docker containers, perl is not available by default.

Which "docker containers"?
I've checked several ones, and it's present in `ubuntu`, `debian`, `linuxmintd/mint20-amd64`, `roboxes/rhel7`, `roboxes/rhel8`, `gentoo`, `alt`, and missing only in `centos` (which also lacks `which` on which we also depend) and `alpine` (which lacks `bash`).

**Comment by native-api** [comment]
In any case, `perl` is used to check if an entry is in `PATH` -- because all the ways to do it in Bash that I found required convoluted several-lines scripts.

If you can figure out a sufficiantly elegant way to do this reliably without `perl`, a PR is welcome.

**Comment by bouktin** [comment]
Thank you @native-api for the feedback. 

Assuming awk is available (and that's to be ferivied), I figured out that solution:

Replace line [137](https://github.com/pyenv/pyenv/blob/3e3f40fefcdf2060b421a688168f3dd2f03811ef/libexec/pyenv-init#L137) with:
```
if ! echo $PATH | awk -F':' -v path="${PYENV_ROOT}/shims" '{for(i=1; i<=NF; i++) { if ($i == path) {exit 1 ;} } }' ; then
```

I'll try to take time to create a PR.

**Comment by native-api** [comment]
Actually, something like `[[ ":$PATH:" == *":${PYENV_ROOT}/shims:"* ]]` should work.

Strangely, I never found this solution applied specifically to `PATH`! (It can be found by "bash check if contains a substring" -- but you need to come up with surrounding `$PATH` to make this leap.)
