### ISSUE TITLE
pyenv install failed. configure: error: cannot run C compiled programs

### ISSUE THREAD

**Issue by tsonglew** [pyenv/pyenv#1926]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS Big Sur 11.2.3
- [x] OS architecture (e.g. amd64): Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
- [x] pyenv version: 1.2.27
- [x] Python version: 3.9.2
- [x] C Compiler information (e.g. gcc 7.3):  12.0.5 
- [x] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`
  https://gist.github.com/tsonglew/dfb82c468092d9abd9eefcaa84d615fd

**Comment by native-api** [comment]
As the output instructs you, check `config.log` in `/var/folders/_w/7x5ykm8x1_3ftrc07v95gc2c0000gn/T/python-build.20210515180935.43047/Python-3.6.4` to see what exact error happened while trying to run "a C compiled program".

**Comment by mamingxi0906** [comment]
#1746  had deal with the problem for python3.X, if reminder Error like Missing the OpenSSL lib,
set like this might workout.
`
CPPFLAGS="-I<openssl install prefix>/include" \
LDFLAGS="-L<openssl install prefix>/lib" \
pyenv install -v <python version>
`
But I haven't solved it yet for python2.X.
Then for 2.6.6 it didn't work.
```shell
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-2.7.15.tar.xz...
-> https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tar.xz
Installing Python-2.7.15...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 11.2.3 using python-build 1.2.19-6-gbdfed51d)

Inspect or clean up the working tree at /var/folders/41/_my2v6jj69n091pvsvc9k6lw0000gn/T/python-build.20210517140641.23392
Results logged to /var/folders/41/_my2v6jj69n091pvsvc9k6lw0000gn/T/python-build.20210517140641.23392.log

Last 10 log lines:
checking MACHDEP... darwin
checking EXTRAPLATDIR... $(PLATMACDIRS)
checking for --without-gcc... no
checking for --with-icc... no
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/var/folders/41/_my2v6jj69n091pvsvc9k6lw0000gn/T/python-build.20210517140641.23392/Python-2.7.15':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.

**Comment by native-api** [comment]
This had happened for me when I put an incorrect switch into `CFLAGS`.
So check your envvars that affect the compiler.
This was visible in `config.log` as an incorrect command line for the compiler.
