### ISSUE TITLE
Global installation (Question)

### ISSUE THREAD

**Issue by Eolien55** [pyenv/pyenv#1927]
Really good job, pyenv is very useful to me. However, I tried to run a python file with sudo privileges, and it didn't work, because pyenv is installed only for the user that installed it. I wonder if pyenv was meant to allow to configure it globally (in which case the automatic installer (http://pyenv.run) should allow to set the installation as global), or not.
However, have a great day !

**Comment by native-api** [comment]
Pyenv is designed to run with any prefix, so you can install it globally.

However, to be able to use it with Sudo, you'll need for the Sudo environment to somehow retain the necessary environment variables -- `PYENV_ROOT` and `PATH` (if necessary to find `pyenv`).

**Comment by Eolien55** [comment]
Well, thanks for the quick response ; in fact, pyenv is far more flexible than what thought. Awesome tool !
