### ISSUE TITLE
Release for CPython 3.9.5 and 3.8.10

### ISSUE THREAD

**Issue by dbowring** [pyenv/pyenv#1929]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description

Please make an official release including the latest micro releases for CPython (`3.8.10`, `3.9.5`). Thank you.

**Comment by ssbarnea** [comment]
It appears that Fedora 34 already shipped with cpython 3.9.5 while pyenv still lacks behind. My expectation was that pyenv would move much faster than mainline distros at updating python.

**Comment by native-api** [comment]
If someone makes a PR, we'll gladly accept it. Copying existing scripts and changing versions and checksums will likely be enough.

I could do this myself but you're the interested party here and I don't want you to take new version support for granted. We don't currently have a robot that would do this automatically.

**Comment by ssbarnea** [comment]
Release is still a human process, unless you switch to a process of pulling from master. I do remember having the same problem few month back, some issue, code merged but not released.

**Comment by native-api** [comment]
@anton-petrov Since there's [a breaking change](https://github.com/pyenv/pyenv/pull/1898), the major version should probably be bumped.

**Comment by anton-petrov** [comment]
@native-api I have the same opinion.

**Comment by anton-petrov** [comment]
> @anton-petrov Since there's [a breaking change](https://github.com/pyenv/pyenv/pull/1898), the major version should probably be bumped.

Did you mean - bumped to 2?

**Comment by native-api** [comment]
> > @anton-petrov Since there's [a breaking change](https://github.com/pyenv/pyenv/pull/1898), the major version should probably be bumped.
> 
> Did you mean - bumped to 2?

You can bump to 3 if you want :smile:

**Comment by native-api** [comment]
> Did you mean - bumped to 2?

Yes.

Semantic versioning is the sanest scheme I know so why not stick to it.

**Comment by anton-petrov** [comment]
Ok, as you wish, I'll bump it to 3 🤣

**Comment by native-api** [comment]
> 
> 
> Ok, as you wish, I'll bump it to 3 rofl

Nah, don't pin that on me! 🙌

**Comment by anton-petrov** [comment]
@yyuu , what's your opinion?

**Comment by anton-petrov** [comment]
Release: https://github.com/pyenv/pyenv/releases/tag/v2.0.0-rc1
Discussion: https://github.com/pyenv/pyenv/discussions/1938
