### ISSUE TITLE
anaconda3-2021.05 has wrong checksum for MacOS

### ISSUE THREAD

**Issue by marhoy** [pyenv/pyenv#1931]
```╰─ pyenv install anaconda3-2021.05
Downloading Anaconda3-2021.05-MacOSX-x86_64.sh...
-> https://repo.continuum.io/archive/Anaconda3-2021.05-MacOSX-x86_64.sh

BUILD FAILED (OS X 11.3.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/7h/cngf75593v7dn504b5f7smsr0000gn/T/python-build.20210517191221.27477
Results logged to /var/folders/7h/cngf75593v7dn504b5f7smsr0000gn/T/python-build.20210517191221.27477.log

Last 10 log lines:
/var/folders/7h/cngf75593v7dn504b5f7smsr0000gn/T/python-build.20210517191221.27477 ~

checksum mismatch: Anaconda3-2021.05-MacOSX-x86_64.sh (file is corrupt)
expected ec11e325c792a6f49dbdbe5e641991d0a29788689176d7e54da97def9532c762, got 0407bee87eeecad521f1e38eb607b0a85babef4c1b47516dc5c090e152eba5d5
```

**Comment by native-api** [comment]
@anton-petrov https://repo.anaconda.com/archive/ lists MD5 sums rather than SHA256 -- maybe we should stick to that? Otherwise, it's impossible to readily say if there's something wrong with the download, or with our checksum, or the download has changed.

**Comment by anton-petrov** [comment]
Ok, I will check it...

**Comment by binbjz** [comment]
/var/folders/m4/s_tw224x76507gmkn_sjpzpw0000gn/T/python-build.20210519010558.3205 ~/.pyenv
HTTP/2 404
server: GitHub.com
content-type: text/html; charset=utf-8
permissions-policy: interest-cohort=()
access-control-allow-origin: *
etag: "5f920a64-247b"
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'
x-proxy-cache: MISS
x-github-request-id: 859C:5ABD:33E85E:3A636D:60A3F300
accept-ranges: bytes
date: Tue, 18 May 2021 17:05:59 GMT
via: 1.1 varnish
age: 247
x-served-by: cache-hkg17926-HKG
x-cache: HIT
x-cache-hits: 1
x-timer: S1621357560.967849,VS0,VE0
vary: Accept-Encoding
x-fastly-request-id: c0bc5741fab5b6ef2416181ca64fbbd8ebc23faf
content-length: 9339


checksum mismatch: Anaconda3-2021.05-MacOSX-x86_64.sh (file is corrupt)
expected ec11e325c792a6f49dbdbe5e641991d0a29788689176d7e54da97def9532c762, got 0407bee87eeecad521f1e38eb607b0a85babef4c1b47516dc5c090e152eba5d5

**Comment by binbjz** [comment]
We're not having any problems with SHA, so we need to update install_script "ec11e325c..." to "0407bee87..." with sha256
<img width="845" alt="Screen Shot 2021-05-19 at 01 24 06" src="https://user-images.githubusercontent.com/8213913/118696640-16cf4700-b841-11eb-8b96-948944b02d19.png">
<img width="840" alt="Screen Shot 2021-05-19 at 01 24 26" src="https://user-images.githubusercontent.com/8213913/118696659-1c2c9180-b841-11eb-84f5-719b83bc401c.png">
