### ISSUE TITLE
pip install failing with ModuleNotFoundError: No module named '_ctypes'

### ISSUE THREAD

**Issue by sabotagebeats** [pyenv/pyenv#1933]
`File "home/user/.pyenv/versions/3.9.4/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'`

Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ ✅] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ ✅] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ✅ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ✅] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ✅] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [linux 20.04 on wsl2 ] Platform information (e.g. Ubuntu Linux 16.04):
- [intel i5 ] OS architecture (e.g. amd64):
- [pyenv 1.2.26] pyenv version:
- [3.9.4 ] Python version:
- [unknown] C Compiler information (e.g. gcc 7.3): 
- [?] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

**Comment by sabotagebeats** [comment]
https://github.com/ApeWorX/ape-solidity/issues/1

**Comment by sabotagebeats** [comment]
C compiler information: `gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`

**Comment by sabotagebeats** [comment]
https://github.com/pyenv/pyenv/issues/1304#issuecomment-475910149

`libffi-dev is already the newest version (3.3-4).`

**Comment by sabotagebeats** [comment]
https://github.com/pyenv/pyenv/wiki#suggested-build-environment

```
Building dependency tree       
Reading state information... Done
libbz2-dev is already the newest version (1.0.8-2).
libffi-dev is already the newest version (3.3-4).
libncursesw5-dev is already the newest version (6.2-0ubuntu2).
libreadline-dev is already the newest version (8.0-4).
libxml2-dev is already the newest version (2.9.10+dfsg-5).
libxmlsec1-dev is already the newest version (1.2.28-2).
make is already the newest version (4.2.1-1.2).
wget is already the newest version (1.20.3-1ubuntu1).
llvm is already the newest version (1:10.0-50~exp1).
tk-dev is already the newest version (8.6.9+1).
build-essential is already the newest version (12.8ubuntu1.1).
curl is already the newest version (7.68.0-1ubuntu2.5).
liblzma-dev is already the newest version (5.2.4-1ubuntu1).
libsqlite3-dev is already the newest version (3.31.1-4ubuntu0.2).
libssl-dev is already the newest version (1.1.1f-1ubuntu2.3).
xz-utils is already the newest version (5.2.4-1ubuntu1).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu1.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by native-api** [comment]
Need the debug trace as required by the issue template.

**Comment by sabotagebeats** [comment]
after attempting to get the debug trace i'm not sure what happened but it seems to have resolved the issue.

**Comment by Gideon-Felt** [comment]
I'm experiencing this exact same issue.

**Comment by native-api** [comment]
@Gideon-Felt We need the debug trace as per the issue template to be able to say anything.

**Comment by lmarvaud** [comment]
Hello,

I encounter a similar problem. This comment (https://github.com/pyenv/pyenv/issues/1933#issuecomment-843583692) was usefull :

> [#1304 (comment)](https://github.com/pyenv/pyenv/issues/1304#issuecomment-475910149)
> 
> `libffi-dev is already the newest version (3.3-4).`

Looking into the https://github.com/pyenv/pyenv/issues/1304#issuecomment-475910149, I figured the full log noticed two things :
```
INFO: Can't locate Tcl/Tk libs and/or headers
```
and 
```
*** WARNING: renaming "_ctypes" since importing it failed: libffi.so.8: cannot open shared object file: No such file or directory
```

I fixed the first by installing `tk-dev` (didn't fixed the problem)
```
apt-get install tk-dev
```

I fixed the second by following this answer : https://stackoverflow.com/a/70240391 (I didn't try without `tk-dev` installed) 
```
$ brew remove --ignore-dependencies libffi
$ pyenv install 3.6.8  # 3.6.8 in my case
$ brew install libffi
```

**Comment by Gideon-Felt** [comment]
I discovered you either have to have pyenv and all the build dependencies installed through Brew, or non at all through Brew and have them installed via the package manager, if you have them mixed and matched there are some kind of improper assumptions made by pyenv when compiling/installing. and it won't find `libffi` from brew or it won't find `libffi-dev` from the package manager. (No mixing and matching!)
I fixed this problem by deleting my `~/.pyenv` and removing all the dependencies from brew(I uninstalled it all together actually) and force reinstalled all the dependencies and also made sure there were no other conflicting python interpreters&configs besides what came with my distro. then re-installed pyenv and my selected python version and then the packages I wanted to be installed, installed just fine without complaining about missing _ctypes (from the cffi <- libffi-dev) and all is working properly now.

**Comment by caleb15** [comment]
Similar issue: https://stackoverflow.com/questions/27022373/python3-importerror-no-module-named-ctypes-when-using-value-from-module-mul

One person [fixed it by specifying the brew gcc](https://stackoverflow.com/a/70531532/6629672). That solution worked for me as well.
