### ISSUE TITLE
init changes left no easy solution to source completion

### ISSUE THREAD

**Issue by cornfeedhobo** [pyenv/pyenv#1941]
When pyenv moved to preferring `init --path`, something that is now missed is the sourcing of the included completion that `init -` used to source. I think an easy solution could be adding another flag `init --completion $SHELL`. If I find time to open a PR, I'll do just that.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04):
- [x] OS architecture (e.g. amd64): `amd64`
- [x] pyenv version: `pyenv 2.0.0-rc1-2-gac4de222`
- [ ] Python version:
- [ ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach verbose build log as gist

**Comment by native-api** [comment]
[Check the README](https://github.com/pyenv/pyenv#basic-github-checkout). _Both_ `pyenv init --path` and `pyenv init -` are required, in different places.

**Comment by cornfeedhobo** [comment]
@native-api I see what you mean. Interesting. the instructions just weren't that clear. Thanks.

**Comment by native-api** [comment]
You may need to update the codebase. The instructions were unclear at first [but were corrected shortly after](https://github.com/pyenv/pyenv/pull/1920).
