### ISSUE TITLE
sudo: pip3: command not found

### ISSUE THREAD

**Issue by leonheess** [pyenv/pyenv#1945]
### Description
- Debian 10.9
- pyenv 2.0.0
- Python 3.7.9
- C Compiler information ?

Pip doesn't work after installing. Here are the exact commands I used after creating a **new fresh Debian VM (!)**:

```
sudo apt upgrade
sudo apt update
sudo apt install git

git clone https://github.com/pyenv/pyenv.git ~/.pyenv

nano ~/.profile
  added to top:
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
echo 'eval "$(pyenv init -)"' >> ~/.bashrc

sudo apt-get update; sudo apt-get install make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

--- restart login sesh

pyenv --version --> 2.0.0
env PYENV_DEBUG=1 pyenv install -v 3.7.9 --> https://gist.github.com/leonheess/07bd1cb3185d689d26c6917f62767b2b
pyenv shell 3.7.9
pyenv local 3.7.9

sudo pip3 install virtualenv --> Error
```

Interestingly enough `which pip3` results in `/home/mixt4pe/.pyenv/shims/pip3`

**Comment by native-api** [comment]
Can't say anything without a debug trace as required by the issue template.
My guess is you're missing some build dependencies which resulted in an error instlaling Pip.

**Comment by PierreKiwi** [comment]
Could it be because your `~/.profile` is not executed*?

* not sure if it is the right term in this context.

**Comment by mkschl** [comment]
You need to run ```pyenv init`` to see the configuration changes after upgrading to 2.0.0, There is a warning when you start a new terminal window.

**Comment by leonheess** [comment]
> Can't say anything without a debug trace as required by the issue template.
> My guess is you're missing some build dependencies which resulted in an error installing Pip.

I updated the issue with the gist (:

**Comment by leonheess** [comment]
> Could it be because your `~/.profile` is not executed*?
> 
> * not sure if it is the right term in this context.

I'm sorry. I don't understand your question

**Comment by leonheess** [comment]
> You need to run `pyenv init` to see the configuration changes after upgrading to 2.0.0, There is a warning when you start a new terminal window.

Running `pyenv init` did not solve my problem

**Comment by native-api** [comment]
> sudo pip3 install virtualenv --> Error

`sudo` creates a different environment. You need to run `sudo -E` to preserve yours or otherwise somehow set envvars that Pyenv depends on to correct values.

And **you don't really need sudo here at all** because the Python instllation is under your profile so you already have the permissions to install packages into it.

**Comment by leonheess** [comment]
> `sudo` creates a different environment. You need to run `sudo -E` to preserve yours or otherwise somehow set envvars that Pyenv depends on to correct values.
> 
> Better yet, **you don't really need sudo here at all** because the Python installation is under your profile so you already have the permissions to install packages into it.


Thank you so much!
