### ISSUE TITLE
[Feature Request] Support resolving minor Python versions automatically in .python-version

### ISSUE THREAD

**Issue by boltronics** [pyenv/pyenv#1946]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] pyenv version: 2.0.0
(other issue defaults not applicable)

I would like to see:
```
3.8
```
(for example) as the contents of a `.python-version` file, and have this cause `pyenv` to use the latest 3.8 stable release it knows about. ie. 3.8.10 (a the time of writing).

If that is not available, the error would be:
```
pyenv: version `3.8.10' is not installed (set by /path/to/.python-version)
```

Related feature request: https://github.com/pyenv/pyenv/issues/1349

In that thread @hyperknot wrote:
> Can you support the same logic as the Node / nvm community has embraced for a very long time? In nvm "3.7" means latest from 3.7.x and "3.7.7" means exactly version 3.7.7.

This makes a lot of sense from a user standpoint. There is no Python 3.7, there is only 3.7.0. There is a 3.7-dev for what appears to be the 3.7 branch, which likewise does not introduce conflicts.

I think the `:latest` tag used by the `install` argument is misleading, as it's only the latest "stable" release that the `pyenv` version currently running knows about. 

(As an aside, this assumes one is not thinking of the `-dev` releases, as that would be the actual latest version available - and there's nothing to indicate that `latest` doesn't refer to a dev build.)

This is in contrast to other tools such as Docker that use `latest`, since that is actually a tag applied to the image during upload, and hence it is quite accurate to say "this is the latest image" in Docker's case. I think there is a strong argument to be made that `pyenv` is much closer to `nvm` in this respect. I also feel strongly that consistency is important for usability, so would rather see `pyenv` working similarly to `nvm` in this instance.

**Comment by native-api** [comment]
* > and have this cause `pyenv` to use the latest 3.8 stable release it knows about. ie. 3.8.10 (a the time of writing).

   *  _Exactly the latest known?_ Logically speaking, any other installed release from the `3.8` version line would do.

   * Would other flavors qualify? Alternative installations (e.g. https://github.com/pyenv/pyenv/issues/1417)? Prereleases/branch heads? The system Python if it's of an appropriate version (=the one which is futher on `PATH`, whatever it is)?

* > 3.8

    There's a problem with this syntax. Pyenv installations can be named anything (and I mean, _anything_ -- any valid directory name). **How would Pyenv know you want to invoke the version-picking logic rather than just mistyped/specified a nonexistent version?**

**Comment by boltronics** [comment]
Good questions.

>     * > and have this cause `pyenv` to use the latest 3.8 stable release it knows about. ie. 3.8.10 (a the time of writing).
>       * _Exactly the latest known?_ Logically speaking, any other installed release from the `3.8` version line would do.
>       * Would other flavors qualify? Alternative installations (e.g. #1417)? Prereleases/branch heads? The system Python if it's of an appropriate version (=the one which is further on `PATH`, whatever it is)?

I would suggest we aim for consistency.

From the NVM [README](https://github.com/nvm-sh/nvm):

> make nvm default to the latest 5.9 release...:
> `$ echo "5.9" > .nvmrc`

Taken at face value, in Python's "3.8" case this would mean 3.8.10. I think it's safe to consider a release as anything considered "final" by the Python project. I would surely exclude alpha, beta and candidate builds - but `pyenv` doesn't support building those cpython tags out of the box anyway AFAIK/CT.

>         * How would we pick the "best" match if there are multiple?

I would suggest version matching logic would work something like this:

Does version exist?
 - Yes, use that version. Done
 - No, continue.

Do versions exist that match what was specified, with some additional characters starting with a `.` that end with a period followed by some digits? ie. if "3.8" was specified, does `^3\.8\(\..*\)?\.[0-9]+$` exist?
- No, abort with usual `pyenv: version `3.8' is not installed (set by /some/path/.python-version)`
- Yes, continue:

Get latest version by this kind of logic:
```
$ pyver() { grep "^$(cat .python-version)\(\..*\)\?\.[0-9]\+$" <(pyenv install -l | tail -n +2 | tr -d ' ') | sort -V | tail -n 1 ; }
$ echo 3.8 > .python-version 
$ pyver
3.8.10
$ echo 3.9 > .python-version 
$ pyver
3.9.5
$ echo 2.7 > .python-version 
$ pyver
2.7.18
$ echo 3 > .python-version 
$ pyver
3.9.5
$ echo 2 > .python-version 
$ pyver
2.7.18
$ echo pypy2 > .python-version 
$ pyver
pypy2.7-7.3.1
$
```

Well we can fine tune it (for example, the contents of `.python-version` should be escaped into something regex-compatible for maximum accuracy), but I think the general idea of this implementation ought to align with the expectations of almost all `pyenv` users who want this feature.

>     * > 3.8
> There's a problem with this syntax. Pyenv installations can be named anything (and I mean, _anything_ -- any valid directory name). **How would Pyenv know you want to invoke the version-picking logic rather than just mistyped/specified a nonexistent version?**

It would have to be very specifically named. You would have to provide an example for me to fully understand what you mean any why it would be a significant problem that would outweigh the benefits. In the example implementation above, you need both the next character to be a period, and the final characters to be digits for a match to occur.

In any case, I'd suggest we add an example of the behaviour to the README similarly to what `nvm` has done, so users are aware.

**Comment by native-api** [comment]
> I would suggest we aim for consistency.
> 
> From the NVM [README](https://github.com/nvm-sh/nvm):
> 
> > make nvm default to the latest 5.9 release...:
> > `$ echo "5.9" > .nvmrc`

`nvm` only supports one line of releases, so for it, "`5.9`" is unambiguous. Pyenv suppoorts an arbitrary number of independent release lines, so "`X.Y`" is ambiguous.

Despite that, we can simply support only official CPython for now, and add new syntax if and when users emerge with an appropriate use case.

> make nvm default to the latest 5.9 release...:

That's a spectacularly extraordinary and unclear promise worthy of an ad pamphlet :stuck_out_tongue: How does it actually behave?

* Does it switch automatically once you install a newer version/uninstlal the newest version (leaving all your modules behind silently)? Or there's some additional mechanism secretly at work to prevent that?
* Does "latest" mean "latest known" or "latest installed"?

> You would have to provide an example for me to fully understand what you mean any why it would be a significant problem that would outweigh the benefits.

* An installation's name can be nonindicative of the version it provides.
* Users can create their own, arbitrarily-named installation entries.

So with any "special" naming scheme you choose, someone, somewhere is going to make up name that would create a false positive or a false negative. E.g.:

* `miniconda3-4.7.12` provides some Python version, but there's no way to find out which, its version is completely disconnected from the version of Python it provides.
* A user can create a virtual environment named like `3.8-project`, or `janus_project`, or create a Python installation with custom build flags named like this.
* A user can add alternative line of installation scripts with a plugin which would, by necessity. E.g.

**Comment by boltronics** [comment]
> nvm only supports one line of releases, so for it, "5.9" is unambiguous. Pyenv suppoorts an arbitrary number of independent release lines, so "X.Y" is ambiguous.

That's like saying `pyenv install 2.5.0` is ambiguous. Is it CPython? anaconda2? jython? pypy? `pyenv` supports all these and I don't see why this would be considered an issue but that wouldn't be.

```
$ pyver() { grep "^$(cat .python-version)\(\..*\)\?\.[0-9]\+$" <(pyenv install -l | tail -n +2 | tr -d ' ') | sort -V | tail -n 1 ; }
$ echo 2.5 > .python-version 
$ pyver
2.5.6
$ echo jython-2.5 > .python-version 
$ pyver
jython-2.5.3
$ echo anaconda2-2.5 > .python-version 
$ pyver
anaconda2-2.5.0
$ echo pypy-2.5 > .python-version 
$ pyver
pypy-2.5.1
$ 
```
Looks fine to me.

Perhaps if one of the projects changed to a new completely different versioning system it might be a problem, but even then, I don't see why that would be a concern - you would just exclude `stackless-` matches or whatever from being supported.


> > make nvm default to the latest 5.9 release...:
> 
> That's a spectacularly extraordinary and unclear promise worthy of an ad pamphlet stuck_out_tongue How does it actually behave?

It's free software. There's nothing stopping us from inspecting the code if necessary. Alternatively, perhaps this is clarified somewhere in the docs, or perhaps @hyperknot can elaborate?


>     * Does it switch automatically once you install a newer version/uninstlal the newest version (leaving all your modules behind silently)? Or there's some additional mechanism secretly at work to prevent that?

I would personally hope it automatically switches. If you didn't want it to change, you would specify a fixed version, no? Regardless, I would go with what `nvm` does, as it seems people are satisfied by that implementation AFAIK.


>     * Does "latest" mean "latest known" or "latest installed"?

My expectation would be "latest known" since that would be consistent with how it would work when the latest version is requested on the command line (although the syntax would now be inconsistent due to the `:latest` requirement, but would hope we can correct that eventually). Currently when you specify a specific version, you get an error when that version is not installed. I see no reason why it would be any different when you don't specify a version.

I believe this issue didn't come up because people didn't care which version of Python was used (as in, "oh anything in the 3.6 series you have will do"), but rather because people want to ensure everyone is up to date with Python security/bug fixes and not having the project with a `.python-version` holding it back. It leaves people wondering if, for example 3.6.12 was specified for a specific reason (ie. is it broken somehow in 3.6.13) or if the file has fallen behind on getting updated. If only "3.6" was specified, it would be a non-issue.

Having said that, if a developer really doesn't care which version in the 3.6 series was used, it shouldn't be much of an issue in that case to enforce the latest in the 3.6 series that `pyenv` is aware of.

It's also worth keeping in mind that versions will not change anywhere if `pyenv` isn't updated to have new CPython (or whatever is supported) version information, so the user would generally be aware that they have made this change (or applied a `pyenv` update) - which we can document as being something end-users should be aware of, where this feature is described.


> So with any "special" naming scheme you choose, someone, somewhere is going to make up name that would create a false positive or a false negative. E.g.:
> 
>     * `miniconda3-4.7.12` provides some Python version, but there's no way to find out which, its version is completely disconnected from the version of Python it provides.

Why does that example specifically matter?
```
$ pyver() { grep "^$(cat .python-version)\(\..*\)\?\.[0-9]\+$" <(pyenv install -l | tail -n +2 | tr -d ' ') | sort -V | tail -n 1 ; }
$ echo miniconda3-4.7 > .python-version
$ pyver
miniconda3-4.7.12
$ echo miniconda3-4 > .python-version
$ pyver
miniconda3-4.7.12
$ echo miniconda3-4.7.10 > .python-version
$ pyver
$ 
```
Looks fine to me. If `miniconda3-4.7.12` were specified, that exactly matches a known release and wouldn't need to go through this version matching process.
 
>     * A user can create a virtual environment named like `3.8-project`, or `janus_project`, or create a Python installation with custom build flags named like this.

If they specify `3.8-project`, the above will support that. If they create `janus_project`, it will support that. Again, these are exact matches.

If someone created `3.9.6` and used a project referencing `3.9`, it will match - but I would argue that's likely what they intended if they did that.
 
>     * A user can add alternative line of installation scripts with a plugin which would, by necessity. E.g.

I think your example was cut off so not sure what you meant with that last one, or why that would be a problem.

**Comment by native-api** [comment]
> $ pyver() { grep "^$(cat .python-version)\(\..*\)\?\.[0-9]\+$" <(pyenv install -l | tail -n +2 | tr -d ' ') | sort -V | tail -n 1 ; }
> $ echo 2.5 > .python-version 
> $ pyver
> 2.5.6
> $ echo jython-2.5 > .python-version 
> $ pyver
> jython-2.5.3
> $ echo anaconda2-2.5 > .python-version 
> $ pyver
> anaconda2-2.5.0
> $ echo pypy-2.5 > .python-version 
> $ pyver
> pypy-2.5.1
> $

So, you're proposing to make `version` act essentially the same as `version:latest` does now.

I guess we can give it a whirl.

> It's free software. There's nothing stopping us from inspecting the code if necessary.

I didn't want to go spellinking in NVM (or rather, I did and the logic is not clear at first glance so I stopped wasting time). Since you are the interested party, it's in your best interests to clarify those details before replicating the functionality to make sure you don't shoot yourself (and everyone else) in the foot.

> I would personally hope it automatically switches. If you didn't want it to change, you would specify a fixed version, no?

Keep in mind that if it switches automatically, it will break existing projects since `site-packages` would be left behind.

* I was thinking of creating a lockfile like `.pyenv-version.lock` (like `Pipfile` and `Pipfile.lock`) after picking a version -- when the users wishes to migrate, they will erase that file.
* Altertnatively, NVM has an function to migrate installed packages to a new installation. Again, we'll need to clarify how it does that if we're to replicate that functionality -- since it's not possible/desirable to either mechanically move `site-packages` or even `pip install $(pip freeze)` in the general case.

**Comment by hyperknot** [comment]
`.pyenv-version.lock` -> This wouldn't work as the different platforms have different latest patch releases at the same time.

Can we simplify this problem and just do it for mainline / CPython releases first? That'd help 95% of the users and give security to most.

- `3.8` or `3.8.x` goes to "latest in 3.8 branch which is currently available on the current pyenv release"
- anything else - install like currently

**Comment by native-api** [comment]
> Can we simplify this problem and just do it for mainline / CPython releases first? That'd help 95% of the users and give security best practices to the platform.

Fine either way.

Go ahead, make a PR.

**Comment by BrandonLWhite** [comment]
In the interim, I have found the following workaround gets the job done:
```
pyenv install 3.7:latest
ln -s ~/.pyenv/versions/3.7.12 ~/.pyenv/versions/3.7
pyenv local 3.7
python --version
--> Python 3.7.12
```

**Comment by BrandonLWhite** [comment]
I created a plugin to do this automatically: 
https://github.com/upside-services/pyenv-alias-latest-patch-version

**Comment by fredrikaverpil** [comment]
Just want to give a quick mention that [actions/setup-python](https://github.com/actions/setup-python) can take a `.python-version` file containing `3.10` and will then install the latest 3.10.x.

See the docs for more info here: https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-the-python-version-file-input

**Comment by native-api** [comment]
Implemented auto-resolving micro versions in https://github.com/pyenv/pyenv/pull/2487
