### ISSUE TITLE
Pyenv 2.0 virtualenv can't be loaded into zsh shell anymore

### ISSUE THREAD

**Issue by houmie** [pyenv/pyenv#1947]
Hello,

Pyenv was once so easy to install. Sadly the latest version has tainted this experience and made this so unnecessarily frustrating.

I'm on Mac M1 and when I try to ```pyenv activate v395``` I get this error:

```
Failed to activate virtualenv.

Perhaps pyenv-virtualenv has not been loaded into your shell properly.
Please restart current shell and try again.
```

*vim ~/.zshrc*
```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"
```

The documentation is outdated and is misleading, I don't think ```eval "$(pyenv init -)"``` is allowed anymore.
https://github.com/pyenv/pyenv-virtualenv#installing-with-homebrew-for-macos-users

I have ```source ~/.zshrc``` but it doesn't help.

```
➜  ~ pyenv --version
pyenv 2.0.0

➜  ~ pyenv-virtualenv --version
/opt/homebrew/bin/pyenv-virtualenv: line 106: pyenv-version-name: command not found
/opt/homebrew/bin/pyenv-virtualenv: line 141: pyenv-prefix: command not found
pyenv-virtualenv 1.1.5 (virtualenv unknown)
```

**Comment by jav-12** [comment]
Having the same issue

`-- console output produced during zsh initialization follows --

WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.`

**Comment by hortonew** [comment]
Any reference to `pyenv init -` should be updated to `pyenv init --path`.  But then you'll be seeing the initial issue above.

**Comment by hortonew** [comment]
See https://github.com/pyenv/pyenv-virtualenv/issues/387.  You can fix by updating your ~/.zshrc with the following 3 lines:

```
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

**Comment by jefftriplett** [comment]
Apologies. While not 100% related, this same fix was needed to make **pyenv-virtualenvwrapper** work too:

```bash
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
pyenv virtualenvwrapper
```

**Comment by native-api** [comment]
```
% cat ~/.zprofile 
export PYENV_ROOT=~/.pyenv
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

% cat ~/.zshrc   
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
eval "$(pyenv init -)"
```

Zsh is set to run as a login shell (note the "`l`"):

```
% echo "$-"
569XZilms
```
