### ISSUE TITLE
Pyenv 2.0 stops working after an upgrade to macOS Big Sur 11.4

### ISSUE THREAD

**Issue by edbergavera** [pyenv/pyenv#1948]
I noticed pyenv no longer works after upgrading to macOS 11.4. Immediately after the successful upgrade, I opened up iTerm and saw this message:

`WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.`

I then ran the `pyenv init` command and followed the instructions. I added the following commands in both `~./profile` and `~./zprofile`

`export PYENV_ROOT="$HOME/.pyenv"`
`export PATH="$PYENV_ROOT/bin:$PATH"`
`eval "$(pyenv init --path)"`

Restarted my session by terminating iTerm2. The warning message is gone. But pyenv does not seem to switch to the version I set which is 3.9.5. 

<img width="516" alt="Screen Shot 2021-05-26 at 9 37 31 AM" src="https://user-images.githubusercontent.com/1595001/119590310-161d4e80-be07-11eb-98e5-bbf4a94340d1.png">

OS: macOS 11.4
Shell: zsh 5.8 (x86_64-apple-darwin20.1.0)
Pyenv version: 2.0 (updated on Monday via Homebrew)

**Comment by bolinocroustibat** [comment]
Same here. I reinstalled pyenv but that raised other issues

**Comment by LukeAI** [comment]
similar/same issue on ubuntu 20.04. commenting to follow

**Comment by native-api** [comment]
> Restarted my session by terminating iTerm2

1. Do you also have anything relevant in `~/.zshrc`?
2. Make sure you run your shell in iTerm as a login shell. MacOS GUI frontend doesn't act as a login shell like Linux GUIs do.
3. Please show the output of `which -a python`, `pyenv which python` and your `PATH`.

**Comment by omz13** [comment]
FWIW: Instead of `export PATH="$PYENV_ROOT/bin:$PATH"` use `export PATH="$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH"`. This works with my homebrew install of pyenv on macOS 11.4; YMMV.

**Comment by omz13** [comment]
Based on #1947,  I _finally_ managed to get pyenv working with macOS 11.4 and zsh by:

in `~/.zshrc' having:

```sh
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
```

**Comment by pulberg** [comment]
Same results on macOS 11.3.1 after updating to pyenv 2.0 via `brew`, followed instructions outlined in `pyenv init` but still prompted about pyenv PATH - 

```
➜ pyenv global
3.8.3
```
```
➜ python
Python 2.7.17 (default, Dec 23 2019, 21:25:34)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

OS: macOS 11.3.1
shell: GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin19.6.0)

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv-virtualenv/issues/387#issuecomment-847855719

**Comment by native-api** [comment]
Here's an example of a correct setup with `pyenv-virtualenv`: https://github.com/pyenv/pyenv-virtualenv/issues/387#issuecomment-847855719.

If Pyenv is installed with Homebrew, you only need:

> 
> 
> This fixed my zsh setup:
> 
> .zprofile
> 
> ```
> eval "$(pyenv init --path)"
> ```
> 
> .zshrc
> 
> ```
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```

**Comment by pulberg** [comment]
@native-api the comment you referenced is how i already had it set and it was not working (i am skipping the pyenv-virtualenv as i do not have that)- 

.profile and .bash_profile
```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```
.bashrc
```
eval "$(pyenv init -)"
```
This was done according to the directions from `pyenv init`.  I now have it working by removing `eval "$(pyenv init --path)"` from my .profile and .bash_profile and adding it to my .bashrc. I don't know if this is correct, but it makes pyenv work correctly again.

**Comment by native-api** [comment]
> I now have it working by removing `eval "$(pyenv init --path)"` from my .profile and .bash_profile and adding it to my .bashrc. I don't know if this is correct, but it makes pyenv work correctly again.

That's incorrect, you're going to experience https://github.com/pyenv/pyenv/issues/1649 with this setup.
Are you in Linux? (If yes, what are you doing in this topic? It's about MacOS.) In Linux, you need to fully log out and log back in for changes to `~/.profile` to take effect.

**Comment by pulberg** [comment]
As stated in my previous post - 

OS: macOS 11.3.1
shell: GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin19.6.0)

**Comment by edbergavera** [comment]
I can confirm the solution by @omz13 is working on my end :). No other changes were made. Yey!

`eval "$(pyenv init --path)"`
`eval "$(pyenv init -)"`

<img width="510" alt="Screen Shot 2021-05-27 at 1 31 12 AM" src="https://user-images.githubusercontent.com/1595001/119705425-4f979d80-be8b-11eb-8505-642c1c8f2093.png">

**Comment by native-api** [comment]
> 
> 
> As stated in my previous post -
> 
> OS: macOS 11.3.1
> shell: GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin19.6.0)

Make sure that you run the shell in the terminal as a login shell then.

If you do, I'll need a trace of shell startup to figure out what in happening, preferrebly with `PS4` from https://wiki-dev.bash-hackers.org/scripting/debuggingtips#making_xtrace_more_useful

**Comment by pulberg** [comment]
Yes, iTerm2 configured profile as "Login Shell". I will put the config back to the broken state configured as the instructions indicate and try to get the trace for you.

**Comment by pulberg** [comment]
gist of xtrace output - [https://gist.github.com/pulberg/9a0b265b593db8e8ff44fbc0482e1d32#file-pyenv-xtrace](url)

let me know if this isn't helpful if there is something else you need.

**Comment by native-api** [comment]
> 
> 
> gist of xtrace output - [https://gist.github.com/pulberg/9a0b265b593db8e8ff44fbc0482e1d32#file-pyenv-xtrace](url)
> 
> let me know if this isn't helpful if there is something else you need.

Are you sure this is the full startup and in the correct order?
I see `pyenv init -` output -- but it's not executed anywhere.
and then it jumps from `.bash_profile` to `.bashrc` without it being sourced:

> ++(/Users/pulberg/.bash_profile:6): pyenv init --path
> ++(/Users/pulberg/.bashrc:43): pyenv(): local command

Do you have `ENV` or `BASH_ENV` set, by any chance?

**Comment by native-api** [comment]
> Do you have `ENV` or `BASH_ENV` set, by any chance?

Also check if your `/etc/profile` sources `~/.bashrc` (see SUSE note in the README).

**Comment by pulberg** [comment]
this is the output from a new shell "tab", it is the complete output, no env or bash_env set. 

/etc/profile - 
```
cat /etc/profile
# System-wide .profile for sh(1)

if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi

if [ "${BASH-no}" != "no" ]; then
	[ -r /etc/bashrc ] && . /etc/bashrc
fi
```

**Comment by native-api** [comment]
Okay, could you add tracing to _all_ Bash startup files? So whichever order they are executed in, we'll see that.

Add this to the beginning of all the following files (if they exist): `/etc/profile`, `~/.bash_profile`, `~/.bash_login`, `~/.profile`, `~/.bashrc` -- and repeat the tracing.

```
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -x
```

---

Also let's double-check if there are any envvars that affect Bash's behavior: `set | grep BASH`.

**Comment by pulberg** [comment]
I updated `.bashrc`, `.bash_profile`, and `.profile` - 

[https://gist.github.com/pulberg/73c9acc441eccf0c5c17b01bebf9027e#file-pyenv-xtrace2](url)

**Comment by jakobmoss** [comment]
I see the same issue. Using the setup described by `pyenv init` seemingly does not work on MacOS 11.4 with pyenv 2.0.0. 

Using the suggestion by @omz13 make things behave normal again. I have the following in my `.zshrc` and `.zshenv`:
```
if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi
```

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/issues/1948#issuecomment-848954350

> 
> Here's an example of a correct MacOS Zsh setup with `pyenv-virtualenv`: [pyenv/pyenv-virtualenv#387 (comment)](https://github.com/pyenv/pyenv-virtualenv/issues/387#issuecomment-847855719).
> 
> If Pyenv is installed with Homebrew, you only need:
> 
> > .zprofile
> > ```
> > eval "$(pyenv init --path)"
> > ```
> >   
> > .zshrc
> > ```
> > eval "$(pyenv init -)"
> > eval "$(pyenv virtualenv-init -)"
> > ```

Make sure to restart your terminal for the changes to take effect.

If you put everything into `~/.zshrc` as @omz13 suggested, you will be experiencing https://github.com/pyenv/pyenv/issues/1649.

**Comment by pulberg** [comment]
when will the instructions/docs be updated showing the correct setup for bash on mac os install via homebrew?  I have it set currently according to the docs and it is still not working.

**Comment by native-api** [comment]
@pulberg you never gave the diagnostic info requested so what do you expect? I don't have your machine to test on and it's working on mine.

**Comment by SeanRavenhill** [comment]
> I can confirm the solution by @omz13 is working on my end :). No other changes were made. Yey!
> 
> ```
> eval "$(pyenv init --path)"
> eval "$(pyenv init -)"
> ```
> 
> <img alt="Screen Shot 2021-05-27 at 1 31 12 AM" width="510" src="https://user-images.githubusercontent.com/1595001/119705425-4f979d80-be8b-11eb-8505-642c1c8f2093.png">

I can confirm the same on my side. Creating a dot file .zprofile and separating the pormo

> I see the same issue. Using the setup described by `pyenv init` seemingly does not work on MacOS 11.4 with pyenv 2.0.0.
> 
> Using the suggestion by @omz13 make things behave normal again. I have the following in my `.zshrc` and `.zshenv`:
> 
> ```
> if command -v pyenv 1>/dev/null 2>&1; then
>     eval "$(pyenv init --path)"
>     eval "$(pyenv init -)"
>     eval "$(pyenv virtualenv-init -)"
> fi
> ```

I've got a similar setup and the implementation of the solution on my side. Seems to have returned things to normal and no error message gets thrown now when I restart the shell. 

I've got a separate dot file to handle my `.zshrc` environment, as I point that dot file to a file `.env.sh`.

I use pipenv and anaconda to handle my virtual environments.

Here is the script right now in my `.env.sh`
![Screenshot 2021-05-31 at 13 13 35](https://user-images.githubusercontent.com/11776929/120186350-af879e80-c213-11eb-9bec-39698ebf16e6.png)

And testing it out to handle the global python version:
![Screenshot 2021-05-31 at 13 14 16](https://user-images.githubusercontent.com/11776929/120186458-d1812100-c213-11eb-9379-b7a468f9c42e.png)

So all systems seem to be a go my side.

And no need for a .zprofile dot file. As I did try that and it did not resolve anything and the pyenv init warning error would keep getting thrown.

**Comment by pulberg** [comment]
@native-api  I had to remove the gist due to some info being included that should not have been, i can work on that and re-add.  But this issue is not unique to just me, there are several similar github issues reported by other users, and even more users commenting on those issues, so i'm not sure why you think you need a bunch of info from my machine, other users are reporting the same things.

Also, the core of the issues are manifest in a setup following the `pyenv init` instructions, this should be trivial for you to repro on a vm.

**Comment by native-api** [comment]
@pulberg Everyone who reported issues and provided the necessary diagnostic info so far turned out to either not have followed the instructions, have a unusual setup or otherwise making a mistake somewhere.

**Comment by native-api** [comment]
I've added explicit Zsh instructions for MacOS. Hope this clears things up.

**Comment by davcamer** [comment]
On macOS 11.5.1 using zsh, after following the instructions in `pyenv init`, I had to log out completely (as in Apple Menu => Log Out <my user>) before pyenv worked again in Terminal. That is despite `echo $0` printing `-zsh` in a new terminal tab, which should mean that I had a new login shell.

I don't understand why a full log out would be needed to refresh the set up of a login shell, but hope this note can help the next person dealing with a non-functional pyenv.

**Comment by gVien** [comment]
Same issue here on Big Sur 11.4. The odd part is it works using Python 2.7.x (or probably any Python 2). See below.

```
Desktop :> pyenv --version
pyenv 2.0.4
Desktop :> pyenv global
3.9.2
Desktop :> python --version
Python 2.7.16
Desktop :> pyenv versions
  system
  2.7.17
  3.8.5
* 3.9.2 (set by /Users/guy/.pyenv/version)
Desktop :> pyenv global 2.7.17
Desktop :> python --version
Python 2.7.17       <===== works in Python 2.x
```

Some info 
```
Desktop :> which -a python
/Users/guy/.pyenv/shims/python
/usr/bin/python
Desktop :> pyenv which python
/Users/guy/.pyenv/versions/2.7.17/bin/python
Desktop :> echo $PATH (truncated version)
/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/guy/.pyenv/shims:/Users/guy/.pyenv/bin:
```

My shell is bash and I use ~/.bash_profile.
So setup is like this. Initially, I didn't have `eval "$(pyenv init --path)"` but had to add it and it seemed to work but I forgot the reason why. 

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)" 
  eval "$(pyenv init --path)"
fi
```

I stopped debugging after a while and end up using `python3` and then either use `virtualenv` or `virtualenvwrapper` with the `workon` command to setup a local Python env that forces the `pyenv global` to work. 

The python3 is still being honored and matches with the `pyenv global`. You may need to becareful with this a bit when using `pip` as the Python version may not match.
Occasionally, I just use `python3 -m pip` in place of just `pip` unless the directory that it listed after you install a package is the same with `python3 -m pip`.

**Comment by Rabia23** [comment]
> Based on some hints in #1947, I _finally_ managed to get pyenv working with macOS 11.4 and zsh by:
> 
> in `~/.zshrc' having:
> 
> ```shell
> eval "$(pyenv init --path)"
> eval "$(pyenv init -)"
> ```

It worked like a charm. Thank you so much :)

**Comment by rivernews** [comment]
For me only the `--path` line matters -

```sh
eval "$(pyenv init --path)"
# eval "$(pyenv init -)"
```

Something must have changed since `eval "$(pyenv init -)"` was working fine...

**Comment by qihboy** [comment]
> Based on some hints in #1947, I _finally_ managed to get pyenv working with macOS 11.4 and zsh by:
> 
> in `~/.zshrc' having:
> 
> ```shell
> eval "$(pyenv init --path)"
> eval "$(pyenv init -)"
> ```

saved my life
os: BigSur 11.6.2
