### ISSUE TITLE
Feature request: install Python under a custom name/alias

### ISSUE THREAD

**Issue by native-api** [pyenv/pyenv#1956]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): all
- [x] OS architecture (e.g. amd64): all
- [x] pyenv version: 2.0.0
- [x] Python version: all
- [x] C Compiler information (e.g. gcc 7.3): all
- [N/A] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

Python-build already allows to override name for an installation. Why not expose this feature to `pyenv install`?

This will be useful for:

* different build flags
* giving an installation a meaningful name
* recently, for Apple M1, different archtectures (https://github.com/pyenv/pyenv/issues/1853)

**Comment by ThijmenDam** [comment]
Agreed. It's a small convenience, and especially useful for when you would like to have two separate instances of the same Python version.

**Comment by joshfriend** [comment]
Check out the list of pyenv plugins: https://github.com/pyenv/pyenv/wiki/Plugins

in particular, https://github.com/s1341/pyenv-alias might work for your purpose

**Comment by ranophoenix** [comment]
Given that this plugin isn't working [anymore](https://github.com/s1341/pyenv-alias/issues/3) with pyenv recent versions, what is the recommended approach to achieve this same result?

**Comment by IvanaGyro** [comment]
@native-api  Due to #2568 [pyenv-alias](https://github.com/s1341/pyenv-alias) doesn't work anymore. Can we reopen this feature request?

**Comment by native-api** [comment]
Well, of course we can...
But shouldn't you rather be fixing the plugin?
If the maintainer has abandoned it, anyone else could fork it and we'll change the link in the wiki.

**Comment by IvanaGyro** [comment]
@native-api 
I think #2568 made the plugin impossible to be fixed. 2568 changed the behavior of generating the installation path.

**Comment by native-api** [comment]
> @native-api I think #2568 made the plugin impossible to be fixed. 2568 changed the behavior of generating the installation path.

It is possible. The logic just needs to move from the hook load time into a before_install function. The person at https://github.com/s1341/pyenv-alias/issues/3#issuecomment-1421591860 just doesn't know how to strip a path component off a path in Bash.
Well, it's `${path%/*}` or `$(dirname "$path")`.

**Comment by esinker** [comment]
you can test this
https://github.com/esinker/pyenv-version-alias.git

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/wiki/Plugins/ebecaa6c91b373890f1ada2d00ef117f1e9d2d29#community-plugins
