### ISSUE TITLE
`eval "$(pyenv init -)"` message persisting even while working on zsh

### ISSUE THREAD

**Issue by zachcoleman** [pyenv/pyenv#1961]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [MacOS ] Platform information (e.g. Ubuntu Linux 16.04):
- [ amd64] OS architecture (e.g. amd64):
- [1.2.26] pyenv version:
- [ ] Python version:
- [ clang-1200.0.32.21] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

After following the README and adding the appropriate code to both .profile and .zprofile:
```shell
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```

The `zsh` startup still gives the message even though the pyenv shims are working:
```shell
# Load pyenv automatically by appending
# the following to your profile:

eval "$(pyenv init -)"

```

I can verify the shims are working like:
```
which python
> /Users/zachcoleman/.pyenv/shims/python
```

This is more of an annoyance than a critical bug. I believe both "profile" files have correct info in them. Please let me know if there is option to suppress this behavior.

**Comment by native-api** [comment]
Please provide the diagnostic info as required by the issue template for us to be able to say anything.

The warning message appears when the `shims` directory is not on `PATH` at the moment when `
eval "$(pyenv init -)"` is called, so this looks like some unusual configuration.

**Comment by cgswong** [comment]
Looks like a change in behaviour where the message is being forced.

Current:
```
❯ pyenv init -
echo 'WARNING: `pyenv init -` no longer sets PATH.'
echo 'Run `pyenv init` to see the necessary changes to make to your configuration.'
export PYENV_SHELL=zsh
source '/usr/local/Cellar/pyenv/2.0.0/libexec/../completions/pyenv.zsh'
command pyenv rehash 2>/dev/null
pyenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(pyenv "sh-$command" "$@")"
    ;;
  *)
    command pyenv "$command" "$@"
    ;;
  esac
}
```

Previous:
```
❯ pyenv init -
export PYENV_SHELL=zsh
source '/usr/local/Cellar/pyenv/2.0.0/libexec/../completions/pyenv.zsh'
command pyenv rehash 2>/dev/null
pyenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(pyenv "sh-$command" "$@")"
    ;;
  *)
    command pyenv "$command" "$@"
    ;;
  esac
}
```

**Comment by zachcoleman** [comment]
Based on the issue template I'm unsure what build log you'd like to see. Are you wanting to see a build log from an installation of a new version of Python using pyenv? To get a better look at configuration? 

This issue is cropping up after I updated pyenv and not from installing new versions of Python. All my versions of Python are working.

**Comment by native-api** [comment]
> Looks like a change in behaviour where the message is being forced.

It looks that way, but if you look at the logic, it's only added to the output if `$PYENV_ROOT/shims` is not on `PATH`.

> Based on the issue template I'm unsure what build log you'd like to see.

Run the faulty command with `PYENV_DEBUG` envvar set to `1` and show the resulting trace.

**Comment by zachcoleman** [comment]
@native-api I activated the `PYENV_DEBUG` environment variable as requested to my `.zshrc` before `eval "$(pyenv init -)"` was called to get the logged info I believe you're looking for here: 
https://gist.github.com/zachcoleman/bc6b3a1078fd4b0048179c4a59641404

**Comment by native-api** [comment]
You're running an old version of `pyenv` in that command somehow, installed into `/Users/zachcoleman/.pyenv`, via a Git checkout presumably. And it doesn't print a warning message as you reported.

**Comment by native-api** [comment]
(But otherwise -- yes, that's exactly the kind of debug trace that I was asking for!)

**Comment by zachcoleman** [comment]
> (But otherwise -- yes, that's exactly the kind of debug trace that I was asking for!)

Yes, that's my bad. Totally makes sense that you wanted that. Just forgot that there's a `pyenv` call in my .zshrc 🤦. 

This seems like potentially a `brew` issue then. I have only installed and then updated through `brew`.

**Comment by native-api** [comment]
Don't worry, it's all good. Please provide a likewise trace of the command that actually reproduces the error -- then I'll be able to tell what the immediate reason is.

Brew doesn't do shell initialization stuff for Pyenv so it's unlikely to be a Brew issue.

**Comment by zachcoleman** [comment]
Okay, so I played with the permutations of `.profile` and `.zprofile` and the message:
```shell
# Load pyenv automatically by appending
# the following to your profile:

eval "$(pyenv init -)"

```
occurs when `eval "$(pyenv init --path)"` is included in the `.zprofile` file on zsh startup.

**Comment by zachcoleman** [comment]
I found where the message is called in the trace:
```shell
+(/Users/zachcoleman/.pyenv/libexec/pyenv-init:69): echo '# Load pyenv automatically by appending'
# Load pyenv automatically by appending
+(/Users/zachcoleman/.pyenv/libexec/pyenv-init:70): echo '# the following to your profile:'
# the following to your profile:
+(/Users/zachcoleman/.pyenv/libexec/pyenv-init:71): echo
+(/Users/zachcoleman/.pyenv/libexec/pyenv-init:72): case "$shell" in
+(/Users/zachcoleman/.pyenv/libexec/pyenv-init:77): echo 'eval "$(pyenv init -)"'
eval "$(pyenv init -)"
+(/Users/zachcoleman/.pyenv/libexec/pyenv-init:80): echo

```

**Comment by native-api** [comment]
> The `zsh` startup still gives the message even though the pyenv shims are working:
> 
> ```shell
> # Load pyenv automatically by appending
> # the following to your profile:
> 
> eval "$(pyenv init -)"
> ```

Okay, I was apparently misunderstanding what the error is.

You're running `pyenv init -` in your shell initialization file -- while you actually need to run `eval "$(pyenv init -)`.

**Comment by zachcoleman** [comment]
I'm confused my `.zprofile` only has:
```shell
# pyenv stuff
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```

and my `.zshrc` has:
```shell
eval "$(pyenv init -)"
```

and I get this message on startup of zsh:
```shell
# Load pyenv automatically by appending
# the following to your profile:

eval "$(pyenv init -)"

```

**Comment by native-api** [comment]
> I have only installed and then updated through `brew`.

> You're running an old version of `pyenv` in that command somehow, installed into `/Users/zachcoleman/.pyenv`, via a Git checkout presumably.

Looks like you have 2 Pyenv installations on your system -- one installed with Homebrew (under `brew --prefix`) and the other, an old one, directly in `~/.pyenv` via Git checkout.

You need to delete everything from `~/.pyenv` (except `~/.pyenv/versions` if you wish to preserve alternate Python installations) to retain only the Homebrew one.

And also delete the `export PATH="$PYENV_ROOT/bin:$PATH"` line from `.zprofile`.

**Comment by zachcoleman** [comment]
Thank you! @native-api

**Comment by SungFeng-Huang** [comment]
Hi @native-api, I've encountered exactly the same issue as @zachcoleman (shims works but just keep getting the message everytime I start zsh):
> I'm confused my `.zprofile` only has:
> 
> ```shell
> # pyenv stuff
> export PYENV_ROOT="$HOME/.pyenv"
> export PATH="$PYENV_ROOT/bin:$PATH"
> eval "$(pyenv init --path)"
> ```
> 
> and my `.zshrc` has:
> 
> ```shell
> eval "$(pyenv init -)"
> ```
> 
> and I get this message on startup of zsh:
> 
> ```shell
> # Load pyenv automatically by appending
> # the following to your profile:
> 
> eval "$(pyenv init -)"
> ```
while I'm using Arch Linux and pyenv is installed via yay.

Here's my debugging message via `env PYENV_DEBUG=1 pyenv init --path`: https://gist.github.com/SungFeng-Huang/f0d1dc62d3d7a8b04938351abb2eeb42

And there seems to be nothing for me to delete under `~/.pyenv`:
<img width="507" alt="截圖 2021-06-08 上午2 01 21" src="https://user-images.githubusercontent.com/22560619/121067274-6f20b580-c7fd-11eb-8346-0698c1cce16a.png">

Do you know how could I fix the problem? Thanks!

**Comment by native-api** [comment]
@SungFeng-Huang You have Pyenv <2 that doesn't have the `pyenv init --path` command.

**Comment by SungFeng-Huang** [comment]
> @SungFeng-Huang You have Pyenv <2 that doesn't have the `pyenv init --path` command.

Updating to pyenv 2.0.1 does fix my problem. Thank you so much!

**Comment by bluekeybo** [comment]
> I just hit this issue after installing pyenv 2.5.0 via `brew`. `pyenv init` output:
> 
> ```
> $ pyenv init
> # Load pyenv automatically by appending
> # the following to 
> # ~/.bash_profile if it exists, otherwise ~/.profile (for login shells)
> # and ~/.bashrc (for interactive shells) :
> 
> export PYENV_ROOT="$HOME/.pyenv"
> [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
> eval "$(pyenv init -bash)"
> 
> # Restart your shell for the changes to take effect.
> ```
> 
> but this was incorrect.
> 
> 1. There is no `$PYENV_ROOT/bin` dir. Instead, it seems this should be `$PYENV_ROOT/shims`
> 2. it seems the command should be `pyenv init -` not `pyenv init -bash`
> 
> I instead added to my `~.profile`:
> 
> ```
> export PYENV_ROOT="$HOME/.pyenv"
> [[ -d $PYENV_ROOT/shims ]] && export PATH="$PYENV_ROOT/shims:$PATH"
> eval "$(pyenv init -)"
> ```
> 
> and things seem to be working now

Thank you! This worked for me too, also using pyenv 2.5.0 via brew, and zsh.
