### ISSUE TITLE
pyenv global doesn't work with multiple versions

### ISSUE THREAD

**Issue by mplanchard** [pyenv/pyenv#1967]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 20.04
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 2.0.0
- [x] Python version: 3.8.6 3.7.9 3.6.12 3.9.1
- [x] C Compiler information (e.g. gcc 7.3): gcc 10.3.0
- [x] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

The various python versions install fine, but after running the command `pyenv global 3.8.6 3.7.9 3.6.12 3.9.1`, which used to make all of those python versions available for use, I get the following error when running `python`:

```
$ python
pyenv: version `3.8.6
3.7.9
3.6.12
3.9.1' is not installed (set by /home/matthew/.pyenv/version)
```

The contents of `~/.pyenv/version` are:

```
$ cat ~/.pyenv/version
3.8.6
3.7.9
3.6.12
3.9.1
```

The help for `pyenv global` suggests this should still be possible:

```
$ pyenv global --help
Usage: pyenv global <version> <version2> <..>

Sets the global Python version(s). You can override the global version at
any time by setting a directory-specific version with `pyenv local'
or by setting the `PYENV_VERSION' environment variable.

<version> can be specified multiple times and should be a version
tag known to pyenv.  The special version string `system' will use
your default system Python.  Run `pyenv versions' for a list of
available Python versions.

Example: To enable the python2.7 and python3.7 shims to find their
         respective executables you could set both versions with:

'pyenv global 3.7.0 2.7.15'
```

The output of `pyenv versions`:

```
$ pyenv versions
pyenv: version `3.8.6
3.7.9
3.6.12
3.9.1' is not installed (set by /home/matthew/.pyenv/version)
  system
  3.6.12
  3.7.9
  3.8.6
  3.9.1
```

It works fine if I use `pyenv global` to just set one version. Is the multiple version form no longer supported?

**Comment by native-api** [comment]
WFM for the latest version.

Please attach a debug trace of the faulty command as required by the issue template.
My best guess is line endings are wrong.

**Comment by mplanchard** [comment]
Here's the debug for running `pyenv global 3.8.6 3.7.9 3.6.12 3.9.1`: https://gist.github.com/mplanchard/2751b27255f46d89c86e4fe3727622e7

And the debug for a subsequent call to `python`: https://gist.github.com/mplanchard/57e70635bf0c319015ad6cd1150b10c9

**Comment by mplanchard** [comment]
Also seeing that most of pyenv is bash, so FWIW I'm on bash `4.4.23(1)-release`

**Comment by mplanchard** [comment]
Here's a `cat -A` to show the newlines

```
matthew@mpst:~$ cat -A ~/.pyenv/version
3.8.6$
3.7.9$
3.6.12$
3.9.1$
```

**Comment by native-api** [comment]
I don't like this:

>     +(/home/matthew/.pyenv/libexec/pyenv-version-file-read:11): main(): IFS=$'\r'

For me, it prints:

> ```
> +(/home/vmuser/.pyenv/libexec/pyenv-version-file-read:11): main(): IFS=' 	
> '
> ```
> 

Could you show your default `IFS` like below? Looks like there's something in your configuration that changes the default value and/or default Bash behavior.

```
$ echo -n "$IFS" | xxd
00000000: 2009 0a                                   ..
```

**Comment by mplanchard** [comment]
It doesn't seem to be set. Here's what I've got:

```
$ echo -n "$IFS" | xxd
00000000: 2009 0a                                   ..
$ echo $IFS

```

**Comment by mplanchard** [comment]
Running `export IFS=""`, `export IFS=`, `export IFS="\n"`, or `unset IFS` all seem to solve the issue though! With any of those, the command above outputs nothing at all, but pyenv runs successfully

**Comment by mplanchard** [comment]
Welp, that was very weird. Seems like that must have been set to something strange by something in that particular session. I'm not getting it now when I logout/login to reload the bashrc and the bash profile. Thanks for the help debugging, I'll close the issue!
