### ISSUE TITLE
Configuration instructions might introduce current directory into PATH

### ISSUE THREAD

**Issue by dfn-certling** [pyenv/pyenv#1968]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): openSUSE Tumbleweed

The configuration instructions introduce `$PYENV_ROOT/bin` into the path by exporting `$PYENV_ROOT/bin:$PATH`. This is present (at least) in the description in README.md and output by `pyenv init`. If `$PATH` is empty at the point of this command, this introduces an empty component into `PATH`. This in turn is interpreted by POSIX-conforming shells as a legacy syntax (for example bash) as the current directory. This can result in security issues as the user might suddenly execute programs from the current directory without prefixing them with `./`.

In bash this can be worked around by setting PATH to
```
export PATH="$PYENV_ROOT/bin${PATH:+:${PATH}}
```
This way PATH is expanded to `:$PATH` only when it is set, otherwise the colon is not added and PATH only contains pyenv's bin directory.

**Comment by native-api** [comment]
> If `$PATH` is empty at the point of this command

How can this be? `PATH` is never empty during normal operation.

**Comment by dfn-certling** [comment]
Unfortunately, I do not recall the exact setup that lead to this in my environment and it's not happening in my current setup. I just saw the assignment that leads to this if PATH is empty.

**Comment by native-api** [comment]
Then this is not a realistic concern. Since an empty, or even incorrectly-edited `PATH` makes the system unusable, having the current directory in it will be your least concern at that point.
At least, this is [not something to make people complicate their stock setups to allow for](https://xkcd.com/1172/).
