### ISSUE TITLE
`pyenv install` does not read `.python-version` anymore

### ISSUE THREAD

**Issue by scharf** [pyenv/pyenv#1975]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): `Darwin MacBook-Pro 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`
- [x] OS architecture (e.g. amd64): `x86_64`
- [x] pyenv version: `2.0.1`
- [x] Python version: `3.8,3`
- [x] C Compiler information (e.g. gcc 7.3):  `12.0.5`
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

After upgrading to `pyenv 2.0.1` the command 

```
pyenv install
```

does not work anymore. It used to read the `.python-version` and install the correct version.

The (hack?) solution is to use this:

```
pyenv install `cat .python-version`
```

**Comment by native-api** [comment]
See https://github.com/pyenv/pyenv/pull/1907 why that feature was removed

**Comment by native-api** [comment]
We can reintroduce it if that concern is addressed.

**Comment by foolioo** [comment]
@native-api: please state what is the solution or how should we deal with it? if `.python-version` is not detected automatically and not honored by pyenv, then why do we need this file?

clarification will be great.

**Comment by native-api** [comment]
`.python-version` is still honored, only the use of it by `pyenv install` was removed,

The reason is, if there are multiple versions specified in it, it's unclear what to do, see https://github.com/pyenv/pyenv/issues/919#issuecomment-834835025.

**Comment by scharf** [comment]
> `.python-version` is still honored, only the use of it by `pyenv install` was removed,
> 
> The reason is, if there are multiple versions specified in it, it's unclear what to do, see [#919 (comment)](https://github.com/pyenv/pyenv/issues/919#issuecomment-834835025).

I see. I did not know that it is possible to specify multiple version in the `.python-version` file. I thought it is there to create an absolutely reproducible environment. 

That means my solution (assuming there is only one version in the `.python-version`) is the way to go: 

```sh
pyenv install `cat .python-version`
```

It would be nice if I could specify a filename with a single version for `pyenv install` something like 
```
pyenv instal --version-file .python-version
```

The problem with the `cat` is that it only works for unix....

**Comment by native-api** [comment]
> otherwise, install the first one.

Do you have a real use case for that?

If not, I'd rather make that an error (but with a user-friendly message) in accordance to Python Zen until we get a user with a use case so we can make an informed decision.

**Comment by foolioo** [comment]
@native-api:

> [I would have expected it to try to install each of the listed versions.](https://github.com/pyenv/pyenv/issues/919#issue-231848362)

would that be better?

**Comment by native-api** [comment]
> 
> 
> @native-api:
> 
> > [I would have expected it to try to install each of the listed versions.](https://github.com/pyenv/pyenv/issues/919#issue-231848362)
> 
> would that be better?

YES.

**Comment by native-api** [comment]
@stevecj, could you explain you use case in https://github.com/pyenv/pyenv/issues/919 -- why did you expect all the listed versions to be installed?
