### ISSUE TITLE
Stop using psub for fish shell?

### ISSUE THREAD

**Issue by cedricvanrompay** [pyenv/pyenv#1976]
After upgrading my Ubuntu to 20.04, pyenv (using fish shell) was not working any more.
I uninstalled it and re-installed it using `pyenv-installer`, but I had the same exact errors described [here](https://github.com/fish-shell/fish-shell/issues/6613#issuecomment-588396631):

```
source: Error encountered while sourcing file “/tmp/.psub.BJGzc7yHU6”:
source: No such file or directory
```

If you follow the above link, you see the maintainer of Fish shell suggesting not to use `psub`:

> You want just:
> 
> ```
> set -x PATH "/home/nclarke/.pyenv/bin" $PATH
> status --is-interactive; and pyenv init - | source
> status --is-interactive; and pyenv virtualenv-init - | source
> ```
> 
> psub is entirely useless here.

This fixed my bug, personally. Now it works like a charm.

Shouldn't `pyenv-installer` use these commands instead of `psub`?

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/pull/1916
