### ISSUE TITLE
Why doesn't 'pyenv install --list' list all miniconda distributions I see on https://repo.anaconda.com/miniconda/?

### ISSUE THREAD

**Issue by fad1** [pyenv/pyenv#1982]
(This is from using pyenv 2.0.1 on macOS)

Sorry if this is an obvious question, I asked on reddit and stackoverflow but did not receive any helpful answer.

    pyenv install --list | grep miniconda

Why does this not return miniconda packages that include the corresponding python versions? (eg py38 in Miniconda3-py38_4.9.2-MacOSX-x86_64.sh)

I only get the old versions + miniconda3-latest

**Comment by joshfriend** [comment]
someone has to update the list of available versions, which doesnt happen often because people dont use miniconda with pyenv a whole lot

**Comment by fad1** [comment]
Thank you !
