### ISSUE TITLE
Not able to install python 3.6 with pyenv

### ISSUE THREAD

**Issue by pskrunner14** [pyenv/pyenv#1983]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information: Manjaro Linux (Linux 5.10.41-1-MANJARO)
- [x] OS architecture: x68_64
- [x] pyenv version: 2.0.1
- [x] Python version: 3.6.5
- [x] C Compiler information: 11.1.0

### Issue

Installed pyenv via pyenv-installer and tried to install python versions 3.6.5 with pyenv:
```
env PYENV_DEBUG=1 pyenv install -v 3.6.5
```

Also tried python versions 3.6.9, 3.6.11. None of them are working. Getting a similar output (partial) for all:

```
rm -f /home/psk/.pyenv/versions/3.6.5/bin/pyvenv
(cd /home/psk/.pyenv/versions/3.6.5/bin; ln -s pyvenv-3.6 pyvenv)
if test "x" != "x" ; then \
	rm -f /home/psk/.pyenv/versions/3.6.5/bin/python3-32; \
	(cd /home/psk/.pyenv/versions/3.6.5/bin; ln -s python3.6-32 python3-32) \
fi
rm -f /home/psk/.pyenv/versions/3.6.5/share/man/man1/python3.1
(cd /home/psk/.pyenv/versions/3.6.5/share/man/man1; ln -s python3.6.1 python3.1)
if test "xupgrade" != "xno"  ; then \
	case upgrade in \
		upgrade) ensurepip="--upgrade" ;; \
		install|*) ensurepip="" ;; \
	esac; \
	 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
make: *** [Makefile:1099: install] Error 139
+++(/home/psk/.pyenv/plugins/python-build/bin/python-build:797): build_package_standard_install(): build_failed

+++(/home/psk/.pyenv/plugins/python-build/bin/python-build:126): build_failed(): echo
+++(/home/psk/.pyenv/plugins/python-build/bin/python-build:127): build_failed(): colorize 1 'BUILD FAILED'
+++(/home/psk/.pyenv/plugins/python-build/bin/python-build:91): colorize(): '[' -t 1 ']'
BUILD FAILED+++(/home/psk/.pyenv/plugins/python-build/bin/python-build:91): colorize(): printf '\e[%sm%s\e[m' 1 'BUILD FAILED'
++++(/home/psk/.pyenv/plugins/python-build/bin/python-build:128): build_failed(): os_information
++++(/home/psk/.pyenv/plugins/python-build/bin/python-build:97): os_information(): type -p lsb_release
++++(/home/psk/.pyenv/plugins/python-build/bin/python-build:98): os_information(): lsb_release -sir
```

Was able to install version 3.7+ without issue.

Note: there is a similar issue [here](https://github.com/pyenv/pyenv/issues/1472) (python2.7 on Arch Linux) but I couldn't fix this based on solutions for common build problems.

**Comment by native-api** [comment]
We need the whole debug trace as required by the issue template to be able to say anything.

**Comment by mitchhentges** [comment]
Hey, I'm encountering the exact same issue!

- Platform information: Fedora 34
- OS architecture: x86_64
- pyenv version: 2.0.1
- Python version: 3.9.5 (Host), 3.6.13 (attempted installation in `pyenv`)
- C Compiler information: GCC 11.1.1 20210531 (Red Hat 11.1.1-3)
- Verbose build log: https://gist.github.com/mitchhentges/c888168cca47333ee190bcfeb0ad45bd

**Comment by mitchhentges** [comment]
Update: my issue is the same as #1889, and that could be the case here, too.

**Comment by pskrunner14** [comment]
@mitchhentges the [patch](https://github.com/pyenv/pyenv/issues/1889#issuecomment-837697366) fixed things for me! Thanks

**Comment by AngerM** [comment]
For others who find this now. This worked for me with no patch: 
```
CFLAGS=-Wno-implicit-function-declaration CPPFLAGS="-I$(brew --prefix openssl@1.1)/include -I$(xcrun --show-sdk-path)/usr/include" LDFLAGS="-L$(brew --prefix openssl@1.1)/lib -Wno-implicit-function-declaration" pyenv install 3.6.15
```
You have to make sure its building against openssl 1.1 instead of the default openssl that brew is installing these days.

**Comment by native-api** [comment]
I'm opening a discussion why people keep using non-last EOL micro releases without downstream patches -- because I don't quite understand,
[Backport downstream patches for EOL versions to non-last releases? · pyenv · Discussion #3299](https://github.com/orgs/pyenv/discussions/3299)
