### ISSUE TITLE
Not building fcntl module when using pyenv install

### ISSUE THREAD

**Issue by wellrats** [pyenv/pyenv#1986]
When using pyenv install, module fcntl is not been build.
When using build from source it works perfectly.

Tested with pyenv 3.8.9 and 3.9.5 both works out of pyenv but do not work with pyenv.

hostname = linwell1
uname -m = x86_64
uname -r = 5.8.0-55-generic
uname -s = Linux
uname -v = #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
pyenv 2.0.1-5-gbbcecc75

Looking at logs seems that pyconfig.h for any reason is writing when some .h files are not found.
#define HAVE_STROPTS_H 1
and this define is preventing fcntl to be build.

[config.log](https://github.com/pyenv/pyenv/files/6656324/config.log)

[python-build.20210615141435.518951.log](https://github.com/pyenv/pyenv/files/6657503/python-build.20210615141435.518951.log)

**Comment by wellrats** [comment]
As a workaround its possible to edit pyconfig.h and change
```
#define HAVE_STROPTS_H 1
```
to
```
#undef HAVE_STROPTS
```

then execute
```
make -j 8
make install
```

But i think its not the correct way this may occurs.
Thanks

**Comment by native-api** [comment]
WFM.
Looks like a broken complier setup/incorrect compiler envvars passed to the build.

Why aren't those values defined if `<stropts.h>` is being included?

**Comment by wellrats** [comment]
There was a stropts.h in /usr/include with no content.
File removed.
pyenv install sucessfully done with fcntl.
Sorry guys, closing the case.
