### ISSUE TITLE
Initialization broken for xonsh shell

### ISSUE THREAD

**Issue by paugier** [pyenv/pyenv#1989]
I used to initialize pyenv with `xontrib load pyenv`.

Commit 5998f4f7ab12fc0781015ccc0e21ac0978b6c7f4 breaks pyenv initialization for xonsh.

After this commit, `PATH` does not contain `.pyenv/shims` so nothing works.

**Comment by native-api** [comment]
I have no idea what `xontrib load pyenv` does, so can't say anything about the immediate cause.

My guess is it's some custom 3rd-party logic that needs to be updated to conform to Pyenv 2.0's initialization logic, just like OhMyZsh.

**Comment by paugier** [comment]
Thanks for the explanation and sorry for the noise. I just needed to update https://pypi.org/project/xontrib-pyenv with `xpip install xontrib-pyenv -U`.
