### ISSUE TITLE
The terminal process bash terminated with exit code: 1.

### ISSUE THREAD

**Issue by sabotagebeats** [pyenv/pyenv#1994]
Using these instructions to add to my .profile and my .bashrc, I now get the following error when exiting my terminal on Ubuntu 20.04 LTS, WSL2 Windows 10

 `The terminal process bash terminated with exit code: 1.`
https://github.com/pyenv/pyenv/issues/1906#issuecomment-835027647_

**Comment by sabotagebeats** [comment]
also tried the other instructions produced in the warning and get the same issue.

**Comment by native-api** [comment]
Pyenv has no code that executes at terminal exit. The issue must be with some other code.
Set `PS4` according to https://wiki-dev.bash-hackers.org/scripting/debuggingtips#making_xtrace_more_useful, enable tracing and reproduce the issue -- this should tell you what is happening.

**Comment by sabotagebeats** [comment]
@native-api I don't see the error until I add the code for pyenv to the `.profile` and `.bashrc`

I will try again by adding the PS4 code, but the problem is happening on exit so it may not help.

**Comment by native-api** [comment]
> the problem is happening on exit so it may not help.

You need to see the trace output of the exit procedure -- so configure your terminal to not close on shell exit or something.

**Comment by sabotagebeats** [comment]
I'm no longer having this issue. It seems to have resolved itself.

**Comment by sabotagebeats** [comment]
I see that the issue still continues after running pyenv in the terminal

**Comment by native-api** [comment]
Without a means to reproduce the issue or at least a debug trace of the problem as explained in https://github.com/pyenv/pyenv/issues/1994#issuecomment-870484082, there's not much we can do.
