### ISSUE TITLE
Shim execution hangs after home directory is moved and linked or bind-mounted

### ISSUE THREAD

**Issue by sirosen** [pyenv/pyenv#1995]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
* [x] Make sure your problem is not derived from plugins.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 20.04
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 2.0.2

(other description fields N/A)

---

I recently had to relocate my homedir to accommodate other tools ([`snapd` not supporting non-`/home/` locations](https://bugs.launchpad.net/snappy/+bug/1620771), if you must know).
I decided to bind mount my old home, `/mnt/blahblahblah/sirosen/`, to my new one, `/home/sirosen/`, to try to minimize the impact.

When this was done, all of the shims were left pointing at the old home location.

I think it's fine that things didn't work. And once the problem was clear, `pyenv rehash` fixed it all.
However, the pyenv behavior in this scenario was surprisingly bad: shims hang with no output.

If a user moves their homedir and then runs a shim, I believe it would be best for `pyenv` to detect the situation and emit an error telling the user to `rehash`.

Would it be acceptable for pyenv to check if `$PYENV_ROOT` is not a descendant of `$HOME` and warn in this scenario? e.g. Add a warning plus an env var to disable it like `PYENV_ROOT_HOME_WARNING=0`?

---

To reproduce, you can just create a symlink to your home and break a shim by forcing it to use that link.
e.g. `mkdir /tmp/fakehome; ln -s $HOME /tmp/fakehome/me` and edit `~/.pyenv/shims/python3.9`. After such a change, `python3.9` will hang.

If that's not sufficient for others to reproduce (it works for me), please let me know and I'll try to work out what's different for my machine.

**Comment by native-api** [comment]
I don't think we can do any special intelligent handling of such arbitrary situations. There's the `PYENV_DEBUG` envvar if you need to see what's happening behind the scenes when you have a problem -- it's already a huge and usually sufficient aid for any troubleshooting you may need.

> Would it be acceptable for pyenv to check if `$PYENV_ROOT` is not a descendant of `$HOME` and warn in this scenario?

No. `PYENV_HOME` is not required to be anywhere in particular.
