### ISSUE TITLE
Fail to install Python using pyenv

### ISSUE THREAD

**Issue by mingyc** [pyenv/pyenv#200]
I've tried installing 2.7.6 & 2.7.5 but both of them failed. 
Logs:

```
 Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-5.2.zip
  Traceback (most recent call last):
    File "/tmp/python-build.20140625171233.29656/ez_setup.py", line 332, in <module>
      sys.exit(main())
    File "/tmp/python-build.20140625171233.29656/ez_setup.py", line 327, in main
      downloader_factory=options.downloader_factory,
    File "/tmp/python-build.20140625171233.29656/ez_setup.py", line 287, in download_setuptools
      downloader(url, saveto)
    File "/tmp/python-build.20140625171233.29656/ez_setup.py", line 224, in download_file_wget
      _clean_check(cmd, target)
    File "/tmp/python-build.20140625171233.29656/ez_setup.py", line 169, in _clean_check
      subprocess.check_call(cmd)
    File "/home/user/.pyenv/versions/2.7.6/lib/python2.7/subprocess.py", line 540, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['wget', 'https://pypi.python.org/packages/source/s/setuptools/setuptools-5.2.zip', '--quiet', '--output-document', '/tmp/python-build.      20140625171233.29656/Python-2.7.6/setuptools-5.2.zip']' returned non-zero exit status 1
```

**Comment by jgomo3** [comment]
I also have this issue. Including setting the `--insecure` option. Is there a log file for **pyenv**.

This is what happens:

    $ export EZ_SETUP_OPTS="--insecure"
    $ pyenv install 3.4.1
    Downloading Python-3.4.1.tgz...
    -> https://www.python.org/ftp/python/3.4.1/Python-3.4.1.tgz
    error: failed to download Python-3.4.1.tgz

My `curl` and `wget` versions:

**curl**

    $ command -v curl && curl --version
    /home/jgomez/.pyenv/shims/curl
    curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
    Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
    Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

**wget**

    $     command -v wget && wget --version
    /usr/bin/wget
    GNU Wget 1.15 built on linux-gnu.
    
    +digest +https +ipv6 +iri +large-file +nls +ntlm +opie +ssl/openssl 
    
    Wgetrc: 
        /etc/wgetrc (system)
    Locale: 
        /usr/share/locale 
    Compile: 
        gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/etc/wgetrc" 
        -DLOCALEDIR="/usr/share/locale" -I. -I../../src -I../lib 
        -I../../lib -D_FORTIFY_SOURCE=2 -I/usr/include -g -O2 
        -fstack-protector --param=ssp-buffer-size=4 -Wformat 
        -Werror=format-security -DNO_SSLv2 -D_FILE_OFFSET_BITS=64 -g -Wall 
    Link: 
        gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat 
        -Werror=format-security -DNO_SSLv2 -D_FILE_OFFSET_BITS=64 -g -Wall 
        -Wl,-Bsymbolic-functions -Wl,-z,relro -L/usr/lib -lssl -lcrypto 
        -ldl -lz -lidn -luuid ftp-opie.o openssl.o http-ntlm.o 
        ../lib/libgnu.a 
    
    Copyright (C) 2011 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later
    <http://www.gnu.org/licenses/gpl.html>.
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    
    Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
    Please send bug reports and questions to <bug-wget@gnu.org>.

**Comment by ricardoamaro** [comment]
I think the the issue remains on IPV6 connection to https://www.python.org throwing an error:
```
$ curl -v https://www.python.org
* Rebuilt URL to: https://www.python.org/
*   Trying 2a04:4e42:600::223...
* Connected to www.python.org (2a04:4e42:600::223) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 707 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: Error in the pull function.
* Closing connection 0
curl: (35) gnutls_handshake() failed: Error in the pull function.
```

While IPV4 Seems to works fine
```
 curl -v https://www.python.org | head -n 40
* Rebuilt URL to: https://www.python.org/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 151.101.0.223...
* Connected to www.python.org (151.101.0.223) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 702 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: www.python.org (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: 
* 	 start date: Wed, 29 Jun 2016 00:00:00 GMT
* 	 expire date: Thu, 27 Sep 2018 12:00:00 GMT
* 	 issuer: C=US,O=DigiCert Inc,OU=www.digicert.com,CN=DigiCert SHA2 Extended Validation Server CA
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
```

Could this be a fastly issue?
``` 
$ dig +short www.python.org
python.map.fastly.net.
```

**Comment by ricardoamaro** [comment]
Workaround was to pick one of fastly frontends and add it to /etc/hosts:
```
$ dig +short  www.python.org
python.map.fastly.net.
151.101.0.223
151.101.64.223
151.101.128.223
151.101.192.223
```
```
$ echo "151.101.0.223 www.python.org" >> /etc/hosts
```
```
$ pyenv install -v 2.7.12
/tmp/python-build.20170424122948.29712 ~/
Downloading Python-2.7.12.tar.xz...
-> https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tar.xz
/tmp/python-build.20170424122948.29712/Python-2.7.12 /tmp/python-build.20170424122948.29712 ~/repos/ops-runbook-fields
Installing Python-2.7.12...
```
