### ISSUE TITLE
`pyenv shell --unset` should be a primary command. Maybe `pyenv unset`?

### ISSUE THREAD

**Issue by rogerdahl** [pyenv/pyenv#2002]
And thank you for `pyenv` -- it's awesome.

**Comment by native-api** [comment]
There's also `pyenv local --unset` -- what about it?

**Comment by rogerdahl** [comment]
I thought it would temporarily uninstall pyenv, allowing regular virtualenvs to be activated, but that's apparently not the case. Sorry, closing this one.

**Comment by native-api** [comment]
You can activate regular virtualenvs with Pyenv just fine.
