### ISSUE TITLE
Strange Issue with python 3.9.x builds on Mac OS 12.0 (Monterrey)

### ISSUE THREAD

**Issue by ScottGuthart** [pyenv/pyenv#2004]
### Description
- [x] Platform information: M1 Mac on MacOS 12.0 (Monterrey)
- [x] OS architecture: arm64
- [x] pyenv version: 2.0.3
- [x] Python version: 3.9.6, 3.9.5, 3.91 tested
- [x] C Compiler information: 13.0.0
```shell
▶ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.18.6)
Target: arm64-apple-darwin21.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bi
```
- [x] [Verbose build log](https://gist.github.com/ScottGuthart/028b49319f9c09acf389f9a38cea368d)

---

On MacOS 12.0 (Monterrey) I'm able to build python 3.9.1, 3.9.5, and 3.9.6 successfully but when I create a virtual environment I receive the below error.

```shell
python -m venv venv
Error: Command '['/Users/scott/workspace/misc/venv/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

I think something is wrong with my python installation but I'm not sure what. I've tried creating the virtual environment using `python -m venv --without-pip venv` which succeeds along with using pyenv-virtualenv but then when I install jupyter and try to run code in a jupyter notebook I receive this message.

```shell
Traceback (most recent call last):
  File "/Users/scott/.pyenv/versions/3.9.1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/scott/.pyenv/versions/3.9.1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/scott/.pyenv/versions/3.9.1/lib/python3.9/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/Users/scott/.pyenv/versions/3.9.1/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 17, in <module>
    from tornado import ioloop
  File "/Users/scott/.pyenv/versions/3.9.1/lib/python3.9/site-packages/tornado/ioloop.py", line 38, in <module>
    import numbers
  File "/Users/scott/workspace/misc/numbers.py", line 4, in <module>
    first_number = float(sys.argv[1])
ValueError: could not convert string to float: '-f'
```

However, this does work in the terminal

```shell
(venv)
~/workspace/misc
▶ python
Python 3.9.1 (default, Jul  8 2021, 21:08:47)
[Clang 13.0.0 (clang-1300.0.18.6)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 5 + 56
61
```

**It's also worth mentioning, that I initially I had no problems creating virtual environments and using Jupyter. This issue seemed to start right after installing 3.9.6. Now, even if I try to use 3.9.5, 3.9.1 or reinstall pyenv I still encounter the same problem. However, if I activate a virtual environment that I created before I started experiencing this issue, I have no problems.**

---

Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

**Comment by native-api** [comment]
Run this command under PDB and follow the usual troubleshooting procedure
( 1) Identify the exact place in the code where the problem manifests itself; 2) inspect the state of the program at that point to find out which of the values is wrong; 3) track the wrong value back to its origin.).

**Comment by native-api** [comment]
Actually.. this is the reason:

```
File "/Users/scott/.pyenv/versions/3.9.1/lib/python3.9/site-packages/tornado/ioloop.py", line 38, in <module>
    import numbers
  File "/Users/scott/workspace/misc/numbers.py", line 4, in <module>
    first_number = float(sys.argv[1])
```

Your local module name, `numbers`, clashes with some library module that `ioloop` uses.
