### ISSUE TITLE
python-build overwrites some MAKE_OPTS given as environment variable (CFLAGS_EXTRA) for micropython

### ISSUE THREAD

**Issue by yggdr** [pyenv/pyenv#2006]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04):
FreeBSD 13.0-p5
- [x] OS architecture (e.g. amd64):
amd64
- [x] pyenv version:
2.0.3
- [x] Python version:
micropython (all)
- [x] C Compiler information (e.g. gcc 7.3): 
gcc 10.3.0
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

Due to an [issue with compiling micropython > 1.12 on FreeBSD](https://github.com/micropython/micropython/issues/7525) with `asdf` (which uses `pyenv`/`python-build` under the hood), I needed to give `make` an additional `CFLAGS_EXTRA` argument, like so:
`env MAKE=gmake MAKE_OPTS="CFLAGS_EXTRA=-Wno-float-conversion V=1" MAKE_INSTALL_OPTS="CFLAGS_EXTRA=-Wno-float-conversion V=1" ./python-build micropython-1.13 /tmp/TESTPY`
That however doesn't work, because line 893 overwrites `CFLAGS_EXTRA` again:
`"$MAKE" $MAKE_OPTS CFLAGS_EXTRA="-DMICROPY_PY_SYS_PATH_DEFAULT='\"${PREFIX_PATH}/lib/micropython\"'"`
After changing that to `CFLAGS_EXTRA+=[…]`, it works, and according to the logs, merges both my `CFLAGS_EXTRA` and the one explicitly given on this line.
Would a PR for this change be accepted, or am I overlooking something?

**Comment by native-api** [comment]
> Would a PR for this change be accepted, or am I overlooking something?

I don't see a problem. If a Python flavor's build consider an envvar user-providable, we should honor whatever the user provides whenever possible.
I reckon that it's just that `CFLAGS_EXTRA` is rarely used (neither CPython nor compilers use it to my knowledge) so this must've evaded attention.

It'd also help much is you added a test to check for honoring of this specific envvar specifically in Micropython's case.

**Comment by dpgeorge** [comment]
`CFLAGS_EXTRA` is the recommended way for a user to provide additional compiler options (also `LDFLAGS_EXTRA`).

**Comment by yggdr** [comment]
I have opened a PR #2007 for this issue. I couldn't get the test to work right. Could you have a look what I'm doing wrong? I used `stub` to mock `make` to simply output the `CFLAGS_EXTRA` variable, but currently, of the 4 `make` invocations in the tested function, only the first one actually does that. Looking at the `stub` function didn't give me any hints as to why only the first invocation works. I added some `echo`s to make it more clear:

```
bats compiler2.bats
 ✗ passthrough CFLAGS_EXTRA to micropython compiler
   (from function `assert_equal' in file test_helper.bash, line 115,
    from function `assert_output' in file test_helper.bash, line 124,
    in test file compiler2.bats, line 28)
     `assert_output <<OUT' failed
   expected: CFLAGS_EXTRA=-Wno-floating-conversion
   CFLAGS_EXTRA=-Wno-floating-conversion
   CFLAGS_EXTRA=-Wno-floating-conversion -DMICROPY_PY_SYS_PATH_DEFAULT='\"/lib/micropython\"'
   actual:   MPY MAKE
   CFLAGS_EXTRA=-Wno-floating-conversion
   UNIX MAKE AXTLS
   UNIX MAKE
   UNIX MAKE INSTALL
   END
```

**Comment by native-api** [comment]
> Could you have a look what I'm doing wrong?

Done.
