### ISSUE TITLE
UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError

### ISSUE THREAD

**Issue by lorenzoyeung** [pyenv/pyenv#2008]
I am using M1 Mac, would you please explain how to fix this? I am having this issue. I installed python 3.9.4 with pyenv, and now running pandas in VScode, then this error comes up.

"/Users/yeung/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pandas/compat/init.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
warnings.warn(msg)"

Mac M1, and my python environment is as below:

- I installed Rosetta 2, and set my i386Terminal as Rosetta 2 ( I duplicated my Terminal, one is set to use  i386, another is set to use arm64)
- I installed pyenv with brew
- installed python 3.9.4 with pyenv (set as global)
- installed visual studio code with brew
- and finally I installed pandas with "pip install pandas" in my arm64 Terminal.

 ~ python --version
Python 3.9.4
~ pyenv --version
pyenv 2.0.3-2-g84a65357

**Comment by native-api** [comment]
What's unclear in https://github.com/pyenv/pyenv/issues/1800#issuecomment-772177116 ?

**Comment by native-api** [comment]
Duplicate of #1800

**Comment by ThibaultEbroussard** [comment]
Same issue with 3.9.6 version from pyenv (global) on Ubuntu 20.04

**Comment by HenrryVargas** [comment]
Hi

This works for me:
https://www.programmerclick.com/article/3650407895/
