### ISSUE TITLE
pyenv unable to find python packages

### ISSUE THREAD

**Issue by zorzigio** [pyenv/pyenv#2009]
I have been using pyenv and I really like it (thanks!)

I have now been using it with poetry, and it doesn't seem to find python packages anymore. (I am not sure that this is related to the use with poetry, however I am adding this info for completeness)

For instance I can run 

```bash
>pyenv which pytest
/home/gz/.pyenv/versions/test/bin/pytest
```

however if I run 

```bash
>pytest            
zsh: command not found: pytest
```

### System Description

```bash
>lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute
```

```bash
>uname -m
x86_64
```

```bash
>pyenv --version    
pyenv 2.0.0
```

```bash
>python --version  
Python 3.9.5
```

```bash
>gcc --version
gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by jrial** [comment]
I'm seeing a similar issue since I updated my pyenv to 2.0.3-2-g84a65357:

```bash
[14:16] nighty@saltmine ~$ pyenv which ipython
/home/nighty/.pyenv/versions/3.8.0/bin/ipython
[14:16] nighty@saltmine ~$ which ipython
[14:16] nighty@saltmine ~$ ipython

Command 'ipython' not found, did you mean:

  command 'ipython3' from deb ipython3 (7.13.0-1)
  command 'bpython' from deb bpython (0.18-3)

Try: sudo apt install <deb name>
```

Seems the issue is that `~/.pyenv/shims` is no longer prepended to the `PATH`:

```bash
[14:16] nighty@saltmine ~$ echo $PATH
/home/nighty/.pyenv/plugins/pyenv-virtualenv/shims:/home/nighty/.pyenv/bin:/home/nighty/.nvm/versions/node/v8.12.0/bin:/home/nighty/perl5/bin:/home/nighty/bin:/home/nighty/opt/pebble-sdk/bin:/opt/GitHub Desktop:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

If I manually prepend it, everything works fine:
```bash
[14:20] nighty@saltmine ~$ export PATH=~/.pyenv/shims:$PATH
[14:20] nighty@saltmine ~$ echo $PATH
/home/nighty/.pyenv/shims:/home/nighty/.pyenv/plugins/pyenv-virtualenv/shims:/home/nighty/.pyenv/bin:/home/nighty/.nvm/versions/node/v8.12.0/bin:/home/nighty/perl5/bin:/home/nighty/bin:/home/nighty/opt/pebble-sdk/bin:/opt/GitHub Desktop:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[14:20] nighty@saltmine ~$ which ipython
/home/nighty/.pyenv/shims/ipython
[14:20] nighty@saltmine ~$ ipython
Python 3.8.0 (default, Oct 28 2019, 15:39:07) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.7.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]:  
```

Since this is the same system it always used to work on, my guess is there's an issue in the latest release that results in the `~/.pyenv/shims` path not being prepended. The commands responsible for this are in your `.bashrc` (or whatever your shell's equivalent is), and in my case look like this:

```bash
# PyEnv
export PATH="/home/nighty/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

The second eval prepends the pyenv-virtualenv shims, and my guess is the first should prepend the pyenv shims, but somehow this got broken in the latest update.

**Comment by native-api** [comment]
You need to add `eval "$(pyenv init --path)"` to you login shell's initialization file as per the README. This is new since 2.0.

**Comment by zorzigio** [comment]
I was using Oh-My-Zsh and the zsh-pyenv plugin. It was working fine until today.
Removing the plugin and following the steps in the installation steps got pyenv running again

Thanks for the support!

**Comment by jrial** [comment]
Note for future users: there's no need to uninstall and reinstall; you just need to change the `pyenv init` line to add the `--path` parameter. After a logout/login cycle, everything will work again.

**Comment by zorzigio** [comment]
or for Oh-My-Zsh users using the `zsh-pyenv` plugin, remove the plugin and follow the configuration steps in the README.md

(BTW, I didn't mean that I had to re-install `pyenv`, but that I had to follow the instructions on the installation guide to setup `pyenv` since the plugin was not taking care of this anymore)
