### ISSUE TITLE
Checksums for Python 3.10.0rc1 are wrong.

### ISSUE THREAD

**Issue by hiwixxl** [pyenv/pyenv#2024]
sha256sum Python-3.10.0rc1.tar.xz is '797061692282d0e573a0093476e57e39cf52cad56782ab2dfb79afadb3c1e638'
sha256sum Python-3.10.0rc1.tgz  is 'b7efa6edd72bfeae57295f1ccc7c38c9ede8087f9f082382f16f92aa38f684d3''

**Comment by native-api** [comment]
@fredrikaverpil , could you check? Where do the checksums in your PR come from?

**Comment by fredrikaverpil** [comment]
I just opened a PR to fix this.
