### ISSUE TITLE
Pyenv not being added to PATH in WSL if Pyenv-Win is on PATH

### ISSUE THREAD

**Issue by bbulkow** [pyenv/pyenv#2026]
### pyenv mysteriously not working on WSL after Win11 upgrade

I've been using Pyenv happily with WSL and WIN11 forever. Feels like forever. Years. I prefer WSL1 because it is 10x faster for what I use (long story), and I'm still on Ubuntu 18.04 for my WLS1 shell.

I install via the basic "pull and bash" mechanism. I do a clone of the git repo into the usual location in the home directory, execute the path elements to point there, then pyenv init, in my .bash_alises , which has always worked before.

Right around when I upgraded to Windows 11 - probably two weeks ago, when Win11 came through the beta channel (not alpha), I noticed my python version was python2 instead of python3.

Digging in, I see that pyenv is installed properly, still, but when I 'which python' I get '/usr/bin/python', even though I have exec'd the init so the shims should be installed. Either the shims are not getting installed or they are getting removed or overridden?

I've checked every obvious thing I can find, and it just seems like the shims don't install. I've also tried going to a fresh WSL2 install on U20.04. I've looked at the path --- virtualenv was in front, and I removed that. 

If I had to guess, I would assume there's some dependancy on the uname, which probably changed. The current one is:
`Linux SUPERFLY 4.4.0-22000-Microsoft #1-Microsoft Fri Jun 04 16:28:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux`

I've looked through the various scripts that should install the shims and just don't see anything.

Halp? Next places to look?

### Description
- WSL1 Ubuntu 18.04 on Windows 11 preview (beta channel, not alpha)
- OS Architecture - AMD64
- Pyenv version:  2.0.4-5-gab1a9d29
- Python version: all
- GCC 10 (Ubuntu 10.3.0-1ubuntu1~18.04~1)

**Comment by native-api** [comment]
Looks like shims are not on PATH.

If you've upgraded to Pyenv 2 from an earlier version -- did you add `eval "$(pyenv init --path)"` to the session's login shell's configuration as per the README?

**Comment by native-api** [comment]
@distobj You need to not change `-` to `--path` but rather add a `--path` line to login shell's configuration (while the `-` line should be in interactive shell's configuration).

If you rather replace it, you'll lose the shell function and all its benefits (completion and some subcommands).

**Comment by bbulkow** [comment]
Changing to --path worked. Adding --path worked. Closing.

What changed? I don't know. The install doc could use a little more commentary on - vs --path (appears to control whether the path is added, necessary when the init is sourced, which seems to be happening maybe in different distros?)

**Comment by TristynAlxander** [comment]
@native-api, I may not be reading it correctly, but your comment makes it seem like you don't need to set your shims in non-login shells, and I do not think that is correct. I agree that you need to run both `eval "$(pyenv init --path)"`  and `eval "$(pyenv init -)"` to add both shims and convince features, per the [Advanced Configuration](https://github.com/pyenv/pyenv#advanced-configuration), but I think you need to run them both or add the shims manually:

    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"

Alternatively, 

    export PATH="$PYENV_ROOT/shims:$PATH" 
    eval "$(pyenv init -)"

Of course there are exceptions depending on your shell. Typical systems have two start-up files: `.profile` and something like `.bashrc`, `.tcshrc`, or `.zshrc`. In bash, these do not run at the same time. This is a quirk of bash. Most shells have the `.profile` that runs on login (e.g. `ssh` requires a password) and the `.__shrc` that runs on interactive (i.e. you see the terminal). Thus, you'd expect on a interactive login shell (almost all login shells) that both would run. In bash, this does not happen. `.bashrc` does not run on login shells. Many people using bash set up their `.profile` to run `.bashrc` so as to correct this quirk. 

In that context it makes sense that you'd only want to run `eval "$(pyenv init -)"` when you are setting up interactive shells since it sets up convince features, but you'll want to add the shims to your path regardless of everything else. You should probably be careful not to add your shims to your path twice but avoiding that depends on both shell and personal configuration (i.e. if your `.profile` runs `.__shrc`).

**Comment by native-api** [comment]
> you don't need to set your shims in non-login shells

A non-login shell is always a descendant of a login shell. So if you set up the PATH in the session's login shell, you don't need to do it again in non-login ones.

**Comment by andersrmr** [comment]
i recently installed WSL in windows 11 and appear to be having a related problem.  I'm trying to run vscode on top of WSL.  My `.profile` and `.bashrc` are as follows:
```
export PYENV_ROOT="$HOME/git/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
```
but i'm getting an error, repeating multiple times, as you can see:

```
/mnt/c/Users/myusername/.pyenv/pyenv-win/bin/pyenv: 3: cygpath: Permission denied
/mnt/c/Users/myusername/.pyenv/pyenv-win/bin/pyenv: 3: exec: cmd: Permission denied
/mnt/c/Users/myusername/.pyenv/pyenv-win/bin/pyenv: 3: cygpath: Permission denied
/mnt/c/Users/myusername/.pyenv/pyenv-win/bin/pyenv: 3: exec: cmd: Permission denied
```
Anyone know how to fix this?  Separately, I have it working on the windows side with `pyenv-win`.  Ultimately, I'd like to be able to use vs-code with my chosen version of python..

It's not clear to me that the PATH is being updated correctly.  vscode and windows system environmental variables precede by user variables on PATH.

**Comment by native-api** [comment]
@andersrmr Not relevant to Pyenv. We do not use `cygpath`.

**Comment by antoine-lombardo** [comment]
> w how to fix this? Separately, I have it working on the windows side with `pyenv-win`. Ultimately, I'd like to be able to use vs-code with my chosen version of python..
> 
> It's not clear to me that the PATH is being updated correctly. vscode and windows system environmental variables precede my user variables o

I am getting the same error

**Comment by looeee** [comment]
For anyone else having this issue because pyenv-win is installed, see [the comment here](https://github.com/pyenv-win/pyenv-win/issues/469#issuecomment-1913364051):

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH" # instead of `command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"`
eval "$(pyenv init -)"
```

You may also need to change the last line to:

```
eval "$(pyenv init - --path)"
```

**Comment by native-api** [comment]
Perhaps we can adjust the initialization code to work in the same when Pyenv-win is on PATH.
Then we need to figure out how to detect that.

---

Alternatively -- and perhaps preferrably -- why does it even end up on PATH is WSL? I'm not familiar with WSL. AFAIK it's an Ubuntu VM with the host FS visible as a mount.

Why even add something from the host FS to PATH? Windows executables cannot run in the VM, can they?

**Comment by Brandontam29** [comment]
You can run window commands like `explorer.exe .` in your wsl terminal because Window commands are mounted in `/mnt/Users/`

> Why even add something from the host FS to PATH? Windows executables cannot run in the VM, can they? So what's the point?

**Comment by theangkko** [comment]
> For anyone else having this issue because pyenv-win is installed, see [the comment here](https://github.com/pyenv-win/pyenv-win/issues/469#issuecomment-1913364051):
> 
> ```
> export PYENV_ROOT="$HOME/.pyenv"
> export PATH="$PYENV_ROOT/bin:$PATH" # instead of `command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"`
> eval "$(pyenv init -)"
> ```
> 
> You may also need to change the last line to:
> 
> ```
> eval "$(pyenv init - --path)"
> ```

-----------------------------------

With above reply, I cannot resolve my issue that is same with you ( pyenv-win in Window,  pyenv in WSL2)

but refer to the article,   https://stackoverflow.com/a/76483889/14103688
I succeed below commands


export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH=""$PYENV_ROOT/bin:$PATH"

BIN_OLD="/mnt/c/Users/<username>/.pyenv/pyenv-win/bin"
BIN_NEW="$PYENV_ROOT/bin"
SHIMS_OLD="/mnt/c/Users/<username>/.pyenv/pyenv-win/shims"
SHIMS_NEW="$PYENV_ROOT/shims"
export PATH=`echo $PATH | sed "s@$BIN_OLD@$BIN_NEW@" | sed "s@$SHIMS_OLD@$SHIMS_NEW@"`
eval "$(pyenv init -)"

**Comment by native-api** [comment]
Some time ago, I've updated the suggested text for shell configuration files given by `pyenv init` to:
```
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```

This should work in this case.

**Comment by KyrieChen** [comment]
> Some time ago, I've updated the suggested text for shell configuration files given by `pyenv init` to:
> 
> ```
> export PYENV_ROOT="$HOME/.pyenv"
> [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
> eval "$(pyenv init -)"
> ```
> 
> This should work in this case.

it work for me!!!thanks.
