### ISSUE TITLE
LIBDIR incorrect with `--install-framework=/path` on MacOS

### ISSUE THREAD

**Issue by n8henrie** [pyenv/pyenv#2038]
### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS 11.5
- [x] OS architecture (e.g. amd64): ARM64
- [x] pyenv version: 2.0.4
- [x] Python version: multiple
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 12.0.5 (clang-1205.0.22.11)
- [x] Please attach verbose build log as gist: https://gist.github.com/n8henrie/336698284dec3468f75d5aeaed5a6b89

Please see also: https://github.com/PyO3/pyo3/issues/1800#issuecomment-902539210

On MacOS, my usual "install via pyenv" invocation employs `--install-framework=DIR`, so that I can take advantage of a framework install [without clobbering other framework directories](https://github.com/pyenv/pyenv/issues/55#issuecomment-23638979). It usually looks something like this, which is the command I used for the gist above:

```
$ CONFIGURE_OPTS="--enable-framework=$(pyenv root)/versions/3.9.3" \
CFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix libffi)/include -I/opt/homebrew/opt/readline/include" \
LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix libffi)/lib -L/opt/homebrew/opt/readline/lib" \
pyenv install -v 3.9.3
```

It generally works well, but I recently started using [PyO3](github.com/PyO3/pyo3) and [maturin](github.com/PyO3/maturin) and found that I was getting errors using pyenv pythons that worked fine with homebrew.

After [some digging](https://github.com/PyO3/pyo3/issues/1800) and generous efforts by @davidhewitt, it looks like pyenv may not be setting the correct `LIBDIR` in the case of these framework installs, which looks like the source of the issue.

For example, I have 3.9.[3-6] installed via pyenv, with .3, .5, and .6 being framework installs (and .4 non-framework, just for comparison). As you can see, all 4 have their LIBDIR set to the same directory, but 3.9.4 seems to be the only one that actually has a `libpython3.9` in that directory:

```console
$ pyenv versions | grep 3\.9
  3.9.3
  3.9.4
* 3.9.5 (set by /Users/n8henrie/git/pycookiecheat/.python-version)
  3.9.6
$ find ~/.pyenv -path '*/3.9.*/Python.framework'
/Users/n8henrie/.pyenv/versions/3.9.6/Python.framework
/Users/n8henrie/.pyenv/versions/3.9.5/Python.framework
/Users/n8henrie/.pyenv/versions/3.9.3/Python.framework
$ for py in ~/.pyenv/versions/3.9.*/bin/python; do "$py" -m sysconfig | grep '\bLIBDIR\b'; done
        LIBDIR = "/Users/n8henrie/.pyenv/versions/3.9.3/lib"
        LIBDIR = "/Users/n8henrie/.pyenv/versions/3.9.4/lib"
        LIBDIR = "/Users/n8henrie/.pyenv/versions/3.9.5/lib"
        LIBDIR = "/Users/n8henrie/.pyenv/versions/3.9.6/lib"
$ for lib in ~/.pyenv/versions/3.9.*/lib; do printf "%s\n%s\n\n" "$lib" "$(ls "$lib")"; done
/Users/n8henrie/.pyenv/versions/3.9.3/lib
pkgconfig
python3.9

/Users/n8henrie/.pyenv/versions/3.9.4/lib
libpython3.9.a
pkgconfig
python3.9

/Users/n8henrie/.pyenv/versions/3.9.5/lib
pkgconfig
python3.9

/Users/n8henrie/.pyenv/versions/3.9.6/lib
pkgconfig
python3.9
$ find ~/.pyenv/versions -name 'libpython3.9*'
/Users/n8henrie/.pyenv/versions/3.9.6/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin/libpython3.9.dylib
/Users/n8henrie/.pyenv/versions/3.9.6/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin/libpython3.9.a
/Users/n8henrie/.pyenv/versions/3.9.6/Python.framework/Versions/3.9/lib/libpython3.9.dylib
/Users/n8henrie/.pyenv/versions/3.9.5/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin/libpython3.9.dylib
/Users/n8henrie/.pyenv/versions/3.9.5/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin/libpython3.9.a
/Users/n8henrie/.pyenv/versions/3.9.5/Python.framework/Versions/3.9/lib/libpython3.9.dylib
/Users/n8henrie/.pyenv/versions/3.9.3/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin/libpython3.9.dylib
/Users/n8henrie/.pyenv/versions/3.9.3/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin/libpython3.9.a
/Users/n8henrie/.pyenv/versions/3.9.3/Python.framework/Versions/3.9/lib/libpython3.9.dylib
/Users/n8henrie/.pyenv/versions/3.9.4/lib/python3.9/config-3.9-darwin/libpython3.9.a
/Users/n8henrie/.pyenv/versions/3.9.4/lib/libpython3.9.a
```

Is this something that pyenv should be doing differently, to allow tools like PyO3 to more readily locate libpython?

Thanks for your time!

**Comment by n8henrie** [comment]
Thanks for the work on https://github.com/pyenv/pyenv/pull/1935 -- unfortunately, on pyenv 2.0.7 on MacOS Big Sure, using `--enable-framework` without an argument, I am still getting:

```
Creating directory /Library/Frameworks/Python.framework/Versions/3.9/Resources/English.lproj
ginstall: cannot create directory ‘/Library/Frameworks/Python.framework’: Permission denied
Creating directory /Library/Frameworks/Python.framework/Versions/3.9/lib
ginstall: cannot create directory ‘/Library/Frameworks/Python.framework’: Permission denied
make: *** [Makefile:1716: frameworkinstallstructure] Error 1
```

**Comment by native-api** [comment]
I cannot say anything about that without seeing a debug trace as per the issue template.

**Comment by n8henrie** [comment]
Sorry, I didn't use the issue template because I was responding to your suggestion: `First, try to use --enable-framework without an argument`, not trying to create a new issue (yet, though perhaps I will if I can't sort out why that isn't working).

**Comment by n8henrie** [comment]
> First, try to use --enable-framework without an argument.

Resolved as per my edit above, thanks.

Let me test and see if the `LIBDIR` issue is resolved as well.

**Comment by native-api** [comment]
> Resolved by using `PYTHON_CONFIGURE_OPTS="--enable-framework"` instead of `CONFIGURE_OPTS="--enable-framework"`.

That's actually a valid bug: According to https://github.com/pyenv/pyenv/tree/master/plugins/python-build, both `CONFIGURE_OPTS` and `PYTHON_CONFIGURE_OPTS` should be honored. Could you report it separately?

**Comment by n8henrie** [comment]
Better yet, installing this way (`PYTHON_CONFIGURE_OPTS="--enable-framework"` instead of `CONFIGURE_OPTS="--enable-framework=$(pyenv root)/versions/3.9.5"`) resolves the original issue; my rust shared library now finds libpython without requiring any extra linker magic. Thanks for your help!

It seems that while `LIBDIR` is the same, `prefix` is different -- perhaps that's why?

```console
$ for py in ~/.pyenv/versions/3.9.?/bin/python; do
  "${py}" <<< 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"), sysconfig.get_config_var("prefix"), sep="\n")'
done
/Users/n8henrie/.pyenv/versions/3.9.5/lib
/Users/n8henrie/.pyenv/versions/3.9.5/Python.framework/Versions/3.9
/Users/n8henrie/.pyenv/versions/3.9.6/lib
/Users/n8henrie/.pyenv/versions/3.9.6/Library/Frameworks/Python.framework/Versions/3.9
```
