### ISSUE TITLE
Pyenv badly configured error message

### ISSUE THREAD

**Issue by varunagrawal** [pyenv/pyenv#2041]
I've been using Pyenv for over 2 years now and just recently started getting this error message:

```
Found pyenv, but it is badly configured. pyenv might not work for
non-interactive shells (for example, when run from a script).

To fix this message, add these lines to the '.profile' and '.zprofile' files
in your home directory:

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

You'll need to restart your user session for the changes to take effect.
For more info go to https://github.com/pyenv/pyenv/#installation.
```

My `~/.zshrc` file already has the above lines, and I also tried moving them to my `.zprofile` but this had no effect on the error message. I also tried re-installing. Can someone please explain what the issue may be?

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 20.04.2 LTS
- [X] OS architecture (e.g. amd64): amd64
- [X] pyenv version: 2.0.5
- [X] Python version: System version is 3.8.10
- [X] C Compiler information (e.g. gcc 7.3): clang version 10.0.0-4ubuntu1 
- [X] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

**Comment by santiagobasulto** [comment]
I silenced mine by setting the envvar `ZSH_PYENV_QUIET` to `true` ([source](https://github.com/ohmyzsh/ohmyzsh/blob/358ac6a141010b19175d0eb5a6f28ff544aa75d3/plugins/pyenv/pyenv.plugin.zsh#L2))

**Comment by varunagrawal** [comment]
I updated OMZ and the error has gone away. Thanks for the help!

**Comment by julianhille** [comment]
If someone finds this and still has no clue how to fix, i've found the mistake i made.

Pyenv initialization must happen before plugin loading of oh-my-zsh pyenv plugin. 
```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
....
....
plugins=(
    ...
    pyenv
    ....
)


```

**Comment by varunagrawal** [comment]
OMG I ran into this issue again and @julianhille's solution worked absolutely brilliantly!!

**Comment by abcnow** [comment]
I tried  @julianhille solution and it is not working any more.. not sure.. how to go around..now the prompt is telling me to update .zprofile and .profile.. 

#pyenv path
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

I added these lines to my .zprofile and .profile and it is not working..

**Comment by motorlearner** [comment]
Had the same problem as @abcnow. (I used brew to install pyenv). What solved it for me: make sure brew is included in the path **beforehand.** 

The plugin calls `pyenv root` [here](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/pyenv/pyenv.plugin.zsh#L68) to get the pyenv-path, then checks whether pyenv-path/shims is in your PATH---if it isn't, it will add it and display said warning. 

The problem: I could not call pyenv without brew in my PATH. Hence, this solved it for me:

```zsh
eval "$(/opt/homebrew/bin/brew shellenv)"
# and only then 
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```

**Comment by abcnow** [comment]
@motorlearner -> you are the man!! I added this line and it worked:
 eval "$(/opt/homebrew/bin/brew shellenv)" 
 
 ---
PS: coming from my bashprofile setup. I also double checked that homebrew was on my zshrc path. I also erased a few things I previously added on my zprofile as well.. all the errors disappeared after that
