### ISSUE TITLE
Incomplete installation doc when using with pyenv-virtualenv plugin ?

### ISSUE THREAD

**Issue by PierreRust** [pyenv/pyenv#2062]
When using pyenv-virtualenv with pyenv>2, the command ` pyenv activate <venv>` appears to work correctly (i.e. not error is reported) although the shims are not pointing to the venv's python and pip.

When running `pyenv init --path | source` it works fine, although the documentation only mention to run `pyenv init - | source`

This has been tested on ubuntu 20.04, pyenv 2.0.6-7 with fish shell, but it has also been reported with bash in pyenv/pyenv-virtualenv#401 

I'm reporting it here because, while the problem appears with a plugin, it seems to depend on a missing(?) instruction in the installation documentation.

**Comment by native-api** [comment]
I've made a PR with updated setup instructions based on user feedback so far. Please review: https://github.com/pyenv/pyenv/pull/2067
