### ISSUE TITLE
Apt unable to locate package llvm, tk-dev

### ISSUE THREAD

**Issue by fredrikaverpil** [pyenv/pyenv#2076]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information: Ubuntu Desktop 20.04.3 LTS Live USB
- [x] OS architecture: x86_64
- [x] Python version: 3.8.10 (pre-installed)
- [x] C Compiler information (e.g. gcc 7.3): not installed yet

I have previously installed pyenv's [suggested build environment](https://github.com/pyenv/pyenv/wiki#suggested-build-environment) successfully without any errors in Ubuntu 20. However, now I have a completely fresh Live USB that I am running Ubuntu off and in here I cannot install llvm or tk-dev, which are part of the example command in the wiki.

```bash
$ sudo apt-get update; sudo apt-get install make build-essential libssl-dev zlib1g-dev \
> libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
> libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
Ign:1 cdrom://Ubuntu 20.04.3 LTS _Focal Fossa_ - Release amd64 (20210819) focal InRelease
Hit:2 cdrom://Ubuntu 20.04.3 LTS _Focal Fossa_ - Release amd64 (20210819) focal Release
Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease                                         
Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease                                 
Hit:6 http://security.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package llvm
E: Unable to locate package tk-dev
```

When I search for llvm and tk-dev, I can't find them:

```bash
$ sudo apt-cache search llvm
libllvm10 - Modular compiler and toolchain technologies, runtime library
libllvm9 - Modular compiler and toolchain technologies, runtime library
libclang-11-dev - Clang library - Development package
libclang-common-11-dev - Clang library - Common development package
libclang-cpp11 - C++ interface to the Clang library
libclang-cpp11-dev - C++ interface to the Clang library
libclang1-11 - C interface to the Clang library
libllvm-11-ocaml-dev - Modular compiler and toolchain technologies, OCaml bindings
libllvm11 - Modular compiler and toolchain technologies, runtime library
libllvm12 - Modular compiler and toolchain technologies, runtime library

$ sudo apt-cache search tk-dev
libcheese-gtk-dev - tool to take pictures and videos from your webcam - widgets dev
libcolord-gtk-dev - GTK+ convenience library for interacting with colord - dev files
```

Does anyone have any idea on what has happened here?  
Did the packages get renamed or something?

**Comment by fredrikaverpil** [comment]
I've resorted to replacing llvm and tk-dev with llvm-13 and tk8.6-dev. Not sure if this is the right thing to do though. Any advice here would be greatly appreciated.

```bash
sudo apt-get update; sudo apt-get install make build-essential libssl-dev zlib1g-dev \
libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm-13 \
libncursesw5-dev xz-utils tk8.6-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
```

**Comment by fredrikaverpil** [comment]
So, I managed to find a workaround. But I'm not sure if there are issues with it. I'd be happy to hear what you think about it. This is what I did:

* Replaced llvm with llvm-13
* Replaced tk-dev with tk8.6-dev

```bash
sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

sudo apt-get install -y make build-essential libssl-dev zlib1g-dev \
    libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm-13 \
    libncursesw5-dev xz-utils tk8.6-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
```

Either way, to me it seem the wiki information is outdated.

**Comment by native-api** [comment]
`llvm` is present in the official Ubuntu repository: see https://packages.ubuntu.com/focal/llvm and http://archive.ubuntu.com/ubuntu/dists/focal/universe/binary-amd64/ .

Perhaps you're using a transparent caching proxy that is out of date, or your local metadata has incorrect dates or something.

**Comment by fredrikaverpil** [comment]
Thanks @native-api for your input!
This lead me to eventually realizing that the `universe` repository was not added in the live USB Ubuntu Desktop for some reason. After adding it, I can successfully install the packages.

```bash
sudo add-apt-repository universe
```
