### ISSUE TITLE
conda not working for miniconda virtualenvs

### ISSUE THREAD

**Issue by mayanksuman** [pyenv/pyenv#2077]
### Description
`pyenv` do not make correct shims for virtual environments based on `miniconda-latest`. The issue can be reproduced with following commands (please make sure that there is not `$HOME/.pyenv` directory in the begining):

```bash
curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
pyenv install -s miniconda3-latest
pyenv virtualenv miniconda3-latest jupyter
conda                                                         # produce error as conda is not found.
```

Interestingly, if we activate and then deactivate `miniconda3-latest` environment. `conda` any other shim from `miniconda3-latest` start to work.

- [ ] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 21.10
- [ ] OS architecture (e.g. amd64): amd64
- [ ] pyenv version: 2.0.7
- [ ] Python version: miniconda3-latest (3.9.7)
- [ ] C Compiler information (e.g. gcc 7.3): gcc 9.4.0

**Comment by native-api** [comment]
Pyenv-installer doesn't set up your shell environment for you (because they are environment-specific and because we've recently updated them and haven't had enough feedback from users yet to trust them to run unattended). Instead, it prints instructions how to do that after running.

**Comment by native-api** [comment]
We can add instructions on how to use Pyenv in a temporary environment if you install it yourself if that's relevant.

**Comment by mayanksuman** [comment]
> We can add instructions on how to use Pyenv in a temporary environment if you install it yourself if that's relevant.

Yes, that will be helpful.
