### ISSUE TITLE
pyenv local --unset does not walk the directory tree. pyenv-exec does.

### ISSUE THREAD

**Issue by 13steinj** [pyenv/pyenv#2079]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Debian 10
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 2.0.6 but relevant now
- [x] Python version: NA
- [x] C Compiler information (e.g. gcc 7.3): gcc 8.2.0
- [x] Please attach verbose build log as gist Can't
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

I found this bug in the process of writing a fork of pyenv for GCC/clang/binutils/etc. I looked for this issue, but could not find it (unless I searched for the wrong term).

`pyenv local --unset` attempts to delete the current working directory's .pyenv-version file, rather than the one found by walking up the directory tree. While possible understood behavior, it's not cleanly mentioned anywhere.

For the sake of backwards compatibility, I propose adding another option, say, `--unset-walk`, which does the job of unset but walks up the directory tree as necessary, and then outputs what version would be fallen back to now that local is unset. E.g.

shell --unset would just need to output the relevant version.
local --unset would need to output the relevant version under the assumption that CHAINENV_VERSION is unset.

I further propose that --unset warns against using it with no `.pyenv-version` existing in the current working directory.

**Comment by native-api** [comment]
What's the intended use case?

**Comment by 13steinj** [comment]
> What's the intended use case?

I mean it's quite simple-- in fact I'd argue it's a bug rather than an enhancement.

As of right now `pyenv local` sets a version for say, `/home/user/foo` and any subdirectories.

If you're in `/home/user/foo/bar` and end up, for whatever reason, needing to unset the chosen pyenv version, you just can't. Moreso, it doesn't even warn you that it wasn't unset/changed. You have to go up to the relevant directory and then run `pyenv local --unset`. This would be fine if there's a warning, but there's no feedback to tell the user that they messed up.

**Comment by native-api** [comment]
Silently walking up the directory tree and deleting whatever is first found is dangerous 'cuz it may not be what you intended to delete.
E.g. imagine you have `.pyenv-version` in `/home/user` and `/home/user/project` and you want to unset the project version. But if it's not (currently) set for this specific project, you'll delete the home entry instead!

> If you're in /home/user/foo/bar and end up, for whatever reason, needing to unset the chosen pyenv version, you just can't. 

So what you actually want is to be able to quickly see the location to the active `.pyenv-version`, or even of all of them, and then delete and/or edit some of them. Right?

> Moreso, it doesn't even warn you that it wasn't unset/changed.

And for `pyenv local --unset` to tell (on stderr) if nothing was done.

**Comment by 13steinj** [comment]
> So what you actually want is to be able to quickly see the location to the active `.pyenv-version`, or even of all of them, and then delete or edit some of them based on results. Right?

I believe this part is already possible via `pyenv version` and if so I'm okay here.

> And for `pyenv local --unset` to tell (on stderr) if nothing was done.

Yes, possibly suggesting `pyenv local --unset-walk` to unset, walking up the directory tree. This wouldn't be silent and need to be explicitly chosen instead of `--unset`

**Comment by native-api** [comment]
I explained in https://github.com/pyenv/pyenv/issues/2079#issuecomment-932819602 that the behavior as suggested is dangerous because the `.pyenv-version` may not be where you think it is.

I guess a switch to `pyenv local` that would specify the directory where to perform the operation (instead of the current directory) would do the job?
