### ISSUE TITLE
`--enabled-framework` behaves differently with `PYTHON_CONFIGURE_OPTS` vs `CONFIGURE_OPTS` 

### ISSUE THREAD

**Issue by n8henrie** [pyenv/pyenv#2081]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS Big Sur (11.6)
- [x] OS architecture (e.g. amd64): Arm64 (M1 / Apple Silicon)
- [x] pyenv version: 2.0.7
- [x] Python version: 3.9.6
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 13.0.0 (clang-1300.0.29.3)
- [x] Please attach verbose build log as gist: Below
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

Issue [recommended by @native-api](https://github.com/pyenv/pyenv/issues/2038#issuecomment-931528406)

I'm seeing different behavior with `CONFIGURE_OPTS="--enable-framework"` vs `PYTHON_CONFIGURE_OPTS="--enable-framework"`, where the former fails due to permissions issues (see also: https://github.com/pyenv/pyenv/pull/1935):

```console
$ CONFIGURE_OPTS="--enable-framework" \
    CPPFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix libffi)/include" \
    LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix libffi)/lib" \
    pyenv install -v 3.9.6
...
BUILD FAILED (OS X 11.6 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/python-build.20210930152413.20824
Results logged to /var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/python-build.20210930152413.20824.log

Last 10 log lines:
changing mode of build/scripts-3.9/idle3 from 644 to 755
changing mode of build/scripts-3.9/2to3 from 644 to 755
renaming build/scripts-3.9/pydoc3 to build/scripts-3.9/pydoc3.9
renaming build/scripts-3.9/idle3 to build/scripts-3.9/idle3.9
renaming build/scripts-3.9/2to3 to build/scripts-3.9/2to3-3.9
Creating directory /Library/Frameworks/Python.framework/Versions/3.9/Resources/English.lproj
ginstall: cannot create directory ‘/Library/Frameworks/Python.framework’: Permission denied
Creating directory /Library/Frameworks/Python.framework/Versions/3.9/lib
ginstall: cannot create directory ‘/Library/Frameworks/Python.framework’: Permission denied
make: *** [Makefile:1737: frameworkinstallstructure] Error 1
```

```console
$ PYTHON_CONFIGURE_OPTS="--enable-framework" \
    CPPFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix libffi)/include" \
    LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix libffi)/lib" \
    pyenv install -v 3.9.6
...
Installed Python-3.9.6 to /Users/n8henrie/.pyenv/versions/3.9.6
```

Logs for both the former and latter: https://gist.github.com/n8henrie/e3bc02f6f9ed78e8cdd4e858d51ed651

**Comment by native-api** [comment]
Should be fixed in https://github.com/pyenv/pyenv/commit/9985f7b436bd8bea5d1a6c898c908534db476b13

**Comment by n8henrie** [comment]
Thank you!
