### ISSUE TITLE
Simplify Pyenv shell setup and Lift session restart requirement after installing Pyenv

### ISSUE THREAD

**Issue by native-api** [pyenv/pyenv#2085]
Seeing that the requirement to restart the session since 2.0 (due to some setup code needing to run at login shell's rather than interactive shell's startup) poses an inconvenience to users, we've been considering ways to lift that requirement in a way that won't break things.

So far, the best idea is:

* `eval "$(pyenv init -)"` adds shims to PATH if they are not already there
* `eval "$(pyenv init --path)"` adds shims to PATH unconditionally and deletes any other shims entries in PATH

---

This will:

* allow a user to run just `export PATH=~/.pyenv/bin:"$PATH"; eval "$(pyenv init -)"` as before after installing Pyenv and be able to use it right away
  * while still allowing to add a PATH entry at a different moment -- e.g. in distros that prepend `~/.local/bin` to PATH towards the end of profile, we need to add a PATH entry after that
* There will be no need to run `eval "$(pyenv init --path)"` in cases where it runs before `eval "$(pyenv init -)"`
  * for Zsh in MacOS at least
  * in CI where a user installs Pyenv themsevles

The drawbacks are:

* in Linux, until the user restarts the login session:
  * they will have to run the above commands (`export PATH=~/.pyenv/bin:"$PATH"; eval "$(pyenv init -)"`) by hand in every terminal to be able to use Pyenv in it
  * processes outside the updated terminal sessions won't be able to find Pyenv (but before 2.0, they were never able to find Pyenv at all -- so that's not a regression)
* If a user wishes to intentionally add shims to PATH multiple times (e.g. in some layered setup), we'll have to add a switch to `--path` to not munge a previous entry and instruct them to use it. Maybe we'll also have to add a switch to `init -` to not add a PATH entry since otherwise it may be impossible to ensure that the PATH entry is only added at the right moments.

Is it still worth it? What do you think?

**Comment by native-api** [comment]
> There may be folks who would try to run pyenv on Jenkins.

Isn't Jenkins an Init service? Then it wouldn't inherit configuration from profile automatically, it needs to somehow apply it on its own.

**Comment by native-api** [comment]
**To give you an idea of whether it'll be more or less complicated with the change:** in Ubuntu's case, the new configuration would be:

```
sed -Ei -e '/^([^#]|$)/ {a \
export PYENV_ROOT="$HOME/.pyenv"
a \
export PATH="$PYENV_ROOT/bin:$PATH"
a \
' -e ':a' -e '$!{n;ba};}' ~/.profile
echo 'eval "$(pyenv init --path)"' >>~/.profile

echo 'if [ -z "$PYENV_ROOT" ]; then export PYENV_ROOT=~/.pyenv; fi' >>~/.bashrc
echo 'if ! command -v pyenv >/dev/null; then export PATH="$PYENV_ROOT/bin:$PATH"; fi' >>~/.bashrc
echo 'eval "$(pyenv init -)"' >>~/.bashrc
```

---

**If we lift the requirement to make Pyenv available outside shells,** the configuration would simplify to:

```
echo 'if [ -z "$PYENV_ROOT" ]; then export PYENV_ROOT=~/.pyenv; fi' >>~/.bashrc
echo 'if ! command -v pyenv >/dev/null; then export PATH="$PYENV_ROOT/bin:$PATH"; fi' >>~/.bashrc
echo 'eval "$(pyenv init -)"' >>~/.bashrc

echo 'if command -v pyenv >/dev/null; then eval "$(pyenv init --path)"; fi' >>~/.profile
```

---

Importantly enough, the old configuration that users still try to apply --

```
export PYENV_ROOT=~/.pyenv
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```

would start to work again -- but with a bug (that was there before Pyenv 2.0, too!): if there exists `~/.local/bin`, it would be on PATH before `shims` (so anything you install with `pip` for the system Python would override Pyenv's shims).

**Comment by native-api** [comment]
In MacOS, the configuration would simplify to almost what is was before 2.0:

```
echo 'if [ -z "$PYENV_ROOT" ]; then export PYENV_ROOT=~/.pyenv; fi' >>~/.zshrc    # Not needed for Pyenv from Homebrew
echo 'if ! command -v pyenv >/dev/null; then export PATH="$PYENV_ROOT/bin:$PATH"; fi' >>~/.zshrc    # Not needed for Pyenv from Homebrew
echo 'eval "$(pyenv init -)"' >>~/.zshrc
```

And the requirement to run the shell as a login shell would also be lifted.

**Comment by tvalentyn** [comment]
> > There may be folks who would try to run pyenv on Jenkins.
> 
> Isn't Jenkins an Init service? Then it wouldn't inherit configuration from profile automatically, it needs to somehow apply it on its own.

Updating `$PATH` in  `/etc/environment` helps avoid navigating the login vs non-login shell shananigans.

**Comment by native-api** [comment]
**I've done an analysis of how other language version managers do ythe initialization.**

There are two main ways to do it:

* source the init script directly with full explicit path
  * it does everything by itself, including adding the main executable to PATH
* source the init script indirectly (via PATH or with path constructed with configuration envvars), making some configuration steps with separate commands

---

* **RVM**
  * source directly
  * adds lines into `.profile`, `.bashrc`, `,zshrc`, `.mkshrc`
* **phpenv**
  * `PATH=` + source indirectly
    * makes `.bash_profile` source `.profile`
    * adds lines into `.profile`, `.bash_profile`/`.bash_login`, `.zlogin` (i.e. only for login shells)
* **nvm**
  * `NVM_DIR=` + source indirectly
  * adds into `.bashrc`/`.bash_profile`, `.zshrc` (i.e. only for interactive shells)
* **rbenv**
  * `PATH=` + source indirectly
  * adds into `.bashrc`/`.bash_profile`, `.zshrc` (i.e. only for interactive shells)
