### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by sandipanpanda** [pyenv/pyenv#2086]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

We should add a CONTRIBUTING.md file in this repository to provides potential project contributors with a short guide to how they can help with this project.

**Comment by native-api** [comment]
What information do you expect it to contain? Contributing here is discussing issues and submitting pull requests. That's standard practice at Github, it's hardly worth mentioning.

**Comment by StreakSharn** [comment]
Maybe it could include issue templates? A link to an example of a model contribution?

**Comment by native-api** [comment]
I guess it could contain guidance on advanced topics -- like [designning installation scripts](https://github.com/pyenv/pyenv/issues/1445) or doing various maintenance tasks like making a release or synchronizing the codebase with Rbenv.

**Comment by native-api** [comment]
I've authored a contribution guide. Interested parties and especially @pyenv/pyenv-core-maintainers , please review the text -- in particular, see if you agree with the presented policies and formulations (I suspect that the formulations might sound imposing and/or stricter than they actually are).

**Comment by native-api** [comment]
I've authored a contribution guide. Interested parties and especially @pyenv/pyenv-core-maintainers , please review the text -- in particular, see if you agree with the presented policies and formulations (I suspect that the formulations might sound imposing and/or stricter than they actually are).

Also please see if I missed or failed to cover anything.
