### ISSUE TITLE
Pyenv versions listing should use version sort

### ISSUE THREAD

**Issue by Rotonen** [pyenv/pyenv#2097]
With the introduction of 3.10, the sorting of versions is no longer intuitively correct.

```
$ pyenv versions
* system
  3.10.0
  3.9.7
  ```

This seems to happen as a side effect of glob expansion sorting on a byte for byte basis on most filesystems.

https://github.com/pyenv/pyenv/blob/fab0082bd5cdda07f0bfdd69a9c676bc2d2906b3/libexec/pyenv-versions#L135

GNU `sort` would have a `-V` `--version-sort` [[1](https://man7.org/linux/man-pages/man1/sort.1.html)] flag, but that's not portable as at least `sort` on macOS does not have that [[2](https://ss64.com/osx/sort.html)].

Columnar sort with a separator [[2](https://stackoverflow.com/a/39454220/1214697)]could be a way to approach the problem. This could be added as a pipe to the end of that for loop.

This is the path the `--definitions` command of `python-build` has taken.

https://github.com/pyenv/pyenv/blob/fab0082bd5cdda07f0bfdd69a9c676bc2d2906b3/plugins/python-build/bin/python-build#L1825-L1830

https://github.com/pyenv/pyenv/blob/fab0082bd5cdda07f0bfdd69a9c676bc2d2906b3/plugins/python-build/bin/python-build#L1832-L1835

[1] https://man7.org/linux/man-pages/man1/sort.1.html
[2] https://ss64.com/osx/sort.html
[3] https://stackoverflow.com/a/39454220/1214697

**Comment by native-api** [comment]
> This seems to happen as a side effect of glob expansion sorting on a byte for byte basis on most filesystems.

This has nothing to do with filesystem order. [Bash guarantees the sort to be alphabetical.](https://serverfault.com/questions/122737/in-bash-are-wildcard-expansions-guaranteed-to-be-in-order)

**Comment by native-api** [comment]
> This seems to happen as a side effect of glob expansion sorting on a byte for byte basis on most filesystems.

This has nothing to do with filesystem order. [Bash guarantees the sort to be alphabetical.](https://serverfault.com/questions/122737/in-bash-are-wildcard-expansions-guaranteed-to-be-in-order)

If you want to reorder it, you'll have to support arbitrary filenames. (E.g. read entries to an array, sort them like in https://stackoverflow.com/questions/7442417/how-to-sort-an-array-in-bash but use `\0` as a separator and `sort -z`)

**Comment by Rotonen** [comment]
>This has nothing to do with filesystem order. Bash guarantees the sort to be alphabetical.

Within ASCII, yes. By pointing at filesystems I meant to hint at stuff like composed vs. uncomposed unicode getting sometimes treated inconsistently in glob expansions for characters such as `ä` (and that gets even weirder with `sort` and locale dependent collation [`a` vs. `ä`] in the mix in your suggested alternate approach - portability is *hard*). But that's not the relevant discussion here and is an infinite rabbit hole of things one wishes one never knew about.

Thankfully `sort -V` wraps most of the madness to a point where one never needs to care and all of the inputs here are pretty much guaranteed to always remain ASCII compatible. And you have the function from `python-build` already for platforms where that flag is not available.

In any case thank you for taking a look at this minor UX papercut.

**Comment by victor-gp** [comment]
If someone gets down to this, maybe it's best to sort versions for any python flavor in descending order.

Like 3.10.5, 3.10.4, ... , 2.1.3, activepython-3.6.0, ... , activepython-2.7.14, etc.

Users are much more likely to look for the latest stable version, no?
