### ISSUE TITLE
Add Cinder compiler (Python 3.8.5+cinder) support

### ISSUE THREAD

**Issue by alexdoesh** [pyenv/pyenv#2105]
I'd like to add Facebook's [Cinder](https://github.com/facebookincubator/cinder/) compiler support to pyenv, what's the best way to make it happen soon? They have no proper distribution yet, but it's possible to get the source and compile it (with or without docker image, I have playbooks for both). Can somebody point me, what would be the best approach here, I'll wrap it up and submit PR.

**Comment by native-api** [comment]
We now have a contribution guide which gives more details about authoring installation scripts.
