### ISSUE TITLE
Request to add pypy3.8

### ISSUE THREAD

**Issue by Zac-HD** [pyenv/pyenv#2110]
Changelog: https://doc.pypy.org/en/latest/release-v7.3.6.html

Issue #1699 documents how this went for pypy3.7, including how to add it.  I'm aiming to get to this next weekend, but if anyone wants to jump in before that I'd be delighted 😁

**Comment by joshfriend** [comment]
already done in #2111 it seems!

**Comment by Zac-HD** [comment]
Sweet, within four hours of opening an issue!  Thanks all 😁
