### ISSUE TITLE
For fish shell, "$PYENV_ROOT/versions/3.10.0/bin" masks "$PYENV_ROOT/shims" in PATH for some reason

### ISSUE THREAD

**Issue by xlorepdarkhelm** [pyenv/pyenv#2116]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [*] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [*] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [*] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [*] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [*] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description

I am using pyenv with fish, and I cannot get pyenv to pick up and use the shims, so when I switch versions it just retains the version I set globally, and will not change to another version of python.

When I set the global version:
```fish
$ pyenv global 3.10.0
$ pyenv which python
/home/<user>/.pyenv/versions/3.10.0/bin/python
$ which python
/home/<user>/.pyenv/versions/3.10.0/bin/python
$ python --version
Python 3.10.0
$ $HOME/.pyenv/shims/python --version
Python 3.10.0
```

Then if I set the local version to something different:

```fish
$ pyenv local 3.9.7
$ pyenv which python
/home/<user>/.pyenv/versions/3.9.7/bin/python
$ which python
/home/<user>/.pyenv/versions/3.10.0/bin/python
$ python --version
Python 3.10.0
$ $HOME/.pyenv/shims/python --version
Python 3.9.7
```

I have the following universal variables set:
```fish
$ set -Ux PYENV_ROOT $HOME/.pyenv
$ set -U fish_user_paths $PYENV_ROOT/shims $PYENV_ROOT/bin
```

And the following in my `$HOME/.config/fish/config.fish`:

```fish
status --is-login; and pyenv init --path | source
status --is-interactive; and pyenv init - | source
status --is-interactive; and pyenv virtualenv-init - | source
```

My `PATH` results in `$PYENV_ROOT/versions/3.10.0/bin` being set ahead of `$PYENV_ROOT/shims`, so it finds the wrong python version.

- [*] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu Linux 21.10/fish 3.1.2
- [*] OS architecture (e.g. amd64): aarch64
- [*] pyenv version: 2.1.0-15-g444088b1
- [*] Python version: 3.10.0
- [*] C Compiler information (e.g. gcc 7.3): gcc 11.2.0
- [*] Please attach a debug trace log as gist n/a
  * If the problem happens in a Pyenv invocation, you can turn on debug logging by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`
  * If the problem happens outside of a Pyenv invocation, get the debug log like this:
     ```
     export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
     set -x
     <reproduce the problem>
     set +x
     ```

**Comment by xlorepdarkhelm** [comment]
My `/etc/passwd` file, for my entry has `/usr/bin/fish` as my login shell.

I should note -- the `$fish_user_paths` does get loaded even without the previous comment I made. Everything is there, just in the wrong order. It looks like `$fish_user_paths` gets loaded into `$PATH` first, and then the stuff from `pyenv init` after, which prepends my `$PATH` with its changes. It takes me running that line to set the `$fish_user_paths` a second time into my path to get the order correct. Which seems very kludgy and likely not the way it was intended.

**Comment by native-api** [comment]
> My `/etc/passwd` file, for my entry has `/usr/bin/fish` as my login shell.

Yes, but if you are in a GUI session, you are probably not running it as a login shell -- which is what matters.
In a GUI session, the GUI manager acts as a login shell, and Linux GUI managers. to my knowledge, are only able to run `~/.profile` as `sh`, regardless of what is written in `passwd`.

**Comment by xlorepdarkhelm** [comment]
I don't run it in GUI session. I am SSH'ing into that system remotely. And I have the login shell be defined as fish.

**Comment by xlorepdarkhelm** [comment]
I tried adding the lines to `~/.profile` and it did nothing.

**Comment by xlorepdarkhelm** [comment]
Nope, no virtual environment, no pyenv shell. When I do the `pyenv init` and `pyenv virtualenv-init` lines, it sticks that in my path, and breaks calling "python". I do use `pyenv-virtualenv` but in this case, I'm not even talking about a virtual environment, this is just what `pyenv` is doing.

**Comment by native-api** [comment]
Without seeing a debug trace, I cannot say what exactly is happening.

**Comment by xlorepdarkhelm** [comment]
[config.fish.trace.zip](https://github.com/pyenv/pyenv/files/7388768/config.fish.trace.zip)

This is the trace of the script. All I changed was my username.

**Comment by native-api** [comment]
>  /home/<user>/.pyenv/versions/3.10.0/bin is already present ... so it must be set by something else.

Most probably, it was at some point added to one of the universal variables that gets ultimately added to PATH.
