### ISSUE TITLE
curl (60) SSL certificate problem

### ISSUE THREAD

**Issue by jurosic** [pyenv/pyenv#2134]
After reinstalling curl and openssl, due to another issue when trying to install a python version, im now encountering another issue with SSL certificates
```
BUILD FAILED (Raspbian 10 using python-build 2.2.0)
Results logged to /tmp/python-build.20211027190322.16278.log
Last 10 log lines:
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

From what i see, i think that pyenv is trying to copy a ssl certificate 
`/tmp/python-build.20211027190322.16278 /usr/lib/ssl/certs`
but is either failing to do so, or openssl is not "trusting them"
Im trying to install python 2.7.8 using command:
`pyenv install 2.7.8`

**Comment by yonkeltron** [comment]
Actually I am also having this issue and can reproduce it from inside a Debian Bullseye container! Note that I am behind a corporate firewall as many companies have and curl doesn't seem to be respecting the options I am setting.

Here is a reduced-test-case Dockerfile I am using to reproduce the download issue:

```dockerfile
FROM debian:bullseye

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y bash ca-certificates curl dirmngr gawk git gpg libssl-dev locales
RUN echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen && locale-gen && update-locale LANG=en_US.UTF-8

RUN adduser --disabled-password --gecos '' pyuser
WORKDIR /home/pyuser
USER pyuser
SHELL [ "/bin/bash", "-lc" ]
RUN echo 'insecure' >> ~/.curlrc

RUN curl https://pyenv.run | bash
RUN echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
RUN echo 'eval "$(pyenv init --path)"' >> ~/.bashrc
RUN echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
```

When I build this container it works fine but as soon as I try the following command from inside the container, I get the same curl error. Please observe:

```bash
$ pyenv install -v 3.10.0
Downloading Python-3.10.0.tar.gz...
-> https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tgz
error: failed to download Python-3.10.0.tar.gz

BUILD FAILED (Debian GNU/Linux 11 using python-build 20180424)

Results logged to /tmp/python-build.20211112165952.4796.log

Last 10 log lines:
/tmp/python-build.20211112165952.4796 /workspaces/beachbag
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

I am retrying with the recommended packages here: https://github.com/pyenv/pyenv/wiki#suggested-build-environment

Not sure how those would help a download problem but I'd like to be thorough. Please let me know if I can provide any additional information!

Thanks,
+Jonathan

**Comment by native-api** [comment]
@yonkeltron WFM if I also add `eval "$(pyenv init -)"` to `.bashrc`.

**Comment by jurosic** [comment]
Sorry for the late response, and sorry i didnt specify -v, thats my fault, ive havent really been active in the past weeks, but i managed to install python manually, when i get home im going to try to reproduce this and this time with -v.. that is if i dont forget haha..

**Comment by yonkeltron** [comment]
This might be an issue with python-build actually. Thoughts?
