### ISSUE TITLE
Cannot build 2.7.18 on Apple Silicon

### ISSUE THREAD

**Issue by mikepqr** [pyenv/pyenv#2136]
#2061 doesn't seem to work for me, i.e. `pyenv install 2.7.18` fails on Apple Silicon. pyenv here is 2.2.0 (i.e. includes #2061), installed via brew. 

And because the GNU utils were mentioned in that PR, I should note that coreutils is also installed via brew, but binutils is not.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
* [X] Make sure your problem is not derived from plugins.

### Description
- [X] Platform information: macOS Big Sur 11.6
- [X] OS architecture: Apple Silicon
- [X] pyenv version: 2.2.0
- [X] Python version: 2.7.18
- [X] C Compiler information (e.g. gcc 7.3): Apple clang version 12.0.5 (clang-1205.0.22.9)
- [X] Please attach a debug trace log as gist

[python-build.20211027233300.45128.log](https://github.com/pyenv/pyenv/files/7431721/python-build.20211027233300.45128.log)

**Comment by daironmichel** [comment]
this did it for me
```
LDFLAGS="-L/opt/homebrew/Cellar/openssl@1.1/1.1.1m/lib" CPPFLAGS="-I/opt/homebrew/Cellar/openssl@1.1/1.1.1m/include" pyenv install 2.7.18
```

**Comment by ronhuafeng** [comment]
> this did it for me
> 
> ```
> LDFLAGS="-L/opt/homebrew/Cellar/openssl@1.1/1.1.1m/lib" CPPFLAGS="-I/opt/homebrew/Cellar/openssl@1.1/1.1.1m/include" pyenv install 2.7.18
> ```

It works for me too. Macbook Pro m1
