### ISSUE TITLE
Wrong compile flags generated on Debian

### ISSUE THREAD

**Issue by MFairley** [pyenv/pyenv#2138]
### Description
- [ ] Platform information: Debian 10
- [ ] OS architecture: x86_64
- [ ] pyenv version: pyenv 2.2.0
- [ ] Python version: 3.9.2
- [ ] C Compiler information (e.g. gcc 7.3):  gcc version 8.3.0 (Debian 8.3.0-6) 
- [ ] https://gist.github.com/MFairley/04ce7e72296d3e90a71d3b7e6ab01a8b 

There appears to be an issue with the compiler flags generating an incorrect gcc command

```
configure:3944: gcc -fPIC  -I/home/user/.pyenv/versions/3.9.2/include -IUse 'apt-get update' and 'apt-get install' instead./include -L/home/user/.pyenv/versions/3.9.2/lib -LUse 'apt-get update' and 'apt-get install' instead./lib conftest.c  >&5
```

If I manually run 

```
./configure --prefix=/home/user/.pyenv/versions/3.9.2 --libdir=/home/user/.pyenv/versions/3.9.2/lib
```

then it works but not using pyenv install or pyenv doctor.

**Comment by native-api** [comment]
Please attach a debug trace log of the failing command as specified in the issue template.

Looks like you don't have a dependency installed, but that error message surely shouldn't be getting into the flags.

**Comment by MFairley** [comment]
I attached the config.log as a gist. Is there a different debug trace log needed?

**Comment by native-api** [comment]
Yes, the output of `PYENV_DEBUG=1 pyenv install -v <python_version>` is needed.

**Comment by MFairley** [comment]
Here's the output: https://gist.github.com/MFairley/732500ead81e020aa94b4b685e7ee038

**Comment by native-api** [comment]
Okay, the erroneous values do not come from Pyenv's logic.

Looks like you have some garbage in envvars affecting the compiler.

Can't say more 'cuz you seem to have reported your version wrong: the `configure` line numbers in your `config.log` do not correspond to the one in either `3.9.2` or `3.9.6`.

**Comment by native-api** [comment]
> 
> 
> Here's the output: https://gist.github.com/MFairley/732500ead81e020aa94b4b685e7ee038

Sh1t. That's the build log file, not the output of the command as requested. It's incomplete. Please provide the full output of the command _itself_ -- e.g. like this: `<command> 2>&1 | tee trace.log`

**Comment by MFairley** [comment]
Sorry, I accidentally entered the wrong python version. Here's the output of `PYENV_DEBUG=1 pyenv install -v 3.9.2 2>&1 | tee trace.log`

https://gist.github.com/MFairley/b3b2975abff0c68af2068d2fcb6fa76b

**Comment by MFairley** [comment]
It looks like this issue is due to a command `brew` that prints "Use 'apt-get update' and 'apt-get install' instead." and causes pyenv to think that it should use brew even though I'm on Debian.

**Comment by native-api** [comment]
Exactly! Where does it come from? `apt-file` doesn't find anything relevant:

```
debian@debian10:~$ apt-file search -x /brew\$
r-cran-brew: /usr/lib/R/site-library/brew/R/brew
```

---

If you just make it print that message to stderr instead of stdout as it should, the problem will be already fixed.

**Comment by MFairley** [comment]
It's an internal command that's on the Debian image at my company. 

> If you just make it print that message to stderr instead of stdout (as it should do since this is an error message), the problem will be already fixed.

Exactly, we just made this change after discovering this issue.

**Comment by Groxx** [comment]
Along related lines!
`$(brew ... || true)` followed by a check only for a string prefix is _incredibly_ fragile, literally any kind of brew issue could result in a similar kind of misbehavior.

Can I request instead doing what other similar funcs in here do, and at least checking to see if the result is a directory that exists?  Or treating a non-zero exit as a "do not use brew" failure?

**Comment by native-api** [comment]
Agreed. It's just that it's nontrivial in Bash to handle failures of commands run an output capture expression and this is a very uncommon situation -- so whoever wrote the code probably didn't bother.

We would welcome a PR that would handle cases like this.

**Comment by Groxx** [comment]
er.  no it's not.  $? contains the exit code:
```
val="$(brew asdf)"
[[ $? == 1 ]] && echo "failed"
```
results in 
```
❯ bash test.sh
Error: Unknown command: asdf
failed
```
the `|| true` has likely just turned into bad cargo-culting.
