### ISSUE TITLE
Pyenv cannot be used after being upgraded

### ISSUE THREAD

**Issue by guoziqin** [pyenv/pyenv#2142]
### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): macos catalina 10.15.7
- [ ] OS architecture (e.g. amd64): x86
- [ ] pyenv version: 2.2.0-5-g54889eb8
- [ ] Python version: 3.6.4
- [ ] C Compiler information (e.g. gcc 7.3):  12.0.0
- [ ] Please reproduce the problem with debug tracing enabled and attach the resulting output as a gist
![image](https://user-images.githubusercontent.com/37041136/140016168-38882a79-9611-48a4-83a8-56a46f057edc.png)

**Comment by guoziqin** [comment]
![image](https://user-images.githubusercontent.com/37041136/140016290-492cce8c-3f73-4593-b4fe-c8ec4a53770e.png)
The project won't get off the ground，Before that I pulled out our latest code update

**Comment by guoziqin** [comment]
`cd /Users/guoziqin/.pyenv/plugins/python-build/../.. && git pull && cd -`
I used this command to update the Pyenv source

**Comment by guoziqin** [comment]
I am now unable to use Pyenv on my terminal

**Comment by CptSpaceToaster** [comment]
Could the issue template be modified to catch the repeat error?

**Comment by guoziqin** [comment]
> pyenv init --path

![image](https://user-images.githubusercontent.com/37041136/140461987-b59abb1f-4cd2-4589-8351-ec7241cf7f58.png)
It still doesn't seem to work.

**Comment by guoziqin** [comment]
> Could the issue template be modified to catch the repeat error? It seems like lots of folks are running into this one.
What template should I modify? I don't quite understand what you mean

**Comment by guoziqin** [comment]
> another victim of #2001?
> 
> make sure your shell setup runs `pyenv init --path` as described in the README. just running `pyenv init -` no longer works
![image](https://user-images.githubusercontent.com/37041136/140462124-337e420f-7dbc-4853-8c4a-8f527a6aef0c.png)
This is the result of my pyenv init - command

**Comment by guoziqin** [comment]
> another victim of #2001?
> 
> make sure your shell setup runs `pyenv init --path` as described in the README. just running `pyenv init -` no longer works
I changed pyenv init - to pyenv Init - path in.zshrc to solve my problem successfully.Thank you for answering my questions

**Comment by guoziqin** [comment]
> Could the issue template be modified to catch the repeat error? It seems like lots of folks are running into this one.

Thank you very much

**Comment by guoziqin** [comment]
> Could the issue template be modified to catch the repeat error? It seems like lots of folks are running into this one.

Thank you very much

**Comment by guoziqin** [comment]
> Could the issue template be modified to catch the repeat error? It seems like lots of folks are running into this one.

Thank you very much

**Comment by guoziqin** [comment]
> Could the issue template be modified to catch the repeat error? It seems like lots of folks are running into this one.

Thank you very much
