### ISSUE TITLE
Enhancement: Install by default last patch version if missing

### ISSUE THREAD

**Issue by mBouamama** [pyenv/pyenv#2145]
# Enhancement 
Install by default last patch version if missing.

# Why?
Because when I use pyenv Ii only want to download a python version and I want last patch version and I don't know what's number is it. That's why I wanted this enhancement.

# Expected Behavior

```shell
$ pyenv install 3.8
Downloading Python-3.8.12.tar.xz...
-> https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tar.xz
Installing Python-3.8.12...
```

# Actual Behavior
```
$ pyenv install 3.8
python-build: definition not found: 3.8

The following versions contain `3.8' in the name:
```

# Idea
By default add last patch version if its missing, an other solution can be an auto-completion and press tab for having list of patch version

**Comment by BrandonLWhite** [comment]
Try `pyenv install 3.8:latest`.  This was added recently and seems like it will do exactly what you are wanting.

**Comment by mBouamama** [comment]
perfect thx
