### ISSUE TITLE
"ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?"

### ISSUE THREAD

**Issue by iamrathore** [pyenv/pyenv#2146]
Hello- I was trying to install python version 2.7.X in my WSL for an ML course where I need to work on GraphLab and it supports only the python 2.7 version(someone mentioned on Github but on their website it mentioned python 3.6 will work which is not working) and when I was trying to install it, the system throws the below error.

"ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?
Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems
BUILD FAILED (Ubuntu 20.04 using python-build 20180424)"

I checked the mentioned link but still it didn't work for me.
Can anyone help me?

Thanks

**Comment by native-api** [comment]
Please include the required diagnostic info as per the issue template and explain what steps you took and what the results were.

**Comment by iamrathore** [comment]
I downloaded the previous version of OpenSSL 1.0 since someone mentioned that 2.7 will not work in the updated version but that version didn't install correctly. the complier through some error at the end. I followed the step which was mentioned in this link- https://github.com/pyenv/pyenv/wiki/Common-build-problems but nothing works out.

**Comment by native-api** [comment]
> Please include the required diagnostic info as per the issue template and explain what steps you took and what the results were.

http://idownvotedbecau.se/itsnotworking/
https://github.com/pyenv/pyenv/blob/master/.github/ISSUE_TEMPLATE.md
