### ISSUE TITLE
bug: pip installing into /usr/lib/python3.8/site-packages instead of ~/.pyenv/versions/myenvironment/lib/python3.8/site-packages/

### ISSUE THREAD

**Issue by sabotagebeats** [pyenv/pyenv#2148]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 20.04LTS WSL2
- [x] OS architecture (e.g. amd64): Intel
- [x] pyenv version: pyenv 2.2.0-5-g54889eb8
- [x] Python version: Python 3.8.10
- [x] C Compiler information (e.g. gcc 7.3): gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
- [ ] Please reproduce the problem with debug tracing enabled and attach the resulting output as a gist
  * If the problem happens in a Pyenv invocation, you can turn on tracing by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`
    * If the problem is with `pyenv install`, make sure to also enable its verbose mode (`-v`)
  * If the problem happens outside of a Pyenv invocation, enable shell trace output like this:
     ```sh
     export PS4='+(${(%):-%x}:${LINENO}): ${funcstack[0]:+${funcstack[0]}(): }'  #Zsh
     export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'  #Bash
     set -x
     <reproduce the problem>
     set +x
     ```

**Comment by sabotagebeats** [comment]
https://github.com/ApeWorX/ape/issues/222

**Comment by sabotagebeats** [comment]
from my `~/.bashrc`:

```# pyenv
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"```

**Comment by sabotagebeats** [comment]
```
 Running setup.py develop for eth-ape
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/sabotage/ape/ape/setup.py'"'"'; __file__='"'"'/home/sabotage/ape/ape/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
         cwd: /home/sabotage/ape/ape/
    Complete output (18 lines):
    running develop
    WARNING: The user site-packages directory is disabled.
    error: can't create or remove files in install directory
    
    The following error occurred while trying to add or remove files in the
    installation directory:
    
        [Errno 2] No such file or directory: '/usr/lib/python3.8/site-packages/test-easy-install-14112.write-test'
    
    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:
    
        /usr/lib/python3.8/site-packages/
    
    This directory does not currently exist.  Please create it and try again, or
    choose a different installation directory (using the -d or --install-dir
    option).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/sabotage/ape/ape/setup.py'"'"'; __file__='"'"'/home/sabotage/ape/ape/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.
```

**Comment by native-api** [comment]
Please update your shell's configuration according to the README.

**Comment by sabotagebeats** [comment]
> Please update your shell's configuration according to the README.

The problem is that it is not documented properly @native-api 

I have documented the resolution to this problem here https://github.com/pyenv/pyenv-installer/issues/112

**Comment by DestyNova** [comment]
> > Please update your shell's configuration according to the README.
> 
> The problem is that it is not documented properly @native-api
> 
> I have documented the resolution to this problem here [pyenv/pyenv-installer#112](https://github.com/pyenv/pyenv-installer/issues/112)

It is documented in the [pyenv README](https://github.com/pyenv/pyenv#basic-github-checkout) but not in the [pyenv-installer README](https://github.com/pyenv/pyenv-installer) which definitely needs an update. Unfortunately the pyenv "basic Github checkout" instructions that need to be followed are quite long and a lot of people will give up at that point.
