### ISSUE TITLE
(Intel mac) Binary Go unavailable for this platform

### ISSUE THREAD

**Issue by mcandre** [pyenv/pyenv#2149]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description

No matter which Go version I select, gvm reports `ERROR: Binary Go unavailable for this platform`.

```console
$ gvm install go1.4 -B
Installing go1.4 from binary source
ERROR: Binary Go unavailable for this platform

$ uname -a
Darwin andrew.attlocal.net 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64
```

- [ ] Platform information (e.g. Ubuntu Linux 16.04): macOS Big Sur
- [ ] OS architecture (e.g. amd64): amd64
- [ ] pyenv version: 2.2.0
- [ ] Python version: 2.7.16
- [ ] C Compiler information (e.g. gcc 7.3): Apple clang 13.0.0
- [ ] Please reproduce the problem with debug tracing enabled and attach the resulting output as a gist
  * If the problem happens in a Pyenv invocation, you can turn on tracing by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`
    * If the problem is with `pyenv install`, make sure to also enable its verbose mode (`-v`)
  * If the problem happens outside of a Pyenv invocation, enable shell trace output like this:
     ```sh
     export PS4='+(${(%):-%x}:${LINENO}): ${funcstack[0]:+${funcstack[0]}(): }'  #Zsh
     export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'  #Bash
     set -x
     <reproduce the problem>
     set +x
     ```

As a workaround, I'm ditching gvm and installing Go manually.

**Comment by native-api** [comment]
How is this relevant to Pyenv?..
