### ISSUE TITLE
pyenv fails to redirect python for Raspian OS (Pi 400 board)

### ISSUE THREAD

**Issue by mightylastingcode** [pyenv/pyenv#2151]
I have successfully installed pyenv for Raspian OS Buster on Pi 400 board.

The only problem is that it will not redirect the python path to the newer python 3.9.7 I installed with pyenv.   It works on my Raspberry Pi 3B with Raspian OS Jesse.   

===============================
.bashrc file

export PATH="~/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

================================
$pyenv local 3.9.7
$pyenv local 
3.9.7
$which python3
/usr/bin/python    (Not correct)   It should be /home/pi/.pyenv/versions/3.9.7/bin/python
$python3
Python 3.7.3....   (Not correct)   It should be 3.9.7.

$echo $PATH
/home/pi/.pyenv/plugins/pyenv-virtualenv/shims:~/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games

$/home/pi/.pyenv/versions/3.9.7/bin/python
Python 3.9.7....

I can only run 3.9.7 with the full executable path.

Please help.  Thank you.
Mike

**Comment by native-api** [comment]
`echo 'eval "$(pyenv init --path)"' >>~/.profile` as per the README and relogin or restart the shell as a login shell.

**Comment by mightylastingcode** [comment]
Thank you for your suggestion.   I have read the readme file.   I have checked the setup in Ubuntu.  

Your command will place eval "$(pyenv init --path)" at the end of the ./profile file.  

Unfortunately, ./profile is never invoked when I open a new terminal.  It does not work.

I put some echo lines in both ./profile and ./bashrc files for debugging.   I found out that only ./bashrc file is invoked when I open a new terminal.

So, I experimented and found a working solution.  Put everything in the ./bashrc file.

export PATH="~/.pyenv/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"**

This is the solution that will work on Raspbian OS.

**Comment by native-api** [comment]
> Unfortunately, ./profile is never invoked when I open a new terminal. It does not work.

That's why I wrote _"relogin or restart the shell as a login shell"_ right after that phrase.

---

> So, I experimented and found a working solution. Put everything in the ./bashrc file.
> 
> export PATH="~/.pyenv/bin:$PATH" eval "$(pyenv init --path)" eval "$(pyenv init -)" eval "$(pyenv virtualenv-init -)"**
> 
> This is the solution that will work on Raspbian OS.

Except if your stock `~/.profile` adds `~/.local/bin` to PATH like the one in Debian/Ubuntu that Raspbian is based on. Then if you have that directory, any scripts you install with Pip for your system Python would override Pyenv's shims.

**Comment by native-api** [comment]
Lifting the requirement to relogin is being discussed in https://github.com/pyenv/pyenv/issues/2085

**Comment by mightylastingcode** [comment]
Yes, I did not understand relogin that you mentioned in your post.   I will do some study on relogin and go to the link for the relogin discussion.   What is the case that ~/.local/bin is added to ~/.profile?    You raised some good points.  

I am trying to catch up with what you know.  Thank you for posting again.

Michael

**Comment by native-api** [comment]
> What is the case that ~/.local/bin is added to ~/.profile?

The stock one in Ubuntu has this towards its end:

```
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
```

**Comment by mightylastingcode** [comment]
You are right.  These lines appear in the .profile file for both Ubuntu and Raspian OS.   I need to get a big picture of what these .bashrc and .profile are used for.   When I do remote login with ssh, the .profile file is evoked.   You got that right.  

Wow.  I need to understand the implication of my implementation.  And, I need to understand the official way that the setup is done as instructed on the readme page.    Hope to grasp the scope of these setup requirements.
