### ISSUE TITLE
Python 3.9.8 and 3.9.9 missing

### ISSUE THREAD

**Issue by memark** [pyenv/pyenv#2163]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS 12.0.1
- [x] OS architecture (e.g. amd64): arm64
- [x] pyenv version: 2.2.0

Python 3.9.8 was released on Nov 5 and Python 3.9.9 on Nov 15. Can we please have these versions available in pyenv?

https://www.python.org/downloads/release/python-398/
https://www.python.org/downloads/release/python-399/

❯ pyenv --version
pyenv 2.2.0

❯ pyenv install -l | grep 3.9
  3.9.0
  3.9-dev
  3.9.1
  3.9.2
  3.9.4
  3.9.5
  3.9.6
  3.9.7
  miniconda-3.9.1
  miniconda3-3.9.1
  miniconda3-3.9-4.9.2
  miniconda3-3.9-4.10.3

**Comment by joshfriend** [comment]
They're both there:

* #2162 (https://github.com/pyenv/pyenv/blob/master/plugins/python-build/share/python-build/3.9.9)
* #2152 (https://github.com/pyenv/pyenv/blob/master/plugins/python-build/share/python-build/3.9.8)

Pyenv releases in homebrew are not always immediately created after a new python version is released. If this small delay is inconvenient, consider switching your pyenv install method to the ["Github Checkout"](https://github.com/pyenv/pyenv#basic-github-checkout) version.
