### ISSUE TITLE
Recent versions of PyPy 2.7 are missing

### ISSUE THREAD

**Issue by Mukundan314** [pyenv/pyenv#2167]
Several PyPy 2.7 versions are missing:
- pypy2.7-7.3.2
- pypy2.7-7.3.2-src
- pypy2.7-7.3.3
- pypy2.7-7.3.3-src
- pypy2.7-7.3.4
- pypy2.7-7.3.4-src
- pypy2.7-7.3.5
- pypy2.7-7.3.5-src
- pypy2.7-7.3.6
- pypy2.7-7.3.6-src

See https://downloads.python.org/pypy/

**Comment by pavan696969** [comment]
can i work on this

**Comment by pavan696969** [comment]
.

**Comment by CEOSPFUTURE2** [comment]
Yes.   I'm having trouble logging in bro .I also need help with my website.
I  believe it's down

**Comment by CEOSPFUTURE2** [comment]
Explain

**Comment by CEOSPFUTURE2** [comment]
Yes . If your helping me build my company you can work on anything you like
.

**Comment by CEOSPFUTURE2** [comment]
Do you think you can give me a call.  I.have 100s of questions

**Comment by Hayashi-Yudai** [comment]
Can I do this issue?
