### ISSUE TITLE
Automatically apply appropriate arch flags

### ISSUE THREAD

**Issue by mcandre** [pyenv/pyenv#2169]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): macOS 12
- [ ] OS architecture (e.g. amd64): arm64
- [ ] pyenv version: 2.2.2
- [ ] Python version: 3.10.0
- [ ] C Compiler information (e.g. gcc 7.3): Apple clang 13
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

Please automatically detect the architecture, and supply the appropriate build flags to Python installation. For example, M1 environments should automatically feature `ARCHFLAGS="-arch arm64"`.

**Comment by native-api** [comment]
Did you try without any ARCHFLAGS? Is there anything else in your environment that affects architecture selection?

Pyenv doesn't have any special architecture selection logic so without additional input from envvars, it should be building for whatever is considered the "current" architecture.

**Comment by native-api** [comment]
> it should be building for whatever is considered the "current" architecture

And importantly, that shouldn't require any additional flags.

If you attach the debug trace of a failed build as per the issue template and also `config.log` from the build tree, I may be able to say where there wrong architecture selection comes from.

**Comment by medington** [comment]
Just wanted to chime in here and say that I was running into this error and it turns out I had `export ARCHFLAGS="-arch x86_64"` in my shell config on an M1 Mac.

No idea when or why I added that to my bash shell config but that was the culprit!
