### ISSUE TITLE
Wiki `Home` page contains broken links

### ISSUE THREAD

**Issue by daaf** [pyenv/pyenv#2170]
The following links on the Home page of the wiki are broken:
- [How to verify that I have set up pyenv correctly?](https://github.com/pyenv/pyenv/wiki#how-to-verify-that-i-have-set-up-pyenv-correctly) > "installation instructions"
    - Current URL: https://github.com/pyenv/#installation
    - Correct URL: https://github.com/pyenv/pyenv/blob/master/README.md#installation
    - Even more precise URL: https://github.com/pyenv/pyenv/blob/master/README.md#basic-github-checkout
- [pyenv is installed but things just aren't working for me!](https://github.com/pyenv/pyenv/wiki#pyenv-is-installed-but-things-just-arent-working-for-me) > "existing issues"
    - Current URL: https://github.com/pyenv/issues
    - Correct URL: https://github.com/pyenv/pyenv/issues

I have fixed these links and made other minor adjustments (e.g. making link text more descriptive) in my [fork of the wiki](https://github.com/daaf/pyenv/wiki).

Thanks!

**Comment by native-api** [comment]
Done.
