### ISSUE TITLE
Locating the .pyenv folder somewhere other than home dir

### ISSUE THREAD

**Issue by mike-lawrence** [pyenv/pyenv#2172]
I know the purpose of pyenv is to have a global set of python installs that can then be accessed with possibly-local version selection, hence locating it at `~/.pyenv` but I have a use case where I'd like to have it in a different location; is that possible at all?

**Comment by native-api** [comment]
[Set the PYENV_ROOT envvar](https://github.com/pyenv/pyenv#environment-variables)
