### ISSUE TITLE
Faulty install of Python version ?

### ISSUE THREAD

**Issue by Cbhihe** [pyenv/pyenv#2175]
Hello,
I did not see anything equivalent to what I report here in the issues. Hope I am not wrong.
I've been using `pyenv`on a daily basis for a couple of years now. Following behavior is comletely new and after a day spent reading post to  troubleshoot the issue, I am stumped.

    $ uname -a 
    Linux SYSTEM 5.15.5-arch1-1 #1 SMP PREEMPT Thu, 25 Nov 2021 22:09:33 +0000 x86_64 GNU/Linux
    $ env PYENV_DEBUG=1 pyenv install -v 3.7.0 2>&1 >| trace1.log
    Installing Python-3.7.0...
    [...]
    Installed Python-3.7.0 to /home/USER/.pyenv/versions/3.7.0
    $ pyenv local 3.7.0
    $ python -V
    Python 3.7.0
    $ python
    Python 3.7.0 (default, Dec  2 2021, 20:54:35)
    [GCC 11.1.0] on linux
    >>>quit()
    $ PYENV_DEBUG=1 python -m pip install -U pip 2>&1 >| trace2.log 
    Segmentation fault (core dumped)

If I do any python package install just using the system python as `/usr/bin/python -m pip install ...`  or any `python -m pip install ...` of any package in any Pyenv virtual environments other than 3.7.0, there is no issue, meaning that packages are installed and everything functions as it always has. The "Segmentation fault" only occurs with 3.7.0...

I reinstalled Pyenv, uninstalled and reinstalled the environment Python 3.7.0, rebooted several times in the process, but nothing doing... I attach two debug trace logs: 
- trace1.log for the installation of 3.7.0
- trace2.log for the ensuing segmentation fault...

Sorry for the noise if this is unrelated to Pyenv, but I see no other context or factor that could explain what I see. After a whole day spent troubleshooting, I am stumped.

[trace1.log](https://github.com/pyenv/pyenv/files/7644882/trace1.log)
[trace2.log](https://github.com/pyenv/pyenv/files/7644883/trace2.log)

**Comment by native-api** [comment]
Looks the same as https://github.com/pyenv/pyenv/issues/2141 and probably https://github.com/pyenv/pyenv/issues/916. We cannot help with debugging segfaults in Arch as per https://github.com/pyenv/pyenv/issues/2141#issuecomment-962287057.
