### ISSUE TITLE
Try to understand the complex sed pattern used to configure the shell environment for pyenv.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyenv/pyenv#2188]
I noticed the following guidance to [configure the shell's environment for Pyenv](https://github.com/pyenv/pyenv#basic-github-checkout):

```bash
# the sed invocation inserts the lines at the start of the file
# after any initial comment lines
sed -Ei -e '/^([^#]|$)/ {a \
export PYENV_ROOT="$HOME/.pyenv"
a \
export PATH="$PYENV_ROOT/bin:$PATH"
a \
' -e ':a' -e '$!{n;ba};}' ~/.profile
echo 'eval "$(pyenv init --path)"' >>~/.profile

echo 'eval "$(pyenv init -)"' >> ~/.bashrc
```
 
Today, I try to understand the following sed patters used in the above code snippet:

```
-e ':a' -e '$!{n;ba};}' 
```

Based on the sed manual, I obtained the following explanations:

```
:a Make label a for b command.
$ Match the last line.
! After the address (or address-range), and before the command, a ! may be inserted, which specifies
that the command shall only be executed if the address (or address-range) does not match.

{ Begin a block of commands (end with a }).

n N Read/append the next line of input into the pattern space.

b label
Branch to label; if label is omitted, branch to end of script.

; Is used to separate multiple sed commands, IIRC.
```
By putting all the above knowledge together, I still haven't figured out any clues
pertaining to the goal to be achieved here. And I also noticed the '{ }}' block construct used in the last patter hasn't been closed/matched.

See [here](https://groups.google.com/g/comp.unix.shell/c/UXvyeVLB_5E/m/-SMd0jqZCQAJ) and [here](https://groups.google.com/g/comp.unix.shell/c/UvFsuwY5ED4/m/f-p5kFXnCgAJ) for relevant discussions. Any hints for this problem will be highly appreciated?

Regards,
HZ

**Comment by native-api** [comment]
This is a trick to make sed insert the text only once, at the first blank line.
After the insertion command, there's a loop that makes sed jump through the rest of the file.

See https://stackoverflow.com/questions/148451/how-to-use-sed-to-replace-only-the-first-occurrence-in-a-file

From the options provided, I chose the syntax that is the most readable and would work in any flavor of Sed (the only quirk left is in some one BSD flavor, it would also create a backup file -- which won't break anything).

**Comment by hongyi-zhao** [comment]
The trick is described [here](https://stackoverflow.com/a/33416489).
