### ISSUE TITLE
Add comment about eval "$(pyenv init --path)" in installation instructions for Ubuntu

### ISSUE THREAD

**Issue by n14s** [pyenv/pyenv#2198]
It seems like in Ubuntu 18.04 ([and possibly others](https://github.com/pyenv/pyenv/issues/849#issuecomment-875875617)) `eval "$(pyenv init --path)"` is needed in .bashrc instead of `eval "$(pyenv init -)"`.

With setting pyenv local x.x.x it would still show me the global python version (not set with pyenv).
After a lot of digging I finally stumbled upon the issue comment of the link above.

I would suggest to change the installation information or at least add a one liner disclaimer for that common issue, so other people can find it right away.

**Comment by native-api** [comment]
It is needed in `.profile`/`.bash_profile` as the README says -- and for it to be executed, you need to restart your login session as the README says, too.

This turned out to be unexpectedly hard for users to follow though, so we're considering implementing https://github.com/pyenv/pyenv/issues/2085 which will lift the restart requirement.

**Comment by n14s** [comment]
I don't know about the people I mentioned in my initial post, but I restarted my computer after putting 
"$(pyenv init --path)" only in my .profile (and "$(pyenv init -)" in my .bashrc) 
as described in Step 2 for bash and it didn't work. 
I needed "$(pyenv init --path)" to be in my .bashrc.

**Comment by kbreit** [comment]
I had this same problem. Ubuntu 21.10 wasn't loading the pyenv specified version, even after logout/login. It was only when I changed to this command and relogged in that it worked.

**Comment by soo-shan** [comment]
> I don't know about the people I mentioned in my initial post, but I restarted my computer after putting "$(pyenv init --path)" only in my .profile (and "$(pyenv init -)" in my .bashrc) as described in Step 2 for bash. It didn't work. I needed "$(pyenv init --path)" to be in my .bashrc.

Same for fresh install of Debian 11 Bullseye

**Comment by antoine-gallix** [comment]
Same for me on kubuntu 21.10. using fish shell, the command `pyenv init` only outputs the following:
```
# See the README for instructions on how to set up
# your shell environment for Pyenv.
```
Whereas `pyenv init --path` produce a correct `pyenv init --path` which was sufficient to activate the shims.

**Comment by snowstorm2965** [comment]
I also needed `eval "$(pyenv init --path)"` in my `.bashrc` on Ubuntu 20.04, but then `pyenv` command autocomplete doesn't work anymore. Anyone else?

**Comment by marcandreuf** [comment]
I have submitted a PR for this https://github.com/pyenv/pyenv/pull/2326
