### ISSUE TITLE
BUILD FAILED (OS X 12.0.1 using python-build 2.2.3-1-g423de9ae): "C compiler cannot create executables"

### ISSUE THREAD

**Issue by gsantosoliver** [pyenv/pyenv#2201]
Got the error:

`BUILD FAILED (OS X 12.0.1 using python-build 2.2.3-1-g423de9ae)`

Found some references on internet and in this git but none worked for me. I installed everything following the instructions on https://github.com/pyenv/pyenv#homebrew-in-macos

Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS Monterey version 12.0.1
- [x] OS architecture (e.g. amd64): Intel Core i7 64bits
- [x] pyenv version: pyenv 2.2.3-1-g423de9ae
- [x] Python version: Trying to install 3.8.6
- [x] C Compiler information (e.g. gcc 7.3): 
```
gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.29)
Target: x86_64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
- [x] Please attach the debug trace of the failing command as a gist: 
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

`gosantos@MacBook-Pro ~ % env PYENV_DEBUG=1 pyenv install -v 3.8.6 2>&1 | tee trace.log
`

Produced the file:
[trace.log](https://github.com/pyenv/pyenv/files/7774840/trace.log)

Gist
https://gist.github.com/gsantosoliver/f97422450d2036d63e2ae6ba15f23c8f

**Comment by native-api** [comment]
```
checking whether the C compiler works... no
configure: error: in `/var/folders/vf/5gbwjkvs3xd530xjyj34_znw0000gn/T/python-build.20211224133338.82421/Python-3.8.6':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

See `config,log` in the build tree to see what exact error happened. This usually means that you have broken compiler flag envvars or a broken compiler setup.

**Comment by gsantosoliver** [comment]
> https://gist.github.com/gsantosoliver/f97422450d2036d63e2ae6ba15f23c8f

Hi @native-api. Here is the config.log file:
[config.log](https://github.com/pyenv/pyenv/files/7775049/config.log)

**Comment by native-api** [comment]
```
clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=12.0'
```

https://stackoverflow.com/questions/63972113/big-sur-clang-invalid-version-error-due-to-macosx-deployment-target suggests that this means an outdated XCode SDK.

**Comment by gsantosoliver** [comment]
> ```
> clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=12.0'
> ```
> 
> https://stackoverflow.com/questions/63972113/big-sur-clang-invalid-version-error-due-to-macosx-deployment-target suggests that this means an outdated XCode SDK (you probably updated the OS but that didn't update the SDK to a version that supports the new OS).

@native-api - I followed the page you sent and did this:

```
softwareupdate --all --install --force
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install

```
It solved my problem. I have sucessfuly installed the python version I wanted:
```
(base) gosantos@MacBook-Pro ~ % pyenv install 3.8.6
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.8.6.tar.xz...
-> https://www.python.org/ftp/python/3.8.6/Python-3.8.6.tar.xz
Installing Python-3.8.6...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.8.6 to /Users/gosantos/Documents/workstuff/dev-stuff/pyenv/versions/3.8.6
```

Thank you so much for your help!
