### ISSUE TITLE
Pyenv is failing to install 3.10.1, due to ModuleNotFoundError: No module named 'binascii'

### ISSUE THREAD

**Issue by spapanik** [pyenv/pyenv#2202]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Arch Linux
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: pyenv 2.2.3
- [x] Python version: Python 3.10.1
- [x] C Compiler information (e.g. gcc 7.3):  gcc (GCC) 11.1.0
- [x] Please attach the debug trace of the failing command as a gist: https://gist.github.com/spapanik/09f77a38422600db42e5880febde2671
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

Pyenv is failing to install python 3.10.1 (3.10.0 works fine).

**Comment by markuspeloquin** [comment]
I similarly cannot install Python 3.10.2 when Python 3.10.1 is installed, even though I don't use pyenv. I'm not sure this is limited to pyenv, but I'd take a fix from anywhere.

Looks like the build is finding the modules from another python installation, probably through PREFIX, but it is *not* finding the corresponding binary modules under lib-dynload/. If I remove ~/.local/lib/python3.10 it builds fine.

```
 CC='clang' LDSHARED='clang -shared -L$HOME/.local/lib -L/usr/local/lib -Wl,-O3 -fuse-ld=lld   ' OPT='-DNDEBUG -g -fwrapv -O3 -Wall'  _TCLTK_INCLUDES='' _TCLTK_LIBS=''       ./python -E ./setup.py  build
Traceback (most recent call last):
  File "$HOME/dist/dev-lang/Python-3.10.2/./setup.py", line 50, in <module>
    from distutils.command.install import install
  File "$HOME/.local/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 20, in <module>
    from .. import _collections
  File "$HOME/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "$HOME/.local/lib/python3.10/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "$HOME/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 23, in <module>
    import zipfile
  File "$HOME/dist/dev-lang/Python-3.10.2/Lib/zipfile.py", line 6, in <module>
    import binascii
ModuleNotFoundError: No module named 'binascii'
make: *** [Makefile:637: sharedmods] Error 1
```

**Comment by Bananaman** [comment]
I do not understand what the actual issue is (even after reading all linked bug reports and the pages they link to and the commits), but hey, the workaround works:

```sh
export SETUPTOOLS_USE_DISTUTILS=stdlib
pyenv install 3.10.2
```

**Comment by native-api** [comment]
> checking for ensurepip... upgrade

Looks like Python's build may now download a newer version of Setuptools.

So the problem should fix itself once a fixed version is released.

We can include the workaround into the installation script(s) nevertheless until that happens but we need to know a full list of affected versions.

**Comment by Bananaman** [comment]
@native-api If it's going to automatically fix itself then there's no reason to add the workaround to pyenv. At least if the fix is coming soon (which it looks like).

**Comment by MostHated** [comment]
I am having this issue with 3.10.0, but unfortunately the `export SETUPTOOLS_USE_DISTUTILS=stdlib` var didn't seem to help. I tried 3.10.0 and 3.10-dev.


<details>
<summary>Details</summary>

```sh
zsh ✗  pyenv install 3.10.0                                              mosthated@pop-os
Installing Python-3.10.0...
patching file aclocal.m4
patching file configure
Hunk #5 succeeded at 10537 (offset -15 lines).
python-build: use readline from homebrew
python-build: use zlib from homebrew

BUILD FAILED (Pop 21.10 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20220202122613.874939
Results logged to /tmp/python-build.20220202122613.874939.log

Last 10 log lines:
  File "/tmp/python-build.20220202122613.874939/Python-3.10.0/Lib/importlib/_common.py", line 52, in get_resource_reader
    return reader(spec.name)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1081, in get_resource_reader
  File "/tmp/python-build.20220202122613.874939/Python-3.10.0/Lib/importlib/readers.py", line 2, in <module>
    import zipfile
  File "/tmp/python-build.20220202122613.874939/Python-3.10.0/Lib/zipfile.py", line 6, in <module>
    import binascii
ModuleNotFoundError: No module named 'binascii'
make: *** [Makefile:1281: install] Error 1
```

</details>

**Comment by alexdelorenzo** [comment]
> I do not understand what the actual issue is (even after reading all linked bug reports and the pages they link to and the commits), but hey, the workaround works:
> 
> ```shell
> export SETUPTOOLS_USE_DISTUTILS=stdlib
> pyenv install 3.10.2
> ```

Just want to note that this solution worked for me with `pyenv-git` from the AUR.

**Comment by native-api** [comment]
https://pypi.org/project/setuptools/60.6.0/ has been released which has [the fix](https://github.com/pypa/setuptools/commit/548b8afedd6f0d83d7375367ac789e88af6e4ae9).
