### ISSUE TITLE
Failed to install python 3.7.10 using pyenv using MacOSX12.1.sdk : "error: unknown type name"

### ISSUE THREAD

**Issue by sivaveera** [pyenv/pyenv#2203]
Recently upgraded to macOS Monterey

Now unable to install python using pyenv

Notable type of errors "error: unknown type name"

See attached
[python-build.20211228075347.83743.log](https://github.com/pyenv/pyenv/files/7785458/python-build.20211228075347.83743.log)

**Comment by native-api** [comment]
Looks like a broken/outdated SDK like in https://github.com/pyenv/pyenv/issues/2201

**Comment by native-api** [comment]
Or you're using Clang from Homebrew which you should not, like in https://github.com/pyenv/pyenv/issues/2171

**Comment by sivaveera** [comment]
I tried both the solutions and no help :|

I even tried 3.9.9 but ended up with different error

configure: error: cannot compute sizeof (long double)
[python-build.20211228092526.46312.log](https://github.com/pyenv/pyenv/files/7785763/python-build.20211228092526.46312.log)

See `config.log' for more details

**Comment by native-api** [comment]
```
configure: WARNING: sys/event.h: present but cannot be compiled
configure: WARNING: sys/event.h:     check for missing prerequisite headers?
configure: WARNING: sys/event.h: see the Autoconf documentation
configure: WARNING: sys/event.h:     section "Present But Cannot Be Compiled"
configure: WARNING: sys/event.h: proceeding with the compiler's result
```

This means that your toolchain is broken.
`config.log` will show the specific error that happens there.

**Comment by sivaveera** [comment]
Too many errors, unsure how to fix toolchain errors

**Comment by sivaveera** [comment]
**SOLVED: Hope this helps**

Had unwanted .h files in /usr/local/include

**Ran brew doctor and moved them to /tmp/includes:** 
     mkdir /tmp/includes && brew doctor 2>&1 | grep "/usr/local/include" | awk '{$1=$1;print}' | xargs -I _ mv _ /tmp/includes
     see attached file [mvfiles.txt](https://github.com/pyenv/pyenv/files/7786378/mvfiles.txt)
**Removed existing Command line tools:**
    sudo rm -rf /Library/Developer/CommandLineTools
**Forces installed :**
   softwareupdate --all --install --force
**Installed required python:**

pyenv install 3.7.10
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.10.tar.xz...
-> https://www.python.org/ftp/python/3.7.10/Python-3.7.10.tar.xz
Installing Python-3.7.10...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.7.10 to /Users/sivaveera/.pyenv/versions/3.7.10

 pyenv install 3.9.9
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.9.9.tar.xz...
-> https://www.python.org/ftp/python/3.9.9/Python-3.9.9.tar.xz
Installing Python-3.9.9...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.9.9 to /Users/sivaveera/.pyenv/versions/3.9.9

**Comment by sivaveera** [comment]
Note: This macbook was from 2018 hence had some old libs in /usr/local/include that was creating problems

**Comment by JeroenSchmidt** [comment]
@sivaveera  `softwareupdate --all --install --force` solved my problem. 

* macbook pro 16" 2019
* MacOS 12.4
