### ISSUE TITLE
Request wiki change - OpenSSL Install for Amazon Linux 2

### ISSUE THREAD

**Issue by gadams999** [pyenv/pyenv#2210]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Amazon Linux 2
- [x] OS architecture (e.g. amd64):x86_64
- [x] pyenv version: 2.2.3-1
- [x] Python version: 3.10.1
- [x] C Compiler information (e.g. gcc 7.3): 7.3.1
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

Suggesting change to the wiki. To compile with OpenSSL support, currently the wiki has the following suggestion on the [prereq page](https://github.com/pyenv/pyenv/wiki/Common-build-problems):

- Fedora/CentOS/RHEL(aws ec2):
    - Alternative to openssl-devel:

   ```
    sudo yum install compat-openssl10-devel --allowerasing
   ```

This doesn't work for AL2. What did work was removing the `openssl-devel` package (but not the main `openssl` utilities package) and installing `openssl11-devel` instead. At that point `pyenv install 3.10.1` successfully builds. The version of OpenSSL for the `ssl` module is correct:

```
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.1.1g FIPS  21 Apr 2020'
```

Suggesting addition to the wiki for Amazon Linux 2. Happy to author the changes if needed, don't know how to submit. :)

**Comment by native-api** [comment]
> This doesn't work for AL2. What did work was removing the `openssl-devel` package (but not the main `openssl` utilities package) and installing `openssl11-devel` instead.

I reckon you can, by analogy, run

```
sudo yum install openssl11-devel --allowerasing
```

**Comment by gadams999** [comment]
True, or via `yum swap` too. Just wanted to highlight that for others that were trying the `compat-openssl10-devel` rpm.

**Comment by native-api** [comment]
[Done.](https://github.com/pyenv/pyenv/wiki/Common-build-problems/_compare/3465aade3299cb8e393cc9f1e5f050a7f7f15b78...561e9277cb69363d8a1b2527dcdf16f56de38380)

**Comment by ZackWheelerAvanan** [comment]
This didn't work for me on my ec2 because the yum in my env doesn't have the --allowerasing option.  What @gadams999 suggested worked though. The exact command was:

`sudo yum swap openssl-devel openssl11-devel` I was then able to install `3.10.8` without issue
