### ISSUE TITLE
`conda: command not found` even after `pyenv install miniconda3-latest`

### ISSUE THREAD

**Issue by astrojuanlu** [pyenv/pyenv#2213]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information: Ubuntu 20.04.2 LTS
- [x] OS architecture: Linux ws-f11277a0-842a-4549-881d-b93a4a43c1bc 5.13.0-1007-gcp #8-Ubuntu SMP Thu Nov 11 10:05:41 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- [x] pyenv version: 2.0.6
- [x] Python version: miniconda3-latest
- [ ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

I do

```
$ pyenv install miniconda3-latest
```

and open a new shell, but I still get this error:

```
$ conda
pyenv: conda: command not found

The `conda' command exists in these Python versions:
  miniconda3-latest
```

It is only solved if I do this:

```
$ /home/gitpod/.pyenv/versions/miniconda3-latest/bin/conda init bash
$ exec $SHELL
(base) $ # optionally `conda deactivate`
```

Is this intended?

**Comment by Juanpam** [comment]
@native-api I'm still getting this issue currently. Activating a anaconda python version enables the conda CLI to be available in the shell, but activating a virtualenv from a anaconda python version does not.

**Comment by native-api** [comment]
@Juanpam that is a different issue, https://github.com/pyenv/pyenv-virtualenv/issues/246
