### ISSUE TITLE
Build error - zsh:9: parse error near `fi'

### ISSUE THREAD

**Issue by undrivendev** [pyenv/pyenv#2216]
### Description
- Manjaro Linux
- amd64
- pyenv version: 2.2.3
- Python version: system=3.10.1, trying to install 3.9.4
- C Compiler information: gcc 11.1.0
- [trace.log](https://github.com/pyenv/pyenv/files/7872800/trace.log)
- zsh version: 5.8

Hi,
I installed the default 'python' package from my OS's package manager and I need to install an additional python version (3.9.4), for which I'm trying to use pyenv.  I'm launching the command `pyenv install 3.9.4` but during the build it fails with the error: ``zsh:9: parse error near `fi'``. I also tried installing other versions, nothing changes. I'm using zsh, I attached the full debug log.
Thank you for the project.

**Comment by native-api** [comment]
[Make uses `/bin/sh` as the shell to exectute scripts (unless another one is set in the makefile)](https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html).
You must've somehow set `/bin/sh` to point to Zsh.

**Comment by native-api** [comment]
This is a valid case to report a bug in Zsh in my book. The trace log has the complete code that causes the error, I can see that it's successfully parsed by Bash and gives the above error in Zsh.

**Comment by undrivendev** [comment]
Thank you! By changing the /bin/sh symlink it works. I'll try to submit an issue to zsh.
Closing.
