### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by cyccty** [pyenv/pyenv#2220]
Ubuntu 18.04.6 LTS

1 
git clone https://github.com/pyenv/pyenv.git ~/.pyenv

2 
cd ~/.pyenv && src/configure && make -C src
<img width="1133" alt="Screen Shot 2022-01-16 at 10 42 58 AM" src="https://user-images.githubusercontent.com/32961048/149645310-a074416e-4fdf-4736-81d8-1cfbc389694b.png">

3 
sed -Ei -e '/^([^#]|$)/ {a \
export PYENV_ROOT="$HOME/.pyenv"
a \
export PATH="$PYENV_ROOT/bin:$PATH"
a \
' -e ':a' -e '$!{n;ba};}' ~/.profile
echo 'eval "$(pyenv init --path)"' >>~/.profile
echo 'eval "$(pyenv init -)"' >> ~/.bashrc

4
source ~/.bashrc
<img width="470" alt="Screen Shot 2022-01-16 at 10 45 07 AM" src="https://user-images.githubusercontent.com/32961048/149645346-39f5deef-061b-4e21-9cef-635bff4b519c.png">

After all the above steps, when I run pyenv, the error shown as blew:
<img width="909" alt="Screen Shot 2022-01-16 at 10 38 43 AM" src="https://user-images.githubusercontent.com/32961048/149645342-e04f9cc8-42b2-453e-a8a5-f1ff1741d86d.png">

Please help me.

**Comment by beanaroo** [comment]
We started seeing the same errors:
- Fedora 35 (container image)
- Using the automatic installer

```Dockerfile
ENV PYENV_ROOT="${HOME}/.pyenv"
ENV PATH="${PYENV_ROOT}/shims:${PYENV_ROOT}/bin:${PATH}"

ENV PYTHON_VERSION=3.8.12

RUN set -ex \
    && curl https://pyenv.run | bash \
    && pyenv update \
    && pyenv install $PYTHON_VERSION \
    && pyenv global $PYTHON_VERSION \
    && pyenv rehash
```

Results in:
```
+ pyenv install 3.8.12
/root/.pyenv/plugins/python-build/bin/pyenv-install: line 142: pyenv-hooks: command not found
```

Additionally:
```
$ pyenv --version
/root/.pyenv/bin/pyenv: line 115: exec: pyenv---version: not found

$ pyenv init -
pyenv: no such command `init'
```

---

After adding some echo statements in `pyenv` I was able to determine that `bin_path` is resolved as `/root/.pyenv/bin` (on my Arch Linux desktop it resolves to `..../libexec`).

This is why https://github.com/pyenv/pyenv/blob/master/libexec/pyenv#L90 has no effect.

Manually adding `${PYENV_ROOT}/libexec` to `PATH` works around the issue at the moment.

**Comment by Harmouch101** [comment]
Ubuntu 20.04.4 LTS

I would say that the installation process in the readme file is quite a mess(a bunch of `echo`'s and sed...), It seems like the maintainers never used `cat` for the context of appending data to a file. The thing is that cats are so graceful and beautiful lovely animals.

Anywho, here goes my clean steps of installing `pyenv` on Ubuntu:

1- clone the repo to `~/.pyenv`

```bash
git clone https://github.com/pyenv/pyenv ~/.pyenv
```

2- if you are using [`zsh`](https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH):

```bash
cat << EOF >> ~/.zshrc
# pyenv config
export PATH="${HOME}/.pyenv/bin:${PATH}"
export PYENV_ROOT="${HOME}/.pyenv"
eval "$(pyenv init -)"
EOF
```

or if you using the default bash shell, do this instead:

```bash
cat << EOF >> ~/.bashrc
# pyenv config
export PATH="${HOME}/.pyenv/bin:${PATH}"
export PYENV_ROOT="${HOME}/.pyenv"
eval "$(pyenv init -)"
EOF
```

3- Close the current shell session, and open a new one:
 
And there you go, you have just successfully installed `pyenv`

```bash
➜  ~ pyenv --version
pyenv 2.2.4-1-4-g1e79a522
```

I hope this could help someone in the wild.

**Comment by misterwickone** [comment]
![Screenshot from 2022-11-10 22-20-26](https://user-images.githubusercontent.com/112323581/201163613-7bc2597d-aaf3-42b0-a2c8-a4e8567d255c.png)
Guys!! Please help me. I recently started CS50 and this problem..... Can you show what to do????
