### ISSUE TITLE
Wiki Addition Request for 3rd-party plugin: pyenv-alias-latest-patch-version

### ISSUE THREAD

**Issue by BrandonLWhite** [pyenv/pyenv#2232]
I have published a plugin that I think many in the community will find helpful.
https://github.com/upside-services/pyenv-alias-latest-patch-version

## pyenv-alias-latest-patch-version
pyenv plugin to facilitate 'major.minor' .python-version values that map to the latest patch versions.

This plugin allows you to specify Major.minor versions, without the patch version, so that projects that make use of .python-version are not pinned/locked to a specific patch version. This in turn eliminates the need for multiple developer, CI/CD, and deployment systems from having to use specific Major.minor.patch versions.

With .python-version declared in this way, you are saying "use the latest available patch version for this Major.minor Python version"

CI/CD systems can then be independently updated with the latest Python patch version without having to make the corresponding update to .python-version in the source code repository.

---
I would also like to begin the discussion of the possibility including this behavior directly in pyenv, when installing using the `:latest` option.  I'm willing to submit a PR if the pyenv devs are open to this idea.

**Comment by native-api** [comment]
Done.

**Comment by native-api** [comment]
> I would also like to begin the discussion of the possibility including this behavior directly in pyenv

Actually, this is the most requested feature atm! It's currently filed under https://github.com/pyenv/pyenv/issues/2145.

As usual, there's "devil in the details" -- it's unclear what to do with such an alias when a newer patch release becomes available, whether to include other Python flavors into the search, what to do when there are multiple matches (e.g. multiple patch releases are installed).

**Comment by native-api** [comment]
Not only are we interested, we are able to pay up to 100$ depending on how fully the functionality is implemented.
