### ISSUE TITLE
Not able to install 3.7.6 in M1 Pro macOS Monterey

### ISSUE THREAD

**Issue by Sanju98** [pyenv/pyenv#2235]
User@user ~ % pyenv install 3.7.6
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.6.tar.xz...
-> https://www.python.org/ftp/python/3.7.6/Python-3.7.6.tar.xz
Installing Python-3.7.6...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 12.2 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/cv/80964bw12p3c_jjrc72h99sr0000gn/T/python-build.20220201085556.91788
Results logged to /var/folders/cv/80964bw12p3c_jjrc72h99sr0000gn/T/python-build.20220201085556.91788.log

Last 10 log lines:
checking size of _Bool... 1
checking size of off_t... 8
checking whether to enable large file support... no
checking size of time_t... 8
checking for pthread_t... yes
checking size of pthread_t... 8
checking size of pthread_key_t... 8
checking whether pthread_key_t is compatible with int... no
configure: error: Unexpected output of 'arch' on OSX
make: *** No targets specified and no makefile found.  Stop.

**Comment by joshfriend** [comment]
Please follow the issue template and search the issues list for existing solutions to your problem before opening a new one. 

https://github.com/pyenv/pyenv/search?q=Unexpected+output+of+%27arch%27+on+OSX&type=issues

Either try some of the steps from existing issues, or use a newer version of python (at least 3.9.1) that has M1 architecture support
