### ISSUE TITLE
python -m pip segfaults in 3.6.15

### ISSUE THREAD

**Issue by fofoni** [pyenv/pyenv#2239]
### Description
- [x] Platform information: Arch Linux, Linux 5.15.12-arch1-1
- [x] OS architecture: amd64
- [x] pyenv version: latest (after commit fixing 3.6.15 build)
- [x] Python version: 3.6.15
- [x] C Compiler information (e.g. gcc 7.3): gcc 11.1.0
- [x] Debug trace of the failing command: generated with `env PYENV_DEBUG=1 python -m pip --version`: [trace.log](https://gist.github.com/fofoni/aebf18855a7ab62f9911350a7060d6c4)

This was mentioned in #2236, but that was closed, so I'm opening this. During installation, a segfault occurs in some command related to ensurepip (@bruno-fs posted useful info about it in #2236). I said that the python binary itself looked fine, but it actually doesn't:

```
$ pyenv version
3.6.15 (set by PYENV_VERSION environment variable)

$ pyenv which pip
/home/iptv/.local/lib/pyenv/versions/3.6.15/bin/pip

$ pyenv which python
/home/iptv/.local/lib/pyenv/versions/3.6.15/bin/python

$ pip --version
pip 21.3.1 from /home/iptv/.local/lib/python3.6/site-packages/pip (python 3.6)

$ python -m pip --version
Segmentation fault (core dumped)
```

I can't find any core file in my machine.

**Comment by native-api** [comment]
Duplicate of https://github.com/pyenv/pyenv/issues/2141

**Comment by jteppinette** [comment]
I resolved this on Pop!_OS / Ubuntu 21.10 by installing with clang:

```sh
$ sudo apt install clang -y
$ CC=clang pyenv install 3.6.15
```

**Comment by alerodrom** [comment]
> I resolved this on Pop!_OS / Ubuntu 21.10 by installing with clang:
> 
> ```shell
> $ sudo apt install clang -y
> $ CC=clang pyenv install 3.6.15
> ```

Thanks @jteppinette! This work in Ubuntu 22.04 and python 3.5.4.

**Comment by remanifest** [comment]
> I resolved this on Pop!_OS / Ubuntu 21.10 by installing with clang:
> 
> ```shell
> $ sudo apt install clang -y
> $ CC=clang pyenv install 3.6.15
> ```

Thank you. This also worked on Arch Linux.

**Comment by asr** [comment]
> I resolved this on Pop!_OS / Ubuntu 21.10 by installing with clang:
> 
> ```shell
> $ sudo apt install clang -y
> $ CC=clang pyenv install 3.6.15
> ```

Thank you! I needed to follow these [instrucctions](https://github.com/pyenv/pyenv/issues/945#issuecomment-695777331) before the above instructions for installing Python 3.2.6 on Ubuntu 22.04.1.

**Comment by drizzle-mizzle** [comment]
> I resolved this on Pop!_OS / Ubuntu 21.10 by installing with clang:
> 
> ```shell
> $ sudo apt install clang -y
> $ CC=clang pyenv install 3.6.15
> ```
@jteppinette 
Why does it actually work this way?...😶
Big thanks, anyway

**Comment by skoenig** [comment]
> ```shell
> $ sudo apt install clang -y
> $ CC=clang pyenv install 3.6.15
> ```

Works here on a Debian 12 (bookwork) for Python 3.6.5 too.

**Comment by odravison** [comment]
Worked flawlessly here on Ubuntu 24.04 (Noble)

![image](https://github.com/user-attachments/assets/ec961c29-c777-4358-8db1-67e43d9452b0)

**Comment by carl3** [comment]
I found this fix elsewhere and worked for me:
$ sudo apt install gcc-10
$ CC=gcc-10 pyenv install 3.6.15
