### ISSUE TITLE
Allow creating hooks for e.g. installing a new python version to be able to automatically add common packages

### ISSUE THREAD

**Issue by Martmists-GH** [pyenv/pyenv#2242]
I often use pyenv for quickly testing things on different versions, however I find myself reinstalling common packages very often. Ideally these would be installed by default, but not every user would want that. Hence I suggest adding an env var or config or similar for hooks, for example to install packages on newly installed versions or similar.

**Comment by native-api** [comment]
There's a 3rd-party plugin, https://github.com/jawshooah/pyenv-default-packages, for that.

https://github.com/pyenv/pyenv/wiki/Plugins#community-plugins
