### ISSUE TITLE
python -m pip install does not create shims

### ISSUE THREAD

**Issue by cgarciaarano** [pyenv/pyenv#2243]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): CentOS7/CentOS8 (containerized)
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 2.2.4-1
- [x] Python version: 3.8.12, but it does happen in 3.9.7 as well
- [x] C Compiler information (e.g. gcc 7.3): gcc 4.8.5
- [x] Please attach the debug trace of the failing command as a gist: [trace.log](https://github.com/pyenv/pyenv/files/8004662/trace.log)

  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

Hi folks, we're using `pyenv` to create container images with different Python versions easily for CI, but we just spotted this problem.
When some user of the container image installs her dependencies using the [recommended way](https://docs.python.org/3/installing/index.html#basic-usage) (e.g. `python -m pip install pytest`), `pyenv` is not creating the shim for it.

Example:
```
# python -m pip install pytest
Looking in indexes: https://...
...
 
# pyenv which pytest
/pyenv-2.2.4-1/versions/3.8.12/bin/pytest
 
# which pytest
/usr/bin/which: no pytest in (/pyenv-2.2.4-1/shims:/pyenv-2.2.4-1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
 
# pytest
bash: pytest: command not found
```
This is opposed to what happens when plain `pip` is used:
```
# pip install pytest
Looking in indexes: https://...
...

# pytest --version
pytest 6.2.5
 
 
# pyenv which pytest
/pyenv-2.2.4-1/versions/3.8.12/bin/pytest
 
# which pytest
/pyenv-2.2.4-1/shims/pytest
```

Of course, running `pyenv rehash` fixes the issue, but I was wondering in there's a possibility to have a consistent behavior, either users install using `pip` directly or as module.

Checking the debug log, I guess this line is the culprit:
```
++(/pyenv-2.2.4-1/pyenv.d/exec/pip-rehash.bash:5): source(): [[ python =~ ^(pip|easy_install)[23](\.d)?$ ]]
```

PD: I can help with PR if needed, but it may delay a bit as I'm taking holidays today :sunglasses:

**Comment by native-api** [comment]
This is by design. Pyenv only does an automatic `rehash` if Pip is run via the shim. Running it after every shim invocation seems wasteful. So I'm not sure what we can do here.

Manually running `pyenv rehash` after you run Pip in any other manner is the intended way.

**Comment by native-api** [comment]
> What I can try to do is to do an automatic `rehash` only when they run `python -m pip`, not after every shim invocation. Does it make sense?

Yes, you can do that if you can parse the command line reliably. But command line syntax depends on the Python version and flavor being used...

For system Python, distribution maintainers achieve distribution-specific behaviour by patching Pip itself...

Why do your users prefer `python -m pip` to `pip` anyway? You can't really keep them in the dark about you using Pyenv forever anyway due to [the law of leaking abstractions](https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/).
