### ISSUE TITLE
Ubuntu dependencies are not checked or clearly documented

### ISSUE THREAD

**Issue by bburtin** [pyenv/pyenv#2246]
pyenv requires a number of operating system dependencies and they are not clearly documented.  When these dependencies are not installed `pyenv install` fails without clear instructions about how to solve the problem.  Ideally, `pyenv install` should check for these dependencies before attempting to download and install Python.  If that's not viable, it would really help if the OS dependencies were clearly documented, along with installation instructions for Ubuntu 20.04.3:

```bash
sudo apt install build-essential zlib1g zlib1g-dev libssl-dev libffi-dev
```

**Comment by joshfriend** [comment]
like on this page which is linked from the README? https://github.com/pyenv/pyenv/wiki

**Comment by bburtin** [comment]
Thanks for pointing this out.  Most likely I skipped past the OS dependencies because the docs used words like "suggested" and "sometimes."  I probably figured that if the build fails, it would tell me which dependency is missing.  Then I forgot about that page.

You may consider checking for unmet dependencies before attempting to install an interpreter.  But I understand that you're delegating the build to a separate project.  Chances are that it isn't easy to do.  Thanks for your continued support of this project!
