### ISSUE TITLE
Pyenv is failing to install on macOS 12.2 (python==3.x.x) C compilation error

### ISSUE THREAD

**Issue by tsmith1985** [pyenv/pyenv#2248]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): macOS 12.2
- [X] OS architecture (e.g. amd64): x86_64-apple-darwin21.3.0
- [X] pyenv version: 2.2.4
- [X] Python version: 3.8.12, 3.9.10, 3.10.0, 3.10.1, 3.10.2
- [X] C Compiler information (e.g. gcc 7.3):
```bash
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.27.3)
Target: x86_64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
- [X] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
  * [https://gist.github.com/tsmith1985/d84597526a2412d3daddb246af4b804a](https://gist.github.com/tsmith1985/d84597526a2412d3daddb246af4b804a)

**Comment by native-api** [comment]
> error: "sizeof(pid_t) is neither sizeof(int), sizeof(long) or sizeof(long long)"

Looks like the same as @cpallapolu's problem in https://github.com/pyenv/pyenv/issues/2244.
An antivirus is a likely cause.

---

> @cpallapolu From `config.log`, I see that a number of innocent-looking Configure's test programs are being killed by the system. I've no idea why that happens. All I can say this has nothing to do with Pyenv's logic.
> 
> ```
> configure:7764: ./conftest
> ./configure: line 1967: 89699 Killed: 9               ./conftest$ac_exeext
> configure:7764: $? = 137
> configure: program exited with status 137
> ```

> @cpallapolu I've got an idea -- killing random programs is something that an antivirus would do.

**Comment by cpallapolu** [comment]
> .

Yes, Once I disabled the anti virus, the installation worked fine. I had the antivirus in macOS v11(installed python v3.9.1) but never had this issue. Maybe something changed in macOS v12 that's causing this.

**Comment by Evgenus** [comment]
Holy ****, I spent almost 2 days on this
