### ISSUE TITLE
"which python" says that pyenv is being used but "python -V" still outputs the wrong version on macOS

### ISSUE THREAD

**Issue by williamtayeb** [pyenv/pyenv#2255]
### Description
- [x] Platform information: macOS Monterey Version 12.2.1
- [x] OS architecture: Apple M1 Pro
- [x] pyenv version: 2.2.4
- [x] Python version: 2.7.18 (system)

I have read through multiple issues of people experiencing a similar issue but none of their suggested solutions have worked for me so far.

- I installed pyenv through homebrew.
- `pyenv version` outputs `3.10.2 (set by /Users/tayeb/.pyenv/version)`
- `which python` outputs `/Users/tayeb/.pyenv/shims/python`

My `~/.zshrc` contains:
```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
```

I have ensured that my terminal is configured to run my shell as a login shell by executing:
```
if [[ -o login ]]; then echo "login shell"; else echo "not login shell"; fi
```
which outputs: `login shell`

- However after restarting my terminal when I execute `python -V` it still outputs `Python 2.7.18`

Does anyone have any idea what the issue is?

**Comment by native-api** [comment]
Check the results of `pyenv which <executable>` -- this shows what would run when you run a shim.

Also see if you have `python` aliased to something.

**Comment by williamtayeb** [comment]
> Check the results of `pyenv which <executable>` -- this shows what would run when you run the `<executable>` shim.
> 
> Also see if you have `python` aliased to something.

I have just checked by executing `alias` in my terminal and python is not aliased to something. Could you please explain what I would input as `<executable>`?

**Comment by williamtayeb** [comment]
I have no idea what was wrong with my previous setup but I decided to uninstall pyenv with homebrew and then reinstall it using https://github.com/pyenv/pyenv-installer and everything seems to be working smoothly now.
