### ISSUE TITLE
Python 3.10 seems to ignore system OpenSSL's crypto policy

### ISSUE THREAD

**Issue by adampinky85** [pyenv/pyenv#2257]
## Summary
Python 3.10 build recipes do not appear to be respecting the OpenSSL configuration within linux. Testing completed using Pyenv 2.2.4 on both Ubuntu 20.04.4 and Centos-8. Note PEP 644 which requires OpenSSL >= 1.1.1 is released in Python 3.10.

We operate behind a corporate proxy / firewall which causes an SSL error where the Diffie-Hellman key size is too small. In previous Python versions this is resolved by updating the OpenSSL configuration, e.g. downgrading the linux crypto policies `sudo update-crypto-policies --set LEGACY`.

The issue is reproducible in both Ubuntu 20.04.4 and Centos-8. In both linux distributions the SSL error is resolvable in earlier pyenv Python builds e.g. 3.9.10, using the system OpenSSL configurations, but the configuration is not respected with Python 3.10.2.

We raised the [issue](https://bugs.python.org/issue46863) with the core Python team and they believe the issue is likely with the build recipe. The only difference we found in build recipe is an update to the OpenSSL versions; openssl-1.1.1l (3.9.10) to openssl-1.1.1k (3.10.2). The OpenSSL release notes do not appear to suggest anything relevant.

See the details below on the Pyenv, kernel, linux distributions, and Openssl versions, many thanks in advance.

## Details

1. Python 3.10.2 Error:

(py_3_10_2) ➜  py_3_10_2 pip install --upgrade pip
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:997)'))': /simple/pip/

2. Pyenv Version

pyenv --version
pyenv 2.2.4-1-4-g1e79a522

3. Ubuntu details

uname -a
Linux Horatio 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

openssl version -a
OpenSSL 1.1.1f  31 Mar 2020
built on: Wed Nov 24 13:20:48 2021 UTC
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-dnfdFp/openssl-1.1.1f=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
Seeding source: os-specific

4. Centos-8 details

uname -a
Linux localhost.localdomain 5.4.181-1.el8.elrepo.x86_64 #1 SMP Tue Feb 22 10:00:15 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/centos-release
CentOS Stream release 8

gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10)

openssl version -a
OpenSSL 1.1.1k  FIPS 25 Mar 2021
built on: Thu Dec  2 16:40:48 2021 UTC
platform: linux-x86_64
options:  bn(64,64) md2(char) rc4(16x,int) des(int) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wa,--noexecstack -Wa,--generate-missing-build-notes=yes -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG -DPURIFY -DDEVRANDOM="\"/dev/urandom\"" -DSYSTEM_CIPHERS_FILE="/etc/crypto-policies/back-ends/openssl.config"
OPENSSLDIR: "/etc/pki/tls"
ENGINESDIR: "/usr/lib64/engines-1.1"
Seeding source: os-specific
engines:  rdrand dynamic

**Comment by native-api** [comment]
> I found the Python build recipes and Pyenv does appear to install OpenSSL from source.

You say that correctly, but if you look at that line further, you'll see that it's only actually run in MacOS.

In Linux, we don't pass any OpenSSL-related flags to the build unless Linuxbrew is present (detected by `brew` being in PATH).

So whatever OpenSSL CPython's build detects will be used.

We need full diagnostic info as required by the issue template and also `config,log` from the build to say anything more specific.

**Comment by adampinky85** [comment]
Thanks for the quick reply. I've attached the build logs for both the working 3.9.10 and the failing 3.10.2. The other details should be included above but if there is anything else please let me know. I really appreciate your help!

[python_builds.tar.gz](https://github.com/pyenv/pyenv/files/8157620/python_builds.tar.gz)

**Comment by native-api** [comment]
There are no differences at all in the logs except some additional checks in 3.10's Configure:

```diff
  checking whether compiling and linking against OpenSSL works... yes
- checking for X509_VERIFY_PARAM_set1_host in libssl... yes
+ checking for --with-openssl-rpath... 
+ checking whether OpenSSL provides required APIs... yes
  checking for --with-ssl-default-suites... python
  checking for --with-builtin-hashlib-hashes... md5,sha1,sha256,sha512,sha3,blake2

```

So whatever it is, it doesn't appear to stem from Pyenv's logic.

---

Look more closely where the erroneous connection parameters come from, that should give you a clue.
You can make a debug build with `pyenv install` (`-g`) or pass additional compiler flags to e.g. disable optimizations (`CFLAGS`/[`PYTHON_CFLAGS`](https://github.com/pyenv/pyenv/tree/master/plugins/python-build#special-environment-variables)).

**Comment by adampinky85** [comment]
Many thanks! I've updated the Python core issue report and provided more details. I'll update this issue if we make any progress.

**Comment by adampinky85** [comment]
Hi team, the Python core developers [responded ](https://bugs.python.org/issue46863) with the below. I tested the instructions against the pyenv 3.10.2 source directory and it does resolve the issue!

> "pyenv uses default value for ./configure --with-ssl-default-suites. You have to use --with-ssl-default-suites=openssl so your build uses the system's crypto policy correctly."

I'm not sure how best to update the pyenv install script but would be happy to raise a pull request with some guidance. Many thanks in advance! Pyenv is an excellent tool and we really appreciate your efforts.

Test command: `./python -c "from urllib.request import urlopen; resp = urlopen('https://www.python.org'); print(resp.code)"`

**Comment by native-api** [comment]
Yes, we don't override any configuration settings unless that's necessary to make Python work under Pyenv -- in order to give users as close to vanilla experience as possible.

If you need some nondefault configuration settings in your particular setup, you can put them into the [`PYTHON_CONFIGURE_OPTS` envvar](https://github.com/pyenv/pyenv/tree/master/plugins/python-build#special-environment-variables).

**Comment by adampinky85** [comment]
OK thanks for the help, this has resolved our issue!
