### ISSUE TITLE
Moving pyenv root

### ISSUE THREAD

**Issue by rnhmjoj** [pyenv/pyenv#226]
I moved pyenv from my home to /usr/local/ to make it system wide and changed $PYENV_ROOT. However somewhere in pyenv the old path is still used since running a shim gives:

```
$ turses
/usr/local/lib/pyenv/libexec/pyenv-exec: /usr/local/lib/pyenv/versions/2.7.8/bin/turses:
/Users/michele/.pyenv/versions/2.7.8/bin/python: bad interpreter: No such file or directory
```

Deleting shims and rehashing didn't worked.

**Comment by brennebeck** [comment]
I recently just moved my `$PYENV_ROOT` and so went through this whole process. @yyuu's solution didn't seem to fully work. I had to also use `sed` (`gsed` on macOS) to replace many of the shebangs in the bin stubs - they just never rehashed properly to the new `$PYENV_ROOT`. However, I also had to do an additional replacement for some stubs and the specific version of `python2.7` (something like this `gsed -i'.bak2' 's~/usr/local/opt/pyenv/versions/2.7.8/bin/python2.7~/Users/brennebeck/.pyenv/versions/2.7.8/bin/python2.7~' /Users/brennebeck/.pyenv/versions/2.7.8/bin/*`). Not sure why the initial sed replacement didn't cover these cases, but thought I'd add a comment here in case anyone comes across a similar issue.

**Comment by jfferson** [comment]
also seems to work creating /usr/local/pyenv as a symbolik link to ~/.pyenv

**Comment by kingdavid72** [comment]
as of 2018, pyenv is still meant to be used as a single user program. system-wide installation is not easily achievable for multiple users !.
