### ISSUE TITLE
Unable to build universal2 python for macOS intel machine

### ISSUE THREAD

**Issue by jasjuang** [pyenv/pyenv#2262]
When executing `PYTHON_CONFIGURE_OPTS="--enable-universal-archs" pyenv install 3.9.9` on a macOS intel machine, it doesn't install the universal2 python, because `file /Users/$USER/.pyenv/versions/3.9.9/bin/python3` shows only x86_64. However, it is possible to install [universal2 python](https://www.python.org/ftp/python/3.9.10/python-3.9.10-macos11.pkg) via  https://www.python.org/downloads/macos/ on a macOS intel machine. 

After investigating https://github.com/pyenv/pyenv/blob/master/plugins/python-build/bin/python-build#L2137, I realized universal2 python is only limited to Apple Silicon machines, and I am not sure why. Can we enable universal2 python on macOS intel machines as well?

**Comment by native-api** [comment]
The Configure parameter's name is `--with-universal-archs`. But you need to actuall pass `--enable-universalsdk`:

https://github.com/python/cpython/blob/v3.9.9/configure#L1510-L1516

```
  --with-universal-archs=ARCH
                          specify the kind of macOS universal binary that
                          should be created. This option is only valid when
                          --enable-universalsdk is set; options are:
                          ("universal2", "intel-64", "intel-32", "intel",
                          "32-bit", "64-bit", "3-way", or "all") see
                          Mac/README.rst
```

**Comment by native-api** [comment]
In order to cross-compile, IIRC you'd also need dependent libraries for target architecture or you'll get linking errors. I'm not sure if that's possible on an Intel machine.

**Comment by jasjuang** [comment]
Thanks, I tried `PYTHON_CONFIGURE_OPTS="--enable-universalsdk --with-universal-archs=universal2" pyenv install 3.9.9` as suggested, and it failed to install due to 

```
Undefined symbols for architecture arm64:
Undefined symbols for architecture arm64:
  "_libintl_bindtextdomain", referenced from:
  "_libintl_bindtextdomain", referenced from:
      _PyIntl_bindtextdomain in libpython3.9.a(_localemodule.o)
      _PyIntl_bindtextdomain in libpython3.9.a(_localemodule.o)
  "_libintl_dcgettext", referenced from:
  "_libintl_dcgettext", referenced from:
      _PyIntl_dcgettext in libpython3.9.a(_localemodule.o)
      _PyIntl_dcgettext in libpython3.9.a(_localemodule.o)
  "_libintl_dgettext", referenced from:
  "_libintl_dgettext", referenced from:
      _PyIntl_dgettext in libpython3.9.a(_localemodule.o)
      _PyIntl_dgettext in libpython3.9.a(_localemodule.o)
  "_libintl_gettext", referenced from:
  "_libintl_gettext", referenced from:
      _PyIntl_gettext in libpython3.9.a(_localemodule.o)
      _PyIntl_gettext in libpython3.9.a(_localemodule.o)
  "_libintl_setlocale", referenced from:
  "_libintl_setlocale", referenced from:
      _PyLocale_setlocale in libpython3.9.a(_localemodule.o)
      _PyLocale_localeconv in libpython3.9.a(_localemodule.o)
      _PyLocale_setlocale in libpython3.9.a(_localemodule.o)
      _PyLocale_localeconv in libpython3.9.a(_localemodule.o)
  "_libintl_textdomain", referenced from:
  "_libintl_textdomain", referenced from:
      _PyIntl_textdomain in libpython3.9.a(_localemodule.o)
      _PyIntl_textdomain in libpython3.9.a(_localemodule.o)
ld: symbol(s) not found for architecture arm64
ld: symbol(s) not found for architecture arm64
clang: clang: error: error: linker command failed with exit code 1 (use -v to see invocation)
```

Therefore, I installed another homebrew dedicated for arm64 libraries by 

```
cd /opt
mkdir arm-homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C arm-homebrew 
cd arm-homebrew/bin
./brew fetch --force --bottle-tag=arm64_big_sur gettext 
./brew install <where-the-arm64-gettext-is-downloaded-to-from-the-previous-command>
```

It installed successfully and if I do `file /opt/arm-homebrew/lib/libgettextlib.dylib` it shows arm64 correctly. Therefore, I tried to install pyenv again this time with `LDFLAGS="-L/opt/arm-homebrew/lib" CPPFLAGS="-I/opt/arm-homebrew/include" PYTHON_CONFIGURE_OPTS="--enable-universalsdk --with-universal-archs=universal2" pyenv install 3.9.9`, but I am still seeing the same `Undefined symbols for architecture arm64 for gettext` error. I am struggling to understand why pyenv isn't able to pick up the `LDFLAGS`, there is a very similar issue https://github.com/pyenv/pyenv/issues/1877, and it seems that pyenv is able to pick up `LDFLAGS`. I would appreciate if you can let me know why I am still seeing this error.

**Comment by native-api** [comment]
Need diagnostic info as per the issue template to say anything specific about a specific error.

**Comment by jasjuang** [comment]
I investigate the logs more carefully and the `LDFLAGS` are indeed picked up. Is there a way to specify which architecture to build in `PYTHON_CONFIGURE_OPTS`, so I can attempt to build arm64 only? I would like to narrow the problem down to further debug this.

**Comment by native-api** [comment]
AFAICT, you can pass individual archs to `--with-universal-archs`. Barring that, you can always try Autotools' stock `--host` (which accepts a triplet rather than just arch name).

**Comment by jasjuang** [comment]
I tried `LDFLAGS="-L/opt/arm-homebrew/lib" CPPFLAGS="-I/opt/arm-homebrew/include" PYTHON_CONFIGURE_OPTS="--enable-universalsdk --with-universal-archs=arm64" pyenv install 3.9.9` and I get error 
```
configure: error: proper usage is --with-universal-archs=universal2|32-bit|64-bit|all|intel|3-way
```
Can you let me know the exact command to build arm64 only on an intel macOS machine?

**Comment by native-api** [comment]
I cannot. All I can say is the triplet for Arm64 MacOS Monterey appears to be `arm-apple-darwin21.1.0`.

**Comment by native-api** [comment]
According to https://developer.apple.com/documentation/apple-silicon/porting-your-macos-apps-to-apple-silicon , Apple's toolchain expects that dependency libraries for a universal binaries should also be universal binaries -- i.e. the doc seems to imply that it does not look for symbols for different architecture in different libraries.

**Comment by jasjuang** [comment]
There doesn't seem to be a way to install a universal version of gettext from brew. I guess installing a universal python with pyenv isn't going to be straight forward. 

I wonder how python.org does it, do they build all dependencies from source and configured all of them to be universal?

**Comment by native-api** [comment]
> do they build all dependencies from source and configured all of them to be universal?

You can check https://github.com/python/cpython/blob/main/Mac/README.rst and/or ask them.

Judging by https://github.com/python/cpython/blob/main/Mac/README.rst#how-do-i-create-a-binary-distribution, that's exactly what they do.

**Comment by zebrapurring** [comment]
The problem is Homebrew does not support universal binaries (see https://github.com/orgs/Homebrew/discussions/412), so building a universal Python binary is not possible without the universal version of all its dependencies.

However, I was able to build the universal Python binary with `pyenv` by doing the following:

1. Install x86-64 and ARM64 versions of all the dependencies in separate Homebrew instances
2. Use [`lipo`](https://ss64.com/osx/lipo.html) to create universal binaries from both architectures
3. Build Python with `--enable-universalsdk --with-universal-archs=universal2`

Here's a script that prepares a universal Homebrew environment with the required dependencies:

```sh
#!/bin/sh

set -eu

BREW_ARM_PREFIX="$HOME/opt/brew.universal"
BREW_X86_PREFIX="$HOME/opt/brew.x86_64"

# Create one Homebrew clone for ARM64, and another one for x86-64
git clone https://github.com/Homebrew/brew "$BREW_ARM_PREFIX"
git clone https://github.com/Homebrew/brew "$BREW_X86_PREFIX"

# Install dependencies for both architectures
PATH="$BREW_ARM_PREFIX/bin:$PATH" arch -arm64  brew install gettext lzma ncurses openssl@1.1 readline tcl-tk xz
PATH="$BREW_X86_PREFIX/bin:$PATH" arch -x86_64 brew install gettext lzma ncurses openssl@1.1 readline tcl-tk xz

# Merge all binaries from both architectures into fat executables
cd "$BREW_ARM_PREFIX"
find ./Cellar -type f \( -name "*.a" -or -name "*.dylib" -or -perm +111 \) | while read -r f; do
    if file "$f" | grep -q "Mach-O"; then
        if [ -f "$BREW_X86_PREFIX/$f" ]; then
            lipo "$f" "$BREW_X86_PREFIX/$f" -create -output "${f}.universal"
            mv "${f}.universal" "$f"
            echo "MERGED: $f"
        else
            echo "WARNING: x86-64 binary not found: $f"
        fi
    fi
done
```

Now it is possible to build Python using the universal libraries created above:

```sh
BREW_UNIVERSAL_PREFIX="$HOME/opt/brew.universal"
export PATH="$BREW_UNIVERSAL_PREFIX/bin:$PATH"
export LDFLAGS="-L$BREW_UNIVERSAL_PREFIX/opt/gettext/lib     -L$BREW_UNIVERSAL_PREFIX/opt/ncurses/lib     -L$BREW_UNIVERSAL_PREFIX/opt/openssl@1.1/lib     -L$BREW_UNIVERSAL_PREFIX/opt/readline/lib     -L$BREW_UNIVERSAL_PREFIX/opt/tcl-tk/lib     -L$BREW_UNIVERSAL_PREFIX/opt/xz/lib"
export CFLAGS=" -I$BREW_UNIVERSAL_PREFIX/opt/gettext/include -I$BREW_UNIVERSAL_PREFIX/opt/ncurses/include -I$BREW_UNIVERSAL_PREFIX/opt/openssl@1.1/include -I$BREW_UNIVERSAL_PREFIX/opt/readline/include -I$BREW_UNIVERSAL_PREFIX/opt/tcl-tk/include -I$BREW_UNIVERSAL_PREFIX/opt/xz/include"
export CPPFLAGS="$CFLAGS"
export CXXFLAGS="$CFLAGS"
export PKG_CONFIG_PATH="$BREW_UNIVERSAL_PREFIX/opt/ncurses/lib/pkgconfig:$BREW_UNIVERSAL_PREFIX/opt/openssl@1.1/lib/pkgconfig:$BREW_UNIVERSAL_PREFIX/opt/readline/lib/pkgconfig:$BREW_UNIVERSAL_PREFIX/opt/tcl-tk/lib/pkgconfig:$BREW_UNIVERSAL_PREFIX/opt/xz/lib/pkgconfig"
PYTHON_CONFIGURE_OPTS="--enable-universalsdk --with-universal-archs=universal2" pyenv install --verbose 3.11.2
```

The newly built Python can run on both architectures:

```
$ pyenv global 3.11.2

$ python3 -c "import platform; print(platform.machine())"
arm64

$ arch -x86_64 python3 -c "import platform; print(platform.machine())"
x86_64
```

Note that `python` points to the x86-64 version of Python (universal binary with one architecture), while `python3` points to the fat binary with both architectures:

```
$ ls -l "$(dirname "$(pyenv which python3)")"
total 496
lrwxr-xr-x  1 <user>  staff      9 Apr  6 02:44 2to3 -> 2to3-3.11
-rwxr-xr-x  1 <user>  staff    130 Apr  6 02:44 2to3-3.11
lrwxr-xr-x  1 <user>  staff      8 Apr  6 02:44 idle3 -> idle3.11
-rwxr-xr-x  1 <user>  staff    128 Apr  6 02:44 idle3.11
-rwxr-xr-x  1 <user>  staff    258 Apr  6 02:44 pip3
-rwxr-xr-x  1 <user>  staff    258 Apr  6 02:44 pip3.11
lrwxr-xr-x  1 <user>  staff      9 Apr  6 02:44 pydoc3 -> pydoc3.11
-rwxr-xr-x  1 <user>  staff    113 Apr  6 02:44 pydoc3.11
lrwxr-xr-x  1 <user>  staff     18 Apr  6 02:44 python -> python3.11-intel64
lrwxr-xr-x  1 <user>  staff     10 Apr  6 02:44 python3 -> python3.11
lrwxr-xr-x  1 <user>  staff     17 Apr  6 02:44 python3-config -> python3.11-config
lrwxr-xr-x  1 <user>  staff     18 Apr  6 02:44 python3-intel64 -> python3.11-intel64
-rwxr-xr-x  1 <user>  staff  99351 Apr  6 02:44 python3.11
-rwxr-xr-x  1 <user>  staff   2072 Apr  6 02:44 python3.11-config
-rwxr-xr-x  1 <user>  staff  71225 Apr  6 02:44 python3.11-gdb.py
-rwxr-xr-x  1 <user>  staff  49784 Apr  6 02:44 python3.11-intel64

$ file "$(pyenv which python)"
/Users/<user>/.pyenv/versions/3.11.2/bin/python: Mach-O universal binary with 1 architecture: [x86_64:Mach-O 64-bit executable x86_64]
/Users/<user>/.pyenv/versions/3.11.2/bin/python (for architecture x86_64):    Mach-O 64-bit executable x86_64

$ file "$(pyenv which python3)"
/Users/<user>/.pyenv/versions/3.11.2/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/Users/<user>/.pyenv/versions/3.11.2/bin/python3 (for architecture x86_64):   Mach-O 64-bit executable x86_64
/Users/<user>/.pyenv/versions/3.11.2/bin/python3 (for architecture arm64):    Mach-O 64-bit executable arm64
```

**Comment by rtgoodwin** [comment]
This worked wonderfully to let me use an Intel-only wheel. I've saved the whole thing as "brewniversal.sh", and may this never disappear from the internet :)

**Comment by zornme** [comment]
Another happy user of [zebrapurring](https://github.com/zebrapurring)'s lovely script here. It felt prudent to note that, due to homebrew changes, you'll want to add `export HOMEBREW_NO_INSTALL_FROM_API=1` to the top of the script that prepares a universal Homebrew environment with the required dependencies. Thanks!

**Comment by DanielSchaffer** [comment]
For anyone coming back to this, `openssl@1.1` has since been disable, so you'll need to use `openssl@3` instead. Updated script including @zornme update is:

```
#!/bin/sh

set -eu

BREW_ARM_PREFIX="$HOME/opt/brew.universal"
BREW_X86_PREFIX="$HOME/opt/brew.x86_64"
export HOMEBREW_NO_INSTALL_FROM_API=1

# Create one Homebrew clone for ARM64, and another one for x86-64
git clone https://github.com/Homebrew/brew "$BREW_ARM_PREFIX"
git clone https://github.com/Homebrew/brew "$BREW_X86_PREFIX"

# Install dependencies for both architectures
PATH="$BREW_ARM_PREFIX/bin:$PATH" arch -arm64  brew install gettext ncurses openssl@3 readline tcl-tk xz
PATH="$BREW_X86_PREFIX/bin:$PATH" arch -x86_64 brew install gettext ncurses openssl@3 readline tcl-tk xz

# Merge all binaries from both architectures into fat executables
cd "$BREW_ARM_PREFIX"
find ./Cellar -type f \( -name "*.a" -or -name "*.dylib" -or -perm +111 \) | while read -r f; do
    if file "$f" | grep -q "Mach-O"; then
        if [ -f "$BREW_X86_PREFIX/$f" ]; then
            lipo "$f" "$BREW_X86_PREFIX/$f" -create -output "${f}.universal"
            mv "${f}.universal" "$f"
            echo "MERGED: $f"
        else
            echo "WARNING: x86-64 binary not found: $f"
        fi
    fi
done
```

**Comment by eduarcor** [comment]
Trying to install python 3.13.9 universal, tcl tk waits forever, skipping it is an option but not 100% functional ... Can anyone help me?

**Comment by native-api** [comment]
> tcl tk waits forever

Tcl/Tk takes quite some time to build from source. Depending on what exactly you're doing, that may be the case.

**Comment by eduarcor** [comment]
> > tcl tk waits forever
> 
> Tcl/Tk takes quite some time to build from source. Depending on what exactly you're doing, that may be the case.

The whole night? I mean, 8h +? Don't think so...

**Comment by native-api** [comment]
> The whole night? I mean, 8h +? Don't think so...

I cannot tell you anything else without any details other than suggest to increase the verbosity of whatever you're running to see what's happening.

**Comment by eduarcor** [comment]
> I cannot tell you anything else without any details other than suggest to increase the verbosity of whatever you're running to see what's happening.
If you can help me out on how I would be glad to do it. I am using the previous sh scripts (saved into a file, and run directly on terminal). Thanks

**Comment by native-api** [comment]
> I am using the previous sh scripts (saved into a file, and run directly on terminal)

If you are referring to https://github.com/pyenv/pyenv/issues/2262#issuecomment-2479635171 ,
changing `brew install` to `brew install --verbose` will show the build progress.

**Comment by native-api** [comment]
@DanielSchaffer et al

> PATH="$BREW_ARM_PREFIX/bin:$PATH" arch -arm64  brew install gettext ncurses openssl@3 readline tcl-tk xz
> PATH="$BREW_X86_PREFIX/bin:$PATH" arch -x86_64 brew install gettext ncurses openssl@3 readline tcl-tk xz

Note that Tcl/Tk 9 support in CPython is experimental as of 3.14. So you may want to instead install `tcl-tk@8`

**Comment by native-api** [comment]
It turns out, MacPorts can build its packages as universal binaries with an option switch: https://trac.macports.org/wiki/howto/buildUniversal

Since Pyenv can now use MacPorts for dependencies, this is probably the easiest way to make universal builds.
