### ISSUE TITLE
suggestion: include `git` into prerequisites install commands

### ISSUE THREAD

**Issue by x2es** [pyenv/pyenv#2275]
I suggest to add `git` to all commands in the section [Suggested build environment](https://github.com/pyenv/pyenv/wiki#suggested-build-environment). Currently `git` included only for Alpine and Solus. I have got interruption of autoinstall on LMDE (Linux Mint) due of git absence.

Git is pretty common and obvious tool for developers, but half of python community is non-programmers and/or early students. Take a look at the thread https://github.com/pyenv/pyenv/issues/2214. Part of community are experiencing difficulties despite instructions is really robust for developers. I believe it's huge impact for community when students able to start with right mindset using tools like `pyenv`/`rbenv`.

**Comment by native-api** [comment]
Agree, but Git should rather go into https://github.com/pyenv/pyenv#prerequisites.

It's not required in all cases though. It's required unless you install Pyenv through your system's package manager or if you wish to install Python from branch tips.

**Comment by x2es** [comment]
Yes, it doesn't looks like "build" dependency.
I am thinking in perspective of minimal steps using [pyenv-installer](https://github.com/pyenv/pyenv-installer). Also good to avoid spawning new tabs for side instructions. For my case it may go into https://github.com/pyenv/pyenv-installer#prerequisites also.

This way shift may be simple as https://github.com/pyenv/pyenv-installer/pull/128
