### ISSUE TITLE
Unable to install pypy3.8-7.3.8 or pypy3.9-7.3.9 on MacOS 12.3

### ISSUE THREAD

**Issue by cliebBS** [pyenv/pyenv#2278]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ x ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ x ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ x ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ x ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ x ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ x ] Platform information (e.g. Ubuntu Linux 16.04): MacOS 12.3
- [ x ] OS architecture (e.g. amd64): arm64
- [ x ] pyenv version: 2.2.5
- [ x ] Python version: 3.7.13
- [ x ] C Compiler information (e.g. gcc 7.3): Apple clang version 13.1.6 (clang-1316.0.21.2)
- [ x ] Please attach the debug trace of the failing command as a gist:
  * `pyenv install pypy3.8-7.3.8` [trace.log](https://github.com/pyenv/pyenv/files/8286316/trace.log)
  * `pyenv install pypy3.9-7.3.9` [trace.log](https://github.com/pyenv/pyenv/files/8286319/trace.log)

When trying to install either `pypy3.8-7.3.8` or `pypy3.9-7.3.8` using pyenv 2.2.5 on MacOS 12.3 installed via HomeBrew, I get the following error:

```bash
/opt/homebrew/Cellar/pyenv/2.2.5/plugins/python-build/bin/../share/python-build/pypy3.9-7.3.8: line 78: pd: readonly variable
/opt/homebrew/Cellar/pyenv/2.2.5/plugins/python-build/bin/../share/python-build/pypy3.9-7.3.8: line 81: : command not found

BUILD FAILED (OS X 12.3 using python-build 20180424)
```

**Comment by gtmtg** [comment]
Fwiw, experiencing the same issue - why was this closed?

**Comment by mjpieters** [comment]
> Fwiw, experiencing the same issue - why was this closed?

Because it was fixed by a commit; you can either use the development version of pyenv or wait for a new release, or apply the fix in the [linked commit](https://github.com/pyenv/pyenv/commit/bfe54c94598d67a24b961203428e9887833004f3), locally.

**Comment by lucaswiman** [comment]
This can also be fixed by upgrading bash with brew FWIW.
