### ISSUE TITLE
Unable to build _ctypes and _decimal for 3.7.13 on MacOS arm64

### ISSUE THREAD

**Issue by cliebBS** [pyenv/pyenv#2279]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ x ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ x ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ x ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ x ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ x ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ x ] Platform information (e.g. Ubuntu Linux 16.04): MacOS 12.3
- [ x ] OS architecture (e.g. amd64): arm64
- [ x ] pyenv version: 2.2.5
- [ x ] Python version: 3.7.13
- [ x ] C Compiler information (e.g. gcc 7.3): Apple clang version 13.1.6 (clang-1316.0.21.2)
- [ ] Please attach the debug trace of the failing command as a gist:
  * `pyenv install -vv 3.7.13` (build log was 1.4MB, which appears to be too big for GitHub, so I uploaded the part that shows the failure) 
[build.log](https://github.com/pyenv/pyenv/files/8287193/build.log)

Looking at the `patches` directory, it appears that the patches that were added to get 3.7.12 to compile for M1 did not get ported for 3.7.13.

**Comment by native-api** [comment]
Fixed in https://github.com/pyenv/pyenv/commit/a43631d7c0182abab80bd3fbb51fca39644e51f8
