### ISSUE TITLE
No `shell` command in Mac OS.

### ISSUE THREAD

**Issue by allomov** [pyenv/pyenv#228]
Hi. 

I've installed `pyenv` with brew and it really have potential to solve all my problems with python versions on mac. Here is the version of pyenv:

```
→ pyenv --version
pyenv 20140705
```

The problem is when I try to use `shell` command it says there is no such: 

```
→ pyenv shell
pyenv: no such command `shell'
```

Still I can see `shell` command in the list of commands. 

Thank you, 
Alex L.

**Comment by SSUHan** [comment]
thank you, U save my times

**Comment by DearX-dlx** [comment]
In shell window input
`eval "$(pyenv init -)";`
it work for me

**Comment by Dandutra** [comment]
Thank you
