### ISSUE TITLE
Installing python 3.10.3 fails on macOS Monterey 12.3: "Killed: 9 CC='clang'"

### ISSUE THREAD

**Issue by gedankenexperimenter** [pyenv/pyenv#2289]
On one M1 MacBook I have, pyenv is failing to install any version of python.  The error doesn't give me much idea of what the problem is, unfortunately:
```
/bin/sh: line 1: 77877 Killed: 9               CC='clang' LDSHARED='clang -bundle -undefined dynamic_lookup -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/readline/lib -L/Users/merlin/.pyenv/versions/3.10.3/lib -L/opt/homebrew/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/readline/lib -L/Users/merlin/.pyenv/versions/3.10.3/lib -L/opt/homebrew/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib  ' OPT='-DNDEBUG -g -fwrapv -O3 -Wall' _TCLTK_INCLUDES='' _TCLTK_LIBS='' ./python.exe -E ./setup.py $quiet build
make: *** [sharedmods] Error 137
```

I've tried several different versions of python 3.9 and 3.10, all with no luck.  This problem seemed to begin when I got a report from the OS, seemingly out of the blue, that python had crashed.  Prior to that, I had several versions of python installed from pyenv (including 3.10.2), all working just fine, as well as a couple of python versions installed by Homebrew to satisfy dependencies.  Both the Homebrew version and the pyenv versions that had been installed now crash when running any script (e.g. `pip list`).  The system versions from Apple still work.  The problem began before I upgraded to macOS 12.3, but it persisted after that.

I've tried this out on a similar MacBook, and that one works fine: installing python 3.10.3 succeeds, and scripts run without issue.  It's possible that this is related to the fact that I had installed the homebrew version of llvm so that I could run include-what-you-use a week or so ago, and had that version of `clang` first in my path, but even with it purged, and using Apple's version, it still doesn't work.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): **macOS 12.3**
- [x] OS architecture (e.g. amd64): **arm64**
- [x] pyenv version: **2.2.5**
- [x] Python version: **3.10.3**
- [x] C Compiler information (e.g. gcc 7.3): **Apple clang version 13.1.6 (clang-1316.0.21.2)**
- [x] Please attach the debug trace of the failing command as a gist: [trace.log](https://gist.github.com/gedankenexperimenter/68f51b2ccb132c8692a3512781aa40d6)

**Comment by gedankenexperimenter** [comment]
I've tried `pypy3.9-7.3.8`, as well, which installs without issue.

**Comment by bsarrazin** [comment]
I am experiencing the same thing, I opened an issue here: https://github.com/danhper/asdf-python/issues/133

**Comment by bsarrazin** [comment]
@native-api I don't have any anti-virus installed as suggested in #2248 and am experiencing this exact issue, see https://github.com/danhper/asdf-python/issues/133

**Comment by native-api** [comment]
@bsarrazin Are you sure about that?.. AFAICS, MacOS has a built-in antivirus: https://www.comparitech.com/blog/information-security/if-you-have-a-mac-do-you-need-antivirus-protection/

In any case, all I can see is that the OS kills a compilation process that is building the `_decimal` module. That has nothing to do with Pyenv's logic.

```
clang -bundle -undefined dynamic_lookup -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/readline/lib -L/Users/merlin/.pyenv/versions/3.10.3/lib -L/opt/homebrew/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/readline/lib -L/Users/merlin/.pyenv/versions/3.10.3/lib -L/opt/homebrew/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/readline/lib -L/Users/merlin/.pyenv/versions/3.10.3/lib -L/opt/homebrew/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/readline/include -I/Users/merlin/.pyenv/versions/3.10.3/include -I/opt/homebrew/include build/temp.macosx-12.3-arm64-3.10/private/var/folders/v7/0pgsjbss4cb1_y5_jbkybjs40000gn/T/python-build.20220323093000.56282/Python-3.10.3/Modules/_decimal/_decimal.o build/temp.macosx-12.3-arm64-3.10/private/var/folders/v7/0pgsjbss4cb1_y5_jbkybjs40000gn/T/python-build.20220323093000.56282/Python-3.10.3/Modules/_decimal/libmpdec/basearith.o build/temp.macosx-12.3-arm64-3.10/private/var/folders/v7/0pgsjbss4cb1_y5_jbkybjs40000gn/T/python-build.20220323093000.56282/Python-3.10.3/Modules/_decimal/libmpdec/constants.o build/temp.macosx-12.3-arm64-3.10/private/var/folders/v7/0pgsjbss4cb1_y5_jbkybjs40000gn/T/python-build.20220323093000.56282/Python-3.10.3/Modules/_decimal/libmpdec/context.o build/temp.macosx-12.3-arm64-3.10/private/var/folders/v7/0pgsjbss4cb1_y5_jbkybjs40000gn/T/python-build.20220323093000.56282/Python-3.10.3/Modules/_decimal/libmpdec/convolute.o build/temp.macosx-12.3-arm64-3.10/private/var/folders/v7/0pgsjbss4cb1_y5_jbkybjs40000gn/T/python-build.20220323093000.56282/Python-3.10.3/Modules/_decimal/libmpdec/crt.o build/temp.macosx-12.3-arm64-3.10/private/var/folders/v7/0pgsjbss4cb1_y5_jbkybjs40000gn/T/python-build.20220323093000.56282/Python-3.10.3/Modules/_decimal/libmpdec/difradix2.o build/temp.macosx-12.3-arm64-3.10/private/var/folders/v7/0pgsjbss4cb1_y5_jbkybjs40000gn/T/python-build.20220323093000.56282/Python-3.10.3/Modules/_decimal/libmpdec/fnt.o build/temp.macosx-12.3-arm64-3.10/private/var/folders/v7/0pgsjbss4cb1_y5_jbkybjs40000gn/T/python-build.20220323093000.56282/Python-3.10.3/Modules/_decimal/libmpdec/fourstep.o build/temp.macosx-12.3-arm64-3.10/private/var/folders/v7/0pgsjbss4cb1_y5_jbkybjs40000gn/T/python-build.20220323093000.56282/Python-3.10.3/Modules/_decimal/libmpdec/io.o build/temp.macosx-12.3-arm64-3.10/private/var/folders/v7/0pgsjbss4cb1_y5_jbkybjs40000gn/T/python-build.20220323093000.56282/Python-3.10.3/Modules/_decimal/libmpdec/mpalloc.o build/temp.macosx-12.3-arm64-3.10/private/var/folders/v7/0pgsjbss4cb1_y5_jbkybjs40000gn/T/python-build.20220323093000.56282/Python-3.10.3/Modules/_decimal/libmpdec/mpdecimal.o build/temp.macosx-12.3-arm64-3.10/private/var/folders/v7/0pgsjbss4cb1_y5_jbkybjs40000gn/T/python-build.20220323093000.56282/Python-3.10.3/Modules/_decimal/libmpdec/numbertheory.o build/temp.macosx-12.3-arm64-3.10/private/var/folders/v7/0pgsjbss4cb1_y5_jbkybjs40000gn/T/python-build.20220323093000.56282/Python-3.10.3/Modules/_decimal/libmpdec/sixstep.o build/temp.macosx-12.3-arm64-3.10/private/var/folders/v7/0pgsjbss4cb1_y5_jbkybjs40000gn/T/python-build.20220323093000.56282/Python-3.10.3/Modules/_decimal/libmpdec/transpose.o -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -L/usr/local/lib -lm -o build/lib.macosx-12.3-arm64-3.10/_decimal.cpython-310-darwin.so
<...>
/bin/sh: line 1: 66834 Killed: 9               CC='clang' LDSHARED='clang -bundle -undefined dynamic_lookup -L/opt/homebrew/opt/readline/lib -L/opt/homebrew
```

**Comment by native-api** [comment]
https://apple.stackexchange.com/questions/329532/where-does-gatekeeper-xprotect-log-to

**Comment by gedankenexperimenter** [comment]
For the record, my machine was also not running any third-party anti-virus software, but I believe the explanation to be essentially correct.  There were other things being effected, not just python builds (e.g. rsync would also be killed immediately).  I solved the problem by taking the rather drastic step of uninstalling Homebrew completely (with all of its packages) and reinstalling from scratch.

**Comment by bsarrazin** [comment]
@native-api @gedankenexperimenter I can confirm that uninstalling/reinstalling homebrew (+ asdf) fixed the issue. I was able to install the latest.

Not sure what this means exactly, but maybe someone seeing this issue in the future can try the same thing. Thanks for the help!
