### ISSUE TITLE
pyenv failed to install python in Ubuntu 22.02

### ISSUE THREAD

**Issue by sudoyang** [pyenv/pyenv#2293]
### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 22.04
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 2.2.5-4-g986fe1a7
- [x] Python version: 3.8.9
- [x] C Compiler information (e.g. gcc 7.3): 11.2.0 (Ubuntu 11.2.0-18ubuntu1)
- [x] Please attach the debug trace of the failing command as a gist:
  trace.log file is listed as
[trace.log](https://github.com/pyenv/pyenv/files/8338475/trace.log)

My feeling is that the issue is related with libffi-dev version. When I tried to install 3.9.9 and 3.10.0, the same issue happened.

➜  ~ pyenv install 3.10.0 
Downloading Python-3.10.0.tar.xz...
-> https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tar.xz
Installing Python-3.10.0...
patching file aclocal.m4
patching file configure
Hunk #5 succeeded at 10537 (offset -15 lines).
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems

BUILD FAILED (Ubuntu 22.04 using python-build 2.2.5-4-g986fe1a7)

Inspect or clean up the working tree at /tmp/python-build.20220324124542.205859
Results logged to /tmp/python-build.20220324124542.205859.log

Last 10 log lines:
Installing collected packages: setuptools, pip
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/phy/.pyenv/versions/3.10.0/include/python3.10/setuptools
  sysconfig: /tmp/python-build.20220324124542.205859/Python-3.10.0/Include/setuptools
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/phy/.pyenv/versions/3.10.0/include/python3.10/pip
  sysconfig: /tmp/python-build.20220324124542.205859/Python-3.10.0/Include/pip
  WARNING: The scripts pip3 and pip3.10 are installed in '/home/phy/.pyenv/versions/3.10.0/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-21.2.3 setuptools-57.4.0

**Comment by native-api** [comment]
Looks like you don't have the Python build prerequisites installed. See the README.

**Comment by dycw** [comment]
I'm encountering this on Ubuntu 22.04 LTS (I presume issue has an erroneous title; OP is talking about 22.04 too).

The same script of mine which has worked fine for me since 20.04 LTS:

```bash
  # https://bit.ly/3EU10yZ
  sudo apt-get update -y
  sudo apt-get install -y \
    make \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    curl \
    llvm \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libxml2-dev \
    libxmlsec1-dev \
    libffi-dev \
    liblzma-dev
   
  # https://bit.ly/3LbZ9HQ
  curl https://pyenv.run | bash
  pyenv install 3.10.4  # latest
```

I get back

```
✦ ❯ pyenv install 3.10.4
Downloading Python-3.10.4.tar.xz...
-> https://www.python.org/ftp/python/3.10.4/Python-3.10.4.tar.xz
Installing Python-3.10.4...
python-build: use readline from homebrew
python-build: use zlib from homebrew
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (Ubuntu 22.04 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20220423140129.326054
Results logged to /tmp/python-build.20220423140129.326054.log

Last 10 log lines:
         ./python -E -m ensurepip \
                $ensurepip --root=/ ; \
fi
Looking in links: /tmp/tmp_wa5l3j6
Processing /tmp/tmp_wa5l3j6/setuptools-58.1.0-py3-none-any.whl
Processing /tmp/tmp_wa5l3j6/pip-22.0.4-py3-none-any.whl
Installing collected packages: setuptools, pip

  WARNING: The scripts pip3 and pip3.10 are installed in '/home/derek/.pyenv/versions/3.10.4/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-22.0.4 setuptools-58.1.0
```

Attached log file:
[python-build.20220423140129.326054.log](https://github.com/pyenv/pyenv/files/8546362/python-build.20220423140129.326054.log)

Any ideas?

**Comment by nikolaiam** [comment]
Same issue here, with Ubuntu 22.04 and all the Python build prerequisites mentioned in the README installed. Did anyone solve this issue?

**Comment by nikolaiam** [comment]
Same problem here, with Ubuntu 22.04 and all the Python build prerequisites in the README installed. Did anyone solve this?

**Comment by native-api** [comment]
@dycw , your case is a duplicate of https://github.com/pyenv/pyenv/issues/1479

**Comment by nikolaiam** [comment]
Thank you @dycw and @native-api! I tried setting the `LDFLAGS` variable as in #1479 but that was still unsuccessful for me. The alias @dycw suggested was successful:
```
alias pyenv-install-with-brew='CC="$(brew --prefix gcc)/bin/gcc-11" pyenv install'
```

**Comment by kitos9112** [comment]
Wondering why this common issue is not documented here https://github.com/pyenv/pyenv/wiki/common-build-problems

I had to use gcc-12 to install python 3.9.13, but this thread helped me a lot. Thanks!

```sh
alias pyenv-install-with-brew='CC="$(brew --prefix gcc)/bin/gcc-12" pyenv install'
```

**Comment by kc-sn** [comment]
is there a fix for this that doesn't involve using brew on linux?

**Comment by devacharan** [comment]
> Wondering why this common issue is not documented here https://github.com/pyenv/pyenv/wiki/common-build-problems
> 
> I had to use gcc-12 to install python 3.9.13, but this thread helped me a lot. Thanks!
> 
> ```shell
> alias pyenv-install-with-brew='CC="$(brew --prefix gcc)/bin/gcc-12" pyenv install'
> ```

hello, 

where incorporate this alias command ?

**Comment by kitos9112** [comment]
@devacharan 

The alias is a shell capability to tailor your user experience by executing larger or complex commands that are more difficult to remember.

I normally place them in my ~/.basrh or ~/.zshrc files.

**Comment by devacharan** [comment]
> @devacharan
> 
> The alias is a shell capability to tailor your user experience by executing larger or complex commands that are more difficult to remember.
> 
> I normally place them in my ~/.basrh or ~/.zshrc files.

thanks a lot @kitos9112

**Comment by BuddhiAbeyratne** [comment]
This issue shows up on Arm CPUs and Brew doesn't support arm outside of apple silicon 
any ideas ?

**Comment by native-api** [comment]
There's a mix of different issues in this topic. Looks like I'll have to delete it for it to stop confusing people.

**Comment by native-api** [comment]
"missing GNU readline, OpenSSL" is a rather generic effect and can be for many reasons. Look for any more specific errors in the build log and if they've been reported before. If not, create new issues and provide the necessary diagnostic information.
