### ISSUE TITLE
`--enable-shared` should be default

### ISSUE THREAD

**Issue by rickmark** [pyenv/pyenv#2294]
# Summary

Because `pyenv` is used by developers, and because adding shared requires removal and re-installation (a timely and potentially breaking process) shared library (which is only a small addition to the static lib) should be on by default.

Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

**Comment by native-api** [comment]
We don't override the defaults in order to provide users with as close to vanilla experience as practical, in order to minimize the possible surprises. Do you have any evidence that shows that `--enable-shared` is the configuration that users expect by default? AFAICS from https://github.com/python/cpython/blob/12c0012cf97d21bc637056983ede0eaf4c0d9c33/configure.ac#L1224-L1237, CPython only builds with `--enable-shared` by default in Cygwin -- hardly the most common use case.

If you need custom configuration switches in every installation, you can put them into the `PYTHON_CONFIGURE_OPTS` envvar.

**Comment by native-api** [comment]
Good, but that seems to be Homebrew's local decision -- and outside their main platform to boot.

Is there anything closer to the roots? E.g. previously, [a user reported that SQLite extensions are enabled by default in the official Python Docker image](https://github.com/pyenv/pyenv/issues/1702). That was good enough for me :slightly_smiling_face:

**Comment by rickmark** [comment]
Maybe this should be kicked up to python itself?  It seems silly that if you install their package from the internet you get the Dylib / framework but when building from source you do not?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by native-api** [comment]
@rickmark whatever floats your boat. As I've written earlier, we'd like to see some evidence that shows that `--enable-shared` is the expected default -- so that the change would look like a logical and expected step rather than forcing an arbitrary personal choice onto everyone.

**Comment by NyaMisty** [comment]
@native-api 
it's really a shame of you not knowing python are mostly being built with shared library and keeps 
asking others to say the "root evidence".

- There are obvious evidence available on all platforms one can use (Linux/Windows/Mac):
  - Almost all Linux distributions have packages using Python interpreter as dependency (like gdb). They are all using libpython3.X.so.1.0 (usually provided by libpython3.X pacakge). 
  - Python on Windows are always shipped with `Python3.DLL`
  - On macOS, the OS-bundled Python ships `/usr/lib/libpython.dylib`

- Just in case you are still asking for "root evidence": 
  - Debian (and actually Ubuntu) always builds shared library: https://salsa.debian.org/cpython-team/python3/-/blob/python3.10/debian/rules#L462
  (in this file `stamps/stamp-configure-shared` is depended by `stamps/stamp-build-shared`, `stamps/stamp-build`, `build-arch` and `build`)

- Lastly, There's no point to use so-called "vanilla experience", just like you will usually never use "vanilla sh/bash". You should know Python is no longer a small package. Just like Linux kernel, no one builds a big system with fully-default configuration.

**Comment by Czaki** [comment]
The main adavnate is that many python packages require to have access to shared lib to build properly. In the case of system-provided python, one just install one additional package, and its works. 

in the case of pyenv one needs to reinstall the environment in place, and if fails then brokes every virtualenvs already set up. 

Most people on Linux use python from the package manager, not python.org. So default configuration should be what is most commonly shipped with the systems, not installers from python.org. 

At this moment I do not have access to log, but in my case, if I forgot to force enable-shared on setup python it takes me up to two months to hit the situation when I need to reinstall python as some package does not provide wheel and requires shared object during compilation.

**Comment by pan3793** [comment]
+1 for `--enable-shared` in default, just struggled overnight when installing https://github.com/ninia/jep and eventually find this is the root cause.

**Comment by CastixGitHub** [comment]
it is also default in official docker python image
https://github.com/docker-library/python/blob/c0dc77e/3.11/alpine3.17/Dockerfile#L77

**Comment by the-moog** [comment]
I've written a [gist](https://gist.github.com/the-moog/f2aa5d6ea5f77c1e07d67bd7b7f7f8e2) as I had a requirement for .SO on a particular env and also needed SSL which is newer than the one in my OS.
Feel free to consider including this in the distribution on on the wiki/examples.
Currently it's just a file you put into `$(pyenv root)/pyenv.d/install` and edit as required. 

Perhaps I should continue to develop it as some sort of plugin?
That way users have the option of using shared or not, by simply including the gist for a given version.

I've just added a comment with a suggestion to extend the way config options are passed that would make this add-on very powerful.

**Comment by anton-petrov** [comment]
@the-moog You did a great job - it would be good if you could make your code into a plugin and create a PR based on it.
