### ISSUE TITLE
pynev shell boot up messages in Ubuntu

### ISSUE THREAD

**Issue by Trid-collab** [pyenv/pyenv#2297]
I have installed pyenv on Ubuntu 20.04 using Homebrew 
I have also configured my shell using the instruction mentioned in the site 

```# the sed invocation inserts the lines at the start of the file
# after any initial comment lines
sed -Ei -e '/^([^#]|$)/ {a \
export PYENV_ROOT="$HOME/.pyenv"
a \
export PATH="$PYENV_ROOT/bin:$PATH"
a \
' -e ':a' -e '$!{n;ba};}' ~/.profile
echo 'eval "$(pyenv init --path)"' >>~/.profile

echo 'eval "$(pyenv init -)"' >> ~/.bashrc

```

but I find that when I rebooting my shell I am getting messages like 

```
Command 'pyenv' not found, did you mean:

  command 'pyvenv' from deb python3-venv (3.8.2-0ubuntu2)
  command 'p7env' from deb libnss3-tools (2:3.49.1-1ubuntu1.6)

Try: sudo apt install <deb name>
```
though pyenv seems to working. I am able to install new versions of python.
Is there some mistake I am doing

**Comment by native-api** [comment]
You need to log out of your login session, not just "reboot the shell".

**Comment by Trid-collab** [comment]
I didn't quite follow. My Ubuntu installation is on WSL  and start wsl it starts Ubuntu and logs me in my user login. So even if I log out the problem still persists when I relogon

**Comment by native-api** [comment]
I don't have WSL so can't check how it does its shell initialization. Does it ever execute `~/.profile`?

**Comment by RFRIEDM-Trimble** [comment]
Instead of logging out, you can just run this right after you echo'd the stuff to your `.bashrc` & `.profile`
`su - $USER`

**Comment by Trid-collab** [comment]
The issue has been fixed. I had installed Pyenv my WSL Ubuntu using Homebrew. It was an issue configuring Homebrew with my bash.
