### ISSUE TITLE
pyenv shows the version has changed, but in fact it doesn't.（in ArchLinux）

### ISSUE THREAD

**Issue by zdx-alex** [pyenv/pyenv#2299]
### Description
- [x] Platform information (ArchLinux):
- [x] OS architecture (amd64):
- [x] pyenv version: 2.2.5-9-g72757562
- [x] Python version: 3.8.12
- [x] C Compiler information (gcc 11.2.0): 
- [x] Please attach the debug trace of the failing command as a gist: not that kinds of bug

I followed the steps to install pyenv, the .zshrc:（and I have typed source .zshrc）
![image](https://user-images.githubusercontent.com/49095300/160060890-bcaf503c-2218-4882-a8ef-068731141ce5.png)
and it does running:
![image](https://user-images.githubusercontent.com/49095300/160060973-91fcd02d-5e82-41cf-ac74-164a4b4a550b.png)
and I try to set global version of python:
![image](https://user-images.githubusercontent.com/49095300/160061068-249b5a51-0c43-4497-a82a-d22239e90cab.png)
and pyenv shows it does changed:
![image](https://user-images.githubusercontent.com/49095300/160061113-3c8e309e-3630-402a-af54-91d5f70314e0.png)
however, when I check python --version:
![image](https://user-images.githubusercontent.com/49095300/160061189-ff222a8d-99a5-4688-ad71-82ae1f107032.png)

So, could anyone please tell me what should I do to fix this problem..

**Comment by native-api** [comment]
As per the README, you need to also execute `eval "$(pyenv init --path)"` in your login shell's configuration file. (GUI frontends in Linux typically act as a `sh` login shell so their configuration file is `~/.profile`).

**Comment by native-api** [comment]
That requirement has proven to be too much of a burden for users so we're considering lifting it in https://github.com/pyenv/pyenv/issues/2085.

**Comment by zdx-alex** [comment]
> 

Oh God, how blind and careless is me. Thank you! I'll try it tomorrow!

**Comment by zdx-alex** [comment]
> As per the README, you need to also execute `eval "$(pyenv init --path)"` in your login shell's configuration file. (GUI frontends in Linux typically act as a `sh` login shell so their configuration file is `~/.profile`).

It works, thank you so much, may be next time, make these configuration about .zshrc to be a configure.sh ?
