### ISSUE TITLE
pyenv 2.2.5 BUILD FAILED

### ISSUE THREAD

**Issue by chhabrasherry** [pyenv/pyenv#2305]
pyenv version: 2.2.5
trying to install python 3.9.11
MacOS 12.2.1 Monterey
gcc --version
Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: x86_64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
NOTE: I tried reinstalling the developer tools, brew, gcc and pyenv. None of them worked. The installation still shows an error

bash-3.2$ pyenv install 3.9.11
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.9.11.tar.xz...
-> https://www.python.org/ftp/python/3.9.11/Python-3.9.11.tar.xz
Installing Python-3.9.11...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 12.2.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/w_/czsq26kj24l2crx6cmvhpfjr0000gn/T/python-build.20220331090044.10739
Results logged to /var/folders/w_/czsq26kj24l2crx6cmvhpfjr0000gn/T/python-build.20220331090044.10739.log

Last 10 log lines:
checking for python3... python3
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... "darwin"
checking for gcc... /usr/local/bin/gcc-11
checking whether the C compiler works... no
configure: error: in `/var/folders/w_/czsq26kj24l2crx6cmvhpfjr0000gn/T/python-build.20220331090044.10739/Python-3.9.11':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/issues/2201

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/issues/2201#issuecomment-1000901947:

> ```
> checking whether the C compiler works... no
> configure: error: in `/var/folders/vf/5gbwjkvs3xd530xjyj34_znw0000gn/T/python-build.20211224133338.82421/Python-3.8.6':
> configure: error: C compiler cannot create executables
> See `config.log' for more details
> ```
> 
> See `config.log` in the build tree to see what exact error happened. This usually means that you have broken compiler flag envvars or a broken compiler setup.
