### ISSUE TITLE
Failed to install 3.6.15 with Xcode 13.3

### ISSUE THREAD

**Issue by ThomasHezard** [pyenv/pyenv#2307]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
* [x] Make sure your problem is not derived from plugins.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): _**macOS 12.3**_
- [x] OS architecture (e.g. amd64): _**x86_64**_
- [x] pyenv version: _**2.2.5**_
- [x] Python version: _**3.6.15**_
- [x] C Compiler information (e.g. gcc 7.3): _**Apple clang version 13.1.6 (clang-1316.0.21.2)**_
- [x] Please attach the debug trace of the failing command as a gist:
    - [trace_3-6-15.log](https://github.com/pyenv/pyenv/files/8396486/trace_3-6-15.log)

### Additional info
- Problem appeared with Xcode 13.3, no issues with Xcode 12.2.1.
- Reproduced on macOS 12.2.1 X86_64
- Tried all the flags (openssl, readline, zlib etc.) mentionned in [common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems) => nothing worked
- Tried using gcc instead of clang as mentionned [here](https://github.com/pyenv/pyenv/issues/2143#issuecomment-1069223994) => not the same errors but not working either.
- I initially had the problem with 3.7.12 and 3.8.12, but updating to 3.7.13 and 3.8.13 solved the issue. However, I don't find any solution for Python 3.6.z.

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/pull/2288 claims to have fixed the issue for 3.6.15. Update to the head version to get it.

**Comment by ThomasHezard** [comment]
- I confirm that 3.6.15 is installing properly on [current HEAD version](https://github.com/pyenv/pyenv/commit/f0f2cdd1c6b3b272168b508610cfbbe0ccef8ea5) for both macOS 12.2.1 and macOS 12.3 (x86_64, did not test ARM) with Xcode 13.3 👌     
- Python 3.7.12 is also fixed (on the same configs), but 3.8.12 still fails to install.

Any idea of the next release calendar?

**Comment by native-api** [comment]
We make releases about once a month.

**Comment by ThomasHezard** [comment]
3.8.12 is clearly not critical for me, updating to 3.8.13 was a perfectly acceptable solution for my use-case (building wheels for multiple Python versions on macOS).    

I'll sure check the CONTRIBUTING document and try it next time I need a fix 🙂
