### ISSUE TITLE
Unable to install 3.7.9 using pyenv 2.2.5 on MacOS Monterey 12.3.1: "error: internal configure error for the platform triplet, please file a bug report"

### ISSUE THREAD

**Issue by ebarrios20** [pyenv/pyenv#2312]
`      System Version: macOS 12.3.1 (21E258)`
 `     Kernel Version: Darwin 21.4.0`
   `   Boot Volume: Macintosh HD`
    `  Boot Mode: Normal`
   `   Computer Name: MacBookPro 11.3.1`

I tried to follow other similar issues such as https://github.com/pyenv/pyenv/issues/2171 and https://github.com/pyenv/pyenv/wiki/Common-build-problems. However, I was unable to fix this problem. 

```
$pyenv install 3.7.9
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Installing Python-3.7.9...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 12.3.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/1p/9xg_6rvx2hg740d3kpqsw__c0000gp/T/python-build.20220404101916.21756
Results logged to /var/folders/1p/9xg_6rvx2hg740d3kpqsw__c0000gp/T/python-build.20220404101916.21756.log

Last 10 log lines:
checking for --with-cxx-main=<compiler>... no
checking for clang++... no
configure:

  By default, distutils will build C++ extension modules with "clang++".
  If this is not intended, then set CXX on the configure command line.
  
checking for the platform triplet based on compiler characteristics... darwin
configure: error: internal configure error for the platform triplet, please file a bug report
make: *** No targets specified and no makefile found.  Stop.
```
---

`$ pyenv doctor` command returns: "Congratulations! You are ready to build pythons!" Only when I include the openssl prefixes. 

` CFLAGS="-I$(brew --prefix openssl)/include"`
` LDFLAGS="-L$(brew --prefix openssl)/lib"`

Otherwise, I get the following error 
```
$ pyenv doctor 
Cloning /Users/estebanbarrios/.pyenv/plugins/pyenv-doctor/bin/.....
Installing python-pyenv-doctor...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 12.3.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/1p/9xg_6rvx2hg740d3kpqsw__c0000gp/T/python-build.20220404102440.25262
Results logged to /var/folders/1p/9xg_6rvx2hg740d3kpqsw__c0000gp/T/python-build.20220404102440.25262.log

Last 10 log lines:
checking readline/readline.h, presence... no
checking for readline/readline.h,... no
checking readline/rlconf.h usability... yes
checking readline/rlconf.h presence... yes
checking for readline/rlconf.h... yes
checking for SSL_library_init in -lssl... no
configure: WARNING: OpenSSL <1.1 not installed. Checking v1.1 or beyond...
checking for OPENSSL_init_ssl in -lssl... no
configure: error: OpenSSL is not installed.
make: *** No targets specified and no makefile found.  Stop.
Problem(s) detected while checking system.

See https://github.com/pyenv/pyenv/wiki/Common-build-problems for known solutions.
```
---

I have also updated my XCode SDK to 13.3 from https://developer.apple.com/download/all/?q=Xcode by following https://github.com/pyenv/pyenv/issues/2201#issuecomment-1001597344. 
`softwareupdate --all --install --force`
`sudo rm -rf /Library/Developer/CommandLineTools`
`sudo xcode-select --install`

--- 
Here is my config log.
[config.log](https://github.com/pyenv/pyenv/files/8411938/config.log)

**Comment by native-api** [comment]
Upgrade to 3.7.13 or provide a PR backporting the below-mentioned patch to the version you're interested in.

We can backport it ourselves, that's not too hard... but how far back do we need to go?

---

https://github.com/pyenv/pyenv/issues/2143#issuecomment-1072032647

> Closing as per [#2143 (comment)](https://github.com/pyenv/pyenv/issues/2143#issuecomment-1070640288):
> 
> > I can confirm yesterday's releases 3.7.13, 3.8.13, 3.9.11 and 3.10.3 all work fine on my Intel mac. The GCC solution was not a viable one for me as it caused issues with pip modules that were built with clang. I don't think I need 3.6 or older branches at the moment but I suspect they might need manual patches via pyenv since they're EOL upstream.
> 
> **[The cause is a change in Apple Clang 13.0.0+ that made it incompatible with existing Python versions.](https://bugs.python.org/issue45405) Upgrade to the aforementioned newest Python versions to fix the issue.**
> 
> For older releases, PRs with patches backporting [python/cpython@9c47667](https://github.com/python/cpython/commit/9c4766772cda67648184f8ddba546a5fc0167f91) are welcome if someone is interested in supporting building them with that newer Clang.

**Comment by Seanstoppable** [comment]
pyenv provides the ability to apply patches, so if you really can't upgrade to 3.7.13 for some reason, you can do the following:

`pyenv install --patch 3.7.9 < <(curl -sSL https://github.com/python/cpython/commit/720bb456dc711b0776bae837d1f9a0b10c28ddf2.patch\?full_index\=1)`

**Comment by ewanjoy** [comment]
Met same issue, got it resolved by checking https://issueantenna.com/repo/pyenv/pyenv/issues/2284, https://github.com/pyenv/pyenv/issues/2143. 

> t's due to the latest Apple CLang's releases being incompatible with CPython's Configure.
Fixed in 3.7.13, 3.8.13, 3.9.11 and 3.10.3 .

As tested, 'pyenv install 3.8.13' works for me.

**Comment by ebarrios20** [comment]
Wasn't able to install 3.7.13 with `pyenv install 3.7.13`. However, I was able to install 3.7.13 and 3.7.9 using 
`CC="$(brew --prefix gcc)/bin/gcc-11" PYTHON_BUILD_HOMEBREW_OPENSSL_FORMULA="openssl@3" pyenv install 3.7.13`

**Comment by native-api** [comment]
@ebarrios20 be warned that CPython compiled with `CC="$(brew --prefix gcc)/bin/gcc-11"` is binary incompatible with the regular one -- including incompatible with stock wheels.

**Comment by PipeKnight** [comment]
Recently I had the same problem, I couldn't install any python version with Pyenv on my M1 Pro. I tried lots of hacks mentioned in issues: patches, flags, reinstalling zlib, bzip and so on, resetting xcode-command-line-tools. Nothing worked. But then my friend told me I should install the Xcode itself from App Store. And lol, that worked!

Just install Xcode and run ```pyenv install 3.7.13```
(works with all latest revisions supported by pyenv such as 3.7.13, 3.8.13, 3.9.11, 3.10.3, etc.)

**Comment by pkfec** [comment]
I ran into same exact problem with masOS Monterey v12.3.1. I followed the steps below before installing python with pyenv.

1. uninstall xcode:  `sudo rm -rf /Library/Developer/CommandLineTools`
2. restart mac 
3. installed xcode: `xcode-select --install`
4. install python: `pyenv install 3.7.12`

Hope this helps!
