### ISSUE TITLE
Error install python-2.7.18

### ISSUE THREAD

**Issue by ccapudev** [pyenv/pyenv#2314]
Issue install python 2.7.18
### Setup
- Ubuntu Linux 22.04:
- amd64
- pyenv version v2.2.5 (f0f2cdd1c6b3b272168b508610cfbbe0ccef8ea5):
- System Python version 3.10.4
- gcc 11.2.0 
- Debug log https://gist.github.com/ccapudev/7ccca961345fd9b3a0d4fdbbc3863fc7

![install_python_crash](https://user-images.githubusercontent.com/13970636/161862213-e6e17e57-35ae-4cc9-a2a3-eb627b189acd.png)

**Comment by native-api** [comment]
As the error message says, this is a problem with GCC 11; it also specifies what you need to provide them for diagnostics.

**Comment by Erotemic** [comment]
I'm also experiencing this. Is this a bug in gcc11? Or is this due to some dependency (e.g. ssl, hashlib, ...) being too new for 2.7?
