### ISSUE TITLE
Python 3.10.4 is in pydev, but not in python-build

### ISSUE THREAD

**Issue by workflowsguy** [pyenv/pyenv#2319]
I could install 3.10.4 with `pydev install 3.10.4`,

but 

`sudo python-build 3.10.4 /usr/local/`

gives

`python-build: definition not found: 3.10.4`

Should pyenv and python-build not have the same knowledge about existing versions?

### Description
- OS: macOS 10.13.6
- OS architecture: amd64
- pyenv version: pyenv 2.2.5-11-gf0f2cdd1
- Python version: 3.10.4
- C Compiler information:
```Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 ```

**Comment by andreif** [comment]
https://github.com/pyenv/pyenv/pull/2295 not released yet

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/releases/tag/v2.3.0
