### ISSUE TITLE
Deploy pyenv with local proxy server

### ISSUE THREAD

**Issue by maldag** [pyenv/pyenv#2320]
Would it be possible to use a local proxy server to restrict using only certain pyenv versions?

**Comment by native-api** [comment]
Not sure what you're trying to achieve but you can install any release and any commit you like.

**Comment by maldag** [comment]
The point would be to redirect the download url where pyenv looks for possible installations to local server instance.

**Comment by native-api** [comment]
For this, you may look at https://github.com/pyenv/pyenv-installer/blob/master/bin/pyenv-offline-installer instead. It allows you to bundle Pyenv with installer.
