### ISSUE TITLE
python 3.9.8 on MacOS 12.2.1 fails BUILD

### ISSUE THREAD

**Issue by ADiTuri** [pyenv/pyenv#2322]
### Description
I have tried to install different version of python3.9.X (3.9.9, 3.9.10, 3.9.11) and none of them are working. 
I have also tried some 3.8.X and 3.5.X all giving different errors.
I am mainly interested in python 3.9.8

- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS Monterey 12.2.1
- [x] pyenv version: 2.2.5
- [x] Python version: 3.9.8 
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 12.0.5 (clang-1205.0.22.9)
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `pyenv install 3.9.11`).

Here you can find the [log](https://drive.google.com/file/d/1X4fnPkM-FMWUaREy5Ua2TqNu26UlRU_Y/view?usp=sharing) and here you can find the config [log](https://drive.google.com/file/d/1sS279WqvomsH4wlU_7t_Qc7TC97c6cmU/view?usp=sharing)
This is what I am getting: 

``` python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.9.8.tar.xz...
-> https://www.python.org/ftp/python/3.9.8/Python-3.9.8.tar.xz
Installing Python-3.9.8...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 12.2.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/jl/hp_s9knj13x5ft7mffr258r40000gp/T/python-build.20220412182145.25030
Results logged to /var/folders/jl/hp_s9knj13x5ft7mffr258r40000gp/T/python-build.20220412182145.25030.log

Last 10 log lines:
if test $? -ne 0 ; then \
	echo "generate-posix-vars failed" ; \
	rm -f ./pybuilddir.txt ; \
	exit 1 ; \
fi
make: *** [Makefile:688: python.exe-gdb.py] Killed: 9
make: *** Waiting for unfinished jobs....
/bin/sh: line 5: 33970 Killed: 9               ./python.exe -E -S -m sysconfig --generate-posix-vars
generate-posix-vars failed
make: *** [Makefile:618: pybuilddir.txt] Error 1  



Here you can find the [log](https://drive.google.com/file/d/1X4fnPkM-FMWUaREy5Ua2TqNu26UlRU_Y/view?usp=sharing) and here you can find the config [log](https://drive.google.com/file/d/1sS279WqvomsH4wlU_7t_Qc7TC97c6cmU/view?usp=sharing)

**Comment by activeliang** [comment]
Some individuals, like myself, may have encountered issues with different versions of Homebrew due to the M1 chip. I am documenting this here for your reference. Please refer to the official documentation：
https://github.com/pyenv/pyenv/wiki/Common-build-problems#on-apple-silicon-when-building-for-arm64-a-dependency-is-present-in-x64-homebrew-but-not-arm64-homebrew
