### ISSUE TITLE
can't install python 3.5 on Mac OS Monterey

### ISSUE THREAD

**Issue by shasan2519** [pyenv/pyenv#2323]
I need to run regression testing on some stuff and to get it working I need python 3.5 to even being with. How do I solve this?

`(kptestsuites) ➜  ~ pyenv install  3.5.0      
Downloading openssl-1.0.2k.tar.gz...
-> https://pyenv.github.io/pythons/6b3977c61f2aedf0f96367dcfb5c6e578cf37e7b8d913b4ecb6643c3cb88d8c0
Installing openssl-1.0.2k...
Installed openssl-1.0.2k to /Users/dev/.pyenv/versions/3.5.0

python-build: use readline from homebrew
Downloading Python-3.5.0.tar.xz...
-> https://www.python.org/ftp/python/3.5.0/Python-3.5.0.tar.xz
Installing Python-3.5.0...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 12.3.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/3b/9095zxkd5w93vmwn1vng44s80000gn/T/python-build.20220413122821.24821
Results logged to /var/folders/3b/9095zxkd5w93vmwn1vng44s80000gn/T/python-build.20220413122821.24821.log

Last 10 log lines:
checking for --with-cxx-main=<compiler>... no
checking for clang++... no
configure:

  By default, distutils will build C++ extension modules with "clang++".
  If this is not intended, then set CXX on the configure command line.
  
checking for the platform triplet based on compiler characteristics... darwin
configure: error: internal configure error for the platform triplet, please file a bug report
make: *** No targets specified and no makefile found.  Stop.`

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/issues/2143#issuecomment-1072032647
