### ISSUE TITLE
Selecting latest available patch version using glob pattern

### ISSUE THREAD

**Issue by den-is** [pyenv/pyenv#2331]
I've started using pyenv extensively just recently.
And have found one minor annoyance, at least it is for me.

Description:
Node-A is running project that uses "old" python 3.10.2 installed using pyenv
Node-B is a new node with the ability to install the latest python 3.10.4

I'm not able to find a way if how it is possible to automate the python version switch.
How to make python version update transparent and smooth for the application.

It could be nice to have something like

`.python-version` with contents like:
`3.10` or `3.10.*` (or version restrictions as done in some other systems `~3.10.0`, etc)that will select the newest available python 3.10

I'm actually using `direnv`. And of course `layout pyenv 3.10[.*]` in the envrc is not working either.

**Comment by thomasfinstad** [comment]
I am bumping into this as-well right now, but for a different use-case.

I wish to use pyenv in a automatic testing and publishing scenario, and the required python versions come in tox format example:
py3,py38,py310,pypy37,pypy39
I can easily convert these to
3,3.8,3.10,pypy3.7,pypy3.9
but that leaves missing version numbers.

I wonder if support for the same style as tfenv would be useful, or a version of that style?
When they wish to use a more "smart" way to find the version you prepend the version with `latest:` and then you use regex to complete the version number. 
This lets you pick if you wish to avoid `-dev` versions etc by doing something like this `latest:3.8[0-9.]*$`.

This also opens up options for other ways to find the version, for example `oldest:3.10.*` or what ever else is useful.

**Comment by native-api** [comment]
Implemented auto-resolving micro versions in https://github.com/pyenv/pyenv/pull/2487
