### ISSUE TITLE
compile python3.8.5 failed when changed the env variables

### ISSUE THREAD

**Issue by JohnHerry** [pyenv/pyenv#2333]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ Y] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ Y] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ Not Sure] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ Y] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ Y] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): CentOS7.9
- [ ] OS architecture (e.g. amd64): X86_64
- [ ] pyenv version: 2.2.5
- [ ] Python version: 3.8.5
- [ ] C Compiler information (e.g. gcc 7.3):  4.8.5
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

It is success when I run `env PYTHON_CONFIGURE_OPTS="--emable-shared" pyenv install 3.8.5`
But when I changed to  `env PYTHON_CONFIGURE_OPTS="--enable-shared --enable-optimizations --with-ssl" pyenv install 3.8.5`
it failed to compile. error info:

```code
LD_LIBRARY_PATH=/tmp/python-build.20220422114215.15674/Python-3.8.5 ./python -E -S -m sysconfig --generate-posix-vars ;\
if test $? -ne 0 ; then \
        echo "generate-posix-vars failed" ; \
        rm -f ./pybuilddir.txt ; \
        exit 1 ; \
fi
Could not import runpy module
Traceback (most recent call last):
  File "/tmp/python-build.20220422114215.15674/Python-3.8.5/Lib/runpy.py", line 15, in <module>
    import importlib.util
  File "/tmp/python-build.20220422114215.15674/Python-3.8.5/Lib/importlib/util.py", line 14, in <module>
    from contextlib import contextmanager
  File "/tmp/python-build.20220422114215.15674/Python-3.8.5/Lib/contextlib.py", line 4, in <module>
    import _collections_abc
SystemError: <built-in function compile> returned NULL without setting an error
generate-posix-vars failed
```

Im I lossing some packages that I should preinstalled?

**Comment by native-api** [comment]
Need the debug trace and `config.log` to say anything specific. Looks like either a Python problem, a compiler problem, or that some module fails to build.

Also check if you have any `FLAGS` evvars set as those affect the compiler.

**Comment by JohnHerry** [comment]
It is ok now after installation of `xz-devel`.

It seems that the `--with-ssl` python compile option requires the `liblzma-devel` installed, but in my CentOS it was not found. `xz-devel` is ok.

 Thanks.
