### ISSUE TITLE
Setup instructions in README don't reflect released behavior

### ISSUE THREAD

**Issue by relsqui** [pyenv/pyenv#2350]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 20.04.4 via WSL in Win10
- [x] OS architecture (e.g. amd64): x64
- [x] pyenv version: 2.25
- [x] Python version: n/a
- [x] C Compiler information (e.g. gcc 7.3): 9.4.0
- [x] Please attach the debug trace of the failing command as a gist: n/a

---

When changes to `pyenv init -` were made [yesterday](https://github.com/pyenv/pyenv/commit/8439f8e18714c2aec0399e9cea022467dc4511ff), the README was also updated promptly, which is great. However, the latest release of pyenv which I installed through homebrew this morning does not have those changes, which means that following the published setup instructions never put the shims in my $PATH. I'm brand new to pyenv and have had a confusing adventure figuring out how and when that was supposed to happen.

As much as I agree with keeping the docs in step with the code, given that this README also needs to support the released version (unless I missed some other instructions), it might be worth continuing to include a `pyenv init --path` step until the change to `pyenv init -` is released.

**Comment by native-api** [comment]
2.3.0 has been released.

For the record, you can see the README for any older release or by selecting a tag in the branch dropdown.
