### ISSUE TITLE
PYENV_VERSION not set when changing working directory

### ISSUE THREAD

**Issue by KingMichaelPark** [pyenv/pyenv#2352]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [Ubuntu 22.04] Platform information (e.g. Ubuntu Linux 16.04):
- [amd64] OS architecture (e.g. amd64):
- [pyenv 2.3.0-1-g867f34b5] pyenv version:
- [>3.8.13] Python version:
- [11.2] C Compiler information (e.g. gcc 7.3): 

### Summary

When changing directory into a directory with a `.python-version` I would expect
for the `$PYENV_VERSION` to be set so that paths can be discovered correctly for
[pyright](https://github.com/microsoft/pyright). When I change into the directory
the virtual-environment is properly loaded in the sense that calling `python`
I can use the installed libraries that were installed via pip. However, in order
for them to get picked up by pyright, I need to call `pyenv shell version_name` in order
for the $PYENV_VERSION to be picked up. If the $PYENV_VERSION is not set, then it will
not find any of the imports. 

### Steps to Reproduce

```bash
mkdir ~/test
cd test
pyenv virtualenv 3.10.4 test_env
echo "test_env" > .python-version
```

![image](https://user-images.githubusercontent.com/64011084/166908612-19d2df05-27b5-4104-bc80-58b9de895553.png)

Then after setting the $PYENV_VERSION
```bash
export PYENV_VERSION="$(pyenv version-name)"
```

![image](https://user-images.githubusercontent.com/64011084/166909341-71226d28-c027-4f73-998f-ad8df96f2495.png)

No issue discovering imports. So even if this is expected behaviour, is there a way to call
that export command as some hook on cwd?

**Comment by native-api** [comment]
[`PYENV_VERSION` is an envvar that _you_ can set](https://github.com/pyenv/pyenv#environment-variables) (either manually or with `pyenv shell`) to override the versions inferred from the current directory. Pyenv doesn't set it automatically.

**Comment by native-api** [comment]
The screenshots you showed are _not_ Pyright (since Pyright is a plugin for IDEs AFAICS) so I need to know what exactly you're doing to be able to advise anything.

Basically, you need to somehow tell Pyright and/or your IDE which Python interpreter to use in a way that would pick up the right Pyenv-provided version.

**Comment by KingMichaelPark** [comment]
@native-api It's the pyright language server being called from neovim lsp. I will do some digging to figure it out. Thank you for taking the time to get back to me.

**Comment by KingMichaelPark** [comment]
The update is that you can add a pyrightconfig.json file with the path to the virtualenv and it activates. I have just moved away from pyenv-virtualenv and will stick to pyenv with `python -m venv .venv` instead. Easier to manage.
