### ISSUE TITLE
Segmentation fault when installing Python 3.6.15 on Ubuntu 22.04

### ISSUE THREAD

**Issue by IngoMeyer441** [pyenv/pyenv#2359]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): **Ubuntu Linux 22.04**
- [x] OS architecture (e.g. amd64): **amd64**
- [x] pyenv version: **latest master (commit df5ecfc72ddf382af1b0b576ba6a0d01c8f9e625)**
- [x] Python version: **3.6.15**
- [x] C Compiler information (e.g. gcc 7.3): **11.2.0**
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

---

Thanks for the very useful pyenv project. :slightly_smiling_face: 
Installing Python 3.6.15 on Ubuntu 22.04 causes a segmentation fault at the moment:

```
if test "xupgrade" != "xno"  ; then \
        case upgrade in \
                upgrade) ensurepip="--upgrade" ;; \
                install|*) ensurepip="" ;; \
        esac; \
         ./python -E -m ensurepip \
                $ensurepip --root=/ ; \
fi
Segmentation fault (core dumped)
```

I attached `trace.log` as requested above and the log output of the build itself. The failing build can be reproduced in a fresh Ubuntu 22.04 Docker container with the following Bash script:

```bash
#!/bin/bash

PYENV_ROOT="/usr/local/pyenv"

apt-get update && \
apt-get install -y --no-install-recommends build-essential \
                                           ca-certificates \
                                           curl \
                                           gawk \
                                           git \
                                           libbz2-dev \
                                           libffi-dev \
                                           liblzma-dev \
                                           libncursesw5-dev \
                                           libreadline-dev \
                                           libsqlite3-dev \
                                           libssl-dev \
                                           zlib1g-dev && \
curl -o "/tmp/pyenv-master.tar.gz" -L "https://github.com/pyenv/pyenv/archive/master.tar.gz" && \
tar -C /tmp/ -xvf "/tmp/pyenv-master.tar.gz" && \
mv "/tmp/pyenv-master" "${PYENV_ROOT}" && \
"${PYENV_ROOT}/bin/pyenv" install "3.6.15"
```

[trace.log](https://github.com/pyenv/pyenv/files/8650658/trace.log)
[python-build.20220509095324.26933.log](https://github.com/pyenv/pyenv/files/8650656/python-build.20220509095324.26933.log)

**Comment by native-api** [comment]
Python 3.6 is EOL. Most probably, it's not compatible with OpenSSL 3 that Kinetic provides.

**Comment by native-api** [comment]
Releases with https://github.com/python/cpython/issues/83001 are the ones that support OpenSSL 3.

However, that issue has many PRs linked that were applied over a length of time -- so I'm not sure at which point of those OpenSSL 3 can be deemed "supported".

**Comment by native-api** [comment]
I managed to successfully install 3.6.15 in Jammy with a custom OpenSSL 1.1.1:

```
curl -O https://www.openssl.org/source/old/1.1.1/openssl-1.1.1n.tar.gz
tar -xf openssl-1.1.1n.tar.gz 
cd openssl-1.1.1n/
./config shared -Wl,-rpath=/opt/openssl11/lib --prefix=/opt/openssl11
make
sudo make install
CPPFLAGS=-I/opt/openssl11/include LDFLAGS="-L/opt/openssl11/lib -Wl,-rpath=/opt/openssl11/lib" pyenv install 3.6.15
```

``
$ ldd /home/vmuser/.pyenv/versions/3.6.15/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so
<...>
	libssl.so.1.1 => /opt/openssl11/lib/libssl.so.1.1 (0x00007f360ea96000)
	libcrypto.so.1.1 => /opt/openssl11/lib/libcrypto.so.1.1 (0x00007f360e7a9000)
<...>
```

**Comment by DenisBY** [comment]
This solution helped me https://github.com/pyenv/pyenv/issues/2239#issuecomment-1079275184

**Comment by igaurab** [comment]
> This solution helped me [#2239 (comment)](https://github.com/pyenv/pyenv/issues/2239#issuecomment-1079275184)

the solution seems to work. 
OS: Ubuntu 22.04 (Ubuntu Mate)

**Comment by feenes** [comment]
still getting the segmentation fault.

Any other solution for this?

**Comment by ninthday** [comment]
> This solution helped me [#2239 (comment)](https://github.com/pyenv/pyenv/issues/2239#issuecomment-1079275184)

Thx, this solution work for me to install pyrhon 3.7.3.

OS: Ubuntu 22.04
version: pyenv 2.3.7-2-g58bbbf88

**Comment by jmahandmi** [comment]
> This solution helped me [#2239 (comment)](https://github.com/pyenv/pyenv/issues/2239#issuecomment-1079275184)

I was also getting the core dump when trying to pyenv install 3.7.3 in `node:16.20.1-alpine3.17`

This solution worked
