### ISSUE TITLE
The pyenv failed  suddenly

### ISSUE THREAD

**Issue by JohnHerry** [pyenv/pyenv#2360]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [Y ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [Y] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [Not sure] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [Not sure] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [Not sure] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [Y ] Platform information (e.g. Ubuntu Linux 16.04): CentOS7.9
- [Y ] OS architecture (e.g. amd64): X86_64
- [ Y] pyenv version: 2.2.5
- [Y ] Python version: All versions
- [ Y] C Compiler information (e.g. gcc 7.3): 4.8.5
- [Y ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

I had upgrade my local pyenv last month, it works well for weeks. Today when I entered some virtualenv created by my "pyenv virtualenv" weeks ago, the pyenv just failed. the `python` command just call the system default python.  
When I run "pyenv shell" it juse say "pyenv: shell integration not enabled. Run `pyenv init` for instructions";  But there is  "eval ($pyenv init -)" in my bash_profile, which is set by the pyenv-installer long times ago on my old version pyenv first installation, and as I had said, the pyenv just works well last week, now it illed.  what is wrong?

**Comment by native-api** [comment]
Cannot say for sure since you didn't give a debug trace of a faulty invocation.

If you've upgraded straight from Pyenv 1, it's probably a good idea to upgrade straight to 2.3.0 rather than to 2.2.5 since vesions 2.0.0-2.2.5 used a different, more complicated shell configuration setup.

See https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv for the current shell setup instructions and https://github.com/pyenv/pyenv/tree/v2.2.5#basic-github-checkout for instructions for 2.2.5.

**Comment by JohnHerry** [comment]
> Cannot say for sure since you didn't give a debug trace of a faulty invocation.
> 
> If you've upgraded straight from Pyenv 1, it's probably a good idea to upgrade straight to 2.3.0 rather than to 2.2.5 since versions 2.0.0-2.2.5 used a different, more complicated shell configuration setup.
> 
> See https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv for the current shell setup instructions and https://github.com/pyenv/pyenv/tree/v2.2.5#basic-github-checkout for instructions for 2.2.5.

Thank you for the help.

It is OK now since I have changed in bash_profile from "pyenv init -" to "pyenv init --path".  I am sure it worked well weeks ago until yestorday when I use the old config. It is strange!
