### ISSUE TITLE
issue on linux: i alredy istalled another version of python but needed to install a new one and this happend

### ISSUE THREAD

**Issue by ORGINRISHITH** [pyenv/pyenv#2362]
Downloading Python-3.6.10.tar.xz...
-> https://www.python.org/ftp/python/3.6.10/Python-3.6.10.tar.xz
Installing Python-3.6.10...

BUILD FAILED ( using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20220510141712.23570
Results logged to /tmp/python-build.20220510141712.23570.log

Last 10 log lines:
  File "/tmp/python-build.20220510141712.23570/Python-3.6.10/Lib/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/tmp/python-build.20220510141712.23570/Python-3.6.10/Lib/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
make: *** [Makefile:1102: install] Error 2
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 25, in <module>
    import lsb_release
ModuleNotFoundError: No module named 'lsb_release'

**Comment by native-api** [comment]
> Traceback (most recent call last):
> File "/usr/bin/lsb_release", line 25, in
> import lsb_release
> ModuleNotFoundError: No module named 'lsb_release'

That's an error with your system's `lsb_release`.

Without the required diagnostic information as per the issue template, I cannot say any more than that.

**Comment by ORGINRISHITH** [comment]
Sorry to disturb bur is there a fix for this
