### ISSUE TITLE
pyenv python-build failing at aws ec2 userdata

### ISSUE THREAD

**Issue by uday-projectn** [pyenv/pyenv#2365]
As part of cloud machine aws, we kept the instalaltion of python using pyenv using userdata of aws.
but it is failing there.

Even expanded all the variable values and tried but it is failing at python installation.

I ran the commands directly in userdata now and saw, it is getting stuck at below command.

`/root/.pyenv/plugins/python-build/bin/python-build $python_version /usr/local/python_projectn/`
If I run later once login, it is working. But with userdata of aws, it is getting stuck at installing the python and stopping there.

```
Downloading Python-3.9.5.tar.xz...
-> https://www.python.org/ftp/python/3.9.5/Python-3.9.5.tar.xz
Installing Python-3.9.5...
```
portion of script till where it is failing:
```

pyenv_release=2.2.5
wget https://github.com/pyenv/pyenv/archive/refs/tags/v$pyenv_release.tar.gz -O pyenv-package.tar.gz
tar -xvf pyenv-package.tar.gz
mv pyenv-$pyenv_release /root/.pyenv
rm -rf pyenv-package.tar.gz

export PATH=/root/.pyenv/bin:/root/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:$PATH

python_version=3.9.5
echo "Installing python: $python_version"

/root/.pyenv/plugins/python-build/bin/python-build $python_version /usr/local/python_projectn/

```

Please suggest how to fix this

**Comment by native-api** [comment]
Please provide the necessary diagnostic info as per the issue template.
