### ISSUE TITLE
Pycharm cannot choose pipenv: "Pipenv interpreter has been already added, select 'Pipenv (pythonProject1)' in your interpreters list"

### ISSUE THREAD

**Issue by allenjol** [pyenv/pyenv#2366]
I have installed python 3.10.2 in my macos， and then i use command `pip install pipenv` in my macos version 12.3.1.

But when i use pycharm to create the first project, it can choice pipenv,and then, when i want to create second project,i got this problem:
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/28972707/168208368-17a252f1-b5e4-475a-9b44-92862ed9eea9.png">

The first project's Pipfile is here:
<img width="978" alt="image" src="https://user-images.githubusercontent.com/28972707/168208516-1a87fb82-83df-4b8f-9637-ffbf42fc9dab.png">

who one know that and how to resolve it？

**Comment by native-api** [comment]
As it says, you should select "previously configured interpreter" then select "Pipenv (pythonProject1)" from the dropdown list.
