### ISSUE TITLE
Request: pyenv install --pin (pin after installation)

### ISSUE THREAD

**Issue by jamesbraza** [pyenv/pyenv#2370]
### Description

- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 18.04.6 LTS
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 2.3.0
- [x] Python version: 3.10

Before I begin, I want to say that `pyenv` is a huge help to me, and I think it's really awesome.

When standing up a new machine, I commonly take the below steps:
1. Install `pyenv`
2. Install the latest Python: `pyenv install 3.10:latest`
3. Pin what version was installed: `pyenv global 3.10.4`

Step 3 requires me to actually look at what Python version was installed, which the prior command already knew.  Thus, I think step 3 can be automated via a command-line flag to `pyenv install`.  Something like:
- `pyenv install --pin-global 3.10:latest`: to bake in running `pyenv global 3.10.4` after step 2's install completes
- `pyenv install --pin-local 3.10:latest`: to bake in running `pyenv local 3.10.4` after step 2's install completes

What do you think of this?  It's merely a convenience/optimization for end-user automation.

**Comment by native-api** [comment]
Looks like the same can be done by allowing `3.10:latest` in version selection as per https://github.com/pyenv/pyenv/issues/1946

**Comment by native-api** [comment]
Implemented auto-resolving micro versions in https://github.com/pyenv/pyenv/pull/2487

**Comment by jamesbraza** [comment]
@native-api firstly, that's an awesome feature in micro versions, thank you!

I think this issue was also about adding `pyenv install` args:
- `pyenv install --pin-global 3.10`: will install 3.10.X with `--pin-global` baking in the following `pyenv global 3.10.X` call
- `pyenv install --pin-local 3.10`: will install 3.10.X with `--pin-local` baking in `.python-version` file creation

Does that make sense?  I think this request shouldn't actually be closed out yet.

**Comment by native-api** [comment]
With that feature, the "pin" should be unneeded. When installing, "3.10" resolves to the latest known 3.10 release, when selecting, to the latest installed.

**Comment by jamesbraza** [comment]
Yeah agreed, `pyenv install 3.10` works as desired!

However, we still have to have further `pyenv` calls after installation:

```bash
pyenv global 3.10.X  # X here has to match what was just installed
# or
pyenv local 3.10.X  # X here has to match what was just installed
```

**Comment by native-api** [comment]
You can `pyenv global/local 3.10` just as well.

**Comment by jamesbraza** [comment]
Oh that's nice, I like that and see what you mean, yes it does automate version selection.

I guess I was thinking to have some way to do both actions (install and pin) in one call (using a flag to `pyenv install`), not two calls.

**Comment by native-api** [comment]
> (though only for the latest bugfix version)

Possible prefixes aren't limited to just `X.Y`, you can search for any full prefix (i.e. followed by a `.` or a `-` in the name).
