### ISSUE TITLE
macos 12.4  can't install 2.7.18 

### ISSUE THREAD

**Issue by qiusheng2011** [pyenv/pyenv#2376]
```
macbookprom1 tmp % CFLAGS=-I/opt/homebrew/opt/openssl@1.1/include  LDFLAGS=-L/opt/homebrew/opt/openssl@1.1/lib  pyenv install 2.7.18
python-build: use openssl from homebrew
python-build: use readline from homebrew
Installing Python-2.7.18...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (OS X 12.4 using python-build 1.2.23-54-gabcbf6e1)

Inspect or clean up the working tree at /var/folders/ry/zzljfh4s3mnf088y1xq_gtsc0000gn/T/python-build.20220523165442.59386
Results logged to /var/folders/ry/zzljfh4s3mnf088y1xq_gtsc0000gn/T/python-build.20220523165442.59386.log

Last 10 log lines:
rm -f /Users/gxz/.anyenv/envs/pyenv/versions/2.7.18/share/man/man1/python.1
(cd /Users/gxz/.anyenv/envs/pyenv/versions/2.7.18/share/man/man1; ln -s python2.1 python.1)
if test "xno" != "xno"  ; then \
        case no in \
            upgrade) ensurepip="--upgrade" ;; \
            install|*) ensurepip="" ;; \
        esac; \
         ./python.exe -E -m ensurepip \
            $ensurepip --root=/ ; \
    fi
```

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. mac os 12.4):
- [x] OS architecture (e.g. amd64 m1):
- [x] pyenv version: pyenv 1.2.23-54-gabcbf6e1
- [x] Python version: 2.7.18
- [x] C Compiler information (e.g. gcc  13.1.6):

**Comment by native-api** [comment]
Please provide the necessary diagnostic information as per the issue template.

**Comment by phoenixxyang** [comment]
[python-build.20220817151121.20855.log](https://github.com/pyenv/pyenv/files/9357274/python-build.20220817151121.20855.log)
Got same issue while installing python 2.7.18 on MacOS 12.4 via pyenv.
