### ISSUE TITLE
Recent changes in macOS Monterey 12.3 broke system version behaviour

### ISSUE THREAD

**Issue by debo** [pyenv/pyenv#2379]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS Monterey 12.4 (but also 12.3 should be affected)
- [x] OS architecture (e.g. amd64): arm64
- [x] pyenv version: 2.3.0
- [x] Python version: system
- [ ] C Compiler information (e.g. gcc 7.3): N/A
- [x] Please attach the debug trace of the failing command as a gist: https://gist.github.com/debo/70ce248df725b5ad66be9c38044e62b0

It appears that, since the release of [macOS Monterey 12.3, python 2.7 has been officially deprecated](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes) and this means that the binary `/usr/bin/python` have been completely removed from the system. For this reason `pyenv` cannot identify the `system` version (my understanding is that it's looking for that specific path) and running `python --version` after defaulting `pyenv global` to `system` MacOS users will get an error similar to the following:
```shell
~ python --version
pyenv: python: command not found

The `python' command exists in these Python versions:
  ...

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
```
The easiest solution would be creating a symlink to `/usr/bin/python3` still available, unfortunately by default MacOS has SIP (System Integrity Protection) enabled which means that, myself, like most of people in my situation, cannot modify `/usr/bin` and create the aforementioned symlink.

Would it be possible to make the behaviour of detecting `system` python more flexible?

**Comment by native-api** [comment]
> ```shell
> ~ python --version
> pyenv: python: command not found
> 
> The `python' command exists in these Python versions:
>   ...
> ```

That's by design. What else did you expect if there's no `python` executable to run?

**Comment by debo** [comment]
I appreciate that, the problem is that technically system python still exists, but it's called `/usr/bin/python3`, so I guess it would be nice for it to still be detected, it's still the python executable that comes bundled with the operating system after all. Why the decided to not call it just `python` being the only binary is beyond my comprehension but that's another story.

I don't know `pyenv`  code well enough but, could something similar to what was done in [this commit](https://github.com/pyenv/pyenv/commit/af438abeaec9632453be96e163d787ee5e78b61b) be implemented? Would it still fit pyenv philosophy?

**Comment by native-api** [comment]
As per https://peps.python.org/pep-0394/#for-python-runtime-distributors, UNIX distro vendors are free to alias `python` to either `python2` or `python3` or not provide it at all. As such, Pyenv reports "`system`" version present when either `python`, `python2` or `python3` is available. So the detection works correctly.
Pyenv does not try to second-guess the system vendor here -- and it can not do so meaningfully anyway (since that's explicitly the vendor's arbitrary choice) and that would be unwise, too (see below).

That change in the PEP was made specifically to ease the transition to Python 3 -- specifically so that users stop relying on "`python`" and making mutually-exclusive assumptions about it. [The recommendation then instructs users](https://peps.python.org/pep-0394/#for-python-script-publishers) to switch from just "`python`" to "`pythonX`" or "`pythonX.Y`" depending on the code's requirements and only use "`python`" in scripts designed solely for virtual environments.

---

So you either need to switch from "`python`" to "`pythonX`" or "`pythonX.Y`" if you wish to keep using the system's version,
or [select](https://github.com/pyenv/pyenv#switch-between-python-versions) some Pyenv-provided version.

**Comment by debo** [comment]
> Pyenv reports "system" version present when either python, python2 or python3 is available. So the detection works correctly.
Ok, but if, as you say the detection works correctly for any of those permutations depending by which one is available, how come that in the following scenario:
```shell
~ pyenv versions
* system (set by /Users/marco.debortoli/.pyenv/version)
  2.7.18
  3.10.4
  3.7.13
  3.8.13
  3.9.12
```
I get the following error:
```shell
pyenv: python: command not found

The `python' command exists in these Python versions:
    ...

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
```
When I run `python --version`? If I search for the binary I get the following:
```shell
~ which python3
/Users/debo/.pyenv/shims/python3
```
Did I screw up something something with the `PATH`?

**Comment by native-api** [comment]
You need to run `python3 --version` rather than "`python --version`" since `python3` is what the system provides.

**Comment by native-api** [comment]
Likewise, specify `/usr/bin/env python3` in scripts.

**Comment by native-api** [comment]
Likewise, specify `#!/usr/bin/env python3` in scripts.

**Comment by debo** [comment]
> You need to run python3 --version rather than "python --version" since python3 is what the system provides.
Mmmm, there is discrepancy in behaviour though no? Why doesn't `pyenv` internally alias the system python version, regardless of the binary name, to `python` as it does for the versions it installs like in the following case:
```shell
~ pyenv local 2.7.18
~ python --version
Python 2.7.18
```

**Comment by debo** [comment]
Oh wait, I got it, sorry I was being thick. If the version is managed by `pyenv`, pyenv maintainers decided to alias the current version to `python` but, for system python, you don't alias it but keep it transparent to whichever binary name `system` python uses. Correct?

**Comment by native-api** [comment]
Exactly!

**Comment by debo** [comment]
Understood! Thanks a lot for your patience in explaining it.
