### ISSUE TITLE
"ld: library not found for -lintl" when linking against Pyenv-provided Python on an arm64 Mac

### ISSUE THREAD

**Issue by dnicolson** [pyenv/pyenv#2381]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS 12.4 (21F79)
- [x] OS architecture (e.g. amd64): arm64
- [x] pyenv version: 2.3.1
- [x] Python version: 3.10.3
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 13.1.6 (clang-1316.0.21.2.5)
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

Python Autoconf scripts can fail on M1 Macs but not Intel Macs and it appears to be related to `gettext` being installed by Homebrew in the `/opt/homebrew` directory instead of `/opt/local`.

Interestingly, commenting out [these lines](https://github.com/pyenv/pyenv/blob/v2.3.1/plugins/python-build/bin/python-build#L1328-L1335) from the `use_homebrew` method in `python-build` appears to resolve the issue.

This works on an Intel Mac:
```
pyenv install 3.10.3
pyenv shell 3.10.3

cat > test.c <<EOF
#include <Python.h>

int main() {
  Py_Initialize();
}
EOF
gcc test.c $(python-config --cflags --ldflags --embed)
```

The result on an M1 Mac:
```
ld: library not found for -lintl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This works on an M1 Mac:
```
gcc test.c -L/opt/homebrew/opt/gettext/lib $(python-config --cflags --ldflags --embed)
```

This works on an M1 Mac after commenting out `use_homebrew` (lines 1328-1335 in `/opt/homebrew/Cellar/pyenv/2.3.1/plugins/python-build/bin/python-build`):
```
pyenv install 3.10.3
gcc test.c $(python-config --cflags --ldflags --embed)
```

Without `use_homebrew`:
```
otool -L ~/.pyenv/versions/3.10.3/bin/python
/Users/dave/.pyenv/versions/3.10.3/bin/python:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1858.112.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```

With `use_homebrew`:
```
otool -L ~/.pyenv/versions/3.10.3/bin/python
/Users/dave/.pyenv/versions/3.10.3/bin/python:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1858.112.0)
	/opt/homebrew/opt/gettext/lib/libintl.8.dylib (compatibility version 11.0.0, current version 11.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```

**Comment by native-api** [comment]
Please provide debug traces for the scenarios you've described. We can't see what's happening under the hood otherwise.

**Comment by native-api** [comment]
@dnicolson Okay, I've checked that CPython can successfully build without Gettext -- so that's what must be happening when you comment out lines. (It just doesn't provide the appropriate functionality then.)

So I don't require traces as of now. We're back to https://github.com/pyenv/pyenv/issues/2381#issuecomment-1142582119

**Comment by native-api** [comment]
Okay, I was able to reproduce the issue in a VM when Homebrew is installed at a nonstandard prefix.

**Comment by ktavabi** [comment]
> That could help. I'm very interested where else Python's build finds Gettext without those arguments (I suspect that nowhere). Please also attach `config.log`s if you can and the output of the `python-config` invocation.
> 
> @joshfriend , you can probably help here since you have the hardware.

👋🏿 hello all, 
I am fairly certain I am encountering the same problems on an arm64 mac without any `homebrew` brews ☕️

Here is the result of my `invocation`. That should also tell you about how much I know about `pyenv`

![image](https://user-images.githubusercontent.com/4381290/171906009-2604459a-ef8a-4e15-9e47-b692afad664a.png)

**Comment by native-api** [comment]
@ktavabi , your issue is a different one. Please check https://github.com/pyenv/pyenv/wiki/Common-build-problems and if that doesn't help, create a separate ticket and provide the necessary diagnostic info as per the issue template.

**Comment by native-api** [comment]
No-one replied at the Homebrew forum so far.
So I assume that those Homebrew args are supposed to be omitted when you're within the Homebrew ecosystem since it adds them automagically.

But we are outside it -- so we do need to add them.
