### ISSUE TITLE
original python versions can not be found

### ISSUE THREAD

**Issue by YitongD** [pyenv/pyenv#2387]
Before I install pyenv, I have python3.9 and python2.7 in my systems. But after installing pyenv, the two versions can not be found and some tools such as tensorflow, .etc can not be used correctly. 
`--pyenv versions
* system (set by /home/SENSETIME/dongyitong/.pyenv/version)`
--ModuleNotFoundError: No module named 'tensorflow'

Can you help me with the problem?

**Comment by native-api** [comment]
Please provide the necessary diagnostic information as per the issue template for us to be able to say anything specific.

Also please describe your environment in more details:
* how exactly are those previous versions installed (distro-provided? installed them yourself somewhere, somehow?),
* which Python installation the modules in question belong to
* what exact invocation fails (in the diagnostic information above, please provide the trace for that invocation)
