### ISSUE TITLE
Do not skip curl config using `-q`

### ISSUE THREAD

**Issue by i5513** [pyenv/pyenv#239]
Hello,

When you use curl, it is a good idea reading the config, why are you using -q option ?

```
 http_get_curl() {
-  curl -q -o "${2:--}" -sSLf "$1"
+  curl -o "${2:--}" -sSLf "$1"
 }
```

In my case it was failing because I have a proxy configured and (a wrong but necessary) -k option

Thank you
##

**Comment by alexeiz** [comment]
The sole reason you'd have .curlrc is that curl doesn't work without it for one reason or another.  If .curlrc is ignored it's almost guaranteed that `pyenv install` won't work for people that rely on .curlrc.  The fix is trivial: remove the `-q` option.

**Comment by chenfengyuan** [comment]
I suppose add a note about http_proxy / https_proxy in README.md is really a good idea, because every one in China need a proxy to install python (github.io is blocked by something).

**Comment by yyuu** [comment]
I have never been to China! Pull requests are welcomed!

**Comment by leonardon473** [comment]
For people who want to bypass SSL verification when using Pyenv, you can do so by running the following command in the terminal:
`export PYTHON_BUILD_CURL_OPTS=-k`
