### ISSUE TITLE
Impossible to install scipy (libraries openblas, lapack not found)

### ISSUE THREAD

**Issue by durandg12** [pyenv/pyenv#2394]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): macOS 11.6.1
- [X] OS architecture (e.g. amd64): ARM64 (Apple M1)
- [X] pyenv version: 2.3.1
- [X] Python version: 3.10.1
- [X] C Compiler information (e.g. gcc 7.3): Apple clang version 13.0.0 (clang-1300.0.29.30)
- [X] Please attach the debug trace of the failing command as a gist:
  [The gist](https://gist.github.com/durandg12/381dec9ed34815e22e906bae5ed363aa)

I can't install scipy with pip on a version of python managed by pyenv. From the error log, the problem seems to be that pip doesn't find BLAS and Lapack, whereas I have them installed (I have read that they are installed with macOS, and for good measure I have installed them too with brew):
```
 openblas_clapack_info:
        libraries openblas,lapack not found in ['/Users/durand/.pyenv/versions/3.10.1/lib', '/usr/local/lib', '/usr/lib']
```

Note that installing scipy works with a version of python not managed by pyenv, like my version of python installed and managed with brew.

I've read that installing from a wheel could be the way, but no wheel of scipy for python 3.10 [(found there)](https://pypi.org/project/scipy/#files) is supported by my configuration it seems.

I've also tried to type
```export PKG_CONFIG_PATH="/opt/homebrew/opt/lapack/lib/pkgconfig:/opt/homebrew/opt/openblas/lib/pkgconfig"```
before typing `pip install scipy` in hope that pip would find Lapack and BLAS but it didn't work and threw the same error.

**Comment by native-api** [comment]
Since the libs are not found in `/usr/lib`, they are probably NOT bundled with your system.

Try with the Pyenv development head (`brew install pyenv --head`) first (it adds Homebrew to distutils' `LIBS`).

If that doesn't help, set the envvars to the libs' locations according to https://docs.scipy.org/doc/scipy/building/linux.html

**Comment by durandg12** [comment]
> If they are installed with Homebrew, try with the Pyenv development head (`brew install pyenv --head`) first ([it adds Homebrew to distutils' `LIBS`](https://github.com/pyenv/pyenv/commit/bc13a87beebfafb0e1baa352c0ba396fae4754b0)).

This worked, thanks.

**Comment by durandg12** [comment]
@native-api I have to reopen this issue, because it doesn't work anymore. I reinstalled pyenv with `brew install pyenv --head` (I now have pyenv version 2.3.6) and it is impossible to install a new version (1.9.3) of scipy, the error is basically the same 
```
../../scipy/meson.build:131:0: ERROR: Dependency "OpenBLAS" not found, tried pkgconfig and framework
```

It also doesn't work if I try to install the version of scipy I have already installed thanks to your trick (1.8.1) in a virtual env created with virtualenvwrapper.

Furthermore, the link you added to the scipy doc leads to an error 404.

Strangely enough, none of those problems happened on my personal laptop (MacBook Air 2022 with M2 chip, macOS 12). Should I try to update the OS? When I'm home I'll post the full configuration of my personal computer.

**Comment by native-api** [comment]
AFAICS, this problem is not relevant to Pyenv. It's your job to install any dependencies for your specific software and provide a way for the build of your specific software to find them.

> Furthermore, the link you added to the scipy doc leads to an error 404.

The URL is pretty descriptive. I think googling "scipy build in Linux" will give you the new location.

Judging by the error message, you need to make this library available on `pkgconfig` path. Did you install the library? If you installed it with Homebrw, it's probably keg-only. Check its `brew info` output how to add it to `pkgconfig` path.

> ImportError: dlopen(/Users/durand/.pyenv/versions/3.10.1/lib/python3.10/site-packages/scipy/linalg/_fblas.cpython-310-darwin.so, 2): Library not loaded: /opt/homebrew/opt/gcc/lib/gcc/11/libgfortran.5.dylib
>   Referenced from: /Users/durand/.pyenv/versions/3.10.1/lib/python3.10/site-packages/scipy/linalg/_fblas.cpython-310-darwin.so
>   Reason: image not found

Most probably, you've upgraded GCC since bulding so that library no longer exists. Rebulid it, then it'll link against whatever you have now. [There's a 3rd-party plugin](https://github.com/pyenv/pyenv/wiki/Plugins) that attempts to do that.

**Comment by durandg12** [comment]
`brew info openblas` indeed gave me the solution: I needed to type 
```
export PKG_CONFIG_PATH="/opt/homebrew/opt/openblas/lib/pkgconfig"
```
before installing scipy. openblas is indeed keg-only. Still it's strange that a few months ago your solution worked without needing this step, and now it doesn't.

And you were right as to why the existing installation of Scipy didn't work either, it was because I had upgraded gcc.

For information I tried the 3rd-party plugin `pyenv-fix-version` before but it didn't do anything useful.

**Comment by HazelHik** [comment]
> `brew info openblas` indeed gave me the solution: I needed to type
> 
> ```
> export PKG_CONFIG_PATH="/opt/homebrew/opt/openblas/lib/pkgconfig"
> ```
> 
> before installing scipy. openblas is indeed keg-only. Still it's strange that a few months ago your solution worked without needing this step, and now it doesn't.
> 
> And you were right as to why the existing installation of Scipy didn't work either, it was because I had upgraded gcc.
> 
> For information I tried the 3rd-party plugin `pyenv-fix-version` before but it didn't do anything useful.

this + `export LDFLAGS="-L/opt/homebrew/opt/openblas/lib"` + `export CPPFLAGS="-I/opt/homebrew/opt/openblas/include"` helped, thanks

**Comment by RobPruzan** [comment]
> `brew info openblas` indeed gave me the solution: I needed to type
> 
> ```
> export PKG_CONFIG_PATH="/opt/homebrew/opt/openblas/lib/pkgconfig"
> ```
> 
> before installing scipy. openblas is indeed keg-only. Still it's strange that a few months ago your solution worked without needing this step, and now it doesn't.
> 
> And you were right as to why the existing installation of Scipy didn't work either, it was because I had upgraded gcc.
> 
> For information I tried the 3rd-party plugin `pyenv-fix-version` before but it didn't do anything useful.

This worked for me

**Comment by SplitInf** [comment]
> `brew info openblas` indeed gave me the solution: I needed to type
> 
> ```
> export PKG_CONFIG_PATH="/opt/homebrew/opt/openblas/lib/pkgconfig"
> ```
> 
> before installing scipy. openblas is indeed keg-only. Still it's strange that a few months ago your solution worked without needing this step, and now it doesn't.
> 
> And you were right as to why the existing installation of Scipy didn't work either, it was because I had upgraded gcc.
> 
> For information I tried the 3rd-party plugin `pyenv-fix-version` before but it didn't do anything useful.

I ended up installing via brew

```
brew install openblas
export PATH="/opt/homebrew/opt/openblas/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/openblas/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openblas/include"
```
