### ISSUE TITLE
How to remove pyenv global after uninstalling python versions?

### ISSUE THREAD

**Issue by Aholicknight** [pyenv/pyenv#2395]
I uninstalled 2.7.18 + 3.10.4 by doing the commands `pyenv uninstall 2.7.18` and `pyenv uninstall 3.10.4` and when i run `pyenv global` it shows this command output: 
<img width="547" alt="Screen Shot 2022-06-16 at 9 13 46 AM" src="https://user-images.githubusercontent.com/7843719/174104559-3c2403f5-4fb8-4e9d-a3aa-16c3126a9bef.png">

Is this okay or is there a command to uninstall / remove globals? Thank you!

**Comment by native-api** [comment]
`pyenv global system`
