### ISSUE TITLE
Need documentation Example

### ISSUE THREAD

**Issue by skillkrio** [pyenv/pyenv#2398]
Hi i am new to pyenv. I am little bit confused of shims. Correct me if iam wrong . Lets say i have installed two versions of python 3.0 and 3.1 using pyenv and the my pyenv global version is 3.0. when i run any python command a new path folder .pyenv/shims got injected in my path which stops calling the real system environment python executables and it is intercepting the python call using this injected path. The .pyenv hidden folder contains subfolder called shims . In my understanding shims is just a folder which contains list of pyenv installed python versions. If i run any python commands  pyenv check at shell version (not set), local version(not set) and finally global version(3.0). It is going to find the global version (3.0) in the shims folder. why its not executing the python command using python shims executables?  instead it is passing it to pyenv executables. my question is
1. python shims are not capable of running python commands

2. how pyenv executables runs the obtained python command from the python shims executables. Under the hood it uses python or shell script to run our python program

3. If the right version of python is found in shims folder why it is not executing the commands there itself. Then why we have different versions of python shims in the shims folders better it can directly route to the pyenv executables

**Comment by native-api** [comment]
> shims is just a folder which contains list of pyenv installed python versions

`~/.pyenv/shims` directory contains _"shims"_ -- shell scripts that act as "smart links", selecting and running the real executable according to Pyenv's logic. Pyenv generates shims as needed automatically.

You can run `pyenv which <executable>` to see what real executable would be run when you invoke `<executable>` via a shim.

Pyenv-installed Python versions rather reside under `~/.pyenv/versions`.
