### ISSUE TITLE
3.10.5 version not appearing in install/list

### ISSUE THREAD

**Issue by samuelbailey123** [pyenv/pyenv#2402]
Platform information (e.g. Ubuntu Linux 16.04): macOS
OS architecture (e.g. amd64): arm 
pyenv version: 2.3.1
Python version: 3.10.5
C Compiler information (e.g. gcc 7.3): clang-1316.0.21.2.5

**Comment by aphedges** [comment]
You need to update to the recently released [pyenv v2.3.2](https://github.com/pyenv/pyenv/releases/tag/v2.3.2) to install CPython 3.10.5.

**Comment by samuelbailey123** [comment]
Ah I see it just came out today. Thanks.
