### ISSUE TITLE
Failed to switch under BigSur Mac

### ISSUE THREAD

**Issue by DecentrilizedMan** [pyenv/pyenv#2403]
I've successfully download python 3.7.5 via :
'''CFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix bzip2)/include -I$(brew --prefix readline)/include -I$(xcrun --show-sdk-path)/usr/include" LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix readline)/lib -L$(brew --prefix zlib)/lib -L$(brew --prefix bzip2)/lib" pyenv install --patch 3.7.5 < <(curl -sSL https://github.com/python/cpython/commit/8ea6353.patch\?pyenv install miniforge3-4.9.2full_index\=1) ''' 

<img width="440" alt="image" src="https://user-images.githubusercontent.com/43113774/176687270-b53b5fc9-8042-4452-97c5-3ffad67d257b.png">

But when i use the  command : '''pyenv global 3.7.5'''
It still shows the last python version 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/43113774/176687487-5dd308a6-d35e-41bf-b300-5e7a20e2966f.png">

**Comment by native-api** [comment]
Looks like shims are not in your PATH. Check that you've set up your shell accroding to https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv
