### ISSUE TITLE
Segmentation fault with pip3 - Xubuntu 22

### ISSUE THREAD

**Issue by niccokunzmann** [pyenv/pyenv#2406]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Xubuntu 22
- [x] OS architecture (e.g. amd64): amd64
- [X] pyenv version: pyenv 2.3.2-1-g46097aa7
- [x] Python version: $ pyenv versions --bare 2.7.18 3.6.15 3.7.13 3.8.13 3.9.13 + system(python 3.10)
- [x] C Compiler information (e.g. gcc 7.3): gcc --version
    gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
  * [trace.log](https://github.com/pyenv/pyenv/files/9032535/trace.log)

I want to have several versions of pyenv globally.
So, I do this:

    pyenv global `pyenv versions --bare` system

When I do `pip3`, I get a segmentation fault.

```
$ pip3
/home/sabin/.pyenv/pyenv.d/exec/pip-rehash/pip: line 20:  3233 Segmentation fault      (core dumped) "$PYENV_COMMAND_PATH" "$@"
```

In contrast for this:

    pyenv global system `pyenv versions --bare`

Everyhthing works fine:

```
sabin@schneidebrett:~$ pip3 --version
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
sabin@schneidebrett:~$ pip2 --version
pip 19.2.3 from /home/sabin/.pyenv/versions/2.7.18/lib/python2.7/site-packages/pip (python 2.7)
```

**Comment by native-api** [comment]
Cannot reproduce with a clean Xubuntu 22 with Pyenv installed according to the README.

From what you provided:

* Pip from 3.6.15 must be the one failing. Try [installing Python build dependencies](https://github.com/pyenv/pyenv/wiki#suggested-build-environment), then rebuilding it (`pyenv install --force 3.6.15`).
* > pyenv version: pyenv 2.3.2-1-g46097aa7

  there's no such version in this repo. You may have local changes

**Comment by github-yxb** [comment]
same issues on  Ubuntu 21.10 when i activated virtualenv.
python version: 3.6.15
pip version: 18.1
`.pyenv/pyenv.d/exec/pip-rehash/pip: line 20: 16333 Segmentation fault      (core dumped) "$PYENV_COMMAND_PATH" "$@"`

**Comment by native-api** [comment]
A segmentation fault means either a bug or (more likely) library incompatibility. E.g. it could happen if you updated a system-provided dependency library after you've built Python and the new version has changes that the old Python can't cope with.

As I said, rebuilding the Python may help because source code is more flexible than a compiled binary.

Note the 3.6 is EOL (https://en.wikipedia.org/wiki/History_of_Python#Version_3) so it's not tested with or adapted for newer versions of libraries.

You can open the core dump with `gdb` to see where exactly it failed to try to figure out the reason. Without a means to reproduce the fault (reproduction steps or e.g. a VM image of your system), I cannot help you here.

**Comment by DenisBY** [comment]
It seems you need to add few options: https://stackoverflow.com/questions/72102435/how-to-install-python3-6-on-ubuntu-22-04

**Comment by DenisBY** [comment]
This helped me
https://github.com/pyenv/pyenv/issues/2239#issuecomment-1079275184

**Comment by niccokunzmann** [comment]
I can confirm that this is a problem for Python 3.6 and this is right for me to be closed.
```
$ pip3.6
Segmentation fault (core dumped)
```
