### ISSUE TITLE
Installing 3.10 using openssl11 on Centos 7

### ISSUE THREAD

**Issue by slee356** [pyenv/pyenv#2416]
I'm trying to install 3.10 on Centos 7 and am getting "The Python ssl extension was not compiled. Missing the OpenSSL lib?" error. I understand 3.10 dropped the support for older OpenSSL. I have installed OpenSSL 1.1.1 which is spot install. What is the best way to tell pyenv to use `openssl11`?

**Comment by native-api** [comment]
See https://github.com/pyenv/pyenv/wiki/Common-build-problems and in particular https://github.com/pyenv/pyenv/wiki/Common-build-problems#error-the-python-ssl-extension-was-not-compiled-missing-the-openssl-lib

**Comment by aphedges** [comment]
I've tried following those directions before, but CentOS 7/RHEL 7 is a special case. Fortunately, @[tiran](https://github.com/tiran) (fake mention to not ping him) figured out how to do it and documented it: <https://github.com/tiran/cpython_builddep/blob/1c510950edd947eee9233a023d5ff5fecc96889a/README.md#note>. Unfortunately, I could not figure out how to write a custom hook to handle the necessary code changes, so I just installed OpenSSL 1.1.1 from source and used my personal copy. If you know how to get tiran's solution to work with pyenv, it'd be very helpful.

**Comment by eleksis** [comment]
I'm also struggling with this. Installed openssl11 package, but not able to successfully pass the correct paths to install command.

Can someone please add working example for  CentOS7/RHEL7 to [docs](https://github.com/pyenv/pyenv/wiki/Common-build-problems#1-openssl-is-installed-to-an-uncommon-location)?

**Comment by Yebolin** [comment]
nginx can build with openssl11, so system can have two version openssl together.
i think i can build python3 the same way, 
`sed -i 's/PKG_CONFIG openssl /PKG_CONFIG openssl11 /g' configure`
but fail to make, i am trying to fix it too

**Comment by Yebolin** [comment]
```
yum install openssl11-libs openssl-devel
export CFLAGS="$CFLAGS $(pkg-config --cflags openssl11)"
export LDFLAGS="$LDFLAGS $(pkg-config --libs openssl11)"
./configure --prefix=/usr/local/python3.10 --enable-optimizations
make
make altinstall
```
it works

**Comment by aphedges** [comment]
@Yebolin, thank you very much for how you compiled it! I was able to use a modified version of your commands to compile with pyenv, and I added the steps to the wiki section <https://github.com/pyenv/pyenv/wiki/Common-build-problems#error-the-python-ssl-extension-was-not-compiled-missing-the-openssl-lib> with <https://github.com/pyenv/pyenv/wiki/Common-build-problems/_compare/c96e0f628f2f1ee043fc5441d93be7ea17dd02fa...b5d54913196b42c858d54a11960ceff25729f072>.

**Comment by mcbex** [comment]
I was able to get this to work by combining a few previous answers. Here is my entire solution in case it helps anyone: 
```
yum install -y openssl-devel openssl11-devel openssl11-lib
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH"
CPPFLAGS="-I/usr/include/openssl11" LDFLAGS="-L/usr/lib64/openssl11 -lssl -lcrypto" pyenv install -v 3.10.4
```
I'm not sure why I had to install both openssl-devel and openssl11-devel but that was one of the missing pieces I needed. Other was using the entire output of `pkg-config --cflags openssl11` and `pkg-config --libs openssl11`. I included both versions for clarity. but the last line from above can also be replaced with: 
```
CPPFLAGS=$(pkg-config --cflags openssl11) LDFLAGS=$(pkg-config --libs openssl11) pyenv install -v 3.10.4
```

**Comment by jarkko-hautakorpi** [comment]
@aphedges 
> to compile with pyenv
Did you firs remove (or not install at all) openssl-devel or how did you make the pyenv install script to use the openssl11-devel version? Did you change some symlinks perhaps? I'm still getting 
_ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?_

**Comment by funk1d** [comment]
For those who cannot `yum install openssl11 openssl11-devel` directly, try
```sh
yum install epel-release
yum install openssl11 openssl11-devel
```

**Comment by jdogmcsteezy** [comment]
If anyone comes here trying to use openssl1.1.1 on Centos7 ARM and link it to your pyenv installation I have found a fix.

First install openssl from source:
```
    wget https://www.openssl.org/source/openssl-1.1.1.tar.gz
    tar -xvzf openssl-1.1.1.tar.gz
    cd openssl-1.1.1/
    ./config
    make -j$(($(nproc)+1))
    make install
```
Then add the new install location to your linker config
```
    echo '/usr/local/lib' >> /etc/ld.so.conf
    ldconfig
```
Then run pyenv install normally.

I originally used @mcbex's solution on x86 and that worked great but openssl11 packages do not exist on arm from what I could find so I needed to install from source.  I tried linking to the source installed libs like before with (any many other variations)
```
CPPFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib -lssl -lcrypto" pyenv install -v 3.10.4
```
but that did not work

**Comment by wingor** [comment]
> 

Thank you,it works for me

**Comment by iuriguilherme** [comment]
The [instructions](https://github.com/pyenv/pyenv/wiki/Common-build-problems#error-the-python-ssl-extension-was-not-compiled-missing-the-openssl-lib) weren't enough to help my use case but I managed to find out how to compile python 3.10+ as user on a Debian 9:

Find the [latest version of openssl](https://www.openssl.org/source/), for example 3.0.7 or 1.1.1s:

```bash
wget -c https://www.openssl.org/source/openssl-3.0.7.tar.gz
tar -xf openssl-3.0.7.tar.gz
pushd openssl-3.0.7
## --libdir is needed in my setup to prevent openssl using lib64 which I can't link with ldconfig because I don't have sudo
## alternatively the last command (pyenv install) can use lib64 instead of lib
./config --prefix=${HOME}/.local --openssldir=${HOME}/.local --libdir=lib
make
make test
make install
CPPFLAGS="-I${HOME}/.local/include" LDFLAGS="-L${HOME}/.local/lib -Wl,-rpath,${HOME}/.local/lib" CONFIGURE_OPTS="-with-openssl=${HOME}/.local" pyenv install 3.10.9
```

**Comment by mqquish** [comment]
Im having the same issue but with Cent OS 8 . https://github.com/pyenv/pyenv/wiki/Common-build-problems/_compare/c96e0f628f2f1ee043fc5441d93be7ea17dd02fa...b5d54913196b42c858d54a11960ceff25729f072 didnt solve my issue unfortunately :/

**Comment by aphedges** [comment]
> Im having the same issue but with Cent OS 8 . https://github.com/pyenv/pyenv/wiki/Common-build-problems/_compare/c96e0f628f2f1ee043fc5441d93be7ea17dd02fa...b5d54913196b42c858d54a11960ceff25729f072 didnt solve my issue unfortunately :/
> 
> Is there a modified version of the above that might work for Centos 8?

You shouldn't need to use any special setup on CentOS 8. It comes with OpenSLL 1.1.1, and I don't think I needed to use any special setup when I installed Python on Rocky 8. The two OS's should be pretty much identical because Rocky 8 is a new downstream of RHEL meant to replace CentOS 8 after it hit EOL over a year ago.

**Comment by cleverpig** [comment]
> For those who cannot `yum install openssl11 openssl11-devel` directly, try
> 
> ```shell
> yum install epel-release
> yum install openssl11 openssl11-devel
> ```
> 
> Reference: https://qiita.com/mykysyk@github/items/eb2fa27f4d77fbe2a2b0
> 
> ```shell
> yum install gcc zlib-devel bzip2 bzip2-devel readline readline-devel sqlite sqlite-devel openssl openssl-devel git libffi-devel
> yum install epel-release
> yum install openssl11 openssl11-devel
> git clone https://github.com/pyenv/pyenv.git ~/.pyenv
> echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bash_profile
> echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
> source ~/.bash_profile
> export CFLAGS=$(pkg-config --cflags openssl11)
> export LDFLAGS=$(pkg-config --libs openssl11)
> mkdir -p ~/tmp
> export TMPDIR=~/tmp
> pyenv install 3.10.4
> pyenv versions
> * system (set by /root/.pyenv/version)
>   3.10.4
> ```

IT's so GREAT!

**Comment by erg** [comment]
I spent a bit of time compiling openssl+python3.10 so I figured I'd share it. It has some code from the other answers. I couldn't get openssl11 to work on my M1 so I compiled it.

For an airflow-2.5.1 install on `amazonlinux:2` docker image

```sh
# I'm running this as root

# Some of this is not necessary for the task of making python3.10
yum -y update
yum -y upgrade
amazon-linux-extras install -y epel # if you need this, do this before python3 is in the path or it seems to fail
yum -y install git make gcc-c++ gcc cyrus-sasl-devel libcurl-devel shadow-utils libffi-devel bzip2-devel wget mariadb-devel postgresql-devel jq nc python2-cryptography java-1.8.0-openjdk unixODBC-devel zip unzip bzip2 gzip tar zlib-devel readline readline-devel sqlite sqlite-devel openssl openssl-devel openssl-libs

# Install custom openssl
ssl=openssl-1.1.1u
pushd /opt
curl https://ftp.openssl.org/source/old/1.1.1/$ssl.tar.gz --output $ssl.tar.gz
tar xzf $ssl.tar.gz
pushd $ssl
./config --prefix=/opt/openssl && make -j && make install
popd
popd

# python3.10 compile
wget https://www.python.org/ftp/python/3.10.12/Python-3.10.12.tgz
tar -xf Python-3.10.12.tgz # released 6/6/23
cd Python-3.10.12/
export CFLAGS="$CFLAGS"
export LDFLAGS="$LDFLAGS -lcrypto -lssl"
./configure --with-openssl=/opt/openssl --with-openssl-rpath=auto --enable-optimizations
make -j
make altinstall

# install it
ln -s /usr/local/bin/python3.10 /usr/bin/python3.10
ln -s /usr/local/bin/python3.10 /usr/bin/python3
ln -s /usr/local/bin/pip3.10 /usr/bin/pip3.10
ln -s /usr/local/bin/pip3.10 /usr/bin/pip3
```

**Comment by aidanhall34** [comment]
> ```
> yum install openssl11-libs openssl-devel
> export CFLAGS="$CFLAGS $(pkg-config --cflags openssl11)"
> export LDFLAGS="$LDFLAGS $(pkg-config --libs openssl11)"
> ./configure --prefix=/usr/local/python3.10 --enable-optimizations
> make
> make altinstall
> ```
> 
> it works

TYSM you have finally solved this for me after 6 hours ❤️ 

After many hours of the pip error:
```text
[SSLError("Can't connect to HTTPS URL because the SSL module is not available.")](https://stackoverflow.com/questions/63084049/sslerrorcant-connect-to-https-url-because-the-ssl-module-is-not-available)
```

I finally got Python3.11 complied in a centos7 docker container:
```dockerfile
FROM geerlingguy/docker-centos7-ansible:python3
...
RUN wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz; \
    tar xvf Python-3.11.4.tgz;
RUN cd Python-3*/; \
    export CFLAGS="$CFLAGS $(pkg-config --cflags openssl11)" ; \
    export LDFLAGS="$LDFLAGS $(pkg-config --libs openssl11)" ; \
    LDFLAGS="${LDFLAGS} -Wl,-rpath=/lib64/openssl11/" ./configure && \
    make && \
    make altinstall && \
    cd ../ ;\
    ln -s -f $(which python3.11) $(which python3) && \
    ln -s -f $(which pip3.11) $(which pip3) ;
```

**Comment by amidevous2** [comment]
> ```
> yum install openssl11-libs openssl-devel
> export CFLAGS="$CFLAGS $(pkg-config --cflags openssl11)"
> export LDFLAGS="$LDFLAGS $(pkg-config --libs openssl11)"
> ./configure --prefix=/usr/local/python3.10 --enable-optimizations
> make
> make altinstall
> ```
> 
> it works

not good require build openssl with source code

**Comment by amidevous2** [comment]
require litle edition



> I spent a bit of time compiling openssl+python3.10 so I figured I'd share it. It has some code from the other answers. I couldn't get openssl11 to work on my M1 so I compiled it.
> 
> For an airflow-2.5.1 install on `amazonlinux:2` docker image
> 
> # I'm running this as root
> 
> # Some of this is not necessary for the task of making python3.10
> yum -y update
> yum -y upgrade
> amazon-linux-extras install -y epel # if you need this, do this before python3 is in the path or it seems to fail
# warning package name curl-devel and not libcurl-devel
> yum -y install git make gcc-c++ gcc cyrus-sasl-devel curl-devel shadow-utils libffi-devel bzip2-devel wget mariadb-devel postgresql-devel jq nc python2-cryptography java-1.8.0-openjdk unixODBC-devel zip unzip bzip2 gzip tar zlib-devel readline readline-devel sqlite sqlite-devel openssl openssl-devel openssl-libs
> 
> # Install custom openssl
> ssl=openssl-1.1.1w
> pushd /opt
# curl require option -fL
> curl https://github.com/openssl/openssl/releases/download/OpenSSL_1_1_1w/$ssl.tar.gz -fL --output $ssl.tar.gz
> tar xzf $ssl.tar.gz
> pushd $ssl
> ./config --prefix=/opt/openssl && make -j && make install
> popd
> popd
> 
> # python3.20 compile

#not recomend use wget return ssl error on EL6/7

> curl -fL https://www.python.org/ftp/python/3.10.20/Python-3.10.20.tgz --output Python-3.10.20.tgz
> tar -xf Python-3.10.20.tgz
> cd Python-3.10.20/
> export CFLAGS="$CFLAGS"
> export LDFLAGS="$LDFLAGS -lcrypto -lssl"
#warning not recommend use /usr/local for prefix
> ./configure --prefix=/opt/python3.10.20 --with-openssl=/opt/openssl --with-openssl-rpath=auto --enable-optimizations
> make -j
> make altinstall
> 
> # install it
> ln -s /opt/python3.10.20/bin/python3.10 /usr/bin/python3.10
> ln -s /opt/python3.10.20/bin/python3.10 /usr/bin/python3
> ln -s /opt/python3.10.20/bin/pip3.10 /usr/bin/pip3.10
> ln -s /opt/python3.10.20/bin/pip3.10 /usr/bin/pip3
