### ISSUE TITLE
Allow pypy2* and pypy3* versions to be patched

### ISSUE THREAD

**Issue by brogon** [pyenv/pyenv#2418]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): all
- [x] OS architecture (e.g. amd64): any
- [x] pyenv version: 2.3.2
- [x] Python version: pypy3.9-7.3.9-src (sample)
- [x] C Compiler information (e.g. gcc 7.3): gcc 11.2.1
- [ ] ~~Please attach the debug trace of the failing command as a gist:~~

The last point makes no sense in this case as there is nothing to see.

The issue is within the `apply_python_patch` function of the `python-build` plugin: it only allows patches for Python versions starting with "Python-", "jython-", "pypy-" or "stackless-". But newer PyPy versions use a naming schema like `pypy<CPython-equivalent-version>-<app-version>` (e.g. "pypy3.9-7.3.9" or "pypy2.7-7.3.9"), which means they can't be patched, neither by internal patches nor by the "-p / --patch" argument to "pyenv install".

I'd propose a simple change like this:
```patch
--- a/plugins/python-build/bin/python-build	2022-07-25 18:24:50.974657691 +0200
+++ b/plugins/python-build/bin/python-build	2022-07-25 18:33:44.666132795 +0200
@@ -1641,7 +1641,7 @@
   local patchfile
   case "$1" in
-  Python-* | jython-* | pypy-* | stackless-* )
+  Python-* | jython-* | pypy-* | pypy2.?-* | pypy3.?-* | pypy3.??-* | stackless-* )
     patchfile="$(mktemp "${TMP}/python-patch.XXXXXX")"
     cat "${2:--}" >"$patchfile"
```
If `pypy?.?-* | pypy?.??-*` may be also distinct enough, and would support future "language" versions.

**Comment by native-api** [comment]
Sure thing. Could you convert this into a PR?
