### ISSUE TITLE
pypy2/3 patching still not working

### ISSUE THREAD

**Issue by brogon** [pyenv/pyenv#2422]
Followup to https://github.com/pyenv/pyenv/issues/2418 whose solution unfortunately didn't fix the issue; the use of BASH's `extglob` functionality doesn't work the way it was implemented:

 -  "extglob" mode in BASH doesn't support RegEx-like character classes like [:digits:], you need to
    use [0-9] (unless there is another option again for *that*...)

 -  BASH `shopt` is *really* strange - it's used by both the parser and the runtime: you need to "wrap"
    `apply_python_patch()` with `shopt -s extglob` / `shopt -u extglob`, but then also call `shopt -s extglob`
    and `shopt -u extglob` again *within* the function.
    Otherwise it parses the glob pattern, but applies it "literally" (non-extglob-wise) - which won't match
    anything reasonable.

I've created a new PR, https://github.com/pyenv/pyenv/pull/2421, to fix it (with "extglob" :wink: ).

**Comment by native-api** [comment]
I presume #2421 fixed this.
