### ISSUE TITLE
Cannot find dependencies if they are installed with Linuxbrew

### ISSUE THREAD

**Issue by kaykhan** [pyenv/pyenv#2426]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 22.04
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: pyenv 2.3.2
- [x] Python version: Python 3.10.4
- [x] C Compiler information (e.g. gcc 7.3): gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

[trace.log](https://github.com/pyenv/pyenv/files/9212249/trace.log)

Im trying to install a version of python using pyenv command `pyenv install 3.8.13`. However i get the following error:

```
Downloading Python-3.8.13.tar.xz...
-> https://www.python.org/ftp/python/3.8.13/Python-3.8.13.tar.xz
Installing Python-3.8.13...
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
WARNING: The Python curses extension was not compiled. Missing the ncurses lib?
WARNING: The Python ctypes extension was not compiled. Missing the libffi lib?
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (Ubuntu 22.04 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20220728164749.716382
Results logged to /tmp/python-build.20220728164749.716382.log

Last 10 log lines:
	 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
Looking in links: /tmp/tmp4m4ln38q
Processing /tmp/tmp4m4ln38q/setuptools-56.0.0-py3-none-any.whl
Processing /tmp/tmp4m4ln38q/pip-22.0.4-py3-none-any.whl
Installing collected packages: setuptools, pip
  WARNING: The scripts pip3 and pip3.8 are installed in '/home/kay/.pyenv/versions/3.8.13/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-22.0.4 setuptools-56.0.0
```

 **openssl version**
 
```
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
```

**Comment by kyleposluns** [comment]
I'm also having similar issues on Ubuntu 22.04 using WSL 2.

**Comment by MinghongAlexXu** [comment]
The same applies to me.

**Comment by native-api** [comment]
It looks like the dependencies are installed with Linuxbrew rather than the system's package manager.

Pyenv currently doesn't search Linuxbrew -- because
* they don't work out of the box like Homebrew-provided ones do
* system-provided libs are preferrable to Linuxbrew-provided as more stable (thus existing installations are less likely to break on a package upgrade)
   * and it's impossible to tell the compiler/linker to look in stadard locations and _after_ that in Linuxbrew.

See https://github.com/pyenv/pyenv/issues/1479 on why that was done.

I guess we can make an exception for the case when Pyenv itself is Linuxbrew-provided?

**Comment by kaykhan** [comment]
> It looks like the dependencies are installed with Linuxbrew rather than the system's package manager.
> 
> Pyenv currently doesn't search Linuxbrew for dependency libraries -- because
> 
> * they don't work out of the box like Homebrew-provided ones do
> * system-provided libs are preferrable to Linuxbrew-provided because
>   
>   * system package manager is the primary means of installing software in Linux, unlike MacOS
>   * system-provided libs are more stable (thus existing Python installations are less likely to break on a package upgrade)
> * it's impossible to tell the compiler/linker to look in stadard locations and _after_ that in Linuxbrew so we cannot simply make Linuxbrew a lower-priority source
> 
> See #1479 for details.
> 
> I guess we can make an exception and prefer Linuxbrew in the case when Pyenv itself is Linuxbrew-provided?

Not sure what you meant by your last statement. pyenv is installed using linuxbrew

**whereis pyenv**

```
pyenv: /home/linuxbrew/.linuxbrew/bin/pyenv
```

Are you suggesting i should uninstall pyenv from linuxbrew and install pyenv using something else. If so is this a good alternative https://github.com/pyenv/pyenv-installer is

**Comment by native-api** [comment]
> Are you suggesting i should uninstall pyenv from linuxbrew and install pyenv using something else. If so is this a good alternative https://github.com/pyenv/pyenv-installer

No, I'm suggesting you install Python build dependencies using the system's package manager rather than Linuxbrew.

**Comment by kaykhan** [comment]
> > Are you suggesting i should uninstall pyenv from linuxbrew and install pyenv using something else. If so is this a good alternative https://github.com/pyenv/pyenv-installer
> 
> No, I'm suggesting you install Python build dependencies using the system's package manager rather than Linuxbrew.

Thank you i followed here to install the build dependencies. https://devguide.python.org/getting-started/setup-building/index.html#install-dependencies

I was then able to successfully install python3.8

```
pyenv install 3.8.13                                        
Downloading Python-3.8.13.tar.xz...
-> https://www.python.org/ftp/python/3.8.13/Python-3.8.13.tar.xz
Installing Python-3.8.13...
Installed Python-3.8.13 to /home/kay/.pyenv/versions/3.8.13
```
