### ISSUE TITLE
install 3.11-dev on macOS hangs near end

### ISSUE THREAD

**Issue by brondsem** [pyenv/pyenv#2427]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information: macOS 12.5
- [x] OS architecture: intel x86_64
- [x] pyenv version: pyenv 2.3.2
- [x] Python version: 3.11-dev
- [x] C Compiler information:  Apple clang version 13.1.6 (clang-1316.0.21.2.5)
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

`pyenv install 3.11-dev` hangs near the end.  The `make` process is the one running, and I have to ctrl-c to stop it. 
Here's trace.log output, up until I ctrl-c it: https://gist.github.com/brondsem/9f3bf2eb762fcc6551db5930ceca8649

I can install 3.10.5 okay.

Seems very similar to this discussion post: https://github.com/pyenv/pyenv/discussions/2408

**Comment by native-api** [comment]
The hang happend inside CPython's build.

The last messages before hanging are from `setup.py`.

Please `export` `DISTUTILS_DEBUG=1` and `PYTHON_MAKE_OPTS="--trace -p"` and run the build again to get more tracing for these specific steps.

---

Your `openssl@1.1` also seems broken. This may be connected to the hanging.

```
*** WARNING: renaming "_ssl" since importing it failed: dlopen(/private/var/folders/9h/j98ts0cn5v59kmt4r13k4k180000gp/T/python-build.20220729113726.92812/Python-3.11-dev/build/lib.macosx-12.5-x86_64-3.11/_ssl.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace (_SSL_get_peer_certificate)
*** WARNING: renaming "_hashlib" since importing it failed: dlopen(/private/var/folders/9h/j98ts0cn5v59kmt4r13k4k180000gp/T/python-build.20220729113726.92812/Python-3.11-dev/build/lib.macosx-12.5-x86_64-3.11/_hashlib.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace (_EVP_MD_block_size)
```

**Comment by brondsem** [comment]
`make` didn't like the `--trace` option: `/Library/Developer/CommandLineTools/usr/bin/make: unrecognized option `--trace'`

So I did `brew install make` and ran with `MAKE=gmake` and then it worked without hanging.

I also got openssl reinstalled and working, but that didn't make a difference whether it hung or not.

Thanks for the pointers!

**Comment by native-api** [comment]
You can use `-d` instead of `--trace` (it doesn't show the same information but is better than nothing).

**Comment by brondsem** [comment]
Ok here's the output of `env DISTUTILS_DEBUG=1 PYTHON_MAKE_OPTS="-d -p" PYENV_DEBUG=1 pyenv install -v 3.11-dev 2>&1 | tee trace.log` up until the point where it hung and I killed it: https://gist.github.com/brondsem/95ffab665d7c65406d5f1aa889baa61e

That said, I did work around the issue with using `gmake` so feel free to close this issue if you wish.  Or if its something that might affect others trying 3.11 and you want to figure it out, I can try any further debugging/workaround commands.

**Comment by ssbarnea** [comment]
I can confirm that the only thing needed was installing make and adding MAKE=gmake, still I do not think that this should be needed, or at least should be implicit if python stops supporting older versions of make (basically the macos version).

**Comment by native-api** [comment]
> Ok here's the output of `env DISTUTILS_DEBUG=1 PYTHON_MAKE_OPTS="-d -p" PYENV_DEBUG=1 pyenv install -v 3.11-dev 2>&1 | tee trace.log` up until the point where it hung and I killed it: https://gist.github.com/brondsem/95ffab665d7c65406d5f1aa889baa61e
> 

> Successfully remade target file `all'.

This suggests that Make has successfully completed... but the following Pyenv logic seems to never get control.
Do you have an active Make process during the hang?

If yes, this looks like Apple's Make hanging on exit.

**Comment by native-api** [comment]
```

> % make -v -d         
> GNU Make 3.81
> Copyright (C) 2006  Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.
> There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
> PARTICULAR PURPOSE.
> 
> This program built for i386-apple-darwin11.3.0
```

They use an old version of GNU make so they are obligated to provide the corresponding source code.
So it's possible to build it from source and debug the issue (or download debug symbols for the stock program to do the same but I didn't find a way to do this. Apple support should know though).

**Comment by brondsem** [comment]
Yes there is an active make process still, when its hung:

```
  UID   PID  PPID   C STIME   TTY           TIME CMD
  502 64789 64745   0  5:05PM ttys006    0:00.06 bash /usr/local/Cellar/pyenv/2.3.3/plugins/python-build/bin/python-build -v 3.11-dev /Users/brondsem/.pyenv/versions/3.11-dev
  502 64819 64789   0  5:05PM ttys006    0:00.09 tail -f /var/folders/9h/j98ts0cn5v59kmt4r13k4k180000gp/T/python-build.20220816170507.64789.log
  502 74619 64789   0  5:07PM ttys006    0:02.04 /Library/Developer/CommandLineTools/usr/bin/make -j 8 -d -p
```

I don't know anything about debugging binaries ☹️

**Comment by native-api** [comment]
Well, you can report that to Apple.
I presume they'll need reproduction steps or access to you machine to reproduce the issue, but who knows.
Maybe they already have access to your machine... :eye:

**Comment by ssbarnea** [comment]
@native-api Apple would not be the only company with access it, also my employer, Red Hat. I also suspect that the corporate imposed SentinelOne could cause this but I am unable to remove it. I mentioned it here because maybe we can cross-correlate the issue with others. IMHO I doubt it is a bug in make because we would have seen far more reports.

At least I am glad that I was able to find an workaround.

**Comment by ssbarnea** [comment]
Sadly the problem is still valid and pyenv could at least add the `MAKE=gmake` itself. I am not sure if the not-in-my-garden was the best approach here.

**Comment by native-api** [comment]
This problem affects two people and is caused by their, unknown, environment being plain broken, in some, unknown, way.

Not sure why you think a workaround for something like that belongs in Pyenv and not that environment.
