### ISSUE TITLE
pyenv install python 3.6.13 failed on M1 pro Monterey

### ISSUE THREAD

**Issue by shezhangzhang** [pyenv/pyenv#2429]
<img width="752" alt="image" src="https://user-images.githubusercontent.com/26793777/182538578-59e21f3f-c48d-4617-92e7-a7dc82812c31.png">

I looked at a lot of issues, but couldn't solve it on my mac.
Latest mac(m1 pro), latest macos.

**Comment by native-api** [comment]
For 3.6.15, we provide patches to support MacOS 11+ (See https://github.com/pyenv/pyenv#python-versions-with-extended-support).

**Comment by shezhangzhang** [comment]
> For 3.6.15, we provide patches to support MacOS 11+ (See https://github.com/pyenv/pyenv#python-versions-with-extended-support).

What about 3.6.13?

**Comment by native-api** [comment]
We accept patches from interested users, even for EOL versions. See https://github.com/pyenv/pyenv/blob/master/CONTRIBUTING.md#deprecation-policy.

Alternatively, you can commission us to do that for you by either donating or by offering a bounty on this issue at https://gitpay.me.

**Comment by yueismyname** [comment]
I came across same issue, @shezhangzhang did you solve it?

**Comment by shezhangzhang** [comment]
> I came across same issue, @shezhangzhang did you solve it?

@yueismyname No, I didn't, I used my stale intel Mac🥲
