### ISSUE TITLE
SSL certificate error (curl 60) during installation of python 3.10.6

### ISSUE THREAD

**Issue by BawiFrog** [pyenv/pyenv#2435]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS Mojave 10.14.6
- [x] OS architecture (e.g. amd64): x86_64-apple-darwin18.7.0
- [x] pyenv version: 2.3.3
- [x] Python version: 3.10.6
- [x] C Compiler information (e.g. gcc 7.3): clang-1001.0.46.4
- [x] Please attach the debug trace of the failing command as a gist:
[trace.log](https://github.com/pyenv/pyenv/files/9334077/trace.log)

During the process of installing python through the command "pyenv install -v 3.10.6", the process is unsuccessful following a "curl: (60) SSL certificate problem: certificate has expired" error.
The problem seems to reside in the downloading of the file "readline-8.1.tar.gz" with the url "https://ftpmirror.gnu.org/readline/readline-8.1.tar.gz".
I tried to override the expired certificate through the "curl -k" and "curl --insecure" command lines but it doesn't seem to work.

I sincerely apologize if this is a personal problem as after trying every solution I could think of I still can't install python in pyenv and thought this error might have its place in the Issues section of this repository.

**Comment by native-api** [comment]
WFM atm. Was a problem with the remote server.

It's possible to work around it by replacing the corresponding URL in the Pyenv source with a working one. (Make sure that the archive is the same or remove the `#<hash>` suffix to the URL, too, if it's present (it's a hash that the download is checked against).)
