### ISSUE TITLE
Multiple entries of PYENV_ROOT prefix in .bashrc and .zshrc, causing delays when opening the terminal

### ISSUE THREAD

**Issue by arunpdl** [pyenv/pyenv#2436]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): Manjaro Linux (21.3.6)
- [ ] OS architecture (e.g. amd64): amd64
- [ ] pyenv version: 2.3.1
- [ ] Python version: 3.10.5
- [ ] C Compiler information (e.g. gcc 7.3): 12.1.1
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

There seems to be multiple entries of prefix being created on my ~/.bashrc and ~/.zshrc.
`
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
`

The number of entries seems to be increasing upon usage which is causing bash and zsh to start with significant delay.

**Comment by native-api** [comment]
Looks like someone misunderstood the README instructions.

The `echo <smth> >>~/.bashrc` lines are meant to be executed interactively, not copied into your `rc` files verbatim.

@janithpet [has already improved the wording to clarify this](https://github.com/pyenv/pyenv/pull/2431). Maybe other similar parts could use the same?

**Comment by janithpet** [comment]
> Looks like someone misunderstood the README instructions.
> 
> The `echo <smth> >>~/.bashrc` lines are meant to be executed upon Pyenv installation (interactively or otherwise), not copied into your `rc` files verbatim.
> 
> @janithpet [has already improved the wording to clarify this](https://github.com/pyenv/pyenv/pull/2431). Maybe other similar parts could use the same?

Made a PR with some changes. I think this should be clear now?

**Comment by Alejandroacho** [comment]
Im having the same issue, any help to solve it? its very annoying, I uninstalled pyenv due to this but this error still hapening

**Comment by vinodpandey** [comment]
@Alejandroacho please make sure that you don't have below code in your `~/.bashrc`, `~/.zshrc` or `/.zprofile` with `echo`. 

```
echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
echo 'eval "$(pyenv init -)"' >> ~/.zshrc
```

The correct entry that should be in your `~/.zshrc` is below

```
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```

**Comment by nexgen** [comment]
I'm getting the exact same problem. There's no command with echo in these files: ~/.bashrc, ~/.zshrc or /.zprofile

**Comment by kalanaw** [comment]
> I'm getting the exact same problem. There's no command with echo in these files: ~/.bashrc, ~/.zshrc or /.zprofile

Same here. Can't find what exactly keep adding these lines each time I open the terminal window/tab.

**Comment by native-api** [comment]
Launch your shell with tracing on. That should show all startup commands it runs.

**Comment by emurano** [comment]
ZSH users, just make sure your ~/.zprofile file doesn't have the installation comments. That's what got me, as I was just looking at my ~/.zshrc file initially.
