### ISSUE TITLE
/opt/pyenv/pyenv.d/install/latest.bash: line 5: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by yalh76** [pyenv/pyenv#2451]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Debian 11
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 2.3.4-1-g4e31668c
- [x] Python version: 3.9.2
- [x] C Compiler information (e.g. gcc 7.3):  10.2.1 20210110
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

since https://github.com/pyenv/pyenv/commit/4e31668c2136bd7c97b30776da62e80e9a376279
[trace.log](https://github.com/pyenv/pyenv/files/9492025/trace.log)

**Comment by yalh76** [comment]
@native-api seems your last commit cause an issue ^^

**Comment by Djelibeybi** [comment]
Can confirm that reverting the change resolves the issue on Oracle Linux 9.

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/commit/23559ee6d10c5c702f924803b81eaa54a776b360

Looks like there cannot be any space between the `=` from variable assignment and the `(` that opens an array initializer. Figures.

**Comment by yalh76** [comment]
> [23559ee](https://github.com/pyenv/pyenv/commit/23559ee6d10c5c702f924803b81eaa54a776b360)
> 
> Looks like there cannot be any space between the `=` from variable assignment and the `(` that opens an array initializer. Figures.

Thanks, issue fixed :)

**Comment by stillborn333** [comment]
git push --set-upstream git@gitlab.com:chaddouthit0/$(git rev-parse --show-toplevel | xargs basename).git $(git rev-parse --abbrev-ref HEAD)
