### ISSUE TITLE
new release please?

### ISSUE THREAD

**Issue by davidszotten** [pyenv/pyenv#2462]
Hi,

Any chance of a a new release that includes the ([CPython security releases 3.7.14, 3.8.14 and 3.9.14](https://github.com/pyenv/pyenv/commit/a0fbdad292811101320c7cb1142f82a5b2e8f827))

Thank you!

**Comment by native-api** [comment]
You can install a head version of Pyenv, for both Git checkout and Homebrew, at any time. You aren't constrained by the release schedule.

**Comment by tim-schilling** [comment]
@native-api I'm not sure that's true. I've updated my brew instance of pyenv to HEAD as of a few days ago (093d0b3), and it still can't find 3.10.7

```
$ brew upgrade pyenv
Warning: pyenv HEAD-093d0b3 already installed
$ pyenv install 3.10.7
python-build: definition not found: 3.10.7
```

**Comment by tim-schilling** [comment]
- [x] Platform information (e.g. Ubuntu Linux 16.04): Macbook Air M1, 2020, 
- [x] OS architecture (e.g. amd64): ARM, arm64-apple-darwin21.6.0
- [x] pyenv version: 2.3.4, but HEAD - 5b08a649
- [x] Python version: Trying to install 3.10.7
- [x] C Compiler information (e.g. gcc 7.3):  Apple clang version 14.0.0 (clang-1400.0.29.102)
- [x] Please attach the debug trace of the failing command as a gist: 
[trace.log](https://github.com/pyenv/pyenv/files/9629679/trace.log)

**Comment by native-api** [comment]
From the trace, you're still running 2.3.4. A head version should be in `/opt/homebrew/Cellar/pyenv/HEAD-5b08a64`.

Make sure that your PATH is right and `brew` and `pyenv` run what you think they run.

**Comment by tim-schilling** [comment]
Ugh. `brew link pyenv --HEAD` was what I was missing. Thanks @native-api

**Comment by gwerbin** [comment]
As per the original request in this thread: it would be great to have a v2.3.5 release that includes these new versions!

Is there anything that I or any other community members can do, in order to help make that happen?

Many package managers (e.g. Homebrew) refuse to package "head/trunk/master/dev" versions, and many workflows (e.g. setting up a consistent development environment across several developers' machines) depend on tagged releases for consistency.

**Comment by robbieaverill** [comment]
+1 on a new release. For me:

```
% pyenv --version
pyenv 2.3.4

% pyenv install 3.9.14
python-build: definition not found: 3.9.14

See all available versions with `pyenv install --list'.

If the version you need is missing, try upgrading pyenv:

  brew update && brew upgrade pyenv

% brew update && brew upgrade pyenv
...
Warning: pyenv 2.3.4 already installed
```

A 2.3.5 release would presumably make 3.9.14 installable via homebrew for me.
