### ISSUE TITLE
Pyenv install 3.6.15 on Mac m1

### ISSUE THREAD

**Issue by Robin1980** [pyenv/pyenv#2465]
The error exists to all the python versions higher than 3.6.15, I tried the 3.7.*, 3.8.*, 3.9.* and 3.10.*.  All trials are with the similar errors.  Meanwhile, the error happens to all the OSx 12.*.   

python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.6.15.tar.xz...
-> https://www.python.org/ftp/python/3.6.15/Python-3.6.15.tar.xz
Installing Python-3.6.15...
patching file configure
patching file configure.ac
patching file Misc/NEWS.d/next/macOS/2019-06-03-05-49-49.bpo-36231.RfmW_p.rst
patching file setup.py
patching file setup.py
patching file Doc/library/ctypes.rst
patching file Lib/test/test_unicode.py
patching file Modules/_ctypes/_ctypes.c
patching file Modules/_ctypes/callproc.c
patching file Modules/_ctypes/ctypes.h
patching file setup.py
patching file Misc/NEWS.d/next/macOS/2020-06-24-13-51-57.bpo-41100.mcHdc5.rst
patching file configure
patching file configure.ac
patching file 'Misc/NEWS.d/next/Core and Builtins/2020-06-30-04-44-29.bpo-41100.PJwA6F.rst'
patching file Modules/_decimal/libmpdec/mpdecimal.h
patching file setup.py
patching file Misc/NEWS.d/next/Build/2021-10-11-16-27-38.bpo-45405.iSfdW5.rst
patching file configure
patching file configure.ac
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 12.6 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/cc/wsp5_wnj30x_p87x_76s1tvc0000gn/T/python-build.20220915172842.88885
Results logged to /var/folders/cc/wsp5_wnj30x_p87x_76s1tvc0000gn/T/python-build.20220915172842.88885.log

Last 10 log lines:
        if ((size_t)required_capacity > SIZE_MAX / sizeof(node)) {
            ~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~
221 warnings and 10 errors generated.
make: *** [Parser/node.o] Error 1

**Comment by native-api** [comment]
Please provide the necessary diagnostic information as per the issue template.
