### ISSUE TITLE
pyenv build arch64 python failed

### ISSUE THREAD

**Issue by Jokky6** [pyenv/pyenv#2470]
> You're trying to build for Arm64 but are using Pyenv from an x64 Homebrew installation.
> 
> As a rule, you should have the same installation of Homebrew in PATH as your current architecture, use Pyenv from that installation, and set `PYENV_ROOT` differently depending on architecture to avoid mixing up stuff for the two architectures. (See [#1853 (comment)](https://github.com/pyenv/pyenv/issues/1853#issuecomment-847827280) and [#1853 (comment)](https://github.com/pyenv/pyenv/issues/1853#issuecomment-847886256) for an example.)
> 
> Regardless, in the log, I do see that Pyenv adds the correct compiler switches to use libs from the Arm64 Homebrew. So it seems strange that `ld` picks a wrong instance of `libintl`.
> 
> Do you have `gettext` in the Arm64 Homebrew installed and linked? There should be a `libintl*.so` in `/opt/homebrew/lib`, built for the Arm64 architecture.
> 
> If you have it, check if it has the exported symbols that the linker complains about.

Before I ask the question, I had try the way.
But the arch 64 builds failed！

_Originally posted by @Jokky6 in https://github.com/pyenv/pyenv/issues/2441#issuecomment-1255725190_

**Comment by native-api** [comment]
Closing as apparently posted by mistake.
