### ISSUE TITLE
Build failed for python 3.8.[1-3], macOS x86_64

### ISSUE THREAD

**Issue by alxrey** [pyenv/pyenv#2473]
Impossible to install python 3.8.1, 3.8.2 or 3.8.3.
I still obtain the following error:
```
Installing Python-3.8.1...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 12.6 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/z0/3p2k6mjd2c3fsr1np1pp97k80000gn/T/python-build.20221003220517.22187
Results logged to /var/folders/z0/3p2k6mjd2c3fsr1np1pp97k80000gn/T/python-build.20221003220517.22187.log

Last 10 log lines:
checking for --with-cxx-main=<compiler>... no
checking for clang++... no
configure:

  By default, distutils will build C++ extension modules with "clang++".
  If this is not intended, then set CXX on the configure command line.
  
checking for the platform triplet based on compiler characteristics... darwin
configure: error: internal configure error for the platform triplet, please file a bug report
make: *** No targets specified and no makefile found.  Stop.
```

I had a look on similar problems and possible solutions but nothing worked.

### Description
- Platform information: macOS 12.6 (Intel)
- OS architecture: x86_64 Darwin 21.6
- pyenv version: 3.10.1
- Python version: 3.8.[1-3]
- C Compiler information: Apple clang version 14.0.0 (clang-1400.0.29.102)
- debug trace of the failing command: https://gist.github.com/alxrey/c94628178bdbc9d4e9ec1fd078e2e31b

**Comment by smokaleksander** [comment]
Same issue on macOS 12.6 with M1 chip.
Trying to install python 3.7.0.
Installing llvm(clang++) did not help.

**Comment by native-api** [comment]
Pythons <3.7.8 and <3.8.4 do not support MacOS 11+.
(As an indicator, we've provided patches to support XCode 13.3 only for those who do, see https://github.com/pyenv/pyenv#python-versions-with-extended-support .)

**Comment by alxrey** [comment]
Oh okay thanks for the information. But I've a software which is based on Python (a dedicated version of Python is installed with it), the version is the 3.8.2 and the software works perfectly well.
Does it mean that it uses another intermediate tool to make it works ?

**Comment by smokaleksander** [comment]
I had successfully installed version 3.7.13 so iI think the problem is caused by something else than lack of support of macOS 11+

**Comment by native-api** [comment]
> Oh okay thanks for the information. But I've a software which is based on Python (a dedicated version of Python is installed with it), the version is the 3.8.2 and the software works perfectly well. Does it mean that it uses another intermediate tool to make it works ?

They probably use a patched Python with the appropriate changes backported.
We do accept patches for supporting other environments from interested parties, see https://github.com/pyenv/pyenv/blob/master/CONTRIBUTING.md#adding-version-specific-fixespatches
