### ISSUE TITLE
Can a release be done?

### ISSUE THREAD

**Issue by deronnax** [pyenv/pyenv#2474]
Hello.
Can a release be done? Python 3.7.14 has been released a month ago and it's still not available via pyenv. If there is a guideline on how to release, I volunteer to do it.
Cheers

**Comment by native-api** [comment]
My last few days were rather exhausting. I'll do it on Thursday if no-one does it before.

There is a guideline, I was planning to put it into some file someday, e.g. "MAINTENANCE.md", but it requires appropriate rights:

* In the Changelog, insert changes description (slightly reformatted autogenerated release summary, only the changes section).
  * the autogenerated summary may need some editing (e.g. rephrase entries, remove entries that are too minor (e.g. a documentation typo fix)
* In https://github.com/pyenv/pyenv/blob/master/libexec/pyenv---version , change the version.
* Create and push the tag
* Make the release from the tag, using autogenerated release summary.

**Comment by deronnax** [comment]
Thank you. If it's not done Thursday, I will give it a look Friday.

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/releases/tag/v2.3.5

**Comment by deronnax** [comment]
thank you so much 🙏
