### ISSUE TITLE
Python 3.10.8 build fails with /usr/local/opt/llvm/bin/llvm-ar: error: libpython3.10.a: Invalid record

### ISSUE THREAD

**Issue by scolby33** [pyenv/pyenv#2485]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS 12.6
- [x] OS architecture (e.g. amd64): amd64 AND Apple M1 ARM
- [x] pyenv version: HEAD ([03a5d65](https://github.com/pyenv/pyenv/commit/03a5d65387db282f77a8bc92581cd734133329b5))
- [x] Python version: 3.10.8
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 14.0.0 (clang-1400.0.29.102)
- [x] Please attach the debug trace of the failing command as a gist: [trace.log](https://github.com/pyenv/pyenv/files/9778510/trace.log) (trace is from my amd64 machine, but I can provide one from the M1 ARM machine if necessary as well)

EDIT:
I realized I should check if this is just a 3.10.8 problem or if it is more general. Unfortunately, it is more general. It also happens with 3.10.6 and 3.9.15. I struggled a while back with llvm-ar and LTO, and my setup hasn't changed since then. Python 3.10.7 built fine on September 12 of this year. I'm not sure if there has been an update to pyenv that could've caused this or if my version of llvm (from Homebrew) or clang (from Apple) has changed in the meantime. Any insight would be appreciated.

**Comment by native-api** [comment]
CPython only officially supports Apple's toolchain.
Delete Homebrew's LLVM from PATH.
