### ISSUE TITLE
fail to build package using pyenv python.

### ISSUE THREAD

**Issue by dongwangdw** [pyenv/pyenv#2490]
I am in ubuntu 22.04 with python 3.10.
I installed python 3.9 with pyenv.
I tried to install apach-airflow 2.2.3 failed to build it.
error said: setuptools not available.
But I did have setuptools availbe in .pyenv/.... path.

Is this a bug or misconfig? Please help.

**Comment by native-api** [comment]
Please provide the necessary diagnostic info as per the issue template.
