### ISSUE TITLE
System pip vs pyenv python pip

### ISSUE THREAD

**Issue by otrejo-soria** [pyenv/pyenv#2491]
As part of our wheel build creation process, we use pyenv to build with different python version, but we stumble upon the following problem where pyenv pip (from one of the pyenv python versions we installed) couldn't install the wheel and I think we have narrow it down to the following.

When we run system python pip as follows , we get:
```
v
mac-9bc3f:libmacho localadmin$ python3 --version
Python 3.10.7
mac-9bc3f:libmacho localadmin$ python3 -m pip --version
pip 22.3 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)
mac-9bc3f:libmacho localadmin$ python3 -m pip debug verbose | less
....
Compatible tags: 1945
  cp310-cp310-macosx_11_0_x86_64
  cp310-cp310-macosx_11_0_intel
  cp310-cp310-macosx_11_0_fat64
  cp310-cp310-macosx_11_0_fat32
  cp310-cp310-macosx_11_0_universal2
  cp310-cp310-macosx_11_0_universal
  cp310-cp310-macosx_10_16_x86_64
  cp310-cp310-macosx_10_16_intel
  cp310-cp310-macosx_10_16_fat64
  cp310-cp310-macosx_10_16_fat32
  ...
  [First 10 tags shown. Pass --verbose to show all.]
```

where as using pip from `pyenv install --skip-existing -v 3.10.7`, we get
```
mac-9bc3f:libmacho localadmin$ ~/.pyenv/versions/3.10.7/bin/python --version
Python 3.10.7
mac-9bc3f:libmacho localadmin$ ~/.pyenv/versions/3.10.7/bin/python -m pip --version
pip 22.3 from /Users/localadmin/.pyenv/versions/3.10.7/lib/python3.10/site-packages/pip (python 3.10)
mac-9bc3f:libmacho localadmin$ ~/.pyenv/versions/3.10.7/bin/python -m pip debug --verbose | less
...
Compatible tags: 1807
  cp310-cp310-macosx_10_16_x86_64
  cp310-cp310-macosx_10_16_intel
  cp310-cp310-macosx_10_16_fat64
  cp310-cp310-macosx_10_16_fat32
  cp310-cp310-macosx_10_16_universal2
  cp310-cp310-macosx_10_16_universal
  cp310-cp310-macosx_10_15_x86_64
  cp310-cp310-macosx_10_15_intel
  cp310-cp310-macosx_10_15_fat64
  cp310-cp310-macosx_10_15_fat32
  cp310-cp310-macosx_10_15_universal2
  cp310-cp310-macosx_10_15_universal
  cp310-cp310-macosx_10_14_x86_64
  cp310-cp310-macosx_10_14_intel
  cp310-cp310-macosx_10_14_fat64
  cp310-cp310-macosx_10_14_fat32
  cp310-cp310-macosx_10_14_universal2
  cp310-cp310-macosx_10_14_universal
  cp310-cp310-macosx_10_13_x86_64
  cp310-cp310-macosx_10_13_intel
  cp310-cp310-macosx_10_13_fat64
  cp310-cp310-macosx_10_13_fat32
  cp310-cp310-macosx_10_13_universal2
  cp310-cp310-macosx_10_13_universal
```
 As you can notice, there is no Mac 11: `cp310-cp310-macosx_11_0_x86_64` vs `cp310-cp310-macosx_10_16_x86_64`.

Any ideas?

**Comment by native-api** [comment]
Could you please add the diagnostic information as per the issue template?

AFAIK, all Pyenv does about MacOS compatibility tags from its side is [set the envvar `MACOS_DEPLOYMENT_TARGET` envvar to the version of the running MacOS as reported by `sw_vers -productVersion`](https://github.com/pyenv/pyenv/blob/03a5d65387db282f77a8bc92581cd734133329b5/plugins/python-build/bin/python-build#L2266-L2275). Anything beyond that must be coming from CPython's build logic.

So the Pyenv-built Python should have tags corresponding to the running MacOS -- and if it's `10.16`, of course you can't run wheels built for `11.0` on it.

**Comment by otrejo-soria** [comment]
I am running:
```
sw_vers -productVersion
11.7
pyenv --version
pyenv 2.3.5
```
And the problem is that pip from pyenv python cannot install my wheel. Ex:
```
~/.pyenv/versions/3.10.7/bin/python -m pip install mywheel-0.0.dev5539721925150-cp310-cp310-macosx_11_0_x86_64.whl
ERROR: mywheel-0.0.dev5539721925150-cp310-cp310-macosx_11_0_x86_64.whl is not a supported wheel on this platform.
```

where is if I use the system pip like so , it works:
```
python3 -m pip install mywheel-0.0.dev5539721925150-cp310-cp310-macosx_11_0_x86_64.whl
Processing mywheel-0.0.dev5539721925150-cp310-cp310-macosx_11_0_x86_64.whl
Installing collected packages: mywheel
Successfully installed mywheel-0.0.dev5539721925150
```

And it all comes down to the pyenv pip that it installed. At least that is what I think it is happening because of tags shown above. I ran pyenv in my mac 11. 

I also just did this 
```
mac-9bc3f:libmacho localadmin$ python3
Python 3.10.7 (main, Sep 15 2022, 01:52:03) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> print(platform.mac_ver())
('11.7', ('', '', ''), 'x86_64')
>>> exit()
mac-9bc3f:libmacho localadmin$ ~/.pyenv/versions/3.10.7/bin/python
Python 3.10.7 (main, Oct 21 2022, 10:45:57) [Clang 12.0.0 (clang-1200.0.32.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> print(platform.mac_ver())
('10.16', ('', '', ''), 'x86_64')
```
Each of the python interpreter are returning different versions so whatever pyenv python is using seems to be wrong. Not sure how pyenv gets their versioning in a mac 11

**Comment by native-api** [comment]
> Python 3.10.7 (main, Oct 21 2022, 10:45:57) [Clang 12.0.0 (clang-1200.0.32.2)] on darwin

I suggest upgrading your XCode command-line tools. In MacOS 12 with XCode 14, I'm getting correct tags.

Deduced that from the old compiler version (XCode 13 has CLang 13) and from fact that "10.16" actually means early versions of Big Sur. Your compiler probably can't emit anything newer.

**Comment by otrejo-soria** [comment]
I updated to to xcode 13.4 and now I am getting the right version. Unfortunately, I cannot upgrade to mac 12 yet, but I am happy with the use of a newer xcode. Thanks for the help :D
