### ISSUE TITLE
Pyenv.cfg - no mention at all, literally anywhere.

### ISSUE THREAD

**Issue by altimmons** [pyenv/pyenv#2492]
Just a quick statement: 

No documentation at all for pyenv.cfg anywhere at all.  Not mentioned in Readme or docs. And even a google search turns up junk.
If the answer is dont touch it, then add that to readme.  But I have no idea the keys I can add.  I want to add another directory to path in the venv.  The path is in the main folder but not in venv.  It needs to locate these fuoes- which are not libraries or pkgs but internal code classes and methods.

**Comment by joshfriend** [comment]
Are you talking about [`pyvenv.cfg`](https://docs.python.org/3/library/venv.html)? There's no concept of a `pyenv.cfg` in pyenv, which is why it has no docs and is not mentioned on google. `pyvenv.cfg` (with a `v`) is a concept related to the venv module and not pyenv.

**Comment by altimmons** [comment]
Yes,  you are correct, it is either VS Code or a plugin creating and
reading it, not sure which.  Sorry about the confusion.  More info on the
file would be great, but theres more than one way to skin a cat, so I got
it done.
