### ISSUE TITLE
pyenv 2.3.5 does not see python 3.10.8

### ISSUE THREAD

**Issue by kurtgn** [pyenv/pyenv#2498]
### Description
- [x] Platform information: `MacOS Mojave 10.14.6 `
- [x] OS architecture:  `x86_64`
- [x] pyenv version: `2.3.5`
- [x] Python version: `3.10.8`
- [x] C Compiler information : `4.2.1`

```
$ pyenv --version
pyenv 2.3.5

$ pyenv install --list | grep 3.10
  3.10.0
  3.10-dev
  3.10.1
  3.10.2
  3.10.3
  3.10.4
  3.10.5
  3.10.6
  3.10.7
  mambaforge-4.10.3-10
  miniconda-3.10.1
  miniconda3-3.10.1
  miniforge3-4.10.3-10
```

Should I just wait for new pyenv version or there's something wrong with my system?

**Comment by polydevuk** [comment]
Install the python-build plugin then go to .pyenv/plugins/python-build and `git pull`.

**Comment by native-api** [comment]
You can install the head version with `brew install pyenv --head`.
