### ISSUE TITLE
Rehash shebang lines

### ISSUE THREAD

**Issue by Bilge** [pyenv/pyenv#2502]
I am copying the `.pyenv` directory from one user to another. I can fix the shims with `pyenv rehash` but the shebang lines still point to the old user. How do I rehash the shebang lines?

**Comment by native-api** [comment]
WDYM "shebang lines still point to the old user"? They should always be `#!/usr/bin/env bash`.

**Comment by Bilge** [comment]
But they're not, they're hard-coded to the user's home directory.

**Comment by native-api** [comment]
Then you seem to have something custom.

Please provide the diagnostic info as per the issue template for us to be able to say anything more specific.

**Comment by native-api** [comment]
> And why would they be pointing to Bash anyway? They're python scripts.

You probably mean not Pyenv shims (in `$PYENV_ROOT/shims`) but executables for installed Python packages. Pyenv doesn't touch those, it's Pip or Setuptools that creates them IIRC.

**Comment by Kfelts** [comment]
I'm having this same exact problem. It's taken a lot of research and rabbit holes to end up on this thread, but the shebangs on mine have also been changed, preventing pip from installing in the proper virtualenv.
