### ISSUE TITLE
`pyenv-latest` may report the wrong prefix

### ISSUE THREAD

**Issue by aurelg** [pyenv/pyenv#2519]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): Archlinux, up to date as of 2022-11-08
- [X] OS architecture (e.g. amd64): amd64
- [X] pyenv version: latest from master, ie. 904fe96
- [X] Python version: tested w/ 3.10.4 and 3.11.0
- [C] C Compiler information (e.g. gcc 7.3): gcc 12.2.0
- [ ] Please attach the debug trace of the failing command as a gist: (irrelevant)

Since commit a12f947cc3b21e908648d063229678147c09e7be, I noticed that my prefixes are not automatically detected correctly, as they were with 0b5e16add3b5d9bd3608804b786d43afc5640ce0.

Say I have two environments, eg. `MY-SUPER-PREFIX` and `MY-SUPER`. When `MY-SUPER` is set in a `.python-version` file, I would expected `MY-SUPER` to be activated. Yet, it's `MY-SUPER-PREFIX` that gets activated.

I traced the issue back to https://github.com/pyenv/pyenv/pull/2487, and more specifically to [pyenv-latest:43](https://github.com/pyenv/pyenv/blob/master/libexec/pyenv-latest#L43):

```sh
grep -Ee "^$prefix_re[-.]" || true))
```

This line greps the current prefix followed by a `-` or a `.`, and anything else. In my case, the prefix `MY-SUPER` would match both `MY-SUPER` and `MY-SUPER-PREFIX`.

The following lines filter a bit further, but not enough to remove the spurious `MY-SUPER-PREFIX`, which eventually gets activated instead of `MY-SUPER`.

I'm not sure how to solve this issue.

The problem would be solved by replacing line 43 with the following, but part of the magic is lost.

```sh
grep -Ee "^$prefix_re$" || true))
```

Another option would be to whitelist what is allowed (`dev`, `src`, `latest`, etc...) (but that could also collide as well with other prefixes):

```sh
grep -Ee "^$prefix_re[\-(dev|src|latest|(b|rc)[0-9]+)]*$" || true))
```

However, if the magic gets broken, I feel it should either be fixed, or made optional?

**Comment by native-api** [comment]
A solution would be to make a complete name resolve to itself.

I hesitated to add that because that's already done by the selecting subcommands if prefix resolution fails -- that would be duplicate no-op functionality which would make us prone to do unneeded work. Subcommands do need to default to what the user passed if prefix resolution fails in order to show an informative error message with the bogus name when it fails somewhere down the line.

The idea was that for a complete name, prefix resolution would fail and the subcommand would proceed with the name.
But I didn't have a case when one complete name is a valid prefix of another -- so the resolution would succeed when it shouldn't...
