### ISSUE TITLE
/var/lib/snapd/void Permission denied while pyenv install (Ubuntu 22.04.1 LTS)

### ISSUE THREAD

**Issue by PeterZhizhin** [pyenv/pyenv#2522]
I am trying to run `pyenv install 3.10.8` and get the following error: `Failed to open the file /var/lib/snapd/void/Python-3.10.8.tar.xz, cause: Permission denied`

I am not sure why it happens, because it used to work on a previous Ubuntu version (18.04).

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 22.04.1 LTS
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: pyenv 2.3.6-6-g8dd46e39
- [x] Python version: 3.10.8 
- [x] C Compiler information (e.g. gcc 7.3): `gcc --version` gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
- [x] Please attach the debug trace of the failing command as a gist: https://gist.github.com/PeterZhizhin/eb5ad804c034b7bb750baf9220226e3d
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

**Comment by native-api** [comment]
Diagnosing it with `strace` and searching around, it turns out that **snap applications** -- which your `aria2c` is -- **cannot access `/tmp`.**
Which is where Pyenv does the build stuff and needs to download things into.

As a workaround, you can set `PYTHON_BUILD_HTTP_CLIENT` envvar to `curl` or `wget` to use that rather than `aria2c`.

**Comment by native-api** [comment]
We can work around that, but I'm not sure what the best course of action would be.

Should we just skip using aria2c in such a case, or should we download somewhere else?
