### ISSUE TITLE
"The Python ssl extension was not compiled" with Linuxbrew installed despite OpenSSL is present

### ISSUE THREAD

**Issue by Studio-user** [pyenv/pyenv#2523]
### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 22.04
- [x] OS architecture (e.g. amd64): 64bit
- [x] pyenv version: 2.3.6
- [ ] Python version: XXXXXXXX
- [x] C Compiler information (e.g. gcc 7.3): gcc 11.3.0
- [x] Please attach the debug trace of the failing command as a gist:

I want to download python version 3.7.13 and 3.8.13 through pyenv but it doesn't work.
It's Ubuntu 22.04 on VirtualBox

`pyenv install -v 3.8.13`

########################################################
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.

https://github.com/pyenv/pyenv/wiki/Common-build-problems

BUILD FAILED (Ubuntu 22.04 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20221110215218.56192

Results logged to /tmp/python-build.20221110215218.56192.log

Last 10 log lines:

		install|*) ensurepip="" ;; \

	esac; \

	 ./python -E -m ensurepip \

		$ensurepip --root=/ ; \

fi

Looking in links: /tmp/tmppxa9p8mc

Processing /tmp/tmppxa9p8mc/setuptools-56.0.0-py3-none-any.whl

Processing /tmp/tmppxa9p8mc/pip-22.0.4-py3-none-any.whl

Installing collected packages: setuptools, pip

Successfully installed pip-22.0.4 setuptools-56.0.0
########################################################

The error is like this.

I tried
`LDFLAGS="-Wl,-rpath,$(brew --prefix openssl)/lib" \
CPPFLAGS="-I$(brew --prefix openssl)/include" \
CONFIGURE_OPTS="--with-openssl=$(brew --prefix openssl)" \`

also
`CPPFLAGS="-I<openssl install prefix>/include" \
LDFLAGS="-L<openssl install prefix>/lib" \`

and reinstall libssl, upgrade libssl

If I didn't use -v option, there was a path error but not now, I don't know why.
maybe because I added path that /home/"username"/.python blabla to ~/.bashrc

**Comment by native-api** [comment]
Please provide the required diagnostic information as per the issue template. Please also provide `config.log` from the build directory.

**Comment by Studio-user** [comment]
pyenv install 3.8.13

Downloading Python-3.8.13.tar.xz...

-> https://www.python.org/ftp/python/3.8.13/Python-3.8.13.tar.xz

Installing Python-3.8.13...

ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?



Please consult to the Wiki page to fix the problem.

https://github.com/pyenv/pyenv/wiki/Common-build-problems





BUILD FAILED (Ubuntu 22.04 using python-build 20180424)



Inspect or clean up the working tree at /tmp/python-build.20221110232933.2458

Results logged to /tmp/python-build.20221110232933.2458.log



Last 10 log lines:

		install|*) ensurepip="" ;; \

	esac; \

	 ./python -E -m ensurepip \

		$ensurepip --root=/ ; \

fi

Looking in links: /tmp/tmpwfpq7rv_

Processing /tmp/tmpwfpq7rv_/setuptools-56.0.0-py3-none-any.whl

Processing /tmp/tmpwfpq7rv_/pip-22.0.4-py3-none-any.whl

Installing collected packages: setuptools, pip

Successfully installed pip-22.0.4 setuptools-56.0.0

**Comment by Studio-user** [comment]
How can I find the debug trace?
I found the `config.log` file but can't copy the contents. I'm really sorry but can you explain it?

**Comment by kb-** [comment]
I had the same issue on Ubuntu 22.04. It worked after running `sudo apt-get install python-openssl`

**Comment by binbjz** [comment]
> How can I find the debug trace? I found the `config.log` file but can't copy the contents. I'm really sorry but can you explain it?

```sh
env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log
```

**Comment by Jengamon** [comment]
I'm having a similar problem, probably because I'm Homebrewing on Ubuntu but anyways, I'm on pyenv 2.3.7 and trying to install python version 3.11.0.

Below is the debug trace from @binbjz's command, so 
```     
env PYENV_DEBUG=1 pyenv install -v 3.11.0 2>&1 | tee trace.log
```
[trace.log](https://github.com/pyenv/pyenv/files/10137165/trace.log)

**Comment by native-api** [comment]
@Jengamon from your log, it looks like OpenSSL is not installed. Please make sure that you've installed the [Python build dependencies](https://github.com/pyenv/pyenv/wiki#suggested-build-environment).

**Comment by Jengamon** [comment]
The problem is that it *is* installed, both the apt package, and on Home-brew, where I have pyenv installed. (openssl@1.1, and openssl@3)

**Comment by Jengamon** [comment]
I also have tried manually pointing to OpenSSL with a `CONFIGURE_OPTS="--with-openssl='/home/linuxbrew/.linuxbrew/opt/openssl@3'"` or something to that effect, let me actually try it again soon on the machine.

**Comment by Jengamon** [comment]
@native-api 
I've also tried copy-pasting from the build instructions, both the brew command and the Ubuntu command, do you think the error has something to do with the fact I've installed pyenv on Homebrew on Ubuntu?
I have both openssl 3 and 1.1 Homebrew packages installed, and I have tried with apt package libssl-dev installed and not...

**Comment by native-api** [comment]
Pyenv currently doesn't use dependencies from Linuxbrew (linking against them requires additional compiler switches and breaks things when you upgrade them). Install the Apt package and unset any compiler-affecting envvars pointing to Linuxbrew.

**Comment by Jengamon** [comment]
Ok, so it seems that I have to remove pointing to linuxbrew *and* manually remove Linuxbrew pkg-config with a `brew remove --ignore-dependencies pkg-config`. Once I did both of those, then it worked on Linuxbrew. That might need to be made note of?

**Comment by native-api** [comment]
The question is, why is Linuxbrew's `pkg-config` in you PATH in the first place, overriding the stock one? I suspect that the formula is keg-only... https://github.com/pyenv/pyenv/wiki/Common-build-problems#keg-only-homebrew-packages-are-forcibly-linked--added-to-path

**Comment by dkolb** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/pkg-config.rb

It is not keg-only, unfortunately.

**Comment by dkolb** [comment]
So I've been struggling with pyenv via asdf's python plugin on Ubuntu 22.04 on WSL2.  I seem to have stumbled on a couple of options for "fixing" pkg-config. I suspect something is up with homebrew's...continuing choices about openssl 1.1 vs 3.0 libraries.

```
~ > set -e PKG_CONFIG_PATH
~ > /home/linuxbrew/.linuxbrew/bin/pkg-config --libs openssl
-L/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1s/lib -lssl -lcrypto
~ > /usr/bin/pkg-config --libs openssl
-lssl -lcrypto
~ > /usr/bin/pkg-config --modversion openssl
3.0.2
~ > set -x PKG_CONFIG_PATH (brew --prefix)/opt/openssl/lib/pkgconfig
~ > echo $PKG_CONFIG_PATH
/home/linuxbrew/.linuxbrew/opt/openssl/lib/pkgconfig
~ > pkg-config --debug --libs openssl^C
~ > /home/linuxbrew/.linuxbrew/bin/pkg-config --libs openssl
-L/home/linuxbrew/.linuxbrew/Cellar/openssl@3/3.0.7/lib -lssl -lcrypto
```

It seems the options are as follows:

Set `PKG_CONFIG_PATH` to `$(brew --prefix)/opt/openssl/lib/pkgconfig)`. This will link against homebrew's openssl@3. However, you've discouraged this because it can break things.

You can also set `PKG_CONFIG_EXECUTABLE` to `/usr/bin/pkg-config` or some other path specifically when interacting with pyenv (via asdf if necessary) to fall back to the system's pkg-config and utilize the system openssl.

```
~ > set -x PKG_CONFIG_EXECUTABLE /usr/bin/pkg-config
~ > echo $PKG_CONFIG_PATH

~ > asdf uninstall python 3.11.0
~ > asdf install python 3.11.0
python-build 3.11.0 /home/david/.asdf/installs/python/3.11.0
Downloading Python-3.11.0.tar.xz...
-> https://www.python.org/ftp/python/3.11.0/Python-3.11.0.tar.xz
Installing Python-3.11.0...
WARNING: The Python tkinter extension was not compiled and GUI subsystem has been detected. Missing the Tk toolkit?
Installed Python-3.11.0 to /home/david/.asdf/installs/python/3.11.0
```

I really don't know there's a good fix to be had at the level of pyenv, tbqh.

**Comment by native-api** [comment]
OpenSSL 3 is not the problem. Recent versions of Python do support OpenSSL 3 (even thought the support is still officially experimental AFAIK).

From what I can see, the problem is:
* linking against Homebrew dependencies requires additional linker flags (which we don't set in Linux)
* Linuxbrew's suggested setup activates `brew shellenv` which seems to add its `bin` to PATH
* that overrides `pkg-config`, but probably doesn't override `gcc` (Homebrew-provided compilers have the needed additional linker flags specified in their configuration) or set `LDFLAGS`.

So I'm not sure how with that apparently incomplete build environment, we're supposed to link against either Homebrew- or non-Homebrew dependencies...

**Comment by dkolb** [comment]
That makes much more sense and I can confirm:

> that overrides pkg-config (which provides paths to Homebrew- instead of stock OpenSSL), but probably doesn't override gcc (Homebrew-provided compilers have the needed additional linker flags specified in their configuration) or set LDFLAGS.

This is correct. [Homebrew's `gcc`](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gcc.rb#L162) only installs a link to `gcc-#{version}` so the `gcc` in your path remains the system `gcc`.

Setting `CC=gcc-12` (current version installed by the formula) also gets you a successful build.

And agreed, I don't think there's any cleaning up to do at this level. Homebrew Linux needs to figure this out.
