### ISSUE TITLE
pyenv fails to install CPython 3.11.0 on MacOS Ventura

### ISSUE THREAD

**Issue by pbhowmic** [pyenv/pyenv#2525]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS Ventura 13.0
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 2.3.6
- [x] Python version: 3.11.0
- [x] C Compiler information (e.g. gcc 7.3): xcode-select version 2396
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. 
[trace.log](https://github.com/pyenv/pyenv/files/9992590/trace.log)
E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

**Comment by binbjz** [comment]
`py
import sysconfig, pprint; pprint.pprint(sysconfig.get_config_vars()['HOST_GNU_TYPE'])
'aarch64-apple-darwin21.6.0'
`
`sh
env PYTHON_CONFIGURE_OPTS="--build=aarch64-apple-darwin21.6.0 --enable-shared --enable-optimizations" pyenv install 3.11.0 -v
`

**Comment by native-api** [comment]
@pbhowmic your compiler toolchain appears to be broken.

Make sure you don't have Homebrew's `binutils` and `llvm` on `PATH`. Also check any ennvars that affect the compiler.

If you've just upgraded to MacOS 13, try upgrading XCode command-line tools.

**Comment by pbhowmic** [comment]
Yep, that did the trick
