### ISSUE TITLE
`uninstall-python': not a valid identifier

### ISSUE THREAD

**Issue by PushUpek** [pyenv/pyenv#2529]
So, function name is invalid. I think it should be `uninstall_python`

https://github.com/pyenv/pyenv/blob/4c261e6ea1a123e321a47b6c723ebd2603527e4d/plugins/python-build/bin/pyenv-uninstall#L65

**Comment by native-api** [comment]
Interesting. For some weird reason, it works, even in MacOS with Bash 3.2!

**Comment by PushUpek** [comment]
No, it's not working

`/Users/pushupek/.pyenv/plugins/python-build/bin/pyenv-uninstall: line 93: `uninstall-python': not a valid identifier`

and for install
```
/Users/pushupek/.pyenv/plugins/python-build/bin/python-build: line 743: syntax error near unexpected token `('
/Users/pushupek/.pyenv/plugins/python-build/bin/python-build: line 743: `  [ -n "$HAS_PATCH" ] && apply_patch "$package_name" <(cat "${package_name}.patch")'
/Users/pushupek/.pyenv/plugins/python-build/bin/python-build: line 743: syntax error near unexpected token `('
/Users/pushupek/.pyenv/plugins/python-build/bin/python-build: line 743: `  [ -n "$HAS_PATCH" ] && apply_patch "$package_name" <(cat "${package_name}.patch")'
/Users/pushupek/.pyenv/plugins/python-build/bin/python-build: line 743: syntax error near unexpected token `('
/Users/pushupek/.pyenv/plugins/python-build/bin/python-build: line 743: `  [ -n "$HAS_PATCH" ] && apply_patch "$package_name" <(cat "${package_name}.patch")'
```

But if you add `set +o posix` to `python-build` and `pyenv-uninstall` it's work fine without any changes.

MacOS 13.0.1
Bash 3.2.57(1)-release (arm64-apple-darwin22)

**Comment by native-api** [comment]
> But if you add `set +o posix` to `python-build` and `pyenv-uninstall` it's work fine without any changes.

This must be the reason. "POSIX mode" adds restrictions to Bash. Maybe you have the `POSIXLY_CORRECT` envvar set that enables the POSIX mode by default.

**Comment by PushUpek** [comment]
omg, it was set in fish.conf :F
