### ISSUE TITLE
Install does not work on M1 Monterey 12.6

### ISSUE THREAD

**Issue by nevzatseferoglu** [pyenv/pyenv#2530]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Apple M1 Monterey
- [x] OS architecture (e.g. amd64): Darwin arm64
- [x] pyenv version: 2.3.6
- [x] Python version: 3.6.8
- [x] C Compiler information (e.g. gcc 7.3): gcc --version                                                                                                     21:03:28
Apple clang version 14.0.0 (clang-1400.0.29.102)
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
[trace.log](https://github.com/pyenv/pyenv/files/10024545/trace.log)

`pyenv install <version>` does not work.

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/wiki/Common-build-problems#configure-error-internal-configure-error-for-the-platform-triplet-please-file-a-bug-report-in-macos
