### ISSUE TITLE
it looks can't work when I get `pyeny` by the windows installation

### ISSUE THREAD

**Issue by priority3** [pyenv/pyenv#2541]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

this is a amazing project, I get it by [installation](https://github.com/pyenv/pyenv#windows), 
I clone the repo, and then execute the following command  but it looks some warnings happened
![image](https://user-images.githubusercontent.com/75966543/205321788-dfc4f048-9233-46b5-916d-8f633a264ec2.png)

I echo the code into .bashrc and .bash_profile, restart my shell 
execute `exec "$SHELL"`

![image](https://user-images.githubusercontent.com/75966543/205322709-37a3cf52-40eb-4e32-bd12-a8aeda8192ec.png)

maybe this is my bad cause it, I will appreciate if your take some help for me🤣

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): win10
- [ ] OS architecture (e.g. amd64):
- [ ] pyenv version:
- [ ] Python version:
- [ ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

**Comment by anton-petrov** [comment]
We do not support Windows, use https://github.com/pyenv-win/pyenv-win
