### ISSUE TITLE
`pyenv install 3.10` fails

### ISSUE THREAD

**Issue by joeflack4** [pyenv/pyenv#2543]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ x Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS 11.4
- [x] OS architecture (e.g. amd64): Intel x64
- [x] pyenv version: 2.3.7
- [x] Python version: 3.11
- [x] C Compiler information (e.g. gcc 7.3): gcc-6
- [x] Please attach the debug trace of the failing command as a gist: https://gist.github.com/joeflack4/b40478868bc8863a93ac6e6e3a0b0321
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

## Overview
I'm trying to install 3.10, and it fails. I also moved `/usr/local/bin/gcc-6` out of `/usr/local/bin/` in hopes that it would use `gcc-12` or another one that I have on my machine, but it still tried to use `gcc-6`.

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/wiki/Common-build-problems#keg-only-homebrew-packages-are-forcibly-linked--added-to-path

**Comment by native-api** [comment]
(The immediate error means that you compiler toolchain is broken though, but this irrelevant sine you shouldn't be using it in the first place.)

**Comment by joeflack4** [comment]
Thanks. I looked at the common build problems, but it didn't look related to my issue. But I see you understand this better than I.

I didn't choose to use `gcc-6`, though. As I explained in my OP, I moved the file out of `/usr/local/bin/` but it still tried to use it, which sounds like a programming error of some sort. Shouldn't it select something else?

I have all of this in my PATH:
```
ls /usr/local/bin | grep gcc
gcc-12
gcc-6
gcc-ar-12
gcc-ar-6
gcc-nm-12
gcc-nm-6
gcc-ranlib-12
gcc-ranlib-6
x86_64-apple-darwin20-gcc-12
x86_64-apple-darwin20-gcc-ar-12
x86_64-apple-darwin20-gcc-nm-12
x86_64-apple-darwin20-gcc-ranlib-12
x86_64-apple-darwin20.3.0-gcc-6
x86_64-apple-darwin20.3.0-gcc-6.5.0
x86_64-apple-darwin20.3.0-gcc-ar-6
x86_64-apple-darwin20.3.0-gcc-nm-6
x86_64-apple-darwin20.3.0-gcc-ranlib-6
```

However, I don't think it's correct to say it "has no business on my computer". I installed these while I was working on C++ projects. But I have had issues with C++ (which has terrible package management, etc), so it's possible there's a etter way to install specific compilers for that kind of work.

**Comment by joeflack4** [comment]
Oh, it looks like I uninstalled Xcode. I can't remember which problems I had specifically that made me uninstall it, but it definitely has caused major headaches from time to time. I will perhaps try installing it again.

**Comment by native-api** [comment]
The problem is not that GCC in installed. The problem is that you have explicitly selected it as the compiler to use (by setting it to the `CC` ennvar from what I can see).

**Comment by native-api** [comment]
> So Homebrew's GCC has no business being on PATH

I stay corrected in this particular place. That formula is not keg-only as I thought, and it does not override the stock `/usr/bin/gcc` stub.
