### ISSUE TITLE
2.3.9 Regression in pyenv-latest

### ISSUE THREAD

**Issue by willgleich** [pyenv/pyenv#2569]
pyenv 2.3.9

`pyenv install 3.6:latest`
> python-build: definition not found: 3.6:latest
   See all available versions with `pyenv install --list'.

After installing pyenv with `curl https://pyenv.run | bash` the latest release will not install python versions using the latest tag. This is showing up on an aarach64 ubuntu 20.04 image.

Workaround: Downgrade to pyenv v2.3.8 and everything works as expected 
```
export PYENV_GIT_TAG=v2.3.8
curl https://pyenv.run | bash
```

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 20.04
- [X] OS architecture (e.g. amd64): aarach64
- [X] pyenv version: 2.3.9
- [X] Python version: 3.8.10
- [X] C Compiler information (e.g. gcc 7.3): gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
- [X] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
  * https://gist.github.com/willgleich/3235f0a282b139761b8dbf2dc2c9af8c

Workaround: Downgrade to pyenv v2.3.8 and everything works as expected 
```
export PYENV_GIT_TAG=v2.3.8
curl https://pyenv.run | bash
```

**Comment by ssbarnea** [comment]
Oh joy, I have being asking for something like this for years and when it was implemented it got broken before even having time to use it once. :(

**Comment by native-api** [comment]
There's now a better implementation, via specifying arbitrary prefix: https://github.com/pyenv/pyenv#prefix-auto-resolution

**Comment by ssbarnea** [comment]
@native-api The `pyenv latest 3.10` is of very little use because it cannot be used to install a python 3.10 version under a stable path (one that does not include the minor version).

That is a critical missing big because every python path change would fully break virtualenvs and IDE configuration, which will need to be reconfigured to recognize the paths, even if python was only updated from `X.Y.0` to `X.Y.1`.

I do have hundreds (>200) open source repos which i work with and contribute with, so you can imagine how frustrating is to have to reconfigure python interpreters in each vscode workspace I open as vscode always saves the "resolved" python path (never uses the shims). Usually by the time I fix the python paths a new release is released.

![](https://sbarnea.com/ss/pyenv-python-paths.png)

**Comment by wshanks** [comment]
You can now do `pyenv install 3.10` instead of `pyenv install 3.10:latest` (that is what the documentation @native-api referenced says).

**Comment by native-api** [comment]
@ssbarnea Latest version auto-resolution was never intended to create "stable paths". Please open a separate issue about that and describe your use case(s) there. Then we'll be able to see what we can do.

**Comment by ssbarnea** [comment]
I raised https://github.com/pyenv/pyenv/issues/2600 and put details there thanks. Hopefully we will find a soluion.
