### ISSUE TITLE
Incorrect build deps added to wiki?

### ISSUE THREAD

**Issue by JacobHayes** [pyenv/pyenv#2570]
The wiki was recently [updated](https://github.com/pyenv/pyenv/wiki/Home/_compare/e7978e369baf620ed7a183cf522e116805e84f79) to include the following build dependencies for Debian/Ubuntu:

```
libsasl2-dev python3-dev libldap2-dev
```

Are these necessary? `python3-dev` seems unnecessary (I'm assuming pyenv pulls the relevant version's headers) and I can't seem to find anything in CPython about libsasl2 nor libldap2. I'm wondering if they were added so a `pip` installed package could be compiled? cc @gnihrizov

**Comment by native-api** [comment]
Reverted.

**Comment by JacobHayes** [comment]
Thanks!
