### ISSUE TITLE
pyenv install BUILD FAILED [Bad CPU type in executable]

### ISSUE THREAD

**Issue by Machikanewani** [pyenv/pyenv#2571]
I have Python 3.10.9 installed by Homebrew and for some reasons have to install a version >= 3.7, < 3.10. Then I came across the "Bad CPU type in executable" trouble and haven't found any others get the same error. 

- [ ] Platform information (OS X 13.1):
- [ ] OS architecture (i5):
- [ ] pyenv version: 2.3.9
- [ ] Python version: 3.8.10
- [ ] C Compiler information (not sure): 
- [ ] Please attach the debug trace of the failing command as a gist:

python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.8.10.tar.xz...
-> https://www.python.org/ftp/python/3.8.10/Python-3.8.10.tar.xz
Installing Python-3.8.10...
patching file 'Misc/NEWS.d/next/Build/2021-10-11-16-27-38.bpo-45405.iSfdW5.rst'
patching file configure
patching file configure.ac
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 13.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/cy/k4vntxnd2db0gpt5ftqtv1_00000gp/T/python-build.20221226025316.31837
Results logged to /var/folders/cy/k4vntxnd2db0gpt5ftqtv1_00000gp/T/python-build.20221226025316.31837.log

Last 10 log lines:
config.status: creating pyconfig.h
creating Modules/Setup.local
creating Makefile

If you want a release build with all stable optimizations active (PGO, etc),
please run ./configure --enable-optimizations

/usr/local/Cellar/pyenv/2.3.9/plugins/python-build/bin/python-build: line 821: /usr/local/bin/make: Bad CPU type in executable

**Comment by native-api** [comment]
> /usr/local/bin/make: Bad CPU type in executable

There should not be a `make` in `/usr/local/bin`. Apple's Make is in `/usr/bin`.

**Comment by Machikanewani** [comment]
> > /usr/local/bin/make: Bad CPU type in executable
> 
> There should not be a `make` in `/usr/local/bin`. Apple's Make is in `/usr/bin`.

So should I change the PATH of `make`?

**Comment by native-api** [comment]
You should probably delete that `make`. I don't know what that is.

**Comment by native-api** [comment]
You should probably delete that `make` or, better, uninstall whatever it belongs to.
I don't know what that is.

**Comment by Machikanewani** [comment]
Deleting `make` works! Thank you!
