### ISSUE TITLE
entry_point incorrect with pyproject.toml wheels installed with pyenv's pip shim.

### ISSUE THREAD

**Issue by MatthewRalston** [pyenv/pyenv#2572]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ x ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ x ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ x ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ x ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ x ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ x ] Platform information (e.g. Ubuntu Linux 16.04): Arch 6.0.12-arch1-1
- [ x ] OS architecture (e.g. amd64): x86_64
- [  x] pyenv version: pyenv 2.3.4-19-g1f526edb
- [  x] Python version: 3.10.1
- [ x] C Compiler information (e.g. gcc 7.3): 11.1.0
- [ x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

https://gist.github.com/MatthewRalston/e51500476c8dfdd14ae3622b40fde77b

## What is my environment?
Python 3.10.1
pip 22.3.1

## What have I tried?
```python
cd kmerdb
python -m build
pip install -I dist/kmerdb-0.7.2-py3-none-any.whl
```

Install completes successfully. This is not a pip issue. Kmerdb imports correctly in the pyenv's version but the pyproject.toml produces an entry_point that is not properly handled by the shim or the bin script. See below for details.

## `pyproject.toml`

```toml
[build-system]
requires = ["setuptools", "wheel", "numpy>=1.19.0", "Cython>=0.29.21"]
build-backend = "setuptools.build_meta"

[project]
name = "kmerdb"
version = "0.7.2"
description = "Yet another kmer library for Python"

#...


[project.entry-points]
console_scripts = {kmerdb = "kmerdb:cli"}
```

## Expected

I expect the installed bin script to not produce the following.
```bash
(kdb) [matt@argo] git:pyprojecttoml_build_twine+ </ffast2/kdb>>kmerdb -h
Traceback (most recent call last):
  File "/home/matt/.pyenv/versions/kdb/bin/kmerdb", line 5, in <module>
    from kmerdb import cli
ModuleNotFoundError: No module named 'kmerdb'
(kdb) [matt@argo] git:pyprojecttoml_build_twine+ </ffast2/kdb>>python
Python 3.10.1 (main, Jan  1 2022, 21:28:19) [GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kmerdb
>>> # Imports successfully
>>> # 'python -m kmerdb' also invokes the cli correctly.
(kdb) [matt@argo] git:pyprojecttoml_build_twine+ </ffast2/kdb>>cat ~/.pyenv/versions/kdb/bin/kmerdb 
#!/home/matt/.pyenv/versions/3.10.1/envs/kdb/bin/python3.10
# -*- coding: utf-8 -*-
import re
import sys
from kmerdb import cli
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())
[matt@argo] git:pyprojecttoml_build_twine+ </ffast2/kdb>>kmerdb -h
Traceback (most recent call last):
  File "/home/matt/.pyenv/versions/kdb/bin/kmerdb", line 5, in <module>
    from kmerdb import cli

```

## Referencing issue

https://github.com/MatthewRalston/kmerdb/issues/97#issuecomment-1366136134

**Comment by MatthewRalston** [comment]
I have also tried adjusting my entry_point options as in the official `entry_points` [guide](https://setuptools.pypa.io/en/latest/userguide/entry_point.html)

* `pyproject.toml`
```toml
[project.scripts]
kmerdb = "kmerdb:cli"
```
* `setup.cfg`
```toml
[options.entry_points]
console_scripts {kmerdb = kmerdb:cli}
```

* `setup.py`
```python
setup(
name=NAME
# ...
entry_points={'console_scripts': ['kmerdb=kmerdb:cli']}
```

**Comment by native-api** [comment]
Does this happen outside of a virtualenv? It seems to me this is a Pyenv-Virtualenv's issue.

**Comment by MatthewRalston** [comment]
Yeah, it wasn't either. It was an issue with pyproject.toml and setup.py PEP606 migration. I can mark this as closed. It has to do with correctly acquiring information into the whl file created with `python -m build`. Closing.
