### ISSUE TITLE
import hashlib throwing error on pyenv installation of python 3.11

### ISSUE THREAD

**Issue by bsteiger** [pyenv/pyenv#2573]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS Ventura 13.1 (22C65)
- [x] OS architecture (e.g. amd64): arm64 (M1)
- [x] pyenv version: 2.3.9
- [x] Python version: 3.11.0, 3.11.1
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 14.0.0 (clang-1400.0.29.202)
- [x] Please attach the debug trace of the failing command as a gist: `pyenv install 3.11 --force` [trace.log](https://github.com/pyenv/pyenv/files/10311428/trace.log)
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

After installing 3.11.1 with the `pyenv install 3.11.1` command and then switching to 3.11.1 with `pyenv shell 3.11.1`, I get the following error when running `pip --version`
```
ERROR:root:code for hash blake2b was not found.
Traceback (most recent call last):
  File "/Users/Brandon/.pyenv/versions/3.11.1/lib/python3.11/hashlib.py", line 307, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Brandon/.pyenv/versions/3.11.1/lib/python3.11/hashlib.py", line 129, in __get_openssl_constructor
    return __get_builtin_constructor(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Brandon/.pyenv/versions/3.11.1/lib/python3.11/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type blake2b
ERROR:root:code for hash blake2s was not found.
Traceback (most recent call last):
  File "/Users/Brandon/.pyenv/versions/3.11.1/lib/python3.11/hashlib.py", line 307, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Brandon/.pyenv/versions/3.11.1/lib/python3.11/hashlib.py", line 129, in __get_openssl_constructor
    return __get_builtin_constructor(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Brandon/.pyenv/versions/3.11.1/lib/python3.11/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type blake2s
pip 22.3.1 from /Users/Brandon/.pyenv/versions/3.11.1/lib/python3.11/site-packages/pip (python 3.11)
```
This can also occur anytime `import hashlib` is called from within python.

No issues seen when using pyenv installed python versions 3.8.16, 3.9.16, or 3.10.9
No issues seen when python 3.11 is installed using `brew install python@3.11`

**Comment by native-api** [comment]
There must've been an error buliding the hashlib extension during installation. IIRC blake2b implementation is taken from OpenSSL.

**Comment by bsteiger** [comment]
Did the OpenSSL requirements change in 3.11? I do see errors in the
trace.log around line 13393 about building the _blake2 extension.

**Comment by native-api** [comment]
I cannot reproduce this in Big Sur or Monterey. So I guess something in the OS or compiler may have changed.
Ventura doesn't support my hardware. @anton-petrov @joshfriend can you try to reproduce it?

@bsteiger Until someone from the team can reproduce it, you'll have to localize the issue further.
This doesn't seem to be a linking issue or OpenSSL issue since 3.11 has its own implementation of the `blake2b` algorithm. Patches in the [Homebrew's `python@3.11` formula](https://github.com/Homebrew/homebrew-core/blob/45bbce30258b8c608d2f900e3d869b648f865567/Formula/python@3.11.rb) don't seem to contain anything immediately relevant, either.

**Comment by anton-petrov** [comment]
Hm, it's strange, because I just installed latest pyenv from zero using homebrew and was unable to reproduce this bug on my system (Apple M1, macOS Ventura 13.1) - everything works fine!

```shell
❯ brew install pyenv
❯ pyenv install 3.11.1
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.11.1.tar.xz...
-> https://www.python.org/ftp/python/3.11.1/Python-3.11.1.tar.xz
Installing Python-3.11.1...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.11.1 to /Users/anton/.pyenv/versions/3.11.1
❯ pyenv shell 3.11.1
❯ eval "$(pyenv init -)"
❯ eval "$(pyenv init --path)"
❯ pyenv shell 3.11.1
❯ python
Python 3.11.1 (main, Jan 23 2023, 11:16:11) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
...
❯ pip --version
pip 22.3.1 from /Users/anton/.pyenv/versions/3.11.1/lib/python3.11/site-packages/pip (python 3.11)
```

Alsow works as expected for me.
```python
import hashlib
```

**Comment by joshfriend** [comment]
I'm still on Ventura with both of my Macs, maybe ill update my personal mac to Ventura

**Comment by dragid10** [comment]
I will say that even using the pyenv installer on Ubuntu (No linuxbrew), I also still got this.

I spent about an hour uninstalling a bunch of other linuxbrew packages that symlinked over the native binaries (gcc and other build tools). After doing so, I was able to reinstall python 3.11 and stopped getting this error

**Comment by jacklee1792** [comment]
I'm encountering the same issues on Ventura 13.0.1 - 3.11 installed with Homebrew works fine and so do `pyenv` versions <3.11. @bsteiger did you find a fix?

**Comment by native-api** [comment]
```
ld: warning: ignoring file /usr/local/Cellar/libb2/0.98.1/lib/libb2.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
*** WARNING: renaming "_blake2" since importing it failed: dlopen(/private/var/folders/gw/kps9wm3s3b71d21jkj47d9m80000gn/T/python-build.20221227184949.70298/Python-3.11.1/build/lib.macosx-13.1-arm64-3.11/_blake2.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_blake2b_final'
```

Looks like the x64 Homebrew installation is getting in the way.

**Comment by native-api** [comment]
> ```
> ld: warning: ignoring file /usr/local/Cellar/libb2/0.98.1/lib/libb2.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
> *** WARNING: renaming "_blake2" since importing it failed: dlopen(/private/var/folders/gw/kps9wm3s3b71d21jkj47d9m80000gn/T/python-build.20221227184949.70298/Python-3.11.1/build/lib.macosx-13.1-arm64-3.11/_blake2.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_blake2b_final'
> ```
> 
> Looks like the x64 Homebrew installation is getting in the way.

Okay, looks like I've got a clue.

* Since x64's Homebrew is in `/usr/local`, it's always in the compiler's search path.
* So if a library is installed and linked there, the compiler always finds it, even if it's compiling for `arm64`.
* [CPython's `_blake2` extension tries to use `libb2` if it's installed. Otherwise, it uses a builtin implementation -- which includes that `blake2b_final` function](https://github.com/python/cpython/blob/a7a450f84a087421603170c2dad226bb881d4d9a/Modules/_blake2/blake2module.h#L4-L13) (the leading underscore in linker's output -- `_blake2b_final` -- looks like C++ compiler's [mangling](https://en.wikipedia.org/wiki/Name_mangling) which indicates that this function uses the [C calling convention](https://en.wikipedia.org/wiki/X86_calling_conventions#cdecl)).

So **you need to either install `libb2` in the Arm64 Homebrew, or uninstall it in the x64 Homebrew.**

**Comment by jacklee1792** [comment]
Thanks, uninstalling `libb2` on x64 Homebrew as you suggested and reinstalling 3.11 fixed the problem for me!

```
/usr/local/bin/brew uninstall libb2
pyenv install 3.11.1 --force
```
