### ISSUE TITLE
Installing 2.7.18 on a macOS with existing system 2.7.16 will actually yield 2.7.16

### ISSUE THREAD

**Issue by benjyw** [pyenv/pyenv#2578]
On a macOS 11 system (specifically, a GitHub Actions macos-11 runner) that has a system Python version 2.7.16, running `pyenv install 2.7.18` will succeed. But when you run that 2.7.18 (`.pyenv/versions/2.7.18/bin/python`) you actually get the 2.7.16 interpreter!

```
$ .pyenv/versions/2.7.18/bin/python

WARNING: Python 2.7 is not recommended. 
This version is included in macOS for compatibility with legacy software. 
Future versions of macOS will not include Python 2.7. 
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, Aug 29 2022, 10:34:32) 
[GCC Apple LLVM 12.0.5 (clang-1205.0.19.59.6) [+internal-os, ptrauth-isa=deploy on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

I have bisected this to [this commit](https://github.com/pyenv/pyenv/pull/2554/commits/03bba03291a1d6535145e894e71dfeb772823db3).

I'd offer a fix, but I don't really understand what is going on here. 

To access a system that reproduces this, run this github action, and follow the instructions it emits to SSH to the runner:

```
name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
```

I'm also happy to test out a fix. 

------

Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS 11
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 2.3.9
- [x] Python version: 2.7.18
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 13.0.0 (clang-1300.0.29.30)
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`): NA, no command is failing, but the result is broken.

**Comment by benjyw** [comment]
Thanks for the fix!

**Comment by sanan-go** [comment]
I'm still having this issue on pyenv v2.3.18 (macbook pro m1, macOS v12)

![telegram-cloud-photo-size-2-5463368365709052758-y](https://github.com/pyenv/pyenv/assets/85499373/eea69dbf-aea2-4d19-828d-b45febd3151a)

**Comment by native-api** [comment]
@sanan-go need the diagnostic info as per the issue template to say anything specific.
