### ISSUE TITLE
How to disable --enable-shared?

### ISSUE THREAD

**Issue by nihal111** [pyenv/pyenv#2580]
### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): Amazon Linux 2
- [X] OS architecture (e.g. amd64): x86_64
- [X] pyenv version: v2.3.9
- [X] Python version: 3.9.9
- [X] C Compiler information (e.g. gcc 7.3): gcc.x86_64  7.3.1-15.amzn2
- [X] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
  * [trace.log](http://sprunge.us/CF243m) (using latest head)
    - `checking for --enable-shared... yes`
  * [trace2.log](http://sprunge.us/8OO0c3) (using release v2.3.9)
    - `checking for --enable-shared... no`

I am using pyenv to install Python3.9.9 and create a portable virtual environment (using `venv` and `venv-pack`). This has been working fine for quite some time, until the recent --enable-shared change to pyenv makes the Python binary shrink in size resulting in downstream errors where I am trying to use the packaged portable environment - `./environment/bin/python: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory`.

The python binary shrinks in size, as shown below-

#### Using pyenv release 2.3.9, the Python binary is 18MB
```
bash-4.2# export PYENV_GIT_TAG=v2.3.9
bash-4.2# curl https://pyenv.run | bash
...
bash-4.2# pyenv install 3.9.9
Downloading Python-3.9.9.tar.xz...
-> https://www.python.org/ftp/python/3.9.9/Python-3.9.9.tar.xz
Installing Python-3.9.9...
Installed Python-3.9.9 to /usr/local/bin/.pyenv/versions/3.9.9

bash-4.2# ls -arilh /usr/local/bin/.pyenv/versions/3.9.9/bin/python3.9
22647967 -rwxr-xr-x 1 root root 18M Jan  3 03:16 /usr/local/bin/.pyenv/versions/3.9.9/bin/python3.9
```

#### Using automatic installer without setting PYENV_GIT_TAG, the Python binary is 26KB
```
bash-4.2# rm -rf /usr/local/bin/.pyenv
bash-4.2# export PYENV_GIT_TAG=""
bash-4.2# curl https://pyenv.run | bash
...
bash-4.2# pyenv install 3.9.9
Downloading Python-3.9.9.tar.xz...
-> https://www.python.org/ftp/python/3.9.9/Python-3.9.9.tar.xz
Installing Python-3.9.9...
Installed Python-3.9.9 to /usr/local/bin/.pyenv/versions/3.9.9

bash-4.2# ls -arilh /usr/local/bin/.pyenv/versions/3.9.9/bin/python3.9
22648006 -rwxr-xr-x 1 root root 26K Jan  3 03:44 /usr/local/bin/.pyenv/versions/3.9.9/bin/python3.9
```

The responsible change for this changed behaviour seems to be https://github.com/pyenv/pyenv/pull/2554 (--enable-shared by default). Is there a way to unset the `--enable-shared` flag? If not, would it be supported by pyenv in the future?

**Comment by onceme** [comment]
Same question here +1

A pyenv built whl will search for `libpython`:
```
$ ldd _init.cpython-37m-x86_64-linux-gnu.so
	libpython3.7m.so.1.0 => /lib/x86_64-linux-gnu/libpython3.7m.so.1.0 (0x00007fb54bb1a000)
```
vanilla env (apt install or similar) usually doesn't have this shared lib.

**Comment by anton-petrov** [comment]
I understand your concern, but we don't have that option at the moment. 

Perhaps we should consider adding compilation options to an environment variable? For example, somthing like this in .bashrc or .zshrc:
```bash
PYENV_BUILD_OPTIONS="--enable-optimizations --enable-shared --with-lto"
```
to not pass these parameters explicitly on every call to `pyenv`.

So far, we have set a course for compiling CPython in accordance with the way its developers do. Look at the CPython docker image, line 12 (https://hub.docker.com/layers/library/python/3.11.1-buster/images/sha256-967e90721074249c795f99bdebe3f627e46ecac30da792695f7e18dc9ddcontext3b374? =explore) or at the homebrew formula (https://github.com/Homebrew/homebrew-core/blob/master/Formula/python@3.11.rb#L147). In both cases, the --enable-shared option is used.

Any suggestions or discussions are welcome!

**Comment by jblakeman** [comment]
@anton-petrov Given that it breaks a common use case, would you consider reverting forcing `--enable-shared` until support for adding compilation options is available?

**Comment by broken-wheel** [comment]
Seconding @jblakeman, wouldn't it be better to allow backwards compatible behavior instead of forcing a breaking change especially when there's no technical restriction? My workflow also broke with this update and I don't know what the workaround is.

Is there a workaround?

**Comment by nihal111** [comment]
@broken-wheel the workaround I've been using is-
```
# temporarily downgrading to pyenv v2.3.9
ENV PYENV_GIT_TAG=v2.3.9
RUN curl https://pyenv.run | bash
```

@anton-petrov Agree on using an env-var for compilation options, to allow the user to override if required.

**Comment by broken-wheel** [comment]
Thanks @nihal111. But, downgrading wouldn't let us access newer Python versions like @jblakeman mentioned.

Thought I would share some additional thoughts: I have been using `PYTHON_CONFIGURE_OPTS` to explicitly pass `--enable-shared` to `pyenv` (whenever I needed `libpython`), which is actually documented in `pyenv`'s [documentation](https://github.com/pyenv/pyenv/blob/master/plugins/python-build/README.md#special-environment-variables). So, I am not sure what the purpose of `PYENV_BUILD_OPTIONS` is since `pyenv` build already respects `PYTHON_CONFIGURE_OPTS`. 

Also, like @jblakeman mentioned, the default option in upstream Python is `--enable-shared=no` (https://docs.python.org/3/using/configure.html#cmdoption-enable-shared). 

Now, I totally get the desire to match defaults in other mainstream builds. But I personally would be very sad if `pyenv` forces its users to only use Python built with shared mode.

Pretty please, could you revert this change till there's a way to build statically with a default shared build?

**Comment by native-api** [comment]
You should now be able to override `--enable-shared` by setting `PYTHON_CONFIGURE_OPTS=--disable-shared`.
