### ISSUE TITLE
Support curl from snap package

### ISSUE THREAD

**Issue by ehlui** [pyenv/pyenv#2582]
## Short description

Curl library from the **snap package manager** prompts an error right after trying to install a python version
> curl: (23) Failure writing output to destination

### Description

As this is a non-python related I am not adding the error from the debbuger option you recommend for the issues.

- [ ] Platform **Xubuntu 22.04.1**
- [ ] OS architecture (e.g. amd64):
- [ ] pyenv version: **2.3.9**
- [ ] Python version: 3.10.6 (global) and 3.11.1 (installing target)

### Sources to solve this problem 

[askubuntu link](https://askubuntu.com/questions/1356327/cant-write-to-a-hidden-path-using-curl)

**Comment by native-api** [comment]
Well, the reason is that snaps cannot write to `/tmp` where we do the build.

Is there a compelling reason to use `curl` from a snap? [We've supported `aria2c` beinbg a snap](https://github.com/pyenv/pyenv/issues/2522) because it's not available as a normal application in Ubuntu. But `curl` is.

**Comment by native-api** [comment]
As a workaround, you can set the `PYTHON_BUILD_HTTP_CLIENT` envvar to `wget` if you have that available as a normal application.

**Comment by ehlui** [comment]
Thanks!
My solution was to use another curl avoiding from the snap package like from apt instead.
