### ISSUE TITLE
Pyenv install reports commands not found : python-build and parse_options

### ISSUE THREAD

**Issue by AnaHum** [pyenv/pyenv#2603]
After installing `pyenv`, I'm getting the following error :

```
bash-5.2$ pyenv install -l
/opt/homebrew/Cellar/pyenv/2.3.11/plugins/python-build/bin/pyenv-install: line 53: python-build: command not found
/opt/homebrew/Cellar/pyenv/2.3.11/plugins/python-build/bin/pyenv-install: line 78: parse_options: command not found
```
Any ideas how to fix this?

I found exactly same issue reported [here](https://github.com/pyenv/pyenv/issues/2587) but there was a solution proposed in there. in additionI have just installed pyenv on new laptop  and there are no dependencies with older versions

### Prerequisite
* [ ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS Ventura 13.1
- [x] OS architecture (e.g. amd64): Apple M1
- [x] pyenv version: pyenv 2.3.11
- [x] Python version: Python 3.9.6
- [ ] C Compiler information (e.g. gcc 7.3): 
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
  * [trace.log](https://github.com/pyenv/pyenv/files/10491943/trace.log)
- [ ] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

**Comment by native-api** [comment]
Check if there's 'python-build' in `/opt/homebrew/Cellar/pyenv/2.3.11/plugins/python-build/bin/`.

If not, try to reinstall Pyenv, if it's still not there, check you antivirus' logs.

[For Apple's built-in XProtect antivirus](https://github.com/pyenv/pyenv/issues/2392#issuecomment-1152255426):

> MacOS 12 has a bult-in antivirus called XProtect.
> 
> This appears to have info how to view its logs:
> 
> https://apple.stackexchange.com/questions/437837/xprotect-apple-claims-they-do-signature-based-antivirus-but-how-do-we-know

**Comment by AnaHum** [comment]
@native-api  thanks for your answer. I did reinstall pyenv and finally managed to get `python-build ` in `/opt/homebrew/Cellar/pyenv/2.3.11/plugins/python-build/bin/`. yet when I run `pyenv install 3.9.13`    same error pops up 
`/opt/homebrew/Cellar/pyenv/2.3.11/plugins/python-build/bin/pyenv-install: line 78: parse_options: command not found` and plus it deletes python-build again. I checked the antivirus' logs and there are errors but nothing related to pyenv 
[log 2.txt](https://github.com/pyenv/pyenv/files/10497805/log.2.txt)

**Comment by dudulasry** [comment]
I also encounter this problem, with 2.3.11. Is there a possibility for a bug?

**Comment by BrittonBK** [comment]
I'm seeing the same behavior. After installing pyenv with brew:
```
ls /opt/homebrew/Cellar/pyenv/2.3.11/plugins/python-build/bin
>  pyenv-install   pyenv-uninstall   python-build
```

And then after running `env PYENV_DEBUG=1 pyenv install -l 2>&1 | tee trace.log`, my terminal window closes, and when I look back in the same folder I see this:

```
ls /opt/homebrew/Cellar/pyenv/2.3.11/plugins/python-build/bin
>  pyenv-install   pyenv-uninstall
```

[trace.log](https://github.com/pyenv/pyenv/files/10504462/trace.log)

That first time I try to run `pyenv install -l` I only get the `parse_options: command not found` error. Then on subsequent runs, `python-build` is no longer present, and I get the same exact error as `AnaHum` posted originally.

**Comment by native-api** [comment]
> And then after running `env PYENV_DEBUG=1 pyenv install -l 2>&1 | tee trace.log`, my terminal window closes, and when I look back in the same folder I see this:
> 
> ```
> ls /opt/homebrew/Cellar/pyenv/2.3.11/plugins/python-build/bin
> >  pyenv-install   pyenv-uninstall
> ```

This very much looks like an antivirus deletes `python-build`.

**Comment by native-api** [comment]
In previous instances where the XProtect antivirus was falsely detecting Homebrew-related software, including homebrew-installed Pyenv, some people reported that reinstalling Homebrew fixed the problem for them. Apparently, that resets the antivirus' heuristic cache on Homebrew.

**Comment by AnaHum** [comment]
So we have realised that the python-build gets deleted/quarantined as it is labelled as 'Malicious File' by SentinelOne. it is a Corporate laptop so we can not uninstall SentinelOne. Do you have any ideas how to fix it ?

**Comment by native-api** [comment]
You should contact your corporate IT service. They should have the rights to whitelist stuff in the corporate antivirus.
