### ISSUE TITLE
Extremely slow pip install after update to 2.3.12

### ISSUE THREAD

**Issue by 0xDmtri** [pyenv/pyenv#2607]
OS: MacOS Ventura 13.1
Chip: Apple Silicon
Pyenv version: 2.3.12

After the standard update via ```brew``` I immediately noticed that ```pip install ...``` became extremely slow. After the command prompt it waits for about 2-3 minutes before installing.

**Comment by 0xDmtri** [comment]
After I rolled it back to what it was the problem was gone.

**Comment by native-api** [comment]
How do you "roll it back to what it was"? Is your Pyenv installed via Homebrew of via Git checkout?

Please also add the required diagnostic information as per the issue template.

**Comment by 0xDmtri** [comment]
> How do you "roll it back to what it was"? Is your Pyenv installed via Homebrew of via Git checkout?
> 
> Please also add the required diagnostic information as per the issue template.

1. i reinstalled it from src. First, the most recent version to confirm the issue, then rolled it back. 2. On it!

**Comment by 0xDmtri** [comment]
> How do you "roll it back to what it was"? Is your Pyenv installed via Homebrew of via Git checkout?
> 
> Please also add the required diagnostic information as per the issue template.

Ser, I am really sorry but simple reboot of my mac cured the problem... Not sure what it was... Thank you for your time!
