### ISSUE TITLE
Cannot install python 2.7 on MacOS Monterey 12.4: "dyld: Library not loaded: /System/Library/Frameworks/Python.framework/Versions/2.7/Python"

### ISSUE THREAD

**Issue by snrbrnjna** [pyenv/pyenv#2623]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS 12.4
- [x] OS architecture (e.g. amd64): 2,3 GHz 8-Core Intel Core i9
- [x] pyenv version: 2.3.13
- [x] Python version: no system python installed, `python` binary not available. I wat to install the 2.7 versin with pyenv
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 13.0.0 (clang-1300.0.29.30)
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
   [trace.log](https://github.com/pyenv/pyenv/files/10748169/trace.log)
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
  [config.log](https://github.com/pyenv/pyenv/files/10748181/config.log)

- [-] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

**Comment by native-api** [comment]
The error is that the Python executable cannot find `libpython`.

Do you have `libpython2.7.dylib` in `/var/folders/6c/_m7h0s896_d0hwkl2w1nj0bc0000gn/T/python-build.20230215225207.92802/Python-2.7.18`?

If not, it most likely is being deleted by your antivirus.

**Comment by snrbrnjna** [comment]
hm 🤔  no, there's no such file in this directory. But:
- i want to install python2.7, so i suppose this `libpython2.7.dylib` should be part of the installation and not expected to be already on my machine
- there's no such thing like antivirus software on my mac

**Comment by native-api** [comment]
MacOS 12+ has a built-in antivirus called 'XProtect'.

See https://github.com/pyenv/pyenv/issues/2603 and https://github.com/pyenv/pyenv/issues/2392 on how to view its logs and possible workarounds.

**Comment by Tindtily** [comment]
> Hi,
> 
> I'm facing the same issue while trying to install python 2.7.18. But I do see `libpython2.7.dylib` in the working tree folder `/var/folders/6m/wd9lplmd00nf3_39fhmqp1z4tljn6f/T/python-build.20230309085013.1867/Python-2.7.18`
> 
> I'm using pyenv 2.3.14 on MacOS 12.6.2

macos 12.6 and pyenv 2.3.15 have exactly the same problem

**Comment by native-api** [comment]
@saicool , @Tindtily please make sure that you're actually using Pyenv 2.3.12+ (see https://github.com/pyenv/pyenv/wiki/Common-build-problems#python-build-definition-not-found-or-another-new-feature-missing-even-though-you-have-a-new-enough-pyenv). We had [a related bug](https://github.com/pyenv/pyenv/pull/2596) before that.

If you do, please show the output of (substitute your actual build directory):

```
cd /var/folders/6m/wd9lplmd00nf3_39fhmqp1z4tljn6f/T/python-build.20230309085013.1867/Python-2.7.18
DYLD_LIBRARY_PATH=$PWD otool -L ./python.exe
```

**Comment by native-api** [comment]
(Changed the code. [The `otool` method doesn't actually work due to SIP](https://cpufun.substack.com/p/which-library-did-you-say-will-be))

**Comment by Tindtily** [comment]
> please make sure that you're actually using Pyenv 2.3.12+ (see https://github.com/pyenv/pyenv/wiki/Common-build-problems#python-build-definition-not-found-or-another-new-feature-missing-even-though-you-have-a-new-enough-pyenv). We had [a related bug](https://github.com/pyenv/pyenv/pull/2596) before that.

no, i only have one 
<img width="399" alt="image" src="https://user-images.githubusercontent.com/5201107/230747710-59fc4dc7-7779-4c64-bb3a-628f4b93d890.png">

**Comment by Tindtily** [comment]
> @saicool , @Tindtily please make sure that you're actually using Pyenv 2.3.12+ (see https://github.com/pyenv/pyenv/wiki/Common-build-problems#python-build-definition-not-found-or-another-new-feature-missing-even-though-you-have-a-new-enough-pyenv). We had [a related bug](https://github.com/pyenv/pyenv/pull/2596) before that.
> 
> If you do, please show the output of (substitute your actual build directory):
> 
> ```
> cd /var/folders/6m/wd9lplmd00nf3_39fhmqp1z4tljn6f/T/python-build.20230309085013.1867/Python-2.7.18
> DYLD_PRINT_LIBRARIES=1 DYLD_LIBRARY_PATH=$PWD ./python.exe -E -S -m sysconfig --generate-posix-vars
> ```
i'm using macos, the command you give will throw error
<img width="914" alt="image" src="https://user-images.githubusercontent.com/5201107/230747755-2c521b2e-cba5-4a34-bc1e-b2805c652fc9.png">

**Comment by native-api** [comment]
> i'm using macos, the command you give will throw error <img alt="image" width="914" src="https://user-images.githubusercontent.com/5201107/230747755-2c521b2e-cba5-4a34-bc1e-b2805c652fc9.png">

please show the output of **(substitute your actual build directory)**

**Comment by Tindtily** [comment]
> 

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/5201107/230747969-c71ac0bd-8c56-4d80-ad30-dd9077421340.png">

**Comment by native-api** [comment]
:facepalm:

**Comment by Tindtily** [comment]
i'm confused with the python.exe for macos really can run it ?

**Comment by native-api** [comment]
UNIX does not care about extensions, only the contents matter. Foir some reason, CPython's build logic uses `python.exe` as a provisional name.

**Comment by Tindtily** [comment]
> 

okey, got it.

so what's my problem?

**Comment by Tindtily** [comment]
It seems to me that the files are not deployed under the system directory

**Comment by native-api** [comment]
If you cannot follow instructions, I cannot help you...

> please show the output of (substitute your actual build directory):
> 
> ```
> cd /var/folders/6m/wd9lplmd00nf3_39fhmqp1z4tljn6f/T/python-build.20230309085013.1867/Python-2.7.18
> DYLD_PRINT_LIBRARIES=1 DYLD_LIBRARY_PATH=$PWD ./python.exe -E -S -m sysconfig --generate-posix-vars
> ```

In the instructions given, "substitute your actual build directory" means that in the command, instead of `/var/folders/6m/wd9lplmd00nf3_39fhmqp1z4tljn6f/T/python-build.20230309085013.1867`, you need to insert the path to your actual build directory as reported by the build (because it's named differently in every build).

Also please copypaste the text rather than provide a screenshot (ideally, format it as a quote).

**Comment by Tindtily** [comment]
> If you cannot follow instructions, I cannot help you...

soryy, wait a moment

**Comment by Tindtily** [comment]
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/5201107/230748471-12691a50-5ef6-48f7-84bb-f9a78fb6f80b.png">
`
$ DYLD_PRINT_LIBRARIES=1 DYLD_LIBRARY_PATH=$PWD ./python.exe -E -S -m sysconfig --generate-posix-vars
dyld[78800]: <A47D4674-260C-3927-88A3-6026F6905BE0> /private/var/folders/mk/f9j29v250m9cm59sb088b97h0000gn/T/python-build.20230409081545.71086/Python-2.7.18/python.exe
dyld[78800]: Library not loaded: '/System/Library/Frameworks/Python.framework/Versions/2.7/Python'
  Referenced from: '/private/var/folders/mk/f9j29v250m9cm59sb088b97h0000gn/T/python-build.20230409081545.71086/Python-2.7.18/python.exe'
  Reason: tried: '/System/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file)
[1]    78800 abort      DYLD_PRINT_LIBRARIES=1 DYLD_LIBRARY_PATH=$PWD ./python.exe -E -S -m sysconfig
`
Same error still

**Comment by native-api** [comment]
And you claim that there is a `libpython2.7.dylib` in the same directory as `python.exe`?

Because it seems there isn't.

For me, that prints:

```
admin@Mac-Admin Python-2.7.18 % DYLD_PRINT_LIBRARIES=1 DYLD_LIBRARY_PATH=$PWD ./python.exe -E -S -m sysconfig --generate-posix-vars
dyld[780]: <CE8A8481-A8FC-3388-9BF1-35A935AF0B78> /Users/admin/.pyenv/sources/2.7.18/Python-2.7.18/python.exe
dyld[780]: <C8BAA4B3-F526-3EC5-8A81-5A552AD51A47> /Users/admin/.pyenv/sources/2.7.18/Python-2.7.18/libpython2.7.dylib
dyld[780]: <EC3967B9-4A65-395D-AABA-DDD1986FFF3E> /usr/lib/libSystem.B.dylib
<etc>
```

Just to make sure, what does the following print (when you are in the directory with `python.exe`)?

```
otool -L python.exe
otool -L libpython2.7.dylib
```

**Comment by Tindtily** [comment]
> Just to make sure, what does the following print (when you are in the directory with `python.exe`)?

as it print 

```
$ otool -L python.exe
otool -L libpython2.7.dylib
python.exe:
	/System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.16)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 12.0.0, current version 12.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
libpython2.7.dylib:
	/Users/aaa/.pyenv/versions/2.7.18/lib/libpython2.7.dylib (compatibility version 2.7.0, current version 2.7.0)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 12.0.0, current version 12.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

**Comment by native-api** [comment]
Okay -- here's our discrepancy:

> ```
> python.exe:
> 	/System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.16)

It should read the same as `libpython` below -- i.e. "`/Users/aaa/.pyenv/versions/2.7.18/lib/libpython2.7.dylib`"

> libpython2.7.dylib:
> 	/Users/aaa/.pyenv/versions/2.7.18/lib/libpython2.7.dylib (compatibility version 2.7.0, current version 2.7.0)
> ```

Is this the real, unaltered text? It reads "`/Users/aaa/.pyenv/versions/2.7.18/lib/libpython2.7.dylib`" -- but you're supposed to be installing it under `/Users/skirmz/.pyenv/versions/2.7.18/lib` instead (except from trace.log):

```
clang <...> -Wl,-rpath,/Users/skirmz/.pyenv/versions/2.7.18/lib <...> -o python.exe
```

**Comment by Tindtily** [comment]
> s this the real, unaltered text? It reads "`/Users/aaa/.pyenv/versions/2.7.18/lib/libpython2.7.dylib`" -- but you're

i changed the username, what should i do next ?

**Comment by native-api** [comment]
So it actually reads `/Users/skirmz/.pyenv/versions/2.7.18/lib/libpython2.7.dylib`, there's no discrepancy?

**Comment by Tindtily** [comment]
> So it actually reads `/Users/skirmz/.pyenv/versions/2.7.18/lib/libpython2.7.dylib`, there's no discrepancy?

We can see it has discrepancy,  but i don't know how to do next to install python2.7.18 successfully in my mac

**Comment by native-api** [comment]
If the output of `otool -L libpython2.7.dylib` actually reads "`/Users/skirmz/.pyenv/versions/2.7.18/lib/libpython2.7.dylib`" -- then an antivirus is still the most probable cause.
We see that `python.exe` doesn't pick up the right `libpython2.7.dylib` as a dependency at compile time. Most probably, your antivirus starts scanning it -- but instead of holding up system calls that access it, it makes them return "access denied" or smth, making the compiler ignore it.

If however user names returned by `otool -L libpython2.7.dylib` and in `trace.log` are in fact different, you most probaby are doing something funny with paths or user accounts that you didn't tell us (like running some stuff as one user and some as a different one).

**Comment by Tindtily** [comment]
> If however user names returned by `otool -L libpython2.7.dylib` and in `trace.log` are in fact different, you most probaby are doing something funny with paths or user accounts that you didn't tell us (like running some stuff as one user and some as a different one).

i can confirm the username is same

**Comment by Tindtily** [comment]
i checked xprotect log ,it seems that the xprotect did prevent
```

2023-04-09 13:02:19.630275+0800 0x97b6c0   Info        0x0                  302    0    XprotectService: [com.apple.xprotect:xprotect] Xprotect is performing a direct malware and dylib scan: <private>
2023-04-09 13:02:19.665146+0800 0x979643   Info        0x0                  158    0    syspolicyd: (XprotectFramework) [com.apple.xprotect:xprotect] Invalidated
2023-04-09 13:02:19.665163+0800 0x97b6c0   Info        0x0                  302    0    XprotectService: [com.apple.xprotect:xprotect] Invalidated service side
```

**Comment by Tindtily** [comment]
I have to use the [official installer](https://www.python.org/ftp/python/2.7.18/python-2.7.18-macosx10.9.pkg) to install python 2.7.18

**Comment by native-api** [comment]
> See #2603 and #2392 on how to view its logs and possible workarounds.

I also found that `log show --predicate 'eventMessage like "*/python-build*"'` gives a more complete log than filtering by "`subsystem == "com.apple.xprotect"`" -- it will show all logs related to the build directory.

**Comment by sanan-go** [comment]
Hello. I can't switch to python 2.7.18 from system python (2.7.16)
I'm using pyenv v2.3.18 on macbook pro m1, macOS v12

Here's the behavior:
![telegram-cloud-photo-size-2-5463368365709052758-y](https://github.com/pyenv/pyenv/assets/85499373/d2cc85f1-eed5-4025-ba53-732a288711cc)

**Comment by guss77** [comment]
I have this issue on MacOS 12.6.9. Running `pyenv install -s 2.7.18`, I get this log:

```
BUILD FAILED (OS X 12.6.9 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/88/xnyppnvd2k34kbg5fbchhhmr0000gn/T/python-build.20231018152826.71534
Results logged to /var/folders/88/xnyppnvd2k34kbg5fbchhhmr0000gn/T/python-build.20231018152826.71534.log

Last 10 log lines:
                echo "generate-posix-vars failed" ; \
                rm -f ./pybuilddir.txt ; \
                exit 1 ; \
        fi
dyld[79803]: Library not loaded: '/System/Library/Frameworks/Python.framework/Versions/2.7/Python'
  Referenced from: '/private/var/folders/88/xnyppnvd2k34kbg5fbchhhmr0000gn/T/python-build.20231018152826.71534/Python-2.7.18/python.exe'
  Reason: tried: '/System/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file)
/bin/sh: line 1: 79803 Abort trap: 6           DYLD_LIBRARY_PATH=/var/folders/88/xnyppnvd2k34kbg5fbchhhmr0000gn/T/python-build.20231018152826.71534/Python-2.7.18 ./python.exe -E -S -m sysconfig --generate-posix-vars
generate-posix-vars failed
make: *** [pybuilddir.txt] Error 1
```

As far as I understand this is a build failure - the command that fails is ran before the actual installation - which is why `Python.ext` is built with the library path set to `/System/Library/Frameworks/Python.framework/Versions/2.7/Python` - which is were it is supposed to be installed.

Running from the command line, with the "PRINT" environment variable, it also fails in the same way :

```
$ cd /var/folders/88/xnyppnvd2k34kbg5fbchhhmr0000gn/T/python-build.20231018152826.71534
$ DYLD_PRINT_LIBRARIES=1 DYLD_LIBRARY_PATH=$PWD ./python.exe -E -S -m sysconfig --generate-posix-vars
dyld[84100]: <654BB8E1-B236-3DB4-9DDE-E287C23B924B> /private/var/folders/88/xnyppnvd2k34kbg5fbchhhmr0000gn/T/python-build.20231018152826.71534/Python-2.7.18/python.exe
dyld[84100]: Library not loaded: '/System/Library/Frameworks/Python.framework/Versions/2.7/Python'
  Referenced from: '/private/var/folders/88/xnyppnvd2k34kbg5fbchhhmr0000gn/T/python-build.20231018152826.71534/Python-2.7.18/python.exe'
  Reason: tried: '/System/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file)
Abort trap: 6
```

The `otool` output is as follows:

```
$ otool -L python.exe libpython2.7.dylib 
python.exe:
        /System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.16)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1775.118.101)
libpython2.7.dylib:
        /Users/ec2-user/.pyenv/versions/2.7.18/lib/libpython2.7.dylib (compatibility version 2.7.0, current version 2.7.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1775.118.101)
```

Obviously, both `/System/Library/Frameworks/Python.framework/Versions/2.7/Python` and `/Users/ec2-user/.pyenv/versions/2.7.18/lib/libpython2.7.dylib` do not exist.

I've tried to force dyld to load the `libpython2.7.dylib` using `DYLD_INSERT_LIBRARIES` - and I can see that it loads it, but it still output the same error:

```
$ DYLD_INSERT_LIBRARIES=$PWD/libpython2.7.dylib DYLD_PRINT_SEARCHING=1 DYLD_PRINT_LOADERS=1 ./python.exe -E -S -m sysconfig --generate-posix-varsdyld[4039]: PrebuiltLoaders not being used because DYLD_ env vars are set
dyld[4039]: using JustInTimeLoader 0x102cc1bf0 for /private/var/folders/88/xnyppnvd2k34kbg5fbchhhmr0000gn/T/python-build.20231018152826.71534/Python-2.7.18/python.exe
dyld[4039]: find path "/var/folders/88/xnyppnvd2k34kbg5fbchhhmr0000gn/T/python-build.20231018152826.71534/Python-2.7.18/libpython2.7.dylib"
dyld[4039]:   possible path(original path): "/var/folders/88/xnyppnvd2k34kbg5fbchhhmr0000gn/T/python-build.20231018152826.71534/Python-2.7.18/libpython2.7.dylib"
dyld[4039]:   found: dylib-from-disk: "/var/folders/88/xnyppnvd2k34kbg5fbchhhmr0000gn/T/python-build.20231018152826.71534/Python-2.7.18/libpython2.7.dylib"
dyld[4039]: using JustInTimeLoader 0x102cc3740 for /private/var/folders/88/xnyppnvd2k34kbg5fbchhhmr0000gn/T/python-build.20231018152826.71534/Python-2.7.18/libpython2.7.dylib
dyld[4039]: find path "/System/Library/Frameworks/Python.framework/Versions/2.7/Python"
dyld[4039]:   possible path(original path): "/System/Library/Frameworks/Python.framework/Versions/2.7/Python"
dyld[4039]:   possible path(default fallback): "/Library/Frameworks/Python.framework/Versions/2.7/Python"
dyld[4039]:   not found: "/System/Library/Frameworks/Python.framework/Versions/2.7/Python"
dyld[4039]: Library not loaded: '/System/Library/Frameworks/Python.framework/Versions/2.7/Python'
  Referenced from: '/private/var/folders/88/xnyppnvd2k34kbg5fbchhhmr0000gn/T/python-build.20231018152826.71534/Python-2.7.18/python.exe'
  Reason: tried: '/System/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/2.7/Python' (not a file)
Abort trap: 6
```

I do not believe the problem is that `python.exe` fails to load `libpython2.7.dylib` - I think there is some other issue going on that it can't access said folders (because they don't exist) and doesn't even get to what libraries it needs to load.
