### ISSUE TITLE
Cannot install `python 3.11.2` on MacOS Ventura 13.2.1

### ISSUE THREAD

**Issue by saurbhc** [pyenv/pyenv#2624]
Pyenv version:
```console
$ pyenv --version
pyenv 2.3.13
```

Pyenv installation error:
```console
$ pyenv install 3.11.2
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.11.2.tar.xz...
-> https://www.python.org/ftp/python/3.11.2/Python-3.11.2.tar.xz
Installing Python-3.11.2...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 13.2.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/pd/yvrfkz090wb4ws642ltnn3gw0000gn/T/python-build.20230217170607.67783
Results logged to /var/folders/pd/yvrfkz090wb4ws642ltnn3gw0000gn/T/python-build.20230217170607.67783.log

Last 10 log lines:
  "_libintl_setlocale", referenced from:
      __locale_setlocale in _localemodule.o
      __locale_localeconv in _localemodule.o
  "_libintl_textdomain", referenced from:
      __locale_textdomain in _localemodule.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Programs/_freeze_module] Error 1
make: *** Waiting for unfinished jobs....
2 warnings generated.
```

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS Ventura 13.2.1 (22D68)
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: pyenv 2.3.13
- [x] Python version: 3.11.2
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 14.0.0 (clang-1400.0.29.202)
- [x] Please attach the debug trace of the failing command as a gist: [trace.log](https://github.com/pyenv/pyenv/files/10769224/trace.log)
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory: [config.log](https://github.com/pyenv/pyenv/files/10769238/config.log) uploaded from local path -- `/var/folders/pd/yvrfkz090wb4ws642ltnn3gw0000gn/T/python-build.20230217170607.67783/Python-3.11.2/config.log`
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [-] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

**Comment by saurbhc** [comment]
These commands helped me:

1. un-installing openssl, gettext, readline
```console
$ brew uninstall --ignore-dependencies openssl gettext readline
```
2. re-installing openssl, gettext, readline (with -x86_64 architecture)
```console
$ /usr/bin/arch -x86_64 brew install openssl gettext readline
```
3. installing pyenv
```console
$ /usr/bin/arch -x86_64 pyenv install 3.11.2
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.11.2.tar.xz...
-> https://www.python.org/ftp/python/3.11.2/Python-3.11.2.tar.xz
Installing Python-3.11.2...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.11.2 to /Users/saurabhchopra/.pyenv/versions/3.11.2
```

All done!!

**Comment by native-api** [comment]
> These commands helped me:

This should be very useful: we've had a few other reports with the same error. Thank you!

**Comment by codercodingthecode** [comment]
I just wanted to add the difference, if you are using Mac m1/m2/arm based

```/usr/bin/arch -arm64 brew install openssl gettext readline```
and
```/usr/bin/arch -arm64 pyenv install 3.11.2```

mostly important is the key `-arm64`

**Comment by Rah1x** [comment]
> I just wanted to add the difference, if you are using Mac m1/m2/arm based
> 
> `/usr/bin/arch -arm64 brew install openssl gettext readline` and `/usr/bin/arch -arm64 pyenv install 3.11.2`
> 
> mostly important is the key `-arm64`

This didnt help me now in 2025 (trying to install ~3.13.2).
However brew has successfully installed the same version directly. So looks like the problem only exists in pyenv and not python or brew.

**Comment by traffictse** [comment]
> > I just wanted to add the difference, if you are using Mac m1/m2/arm based
> > `/usr/bin/arch -arm64 brew install openssl gettext readline` and `/usr/bin/arch -arm64 pyenv install 3.11.2`
> > mostly important is the key `-arm64`
> 
> This didnt help me now in 2025 (trying to install ~3.13.2). However brew has successfully installed the same version directly. So looks like the problem only exists in pyenv and not python or brew.
> 
> ```
> ==> Fetching python@3.13
> ==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/0eddaa29ec043a63a0f743a244e35c8ee992d3d9/Formula/p/python@3.13.rb
> ################################################################################################################################################################################## 100.0%
> ==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/8b5bcbb262d1ea4e572bba55043bf7d2341a6821/python/3.13-sysconfig.diff
> ################################################################################################################################################################################## 100.0%
> ==> Downloading https://files.pythonhosted.org/packages/d5/ae/09427bea9227a33ec834ed5461432752fd5d02b14f93dd68406c91684622/flit_core-3.10.1.tar.gz
> ################################################################################################################################################################################## 100.0%
> ==> Downloading https://files.pythonhosted.org/packages/47/3e/68beeeeb306ea20ffd30b3ed993f531d16cd884ec4f60c9b1e238f69f2af/pip-25.0.tar.gz
> ################################################################################################################################################################################## 100.0%
> ==> Downloading https://files.pythonhosted.org/packages/92/ec/089608b791d210aec4e7f97488e67ab0d33add3efccb83a056cbafe3a2a6/setuptools-75.8.0.tar.gz
> ################################################################################################################################################################################## 100.0%
> ==> Downloading https://files.pythonhosted.org/packages/8a/98/2d9906746cdc6a6ef809ae6338005b3f21bb568bea3165cfc6a243fdc25c/wheel-0.45.1.tar.gz
> ################################################################################################################################################################################## 100.0%
> ==> Downloading https://www.python.org/ftp/python/3.13.2/Python-3.13.2.tgz
> ################################################################################################################################################################################## 100.0%
> ==> Reinstalling python@3.13
> ==> Downloading https://formulae.brew.sh/api/formula.jws.json
> ==> Patching
> ==> Applying 3.13-sysconfig.diff
> ==> ./configure --enable-ipv6 --datarootdir=/****/python@3.13/3.13.2/share --datadir=/****/python@3.13/3.13.2/share --without-ensurepip --enable-loadable-sqlite-
> ==> make
> ==> make install PYTHONAPPSDIR=/****/python@3.13/3.13.2
> ==> make frameworkinstallextras PYTHONAPPSDIR=/****/python@3.13/3.13.2/share/python@3.13
> ==> /****/python@3.13/3.13.2/bin/python3.13 -m venv /private/tmp/pythonA3.13-20250207-59482-b6hmhj/Python-3.13.2/whl_build
> ==> /private/tmp/pythonA3.13-20250207-59482-b6hmhj/Python-3.13.2/whl_build/bin/pip3 install -v --no-binary :all: --no-index .
> ==> /private/tmp/pythonA3.13-20250207-59482-b6hmhj/Python-3.13.2/whl_build/bin/pip3 install -v --no-binary :all: --no-index .
> ==> /private/tmp/pythonA3.13-20250207-59482-b6hmhj/Python-3.13.2/whl_build/bin/pip3 install -v --no-binary :all: --no-index .
> ==> /private/tmp/pythonA3.13-20250207-59482-b6hmhj/Python-3.13.2/whl_build/bin/pip3 wheel -v --no-binary :all: --no-index --wheel-dir=/****/python@3.13/3.13.2/libexec .
> ==> /private/tmp/pythonA3.13-20250207-59482-b6hmhj/Python-3.13.2/whl_build/bin/pip3 wheel -v --no-binary :all: --no-index --wheel-dir=/****/python@3.13/3.13.2/Frameworks/Pyt
> ==> Downloading https://formulae.brew.sh/api/formula.jws.json
> ==> /****/python@3.13/3.13.2/bin/python3.13 -Im ensurepip
> ==> /****/python@3.13/3.13.2/bin/python3.13 -Im pip install -v --no-index --upgrade --isolated --target=/usr/local/lib/python3.13/site-packages /****/python@3.13
> 🍺  /****/python@3.13/3.13.2: 8,309 files, 191.6MB, built in 12 minutes 31 seconds
> ```
> 
> Then, if you check, its done:
> 
> ```
> python3 --version
> Python 3.13.2
> ```

M3. But I still failed... 
(base) DanielBurt@JoshuaGlennJenson ~ % /usr/bin/arch -arm64 pyenv install 3.12.2
python-build: use openssl@3 from homebrew
python-build: use readline from homebrew
Installing Python-3.12.2...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 15.3.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/_z/ynbxmm_50974xzlqhp9k3h8h0000gn/T/python-build.20250212151731.91771
Results logged to /var/folders/_z/ynbxmm_50974xzlqhp9k3h8h0000gn/T/python-build.20250212151731.91771.log

Last 10 log lines:
/opt/homebrew/bin/ginstall -c -m 755 Modules/zlib.cpython-312-darwin.so /Users/DanielBurt/.pyenv/versions/3.12.2/lib/python3.12/lib-dynload/zlib.cpython-312-darwin.so
/opt/homebrew/bin/ginstall -c -m 755 Modules/_dbm.cpython-312-darwin.so /Users/DanielBurt/.pyenv/versions/3.12.2/lib/python3.12/lib-dynload/_dbm.cpython-312-darwin.so
/opt/homebrew/bin/ginstall -c -m 755 Modules/readline.cpython-312-darwin.so /Users/DanielBurt/.pyenv/versions/3.12.2/lib/python3.12/lib-dynload/readline.cpython-312-darwin.so
/opt/homebrew/bin/ginstall -c -m 755 Modules/_md5.cpython-312-darwin.so /Users/DanielBurt/.pyenv/versions/3.12.2/lib/python3.12/lib-dynload/_md5.cpython-312-darwin.so
/opt/homebrew/bin/ginstall -c -m 755 Modules/_sha1.cpython-312-darwin.so /Users/DanielBurt/.pyenv/versions/3.12.2/lib/python3.12/lib-dynload/_sha1.cpython-312-darwin.so
/opt/homebrew/bin/ginstall -c -m 755 Modules/_sha2.cpython-312-darwin.so /Users/DanielBurt/.pyenv/versions/3.12.2/lib/python3.12/lib-dynload/_sha2.cpython-312-darwin.so
/opt/homebrew/bin/ginstall -c -m 755 Modules/_sha3.cpython-312-darwin.so /Users/DanielBurt/.pyenv/versions/3.12.2/lib/python3.12/lib-dynload/_sha3.cpython-312-darwin.so
/opt/homebrew/bin/ginstall -c -m 755 Modules/_blake2.cpython-312-darwin.so /Users/DanielBurt/.pyenv/versions/3.12.2/lib/python3.12/lib-dynload/_blake2.cpython-312-darwin.so
ginstall: cannot stat 'Modules/_blake2.cpython-312-darwin.so': No such file or directory
make: *** [sharedinstall] Error 1

**Comment by Rah1x** [comment]
> pyenv

I said I didnt use `pyenv`. Try directly installing from homebrew instead of pyenv.

`brew install python@3.13`
