### ISSUE TITLE
the "pyenv global system" command does not work in windows 11

### ISSUE THREAD

**Issue by akash-cis** [pyenv/pyenv#2627]
I want to use the default system python installation on my machine (windows 11) and for that, I tried the command `pyenv global system`, but it does not work it throws a warning as shown below.

```
$ pyenv local system
pyenv specific python requisite didn't meet. Project is using different version of python.
Install python 'system' by typing: 'pyenv install system'

$ pyenv local system
pyenv specific python requisite didn't meet. Project is using different version of python.
Install python 'system' by typing: 'pyenv install system'

$ pyenv shell system
pyenv specific python requisite didn't meet. Project is using different version of python.
Install python 'system' by typing: 'pyenv install system'
```

how can i use my system installed python?

**Comment by native-api** [comment]
Please add the required disgnostic data as per the issue template.

Note that Pyenv doesn't support native Windows. Either you're running in WSL, or your using something else, like https://github.com/pyenv-win/pyenv-win.
