### ISSUE TITLE
`pyenv rehash` is invoked automatically which can cause problems with  insufficient rights

### ISSUE THREAD

**Issue by maldag** [pyenv/pyenv#2628]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Ubuntu 20.04
- [ ] amd64
- [ ] pyenv version:
- [ ] Python version:

When new packages are installed with pip, pyenv rehash gets invoked automatically. This seems to be a new feature.
It will cause problems when pyenv itself is installed with root priliveges (e.g. also some preinstalled python versions in docker images).
This site-repository will not be writable with user rights which pip will correctly detect. Pyenv is still trying to do the rehash which will result in an error.

```
pip install hjson
Defaulting to user installation because normal site-packages is not writeable
Collecting hjson
  Downloading hjson-3.1.0-py3-none-any.whl (54 kB)
Installing collected packages: hjson
Successfully installed hjson-3.1.0
WARNING: You are using pip version 21.1.3; however, version 23.0.1 is available.
You should consider upgrading via the '/opt/pyenv/versions/3.9.6/bin/python3.9 -m pip install --upgrade pip' command.
pyenv: cannot rehash: /opt/pyenv/shims isn't writable
```

### Expected behaviour

Either:
* Do not fail after failed rehash (not preferred)
* Detect not writable path and use `~/.local/..` path

**Comment by native-api** [comment]
Calling `rehash` after running `pip` is intended -- because it may have installed executables so the list of shims needs to be updated. So the error message is useful as it has informed you that this important step has not been done.
[`pip` already does not fail if `rehash` fails](https://github.com/pyenv/pyenv/blob/86a4423bbb8ba5ed8db0f998376eead288050322/pyenv.d/exec/pip-rehash/pip#L23-L31).

Pyenv is not designed for separation of privileges out of the box atm.
Though there can always be a start, there's probably an easier way without adding complication.

**Comment by AnthonyVH** [comment]
Is there any easy way to work around this? I'm running into the same issue.
