### ISSUE TITLE
can't install python 3.4.2 on osx 10.9.4

### ISSUE THREAD

**Issue by RuleTheMoments** [pyenv/pyenv#263]
i try to install a python 3.4.2 using pyenv, but it does not work

<pre>
CFLAGS="-I/Application/Xcode.app/Contents/Developer/usr/include -I$(brew --prefix openssl)/include -I$(brew --prefix sqlite3)/include -I$(xcrun --show-sdk-path)/usr/include" LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix sqlite3)/lib" pyenv install -v 3.4.2
</pre>

error like below

<pre>
Downloading Python-3.4.2.tgz...
-> https://www.python.org/ftp/python/3.4.2/Python-3.4.2.tgz
Installing Python-3.4.2...
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/yyuu/pyenv/wiki/Common-build-problems

BUILD FAILED

Inspect or clean up the working tree at /var/folders/qp/_wylgkcd7310hzghc74wdcwc0000gn/T/python-build.20141029131544.58389
Results logged to /var/folders/qp/_wylgkcd7310hzghc74wdcwc0000gn/T/python-build.20141029131544.58389.log

Last 10 log lines:
(cd /Users/arena/.pyenv/versions/3.4.2/share/man/man1; ln -s python3.4.1 python3.1)
if test "xupgrade" != "xno"  ; then \
        case upgrade in \
            upgrade) ensurepip="--upgrade" ;; \
            install|*) ensurepip="" ;; \
        esac; \
         ./python.exe -E -m ensurepip \
            $ensurepip --root=/ ; \
    fi
Ignoring ensurepip failure: pip 1.5.6 requires SSL/TLS
</pre>

i already installed openssl
<pre>
$ brew install openssl
Warning: openssl-1.0.1j already installed
<pre>

**Comment by Frank-the-Obscure** [comment]
I also ran into this issue using OS X 10.10.3, fixed using the CFLAGS environment variable.
>https://github.com/yyuu/pyenv/wiki/Common-build-problems
>On Mac OS X 10.9 and 10.10 you may need to set the CFLAGS environment variable when installing a new version in order for configure to find the zlib headers (XCode command line tools must be installed first):  
CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install -v 2.7.7
Alternatively, try reinstalling XCode command line tools for your OS (especially if you just upgraded your OS)
