### ISSUE TITLE
[WINGET] Winget support?

### ISSUE THREAD

**Issue by coconutbird** [pyenv/pyenv#2632]
Hi, would you guys consider getting added to WinGet and https://winstall.app/

Would allow for easy setup on new machines :)

**Comment by native-api** [comment]
Pyenv doesn't support Windows outside of WSL. Is that something that these products are designed for?

**Comment by native-api** [comment]
Maybe you'd rather contact https://github.com/pyenv-win/pyenv-win.

**Comment by coconutbird** [comment]
> Maybe you'd rather contact https://github.com/pyenv-win/pyenv-win.

Oops yep, I accidentally commented on the wrong repo.
