### ISSUE TITLE
Where pyenv or which pyenv doesnt show location of gitmodule if installed via git

### ISSUE THREAD

**Issue by ridhwaans** [pyenv/pyenv#2636]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ x] Platform information: WSL2 Ubuntu 22.04
- [x] OS architecture: x86
- [x] pyenv version: pyenv 2.3.14
- [x] Python version: 3.9.4
- [x] C Compiler information: gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [x] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

Hello,

running `where pyenv` or `which pyenv` always returns  
```
pyenv () {
        local command
        command="${1:-}"
        if [ "$#" -gt 0 ]
        then
                shift
        fi
        case "$command" in
                (activate | deactivate | rehash | shell) eval "$(pyenv "sh-$command" "$@")" ;;
                (*) command pyenv "$command" "$@" ;;
        esac
}
```

instead it should be showing the directory if it was installed via git ( as seen in .gitmodules)

Feedback appreciate on how to fix

Thanks

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/issues/2389#issuecomment-1172650331

> this is by design. When the command you query is a shell function, Zsh's `which` prints the function's definition.
> 
> To see _both_ the shell function's definition and the program on PATH, run `which -a pyenv`.
