### ISSUE TITLE
`findutils` package is needed for installing python versions on openSUSE Tumbleweed container

### ISSUE THREAD

**Issue by fabiobarkoski** [pyenv/pyenv#2639]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): openSUSE Tumbleweed
- [x] OS architecture (e.g. amd64): x86_64

Seems like is necessary to install the package `findutils` to properly be able to install python versions with pyenv inside the openSUSE Tumbleweed container.
My final build environment dependencies:
```bash
zypper install gcc automake bzip2 libbz2-devel xz xz-devel openssl-devel ncurses-devel \
readline-devel zlib-devel tk-devel libffi-devel sqlite3-devel libgdbm-devel make findutils
```
Happy to work on adding the `findutils` package to [openSUSE](https://github.com/pyenv/pyenv/wiki#suggested-build-environment) if it's agreed this is worthwhile!

**Comment by native-api** [comment]
Python-Build [does use `find`](https://github.com/pyenv/pyenv/blob/ad15c75e0ea76f339259c4a23cfae2be0eeb10db/plugins/python-build/bin/python-build#L1129) so you can surely add the corresponding package to https://github.com/pyenv/pyenv/wiki .

It was most likely not present because it's usually preinstalled -- [but apparently not in official ocontainers](https://build.opensuse.org/package/view_file/openSUSE:Factory/opensuse-tumbleweed-image/config.kiwi?expand=1).

**Comment by fabiobarkoski** [comment]
Done. Thanks for the reply.
