### ISSUE TITLE
create `deb` package for pyenv

### ISSUE THREAD

**Issue by fabiobarkoski** [pyenv/pyenv#2640]
I've noticed that the pyenv has an `rpm` package on openSUSE, but searching on Linux Mint seems that doesn't have one for `.deb` based systems. So it's not a good idea to make one?
About the `rpm` version, I would like to try to contribute.

**Comment by native-api** [comment]
In any case, that needs to be a separate repository. AFAIK Debian even enforces that by requiring that packaging code exists outside of the main codebase.

**Comment by fabiobarkoski** [comment]
Sure, no problem. Looking at the organization repositories I don't find the RPM repository. So is it a good idea to make a repository for each of them? Or the [pyenv-installer](https://github.com/pyenv/pyenv-installer) meets that's necessities enough.

**Comment by native-api** [comment]
@karthek-git has already written such a package for Debian: https://salsa.debian.org/karthek/pyenv/

I suggest you work with him on any improvements.

**Comment by native-api** [comment]
Still, do not hesitate to let us know if anything needs to be done here from our side.

**Comment by fabiobarkoski** [comment]
Sure, thank you
