### ISSUE TITLE
Any way to change the bundled pip version?

### ISSUE THREAD

**Issue by brevity2021** [pyenv/pyenv#2643]
When I use pyenv to install python 3.9.0/3.9.1 on my mac, the bundled pip version is 20.2.3, which is too old for me. (Interestingly, when I install python 3.8.16 the bundled pip version is 22.0.4). 

I need to manually update the pip versions after running `python -m venv [virtual_env_name]`, which is inconvenient. Any way to change the bundled pip version for Python 3.9x?

- [x] Platform information (e.g. Ubuntu Linux 16.04): Mac
- [x] OS architecture (e.g. amd64): MacOS Montery
- [x] pyenv version: 2.3.15
- [x] Python version: 3.9.1

**Comment by native-api** [comment]
[Venv installs Pip bundled in the `ensurepip` module](https://github.com/python/cpython/blob/634cb61909b1392f0eef3e749931777adb54f16e/Lib/venv/__init__.py#L357-L360). [There's no supported way to upgrade that](https://docs.python.org/3/library/ensurepip.html).

You can however automate upgrading Pip when creating an environment with Pyenv-Virtualenv -- with the https://github.com/jawshooah/pyenv-default-packages [plugin](https://github.com/pyenv/pyenv/wiki/Plugins).

**Comment by native-api** [comment]
That plugin doesn't pass `-U` -- but you can pass it yourself [as it simply copypastes the provided lines into the command line](https://github.com/jawshooah/pyenv-default-packages/blob/fb6f71a0288b5aec5723b6118aa0ca02e2cc9a23/libexec/default-packages.sh#L15).
