### ISSUE TITLE
Can't install x86 version of 3.8.16 on M1 Mac?

### ISSUE THREAD

**Issue by ut-adamc** [pyenv/pyenv#2644]
### Discussed in https://github.com/pyenv/pyenv/discussions/2641

<div type='discussions-op-text'>

<sup>Originally posted by **ut-adamc** March  9, 2023</sup>
PYENV_ROOT was set to $HOME/python/x86_64. pyenv had been installed using an x86 version of homebrew, based in /opt/homebrew_x86

`BUILD FAILED (OS X 12.6.3 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/wc/01hqy4890zv7n7wnqnkjr7vc0000gq/T/python-build.20230309144347.26579
Results logged to /var/folders/wc/01hqy4890zv7n7wnqnkjr7vc0000gq/T/python-build.20230309144347.26579.log

Last 10 log lines:
DYLD_LIBRARY_PATH=/var/folders/wc/01hqy4890zv7n7wnqnkjr7vc0000gq/T/python-build.20230309144347.26579/Python-3.8.16 ./python.exe -E -S -m sysconfig --generate-posix-vars ;\
	if test $? -ne 0 ; then \
		echo "generate-posix-vars failed" ; \
		rm -f ./pybuilddir.txt ; \
		exit 1 ; \
	fi
dyld[39034]: symbol not found in flat namespace (_libintl_bindtextdomain)
/bin/sh: line 1: 39034 Abort trap: 6           DYLD_LIBRARY_PATH=/var/folders/wc/01hqy4890zv7n7wnqnkjr7vc0000gq/T/python-build.20230309144347.26579/Python-3.8.16 ./python.exe -E -S -m sysconfig --generate-posix-vars
generate-posix-vars failed
make: *** [pybuilddir.txt] Error 1`

I also tried installing gcc-11 and compiling with that (`CC=gcc-11 pyenv install 3.8.16`); same result.</div>

**Comment by native-api** [comment]
Please add the necessary diagnostic information as per the issue template.

**Comment by native-api** [comment]
Are you posting from a mobile browser? IIRC it doesn't show up when creating an issue in that case.
In the repository, it's at https://github.com/pyenv/pyenv/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by HackingTrees** [comment]
Judging by the contents of your config.log, you’re showing that you’re running a non-standard version of Python on the M-series machines.

(All versions of Python 2 only support 64-bit machines, and thus run through `aarch -x86_64` as part of compatibility - running through Rosetta 2.)

Try giving `pyenv local --unset` a chance, check to see if Python dumps back to Python 3.X from Xcode or the built-in version in /usr/bin, and then give `pyenv install 3.8.16` another go. I have a strange feeling that Rosetta is telling pyenv enough info to install the ARM version of Python while still trying to push an i386/i486 architecture as part of the build process.

**Comment by native-api** [comment]
> > python-build: definition not found: 3.18.16

Not seeing anything wrong in this line?
