### ISSUE TITLE
ironpython-2.7 install failure: cannot execute binary file

### ISSUE THREAD

**Issue by deronnax** [pyenv/pyenv#2645]
i was curious to see if IronPython could install on my MacOS, and I got this error trying to install it:
``` 
➜ pyenv install ironpython-2.7.7
Downloading IronPython-2.7.7.zip...
-> https://github.com/IronLanguages/main/releases/download/ipy-2.7.7/IronPython-2.7.7-win.zip
Installing IronPython-2.7.7...
Installing pip from https://bootstrap.pypa.io/get-pip.py...
error: failed to install pip via get-pip.py

BUILD FAILED (OS X 13.2.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/nc/hnmjf_855ydc744m77xxp32m0000gn/T/python-build.20230316111700.96755
Results logged to /var/folders/nc/hnmjf_855ydc744m77xxp32m0000gn/T/python-build.20230316111700.96755.log

Last 10 log lines:
  inflating: IronPython-2.7.7/Tutorial/load.xml
  inflating: IronPython-2.7.7/Tutorial/pyevent.py
  inflating: IronPython-2.7.7/Tutorial/spellcheck.py
  inflating: IronPython-2.7.7/Tutorial/Tutorial.htm
 extracting: IronPython-2.7.7/Tutorial/vbx.bat
  inflating: IronPython-2.7.7/Tutorial/wfdemo.py
  inflating: IronPython-2.7.7/Tutorial/winforms.py
  inflating: IronPython-2.7.7/Tutorial/xmlutil.py
/var/folders/nc/hnmjf_855ydc744m77xxp32m0000gn/T/python-build.20230316111700.96755/IronPython-2.7.7 /var/folders/nc/hnmjf_855ydc744m77xxp32m0000gn/T/python-build.20230316111700.96755 ~/dev
/usr/local/Cellar/pyenv/2.3.15/plugins/python-build/bin/python-build: line 2004: /Users/mathieu/.pyenv/versions/ironpython-2.7.7/bin/python: cannot execute binary file
```
There is actually a `win` suffix in the zip archive name itself. Are we sure it works? If yes, I think we could improve the user experience with a better error message/guidance towards what the user should do/install to get the installation working.
If we are not sure it worked one day, we should remove it.

I am willing to spend some time fixing/improving that thing, or removing it, be it needed.
Waiting for your input.

**Comment by native-api** [comment]
You can work around the error by removing "`ensurepip`" from https://github.com/pyenv/pyenv/blob/4ef81b5c7a32d8f10cd288876d69f6e44047c14d/plugins/python-build/share/python-build/ironpython-2.7.7 . Pip will not be installed -- but when you can't run anything, that hardly matters.

**Comment by deronnax** [comment]
@native-api this version of IronPython is EOL but the project itself is not. Actually the first Python 3 release ever ([IronPython 3.4](https://github.com/IronLanguages/ironpython3/releases/tag/v3.4.0)) has been released in December, I was considering implementing the installation in PyEnv.

Do we have stats on wether people download IronPython from PyEnv at all? I hardly thinks to. Btw, newer IronPython2.7 have been released meanwhile (see [IronPython 2.7.12](https://github.com/IronLanguages/ironpython2/releases/tag/ipy-2.7.12)) and they look much more usable and crossplatform (there are many release format with no `win` in the the name).

But maybe people that uses IronPython don't install it from PyEnv and there is no point adding it in PyEnv.

**Comment by deronnax** [comment]
(I changed the title because I was able to reproduce on a Debian)

**Comment by native-api** [comment]
Since Pyenv is the industry standard for managing alt Python versions with minimal hassle, it's definitely worth adding whatever Pythons are in non-marginal use and can work with it -- ppl will use it as it's the easiest way.

**Comment by deronnax** [comment]
I am still bothered by the fact that pyenv install will just crash with an obscure error message. To not experience it, you have to have a good understanding of ironpython and dotnet/mono (I read the IronPython documentation, just .net won't do it), and if you do so, you won't install it using pyenv. By the way, the recipe is ~ 7 years old and IronPython released more than 10 (major) versions meanwhile and nobody ever add them to PyEnv in those 7 years, which to me confirms that nobody using IronPython uses pyenv to install it (and the current ironpython recipes have probably almost never been used either).

But we can close the issue.

**Comment by native-api** [comment]
It was added https://github.com/pyenv/pyenv/pull/775 . It says there that it was tested to work in Ubuntu 16.04 and requires Mono.

We can surely add a check for Mono.

**Comment by native-api** [comment]
AFAIK .NET is now also available for UNIX-like OSes -- so we could check for that, too, if this IronPython release is compatible.

**Comment by deronnax** [comment]
Yup initially I was planning to spend some time fixing it but I will actually not.
