### ISSUE TITLE
Can't use 'which' command to figure out how to uninstall pyenv.

### ISSUE THREAD

**Issue by bgenchel** [pyenv/pyenv#2661]
On both my Mac (M1 Pro Max, Ventura 13.2.1), and my VM (Ubuntu 5.15.0-1016-gcp), when I run `which pyenv`, I get the following: 
```
pyenv () {
        local command
        command="${1:-}"
        if [ "$#" -gt 0 ]
        then
                shift
        fi
        case "$command" in
                (activate | deactivate | rehash | shell) eval "$(pyenv "sh-$command" "$@")" ;;
                (*) command pyenv "$command" "$@" ;;
        esac
}
```
I'm trying to figure out how to uninstall it because it stopped being able to install any python versions (tried all fixes), and the above code doesn't enable me to find out where the command is so I can get rid of it.

**Comment by anton-petrov** [comment]
It all depends on how you installed pyenv. If you used brew, then you can remove it with `brew remove pyenv`. Otherwise, if you installed manually, then just delete the directory `rm -rf ~/.pyenv`

**Comment by native-api** [comment]
If the name you're querying is a shell function, Zsh's `which` prints out the contents of that function. Use `which -a` to print what's found on the filesystem as well.
