### ISSUE TITLE
_decimal module is not accessible if you run python on ARM-based mac

### ISSUE THREAD

**Issue by PSzczepanski1996** [pyenv/pyenv#2662]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS Ventura 13.2.1
- [x] OS architecture (e.g. amd64): Apple Silicon
- [x] pyenv version: 2.3.16
- [x] Python version: 3.8.16
- [x] C Compiler information (e.g. gcc 7.3): Clang 14.0.0 and GCC 11.3.0
![image](https://user-images.githubusercontent.com/21007545/228785918-989c43a6-2234-4965-95df-3a3afdbb7889.png)

Project is working without problems on my Intel-mac which I'm using at home, but for some reason on my ARM Mac Mini it does not find `_decimal` module. I know there is `decimal` module but I don't wanna have problems with merges while switching syntax one to another on both of my machines.

How should I fix it? Is there compilation quirk that is causing this problem? Maybe I miss binary package in `brew`?

**Comment by native-api** [comment]
Please provide the necessary diagnostic information as per the issue template.

**Comment by PSzczepanski1996** [comment]
Okey, I "somehow" fixed it by uninstalling `mpdecimal` package from brew. I also tried to pass information/flag for compiler to use my system library/dependency but it did not fix the issue, so uninstalling resolves problem (temporary?) for me.
