### ISSUE TITLE
Unable to install 3.8.9 on macos 13.3

### ISSUE THREAD

**Issue by drorata** [pyenv/pyenv#2667]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macos 13.3
- [x] OS architecture (e.g. amd64): M1 Pro
- [x] pyenv version: 2.3.16
- [x] Python version: 3.10.4
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- [ ] Please attach the debug trace of the failing command as a gist: [gist](https://gist.github.com/drorata/c29cb85793333537df49459c83435933)
- [ ] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

I'm unable to build 3.8.9. Other version like 3.8.10 worked nicely.

**Comment by native-api** [comment]
You probably have `arch` from Homebrew on PATH.

https://github.com/pyenv/pyenv/wiki/Common-build-problems#keg-only-homebrew-packages-are-forcibly-linked--added-to-path

**Comment by drorata** [comment]
This is indeed very likely. However, nothing in the error message nor in the verbose output matches the errors that are mentioned in the link you shared. Thanks a lot!

**Comment by native-api** [comment]
> This is indeed very likely. However, nothing in the error message nor in the verbose output matches the errors that are mentioned in the link you shared. Thanks a lot!

Fair point. Added the known error messages to the wiki.
