### ISSUE TITLE
pyenv workon virtualenv is invalid in windows

### ISSUE THREAD

**Issue by JhosuaSparrow** [pyenv/pyenv#2669]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04):windows 10
- [ ] OS architecture (e.g. amd64):amd 64
- [ ] pyenv version:all
- [ ] Python version:all
- [ ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [ ] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

In windows, install python by pyenv, install virtualenv, virtualenvwrapper-win，workon test-env, but not change virtualenv.
Than find {PYENV}\shims\workon.bat
When call workon command, run {PYENV}\shims\workon.bat, but this file to run workon by pyenv exec, 
pyenv exec workon virtualenv can not change PATH in cmd window.

![image](https://user-images.githubusercontent.com/13247149/230022084-cf67ffe0-56f8-43d0-bfae-127a7ac62826.png)

So change the {PYENV}\shims\workon.bat
![image](https://user-images.githubusercontent.com/13247149/230022345-e218f3cd-d1da-419f-82d9-0eabd4827eb9.png)

![image](https://user-images.githubusercontent.com/13247149/230026160-3380537b-325e-4329-9e3d-fdd7cae32394.png)

Get version by `set /p CURRENT_VERSION=<%PYENV%\version`

**Comment by native-api** [comment]
[Pyenv-Win is a different project](https://github.com/pyenv-win/pyenv-win).
