### ISSUE TITLE
Show progress bar for downloading

### ISSUE THREAD

**Issue by xu-cheng** [pyenv/pyenv#267]
It's frustrating no knowing the state for a long time downloading.

**Comment by ulgens** [comment]
It could be the part of --verbose mode.

**Comment by gera2ld** [comment]
I just defined a function to download the source file first and then install it with pyenv.

```sh
PYTHON_MIRROR=https://www.python.org/ftp/python
PYENV_CACHE_DIR=~/.pyenv/cache

pyinstall() {
  filename=Python-$1.tar.xz
  mkdir -p $PYENV_CACHE_DIR
  curl -o /tmp/$filename $PYTHON_MIRROR/$1/$filename
  mv /tmp/$filename $PYENV_CACHE_DIR/$filename
  pyenv install $1
}

pyinstall 3.7.0
```

**Comment by samdup123** [comment]
running with --verbose gives you some idea that things are happening

**Comment by nurettin** [comment]
I use a network monitor to see if download is still in progress.
