### ISSUE TITLE
Python Local not changing python version: python -V vs Python -V

### ISSUE THREAD

**Issue by emersondelemmus** [pyenv/pyenv#2672]
I installed pyenv using homebrew and it does not switch python versions using `pyenv local 3.11.0` and checking with `python -V`. However, it does appear to work if I use uppercase 'P' version command: `Python -V'
```python
$ python -V
Python 3.9.6
$ pyenv local 3.11.0
$ pyenv versions
  system
 * 3.11.0 (set by /Users/SampleUser/SampleFolder/.python-version)

$ python -V
Python 3.9.6

$ Python -V
Python 3.11.0
``` 

The following is my ~/.zshrc contents

alias python=/usr/bin/python3
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv init --path)"

Is this by design? Am I supposed to use uppercase `Python -args` command in my pyenv directory? This is not stated in **any** documentation so far. It's very misleading. All tutorials and guides use lowercase `python -args` as default.

**Comment by native-api** [comment]
>    alias python=/usr/bin/python3

Remove the alias. It overrides Pyenv's shim.

**Comment by native-api** [comment]
I dunno where the uppercase Python comes from. Maybe some releases create such an executable.

What do `which Python` and `pyenv which Python` say?

**Comment by native-api** [comment]
...and `readlink $(pyenv which Python)` ?

**Comment by emersondelemmus** [comment]
> > alias python=/usr/bin/python3
> 
> Remove the alias. It overrides Pyenv's shim.

Removing the alias causes `python -V` error:
```python
  pyenv: python: command not found. The 'Python' command exists in these python versions: 3.11.0. 
```
Removing the alias causes my system python 3.9.6 to be obscured. 
This error also applies to command `readlink $(pyenv which Python)

Also which python now points to pyenv enviornment only.
```python
$ which python
/Users/SampleUser/.pyenv/shims/Python
```

**Comment by emersondelemmus** [comment]
> > alias python=/usr/bin/python3
> 
> Remove the alias. It overrides Pyenv's shim.

Removing the alias + installing `3.9.6` & running `pyenv global 3.9.6` worked! It restored my python global default `3.9.6` and my local project python version to `3.11.0`

Thank you very much!
