### ISSUE TITLE
Parser/parser.c:38718:1: internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by JoyfulAndSpeedyMan** [pyenv/pyenv#2673]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 14.04 
- [x] OS architecture (e.g. amd64):  amd64
- [x] pyenv version: 2.3.17
- [x] Python version: 3.11.3
- [x] C Compiler information (e.g. gcc 7.3):  4.8.4
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
  * [trace.log](https://github.com/pyenv/pyenv/files/11167838/trace.log)

- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
  * [config.log](https://github.com/pyenv/pyenv/files/11167874/config.log)
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

**Comment by native-api** [comment]
Any "internal compiler error" is the compiler's problem.

I see ythat you're building a very recent Python with a very old compiler. This combination was definitely not tested by upstream thus there won't be any workarounds in Python's code.

The best would probably be to try with a newer compiler (build it from source if needed; there are probably 3rd-party debs as well).
