### ISSUE TITLE
Manpage: Reference to the non-existing file /usr/share/pyenv/pyenv_user_setup.bash

### ISSUE THREAD

**Issue by tomschr** [pyenv/pyenv#2682]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
* [x] Make sure your problem is not derived from plugins.

This issue is not bound to a specific pyenv release.

### Description

The manpage under `man/man1/pyenv.1` contains a reference to a file which doesn't exist (`/usr/share/pyenv/pyenv_user_setup.bash`):

https://github.com/pyenv/pyenv/blob/a57e0b5019c1d5d08d3311306bde3cf6c58997a2/man/man1/pyenv.1#L15

I'm wondering how this be solved. I see two solutions:

1. use the bash completion file under [`completions/pyenv.bash`](https://github.com/pyenv/pyenv/tree/master/completions) 
2. rewrite it and use the section from https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv

If you want to go even further, you might consider _generating the man page from source_ rather than adding it as a separate entity. That would avoid that the manpage would become stale and outdated. But maybe that is beyond the scope of this issue.

What do you think?

### References

* [bsc#1210030](https://bugzilla.suse.com/show_bug.cgi?id=1210030)

**Comment by native-api** [comment]
CC @karthek-git

**Comment by karthek-git** [comment]
The man page is initially written for debian.
That file exists in my debian package and is for setting up bash shell.
[/debian/int/pyenv_user_setup.bash](https://salsa.debian.org/karthek/pyenv/-/blob/0dab7855a9a9e0e9addebe026205ec78d7a1ea49/debian/int/pyenv_user_setup.bash)

**Comment by tomschr** [comment]
Thanks for the explanation.

I could imagine the following solutions:

* Mention Debian. 
  This would give people from other distributions a hint. However, it's still not clear what non-Debian users has to do.
* Incorporate this little script into this repo.
* Remove the reference to this script.
  Just include the lines into the man page. Normally, I wouldn't recommend that approach. However, in this case, it's only three lines and they are very general. It's expected that they won't change.
* Do something completely different (what I wrote in my first comment).

**Comment by karthek-git** [comment]
We could go with third approach and I'll patch the man page for debian

**Comment by tomschr** [comment]
Can I help with this issue? Prepare a PR? Or are anybody already working on it? :wink: I don't want to interfere with anybody. :slightly_smiling_face:

**Comment by karthek-git** [comment]
@tomschr 
Go ahead. I'm a little busy right now. So, I haven't started working on it yet.
