### ISSUE TITLE
BUILD FAILED (Ubuntu 20.04 using python-build 2.3.17-5-ga57e0b50) "configure: error: cannot run C compiled programs"

### ISSUE THREAD

**Issue by dreamerwyx** [pyenv/pyenv#2683]
### Description
- [ ] Platform information (WSL2 Ubuntu 20.04):
- [ ] OS architecture : x86_64
- [ ] pyenv version: pyenv 2.3.17-5-ga57e0b50
- [ ] Python version: any version(I've tried other versions, such as `3.9`, `3.10`)
```
$ pyenv install 3.8.5
Installing Python-3.8.5...
patching file Misc/NEWS.d/next/Build/2021-10-11-16-27-38.bpo-45405.iSfdW5.rst
patching file configure
patching file configure.ac

BUILD FAILED (Ubuntu 20.04 using python-build 2.3.17-5-ga57e0b50)

Inspect or clean up the working tree at /tmp/python-build.20230418124140.24900
Results logged to /tmp/python-build.20230418124140.24900.log

Last 10 log lines:
checking for --with-universal-archs... no
checking MACHDEP... "linux"
checking for gcc... /home/tdpp/tools/gcc9.3/gcc-ubuntu-9.3.0-2020.03-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/tmp/python-build.20230418124140.24900/Python-3.8.5':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

try：
```bash
sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev
```
it doesn‘t work for me.

I redid it in `VMware Ubuntu 18.04` and got the same issue.

**Comment by native-api** [comment]
This means either a broken compiler or incorrect compiler flags in envvars.

Check `config.log` in the build directory (specified under the "BUILD FAILED" message) for the exact error occurred and the program that was attempted to build.

**Comment by native-api** [comment]
From what I can see, you're using an ARM64 compiler on an x64 machine. Of course, the resulting programs cannot run. The error message even tells you what to do if that's your intention and you want to cross-compile (though it's rather meaningles to do for Pyenv's use case).

**Comment by dreamerwyx** [comment]
> From what I can see, you're using an ARM64 compiler on an x64 machine. Of course, the resulting programs cannot run. The error message even tells you what to do if that's your intention and you want to cross-compile (though it's rather meaningless to cross-compile for Pyenv's use case).

Sorry, I forgot to configure the ARM64 cross compilation environment on my device a few days ago and made modifications to `CC`. I only found out where the problem lies after reading your reply. After removing the ARM64 compilation environment, pyenv can work normally.

Thank you very much.
