### ISSUE TITLE
Can't install python 3.6.0 in Mac OS X Ventura 13.3.1

### ISSUE THREAD

**Issue by khalld** [pyenv/pyenv#2685]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
* [x] Make sure your problem is not derived from packaging
* [x] Make sure your problem is not derived from plugins.

### Description
Platform information (e.g. Ubuntu Linux 16.04):
`Ventura 13.3.1`
OS architecture (e.g. amd64):
`2,6 GHz Intel Core i7 6 core`
pyenv version:
`pyenv 2.3.17`
Python version:
`Python 3.6.0`
C Compiler information (e.g. gcc 7.3): 
`Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

Hi everyone, I need to install Python 3.6.0 on my Macbook, in order to use PythonROV2 (https://github.com/sybrenstuvel/Python-RVO2) . When I try to install i get this error:

```bash
By default, distutils will build C++ extension modules with "clang++". If this is not intended, then set CXX on the configure command line.
```

Anyone could help ? I need to use that version in order to execute that library that is tested only for python 3.6.0

**Comment by native-api** [comment]
That is not an error. The real error is something else.

**Comment by native-api** [comment]
Oh. 3.6.0 doesn't support MacOS 11+.

3.6.15 has downstream patches for that, use it instead..
