### ISSUE TITLE
Consider to convert manpage into a more user-friendly format

### ISSUE THREAD

**Issue by tomschr** [pyenv/pyenv#2689]
### Idea
Currently, the man page is written in a troff/groff format. Would you be positive to the idea to convert from troff/groff to ASCIIDoc (ADoc), ReST, or Markdown (MD)?

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): openSUSE 15.4
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 2.3.17
- [x] Python version: 3.11.2
- [x] C Compiler information (e.g. gcc 7.3): 7.5.0

I see the following benefits to use one the mentioned formats:

* Easier to link. The ADoc/ReST/MD document can be directly called and it is rendered by GitHub and presented in a nice output.
* Easier to contribute as you don't have to know the troff/groff syntax.
* Possibly people are more familiar with ADoc/ReST/MD than troff/groff and are more likely to contribute.
* More readable. This is maybe a bit subjective, but most people got more in contact with MD through GitHub than with troff/groff.

A possible downside:

* You need another step in your build process to generate the manpage output from ADoc/ReST/MD.

Before I dedicate time and effort, I'd like to know if this is applicable to your project or it's a good idea or not. :slightly_smiling_face: 

### Possible tools

There are many ways to write a manpage, but I focus on the three most popular formats:

* ASCIIDoc: use [ASCIIDoctor](https://docs.asciidoctor.org/asciidoctor/latest/manpage-backend/)
* ReST: use [Sphinx](https://www.sphinx-doc.org)
* Markdown: use [md2man](https://github.com/sunaku/md2man), [pandoc](https://pandoc.org/)

It depends on what you prefer and how you want it to integrate into your existing workflow.

**Comment by native-api** [comment]
Pyenv supports installation by just cloning this repo. So not sure where to insert the conversion step -- plus, the user will also need to install the necessary tool.

**Comment by native-api** [comment]
Perhaps a more useful approach would be to code a way to compile the manpage from existing reference documentation -- which is already in ReST.

**Comment by native-api** [comment]
> Perhaps a more useful approach would be to code a way to compile the manpage from existing reference documentation -- which is already in ReST.

This is essentially your suggestion, just on a higher scale.

The conversion procedure can be placed into a makefile -- either the core one or in the `man` subirectory.

**Comment by tomschr** [comment]
> This is essentially your suggestion, just on a higher scale.
> 
> The conversion procedure can be placed into a makefile -- either the core one or in the `man` subirectory.

As Sphinx supports manpages, it's actually even simpler: you delegate it to the Sphinx' Makefile. I can try it (although you have to wait a bit as I'll be on vacation tomorrow). :wink:
