### ISSUE TITLE
Improvements for the suggested build environment on openSUSE

### ISSUE THREAD

**Issue by tucked** [pyenv/pyenv#2694]
The [Suggested build environment](https://github.com/pyenv/pyenv/wiki/Home/ebb2183a6ef1ed1b84c3027d78df64481b1dd320#suggested-build-environment) for openSUSE currently lists `libgdbm-devel`:
``` sh
zypper install gcc automake bzip2 libbz2-devel xz xz-devel openssl-devel ncurses-devel \
readline-devel zlib-devel tk-devel libffi-devel sqlite3-devel libgdbm-devel make findutils
```
However, that does not appear to exist (at least on LEAP 15.4):
``` console
'libgdbm-devel' not found in package names. Trying capabilities.
No provider of 'libgdbm-devel' found.  
```
I didn't hit any errors installing 3.11.0 without it, but [`gdbm-devel` exists](https://opensuse.pkgs.org/15.4/opensuse-oss-x86_64/gdbm-devel-1.12-1.418.x86_64.rpm.html).
Perhaps that's what the wiki should recommend instead.

**Comment by tucked** [comment]
`patch` is also needed:
``` console
WARNING: Please make sure you remove any previous custom paths from your /home/tucked/.pydistutils.cfg file.
Downloading Python-3.7.13.tar.xz...
-> https://www.python.org/ftp/python/3.7.13/Python-3.7.13.tar.xz
Installing Python-3.7.13...
/home/tucked/.pyenv/plugins/python-build/bin/python-build: line 1745: patch: command not found

BUILD FAILED (openSUSE 15.4 using python-build 2.3.17-9-g528d10e9)

Inspect or clean up the working tree at /tmp/python-build.20230504001326.27741
Results logged to /tmp/python-build.20230504001326.27741.log

Last 10 log lines:
/tmp/python-build.20230504001326.27741 /tmp/tmp.VlctNWi6f8
/tmp/python-build.20230504001326.27741/Python-3.7.13 /tmp/python-build.20230504001326.27741 /tmp/tmp.VlctNWi6f8
```

**Comment by native-api** [comment]
`gdbm-devel` is probably needed for the `dbm` extension.

We don't work with SUSE so we don't know its package names.
You can fix the list yourself in the wiki or post it here.

**Comment by native-api** [comment]
Checked package names with docker.

Updated.
