### ISSUE TITLE
All 3.10.x installations use system's libpython v 3.10.6 instead of their own

### ISSUE THREAD

**Issue by LSanselme** [pyenv/pyenv#2698]
Hello,

Thank you for this great tool :slightly_smiling_face: 

I have trouble installing _all_ python versions 3.10.X, except for 3.10.6. It happens to be precisely the version of the system in `/usr/bin/python3.10`.
Notice that I do not have this problem for the 3.9 versions. 

* I'm using Ubuntu 22.04.2 LTS x86_64, `gcc` is in version 11.3.0
* I have a clean pyenv installation, no extra plugins, obtained with 
```
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
cd ~/.pyenv && src/configure && make -C src
```
as specified in the documentation.
* My .zshrc contains the following lines at the end:
```
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```
no other dotfiles have anything pyenv-related as far as I can tell.
* I install _eg_ 3.8.10 using `pyenv install 3.10.8 --force`

* Then if I execute directly `~/.pyenv/versions/3.10.8/bin/python3.10 --version`, the result is `Python 3.10.6`. This is the same result for all other 3.1 versions.

~Please find in these gists the [debug trace](https://gist.github.com/LSanselme/84c9f2f8b5c8e1c534b02e1f979d566a), and the [config.log](https://gist.github.com/LSanselme/d973989619d2a0594588be289de6f522).~

[edit: [config.log](https://gist.github.com/LSanselme/df5314619e07ce37393aca2f33741ec2) and [trace.log](https://gist.github.com/LSanselme/16e416df9794ddede5f5299004e56f6d) for  commit [920ef14](https://github.com/pyenv/pyenv/commit/920ef1456ad6728a42677e093686f3a05aa70047)]

I used `git bisect` to see if I could have a working version for an older commit: it appears to be the case the commit [b3d52b05](https://github.com/pyenv/pyenv/commit/b3d52b05) is the first one for which I do have this problem, its parent [73dc554](https://github.com/pyenv/pyenv/commit/73dc5547fce4a12b77a54b4661cea7de3489baab) is working just fine...

Thanks in advance for your help :slightly_smiling_face:

**Comment by native-api** [comment]
The trace log provided is from an old version, the code related to the handling of `--enable-shared` is different.
Please upgrade to the latest head.

**Comment by native-api** [comment]
We did have some bugs related to `--enable-shared` when if was first made the default, but they have been fixed since. So a simple bisect may be unreliable. Please provide the trace for the latest head so we can see what is happening in the code *now.*

**Comment by LSanselme** [comment]
You can find [here](https://gist.github.com/LSanselme/16e416df9794ddede5f5299004e56f6d) the trace for the current master (commit [920ef14](https://github.com/pyenv/pyenv/commit/920ef1456ad6728a42677e093686f3a05aa70047)).

**Comment by native-api** [comment]
Comparing your logi with a log of a successful build, I see the following related anomaly:

> LD_LIBRARY_PATH=/home/lsanselme/.pyenv/sources/3.10.8/Python-3.10.8:/usr/lib/x86_64-linux-gnu: ./python -E -S -m sysconfig --generate-posix-vars ;\
> <...>
> LD_LIBRARY_PATH=/home/lsanselme/.pyenv/sources/3.10.8/Python-3.10.8:/usr/lib/x86_64-linux-gnu: CC='gcc' LDSHARED='gcc -shared -L/home/lsanselme/.pyenv/versions/3.10.8/lib -Wl,-rpath,/home/lsanselme/.pyenv/versions/3.10.8/lib -L/home/lsanselme/.pyenv/versions/3.10.8/lib -Wl,-rpath,/home/lsanselme/.pyenv/versions/3.10.8/lib  ' OPT='-DNDEBUG -g -fwrapv -O3 -Wall' 	_TCLTK_INCLUDES='-I/usr/include/tcl8.6' _TCLTK_LIBS='-ltk8.6 -ltkstub8.6 -ltcl8.6 -ltclstub8.6' 	./python -E ./setup.py  build
> <etc>

Looking at [3.10.8's `configure.ac`](https://github.com/python/cpython/blob/v3.10.8/configure.ac) on where this path comes from, it looks like you have envvars set that affect the dynamic linker, in particular, `LD_LIBRARY_PATH`. `/usr/lib/x86_64-linux-gnu` in it is what must be overriding rpath to `libpython` in the `python` executable that Pyenv sets.

For some reason, you also have `/usr/lib/x86_64-linux-gnu` in your `PATH`. While it's not likely to be directly causing this problem, it generally has no business being on `PATH` because it contains no executables.

**Comment by LSanselme** [comment]
Thanks, removing `/usr/lib/x86_64-linux-gnu` from `LD_LIBRARY_PATH` (and from my `PATH` as well) solved it!

I may not be the only one with this problem, as I found this message from a month ago in the [gitter chat](https://app.gitter.im/#/room/#yyuu_pyenv:gitter.im/$tDgSsedS_TDkdzw4CuvjZW2Z8aAkHnhKOO2KechbfTE):
> since the Python 3.10.10 upgrade on Manjaro [pyenv] just stopped working
> [...]
> looks like `pyenv install 3.10.7` installs 3.10.10

The root cause may not be the same though.
