### ISSUE TITLE
[Feature Request] Support Gentoo Prefix

### ISSUE THREAD

**Issue by NyaMisty** [pyenv/pyenv#2702]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Gentoo Prefix stable branch
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 2.3.17-11-gb5576240
- [x] Python version: 3.11.3
- [x] C Compiler information (e.g. gcc 7.3): 12.2.1 20230428 (Gentoo 12.2.1_p20230428-r1 p2)

With default parameters, building python under Gentoo Prefix would fail to get _ctypes, readline, _ncurses working correctly.

I've manually managed to build python with this patch, I'm wondering if we should support this or made it into a wiki entry?

`pyenv install -k -p -v <gentoo_helper.patch`
```
*** setup_ori.py        2023-05-24 09:42:14.016611640 +0000
--- setup.py    2023-05-24 10:24:28.103061378 +0000
*************** class PyBuildExt(build_ext):
*** 875,877 ****
          # be assumed that no additional -I,-L directives are needed.
!         if not CROSS_COMPILING:
              self.lib_dirs = self.compiler.library_dirs + system_lib_dirs
--- 875,893 ----
          # be assumed that no additional -I,-L directives are needed.
!         if 'GENTOO_PREFIX' in os.environ:
!             sysroot = os.environ['GENTOO_PREFIX']
!             def sysroot_paths(_, subdirs):
!                 dirs = []
!                 for subdir in subdirs:
!                     if os.path.isabs(subdir):
!                         subdir = subdir[1:]
!                     path = os.path.join(sysroot, subdir)
!                     if os.path.isdir(path):
!                         dirs.append(path)
!                 return dirs
!             self.lib_dirs = (self.compiler.library_dirs +
!                              sysroot_paths(('LDFLAGS', 'CC'), system_lib_dirs))
!             self.inc_dirs = (self.compiler.include_dirs +
!                              sysroot_paths(('CPPFLAGS', 'CFLAGS', 'CC'),
!                                            system_include_dirs))
!         elif not CROSS_COMPILING:
              self.lib_dirs = self.compiler.library_dirs + system_lib_dirs
*************** class PyBuildExt(build_ext):
*** 1075,1076 ****
--- 1091,1093 ----
              do_readline = False
+         #import pdb;pdb.set_trace()
          # Issue 7384: If readline is already linked against curses,
*************** class PyBuildExt(build_ext):
*** 1127,1128 ****
--- 1144,1147 ----
              if not CROSS_COMPILING:
+                 if 'GENTOO_PREFIX' in os.environ:
+                     curses_includes.append(os.environ['GENTOO_PREFIX'] + '/usr/include/ncursesw')
                  curses_includes.append('/usr/include/ncursesw')
*************** class PyBuildExt(build_ext):
*** 1449,1450 ****
--- 1468,1470 ----
          if ffi_lib is None and ffi_inc:
+             #import pdb; pdb.set_trace()
              for lib_name in ('ffi', 'ffi_pic'):
```

**Comment by NyaMisty** [comment]
And here is patch for Python 2.7.18

```
$ cat /tmp/pyenv-misty/plugins/python-build/share/python-build/patches/2.7.18/Python-2.7.18/9999-gentoo_helper.patch
*** a/setup.py  2023-05-24 11:04:06.278481556 +0000
--- b/setup.py  2023-05-24 11:09:46.420687066 +0000
*************** def add_dir_to_list(dirlist, dir):
*** 44,49 ****
--- 44,53 ----
              # If in a macOS SDK path, check relative to the SDK root
              dir_exists = os.path.isdir(
                  os.path.join(macosx_sdk_root(), dir[1:]))
+         elif 'GENTOO_PREFIX' in os.environ:
+             if dir.startswith('/usr'):
+                 dir = os.environ['GENTOO_PREFIX'] + dir
+             dir_exists = os.path.isdir(dir)
          else:
              dir_exists = os.path.isdir(dir)
          if dir_exists:
```

**Comment by NyaMisty** [comment]
I've integrated these patches into my branch for show cases purpose.
And I've tested them on Gentoo Prefix stable branch today.

**Comment by native-api** [comment]
As long as the environment is not too niche, this is okay as per https://github.com/pyenv/pyenv/blob/master/CONTRIBUTING.md#adding-version-specific-fixespatches .

You will need to provide a patch for each release that you want to support this.

Do heed the requirements for user-provided patches though.

E.g. I see a possible breakage already:

> +         elif 'GENTOO_PREFIX' in os.environ:
> +             if dir.startswith('/usr'):
> +                 dir = os.environ['GENTOO_PREFIX'] + dir
> +             dir_exists = os.path.isdir(dir)

What happens if you invoke a Python installed in the host ecosystem (which will also have this patch since we're adding it unconditionally) from a program installed in the Gentoo Prefix ecosystem?

**Comment by native-api** [comment]
It seems to me that to compile Python for the Gentoo Prefix ecosystem, we rather need to pass some path arguments to CPython's configure so that it compiles Python to look for the libs in the right places.
