### ISSUE TITLE
Problem when installing Python on m1 processor

### ISSUE THREAD

**Issue by pomponchik** [pyenv/pyenv#2705]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS Ventura 13.4 (22F66)
- [x] OS architecture (e.g. amd64): arm
- [x] pyenv version: 2.3.18
- [x] Python version: installed Python 3.9.2, the problem when installing 3.10 by pyenv
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- [x] Please attach the debug trace of the failing command as a gist: https://gist.github.com/pomponchik/bb51526c9a800b220a82d2658fd92271
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory: https://gist.github.com/pomponchik/a2b408db83cf29a78bef4ff1c7c212e7

Hi! I have a problem trying to install Python 3.10 via Pyenv. Here is the output I get in the console after executing the "pyenv install 3.10" command:

```
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.10.11.tar.xz...
-> https://www.python.org/ftp/python/3.10.11/Python-3.10.11.tar.xz
Installing Python-3.10.11...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 13.4 using python-build 2.3.18)

Inspect or clean up the working tree at /var/folders/53/0pvqn17x23z2vyy_9yzm6zgh0000gn/T/python-build.20230529153542.63284
Results logged to /var/folders/53/0pvqn17x23z2vyy_9yzm6zgh0000gn/T/python-build.20230529153542.63284.log

Last 10 log lines:
  File "/private/var/folders/53/0pvqn17x23z2vyy_9yzm6zgh0000gn/T/python-build.20230529153542.63284/Python-3.10.11/Lib/ensurepip/__init__.py", line 287, in _main
    return _bootstrap(
  File "/private/var/folders/53/0pvqn17x23z2vyy_9yzm6zgh0000gn/T/python-build.20230529153542.63284/Python-3.10.11/Lib/ensurepip/__init__.py", line 203, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
  File "/private/var/folders/53/0pvqn17x23z2vyy_9yzm6zgh0000gn/T/python-build.20230529153542.63284/Python-3.10.11/Lib/ensurepip/__init__.py", line 104, in _run_pip
    return subprocess.run(cmd, check=True).returncode
  File "/private/var/folders/53/0pvqn17x23z2vyy_9yzm6zgh0000gn/T/python-build.20230529153542.63284/Python-3.10.11/Lib/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/private/var/folders/53/0pvqn17x23z2vyy_9yzm6zgh0000gn/T/python-build.20230529153542.63284/Python-3.10.11/python.exe', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/var/folders/53/0pvqn17x23z2vyy_9yzm6zgh0000gn/T/tmp9ixthyl6/setuptools-65.5.0-py3-none-any.whl\', \'/var/folders/53/0pvqn17x23z2vyy_9yzm6zgh0000gn/T/tmp9ixthyl6/pip-23.0.1-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/var/folders/53/0pvqn17x23z2vyy_9yzm6zgh0000gn/T/tmp9ixthyl6\', \'--root\', \'/\', \'--upgrade\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' died with <Signals.SIGABRT: 6>.
make: *** [install] Error 1
```

**Comment by native-api** [comment]
You're building for ARM64 but using AMD64 Homebrew.

```
+++(/Users/pomponchik/.pyenv/plugins/python-build/bin/python-build:1502): use_homebrew_openssl(): brew --prefix openssl@1.1
++(/Users/pomponchik/.pyenv/plugins/python-build/bin/python-build:1502): use_homebrew_openssl(): local ssldir=/usr/local/opt/openssl@1.1
<...>
checking build system type... aarch64-apple-darwin22.5.0
checking host system type... aarch64-apple-darwin22.5.0
```

**Comment by klueless-io** [comment]
> Users

This is a does tell anyone how to resolve the issue.

**Comment by wesyoung** [comment]
see my response in #2707 (uninstall, re-install homebrew, pyenv seems to resolve it, esp if you mac-transfered your setup from an x86 setup to an M1/2)

**Comment by bowen-upenn** [comment]
Use brew config to make sure that your `macOS` looks something like `14.4.1-arm64` rather than `14.4.1-x86_64`. The latter may happen if you are running a terminal session under a Rosetta 2 emulation, even if you have a Mac with the Apple Silicon. If so, start a terminal session explicitly with the ARM architecture using `arch -arm64 /usr/bin/env zsh`.
