### ISSUE TITLE
Not able to install Pyenv 3.7.6 in M1 Pro macOS Ventura 13.4

### ISSUE THREAD

**Issue by sadhishkumarthiagarajan-srijan** [pyenv/pyenv#2709]
$pyenv install 3.7.9
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.6.tar.xz...
-> https://www.python.org/ftp/python/3.7.6/Python-3.7.6.tar.xz
Installing Python-3.7.6...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 13.4 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/jp/dxj8h811427dchvp0kg91_000000gq/T/python-build.20230603145935.80026
Results logged to /var/folders/jp/dxj8h811427dchvp0kg91_000000gq/T/python-build.20230603145935.80026.log

Last 10 log lines:
checking for --with-cxx-main=<compiler>... no
checking for clang++... no
configure:

  By default, distutils will build C++ extension modules with "clang++".
  If this is not intended, then set CXX on the configure command line.
  
checking for the platform triplet based on compiler characteristics... darwin
configure: error: internal configure error for the platform triplet, please file a bug report
make: *** No targets specified and no makefile found.  Stop.
**Xcode Version:**
Xcode 13.4.1
Build version 13F100
**Using MacOS Ventura 13.4 (M1 chip)**

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv#python-versions-with-extended-support

3.7.6 is incompatible with XCode 13.3+.
Use the latest micro release.

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/wiki/Common-build-problems#configure-error-internal-configure-error-for-the-platform-triplet-please-file-a-bug-report-in-macos
