### ISSUE TITLE
Installing Python 3.5.10 on Manjaro Linux - UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 4210: invalid start byte make

### ISSUE THREAD

**Issue by ddmin** [pyenv/pyenv#2716]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): 6.3.5-2-MANJARO
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: pyenv 2.3.19
- [x] Python version: Python 3.11.3
- [x] C Compiler information (e.g. gcc 7.3): gcc (GCC) 13.1.1 20230429
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

*Command Run*: env PYENV_DEBUG=1 pyenv install -v 3.5.10 2>&1 | tee trace.log
[trace.log](https://github.com/pyenv/pyenv/files/11710599/trace.log)

- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory

[config.log](https://github.com/pyenv/pyenv/files/11710527/config.log)

**Comment by native-api** [comment]
This is https://bugs.python.org/issue42351 , fixed in 3.8.x
