### ISSUE TITLE
Not able to install pyenv 3.7.6 on M1 mac pro

### ISSUE THREAD

**Issue by sadhishkumarthiagarajan-srijan** [pyenv/pyenv#2721]
python-build: use openssl from homebrew
python-build: use readline from homebrew
/var/folders/p5/10sh21t12qj3yqb16jy_y9q00000gq/T/python-build.20230613141952.10010 ~/Desktop
Downloading Python-3.7.6.tar.xz...
-> https://www.python.org/ftp/python/3.7.6/Python-3.7.6.tar.xz
/var/folders/p5/10sh21t12qj3yqb16jy_y9q00000gq/T/python-build.20230613141952.10010/Python-3.7.6 /var/folders/p5/10sh21t12qj3yqb16jy_y9q00000gq/T/python-build.20230613141952.10010 ~/Desktop
Installing Python-3.7.6...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
checking build system type... arm-apple-darwin21.6.0
checking host system type... arm-apple-darwin21.6.0
checking for python3.7... no
checking for python3... python3
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... checking for --without-gcc... no
checking for --with-icc... no
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for a sed that does not truncate output... /usr/bin/sed
checking for --with-cxx-main=<compiler>... no
checking for clang++... no
configure:

  By default, distutils will build C++ extension modules with "clang++".
  If this is not intended, then set CXX on the configure command line.
  
checking for the platform triplet based on compiler characteristics... darwin
configure: error: internal configure error for the platform triplet, please file a bug report
make: *** No targets specified and no makefile found.  Stop.

BUILD FAILED (OS X 12.6.6 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/p5/10sh21t12qj3yqb16jy_y9q00000gq/T/python-build.20230613141952.10010
Results logged to /var/folders/p5/10sh21t12qj3yqb16jy_y9q00000gq/T/python-build.20230613141952.10010.log

Last 10 log lines:
checking for --with-cxx-main=<compiler>... no
checking for clang++... no
configure:

  By default, distutils will build C++ extension modules with "clang++".
  If this is not intended, then set CXX on the configure command line.
  
checking for the platform triplet based on compiler characteristics... darwin
configure: error: internal configure error for the platform triplet, please file a bug report
make: *** No targets specified and no makefile found.  Stop.

***SYSTEM INFO***
APPLE M1 pro macOS Monterey

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv#python-versions-with-extended-support

**Comment by native-api** [comment]
@nbro10  Is there any problem with using the last micro release (3.7.17 as of this writing in your case)? Micro releases are supposed to be compatible with each other.

Old releases may not work in newer environments, that shouldn't come as a surprise, not to say considered a problem of Pyenv.

Maybe the above advise should be included into that section -- if it actually works in practice.
