### ISSUE TITLE
pyenv affecting my python environment even it was not activated

### ISSUE THREAD

**Issue by xiebruce** [pyenv/pyenv#2728]
my OS: `macOS Big Sur 11.5.1 (20G80)`  
cpu Arch: `Intel cpu, amd64`  
pyenv: `2.3.20`  
Python version: 3.11.4  
c compiler info:
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I install `pyenv` and `pyenv-virtualenv` using `brew`
```py
brew install pyenv
brew install pyenv-virtualenv
```

I'm using fish-shell, so after installing, I put `pyenv init - | source` in to `~/.config/fish/config.fish` and source it, I didn't change `PYENV_ROOT`, so `PYENV_ROOT` defaults to `$HOME/.pyenv`.

Then I try the following operations
```bash
# create virtual environment
pyenv virtualenv 3.8 jarvis

# enter virtual environment
pyenv activate jarvis

# deactivate virtual environment
pyenv deactivate
```

for now, everything seems works fine
[![active pyenv][1]][1]

---

But there is a problem: if I check the `python3`/`pip3`'s location, they are all in `/Users/bruce/.pyenv/shims/` even if I didn't activate the virtual environment, which is not right. 
Even more wierder is that the `pip3 --vesion` shows it was in `/usr/local/lib/`. so here's a problem: `which pip3` says is was in `/Users/bruce/.pyenv/shims/` but `pip3 --version` says it was it `/usr/local/lib/`, which is the real location? if I try to install some packages via `pip3 install xxx`, it was installed to `/usr/local/lib/python3.11/site-packages/`

[![enter image description here][2]][2]

what I expect is that the pyenv python env should act as if it was not exists unless I activate it. it should not affect the existing python on my system.

another solution that I can accpet is: python and pip are all in `~/.pyenv/` even if I didn't activate it, acting just like I've activated the virtual env
<img width="772" alt="image" src="https://github.com/pyenv/pyenv/assets/13575500/09fe7696-bbd8-4ebb-8efa-5a5d45a4081f">

so, is this a bug or it's normal?

  [1]: https://i.stack.imgur.com/0f99j.png
  [2]: https://i.stack.imgur.com/j8uEh.png

**Comment by native-api** [comment]
> But there is a problem: if I check the `python3`/`pip3`'s location, they are all in `/Users/bruce/.pyenv/shims/` even if I didn't activate the virtual environment, which is not right.

That's how it's supposed to be, see https://github.com/pyenv/pyenv#understanding-shims
