### ISSUE TITLE
Failed to install micropython-1.19.1 on mac os M1

### ISSUE THREAD

**Issue by WendelHime** [pyenv/pyenv#2731]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): OS X 13.4 using python-build 20180424
- [X] OS architecture (e.g. amd64): arm64 (M1)
- [X] pyenv version: 2.3.20
- [X] Python version: 3.9.6
- [X] C Compiler information (e.g. gcc 7.3): Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- [X] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [ ] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

[trace.log](https://gist.github.com/WendelHime/37aae0bb5dda88d51f66bc13f118eb0e)

**Comment by native-api** [comment]
WFM in MacOS 12 x64.

Looks like an issue with a dependency, BerkeleyDB . 

Maybe it doesn't support ARM64 architecture?

**Comment by native-api** [comment]
Looking at the relevant source code, **this is an upstream issue.**

In the affected `lib/berkeley-db-1.xx/btree/bt_close.c` file, functions are defined in an obsolete way:

```
int
__bt_sync(dbp, flags)
  const DB *dbp;
  u_int flags;
{
```

Looks like eith Micropython's builf makes this an error via `-Werror` in your specific environment, or (more likely) CLang 14 has advanced to the C2x standard by default, and started making this an error instead of a warning.
