### ISSUE TITLE
Build failed 3.6.9 with Ubuntu 22.02.2 LTS

### ISSUE THREAD

**Issue by khorsmann** [pyenv/pyenv#2736]
Hi,
Thank you for your great project!

I dunno why but i cannot build python 3.6.9 anymore.
Also try to upgrade pyenv. Remove my python 3.6.9 and tried to recompile.
Description below. 

```shell

Downloading Python-3.6.9.tar.xz...
-> https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tar.xz
Installing Python-3.6.9...

BUILD FAILED (Ubuntu 22.04 using python-build 2.3.21-2-ga2dff480)

Inspect or clean up the working tree at /home/khorsmann/src/python-build.20230626204455.71511
Results logged to /home/khorsmann/src/python-build.20230626204455.71511.log

Last 10 log lines:
if test "xupgrade" != "xno"  ; then \
        case upgrade in \
                upgrade) ensurepip="--upgrade" ;; \
                install|*) ensurepip="" ;; \
        esac; \
        LD_LIBRARY_PATH=/home/khorsmann/src/python-build.20230626204455.71511/Python-3.6.9 ./python -E -m ensurepip \
                $ensurepip --root=/ ; \
fi
Segmentation fault (core dumped)
make: *** [Makefile:1102: install] Error 139
```

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04):
   *Ubuntu 22.04.2 LTS*
- [x] OS architecture (e.g. amd64):
  *amd64*
- [x] pyenv version:
  *pyenv 2.3.21-2-ga2dff480*
- [x] Python version:
  *3.6.9*
- [x] C Compiler information (e.g. gcc 7.3): 
  *gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0*
- [x] Please attach the debug trace of the failing command as a gist:
  * have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.

https://gist.github.com/khorsmann/c239d7e62c77da4a126f449b9bd970d9 config.log
https://gist.github.com/khorsmann/ceacd14e7ca44abab2a9e1496925e957 trace.log

**Comment by native-api** [comment]
> WARNING++(/home/khorsmann/.pyenv/plugins/python-build/bin/python-build:1808): try_python_module(): echo ': The Python ctypes extension was not compiled. Missing the libffi lib?'
> : The Python ctypes extension was not compiled. Missing the libffi lib?

Looks like you don't have all the prerequisites installed.

**Comment by native-api** [comment]
> 

Oh, sorry, that's due to a core dump. I didn't understand that because the message was in German.

> /home/khorsmann/.pyenv/plugins/python-build/bin/python-build: Zeile 1805: 132423 Speicherzugriffsfehler  (Speicherabzug geschrieben) "$PYTHON_BIN" -c "import $1"

**Comment by native-api** [comment]
You can [enable core dumping in Ubuntu](https://askubuntu.com/questions/966407/where-do-i-find-the-core-dump-in-ubuntu-16-04lts), rerun the faulty build and analyze the dump with `gdb`.

Or pack the build directory together with the dump file and upload it somewhere, maybe we'll be able to do that (not sure how fully one can analyze a core dump on a different system).

**Comment by native-api** [comment]
As a workaround, is using 3.6.15 instead of 3.6.9 an option? Micro releases are supposed to be compatible.

**Comment by khorsmann** [comment]
Hi there,

works with 3.6.15 - only the gcc gods will know why its segfaults. Sorry for the german language - forgot to set LANG=C in before run the traces.

Works for me. Thanks for the hint.
