### ISSUE TITLE
CPython 3.12-dev fails to build if openssl@1.1 is Homebrew-installed

### ISSUE THREAD

**Issue by brechtm** [pyenv/pyenv#2746]
Recording this here for anyone else running into this problem.

With both openssl@1.1 and openssl@3 installed with Homebrew, `pyenv install 3.12-dev` will choose openssl@1.1 and fail with 
```
[ERROR] _hashlib failed to import: dlopen(/private/var/folders/t3/n6h1s2ss58n5l5llnt6c4zbh0000gn/T/python-build.20230725102939.1328/Python-3.12-dev/build/lib.macosx-13.4-arm64-3.12/_hashlib.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_EVP_MD_block_size'
[ERROR] _ssl failed to import: dlopen(/private/var/folders/t3/n6h1s2ss58n5l5llnt6c4zbh0000gn/T/python-build.20230725102939.1328/Python-3.12-dev/build/lib.macosx-13.4-arm64-3.12/_ssl.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_SSL_get_peer_certificate'
```

Uninstalling openssl@1.1 temporarily will make the CPython build pick up openssl@3 instead and complete succesfully. I reinstalled openssl@1.1 afterwards since it is needed by older CPython versions.

This is on macOS Ventura 13.4.1 (c) on M1 with ARM64 Homebrew.

**Comment by native-api** [comment]
Please add full diagnostic information as per the issue template.

**Comment by native-api** [comment]
Also please specify the version and architecture of the OpenSSL package.

**Comment by native-api** [comment]
WFM with openssl@1.1 1.1.1u x64.

**Comment by bebleo** [comment]
I can report that I have the same issue with 3.12.0b4 after installing openssl with homebrew on macOS 13.5

```sh
openssl version
```

results in:

```sh
OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)
```

And

```sh
which openssl
```

Gives:

```sh
/opt/homebrew/bin/openssl
```

[pyenv_install.3.12.0b4.verbose.error.txt](https://github.com/pyenv/pyenv/files/12209963/pyenv_install.3.12.0b4.verbose.error.txt)
[pyenv_install.3.12.0b4.error.txt](https://github.com/pyenv/pyenv/files/12209964/pyenv_install.3.12.0b4.error.txt)

**Comment by native-api** [comment]
@anton-petrov @joshfriend This looks like an ARM64-specific problem. Looks like a specific build of OpenSSL lacks some functions.

**Comment by ok2** [comment]
I have fixed it for me here: https://github.com/pyenv/pyenv/compare/master...ok2:pyenv:py312-ssl312

**Comment by gstos** [comment]
Similar context as @bebleo: trying to install 3.12.0b4 on a M1 Mac (ARM, macOS 13.14.1c, pyenv 2.3.23) with Homebrew installed.  I have both OpenSSL 3.1 and OpenSSL1.1 installed. Exact same failures.  

Also tried changing OpenSSL via env variables as below based on other issues, but pyenv continues to use Homebrew's OpenSSL1. Was this behavior expected or am I doing something wrong?

`PYTHON_CONFIGURE_OPTS="--with-openssl=/opt/Homebrew/Cellar/openssl@3/3.1.2/" pyenv install 3.12.0b4`

**Comment by native-api** [comment]
```

> [ERROR] _hashlib failed to import: dlopen(/private/var/folders/7h/43wvctz56jz13pw620g5vtpm0000gn/T/python-build.20230730145818.43199/Python-3.12.0b4/build/lib.macosx-13.5-arm64-3.12/_hashlib.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_EVP_MD_block_size'
> [ERROR] _ssl failed to import: dlopen(/private/var/folders/7h/43wvctz56jz13pw620g5vtpm0000gn/T/python-build.20230730145818.43199/Python-3.12.0b4/build/lib.macosx-13.5-arm64-3.12/_ssl.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_SSL_get_peer_certificate'
```

Looks like a specific Homebrew build of OpenSSL 1.1 lacks some exported functions that Python expects.

I don't have Apple Silicon so I can't check that.

**Comment by native-api** [comment]
> Looks like a specific Homebrew build of OpenSSL 1.1 lacks some exported functions that Python expects.

Apart from the [workaround by @ok2](https://github.com/pyenv/pyenv/issues/2746#issuecomment-1666502128),

you can also set an envvar `PYTHON_BUILD_HOMEBREW_OPENSSL_FORMULA` to the Homebrew formula to use in the build -- e.g. `openssl` or `openssl@3`:

```bash
export PYTHON_BUILD_HOMEBREW_OPENSSL_FORMULA=openssl
```

**Comment by gstos** [comment]
> Similar context as @bebleo: trying to install 3.12.0b4 on a M1 Mac (ARM, macOS 13.14.1c, pyenv 2.3.23) with Homebrew installed. I have both OpenSSL 3.1 and OpenSSL1.1 installed. Exact same failures.
> 
> Also tried changing OpenSSL via env variables as below based on other issues, but pyenv continues to use Homebrew's OpenSSL1. Was this behavior expected or am I doing something wrong?
> 
> `PYTHON_CONFIGURE_OPTS="--with-openssl=/opt/Homebrew/Cellar/openssl@3/3.1.2/" pyenv install 3.12.0b4`
> 
> ```
> python-build: use openssl@1.1 from homebrew
> python-build: use readline from homebrew
> Downloading Python-3.12.0b4.tar.xz...
> ```

This worked after changing to

> Similar context as @bebleo: trying to install 3.12.0b4 on a M1 Mac (ARM, macOS 13.14.1c, pyenv 2.3.23) with Homebrew installed. I have both OpenSSL 3.1 and OpenSSL1.1 installed. Exact same failures.
> 
> Also tried changing OpenSSL via env variables as below based on other issues, but pyenv continues to use Homebrew's OpenSSL1. Was this behavior expected or am I doing something wrong?
> 
> `PYTHON_CONFIGURE_OPTS="--with-openssl=/opt/Homebrew/Cellar/openssl@3/3.1.2/" pyenv install 3.12.0b4`
> 
> ```
> python-build: use openssl@1.1 from homebrew
> python-build: use readline from homebrew
> Downloading Python-3.12.0b4.tar.xz...
> ```

Adding that I was able to install 3.12.0b4 using:
`CONFIGURE_OPTS="--with-openssl=/opt/Homebrew/Cellar/openssl@3/3.1.2" pyenv install 3.12.0b4`

Although python-build reports that it would be using openssl@1.1 from homebrew, it worked and installed using OpenSSL 3 as per below:

```
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 3.1.2 1 Aug 2023'
```

**Comment by basepi** [comment]
I'm still getting this failure against 3.12.0rc1 -- the `PYTHON_CONFIGURE_OPTS` workaround works, but should that be necessary, or is this considered a bug? Surprised that this is closed.

**Comment by native-api** [comment]
I think that we can move to OpenSSL 3 as the default since 3.12.

Despite a CPython dev having had told us that OpenSSL 3 support is still experimental, it's kinda-sorta official since they started testing against it in their CI several releases ago.

**Comment by basepi** [comment]
I agree -- but I can't uninstall OpenSSL 1.1 due to another package depending on it. In my opinion, pyenv should choose OpenSSL 3 even if 1.1 is available. Feels like a bug to me.
