### ISSUE TITLE
Update missing packages in documentation for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by felixhammerl** [pyenv/pyenv#2747]
### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 22.04 LTS
- [x] OS architecture (e.g. amd64): adm64
- [x] pyenv version: 2.3.23
- [x] Python version: 3.10

In order to avoid going through dozens of error messages on stackoverflow, could we list all of the packages required for the build in the documentation of the common build problems? All of the dependencies are in the Dockerfile, but it would be really cool to have the documentation point that out.

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv#install-python-build-dependencies -> https://github.com/pyenv/pyenv/wiki#suggested-build-environment ?

**Comment by felixhammerl** [comment]
oh gosh, i should rtfm. thank you.
