### ISSUE TITLE
Corporate env where SSL is intercepted

### ISSUE THREAD

**Issue by drummonds** [pyenv/pyenv#2750]
# Problem
In my corporate environment I am unable to download packages, so python build fails.  This can be go around by adding -k to curl commands (I nastily patched .pyenv in a couple of places).  This is not good practice but the alternative is pyenv not building.  Once patched I was able to build successively.

# Suggestion
Add a flag so that -k can be taken from pyenv to curl

**Comment by native-api** [comment]
I'd suggest to rather configure your machine so that standard Linux tools just work.

E.g. if your corporate gateway is intercepting SSL, it must be generating fake certificates for every site, signing it with its own certificate.

So you need to add that certificate to the local trusted root certification store (its exact location anfd format depends on the distro).

**Comment by native-api** [comment]
(Btw intercepting SSL means that your corporate IT service can see every password to every site that you log into from work (e.g. when you use Github to interact with us).)

**Comment by jamesbeegle** [comment]
I ran into this issue setting up Debian in WSL on my work machine. AFAIK there isn't a single global registry all applications read from on Linux, but here's a few big ones:

Get the issuing CA in .pem format and save it to /usr/local/share/ca-certificates/corporate-mitm.pem
* How? In Chrome-likes, click the lock icon in the URL bar, 'Connection is secure' > 'Certificate is valid' > Details tab, then click the top entry in the Certificate Hierarchy section and hit the Export button at the bottom. It defaults to a .crt extension but the contents are identical. Not sure if the extension really matters.

Once you have put that file in the ca-certificates folder mentioned above:
curl (and others?): `sudo update-ca-certificates`
git: `git config --global http.sslCAInfo /usr/local/share/ca-certificates/corporate-mitm.pem`
wget: put this in ~/.wgetrc: `ca_certificate=/usr/local/share/ca-certificates/corporate-mitm.pem`

This approach worked for me, and more importantly, doesn't completely disable all security checks for the software you are installing on your work machine - some forethought that your infosec team will appreciate if they have reason to come ask you questions.

**Comment by drummonds** [comment]
I am going to give that a try out.

**Comment by drummonds** [comment]
I am not quite there yet but this seems exactly the right direction.  In my env not all URLS use the corporate_mitm.pem so I needed to choose one that did.  Many thanks @jamesbeegle  for your help.

**Comment by jamesbeegle** [comment]
As mentioned above, if your environment has enough of a security presence that you're dealing with SSL interception, you probably also have security people to answer to if you go and fire off an automated build process that downloads and compiles executables for you with zero security verification on what you're downloading. Depending on your environment, you might be able to get away with this, but you probably shouldn't.

Try getting the certificate and installing it per the instructions in my post. Only use the above if you're desperate.
