### ISSUE TITLE
please add anaconda3-2023.07-2

### ISSUE THREAD

**Issue by georeth** [pyenv/pyenv#2753]
anaconda3-2023.07-2 has already been released. please add it to available versions.

The linux x64 installer:
`https://repo.anaconda.com/archive/Anaconda3-2023.07-2-Linux-x86_64.sh`

**Comment by anton-petrov** [comment]
Done https://github.com/pyenv/pyenv/commit/db871427c7a232e18ee7a6dc0182989a646ccca9
