### ISSUE TITLE
Add M1 (Apple ARM) support to 2.7.18

### ISSUE THREAD

**Issue by lpapp-foundry** [pyenv/pyenv#2757]
It seems that pyenv cannot install 2.7.18 on Mac M1 (Apple ARM).

```
pyenv install 2.7.18          Downloading openssl-1.0.2q.tar.gz...
-> https://www.openssl.org/source/old/1.0.2/openssl-1.0.2q.tar.gz
Installing openssl-1.0.2q...

BUILD FAILED (OS X 13.5 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/9_/wjqg43y12bz8cnhlmmwh7rgc0000gq/T/python-build.20230816131951.19737
Results logged to /var/folders/9_/wjqg43y12bz8cnhlmmwh7rgc0000gq/T/python-build.20230816131951.19737.log

Last 10 log lines:
   _dgram_write in libcrypto.a(bss_dgram.o)
   _RAND_query_egd_bytes in libcrypto.a(rand_egd.o)
   ...
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [link_a.darwin] Error 1
make[3]: *** [do_darwin-shared] Error 2
make[2]: *** [libcrypto.1.0.0.dylib] Error 2
make[1]: *** [shared] Error 2
make: *** [build_crypto] Error 1
```

This is because the pyenv "recipe" for 2.7.18 fetches openssl 1.0.2 which did not have ARM support at the time. M1 support was added in 1.1.1i according to https://www.openssl.org/news/cl111.txt. 

If I replace https://github.com/pyenv/pyenv/blob/master/plugins/python-build/share/python-build/2.7.18#L2 with `install_package "openssl-1.1.1v" "https://www.openssl.org/source/openssl-1.1.1v.tar.gz" mac_openssl --if has_broken_mac_openssl`, it works fine. 

Would this change be accepted by you if it works also for Linux, etc? This could also potentially bring more security to 2.7.18, but happy to follow your lead on this.

Alternatively, the workaround to use rosetta if one is ok with not using native python.

Thank you in advance for your answer!

**Comment by native-api** [comment]
If 2.7.18 officially supports OpenSSL 1.1, we can replace 1.0 with 1.1 for all versions that do.

**Comment by lpapp-foundry** [comment]
Thanks.

Apologies, I have not noticed this issue before: https://github.com/pyenv/pyenv/issues/2136

You have a good point. I am not sure if 2.7.18 officially supports OpenSSL 1.1.1.

I can see this at least, but not sure if this is enough evidence. What do you think?

https://mail.python.org/pipermail/python-dev/2019-February/156333.html

Perhaps, the authoritative answer would be some changeling entry or so?

**Comment by SnoopJ** [comment]
> If 2.7.18 officially supports OpenSSL 1.1, we can replace 1.0 with 1.1 for all versions that do.

The [Python documentation](https://docs.python.org/2.7/library/ssl.html) lists support for linking to OpenSSL `1.1.0` from 2.7.13 onward:

> Changed in version 2.7.13: Updated to support linking with OpenSSL 1.1.0

I am not clear on what effect the distinction between 1.1.0 and 1.1.1 would have on this request.

**Comment by native-api** [comment]
> I can see this at least, but not sure if this is enough evidence. What do you think?
> 
> https://mail.python.org/pipermail/python-dev/2019-February/156333.html

LGTM. Looks like it's safe to put 1.1 into 2.7.16+ .
Please submit a PR; editing either just 2.7.18 or all three is fine.

**Comment by native-api** [comment]
To double-check compatibility, you can run OpenSSL-related tests in Python's test suite.

**Comment by lpapp-foundry** [comment]
Thanks, good idea!

I ran:

1. pyenv uninstall 2.7.18 (just to start clean)
2. pyenv install --keep 2.7.18
3. cd ~/.pyenv/sources/2.7.18/Python
4. make test

I am attaching the output. It seems that importing openssl worked. There are some connection resets by peer in certain threads, but they are not test failures.

[python-make-test.log](https://github.com/pyenv/pyenv/files/12367725/python-make-test.log)

Does this look OK or is there some issue in the log that we should understand further?

Thank you again for all the feedback on this.

**Comment by native-api** [comment]
> I am attaching the output. It seems that importing openssl worked. There are some connection resets by peer in certain threads, but they are not test failures.
> 
> [python-make-test.log](https://github.com/pyenv/pyenv/files/12367725/python-make-test.log)
> 
> Does this look OK or is there some issue in the log that we should understand further?

LGTM
