### ISSUE TITLE
Deploy `pyenv` builds: bundling `.so`s in `$PYENV_ROOT`?

### ISSUE THREAD

**Issue by ego-thales** [pyenv/pyenv#2762]
Hello

I have the following setup : 
- I have 2 computers, PC1 and PC2, with only PC1 connected to internet,
- I mounted PC1's `home/` on PC2,
- I build python versions using `pyenv` on PC1 and want to run them on PC2.

The problem I'm facing, is that python uses shared object files (`.so`) from the system, and PC2 might not have them available, making it impossible to even run the interpreter. I would like to know if it is possible to configure `pyenv` such that it "**embarks**" the required `.so` in `$PYENV_ROOT`, so that PC2 will always have them at disposal, even if I update them and rebuild python on PC1.

The weird thing is that I **don't** use the `--enable-shared` configure option when building, so I didn't think this would be an issue. Maybe it is because `pyenv` uses it by default and I need to turn it down? (if so, does anyone know how?)

If it is not possible, would this be a viable enhancement? I know next to nothing about shared libraries, so I don't know how credible it is since I said nothing about the *system compatibilities* between PC1 and PC2. In my case, I can at least guarantee that they run the same OS.

Thanks!
Élie

**Comment by ego-thales** [comment]
Sorry,

I just found out that `pyenv` uses `--enable-shared` by default, but [it can be disabled](https://github.com/pyenv/pyenv/issues/2580#issuecomment-1382567978):
```
PYTHON_CONFIGURE_OPTS=--disable-shared
```

**Comment by ego-thales** [comment]
I reopen because despite of using `--disable-shared`, my build isn't portable without some `.so`s:

```console
$ ldd ~/.pyenv/versions/3.11.4/bin/python3.11
	linux-vdso.so.1 =>  (0x00007ffd901d2000)
	libssl.so.1.1 => not found
	libcrypto.so.1.1 => not found
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe97a5e0000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fe97a3dc000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007fe97a1d9000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe979ed7000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe979b09000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe97a7fc000)
```

I even tried using `--enable-static` option, but it didn't make a difference.

**Comment by native-api** [comment]
Pyenv-installed versions are deliberately not self-contained -- to take advantage of the system-provided libs and all their specifics that may be present.

Is there are problem with adding the missing libs to the disconnected system as well?

**Comment by native-api** [comment]
libssl.so.1.1 and libcrypto.so.1.1 are parts of OpenSSL 1.1.1

**Comment by ego-thales** [comment]
Hello,

Thanks for your answer.

> Pyenv-installed versions are deliberately not self-contained -- to take advantage of the system-provided libs and all their specifics that may be present.
> 
> Is there a problem with adding the missing libs to the disconnected system as well?

In principle, there is no problem with that. However, PC2 is actually, in my case, a different PC2 for multiple users on a cluster. And since copying these files by hand seemed a bit like monkey patching the python builds, I'm a bit scared python might break somewhere else later on (another .so missing for some python module not yet indentified?), leading to numerous problems.

I also though about completely symlinking PC1's `/usr/lib64`and `/usr/include` on PC2, but I'm not sure this is a clean, let alone a working approach. Is it?

Another approach would be always synchronize libraries updates on PC1 and PC2 for openssl, and other required dependencies. But the small problem I face here, is that there is a *python build requirements* section on `pyen`docs, but no *python requirements* to go with it. So I'm not entirely sure of what exactly needs to be kept up-do-date. I already know openssl is part of that for example, but what else?


> libssl.so.1.1 and libcrypto.so.1.1 are parts of OpenSSL 1.1.1

Thank you. I already identified this indeed, and installed latest available openssl for my system on PC2, making it work for now 🙏.

Thanks again!
Élie

**Comment by native-api** [comment]
> And since copying these files by hand seemed a bit like monkey patching the python builds

Who says about copying? OpenSSL 1.1 is provided as a package by distros. If your two machines use the same architecture and distro (which they should if you're expecting stuff compiled for one to 'just work' on another), you should be able to just install the same OpenSSL package to the disconnected machine (e.g. from an installation CD or a `.dpkg` file).

The libs at the 2 machines do not have to be exactly the same version, they only need to be compatible; matching `.so` version suffices (`.1.1` in this case) are supposed to indicate compatibility.

**Comment by native-api** [comment]
> there is a _python build requirements_ section on `pyenv` docs, but no _python requirements_ to go with it

```
find "$(pyenv prefix 3.11)" -type f \( -name \*.so -o -name python?.* \) | xargs ldd
```

The runtime dependencies are the library packages corresponding to the development packages listed in the build dependencies and some preinstalled libraries like `libc` and `libm`.

**Comment by ego-thales** [comment]
Ok, thank you.

Regarding this:

> Pyenv-installed versions are deliberately not self-contained -- to take advantage of the system-provided libs and all their specifics that may be present.

Can you explain to me what `--disable-shared` does then please? Is there a difference with `--enable-static`? Because I specifically thought that these options would build self-contained pythons.

Thanks in advance.

**Comment by native-api** [comment]
> Can you explain to me what `--disable-shared` does then please?

It disables creating `libpython.so` -- it's instead linked statically into the Python executable.

You can see help for all CPython's Configure options by running `./configure --help` in the source tree.
Run an installation with `-k` to preserve the source tree in `~/.pyenv/sources`.
