### ISSUE TITLE
BUILD FAILED (Debian 11 using python-build 20180424)

### ISSUE THREAD

**Issue by konabaid** [pyenv/pyenv#2765]
<pre><font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ sudo apt update; sudo apt install build-essential libssl-dev zlib1g-dev \
libbz2-dev libreadline-dev libsqlite3-dev curl \
libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
Ign:1 cdrom://[Debian GNU/Linux 11.7.0 _Bullseye_ - Official amd64 DVD Binary-1 20230429-11:50] bullseye InRelease
Err:2 cdrom://[Debian GNU/Linux 11.7.0 _Bullseye_ - Official amd64 DVD Binary-1 20230429-11:50] bullseye Release
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Hit:3 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:4 http://deb.debian.org/debian bullseye InRelease
Hit:5 http://deb.debian.org/debian bullseye-updates InRelease
Hit:6 http://security.debian.org/debian-security bullseye-security InRelease
Hit:7 http://repo.mysql.com/apt/debian bullseye InRelease
Reading package lists... Done<font color="#A2734C">    </font>
<font color="#C01C28"><b>E: </b></font>The repository &apos;cdrom://[Debian GNU/Linux 11.7.0 _Bullseye_ - Official amd64 DVD Binary-1 20230429-11:50] bullseye Release&apos; does not have a Release file.
<font color="#A2734C">N: </font>Updating from such a repository can&apos;t be done securely, and is therefore disabled by default.
<font color="#A2734C">N: </font>See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
xz-utils is already the newest version (5.2.5-2.1~deb11u1).
build-essential is already the newest version (12.9).
curl is already the newest version (7.74.0-1.3+deb11u7).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2+deb11u2).
libffi-dev is already the newest version (3.3-6).
libxml2-dev is already the newest version (2.9.10+dfsg-6.7+deb11u4).
liblzma-dev is already the newest version (5.2.5-2.1~deb11u1).
libreadline-dev is already the newest version (8.1-1).
libbz2-dev is already the newest version (1.0.8-4).
libsqlite3-dev is already the newest version (3.34.1-3).
libncursesw5-dev is already the newest version (6.2+20201114-2+deb11u1).
tk-dev is already the newest version (8.6.11+1).
libxmlsec1-dev is already the newest version (1.2.31-1).
libssl-dev is already the newest version (1.1.1n-0+deb11u5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ which pyenv
/home/linuxbrew/.linuxbrew/bin/pyenv
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ echo $PATH | grep --color=auto &quot;$(pyenv root)/shims&quot;
<font color="#C01C28"><b>/home/debian/.pyenv/shims</b></font>:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ ls /home/
<font color="#12488B"><b>debian</b></font>  <font color="#12488B"><b>linuxbrew</b></font>  <font color="#12488B"><b>lost+found</b></font>
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ brew uninstall pyenv
Uninstalling /home/linuxbrew/.linuxbrew/Cellar/pyenv/2.3.24... (1,106 files, 4.2MB)
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ ls /home/
<font color="#12488B"><b>debian</b></font>  <font color="#12488B"><b>linuxbrew</b></font>  <font color="#12488B"><b>lost+found</b></font>
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ which pyenv
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ brew install pyenv
Running `brew update --auto-update`...
<font color="#26A269">==&gt;</font> <b>Fetching </b><font color="#26A269"><b>pyenv</b></font>
<font color="#12488B">==&gt;</font> <b>Downloading https://ghcr.io/v2/homebrew/core/pyenv/manifests/2.3.24</b>
Already downloaded: /home/debian/.cache/Homebrew/downloads/6e364f26707b4222206930a21efe173d867e69ab27184aaa400f694bacc0e870--pyenv-2.3.24.bottle_manifest.json
<font color="#12488B">==&gt;</font> <b>Downloading https://ghcr.io/v2/homebrew/core/pyenv/blobs/sha256:1198cc9f259c</b>
Already downloaded: /home/debian/.cache/Homebrew/downloads/f6b5a2a5edbf130df56aa4a4da9ce17f7c29b22569874707150a07f4b0bb92f6--pyenv--2.3.24.x86_64_linux.bottle.tar.gz
<font color="#12488B">==&gt;</font> <b>Pouring pyenv--2.3.24.x86_64_linux.bottle.tar.gz</b>
🍺  /home/linuxbrew/.linuxbrew/Cellar/pyenv/2.3.24: 1,106 files, 4.2MB
<font color="#12488B">==&gt;</font> <b>Running `brew cleanup pyenv`...</b>
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ ls /home/
<font color="#12488B"><b>debian</b></font>  <font color="#12488B"><b>linuxbrew</b></font>  <font color="#12488B"><b>lost+found</b></font>
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ ls /home/debian/
<font color="#12488B"><b>Desktop</b></font>    <font color="#12488B"><b>Downloads</b></font>  <font color="#C01C28"><b>mysql-apt-config_0.8.22-1_all.deb</b></font>  <font color="#12488B"><b>Public</b></font>     <font color="#12488B"><b>Videos</b></font>
<font color="#12488B"><b>Documents</b></font>  <font color="#12488B"><b>Music</b></font>      <font color="#12488B"><b>Pictures</b></font>                           <font color="#12488B"><b>Templates</b></font>
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ ls /home/debian/.
./             .bash_profile  .dbus/         .pki/          .wget-hsts
../            .bashrc        .gnupg/        .profile       
.bash_history  .cache/        .local/        .pyenv/        
.bash_logout   .config/       .mozilla/      .ssh/          
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ ls /home/debian/.pyenv/
plugins/  shims/    versions/ 
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ ls /home/debian/.pyenv/
plugins/  shims/    versions/ 
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ ls /home/debian/.pyenv/versions/
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ ls /home/debian/.pyenv/versions/
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ which pyenv
/home/linuxbrew/.linuxbrew/bin/pyenv
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ ^C
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ echo $PATH | grep --color=auto &quot;$(pyenv root)/shims&quot;
<font color="#C01C28"><b>/home/debian/.pyenv/shims</b></font>:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ echo &apos;export PYENV_ROOT=&quot;$HOME/debian/.pyenv&quot;&apos; &gt;&gt; ~/.bashrc
echo &apos;command -v pyenv &gt;/dev/null || export PATH=&quot;$PYENV_ROOT/bin:$PATH&quot;&apos; &gt;&gt; ~/.bashrc
echo &apos;eval &quot;$(pyenv init -)&quot;&apos; &gt;&gt; ~/.bashrc
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ exec &quot;$SHELL&quot;
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ pyenv install 3.11.4
Downloading Python-3.11.4.tar.xz...
-&gt; https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tar.xz
Installing Python-3.11.4...
Traceback (most recent call last):
  File &quot;&lt;string&gt;&quot;, line 1, in &lt;module&gt;
  File &quot;/home/debian/debian/.pyenv/versions/3.11.4/lib/python3.11/ssl.py&quot;, line 100, in &lt;module&gt;
    import _ssl             # if we can&apos;t import it, let the error propagate
    ^^^^^^^^^^^
ModuleNotFoundError: No module named &apos;_ssl&apos;
<b>ERROR</b>: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems

<b>BUILD FAILED</b> (Debian 11 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20230826224444.181238
<font color="#A2734C">Results logged to /tmp/python-build.20230826224444.181238.log</font>

Last 10 log lines:
	LD_LIBRARY_PATH=/tmp/python-build.20230826224444.181238/Python-3.11.4 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
Looking in links: /tmp/tmp1_vf5c3s
Processing /tmp/tmp1_vf5c3s/setuptools-65.5.0-py3-none-any.whl
Processing /tmp/tmp1_vf5c3s/pip-23.1.2-py3-none-any.whl
Installing collected packages: setuptools, pip
  WARNING: The scripts pip3 and pip3.11 are installed in &apos;/home/debian/debian/.pyenv/versions/3.11.4/bin&apos; which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-23.1.2 setuptools-65.5.0
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ CPPFLAGS=&quot;-I&lt;openssl install prefix&gt;/include&quot; \
LDFLAGS=&quot;-L&lt;openssl install prefix&gt;/lib&quot; \
pyenv install -v 3.11.4
/tmp/python-build.20230826224922.192649 ~
Downloading Python-3.11.4.tar.xz...
-&gt; https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tar.xz
/tmp/python-build.20230826224922.192649/Python-3.11.4 /tmp/python-build.20230826224922.192649 ~
Installing Python-3.11.4...
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for Python interpreter freezing... ./_bootstrap_python
checking for python3.11... no
checking for python3.10... no
checking for python3.9... python3.9
checking Python for regen version... Python 3.9.2
checking for pkg-config... /home/linuxbrew/.linuxbrew/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... &quot;linux&quot;
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/python-build.20230826224922.192649/Python-3.11.4&apos;:
configure: error: C compiler cannot create executables
See `config.log&apos; for more details

<b>BUILD FAILED</b> (Debian 11 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20230826224922.192649
<font color="#A2734C">Results logged to /tmp/python-build.20230826224922.192649.log</font>

Last 10 log lines:
checking for pkg-config... /home/linuxbrew/.linuxbrew/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... &quot;linux&quot;
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/python-build.20230826224922.192649/Python-3.11.4&apos;:
configure: error: C compiler cannot create executables
See `config.log&apos; for more details
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ CONFIGURE_OPTS=&quot;-with-openssl=&lt;openssl install prefix&gt;&quot;
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ LDFLAGS=&quot;-Wl,-rpath,&lt;openssl install prefix&gt;/lib&quot; \
CONFIGURE_OPTS=&quot;-with-openssl=&lt;openssl install prefix&gt;&quot; \
pyenv install -v 3.11.4
/tmp/python-build.20230826225006.193088 ~
Downloading Python-3.11.4.tar.xz...
-&gt; https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tar.xz
/tmp/python-build.20230826225006.193088/Python-3.11.4 /tmp/python-build.20230826225006.193088 ~
Installing Python-3.11.4...
configure: WARNING: you should use --build, --host, --target
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: prefix&gt;
checking build system type... Invalid configuration `install&apos;: machine `install-unknown&apos; not recognized
configure: error: /bin/bash ./config.sub install failed

<b>BUILD FAILED</b> (Debian 11 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20230826225006.193088
<font color="#A2734C">Results logged to /tmp/python-build.20230826225006.193088.log</font>

Last 10 log lines:
/tmp/python-build.20230826225006.193088 ~
/tmp/python-build.20230826225006.193088/Python-3.11.4 /tmp/python-build.20230826225006.193088 ~
configure: WARNING: you should use --build, --host, --target
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: prefix&gt;
checking build system type... Invalid configuration `install&apos;: machine `install-unknown&apos; not recognized
configure: error: /bin/bash ./config.sub install failed
</pre>

**Comment by native-api** [comment]
Please add the required diagnostic information as per the issue template.

**Comment by konabaid** [comment]
> Please add the required diagnostic information as per the issue template.

Hi, sorry for not provide the complete information about the issue. what is the diagnostic information? I'm new at this.

I tried to follow the guide but I felt like something is not correct in my doing. This is what I did :

1. I already installed the suggested build environment, but not enough. it said "Missing the OpenSSL lib?"
<pre>pyenv install 3.11.4
Downloading Python-3.11.4.tar.xz...
-&gt; https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tar.xz
Installing Python-3.11.4...
Traceback (most recent call last):
  File &quot;&lt;string&gt;&quot;, line 1, in &lt;module&gt;
  File &quot;/home/debian/debian/.pyenv/versions/3.11.4/lib/python3.11/ssl.py&quot;, line 100, in &lt;module&gt;
    import _ssl             # if we can&apos;t import it, let the error propagate
    ^^^^^^^^^^^
ModuleNotFoundError: No module named &apos;_ssl&apos;
<b>ERROR</b>: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


<b>BUILD FAILED</b> (Debian 11 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20230826224444.181238
<font color="#A2734C">Results logged to /tmp/python-build.20230826224444.181238.log</font>

Last 10 log lines:
	LD_LIBRARY_PATH=/tmp/python-build.20230826224444.181238/Python-3.11.4 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
Looking in links: /tmp/tmp1_vf5c3s
Processing /tmp/tmp1_vf5c3s/setuptools-65.5.0-py3-none-any.whl
Processing /tmp/tmp1_vf5c3s/pip-23.1.2-py3-none-any.whl
Installing collected packages: setuptools, pip
  WARNING: The scripts pip3 and pip3.11 are installed in &apos;/home/debian/debian/.pyenv/versions/3.11.4/bin&apos; which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-23.1.2 setuptools-65.5.0
</pre>


2. I tried to fix the "Missing the OpenSSL lib?"

<pre>CPPFLAGS=&quot;-I&lt;openssl install prefix&gt;/include&quot; \
LDFLAGS=&quot;-L&lt;openssl install prefix&gt;/lib&quot; \
pyenv install -v 3.11.4
/tmp/python-build.20230826224922.192649 ~
Downloading Python-3.11.4.tar.xz...
-&gt; https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tar.xz
/tmp/python-build.20230826224922.192649/Python-3.11.4 /tmp/python-build.20230826224922.192649 ~
Installing Python-3.11.4...
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for Python interpreter freezing... ./_bootstrap_python
checking for python3.11... no
checking for python3.10... no
checking for python3.9... python3.9
checking Python for regen version... Python 3.9.2
checking for pkg-config... /home/linuxbrew/.linuxbrew/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... &quot;linux&quot;
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/python-build.20230826224922.192649/Python-3.11.4&apos;:
configure: error: C compiler cannot create executables
See `config.log&apos; for more details

<b>BUILD FAILED</b> (Debian 11 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20230826224922.192649
<font color="#A2734C">Results logged to /tmp/python-build.20230826224922.192649.log</font>

Last 10 log lines:
checking for pkg-config... /home/linuxbrew/.linuxbrew/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... &quot;linux&quot;
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/python-build.20230826224922.192649/Python-3.11.4&apos;:
configure: error: C compiler cannot create executables
See `config.log&apos; for more details</pre>

3. I also tried to check fi there is a problem with the PATH; but I dont understand after read the guide. I feel like this is where my issue happened. 

<pre>which pyenv
/home/linuxbrew/.linuxbrew/bin/pyenv
<font color="#26A269"><b>debian@debian</b></font>:<font color="#12488B"><b>~</b></font>$ echo $PATH | grep --color=auto &quot;$(pyenv root)/shims&quot;
<font color="#C01C28"><b>/home/debian/.pyenv/shims</b></font>:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
</pre>

I'm totally new at this. I just started using python by following tutorial on youtube and then got stuck at setting up the pyenv. I installed the pyenv using brew.

I'm using debian 11.7 on my virtual machine.

**Comment by konabaid** [comment]
Case closed

Try to unistall the pyenv and the brew. Then install the pyenv without the brew.

**Comment by konabaid** [comment]
Case closed

Try to uninstall the pyenv and the brew. Then reinstall the pyenv without using the brew.

probably the problem is because the lib is installed by apt so it's not recognized by the pyenv which installed by brew.
