### ISSUE TITLE
Looks like 2.3.35 and 2.3.25 both tag the same commit

### ISSUE THREAD

**Issue by chenrui333** [pyenv/pyenv#2766]
👋 it looks like both tags are tagging the same commit, maybe consider removing 2.3.35 tag? Thanks!

![image](https://github.com/pyenv/pyenv/assets/1580956/644a1c19-4505-424d-b2d1-1d40ea4751f5)

relates to https://github.com/Homebrew/homebrew-core/pull/140603

**Comment by native-api** [comment]
CC @anton-petrov

**Comment by dvzrv** [comment]
Hi! Please *never* delete tags. Downstreams (often seconds or minutes after their creation) use them to build packages from.

I understand that 2.3.35 was created in error. However, it has already been used downstream and removing the tag will lead to broken reproducible builds.

**Comment by anton-petrov** [comment]
Ok, I'll keep that in mind for the future. Sorry for the inconvenience.
