### ISSUE TITLE
Running pyenv inside an existing venv dosn't change python versions

### ISSUE THREAD

**Issue by expruc** [pyenv/pyenv#2767]
### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): **rhel8.8 (container as ubi8)**
- [ ] OS architecture (e.g. amd64): **amd64**
- [ ] pyenv version: **2.3.34**
- [ ] Python version: **3.9.16**
- [ ] C Compiler information (e.g. gcc 7.3): **8.5.0**

I have a ubi8 container (rhel8) in which python 3.9 is installed as a global venv. The venv was created without pyenv (but with python -m venv command). I have followed all the steps for configuring the virtualenvs using pyenv and everything is working as expected, but the python version isn't changed when running `pyenv local X.Y.Z` or even when running `pyenv global X.Y.Z` (the selected version as shown in `pyenv versions` is the correct version but running `python` command gives me the old global version). I have created a similar environment without system python installed as venv and pyenv works as expected so I think the problem resides on the python installed inside a venv.

Is there some way to workaround this issue without disabling the venv? I haven't found issues about installing and configuring pyenv on existing venv. Is there some way to workaround this issue? I have found the pyenv-register plugin but it is archived now and isn't mentioned in the supported plugins for pyenv.

Thank you for the help!

**Comment by native-api** [comment]
Please add the remaining diagnostic information as per the issue template.

Run the faulty commands with PYENV_DEBUG enabled and attach the resulting trace.
