### ISSUE TITLE
Bug: 404 error while calculating hashes and excessive logging with 2023.8.28

### ISSUE THREAD

**Issue by matejsp** [pyenv/pyenv#2773]
when upgrading from pipenv 2023.7.3 to 2023.8.28.

First there is very verbose logging for INFO:pipenv.patched.pip._internal.operations.prepare.
It was not there before. pipenv lock displayed couple of lines and now it display hundreds for each download file.

Now what this bug is about hash calculation. So when downloading file ... 
It seems that automatic calculation of hash in case md5 is used in nexus it uses incorrect url.

INFO:pipenv.patched.pip._internal.operations.prepare:Collecting wcmatch==8.3 (from semgrep==0.78.0->-r /var/folders/l6/nmk965l50gv_90_c4xh5x0_4ctpk94/T/pipenv-jgl0rhw4-requirements/pipenv-an17je3b-constraints.txt (line 19))
INFO:pipenv.patched.pip._internal.network.download:Using cached https://nexus.company.net/repository/pypi-blessed/packages/wcmatch/8.3/wcmatch-8.3-py3-none-any.whl (42 kB)

Downloading file wcmatch-8.3-py3-none-any.whl to obtain hash...
HTTP error 404 while getting https://u:p@nexus.company.net/packages/wcmatch/8.3/wcmatch-8.3-py3-none-any.whl#md5=8d2acdbf5586e2175b9f88d16e599ac8
Downloading file wcmatch-8.3.tar.gz to obtain hash...
HTTP error 404 while getting https://u:p@nexus.company.net/packages/wcmatch/8.3/wcmatch-8.3.tar.gz#md5=d3e45a9f6853ebbb4d64c60d279de2f8
Downloading file wcmatch-8.3.tar.gz to obtain hash...
Downloading file wcmatch-8.3-py3-none-any.whl to obtain hash...

When resolving downloading hashes part of url is missing. But it works when downloading original whl or tar.gz.

[[source]]
name = "nexus"
url = "https://u:p@nexus.company.net/repository/pypi-blessed/simple"
verify_ssl = true

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): MacOSX 13.5.1
- [ ] OS architecture (e.g. amd64): intel
- [ ] pyenv version: 2023.8.28
- [ ] Python version: 3.11

**Comment by matejsp** [comment]
It seems that everything is broken regarding hashes (it seems that case sensitivity is an issue).

What we have in nexus:
<img width="569" alt="image" src="https://github.com/pyenv/pyenv/assets/3091122/4869e2e6-b800-4438-a638-a6693ab74afa">

and with upgraded pipenv all the hashes are removed.
<img width="709" alt="image" src="https://github.com/pyenv/pyenv/assets/3091122/d96b2d44-ce4a-4c5f-905b-48faa522eaf1">

Same story for pyyaml:
<img width="477" alt="image" src="https://github.com/pyenv/pyenv/assets/3091122/55756496-4ef3-47dc-b51f-7e93d125a21c">

vs
<img width="709" alt="image" src="https://github.com/pyenv/pyenv/assets/3091122/9fc8f247-81b5-4301-b51c-c4fe40485525">

Or dots vs dashes:

<img width="635" alt="image" src="https://github.com/pyenv/pyenv/assets/3091122/445e5803-c581-4656-ae40-03eac30a2d9c">

<img width="687" alt="image" src="https://github.com/pyenv/pyenv/assets/3091122/8494b036-f95e-4c0f-a904-103fef6382c7">

MarkupSafe is another case for broken hashes.

**Comment by native-api** [comment]
This looks like a Pip or Pipenv problem.

**Comment by matejsp** [comment]
Sry ... I googled for the wrong project, closing
