### ISSUE TITLE
synatx error on installing due to 503 on github

### ISSUE THREAD

**Issue by thezoggy** [pyenv/pyenv#2775]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 22.04.3 LTS
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: installing
- [x] Python version: 3.10.12
- [x] C Compiler information (e.g. gcc 7.3): 11.4.0
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [ ] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

trying to install:
```
$ curl https://pyenv.run | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   270  100   270    0     0   1220      0 --:--:-- --:--:-- --:--:--  1221
bash: line 2: syntax error near unexpected token `newline'
bash: line 2: `<?xml version="1.0" encoding="utf-8"?>'
```
```
$ curl https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 first byte timeout</title>
  </head>
  <body>
    <h1>Error 503 first byte timeout</h1>
    <p>first byte timeout</p>
    <h3>Error 54113</h3>
    <p>Details: cache-stl760026-STL 1693887840 2977604550</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

trying to load page from browser on another machine:
https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer
```
Error 503 first byte timeout

first byte timeout
Error 54113

Details: cache-dfw-kdal2120141-DFW 1693887636 1785915079

Varnish cache server
```

**Comment by thezoggy** [comment]
and just to clarify, I'm just bringing this failure scenario to light so better error handling can tell the user that its github issue and try again once its resolved

**Comment by native-api** [comment]
Not sure what 'error handling' on our side you have in mind. The command fails before any code from Pyenv gets control.

**Comment by ajgringo619** [comment]
Working fine here, Arch and Linux Mint. Tried the `curl` command you referenced as well - again, no issues.

**Comment by thezoggy** [comment]
yep, worked fine once github outage was resolved as expected.
