### ISSUE TITLE
Python 2.7 install fails through socks proxy

### ISSUE THREAD

**Issue by jeremie-huy** [pyenv/pyenv#2776]
I'm trying to `pyenv install 2.7` with environment variables for socks proxy (http_proxy and https_proxy) and the build fails because of `Missing dependencies for SOCKS support`

It's working with installing version 3.x.

Thanks

### Description
- Platform information: Ubuntu 22.04
- OS architecture: amd64
- pyenv version: 2.3.25
- Python version: system 3.10.12
- C Compiler information: 11.4.0 

[trace.log](https://github.com/pyenv/pyenv/files/12525115/trace.log)

**Comment by native-api** [comment]
This is a limitation of Pip. It requires PySocks to support SOCKS proxies. See e.g. https://github.com/pypa/pip/issues/6668 .

I don't know why it works for you for 3.x . I guess you have PySocks installed for the system Python -- which Pyenv-managed Pythons happen to share the user site directory with.

**Comment by native-api** [comment]
There may be a workaround. E.g. there's probably a Pip setting (which can be set via an ennvar) that would prohibit it from looking online during installation via `ensurepip` -- so you'll have a chance to install PySocks yourself later via some other channel.

**Comment by native-api** [comment]
> there's probably a Pip setting (which can be set via an ennvar) that would prohibit it from looking online during bootstrap/installation

Indeed, it is!

```
PIP_NO_INDEX=1 pyenv install 2.7
```

**Comment by jeremie-huy** [comment]
Thank you for the help!

When using `PIP_NO_INDEX=1` I don't have the SOCKS error anymore, but I encounter another one:
```
ERROR: Could not find a version that satisfies the requirement pip<21.0 (from versions: none)
ERROR: No matching distribution found for pip<21.0
```

I'll continue the investigation

**Comment by native-api** [comment]
> ERROR: Could not find a version that satisfies the requirement pip<21.0 (from versions: none)
> ERROR: No matching distribution found for pip<21.0

That's strange. The pip in https://bootstrap.pypa.io/pip/2.7/get-pip.py is `20.3.4`.
I suggest you run the installation with `PYENV_DEBUG=1` to see what exact command fails.
If it's Pip -- Pip has a number of diagnostic settings, also turnable with envvars.
