### ISSUE TITLE
pyenv init with nvm break mc (Midnight Commander) subshell

### ISSUE THREAD

**Issue by rafajot1** [pyenv/pyenv#2777]
Not sure about the exact technical background of this issue but it looks like
`eval "$(pyenv init -)"` in .bashrc
breaks mc subshell functionality - meaning when switching to subshell in mc by pressing CTRL+O the subshell does not work - any key pressed results in coming back to mc and working in subshell is not possible.

---Update:
It's probably not a purely pyenv issue.
I have just noticed that the problem is only when

`eval "$(pyenv init -)"` in .bashrc

comes together with nvm loading
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
```

Any of these two single settings in .bashrc should not cause the issue but combined together break mc subshell.
Unfortunately I don't know the exact root cause therefore it's probably fair to close this issue but maybe it will be indexed by google for people who come across the same problem.

My environment details (running in wsl console in windows 11)
```
XXX@XXXXX:~$ pyenv --version
pyenv 2.3.25-6-g91002438
XXX@XXXXX:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
XXX@XXXXX:~$ mc --version
GNU Midnight Commander 4.8.27
Built with GLib 2.68.4
Built with S-Lang 2.3.2 with terminfo database
With builtin Editor and Aspell support
With subshell support as default
With support for background operations
With mouse support on xterm and Linux console
With support for X11 events
With internationalization support
With multiple codepages support
With ext2fs attributes support
Virtual File Systems:
 cpiofs, tarfs, sfs, extfs, ext2undelfs, ftpfs, sftpfs, fish
Data types:
 char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64;
XXX@XXXXX:~$ nvm --version
0.39.3
```

**Comment by native-api** [comment]
WFM in Ubuntu 22 with NVM installed. So doesn't look like a Pyenv issue.

Problem diagnostic is always done by the same scenario:

1. Localize the issue. Find the exact place in the code where the problem manifests itself.
2. Examine the state of the program at that exact moment, to find out which of the values is wrong.
3. Trace the wrong value back to its origin.

With a user-level issue, that'll look like this:
1. Localize the issue to a specific component. Ususally by replacing components and seeing what replacements cause the problem to disappear and reappear.
2. Find out what exactly the component is doing wrong. Usually, by tracing its execution somehow (diagnostic logging, Sysinternals Procmon/strace) and finding out values that govern its behaviour -- to see which of them is wrong.
3. Trace the wrong value back to its origin. Relatively easy if the component is open-source so you can see its logic to trace where the value comes from. If it's closed-source, you'll have to make guesses about its logic and verify them. In especially hard cases, I had to disassemble the specific modules with IDA.
