### ISSUE TITLE
Can't build a thing on MacOS 13.5.1 : "ld: library not found for -lSystem"

### ISSUE THREAD

**Issue by Chris-May** [pyenv/pyenv#2782]
I wanted to do whatever I could to not create this ticket, but I can't figure out what to do.

I've recently tried to use `pyenv` on two new MacBook Pros with no success on either. One uses a M2 Max chip. The other is a M2 Pro. Both seem to fail with the same error, so I'm thinking it's an issue with the OS.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): `MacOS 13.5.1` 
- [x] OS architecture (e.g. amd64): `Apple M2 Max`
- [x] pyenv version: `2.3.26`
- [ ] Python version:
- [x] C Compiler information (e.g. gcc 7.3): `clang`
- [x] Please attach the debug trace of the failing command as a gist: [attached here](https://gist.github.com/Chris-May/06710ad372e8aab38d48df77ec2c8e76)
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory

**Comment by native-api** [comment]
According to https://github.com/ponylang/ponyc/issues/3684, this is a problem with theg compiler toolchain after you've upgraded the OS.
You need to upgrade XCode command line tools.

**Comment by Chris-May** [comment]
Sorry for the delay. I've been trying to understand more to try and resolve this.

I updated XCode Tools before I ran anything and again now, and it hasn't made a difference.

I'm still trying to understand what more I can do based on the linked discussion.

**Comment by Chris-May** [comment]
After thrashing around a lot, I finally decided to install XCode and ran these commands:

```sh
sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
xcodebuild -runFirstLaunch 
```
Then I was able to use pyenv.

Hopefully this will help someone.
