### ISSUE TITLE
Python 3.10.8 :: No module named 'readline' & ERROR: The Python ssl extension was not compiled: "symbol not found in flat namespace '_GENERAL_NAME_free'"

### ISSUE THREAD

**Issue by kediwu0331** [pyenv/pyenv#2787]
Platform: macOS Ventura 13.5.2 M1 chip
Pyenv version: 2.3.26
Python: 3.10.8
OpenSSL version: 1.1 (installed from brew)

Tried commands:
`CPPFLAGS="-I$(brew --prefix openssl@1.1)/include -I$(brew --prefix readline)/include -I$(xcrun -show-sdk-path)/usr/include" LDFLAGS="-L$(brew --prefix openssl@1.1)/lib -L$(brew --prefix readline)/lib" pyenv install 3.10.8`

`CONFIGURE_OPTS="--with-openssl=$(brew --prefix openssl)" pyenv install 3.10.8`

I know this is an old issue. But I tried the commands suggested in the official doc and some other posts. None of them works for me. I would be greatly appreciated if someone can give some hint.

**Comment by native-api** [comment]
Please add the necessary diagnostic information as per the issue template.

**Comment by kediwu0331** [comment]
[trace.log](https://github.com/pyenv/pyenv/files/12678440/trace.log)
[config.log](https://github.com/pyenv/pyenv/files/12678446/config.log)

trace.log and config.log are attached. Let me know if these are the logs requested. Thanks for reviewing them!

**Comment by native-api** [comment]
You're building for x64 but have ARM64 Homebrew on PATH.

**Comment by kediwu0331** [comment]
Thanks for reviewing the log. I was able to successfully build after switching to x86_64 homebrew.
