### ISSUE TITLE
Trouble install python 3.4.2

### ISSUE THREAD

**Issue by defcube** [pyenv/pyenv#279]
I'm running on OS X 10.10.1, and have python 3.4.1 installed. 3.4.1 was installed when I was on OS X 10.9 still, so I'm not sure where the problem is coming from.  The problem I hit, when trying to install 3.4.2, can be seen below.

. . .
(cd /usr/local/opt/pyenv/versions/3.4.2/bin; ln -s idle3.4 idle3)
rm -f /usr/local/opt/pyenv/versions/3.4.2/bin/pydoc3
(cd /usr/local/opt/pyenv/versions/3.4.2/bin; ln -s pydoc3.4 pydoc3)
rm -f /usr/local/opt/pyenv/versions/3.4.2/bin/2to3
(cd /usr/local/opt/pyenv/versions/3.4.2/bin; ln -s 2to3-3.4 2to3)
rm -f /usr/local/opt/pyenv/versions/3.4.2/bin/pyvenv
(cd /usr/local/opt/pyenv/versions/3.4.2/bin; ln -s pyvenv-3.4 pyvenv)
if test "x" != "x" ; then \
                rm -f /usr/local/opt/pyenv/versions/3.4.2/bin/python3-32; \
                (cd /usr/local/opt/pyenv/versions/3.4.2/bin; ln -s python3.4-32 python3-32) \
        fi
rm -f /usr/local/opt/pyenv/versions/3.4.2/share/man/man1/python3.1
(cd /usr/local/opt/pyenv/versions/3.4.2/share/man/man1; ln -s python3.4.1 python3.1)
if test "xupgrade" != "xno"  ; then \
                case upgrade in \
                        upgrade) ensurepip="--upgrade" ;; \
                        install|*) ensurepip="" ;; \
                esac; \
                 ./python.exe -E -m ensurepip \
                        $ensurepip --root=/ ; \
        fi
Ignoring ensurepip failure: pip 1.5.6 requires SSL/TLS

**Comment by yangj1e** [comment]
Found same problem. But I am against installing Xcode command line tools since I already have full Xcode application installed. Explicitly installing Xcode command line tools seems to duplicate what are contained in Xcode application.
