### ISSUE TITLE
Unable to install python 3.11.0 with tkinter on MacOS

### ISSUE THREAD

**Issue by absoup** [pyenv/pyenv#2790]
I'm receiving the following error when trying to install `python 3.11.0` via `pyenv` on `MacOS Ventura 13.5.2 (22G91)`:

```console
foo@bar:~$ pyenv install 3.11.0
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.11.0.tar.xz...
-> https://www.python.org/ftp/python/3.11.0/Python-3.11.0.tar.xz
Installing Python-3.11.0...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/me/.pyenv/versions/3.11.0/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
WARNING: The Python tkinter extension was not compiled and GUI subsystem has been detected. Missing the Tk toolkit?
Installed Python-3.11.0 to /Users/me/.pyenv/versions/3.11.0
```

at the same time, I'm able to install `python 3.10.4` without any issues:

```console
foo@bar:~$ pyenv install 3.10.4
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.10.4.tar.xz...
-> https://www.python.org/ftp/python/3.10.4/Python-3.10.4.tar.xz
Installing Python-3.10.4...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.10.4 to /Users/me/.pyenv/versions/3.10.4
```

I found a couple of similar issues reported by someone else here [#94](https://github.com/pyenv/pyenv/issues/94#issuecomment-592990387) and on [stackoverflow](https://stackoverflow.com/questions/60469202/unable-to-install-tkinter-with-pyenv-pythons-on-macos), but after trying all of the recommended solutions I could find - none of them seem to work in my case.

For example, I've tried the following - uninstall, install with some environment variables (actually tried multiple different variations):

```console
foo@bar:~$ pyenv uninstall 3.11.0
pyenv: remove /Users/me/.pyenv/versions/3.11.0? [y|N] y
pyenv: 3.11.0 uninstalled
```

```console
foo@bar:~$ env \
PATH="$(brew --prefix tcl-tk)/bin:$PATH" \
LDFLAGS="-L$(brew --prefix tcl-tk)/lib" \
CPPFLAGS="-I$(brew --prefix tcl-tk)/include" \
PKG_CONFIG_PATH="$(brew --prefix tcl-tk)/lib/pkgconfig" \
CFLAGS="-I$(brew --prefix tcl-tk)/include" \
PYTHON_CONFIGURE_OPTS="--with-tcltk-includes='-I$(brew --prefix tcl-tk)/include' --with-tcltk-libs='-L$(brew --prefix tcl-tk)/lib -ltcl8.6.13 -ltk8.6.13'" \
pyenv install 3.11.0
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.11.0.tar.xz...
-> https://www.python.org/ftp/python/3.11.0/Python-3.11.0.tar.xz
Installing Python-3.11.0...
python-build: use tcl-tk from $PYTHON_CONFIGURE_OPTS
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/me/.pyenv/versions/3.11.0/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
WARNING: The Python tkinter extension was not compiled and GUI subsystem has been detected. Missing the Tk toolkit?
Installed Python-3.11.0 to /Users/me/.pyenv/versions/3.11.0
```

As far as I understand, `pyenv` successfully picks up homebrew's `tcl-tk` and that's not an issue. According to this [comment](https://stackoverflow.com/a/75804235/14688566) on stackoverflow it appears `tcl-tk` is no longer keg-only and, therefore, setting environment variables is no longer needed. In fact, I don't see any caveats like *"tcl-tk is keg-only, which means it was not symlinked into /usr/local"* when I'm running `brew info tcl-tk` (as far as I understand, that's the issue faced by the majority of commenters there and the fix for this is running `pyenv install` once again along with those environment variables).

---

### Description
- [x] Platform information: `macOS Ventura 13.5.2 (22G91)`
- [x] OS architecture: `Intel`
- [x] pyenv version: `2.3.26`
- [x] Python version: `3.11.0`
- [x] C Compiler information: `gcc 14.0.3`
- [x] Please attach the debug trace of the failing command as a gist:
- [x] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`: https://gist.github.com/absoup/23721bc0bcbe1275e6e4e41ef42ae1f7
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`: https://gist.github.com/absoup/14feafbfaaaab0d5507f9aaacf743ebc 
  
[trace.log](https://github.com/pyenv/pyenv/files/12640736/trace.log)
[config.log](https://github.com/pyenv/pyenv/files/12640737/config.log)

**Comment by native-api** [comment]
```
configure:13472: clang -o conftest -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include  -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/Users/me/.pyenv/versions/3.11.0/include  -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/me/.pyenv/versions/3.11.0/lib -Wl,-rpath,/Users/me/.pyenv/versions/3.11.0/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib conftest.c  -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/me/.pyenv/versions/3.11.0/lib -Wl,-rpath,/Users/me/.pyenv/versions/3.11.0/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib >&5
conftest.c:130:10: error: "Tcl older than 8.5.12 not supported"
      #  error "Tcl older than 8.5.12 not supported"
         ^
conftest.c:133:10: error: "Tk older than 8.5.12 not supported"
```

Apparently, 3.11 has dropped support for the Tcl/Tk version that you have installed.
Tcl/Tk 8.5 is bundled with Apple SDK IIRC.
So you need tyo install a newer version with Homebrew.

**Comment by absoup** [comment]
@native-api hm, weird
when I'm running `brew info tcl-tk` - it gives the following output:

```console
foo@bar:~$ brew info tcl-tk
==> tcl-tk: stable 8.6.13 (bottled)
Tool Command Language
https://www.tcl-lang.org
Conflicts with:
  page (because both install `page` binaries)
/usr/local/Cellar/tcl-tk/8.6.13_5 (3,064 files, 52.8MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-09-12 at 20:45:30
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/t/tcl-tk.rb
License: TCL
==> Dependencies
Required: openssl@3 ✔
==> Caveats
The sqlite3_analyzer binary is in the `sqlite-analyzer` formula.
==> Analytics
install: 56,808 (30 days), 170,137 (90 days), 336,980 (365 days)
install-on-request: 26,030 (30 days), 86,361 (90 days), 165,325 (365 days)
build-error: 6 (30 days)
```

so it seems like homebrew's version is older than `8.5.12`

and I see `python-build: use tcl-tk from homebrew` when trying to install `3.11.0` (so it looks like it's picking up homebrew's `tcl/tk`)
