### ISSUE TITLE
install python but i keep getting this error of not being able to 

### ISSUE THREAD

**Issue by jtamprime** [pyenv/pyenv#2798]
pyenv install 3.9.4

This is the output ( I am on windows 10 pro X64)

Downloading Python-3.9.4.tar.xz...

-> https://www.python.org/ftp/python/3.9.4/Python-3.9.4.tar.xz

Installing Python-3.9.4...

patching file Misc/NEWS.d/next/Build/2021-10-11-16-27-38.bpo-45405.iSfdW5.rst

patching file configure

patching file configure.ac

BUILD FAILED (Ubuntu 22.04 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20230921112623.3117

Results logged to /tmp/python-build.20230921112623.3117.log

Last 10 log lines:

checking for python3... python3

checking for --enable-universalsdk... no

checking for --with-universal-archs... no

checking MACHDEP... "linux"

checking for gcc... no

checking for cc... no

checking for cl.exe... no

configure: error: in `/tmp/python-build.20230921112623.3117/Python-3.9.4':

configure: error: no acceptable C compiler found in $PATH

See `config.log' for more details

shadopika@StormStryker:/mnt/c/WINDOWS/system32$ /tmp/python-build.20230921112623.3117.log

-bash: /tmp/python-build.20230921112623.3117.log: Permission denied

shadopika@StormStryker:/mnt/c/WINDOWS/system32$ config.log

config.log: command not found

tried sudo apt install build-essential
[sudo] password for shadopika:

Reading package lists... Done

Building dependency tree... Done

Reading state information... Done

Package build-essential is not available, but is referred to by another package.

This may mean that the package is missing, has been obsoleted, or

is only available from another source

E: Package 'build-essential' has no installation candidate

but still the same problem

**Comment by native-api** [comment]
> Package build-essential is not available, but is referred to by another package.

Something is wrong with your Linux package manager. Not related to Pyenv.
