### ISSUE TITLE
BUILD FAILED (OS X 14.0 using python-build 20180424) "libc++abi: terminating due to uncaught exception of type NSException"

### ISSUE THREAD

**Issue by pekanchuan** [pyenv/pyenv#2801]
`pyenv install 3.11.5`
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.11.5.tar.xz...
-> https://www.python.org/ftp/python/3.11.5/Python-3.11.5.tar.xz
error: failed to download Python-3.11.5.tar.xz

**BUILD FAILED (OS X 14.0 using python-build 20180424)**

Last 10 log lines:
	29  dyld                                0x000000018084fb14 _ZNK5dyld416JustInTimeLoader15runInitializersERNS_12RuntimeStateE + 36
	30  dyld                                0x0000000180849b4c _ZNK5dyld46Loader23runInitializersBottomUpERNS_12RuntimeStateERN5dyld35ArrayIPKS0_EE + 220
	31  dyld                                0x000000018084d654 _ZZNK5dyld46Loader38runInitializersBottomUpPlusUpwardLinksERNS_12RuntimeStateEENK3$_1clEv + 112
	32  dyld                                0x0000000180849ccc _ZNK5dyld46Loader38runInitializersBottomUpPlusUpwardLinksERNS_12RuntimeStateE + 304
	33  dyld                                0x000000018086ead4 _ZN5dyld44APIs25runAllInitializersForMainEv + 464
	34  dyld                                0x0000000180831f34 _ZN5dyld4L7prepareERNS_4APIsEPKN5dyld313MachOAnalyzerE + 3192
	35  dyld                                0x0000000180830f44 start + 1948
)
libc++abi: terminating due to uncaught exception of type NSException
/opt/homebrew/Cellar/pyenv/2.3.27/plugins/python-build/bin/python-build: line 365: 18369 Abort trap: 6           aria2c --allow-overwrite=true --no-conf=true -d "${dir_out}" -o "${out}" ${ARIA2_OPTS} "$1" 1>&4

I tried reinstall pyenv, aria2 and their dependencies, but won't work.

Also tried `brew install python-build`, still not work, please help me.

**Comment by native-api** [comment]
Please add the necessary diagnostic information as per the issue template.

**Comment by ijunaidf** [comment]
I am facing the same issue here on M1 Mac with fresh Sonoma install.

```bash
$ pyenv install 3.11
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.11.5.tar.xz...
-> https://www.python.org/ftp/python/3.11.5/Python-3.11.5.tar.xz
error: failed to download Python-3.11.5.tar.xz

BUILD FAILED (OS X 14.0 using python-build 20180424)

Results logged to /var/folders/t2/pn20fy1d6zg8k1qtbhtl5szc0000gn/T/python-build.20231003110323.6210.log

Last 10 log lines:
	29  dyld                                0x0000000186e47b14 _ZNK5dyld416JustInTimeLoader15runInitializersERNS_12RuntimeStateE + 36
	30  dyld                                0x0000000186e41b4c _ZNK5dyld46Loader23runInitializersBottomUpERNS_12RuntimeStateERN5dyld35ArrayIPKS0_EE + 220
	31  dyld                                0x0000000186e45654 _ZZNK5dyld46Loader38runInitializersBottomUpPlusUpwardLinksERNS_12RuntimeStateEENK3$_1clEv + 112
	32  dyld                                0x0000000186e41ccc _ZNK5dyld46Loader38runInitializersBottomUpPlusUpwardLinksERNS_12RuntimeStateE + 304
	33  dyld                                0x0000000186e66ad4 _ZN5dyld44APIs25runAllInitializersForMainEv + 464
	34  dyld                                0x0000000186e29f34 _ZN5dyld4L7prepareERNS_4APIsEPKN5dyld313MachOAnalyzerE + 3192
	35  dyld                                0x0000000186e28f44 start + 1948
)
libc++abi: terminating due to uncaught exception of type NSException
/opt/homebrew/Cellar/pyenv/2.3.28/plugins/python-build/bin/python-build: line 365:  6291 Abort trap: 6           aria2c --allow-overwrite=true --no-conf=true -d "${dir_out}" -o "${out}" ${ARIA2_OPTS} "$1" 1>&4
```

Adding additional details:
- Platform information: Macos Sonoma 14.0
- OS architecture: arm64
- pyenv version: 2.3.28
- Python version: 3.11.5
- C Compiler information: Apple clang version 15.0.0 (clang-1500.0.40.1)

Attached:
- [trace.log](https://github.com/pyenv/pyenv/files/12788870/trace.log)
- [python-build.log](https://github.com/pyenv/pyenv/files/12788871/python-build.log)

**Comment by iainn** [comment]
I'm experiencing the same issue. It works fine when Rosetta isn't enabled, but as soon as I use Rosetta, I get the same error.

**Comment by emision** [comment]
Problem in aria2c, check here https://github.com/aria2/aria2/issues/2083 

Just add `export LC_MESSAGES="C"` in .bashrc

**Comment by ijunaidf** [comment]
Same here, aria2c is causing the error. I uninstalled the brew provided aria2c and manually built it from the source and then it worked.
