### ISSUE TITLE
Building Python failed: configure: error: cannot compute suffix of object files: cannot compile

### ISSUE THREAD

**Issue by regunakyle** [pyenv/pyenv#2803]
I am on Fedora 38. 
I installed Pyenv with the installer and the prerequisite packages as listed [here](https://github.com/pyenv/pyenv/wiki).

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
* [x] Make sure your problem is not derived from plugins.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): **Fedora 38 KDE** 
- [x] OS architecture (e.g. amd64): **AMD64**
- [x] pyenv version: **2.3.27**
- [x] Python version: **3.11.5** (Install failed)
- [x] C Compiler information (e.g. gcc 7.3):  **gcc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)**

- [x] Please attach the debug trace of the failing command as a gist: 
- https://gist.github.com/regunakyle/893a53c71cb2c87255156379c43eb1c6 (`config.log` also attached)

**Comment by native-api** [comment]
```
ccache: error: Failed to create directory /home/regunakyle/.cache/ccache/lock: Permission denied
```

**Comment by regunakyle** [comment]
> ```
> ccache: error: Failed to create directory /home/regunakyle/.cache/ccache/lock: Permission denied
> ```
> 
> Looks like a permission issue.

Yep, the build works after deleting the `ccache` directory by force. Thanks!
