### ISSUE TITLE
Setup PKG_CONFIG_PATH

### ISSUE THREAD

**Issue by blueyed** [pyenv/pyenv#281]
Could pyenv automatically setup `PKG_CONFIG_PATH` (for pkg-config)?

E.g. for version 3.4.2 it would be:

```
export PKG_CONFIG_PATH=~/.pyenv/versions/3.4.2/lib/pkgconfig
```

I guess this could be done through a plugin quite easily?
But then it's probably nice to have this by default / in the core.

**Comment by native-api** [comment]
I think `pyenv exec` can add this to the env _of the invoked command._

@blueyed , could you describe the intended use case and demonstrate how you envision this feature in action?

**Comment by native-api** [comment]
I think `pyenv exec` can add this to the env _of the invoked command._

@blueyed , could you describe the intended use case and demonstrate how you envision this feature in action?

For starters, I doubt we even _want_ this envvar to always be set.
