### ISSUE TITLE
Use `.pyenv-version` instead of `.python-version`

### ISSUE THREAD

**Issue by jpmelos** [pyenv/pyenv#2816]
`.python-version` is a very generic name. It's bound to find conflicts, as other engineers in other projects choose to use the same name, but for other purposes, in their Python projects, thus making it hard to reconcile `pyenv` with those other projects.

[One such project is GitHub's `dependabot`.](https://github.com/dependabot/dependabot-core/issues/1455#issuecomment-545389290) If a project is using `dependabot`, and they want to control what Python version `dependabot` is going to use to resolve dependencies, they should put a raw Python version (e.g. `3.10.12`) in that file. If a developer wants to use a virtual environment created by `pyenv-virtualenv` locally, they will want to put the virtual environment's name in the file, not a raw Python version. Then, this creates a change that `git` keeps trying to commit to the repository.

Let's make `pyenv` resilient to this problem, in a future-proof way, and change it to use `.pyenv-version`, which is a `pyenv`-specific name, and thus it's much less likely to find conflicts with other projects.

**Comment by native-api** [comment]
AFAICS from [the current Dependabot code](https://github.com/dependabot/dependabot-core/blob/9436f409c17432b27650949e5bfa433066226604/python/lib/dependabot/python/file_parser/python_requirement_parser.rb#L150), it specifically treats `.python-version` as the version [to take from Pyenv](https://github.com/dependabot/dependabot-core/blob/9436f409c17432b27650949e5bfa433066226604/python/lib/dependabot/python/file_parser/python_requirement_parser.rb#L101-L103). So it's not a conflict -- just the opposite, an integration!

If it doesn't support some of Pyenv's newer and/or plugin features, that's a defect of the integration mechanism in Dependabot.

**Comment by native-api** [comment]
Btw [AFAICS](https://github.com/dependabot/dependabot-core/blob/9436f409c17432b27650949e5bfa433066226604/python/lib/dependabot/python/file_parser/python_requirement_parser.rb#L67-L75), it also doesn't support multiple versions in the file.
