### ISSUE TITLE
Debug symbols are not loaded by GDB on activated venv

### ISSUE THREAD

**Issue by alexveden** [pyenv/pyenv#2819]
### Description
- [ ] Debian Linux 10
- [ ] OS architecture (e.g. amd64): x64
- [ ] pyenv version: 2.3.15
- [ ] Python version: 3.10-debug
- [ ] C Compiler information (e.g. gcc 7.3):  10.2
- [] GDB 10.1

I've found that Python debug symbols are not loaded by gdb when activated via `pyenv`, however in case of direct call everything works fine.

## Reproduction steps
```
# install debug version of python
>  pyenv install 3.10 -g

# excecute python directly from installation dir
> gdb ~/.pyenv/versions/3.10.10-debug/bin/python3.10
GDB output here...
*works*
...
Reading symbols from ~/.pyenv/versions/3.10.10-debug/bin/python3.10
...
```
### Create venv
```
> pyenv virtualenv 3.10.10-debug gdbtest

> pyenv activate gdbtest

(gdbtest) > pyenv which python
~/.pyenv/versions/gdbtest/bin/python

> gdb ~/.pyenv/versions/gdbtest/bin/python
*works*
Reading symbols from ~/.pyenv/versions/gdbtest/bin/python...

# THIS FAILS no symbols loaded
> gdb python
....
0x7ffff0fb6050s": not in executable format: file format not recognized
```

**Comment by alexveden** [comment]
It looks like, it's an old issue:
https://stackoverflow.com/questions/66824320/gdb-python-in-pyenv-virtualenv

There is a workaround:
```
gdb `pyenv which python`
```

It's up to you guys to decide if this bug has to be fixed or not.

**Comment by native-api** [comment]
Not sure what we can do from our side. GDB doesn't recognize smart links like Pyenv shims.

**Comment by native-api** [comment]
Not sure what we can do from our side. GDB doesn't resolve smart links like Pyenv shims.
No Pyenv code gets control to be able to do anything about that.

**Comment by levsa** [comment]
> It looks like, it's an old issue: https://stackoverflow.com/questions/66824320/gdb-python-in-pyenv-virtualenv
> 
> There is a workaround:
> 
> ```
> gdb `pyenv which python`
> ```
> 
> It's up to you guys to decide if this bug has to be fixed or not.

I've installed `3.12.10` with `pyenv install --debug 3.12.10` which ended up as `$HOME/.pyenv/versions/3.12.10-debug`, but gdb cannot find debugging symbols (looks like there is a link to a temporary file?):

```
Reading symbols from $HOME/.pyenv/versions/3.12.10-debug/bin/python...

warning: `/private/var/folders/km/zstvzfwj6qx9zfrpj21_wxc40000gn/T/python-build.20251103124741.54175/Python-3.12.10/Programs/python.o': can't open to read symbols: No such file or directory.
(No debugging symbols found in $HOME/.pyenv/versions/3.12.10-debug/bin/python)
```

**Comment by native-api** [comment]
@levsa We do not change anything from what Apple CLang and CPython's build logic do here.

Try rebuilding with the `PYTHON_BUILD_CONFIGURE_WITH_DSYMUTIL` envvar set.
If it works, we'll enable it by default.

**Comment by MSeal** [comment]
Can report `PYTHON_BUILD_CONFIGURE_WITH_DSYMUTIL` does not fix object binary discovery issue on arm osx.
