### ISSUE TITLE
Shell Environment Setup Instruction not Working Properly When Using pyenv in WSL and With pyenv-win

### ISSUE THREAD

**Issue by Xdynix** [pyenv/pyenv#2821]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 22.04.3 LTS (inside WSL)
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 2.3.29
- [ ] Python version: N/A
- [ ] C Compiler information (e.g. gcc 7.3): N/A
- [ ] Please attach the debug trace of the failing command as a gist: N/A
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [ ] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

Firstly I installed `pyenv` in my WSL Ubuntu following the instructions, which is working correctly. Then I installed `pyenv-win` on my Windows (which is the host of the WSL Ubuntu). The `pyenv` in WSL Ubuntu will not working again.

I found that the problem lies in this sentence of Shell environment configuration, mentioned in the installation instructions:

`command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"`

In WSL, it will append the host's `PATH` environment variable to the `PATH` defined in files such as `.zshrc` to allow us to call the host's application from WSL. But this results in the `pyenv` executable from `pyenv-win` also appearing in the `PATH`. Therefore, the sentence configuring `PATH` for `pyenv` considers that there is no need to add the real `pyenv` (`$PYENV_ROOT/bin`) to the `PATH`, which causes the `pyenv` from the host's `pyenv-win` to be called, and it cannot work normally in the WSL environment.

I understand that using more complex checks specifically for WSL use cases is not ideal, so I wanted to suggest if we could mention this edge case in the documentation for anyone who needs it?

**Comment by native-api** [comment]
> if we could mention this edge case in the documentation for anyone who needs it?

We could, but I'm not sure where it belongs.

**Comment by native-api** [comment]
CC @pyenv/pyenv-core-maintainers
