### ISSUE TITLE
Pythno 3.12.0 not in version list

### ISSUE THREAD

**Issue by renja-g** [pyenv/pyenv#2822]
Python 3.12.0 is not in the list of available versions after `pyenv install --list`
only `3.12.0rc1` and `3.12-dev` but it should be fully released now or am I wrong?

**Comment by jack-mcivor** [comment]
You may need to run `pyenv update` to update the list of available versions

**Comment by renja-g** [comment]
Thanks

**Comment by seeker25** [comment]
Might need:
https://github.com/pyenv/pyenv-update

for `pyenv update` to work

**Comment by therealjamesjung** [comment]
In case you've install pyenv via brew, run `brew upgrade pyenv`

**Comment by pkaiser-twist** [comment]
I had to do `git pull` when I was in `user/.pyenv/plugins/python-build` after I had upgraded to the latest
