### ISSUE TITLE
"cannot stat 'Modules/_crypt.cpython-312-x86_64-linux-gnu.so': No such file or directory" in Linux with Homebrew

### ISSUE THREAD

**Issue by punowo** [pyenv/pyenv#2823]
Ubuntu Linux 23.10
amd64
pyenv version: 2.3.30
gcc (Ubuntu 13.2.0-4ubuntu3) 13.2.0

[trace.log](https://github.com/pyenv/pyenv/files/13012615/trace.log)
[python-build.20231018124421.17515.log](https://github.com/pyenv/pyenv/files/13012774/python-build.20231018124421.17515.log)

I installed pyenv using homebrew on Linux, but I also had a similar issue when using the pyenv installer on another Ubuntu 23.10 machine.

**Comment by LFT-W47** [comment]
I have the same problem. I installed `pyenv` with `git clone`.
It seems there is a similar problem with [Mac M1](https://github.com/pyenv/pyenv/issues/).
The suggestions there didn't helped me...
I can install every other version without problems...

**Comment by native-api** [comment]
```
[ERROR] _blake2 failed to import: libb2.so.1: cannot open shared object file: No such file or directory
[ERROR] _crypt failed to import: libcrypt.so.2: cannot open shared object file: No such file or directory
[ERROR] nis failed to import: libnsl.so.3: cannot open shared object file: No such file or directory
```

This looks like https://github.com/pyenv/pyenv/issues/2693#issuecomment-1531613792 .
The compiler uses symlinks `libxxx.so -> libxxx.so.<version>` to decide which specific version to link against when none is explicitly specified (which is the typical case; [to link against a specific version, `-l:libxxx.so.<version>` needs to be used instead of `-lxxx`](https://stackoverflow.com/questions/828053/how-do-you-link-to-a-specific-version-of-a-shared-library-in-gcc) which I've never seen in the wild so far).

> Check if you have invalid symlinks named libssl.so on your system pointing to a nonexistent "libssl.so.1.1".
> 
> You have OpenSSL 3 installed but the build tries to link against OpenSSL 1.1. The above can be the cause.
> 
> If one is in /usr/lib, fix it to point to the corresponding OpenSSL 3 file (reinstalling the OpenSSL package may do this for you).
> If it's in /usr/local/lib, delete it (this most likely means you have leftovers from a source installation of OpenSSL 1.1).

**Comment by LFT-W47** [comment]
> To build with the system's toolchain,
> 
>     * uninstall or at least `brew unlink` Homebrew-provided `pkg-config`; or
> 
>     * remove Homebrew from `PATH`


removing Homebrew from `PATH` worked for me. Ty

**Comment by native-api** [comment]
> Should I worry about the warnings ?

The mentioned modules will be missing so the associated Python functionality won't work. This may or may not be significant for you.
Normally, you want to install all the dependencies as per https://github.com/pyenv/pyenv/wiki#suggested-build-environment before building to get a fully functional Python.

**Comment by native-api** [comment]
> This worked:
> 
> ```
> ~> CC=/home/linuxbrew/.linuxbrew/bin/gcc-13 CPPFLAGS="-I$(brew --prefix)/include" LDFLAGS="-L$(brew --prefix)/lib" py
> ```

Strange. For me, it worked with just `CC=<...>`.
Though without the required logs as per the issue template, I cannot say anything for sure.

**Comment by native-api** [comment]
As a resolution to this topic, it seems we'd need to add an exception to Pyenv to use Homebrew in Linux by default if Pyenv itself has been installed with Homebrew. (Then you would not need to use a Homebrew-provided compiler 'cuz Pyenv would be adding the compiler options that those add implicitly.)
This has been an idea ever [since we turned that off by default due to the problems it was causing](https://github.com/pyenv/pyenv/pull/2349).

Shall we also print a warning if Homebrew is _not_ going to be used but Homebrew-provided `pkg-config` is detected on PATH?

**Comment by kevinderuijter** [comment]
> @punowo this is the reason:
> 
> ```
> checking for pkg-config... /home/linuxbrew/.linuxbrew/bin/pkg-config
> ```
> 
> Homebrew installs `pkg-config` under a name that shadows the system's one.
> 
> This stops one from being able to build software using the system toolchain -- because the flags it produces only work out of the box if using a Homebrew-provided compiler.
> 
> Pyenv doesn't use packages from Homebrew in Linux by default. That's because Homebrew is more problematic to use than distro-provided packages. Unlike most distros, Homebrew is rolling-release -- and as such, its dependency package upgrades break existing Pyenv-provided installations whenever their `.so` names change.
> 
> To build with the system's toolchain,
> 
> * uninstall or at least `brew unlink` Homebrew-provided `pkg-config`; or
> * remove Homebrew from `PATH`
> 
> To build with Homebrew's toolchain,
> 
> * install a Homebrew-provided compiler and
> * direct any builds to use it with `export CC=<compiler executable to use>`

Installing python 3.12.0 raised `/usr/bin/install: cannot stat 'Modules/_crypt.cpython-312-x86_64-linux-gnu.so': No such file or directory`, unlike any other Python version.

Using Ubuntu 22.04 LTS and `brew unlink pkg-config` solved the issue for me.

**Comment by kyhyco** [comment]
`brew unlink pkg-config` also works for macOS

**Comment by Jon2G** [comment]
`ginstall: cannot stat 'Modules/_dbm.cpython-312-darwin.so': No such file or directory`
In my case i was missing gdbm
So i had to `brew install gdbm`

**Comment by BoscoDomingo** [comment]
> `brew unlink pkg-config` also works for macOS

PSA this can be easily undone by the counterpart `brew link pkg-config` afterwards 👍🏼

**Comment by robbiemu** [comment]
> And here is the second command I tried which was successful:
> 
> ```
> env PYTHON_CONFIGURE_OPTS='--enable-optimizations --with-lto' PYTHON_CFLAGS='-march=native -mtune=native' CC=/home/linuxbrew/.linuxbrew/bin/gcc-13 CPPFLAGS="-I$(brew --prefix)/include" LDFLAGS="-L$(brew --prefix)/lib"  pyenv install 3.12
> ```

this did not work for me. I'm on a Mac, so I wanted to avoid the brew toolchain, so my cmd was:

> env PYTHON_BUILD_SKIP_HOMEBREW=1 PYTHON_CONFIGURE_OPTS="--enable-framework --enable-optimizations --with-lto" CC=/opt/homebrew/bin/gcc-13  pyenv install 3.12.0 

where that CC came from brew install gcc, in case that's not obvious. 

the error:
```
Downloading openssl-3.1.2.tar.gz...
-> https://www.openssl.org/source/openssl-3.1.2.tar.gz
Installing openssl-3.1.2...
Installed openssl-3.1.2 to /Users/robbie/.pyenv/versions/3.12.0
Downloading readline-8.2.tar.gz...
-> https://ftpmirror.gnu.org/readline/readline-8.2.tar.gz
Installing readline-8.2...
Installed readline-8.2 to /Users/robbie/.pyenv/versions/3.12.0
Downloading Python-3.12.0.tar.xz...
-> https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tar.xz
Installing Python-3.12.0...

BUILD FAILED (OS X 14.1.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/9h/_r86cs8177x6hmpxy0fg473h0000gp/T/python-build.20231124154047.93268
Results logged to /var/folders/9h/_r86cs8177x6hmpxy0fg473h0000gp/T/python-build.20231124154047.93268.log

Last 10 log lines:
gcc-13: error: unrecognized command-line option '-fprofile-instr-generate'; did you mean '-fprofile-generate'?
gcc-13: error: unrecognized command-line option '-fprofile-instr-generate'; did you mean '-fprofile-generate'?
make[2]: *** [Parser/action_helpers.o] Error 1
make[2]: *** [Parser/token.o] Error 1
gcc-13: error: unrecognized command-line option '-fprofile-instr-generate'; did you mean '-fprofile-generate'?
make[2]: *** [Objects/bytes_methods.o] Error 1
gcc-13: error: unrecognized command-line option '-fprofile-instr-generate'; did you mean '-fprofile-generate'?
make[2]: *** [Parser/parser.o] Error 1
make[1]: *** [profile-gen-stamp] Error 2
make: *** [profile-run-stamp] Error 2
```

**Comment by iandol** [comment]
`brew unlink pkg-config` worked a treat; it would have been nice to get this as a warning or note on the command line. Ubuntu 22.04.03 + homebrew installed pyenv

**Comment by tauanbinato** [comment]
> `brew unlink pkg-config` also works for macOS

This also worked for me using linux mint, installed at first using homebrew, then i uninstalled and installed pyenv manually, still got the problem. So if you use homebrew once you have to do this before installing latest python version

**Comment by albertnieto** [comment]
I don't even have brew installed, any tips?

**Comment by glinka** [comment]
> I don't even have brew installed, any tips?

Following the advice [here](https://superuser.com/questions/1428109/install-python-3-7-3-from-source-with-ssl-failed) worked for me (update `ld.so.conf` to include your local library path(s), then register new settings with `ldconfig`)

**Comment by speetpeet** [comment]
`brew unlink pkg-config` worked. WSL, Ubuntu 22.04.03 and homebrew installed pyenv
