### ISSUE TITLE
Why is the last release tagged with `2.3.30` instead of `v2.3.30`?

### ISSUE THREAD

**Issue by ala-ableton** [pyenv/pyenv#2825]
Hi,
Thanks a lot for pyenv, it is making our life so much easier!

The last release of pyenv (https://github.com/pyenv/pyenv/releases/tag/2.3.30) is associated with the tag `2.3.30`. All previous releases of pyenv 2.3 were associated with tags starting with a leading `v`. I couldn't see in the changelog between https://github.com/pyenv/pyenv/compare/v2.3.29...2.3.30 why this had changed, so I'm wondering whether it was done on purpose or whether the tag was meant to be `v2.3.30`.

What should we expect for future releases? Will the next one be tagged `2.3.31` or `v2.3.31`?

**Comment by anton-petrov** [comment]
It was just my mistake. **v2.3.31** already released.

**Comment by ala-ableton** [comment]
Thanks for the quick reply!
