### ISSUE TITLE
Compilation error while installing Python: "ModuleNotFoundError: No module named '_scproxy'"

### ISSUE THREAD

**Issue by jetpants** [pyenv/pyenv#2826]
After installing pyenv for the first time, I use it to install a version of Python (the version doesn't matter), and I get compilation errors while compiling zlib.

### Description
- macOS 14.0
- pyenv 2.3.31
- trying to install Python 3.10, but it's the same error message with other versions
- Removed and re-installed Xcode command line tools
- Apple clang version 15.0.0 (clang-1500.0.40.1), Target: arm64-apple-darwin23.0.0

### Error message
$ pyenv install 3.10                                                                               
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.10.13.tar.xz...
-> https://www.python.org/ftp/python/3.10.13/Python-3.10.13.tar.xz
Installing Python-3.10.13...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use ncurses from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 14.0 using python-build 2.3.31)

Inspect or clean up the working tree at /var/folders/43/z_5gkk052qg86pymwwgy0yjr0000gq/T/python-build.20231024113649.28802
Results logged to /var/folders/43/z_5gkk052qg86pymwwgy0yjr0000gq/T/python-build.20231024113649.28802.log

Last 10 log lines:
  File "/private/var/folders/43/z_5gkk052qg86pymwwgy0yjr0000gq/T/python-build.20231024113649.28802/Python-3.10.13/Lib/ensurepip/__init__.py", line 287, in _main
    return _bootstrap(
  File "/private/var/folders/43/z_5gkk052qg86pymwwgy0yjr0000gq/T/python-build.20231024113649.28802/Python-3.10.13/Lib/ensurepip/__init__.py", line 203, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
  File "/private/var/folders/43/z_5gkk052qg86pymwwgy0yjr0000gq/T/python-build.20231024113649.28802/Python-3.10.13/Lib/ensurepip/__init__.py", line 104, in _run_pip
    return subprocess.run(cmd, check=True).returncode
  File "/private/var/folders/43/z_5gkk052qg86pymwwgy0yjr0000gq/T/python-build.20231024113649.28802/Python-3.10.13/Lib/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/private/var/folders/43/z_5gkk052qg86pymwwgy0yjr0000gq/T/python-build.20231024113649.28802/Python-3.10.13/python.exe', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/var/folders/43/z_5gkk052qg86pymwwgy0yjr0000gq/T/tmpm2ryr4ti/setuptools-65.5.0-py3-none-any.whl\', \'/var/folders/43/z_5gkk052qg86pymwwgy0yjr0000gq/T/tmpm2ryr4ti/pip-23.0.1-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/var/folders/43/z_5gkk052qg86pymwwgy0yjr0000gq/T/tmpm2ryr4ti\', \'--root\', \'/\', \'--upgrade\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
make: *** [install] Error 1

[config.log](https://github.com/pyenv/pyenv/files/13113194/config.log)
[trace.log](https://github.com/pyenv/pyenv/files/13113136/trace.log)

**Comment by grelland** [comment]
Experiencing the exact same issue. MacOS 13.6.

**Comment by native-api** [comment]
Same problem as in https://github.com/pyenv/pyenv/issues/2776 .
Pip requires additional modules to download through unusual types of proxies.

* Build with `PIP_NO_INDEX` envvar: `PIP_NO_INDEX=1 pyenv install <...>`
* Then get the required additional modules through some other channel and install then into the resulting Python installation

**Comment by native-api** [comment]
Scratch the previous message.

You have bogus include files in `/usr/local/include`:

```
building '_scproxy' extension
clang <...> -c /private/var/folders/43/z_5gkk052qg86pymwwgy0yjr0000gq/T/python-build.20231024113423.14256/Python-3.10.13/Modules/_scproxy.c -o build/temp.macosx-14.0-arm64-3.10/private/var/folders/43/z_5gkk052qg86pymwwgy0yjr0000gq/T/python-build.20231024113423.14256/Python-3.10.13/Modules/_scproxy.o
In file included from /private/var/folders/43/z_5gkk052qg86pymwwgy0yjr0000gq/T/python-build.20231024113423.14256/Python-3.10.13/Modules/_scproxy.c:6:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SystemConfiguration.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:54:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:75:
/usr/local/include/Block.h:16:3: error: Never include this file directly. Use <lzma.h> instead.
#       error Never include this file directly. Use <lzma.h> instead.
        ^
/usr/local/include/Block.h:93:2: error: unknown type name 'lzma_check'
        lzma_check check;
        ^
```

Looks like you had installed LZMA from source at the default prefix (`/usr/local`). As you can see, it breaks Xcode this way 'cuz Apple has the same-named header files.

You need to remove that LZMA installation. If you need it, install it with some other prefix -- e.g. `/opt/<distinguishing name>`.

**Comment by jetpants** [comment]
Thanks, @native-api. That fixed my problem. Much appreciated.

It's a relatively new machine (3 months) and I've barely installed anything, so no idea how this library's include files are here.

@grelland and anyone else with the issue, I went to /usr/local/include and moved these 14 files somewhere else (all containing "liblzma"):

base.h
bcj.h
block.h
check.h
container.h
delta.h
filter.h
hardware.h
index.h
index_hash.h
lzma12.h
stream_flags.h
version.h
vli.h

**Comment by native-api** [comment]
These files might be from the corresponding Homebrew package (then the files are probably symlinks to the package's real location).

Because it conflicts with Xcode, it must be keg-only, but if you manually `brew link` it anyway, things like this happen.
