### ISSUE TITLE
`pyenv install` within Kubeflow notebook: lots of compilation errors, then "ModuleNotFoundError: No module named '_posixsubprocess'"

### ISSUE THREAD

**Issue by anemiroffsumer** [pyenv/pyenv#2834]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

Python env install  (python versions) won't work on a ubuntu (k8s based) Kubeflow notebook https://github.com/kubeflow/kubeflow 
R Studio Notebook builds keep failing with 

BUILD FAILED (Ubuntu 20.04 using python-build 2.3.31)

Inspect or clean up the working tree at /tmp/python-build.20231031154657.197031
Results logged to /tmp/python-build.20231031154657.197031.log

Last 10 log lines:
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/tmp/python-build.20231031154657.197031/Python-3.11.3/Lib/ensurepip/__init__.py", line 4, in <module>
    import subprocess
  File "/tmp/python-build.20231031154657.197031/Python-3.11.3/Lib/subprocess.py", line 104, in <module>
    from _posixsubprocess import fork_exec as _fork_exec
ModuleNotFoundError: No module named '_posixsubprocess'
make: *** [Makefile:1872: install] Error 1

### Description
- [ ] Platform information: Description:    Ubuntu 20.04.6 LTS
- [ ] OS architecture AMD EPYC 7763 64-Core Processor
- [ ] pyenv version: pyenv 2.3.31
- [ ] Python version: 3.11.4
- [ ] C Compiler information:  gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
- [ ] Please attach the debug trace of the failing command as a gist:
 https://drive.google.com/file/d/1dm1QqYlZ-QS0aJDFt6GRTxoD6xx766mo/view?usp=sharing). 
  = build failure log 
 https://drive.google.com/file/d/1R77puk44szKJQUkryy-d4f6enYJ83Cms/view?usp=sharing 
 trace log
 = build failure log 
 

  
  ADDITIONAL INFO:
  
  conda is used as a fundamental build agent for kubeflow: 
  

let me know what additional info you need.

**Comment by native-api** [comment]
```
++(/home/jovyan/.pyenv/plugins/python-build/bin/python-build:818): build_package_standard_build(): '[' -z /opt/conda/bin/x86_64-conda-linux-gnu-cc ']'
<...>
checking build system type... x86_64-conda-linux-gnu
<...>
checking for x86_64-conda-linux-gnu-gcc... /opt/conda/bin/x86_64-conda-linux-gnu-cc
```
---

You have the `CC` envvar set to Conda's compiler. It comes with its own set of C headers which are incompatible with the system's ones. So when they're used together, the compilation process breaks.

Unset that envvar and use the system's compiler.

**Comment by native-api** [comment]
> Python env install (python versions) won't work on a ubuntu (k8s based) Kubeflow notebook https://github.com/kubeflow/kubeflow
> R Studio Notebook builds keep failing with

If you're using some sandboxed environment rather than a standard system, it could be more productive to rather check with the environment's documentation and/or tech support how (and _if)_ you are supposed to install additional software.
