### ISSUE TITLE
BUILD FAILED (OS X 14.1 using python-build 2.3.31-1-g63c471d0)

### ISSUE THREAD

**Issue by binbjz** [pyenv/pyenv#2835]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04):
- [ ] OS architecture (e.g. amd64):
- [ ] pyenv version:
- [ ] Python version:
- [ ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [ ] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

### MacOS、gcc、cmake info：
```sh
$ sw_vers
ProductName:		macOS
ProductVersion:		14.1
BuildVersion:		23B74

$ gcc --version
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

$ cmake --version
cmake version 3.27.7
```

###  Repro Steps
```sh
$ env PYTHON_CONFIGURE_OPTS="--enable-framework --enable-optimizations --with-lto" pyenv install miniconda3-3.11-23.9.0-0 -v

Downloading and Extracting Packages:
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR: invalid Python executable: /Users/binbjz/.pyenv/versions/miniconda3-3.11-23.9.0-0/bin/python

The python-build could not find proper executable of Python after successful build.
Please open an issue for future improvements.
https://github.com/pyenv/pyenv/issues

BUILD FAILED (OS X 14.1 using python-build 2.3.31-1-g63c471d0)

Inspect or clean up the working tree at /var/folders/kh/vtm21r5s3bz53z809m5z21d80000gn/T/python-build.20231106102450.45846
Results logged to /var/folders/kh/vtm21r5s3bz53z809m5z21d80000gn/T/python-build.20231106102450.45846.log

Last 10 log lines:

Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: ...working... done
Executing transaction: ...working...
done
installation finished.
```

### Check the contents of the log file. There is no error message
```sh
$ bat /var/folders/kh/vtm21r5s3bz53z809m5z21d80000gn/T/python-build.20231106102450.45846.log

  29   │ Installing base environment...
  30   │
  31   │
  32   │ Downloading and Extracting Packages
  33   │
  34   │
  35   │ Downloading and Extracting Packages
  36   │
  37   │ Preparing transaction: ...working... done
  38   │ Executing transaction: ...working...
  39   │ done
  40   │ installation finished.
```

### Check python env
```sh
$ pyenv versions
  system
* 3.11.6 (set by /Users/binbjz/.pyenv/version)
  3.12.0

$ ls -la ~/.pyenv/versions/
total 0
drwxr-xr-x  4 binbjz staff 128 Nov  6 10:25 .
drwxr-xr-x 30 binbjz staff 960 Nov  5 19:50 ..
drwxr-xr-x  6 binbjz staff 192 Oct  4 14:58 3.11.6
drwxr-xr-x  9 binbjz staff 288 Oct 10 09:18 3.12.0
```

**Comment by native-api** [comment]
Please `export CONDA_VERBOSITY=2` and provide the debug trace log as per the issue template.

**Comment by binbjz** [comment]
```sh
$ export CONDA_VERBOSITY=2
$ env PYTHON_CONFIGURE_OPTS="--enable-framework --enable-optimizations --with-lto" pyenv install miniconda3-3.11-23.9.0-0 -v


ERROR: invalid Python executable: /Users/binbjz/.pyenv/versions/miniconda3-3.11-23.9.0-0/bin/python

The python-build could not find proper executable of Python after successful build.
Please open an issue for future improvements.
https://github.com/pyenv/pyenv/issues

BUILD FAILED (OS X 14.1 using python-build 2.3.31-1-g63c471d0)

Inspect or clean up the working tree at /var/folders/kh/vtm21r5s3bz53z809m5z21d80000gn/T/python-build.20231107082714.56339
Results logged to /var/folders/kh/vtm21r5s3bz53z809m5z21d80000gn/T/python-build.20231107082714.56339.log

Last 10 log lines:
DEBUG conda.core.link:run_script(1223): for defaults::python.app-3-py311h80987f9_0 at /Users/binbjz/.pyenv/versions/miniconda3-3.11-23.9.0-0, executing script: $ /opt/homebrew/bin/bash /Users/binbjz/.pyenv/versions/miniconda3-3.11-23.9.0-0/.tmp09xrnsnh
DEBUG conda.gateways.subprocess:subprocess_call(76): executing>> /opt/homebrew/bin/bash /Users/binbjz/.pyenv/versions/miniconda3-3.11-23.9.0-0/.tmp09xrnsnh
DEBUG conda.core.prefix_data:_load_single_record(168): loading prefix record /Users/binbjz/.pyenv/versions/miniconda3-3.11-23.9.0-0/conda-meta/bzip2-1.0.8-h620ffc9_4.json

done
DEBUG conda.common.signals:signal_handler(54): de-registering handler for Signals.SIGABRT
DEBUG conda.common.signals:signal_handler(54): de-registering handler for Signals.SIGINT
DEBUG conda.common.signals:signal_handler(54): de-registering handler for Signals.SIGTERM
DEBUG conda.common.signals:signal_handler(54): de-registering handler for Signals.SIGQUIT
installation finished.
```


### python-build log
[python-build.20231107082714.56339.log](https://github.com/pyenv/pyenv/files/13274169/python-build.20231107082714.56339.log)

**Comment by native-api** [comment]
Okay, found the reason. It's the `PYTHON_CONFIGURE_OPTS` envvar, specifically, `--enable-framework` in it.

This envvar is meaningless for Miniconda since that's a precompiled distribution. But it triggers Pyenv's postprocessing build logic intended for CPython's Framework build -- which breaks Miniconda's installation as it has a different directory structure.

**Comment by binbjz** [comment]
@native-api Thank you. It solved my problem perfectly.

**Comment by Binjian** [comment]
Just in case anyone confused about the similar issue under recent macos, failing to install miniconda3 under macos 15.1.1 or later, just use  

`env PYTHON_CONFIGURE_OPTS="--enable-optimizations --with-lto" pyenv install miniconda3-3.12-24.9.2-0 -v`  ,

i.e. ignore the `--enable-framework` option.
