### ISSUE TITLE
python3-config --ldflags does not include prefix libs

### ISSUE THREAD

**Issue by mhaeuser** [pyenv/pyenv#2845]
### Description
- Platform information: macOS 14.1.1
- OS architecture: arm64
- pyenv version: 2.3.32
- Python version: 3.12-dev
- C Compiler information: Apple clang version 15.0.0

I'm not perfectly sure this is actually a bug, because the python3-config documentation is not very specific. However, I intuitively expect ``python3-config --ldflags`` to include linker flags to discover the libraries of the associated prefix.

#### Current Behaviour
The prefix is not included and compiling software with ``$($PYTHON_CONFIG --ldflags --embed)`` fails:
```
> python3-config --ldflags
-lintl -ldl -L/opt/homebrew/lib -Wl,-rpath,/opt/homebrew/lib -framework CoreFoundation
```

#### Expected Behaviour
The prefix likely should be included as such (giving precedence to it over homebrew to avoid python version conflicts):
```
> python3-config --ldflags
-lintl -ldl -L/Users/user/.pyenv/versions/3.12-dev/lib -Wl,-rpath,/Users/user/.pyenv/versions/3.12-dev/lib -L/opt/homebrew/lib -Wl,-rpath,/opt/homebrew/lib -framework CoreFoundation
```

#### Related Code
According to the current code, python3-config ignores LDFLAGS, which do indeed include the prefix search path commands:
https://github.com/pyenv/pyenv/blob/ac32a20f83d12709f2ce48a2764bef8299b51c8b/plugins/python-build/bin/python-build#L1396-L1398
Possibly the prefix paths simply are unintentionally missed for the same reason?

Thank you in advance for your time!

**Comment by mhaeuser** [comment]
Any feedback on this? I can help fix and test the issue, but first I need to understand what precisely is broken (i.e. whether there should just be another set of arguments to "Related Code" or whether something else is going wrong). :)

**Comment by native-api** [comment]
@mhaeuser Need to prepend `-L<installation prefix>/lib -Wl,-rpath,<installation prefix>/lib` to `LIBS`, unconditionally.

**Comment by mhaeuser** [comment]
Fix proposed by https://github.com/pyenv/pyenv/pull/2865
