### ISSUE TITLE
`pyenv build`: build command does not exist (regression?)

### ISSUE THREAD

**Issue by meidaid** [pyenv/pyenv#2846]
### Description
- [ ] Platform information: Ubuntu Linux 22.04 LTS):
- [ ] OS architecture: amd64
- [ ] pyenv version: pyenv 2.3.32-2-g4405459f
- [ ] Python version: None...  trying to use pyenv to install Python 3.11.
- [ ] C Compiler information (e.g. gcc 7.3): gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- [ ] Please attach the debug trace of the failing command as a gist: https://gist.github.com/meidaid/0ed09d6ff0eb85e381f8d48679a79eb9
 
Problem: `pyenv build`: build command does not exist.

Expectation: the command should exist and work.

Desired resolution: I would like to see the command working again.

If you have any questions, please feel free to ask.

**Comment by native-api** [comment]
A `build` command never existed -- in base Pyenv, at least. To install a new Python version, use `pyenv install`.

**Comment by meidaid** [comment]
> A `build` subcommand never existed -- in base Pyenv, at least. To install a new Python version, use `pyenv install`.

Thanks for the quick response.
As it turns out, `pyenv install 3.11` fails in my clean install of Ubuntu 22.04 LTS.
I came to believe that there was a `build` subcommand by mistake.

I believe that I will try to mark this issue as closed, then open a new one regarding the failing `pyenv install 3.11`.
