### ISSUE TITLE
Support installing CPython 3.13.0a2+ with the `--disable-gil` flag

### ISSUE THREAD

**Issue by edgarrmondragon** [pyenv/pyenv#2851]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description

CPython 3.13.0a2+ supports a build time [`--disable-gil`](https://docs.python.org/3.13/using/configure.html#cmdoption-disable-gil) flag. It would be great if `pyenv install` supported installing a GIL-less CPython either with a flag similar to the existing `-g/--debug` flag or with new, GIL-less, versions like `3.13.0a2-nogil`.

**Comment by native-api** [comment]
You can pass any Configure options via the `PYTHON_CONFIGURE_OPTS` envvar. See https://github.com/pyenv/pyenv/blob/master/plugins/python-build/README.md#special-environment-variables

**Comment by edgarrmondragon** [comment]
@native-api Gotcha, that seemed to work. For reference:

```console
$ PYTHON_CONFIGURE_OPTS='--disable-gil' pyenv install 3.13-dev
$ pyenv shell 3.13-dev
$ python3.13 -c 'import sysconfig; sysconfig.get_config_vars('Py_GIL_DISABLED')
1
```

Thanks!

**Comment by ZmicierGT** [comment]
Is there a way to install two 3.13-dev versions but to different directories to test builds both with enabled and disabled gil? [Pyenv-alias](https://github.com/s1341/pyenv-alias) plugin does not work any more, just renaming folders will break the installation.

**Comment by native-api** [comment]
> Is there a way to install two 3.13-dev versions but to different directories to test builds both with enabled and disabled gil? [Pyenv-alias](https://github.com/s1341/pyenv-alias) plugin does not work any more, just renaming folders will break the installation.

It is possible by calling Python-build directly. See its `--help` and README.

**Comment by ZmicierGT** [comment]
@native-api Thank you, it helped. Some details for those who'll search for it in the future. You may find python-build readme [here](https://github.com/pyenv/pyenv/tree/master/plugins/python-build). The sequence of commands I used:

`% python-build 3.13-dev /Users/zmicier/.pyenv/versions/3.13-dev_gil
% PYTHON_CONFIGURE_OPTS='--disable-gil' pyenv install 3.13-dev
% pyenv shell 3.13-dev_gil
% python3.13 -c 'import sysconfig; print(sysconfig.get_config_var("Py_GIL_DISABLED"))'
0
% pyenv shell 3.13-dev
% python3.13 -c 'import sysconfig; print(sysconfig.get_config_var("Py_GIL_DISABLED"))'
1
`

However, seems that the current nogil implementation is less stable than the experimental [nogil 3.9.10 fork](https://github.com/colesbury/nogil).
