### ISSUE TITLE
python 3.11.6 OSX Apple M1 requires openssl3, fails to build with openssl1.1

### ISSUE THREAD

**Issue by russell** [pyenv/pyenv#2856]
Hey,

I was unable to build python 3.11.6 on OSX, the build logs show python 3.11 failing to link to the openssl lib.

```
crypto -o build/lib.macosx-13.6-arm64-3.11/_hashlib.cpython-311-darwin.so
ld: warning: duplicate -rpath '/Users/rsim/.asdf/installs/python/3.11.6/lib' ignored
ld: warning: duplicate -rpath '/opt/homebrew/lib' ignored
ld: warning: duplicate -rpath '/Users/rsim/.asdf/installs/python/3.11.6/lib' ignored
ld: warning: duplicate -rpath '/opt/homebrew/lib' ignored
*** WARNING: renaming "_ssl" since importing it failed: dlopen(/private/var/folders/s1/ly7d_m5n1tb9d9tp1zfn23d00000gq/T/python-build.20231129100527.98412/Python-3.11.6/build/lib.macosx-13.6-arm64-3.11/_ssl.cpython-311-darwin.so, 0x0002): symbol not found in flat namespa
ce '_SSL_get_peer_certificate'
*** WARNING: renaming "_hashlib" since importing it failed: dlopen(/private/var/folders/s1/ly7d_m5n1tb9d9tp1zfn23d00000gq/T/python-build.20231129100527.98412/Python-3.11.6/build/lib.macosx-13.6-arm64-3.11/_hashlib.cpython-311-darwin.so, 0x0002): symbol not found in flat
 namespace '_EVP_MD_block_size'

Following modules built successfully but were removed because they could not be imported:
_hashlib              _ssl
```

The Fix was to force the python 3.11.6 to use the latest openssl. 

```
PYTHON_BUILD_HOMEBREW_OPENSSL_FORMULA=openssl@3 asdf install python 3.11.6
```

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): OSX Ventura 13.6.2
- [x] OS architecture (e.g. amd64): arm64
- [x] pyenv version: v2.3.33
- [x] Python version: 3.11.6
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 15.0.0 (clang-1500.0.40.1)
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.  build log is here https://gist.githubusercontent.com/russell/821ec208886b90eb983c6dba7d621cf2/raw/a0922485d92266fec35572556f79c86424b51bcb/gistfile1.txt
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

**Comment by native-api** [comment]
Regardless, judging by https://github.com/python/cpython/pull/107482/files , OpenSSL 3 support is finally official since 3.11.5 . So we can switch those versions to it.
