### ISSUE TITLE
Support `.python-version` in `git worktree`s 

### ISSUE THREAD

**Issue by webknjaz** [pyenv/pyenv#2859]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Feature Request

$sbj. I often make [Git worktrees](https://git-scm.com/docs/git-worktree#_examples) of projects to work on stuff or conflicting changes in a more isolated location. This is super useful. The only problem is that changing the directory means that I lose access to the pyenv virtualenv (with fallback versions) that's set up to be autoactivated in the main Git checkout.
A workaround is running `pyenv local` again, listing the same versions. But it's a duplication of effort and wouldn't be kept in sync over time.
It'd be nice for this to have `pyenv` to extend the lookup @ https://github.com/pyenv/pyenv/blob/3e1b4e0be1b01737560d0ec8b741c7d8fd704c22/libexec/pyenv-version-file#L12 to take into account Git worktrees, as opposed to just walking up the file system.

A subtree detection is not complicated:
1. There's a text file called `.git` (as opposed to a `.git/` dir in the original checkout that contains the actual tree).
2. That file has a pointer to where Git keeps the tree (but not the checkout around it).
3. Its contents look as follows:
    ```console
    $ cat .git 
    gitdir: /path/to/original/checkout/.git/worktrees/<a-branch-based-worktree-name>
    ```
4. Deducing the `/path/to/original/checkout` part and checking `/path/to/original/checkout/.python-version` should do the job.

**Comment by native-api** [comment]
What's the problem with committing `.python-version` to version control? Then you'll have it in every checkout.

**Comment by native-api** [comment]
FWIW, you can hook selected version lookup. See https://github.com/pyenv/pyenv/blob/3e1b4e0be1b01737560d0ec8b741c7d8fd704c22/libexec/pyenv-version-name#L12-L16 .

**Comment by webknjaz** [comment]
> What's the problem with committing `.python-version` to version control? Then you'll have it in every checkout, including worktrees.

The problem is that it's a library with different virtualenvs and fallbacks. It's different across the contributors too. Plus, when contributing to hundreds of projects, I wouldn't be able to force each of their maintainers switch to my pyenv setup (nor do I want to).

**Comment by native-api** [comment]
Here's a sample plugin code:

**Comment by native-api** [comment]
Here's a sample plugin code:
`/home/vmuser/.pyenv/plugins/git-worktree/etc/pyenv.d/version-name/from-git-worktree.bash`:

```
[[ -f .git ]] || return 0
<locate the version file>
PYENV_VERSION="$(pyenv-version-read-file "<version-file>")
```

**Comment by webknjaz** [comment]
Thank you for pointing this out! I didn't know there's a hook point for this. I'll try implementing it.
