### ISSUE TITLE
Pyenv Failing to install Python 3.12 on OSX Sonoma (MB Air M2): "ld: archive member '/' not a mach-o file"

### ISSUE THREAD

**Issue by koaps** [pyenv/pyenv#2862]
### Description
- Platform information:
MacBook Air M2

- OS architecture: 
ProductName:		macOS
ProductVersion:		14.1.2
BuildVersion:		23B92

- pyenv version:
pyenv 2.3.35

- Python version:
3.12.1

- C Compiler information (e.g. gcc 7.3): 
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

- Please attach the debug trace of the failing command as a gist:

https://gist.github.com/koaps/fdcdda371ff42802aff3bb0a5fbc419d#file-trace-log

- If you have a problem with installing Python, please also attach `config.log` from the build directory

https://gist.github.com/koaps/fdcdda371ff42802aff3bb0a5fbc419d#file-config-log

Seems I'm failing at linking `libHacl_Hash_SHA2.a`

`ld: archive member '/' not a mach-o file in '/private/var/folders/lg/lytxkwcd143gs3g6ygq9g63c0000gn/T/python-build.20231210171607.12722/Python-3.12.1/Modules/_hacl/libHacl_Hash_SHA2.a'`

I installed pyenv_doctor it seems ok
```
$ pyenv doctor
Cloning /Users/koaps/.pyenv/plugins/pyenv-doctor/bin/.....
Installing python-pyenv-doctor...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use ncurses from homebrew
python-build: use zlib from xcode sdk
Installed python-pyenv-doctor to /var/folders/lg/lytxkwcd143gs3g6ygq9g63c0000gn/T/pyenv-doctor.20231210173044.20846/prefix
Congratulations! You are ready to build pythons!
```

I was able to do the same process fine on my older Intel Mac.

**Comment by native-api** [comment]
```
PATH: /opt/homebrew/opt/make/libexec/gnubin/
PATH: /opt/homebrew/opt/coreutils/libexec/gnubin/
PATH: /opt/homebrew/opt/binutils/bin/
```

This error has been reported to happen if you use GCC instead of XCode-provided CLang: https://groups.google.com/g/firebird-devel/c/9a6OckFbl98?pli=1
GNU Coreutils and Binutils on PATH are also known to break build in MacOS: https://github.com/pyenv/pyenv/wiki/Common-build-problems#keg-only-homebrew-packages-are-forcibly-linked--added-to-path

Delete the above entries from PATH.

**Comment by koaps** [comment]
That fixed it, thanks!

**Comment by glaksmono** [comment]
> That fixed it, thanks!

Hey, can you share how do you actually resolved this? I'm not seeing any of those in my PATH, and I still get these errors

**Comment by zrusilla** [comment]
@glaksmono :   `which clang` might give an indication.   Another user I support was picking up a Homebrew-installed `ar` rather than XCode Tools' .   See if you have the Homebrew binutils package installed (`brew list binutils`).

**Comment by NoneShell** [comment]
> [@glaksmono](https://github.com/glaksmono) : `which clang` might give an indication. Another user I support was picking up a Homebrew-installed `ar` rather than XCode Tools' . See if you have the Homebrew binutils package installed (`brew list binutils`).
I just removed ar(/usr/local/bin/ar). it works
