### ISSUE TITLE
Pyenv issue with installing python versions - BUILD FAILED (Ubuntu 22.04 using python-build 20180424)

### ISSUE THREAD

**Issue by PRADEEPRAJKB** [pyenv/pyenv#2866]
Does anyone have similar issue and help me how to resolve it?

<img width="779" alt="Screen Shot 2023-12-18 at 1 44 05 PM" src="https://github.com/pyenv/pyenv/assets/41476736/ad18171a-f1f2-47f7-b0fb-8bb4113bef88">

**Comment by native-api** [comment]
Please addd the necessary diagnostic details as per the issue template.

**Comment by aliahadmd** [comment]
Before install pyenv , Run these command 

step 1. Check Dependencies:
`sudo apt-get install -y build-essential zlib1g-dev libffi-dev libssl-dev liblzma-dev libbz2-dev libreadline-dev libsqlite3-dev`

step 2: necessary Tkinter dependencies:
`sudo apt-get install tk-dev`

**Comment by 8188** [comment]
> Before install pyenv , Run these command
> 
> step 1. Check Dependencies: `sudo apt-get install -y build-essential zlib1g-dev libffi-dev libssl-dev liblzma-dev libbz2-dev libreadline-dev libsqlite3-dev`
> 
> step 2: necessary Tkinter dependencies: `sudo apt-get install tk-dev`

libncurses5-dev is needed for me as well but not tk-dev.
