### ISSUE TITLE
cant install python 3.8.6 on mac M1 "Unexpected output of 'arch' on OSX"

### ISSUE THREAD

**Issue by ofirmac** [pyenv/pyenv#2867]
i get error when trying to install 3.8.6

`configure: error: Unexpected output of 'arch' on OSX
make: *** No targets specified and no makefile found.  Stop.`

`BUILD FAILED (OS X 14.1.2 using python-build 20180424)`

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/wiki/Common-build-problems#keg-only-homebrew-packages-are-forcibly-linked--added-to-path

**Comment by jonathanpv** [comment]
Use the macos installer

https://www.python.org/downloads/macos/
