### ISSUE TITLE
pyenv issue installing python -- BUILD FAILED - error with `openssl` and `readline`

### ISSUE THREAD

**Issue by harsh020** [pyenv/pyenv#2872]
Unable to install python using pyenv.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
* [x] Make sure your problem is not derived from plugins.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Mac OSX 14.0 (Sonoma)
- [x] OS architecture (e.g. amd64): arm64
- [x] pyenv version: 2.3.35
- [x] Python version: 3.12.0
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 15.0.0 (clang-1500.1.0.2.5)
- [x] Please attach the debug trace of the failing command as a gist:
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'readline'
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/harsh/.pyenv/versions/3.12.0/lib/python3.12/ssl.py", line 100, in <module>
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ModuleNotFoundError: No module named '_ssl'
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?
```
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory - [console.log](https://gist.github.com/harsh020/8f1b0446c097b9e88ef922a9fe4e4221)
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach

### Fixes tried
I have tried the following things and have not worked
- [x] Tried all the things mentioned in [Common-build-problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems)
- [x] Re-installing all the dependencies 
- [x] Re-installing pyenv
- [x] Installing pyenv from - source, install script and brew
- [x] Tried solution mentioned [here](https://github.com/pyenv/pyenv/issues/2805#issuecomment-1743536437) 
- [x] Creating symlinks of all dependencies in `/usr/local/lib` & `/usr/local/include`
- [x] `brew info pyenv` shows all dependencies are met:
```bash
Python version management
https://github.com/pyenv/pyenv
/usr/local/Cellar/pyenv/2.3.35 (1,132 files, 3.4MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-12-27 at 01:17:54
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/p/pyenv.rb
License: MIT
==> Dependencies
Required: autoconf ✔, openssl@3 ✔, pkg-config ✔, readline ✔
```

**Comment by native-api** [comment]
Please include the necessary diagnostic information as per the issue template

**Comment by harsh020** [comment]
@native-api i have updated the issue description, please let me know if I missed out anything! thanks

**Comment by native-api** [comment]
```
warning: ignoring file '/usr/local/Cellar/openssl@3/3.2.0_1/lib/libssl.3.dylib': found architecture 'x86_64', required architecture 'arm64'
```

You're building for Arm64 but using an x64 Homebrew.

**Comment by harsh020** [comment]
@native-api, i have tried installing dependencies using arm64 brew and then installing
```bash
CPPFLAGS="-I$(armbrew --prefix)/include" \
LDFLAGS="-L$(armbrew --prefix)/lib" \
pyenv install 3.12.0
```

the build passes but still there is error for readline
```bash
ModuleNotFoundError: No module named 'readline'
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
```

on checking the config.log, the same warning for readline, 
```bash
ld: warning: ignoring file '/usr/local/Cellar/readline/8.2.7/lib/libreadline.8.2.dylib': found architecture 'x86_64', required architecture 'arm64'
```

I have tried [this](https://github.com/pyenv/pyenv/wiki/Common-build-problems#macos-ld-symbol-s-not-found-for-architecture-x86-64-1245) but no luck

although I am overriding the CPPFLAGS and LDFLAGS but still it continues to take them from x86 brew.

[here](https://gist.github.com/harsh020/506cc3d455b9b068f1dfcf3cf38e78cf) is the config.log, can you please help me with this?

**Comment by harsh020** [comment]
@native-api no worries i got it to work by making pyenv use `_86_64` arch using
```bash
CPPFLAGS="-I$(brew --prefix)/include" \
LDFLAGS="-L$(brew --prefix)/lib" \
arch -x86_64 pyenv install 3.12.0
```
