### ISSUE TITLE
macos 14 install python

### ISSUE THREAD

**Issue by Aya-Yang** [pyenv/pyenv#2873]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04):
- [x] OS architecture (e.g. amd64):
- [x] pyenv version:
- [x] Python version:
- [x] C Compiler information (e.g. gcc 7.3): 
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [x] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

**Comment by native-api** [comment]
please include the necessary disgnostic information as per the issue template

**Comment by Aya-Yang** [comment]
Platform information: macOS 14.2
OS architecture: arm
pyenv version: 2.3.35
python version 2.7.18 or 3.7.6
Apple clang version 14.0.0 (clang-1400.0.29.202)
there is the log:
ModuleNotFoundError: No module named 'pyexpat'

**Comment by native-api** [comment]
Need complete logs taken as specified in the template

**Comment by native-api** [comment]
About 3.7.6, it doesn't support MacOS 13+. Use the latest micro release. https://github.com/pyenv/pyenv#python-versions-with-extended-support

**Comment by macserv** [comment]
> About 3.7.6, it doesn't support MacOS 11+.

How did you arrive at that assessment?  The link you provided includes the following scenarios:

- `3.7.8-3.7.15`, `3.8.4-3.8.12`, and `3.9.0-3.9.7` when using Xcode 13.3
- `3.5.10` and `3.6.15` when using macOS 11+ and Xcode 13.3
- `2.7.18` when using macOS 10.15+ on an Apple Silicon Mac

None of these apply to version `3.7.6`.

**Comment by native-api** [comment]
[The patches to 3.7.x were only applied to versions that support MacOS 11+](https://github.com/pyenv/pyenv/pull/2344).

**Comment by macserv** [comment]
> [The patches to `3.7.x-3.9.x` were only applied to versions that support MacOS 11+](https://github.com/pyenv/pyenv/pull/2344).

I think I understand that much, but apparently I'm missing something... if you could please clarify just a bit more for me, it would be helpful.

Here's where I'm hung up:
1. I don't see a patch for `3.7.6`... the patches seem to begin at `3.7.8`.
2. Do those patches apply beyond Xcode **13.3**?  @Aya-Yang is using Xcode **14.1** or **14.2**, based on their `clang` version.

**Comment by native-api** [comment]
> > [The patches to `3.7.x-3.9.x` were only applied to versions that support MacOS 11+](https://github.com/pyenv/pyenv/pull/2344).
> 
> I think I understand that much, but apparently I'm missing something... if you could please clarify just a bit more for me, it would be helpful.
> 
> Here's where I'm hung up:
> 
>     1. I don't see a patch for `3.7.6`... the patches seem to begin at `3.7.8`.
> 

XCode 13.3 was introduced in MacOS 12. So there's no point to support it in versions that don't support even MacOS 11.

>     2. Do those patches apply beyond Xcode **13.3**?  @Aya-Yang is using Xcode **14.1** or **14.2**, based on their `clang` version.

Those patches address an incompatible change in XCode 13.3. So they would apply indefinitely until there are further incompatible changes in some future version of XCode.
