### ISSUE TITLE
BUILD FAILED because of modules & configure: error: GNU readline is not installed.

### ISSUE THREAD

**Issue by PierreP94** [pyenv/pyenv#2881]
### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
* [X] Make sure your problem is not derived from plugins.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 22.04.3 LTS
- [X] OS architecture (e.g. amd64): AMD64
- [X] pyenv version: pyenv 2.3.35
- [X] Python version: any
- [X] C Compiler information (e.g. gcc 7.3): gcc version 11.4.0
- [X] Please attach the debug trace of the failing command as a gist:
  * 'env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
  
[trace.log](https://github.com/pyenv/pyenv/files/13845376/trace.log)

- [X] If you have a problem with installing Python, please also attach `config.log` from the build directory
- 
[config.log](https://github.com/pyenv/pyenv/files/13845413/config.log)

It seems that pyenv doesn't find my modules and so it's impossible to install any version of Python
I have also tried pyenv doctor:

````
Cloning /home/moi/.pyenv/plugins/pyenv-doctor/bin/.....
Installing python-pyenv-doctor...

BUILD FAILED (Ubuntu 22.04 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20240105193713.110828
Results logged to /tmp/python-build.20240105193713.110828.log

Last 10 log lines:
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc accepts -g... yes
checking for /usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc option to accept ISO C89... none needed
checking for rl_gnu_readline_p in -lreadline... no
configure: error: GNU readline is not installed.
Problem(s) detected while checking system.

See https://github.com/pyenv/pyenv/wiki/Common-build-problems for known solutions.
````

Thanks for any help

**Comment by native-api** [comment]
The cause is Pyenv doesn't use Homebrew in Linux. We're going to make an exception to that if Pyenv itself is installed with Homebrew.

As a workaround, you can either install the build dependencies with the system's package manager as per the README, or set the compiler flags to link against the Homebrew-provided libs manually.

**Comment by aliahadmd** [comment]
Before install pyenv , Run these command

step 1. Check Dependencies:
`sudo apt-get install -y build-essential zlib1g-dev libffi-dev libssl-dev liblzma-dev libbz2-dev libreadline-dev libsqlite3-dev`

step 2: necessary Tkinter dependencies:
`sudo apt-get install tk-dev`

**Comment by PierreP94** [comment]
> The cause is Pyenv doesn't use Homebrew in Linux. We're going to make an exception to that if Pyenv itself is installed with Homebrew.
> 
> As a workaround, you can either install the build dependencies with the system's package manager as per the README, or set the compiler flags to link against the Homebrew-provided libs manually.

> Before install pyenv , Run these command
> 
> step 1. Check Dependencies: `sudo apt-get install -y build-essential zlib1g-dev libffi-dev libssl-dev liblzma-dev libbz2-dev libreadline-dev libsqlite3-dev`
> 
> step 2: necessary Tkinter dependencies: `sudo apt-get install tk-dev`

I have already installed all dependencies using apt and also using aptitude (a post was advising it)
I have also tried :
- Automatic install
- Manual install
- Homebrew install
- Snap install (it's an edge version)

All library and modules are installed but still pyenv (and so pyenv doctor) doesn't manage to find them

**Comment by PierreP94** [comment]
Well my problem isn't solved. Pyenv doesn't manage to find modules however I'm trying to install it.
Maybe it's possible to specify location somewhere ?

**Comment by native-api** [comment]
> configure: error: C compiler cannot create executables
> See `config.log' for more details.

This error means that you are passing invalid compiler flags in `*FLAGS` envvars. As the message says, `config.log` has the specific invocation and the error message returned by the compiler.

---

I suggest you unset all compiler-affecting envvars to eliminate them as potential cause. Pyenv is designed to not need any custom envvars set in common use cases.

**Comment by native-api** [comment]
> checking for gcc... /usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc

You are also using a custom compiler (probably built from source). It also might be a cause of malfunctions.

**Comment by PierreP94** [comment]
Ho my god !
I have just used :
`unset CC CXX CFLAGS LDFLAGS CPPFLAGS
`
and it's perfectly working.
Thank you very much for help
