### ISSUE TITLE
Having Success in installing python 3.9.x but not versions >=3.10.x getting an error stating error installing pip

### ISSUE THREAD

**Issue by native-api** [pyenv/pyenv#2883]
### Discussed in https://github.com/orgs/pyenv/discussions/2882

<div type='discussions-op-text'>

<sup>Originally posted by **bnaoe** January  6, 2024</sup>
I've been having success installing 3.9.x python versions with pyenv-win, but when I try to install versions >= 3.10.x I get the same error message. I'm wondering if anybody has experienced this and how it was resolved. Thank you. 

Please see examples below.

pyenv install 3.10.0
:: [Info] ::  Mirror: https://www.python.org/ftp/python
:: [Installing] ::  3.10.0 ...
:: [Error] :: error installing pip.
:: [Error] :: couldn't install 3.10.0

pyenv install 3.11.0
:: [Info] ::  Mirror: https://www.python.org/ftp/python
:: [Installing] ::  3.11.0 ...
:: [Error] :: error installing pip.
:: [Error] :: couldn't install 3.11.0
 </div>

**Comment by native-api** [comment]
@bnaoe Please add the necessary disgnostic information as per the issue template.

**Comment by cmal** [comment]
checking for long double... yes
checking size of long double... configure: error: in `/var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874/Python-3.10.4':
configure: error: cannot compute sizeof (long double)
See `config.log' for more details
++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:786): build_package_standardreturn 1
++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:789): build_package_standardmake -j 10
make: *** No targets specified and no makefile found.  Stop.
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:749): build_package_standarbuild_failed

+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:126): build_failed(): echo
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:127): build_failed(): colorize 1 'BUILD FAILED'
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:91): colorize(): '[' -t 1 ']'
BUILD FAILED+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:91): colorize(): printf '\e[%sm%s\e[m' 1 'BUILD FAILED'
++++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:128): build_failed(): os_information
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by python configure 3.10, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --prefix=/Users/yuzhao/.pyenv/versions/3.10.4 --libdir=/Users/yuzhao/.pyenv/versions/3.10.4/lib --with-openssl=/opt/homebrew/opt/openssl@1.1

## --------- ##
## Platform. ##
## --------- ##

hostname = YudeMBP202114.local
uname -m = arm64
uname -r = 23.0.0
uname -s = Darwin
uname -v = Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000

/usr/bin/uname -p = arm
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
         Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Kernel configured for up to 10 processors.
10 processors are physically available.
10 processors are logically available.
Processor type: arm64e (ARM64E)
Processors active: 0 1 2 3 4 5 6 7 8 9
Primary memory available: 32.00 gigabytes
Default processor set: 715 tasks, 4790 threads, 10 processors
Load average: 3.16, Mach factor: 6.83
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/Cellar/pyenv/2.3.2/libexec
PATH: /usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin
PATH: /usr/local/Cellar/pyenv-virtualenv/1.1.5/shims
PATH: /Users/yuzhao/.pyenv/shims
PATH: /opt/homebrew/opt/texinfo/bin
PATH: /opt/homebrew/Cellar/llvm@12/12.0.1_1/bin
PATH: /Users/yuzhao/.ghcup/bin
PATH: /opt/homebrew/opt/gradle@6/bin
PATH: /Applications/Mathematica.app/Contents/MacOS/
PATH: /Users/yuzhao/.yarn/bin
PATH: /usr/local/opt/qt/bin
PATH: /usr/local/sbin
PATH: /usr/local/opt/icu4c/sbin
PATH: /usr/local/opt/icu4c/bin
PATH: /Users/yuzhao/.asdf/shims
PATH: /opt/homebrew/opt/asdf/libexec/bin
PATH: /Users/yuzhao/.sdkman/candidates/springboot/current/bin
PATH: /Users/yuzhao/.nvm/versions/node/v18.18.0/bin
PATH: /opt/homebrew/bin
PATH: /opt/homebrew/sbin
PATH: /usr/local/bin
PATH: /System/Cryptexes/App/usr/bin
PATH: /usr/bin
...skipping...
RUNSHARED=''
SED='/opt/homebrew/bin/gsed'
SHELL='/bin/sh'
SHLIBS=''
SHLIB_SUFFIX=''
SOABI=''
SOVERSION='1.0'
SRCDIRS=''
STATIC_LIBPYTHON=''
TCLTK_INCLUDES=''
TCLTK_LIBS=''
TEST_MODULES=''
THREADHEADERS=''
TRUE=''
TZPATH=''
UNIVERSALSDK=''
UNIVERSAL_ARCH_FLAGS=''
VERSION='3.10'
WHEEL_PKG_DIR=''
_PYTHON_HOST_PLATFORM=''
ac_ct_AR='ar'
ac_ct_CC='clang'
ac_ct_CXX=''
ac_ct_READELF=''
bindir='${exec_prefix}/bin'
build='aarch64-apple-darwin23.0.0'
build_alias=''
build_cpu='aarch64'
build_os='darwin23.0.0'
build_vendor='apple'
datadir='${datarootdir}'
++++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:97): os_information(): type -p lsb_release
++++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:99): os_information(): type -p sw_vers
+++++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:100): os_information(): sw_vers -productVersion
++++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:100): os_information(): echo 'OS X 14.0'
++++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:128): build_failed(): version
++++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:1933): version(): local git_revision
++++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:1935): version(): GIT_DIR=/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/../../../.git
++++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:1935): version(): git remote -v
++++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:1935): version(): grep -q /pyenv
++++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:1939): version(): echo 'python-build 20180424'
 (OS X 14.0 using python-build 20180424)
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:128): build_failed(): echo ' (OS X 14.0 using python-build 20180424)'

+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:129): build_failed(): echo
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:131): build_failed(): rmdir /var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874
Inspect or clean up the working tree at /var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:132): build_failed(): echo 'Inspect or clean up the working tree at /var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874'
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:135): build_failed(): file_is_not_empty /var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874.log
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:146): file_is_not_empty(): local filename=/var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874.log
++++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:147): file_is_not_empty():wc -l /var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874.log
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:147): file_is_not_empty(): local 'line_count=     487 /var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874.log'
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:149): file_is_not_empty(): '[' -n '     487 /var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874.log' ']'
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:150): file_is_not_empty(): words=($line_count)
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:151): file_is_not_empty(): '[' 487 -gt 0 ']'
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:136): build_failed(): colorize 33 'Results logged to /var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874.log'
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:91): colorize(): '[' -t 1 ']'
Results logged to /var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874.log+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:91): colorize(): printf '\e[%sm%s\e[m' 33 'Results logged to /var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874.log'


+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:137): build_failed(): printf '\n\n'
Last 10 log lines:
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:138): build_failed(): echo 'Last 10 log lines:'
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:139): build_failed(): tail -n 10 /var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874.log
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:147): file_is_not_empty(): local 'line_count=     487 /var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874.log'
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:149): file_is_not_empty(): '[' -n '     487 /var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874.log' ']'
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:150): file_is_not_empty(): words=($line_count)
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:151): file_is_not_empty(): '[' 487 -gt 0 ']'
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:136): build_failed(): colorize 33 'Results logged to /var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874.log'
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:91): colorize(): '[' -t 1 ']'
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:91): colorize(): printf '\e[%sm%s\e[m' 33 'Results logged to /var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874.log'
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:137): build_failed(): printf '\n\n'
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:138): build_failed(): echo 'Last 10 log lines:'
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:139): build_failed(): tail -n 10 /var/folders/m_/3vpp84050q93nxw4d03dxvzh0000gn/T/python-build.20240118143045.42874.log
+++(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:142): build_failed(): exit 1
+(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/python-build:2298): build_failed(): kill 42904
+(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/pyenv-install:248): STATUS=1
+(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/pyenv-install:251): '[' 1 == 2 ']'
+(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/pyenv-install:279): '[' 1 == 0 ']'
+(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/pyenv-install:282): cleanup
+(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/pyenv-install:241): cleanup(): '[' -z '' ']'
+(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/pyenv-install:241): cleanup(): rm -rf /Users/yuzhao/.pyenv/versions/3.10.4
+(/usr/local/Cellar/pyenv/2.3.2/plugins/python-build/bin/pyenv-install:285): exit 1
