### ISSUE TITLE
pyenv shims break vim Python

### ISSUE THREAD

**Issue by jeffmelville** [pyenv/pyenv#2889]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* x[ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- Platform: Ubuntu 20.04
- Architecture: amd64
- pyenv version: 2.3.21
- Python version: 3.9.17
- Compiler: gcc 9.4.0 

When pyenv shims are in the path, vim compiled with python3 support fails to run any Python commands.  This happened with both the system installed vim package (Ubuntu 20.04) and a manually compiled version of vim 8.2 (pointed to system Python)

To reproduce:
- In vim, run ``:python3 import sys; print(sys.version)``

With pyenv shims in path:
```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
 Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
PYTHONHOME = (not set)
 PYTHONPATH = (not set)
 program name = 'python3'
  isolated = 0
environment = 1
  user site = 1
sys._base_executable = '/home/jmelville/.pyenv/shims/python3'
sys.base_prefix = '/tmp/build/80754af9/python_1599203911753/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho'
sys.base_exec_prefix = '/tmp/build/80754af9/python_1599203911753/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold sys.executable = '/home/jmelville/.pyenv/shims/python3'
sys.prefix = '/tmp/build/80754af9/python_1599203911753/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho'
sys.exec_prefix = '/tmp/build/80754af9/python_1599203911753/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho'
sys.path = [
 '/tmp/build/80754af9/python_1599203911753/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python38.zip',
'/tmp/build/80754af9/python_1599203911753/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8',
'/tmp/build/80754af9/python_1599203911753/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/lib-dynload',

                           ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
 ModuleNotFoundError: No module named 'encodings'
Current thread 0x00007fc237317a80 (most recent call first):
 <no Python frame>
```

Without pyenv shims in the path, I get the expected printout from ``sys.version()`` for system Python.

**Comment by native-api** [comment]
This has to be connected to the way Vim locates the Python to use.
Pyenv tries to not be intrusive. E.g. it doesn't change LD_LIBRARY_PATH so if a program is e.g. linked against system `libpython`, it should not be affected.

**Comment by native-api** [comment]
WFM in 20.04 Docker.
Regardless of what I select with Pyenv, it prints

```
3.8.10 (default, Nov 22 2023, 10:22:35)
[GCC 9.4.0]
```
which is the system Python.

---

Do you have some Vim customizations connected to how it searches for Python?
