### ISSUE TITLE
pyenv: cannot rehash: ~/.pyenv/shims/.pyenv-shim exists on startup

### ISSUE THREAD

**Issue by rsantellan** [pyenv/pyenv#2893]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): LMDE 6 (Linux Mint Debian Edition)
- [X] OS architecture (e.g. amd64): amd64
- [X] pyenv version:  pyenv 2.3.32
- [X] Python version: Python 3.11.2
- [X] C Compiler information (e.g. gcc 7.3):  gcc (Debian 12.2.0-14) 12.2.0
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [ ] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

My problem is at startup it takes a really long time to open a terminal, I have guake installed and it shows:

`pyenv: cannot rehash: ~/.pyenv/shims/.pyenv-shim exists`

This is fairly common at powering on the computer, it freeze everything and the I see that error, I can't find any other error.

I thought it was this issue: [2829](https://github.com/pyenv/pyenv/issues/2829#issuecomment-1918317462) but no

**Comment by native-api** [comment]
I was able to reproduce the issue, but when I added

```bash
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -x
```

near the start of `~/.bashrc` to diagnose it, the problem disappeared.

**Comment by native-api** [comment]
I was able to reproduce the issue, but when I added

```
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -x
```

to `~/.bashrc` after the `case $- in <...> esac` part, it went away.

If this happens for you consistently, could you add the above lines, too, and show the resulting tracelog?

This seems to be connected with Guake's session restoration logic. Try disabling that option in its settings and see if that removes the problem.

**Comment by rsantellan** [comment]
Hi @native-api I have disable Guake's session restoration, I will see if is that first and then try the bashrc.

Thanks

**Comment by rsantellan** [comment]
After disabling Guake's session restoration everything work as expected. Thanks @native-api
