### ISSUE TITLE
Python versions with different patch numbers do not work

### ISSUE THREAD

**Issue by stigsanek** [pyenv/pyenv#2894]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS Sonoma 14.3 (23D56)
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 2.3.35
- [x] Python version: 3.8.17
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 15.0.0 (clang-1500.1.0.2.5)
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

I ran `pyenv install 3.8.18`.
After successful installation, I ran `pyenv local 3.8.18` in the `/Users/xxx/xxx/Projects` folder. Everything worked fine.
A few weeks later I also needed version `3.8.17`.
I ran `pyenv install 3.8.17`. After successful installation, I ran `pyenv local 3.8.17` already in another folder `/Users/xxx/Projects`.
When I run `pyenv versions` in this folder, I get a response that `3.8.17` is selected, but when I do `python --version` I get `3.8.18`.
I decided to uninstall `3.8.18` and did `pyenv uninstall 3.8.18`.
This way I only have `system` and `3.8.17` on my system.
Now when I do `python --version` in the `/Users/xxx/Projects` folder, I get an error:

```
Library not loaded: /Users/aleksandregorov/.pyenv/versions/3.8.18/lib/libpython3.8.dylib
Referenced from: <120C8B80-012B-3016-9CC7-6717BDFDA264> /Users/aleksandregorov/.pyenv/versions/3.8.17/bin/python3.8
Reason: tried: '/Users/aleksandregorov/.pyenv/versions/3.8.18/lib/libpython3.8.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/aleksandregorov/.pyenv/versions/3.8.18/lib/libpython3.8.dylib' (no such file), '/Users/aleksandregorov/.pyenv/versions/3.8.18/lib/libpython3.8.dylib' (no such file)
```

I have also tried doing `pyenv rehash`, but that doesn't solve the problem. To make it work, I now have to uninstall `3.8.17` and reinstall it.
But I don't understand why I have 2 versions that differ only in patch number not working together.
[trace.log](https://github.com/pyenv/pyenv/files/14120986/trace.log)

**Comment by native-api** [comment]
Do you have any envvars set that affect the linker (or did you during 3.8.17 installation)? It looks like `LD_FLAGS` or `LD_LIBRARY_PATH` was manually  set at the time of that build, pointing to 3.8.18, causing `python` from 3.8.17 to be linked against `libpython` from 3.8.18.

Can you reproduce the problem by installing these two versions again? If you can, please attach the trace logs and `config.log`'s from those two installations.

**Comment by stigsanek** [comment]
You are right, `LDFLAGS` and `CPPFLAGS` were set in `.zshrc`. After I removed them, everything worked the first time. Thanks for your help, I will close the problem.
