### ISSUE TITLE
"internal compiler error: Segmentation fault" WSL Ubuntu

### ISSUE THREAD

**Issue by carterdr** [pyenv/pyenv#2896]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information: Ubuntu 22.04
- [x] OS architecture: amd64
- [x] pyenv version: 2.3.35
- [x] Python version: 3.12.1 but other versions wont install as well
- [x] C Compiler information: gcc 11.4.0 
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

trace.log:
[python-build.20240205221832.684.log](https://github.com/pyenv/pyenv/files/14174270/python-build.20240205221832.684.log)
config.log:
[config.log](https://github.com/pyenv/pyenv/files/14174277/config.log)

**Comment by carterdr** [comment]
I reinstalled windows and then tried to install python again with pyenv and it still fails.

**Comment by native-api** [comment]
This is an internal compiler error. Try a different compiler version.

```
gcc -c -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall    -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal  -I. -I./Include -I/home/carter/.pyenv/versions/3.12.1/include -I/home/carter/.pyenv/versions/3.12.1/include -fPIC -DPy_BUILD_CORE -o Objects/typevarobject.o Objects/typevarobject.c
<...>
during GIMPLE pass: modref
Objects/typevarobject.c: In function ‘typealias_new_impl’:
Objects/typevarobject.c:1691:1: internal compiler error: Segmentation fault
 1691 | }
      | ^
```

**Comment by belinux** [comment]
I had the same issue as mentioned in #2905 and it seems that my case it's related to system instability, I forced lowered the speed on my bios (just by disabling "Intel Turbo", I know I have to manual tune voltages and stuff if I don't want to run a potato, but I'll do it eventually) and that did the fix..

**Comment by carterdr** [comment]
> I had the same issue as mentioned in #2905 and it seems that my case it's related to system instability, I forced lowering the cpu speed on my bios (just by disabling "Intel Turbo", I know I have to manual tune voltages and stuff if I don't want to run a potato, but I'll do it eventually) and that did the fix.. 

My cpu is overclocked so it's probably the same issue. I ended up just using windows pyenv and not using wsl.

**Comment by native-api** [comment]
I'm a professional IT admin, and this is exactly why I never use overclocking...

**Comment by lukepopp** [comment]
hey just wanted to add to this - I also experienced this on Windows 11 - WSL - i9 14900k.  The culprit was the default motherboard setting "asus multicore enhancement"  which is enabled by default.  Changing this to _disabled_ solved the problem.  However, I never experienced a crash in Windows with this setting on and that included running cinebench, VR workloads, and compiling with Visual Studio 2022.
