### ISSUE TITLE
3.12.2 not in install list

### ISSUE THREAD

**Issue by Xarmer** [pyenv/pyenv#2901]
![image](https://github.com/pyenv/pyenv/assets/126620895/1d76ed14-63d4-406b-8b3e-de403f4dd716)

**Comment by ThiefMaster** [comment]
https://i.imgflip.com/8f3shi.jpg

(sorry, just had to! but that meme aside, 3.12.2 support would be very much appreciated! :))

**Comment by apfromiit** [comment]
Two new versions of python were released on 6 February 2024 - 3.12.2 and 3.11.8

https://www.python.org/doc/versions/

Please support both versions.

**Comment by kevinbowen777** [comment]
FYI. The pull requests for both versions #2898 and #2899 have both passed their checks and are in the queue to be merged.

**Comment by native-api** [comment]
> FYI. The pull requests for both versions #2898 and #2899 have both passed their checks and are in the queue to be merged.

Done and done! :muscle:

**Comment by apfromiit** [comment]
when shall we expect the next release containing these new python versions?

**Comment by ThiefMaster** [comment]
@apfromiit you just need to run `pyenv update` to update your existing pyenv

**Comment by apfromiit** [comment]
@ThiefMaster I tried upgrading pyenv with **`brew upgrade pyenv`** and it fetches the current latest version of **`2.3.35`** which don't have this change. 

Running **`pyenv update`** throws `no such command 'update'`

**Comment by gfpacheco** [comment]
@apfromiit apparently that's [a plugin](https://github.com/pyenv/pyenv-update), but installing and running `pyenv update` doesn't do anything. Still waiting for a way to install python 3.12.2 using pyenv

**Comment by gfpacheco** [comment]
@apfromiit I added [the 3.12.2 file](https://github.com/pyenv/pyenv/pull/2899) manually to my pyenv folder and it was able to install it no problem (I use mac):

`/opt/homebrew/Cellar/pyenv/2.3.35/plugins/python-build/share/python-build/3.12.2`
```
prefer_openssl3
export PYTHON_BUILD_CONFIGURE_WITH_OPENSSL=1
install_package "openssl-3.2.1" "https://www.openssl.org/source/openssl-3.2.1.tar.gz#83c7329fe52c850677d75e5d0b0ca245309b97e8ecbcfdc1dfdc4ab9fac35b39" mac_openssl --if has_broken_mac_openssl
install_package "readline-8.2" "https://ftpmirror.gnu.org/readline/readline-8.2.tar.gz#3feb7171f16a84ee82ca18a36d7b9be109a52c04f492a053331d7d1095007c35" mac_readline --if has_broken_mac_readline
if has_tar_xz_support; then
    install_package "Python-3.12.2" "https://www.python.org/ftp/python/3.12.2/Python-3.12.2.tar.xz#be28112dac813d2053545c14bf13a16401a21877f1a69eb6ea5d84c4a0f3d870" standard verify_py312 copy_python_gdb ensurepip
else
    install_package "Python-3.12.2" "https://www.python.org/ftp/python/3.12.2/Python-3.12.2.tgz#a7c4f6a9dc423d8c328003254ab0c9338b83037bd787d680826a5bf84308116e" standard verify_py312 copy_python_gdb ensurepip
fi
```

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/releases/tag/v2.3.36

**Comment by native-api** [comment]
> @apfromiit apparently that's [a plugin](https://github.com/pyenv/pyenv-update), but installing and running `pyenv update` doesn't do anything. Still waiting for a way to install python 3.12.2 using pyenv

[If you've installed Pyenv with Homebrew, you need to switch to HEAD to be able to update to the latest head without waiting for a release](https://github.com/pyenv/pyenv?tab=readme-ov-file#upgrading-with-homebrew).

**Comment by bcrotty** [comment]
@native-api Brew updated my pyenv to 2.3.36, and it still lists 3.12.1 as the latest. I tried uninstalling pyenv and using the `--head` flag to reinstall. It still gave me pyenv 2.3.36, and I still see 3.12.1 as the latest. Anything else I can try? I'm checking for latest with:
`pyenv latest 3.12`
