### ISSUE TITLE
curl: (22) The requested URL returned error: 503 when trying to download Python-3.8.18.tar.xz

### ISSUE THREAD

**Issue by damascene** [pyenv/pyenv#2902]
I'm trying to install python 3.8 on my device but it seems the link is broken.

```bash
$ pyenv install 3.8
Downloading Python-3.8.18.tar.xz...
-> https://www.python.org/ftp/python/3.8.18/Python-3.8.18.tar.xz
error: failed to download Python-3.8.18.tar.xz

BUILD FAILED (Ubuntu 22.04 using python-build 20180424)

Results logged to /tmp/python-build.20240213120616.212783.log

Last 10 log lines:
/tmp/python-build.20240213120616.212783 ~/dev/face_stuff/happy
curl: (22) The requested URL returned error: 503

```

seems there is an issue in the host link:
https://www.python.org/ftp/python/3.8.18/Python-3.8.18.tar.xz

When I access the url directly I get this in the browser

```text
Error 503 Backend is unhealthy

Backend is unhealthy
Error 54113

Details: cache-sof1510022-SOF 1707815769 4144013172

Varnish cache server
```

I'm able to download other packages in the parent directory:
https://www.python.org/ftp/python/3.8.18/

.tgz version of the file seems downloadable. Reporting this here as it effects Pyenv

**Comment by native-api** [comment]
Seems to work now.

Pyenv is programmed to use the mirror at https://pyenv.github.io/pythons/ which we can populate if an official source becomes unreliable, but let's hope we'd not have to resort to that.
