### ISSUE TITLE
BUILD FAILED with or without using brew on WSL2

### ISSUE THREAD

**Issue by trevorpfiz** [pyenv/pyenv#2913]
https://github.com/pyenv/pyenv/pull/2906#issuecomment-1968173539

the build also fails if I install with `curl https://pyenv.run | bash`. only solution I have found is [this](https://github.com/pyenv/pyenv/issues/950#issuecomment-1352679244), but 3.11 and 3.12 builds still fail with:

```
CFLAGS=-I$(pwd)/include LDFLAGS=-L$(pwd) ~/.pyenv/bin/pyenv install 3.11
Downloading Python-3.11.8.tar.xz...
-> https://www.python.org/ftp/python/3.11.8/Python-3.11.8.tar.xz
Installing Python-3.11.8...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/spark/.pyenv/versions/3.11.8/lib/python3.11/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/home/spark/.pyenv/versions/3.11.8/lib/python3.11/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/spark/.pyenv/versions/3.11.8/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
WARNING: The Python tkinter extension was not compiled and GUI subsystem has been detected. Missing the Tk toolkit?
Installed Python-3.11.8 to /home/spark/.pyenv/versions/3.11.8
```

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu Linux 20.04
- [ ] OS architecture (e.g. amd64): x86_64
- [ ] pyenv version: pyenv 2.3.36
- [ ] Python version: Python 3.12.2
- [ ] C Compiler information (e.g. gcc 7.3): gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
- [ ] Please attach the debug trace of the failing command as a gist: https://gist.github.com/trevorpfiz/701ba35c060cd21f3b69bc34b00bfab7
- [ ] If you have a problem with installing Python, please also attach `config.log` from the build directory
  https://gist.github.com/trevorpfiz/f0e064f58497ab242e5f9c127b246af2

**Comment by ajgringo619** [comment]
Your build didn't fail, it was just built without tkinter and sqlite3 support. `pyenv versions` should show an installed v3.11.8.

**Comment by trevorpfiz** [comment]
> Your build didn't fail, it was just built without tkinter and sqlite3 support. `pyenv versions` should show an installed v3.11.8.

you are right. I reset things and am using Oh My Zsh now. things are working now and I don't know why. can't confirm if brew works now or not.

**Comment by quroom** [comment]
You can install tk-dev, It makes solving problem.
```sudo apt-get install tk-dev```
