### ISSUE TITLE
pyenv fails to install Python 3.12.1/3.12.2 on Raspberry Pi Zero 2W running Bullseye Lite 64-Bit

### ISSUE THREAD

**Issue by neuron-whisperer** [pyenv/pyenv#2923]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): Debian GNU/Linux 11 (bullseye) Lite
- [X] OS architecture (e.g. amd64): 64-bit ARM
- [X] pyenv version: 2.3.36
- [X] Python version: n/a
- [X] C Compiler information (e.g. gcc 7.3): 10.2.1 20210110
- [X] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

Not possible - see below.

Problem: pyenv hangs on building Python 3.12.2, 3.12.1, and likely earlier versions on Raspberry Pi Zero 2W + Debian Bullseye Lite 64-bit.

The specific problem is that pyenv permanently hangs upon while trying to compile compile.c. It appears to hit a roadblock with this file every time. During the hang, the LED on the RPi blinks solid-on and mostly-off at a steady rate of about 1Hz. The device can be pinged, but refuses additional SSH connections. I've waited upwards of two hours with the device processing compile.c, with zero indication of progress. The build process cannot be terminated; the device must be hard-reset to become responsive again.

I've used this exact same setup on the same device, running hte 32-bit version of Debian Bullseye Lite, to install Python 3.12.2, 3.12.1, and other versions. No problems there.

One possibility is that compiling the 64-bit version of Python is causing the RPi to run out of memory. (Storage isn't a problem - the device is using a mostly-empty 16gb micro SD card and reports about 15 gb free.)

**Comment by neuron-whisperer** [comment]
I've run it again with verbose output and have attached the results to this comment.

The RPi has been stuck at the last line for about three hours, just endlessly blinking at about 1 Hz.
[log.txt](https://github.com/pyenv/pyenv/files/14532530/log.txt)

**Comment by native-api** [comment]
For starters, I suggest you to reduce the number of parallel Make tasks with `export PYTHON_MAKE_FLAGS="-j<number>"`. Raspberry Pi Zero 2W has 4 cores but ony 512 MB of memory -- so you may well be experiencing excessive swapping.

**Comment by Choo57** [comment]
Anyone managed to get this working? I also have the exact same issue. Will try make -f 2 shortly instead of 4.. Also saw on a couple of forms that 3.12.0 works but not sure if they also had the 64bit OS, so will probably try that as well if make -f 2 fails

**Comment by Choo57** [comment]
increased swap to 6011 MB, ran make -f 2 and it worked smoothly.
