### ISSUE TITLE
ginstall: cannot stat 'Modules/readline.cpython-312-darwin.so': No such file or directory

### ISSUE THREAD

**Issue by cxyfreedom** [pyenv/pyenv#2933]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS Sonoma 14.1.1
- [x] OS architecture (e.g. amd64): arm64
- [x] pyenv version: 2.3.36
- [x] Python version: 3.12.0
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 15.0.0 (clang-1500.3.9.4)

debug info(contains `attact.log` and `config.log`: [https://gist.github.com/cxyfreedom/c5c9931608e86ac4fa9e00e7133b7f6e](https://gist.github.com/cxyfreedom/c5c9931608e86ac4fa9e00e7133b7f6e)

**Comment by native-api** [comment]
Please add the necessary diagnostic information as per the issue template.

**Comment by native-api** [comment]
In the log, I see a completely different error:
```
configure: error: C compiler cannot create executables
```

```
configure:5099: checking whether the C compiler works
configure:5121: clang -I/usr/local/opt/openssl@3/include -I/usr/local/opt/readline/include -I/usr/local/opt/gettext/include -I/usr/local/opt/xz/include  -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/readline/include -I/usr/local/var/pyenv/versions/3.12.0/include --I/usr/local/opt/ruby/include -I/usr/local/opt/openssl@3/include -I/usr/local/opt/readline/include -I/usr/local/opt/gettext/include -I/usr/local/opt/xz/include -I/opt/homebrew/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/readline/lib -L/usr/local/var/pyenv/versions/3.12.0/lib -Wl,-rpath,/usr/local/var/pyenv/versions/3.12.0/lib -L/usr/local/opt/ruby/lib -L/usr/local/opt/openssl@3/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/xz/lib -L/opt/homebrew/lib -Wl,-rpath,/opt/homebrew/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib conftest.c -L/usr/local/var/pyenv/versions/3.12.0/lib -Wl,-rpath,/usr/local/var/pyenv/versions/3.12.0/lib -L/opt/homebrew/lib -Wl,-rpath,/opt/homebrew/lib >&5
clang: error: unsupported option '--I/usr/local/opt/ruby/include'
configure:5125: $? = 1
```

The cause is an incorrect compiler option in an envvar.
For starters, clear all the compiler-affecting envvars. Pyenv is designed to not need them in non-custom setups.
