### ISSUE TITLE
[Workaround] Debian/Ubuntu - TKInter module fails to build even if tk-dev is installed

### ISSUE THREAD

**Issue by shinji257** [pyenv/pyenv#2934]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): Debian 12 (Bookworm) on WSL 2
- [X] OS architecture (e.g. amd64): amd64
- [X] pyenv version: 2.3.36
- [X] Python version: N/A (tested 3.11.8)
- [X] C Compiler information (e.g. gcc 7.3): brew gcc 13.2.0, system gcc 12.2.0

This is more of a tip here.  If you are on Debian or Ubuntu and it is failing to build the TKinter package even though you have the dependent dev package installed then it is because pkg-config does not have the required information for Python to find it.  This was discovered while scanning the build log as it showed tkinter missing when doing the configure pass.

Workaround:
Execute these prior to install a python version if you are getting the issue.
```
export TCLTK_LIBS="-ltk8.6 -ltkstub8.6 -ltcl8.6"
export TCLTK_CFLAGS="-I/usr/include/tcl8.6"
```

If you brew instead on linux (like I have for a few things) then you won't have this issue.  It will use the tcl-tk build provided by brew instead and it is detected without issue.

Make sure you are following the suggested build environment.  If you go the route of using brew on linux then use the brew package list for Mac OS X but you can skip xcode.

**Comment by native-api** [comment]
Cannot reproduce in a fresh Debian 12 VM with installed dependencies as per https://github.com/pyenv/pyenv/wiki#suggested-build-environment .

Attached my [trace.log](https://github.com/pyenv/pyenv/files/14948834/trace.log), you could e.g. use that to look for discrepancies.
