### ISSUE TITLE
New release? (2.3.37)

### ISSUE THREAD

**Issue by DavidCain** [pyenv/pyenv#2935]
pyenv recently added support for Python's recent security patches of 3.8, 3.9, and 3.10:
- https://github.com/pyenv/pyenv/pull/2929
- https://github.com/pyenv/pyenv/pull/2930

It would be great if the latest release of pyenv supported these versions.
Is a new release possible? The most recent, 2.3.36, is from February.

Thanks!

**Comment by tmaher** [comment]
and CPython 3.11.9 - https://github.com/pyenv/pyenv/pull/2938

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/releases/tag/v2.4.0

**Comment by native-api** [comment]
Created a pinned discussion to figure out a desirable release schedule: https://github.com/orgs/pyenv/discussions/2940

**Comment by DavidCain** [comment]
Thank you!!
