### ISSUE TITLE
Build failed at interpreteridobject.c:109:40 (macOS / arm64 / clang)

### ISSUE THREAD

**Issue by thomasbreydo** [pyenv/pyenv#2943]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): OS X 14.4.1
- [x] OS architecture (e.g. amd64): arm64
- [x] pyenv version:  2.4.0
- [x] Python version: 3.12 (but same issue holds for 3.11, 3.10, 3.9, and likely others)
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 15.0.0 (clang-1500.3.9.4)
- [x] Please attach the debug trace of the failing command as a gist: [trace.log](https://gist.github.com/thomasbreydo/2cf1871d2bf8e312e3b3eff0782f8334)
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory: [config.log](https://gist.github.com/thomasbreydo/21182f716853c29757870b41ac5c8dbe)
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`. 

Hi! **For some reason, pyenv's builds are failing for 3.12** (and every other version I tried, 3.9, 3.10, 3.11)

I've spent a few hours browsing the internet and the Github issues but I can't find a similar issue. Thank you so much.

Here are the logs (also linked above):
- [trace.log](https://gist.github.com/thomasbreydo/2cf1871d2bf8e312e3b3eff0782f8334)
- [config.log](https://gist.github.com/thomasbreydo/21182f716853c29757870b41ac5c8dbe)

Here's the error:

```txt
clang -c -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -I/opt/homebrew/include -I/opt/homebrew/include   -I/opt/homebrew/include -I/opt/homebrew/include  -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal  -I. -I./Include -I/opt/homebrew/opt/ncurses/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/readline/include -I/Users/thomasbreydo/.pyenv/versions/3.12.2/include  -I/opt/homebrew/include -I/opt/homebrew/include -I/opt/homebrew/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/ncurses/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/readline/include -I/Users/thomasbreydo/.pyenv/versions/3.12.2/include  -I/opt/homebrew/include -I/opt/homebrew/include -I/opt/homebrew/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include  -DPy_BUILD_CORE -o Objects/iterobject.o Objects/iterobject.c
Objects/interpreteridobject.c:109:40: error: expected ')'
    return PyUnicode_FromFormat("%s(%" PRId64 ")", name, id->id);
                                       ^
Objects/interpreteridobject.c:109:32: note: to match this '('
    return PyUnicode_FromFormat("%s(%" PRId64 ")", name, id->id);
                               ^
Objects/interpreteridobject.c:116:37: error: expected ')'
    return PyUnicode_FromFormat("%" PRId64 "", id->id);
                                    ^
Objects/interpreteridobject.c:116:32: note: to match this '('
    return PyUnicode_FromFormat("%" PRId64 "", id->id);
                               ^
2 errors generated.
make: *** [Objects/interpreteridobject.o] Error 1
make: *** Waiting for unfinished jobs....
```

Please let me know if you have any thoughts / I'd be happy to test things out. Thank you again.

**Comment by native-api** [comment]
> clang -c -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -I/opt/homebrew/include -I/opt/homebrew/include   -I/opt/homebrew/include -I/opt/homebrew/include  -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal  -I. -I./Include -I/opt/homebrew/opt/ncurses/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/readline/include -I/Users/thomasbreydo/.pyenv/versions/3.12.2/include  -I/opt/homebrew/include -I/opt/homebrew/include -I/opt/homebrew/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/ncurses/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/readline/include -I/Users/thomasbreydo/.pyenv/versions/3.12.2/include  -I/opt/homebrew/include -I/opt/homebrew/include -I/opt/homebrew/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include  -DPy_BUILD_CORE -o Objects/iterobject.o Objects/iterobject.c
> Objects/interpreteridobject.c:109:40: error: expected ')'
>     return PyUnicode_FromFormat("%s(%" PRId64 ")", name, id->id);

Something is broken in your compiler toolchain: looks like `PRId64` is not defined. It's supposed to be a macro defined in `inttypes.h` and expanding to a string literal.

Check if you other compiler toolchains -- and `inttypes.h` in particular -- elsewhere.

**Comment by thomasbreydo** [comment]
@native-api thank you SO, so much. You were right :) At some point in the past, I placed an empty `inttypes.h` file into `/opt/homebrew/include`. Deleting it fixed my issue. Wow.

Thank you again, so much!
