### ISSUE TITLE
PyPy 7.3.16?

### ISSUE THREAD

**Issue by nedbat** [pyenv/pyenv#2947]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
PyPy now has 7.3.16 available: https://www.pypy.org/download.html

Can we get that version added to pyenv?  cc @edgarrmondragon :)

**Comment by native-api** [comment]
@edgarrmondragon Are you generating the files with a script? If yes, it'll be very welcome in https://github.com/pyenv/pyenv/tree/master/plugins/python-build/scripts ! We'd need one in any case if we are to automate adding new releases.

**Comment by native-api** [comment]
> Give a couple of weeks 🙂.

https://meta.stackexchange.com/questions/19478/the-many-memes-of-meta/19514#19514
