### ISSUE TITLE
Python 3.12 cannon install on arch linux, please advise: "/usr/include/asm/sigcontext.h:77:2: error: unknown type name '__uint128_t'"

### ISSUE THREAD

**Issue by c172jeff** [pyenv/pyenv#2950]
Hello,
  On my Arch Linux ARM/Raspberry Pi installation, I cannot install Python 3.12.  I have the attached error.
I run the command  pyenv install 3.12 at my command prompt.

I am using pyenv version 2.4.0
I am using gcc (GCC) 5.3.0

Please advise, Jeff

___________________________________________________________________

 pyenv install 3.12
Downloading Python-3.12.3.tar.xz...
-> https://www.python.org/ftp/python/3.12.3/Python-3.12.3.tar.xz
Installing Python-3.12.3...

BUILD FAILED (Arch Linux ARM using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20240428153332.2150
Results logged to /tmp/python-build.20240428153332.2150.log

Last 10 log lines:
In file included from /usr/include/bits/sigcontext.h:30:0,
                 from /usr/include/signal.h:287,
                 from ./Include/internal/pycore_faulthandler.h:12,
                 from ./Include/internal/pycore_runtime.h:15,
                 from Parser/action_helpers.c:6:
/usr/include/asm/sigcontext.h:77:2: error: unknown type name '__uint128_t'
  __uint128_t vregs[32];
  ^
Makefile:2731: recipe for target 'Parser/action_helpers.o' failed
make: *** [Parser/action_helpers.o] Error 1

**Comment by native-api** [comment]
Please add the necessary diagnostic information as per the issue template.

**Comment by c172jeff** [comment]
[PythonError.zip](https://github.com/pyenv/pyenv/files/15143525/PythonError.zip)

Here is a zip of some log files on another install attempt

**Comment by native-api** [comment]
Is your platform 32-bit or 64-bit? It's detected as 32-bit ARM (`gnueabihf`) but a standard header tries to use a 128-bit type [which are only available for 64-bit targets](https://stackoverflow.com/questions/16088282/is-there-a-128-bit-integer-in-gcc).
Looking at `config.log`, you have some `FLAGS` envvars set (e.g. `MULTIARCH_CPPFLAGS`) -- try unsetting those for starters.

**Comment by c172jeff** [comment]
Installed this….

 

https://hamvoip.org/index.html#firmware

 

It installs a version of Arch Linux for the Raspberry Pi 4.  I am not sure if it is 32 or 64.  I am still looking to find out.

 

uname –a reports

 

Linux N1JEM-607230 5.4.75-1-ARCH #1 SMP PREEMPT Mon Nov 9 16:58:39 UTC 2020 armv7l GNU/Linux

 

What command can I use to determine if its 64 Bit?

Jeff

**Comment by c172jeff** [comment]
How can I try my install again by unsetting the MULTIARCH_CPPFLAGS flag?  I just did a simple install using

pyenv install 3.12

I don't see an option to unset a a flag when running pyenv?

**Comment by native-api** [comment]
PRi 4 is 64-bit. But that page suggests that they make the same image for RPi 2,3 and 4 -- which means that the OS is 32-bit.

Then the standard header should not be using a 128-bit bit type.
You can look at the header to try to figure out why that happens (that line is probably controlled by a flag), or contact the firmware's vendor for support.

**Comment by native-api** [comment]
> How can I try my install again by unsetting the MULTIARCH_CPPFLAGS flag? I just did a simple install using
> 
> pyenv install 3.12
> 
> I don't see an option to unset a a flag when running pyenv?

`unset` it in your shell, or find the place in shell startup files where it's set and comment it out.
But if the OS is 32-bit, that flag is probably not the culprit since you do want to build for 32-bit ARM.

**Comment by native-api** [comment]
Since I don't know how they made the image or what a correct header should look like (on my machine, it doesn't even exist), I do suggest to contact the vendor for pointers.

All in all, `signal.h` seems to be broken on your system (I see this same error in a generic check for this header in `config.h`).
