### ISSUE TITLE
support mainland-china network env

### ISSUE THREAD

**Issue by kirkzhangtech** [pyenv/pyenv#2957]
in china , pyenv downloading python interpreter is too slow , if pyenv could support setup mirror  link ,so that pyenv could download python interpreter from mirror link.

**Comment by native-api** [comment]
Pyenv does support downloading from a mirror by setting the `PYTHON_BUILD_MIRROR_URL` envvar.

It however needs to be organized like our mirror at https://pyenv.github.io/pythons : the path to a package is `$PYTHON_BUILD_MIRROR_URL/<checksum from URL in Pyenv>(the text after the #)/<package_name>(the argument after "install_*" in installation script>`.

**Comment by kirkzhangtech** [comment]
$ export PYTHON_BUILD_MIRROR_URL="http://yoursite.example.com/pythons"
$ pyenv install 2.7.7

if above two lines are enough ?

**Comment by native-api** [comment]
> $ export PYTHON_BUILD_MIRROR_URL="http://yoursite.example.com/pythons" $ pyenv install 2.7.7
> 
> if above two lines are enough ?

Yes. Provided that you actually put the file to the mirror :slightly_smiling_face:

**Comment by kirkzhangtech** [comment]
![image](https://github.com/pyenv/pyenv/assets/46363359/1ed9c64c-d8e6-44a8-8523-4fc18f91e1b2)
i put mirror site into environment variable, but still not work , pyenv still download interpreter from original site

**Comment by native-api** [comment]
Did you put the file to the mirror under the correct name? See updated info above and see https://pyenv.github.io/pythons for URL examples.

**Comment by kirkzhangtech** [comment]
ah~
you mean that
1. i need to manually download tar from mirror site
2. put tar into `~/.pyenv/cache` folder
3. run pyenv install `tar`

is it right ?

**Comment by native-api** [comment]
You need to put the Python package that you'll be downloading onto the mirror that you've specified.

In your case,the file https://www.python.org/ftp/python/3.7.17/Python-3.7.17.tar.xz needs to be available as https://mirrors.huaweicloud.com/python/7911051ed0422fd54b8f59ffc030f7cf2ae30e0f61bda191800bb040dce4f9d2 . "7911051ed0422fd54b8f59ffc030f7cf2ae30e0f61bda191800bb040dce4f9d2" should be the actual file name, and the URL needs to lead directly to the file.

I see that you've replicated the official site's structure. In this case, the easiest would probably be to create symlinks if the mirror allows that. E.g.:

https://mirrors.huaweicloud.com/python/ :

7911051ed0422fd54b8f59ffc030f7cf2ae30e0f61bda191800bb040dce4f9d2 -> 3.7.17/Python-3.7.17.tar.xz

**Comment by kirkzhangtech** [comment]
to be honestly , i could not do that `https://mirrors.huaweicloud.com/python`  is public site which i do not own it .
how about  `https://pyenv.github.io/pythons/` link ?

**Comment by native-api** [comment]
> how about `https://pyenv.github.io/pythons/` link ?

It's outside Mainland China, so I don't think that'll help you.

> https://mirrors.huaweicloud.com/python is public site which i do not own it

You can ask them to add the symlinks. Pyenv is an industry standard so they might be willing to accomodate us.

**Comment by native-api** [comment]
Should they have any questons, you can direct them here.
The current scheme was created by @yyuu , the creator of Pyenv. I think the rationale was to abstract away differences between official sites for different Python flavors and their occasional changes.

**Comment by zzxCNCZ** [comment]
> ah~ you mean that
> 
> 1. i need to manually download tar from mirror site
> 2. put tar into `~/.pyenv/cache` folder
> 3. run pyenv install `tar`
> 
> is it right ?

this works for me

**Comment by zzxCNCZ** [comment]
> > ah~ you mean that
> > 
> > 1. i need to manually download tar from mirror site
> > 2. put tar into `~/.pyenv/cache` folder
> > 3. run pyenv install `tar`
> > 
> > is it right ?
> 
> this works for me

step 3 : run pyenv install ${python version code} will be ok
