### ISSUE TITLE
Long running instance of pyenv-exec sed

### ISSUE THREAD

**Issue by seang123** [pyenv/pyenv#2971]
Linux 6.5.0-35-generic Ubuntu x86_64
pyenv version: 2.4.0
gcc: 11.4.0

I am having an issue with pyenv running an 'sed' program against my system, which is taking a very long time.

Initially I installed python 3.9.16 and created some virtual environments all using pyenv and everything worked fine. 
Then I installed the miniforge3-23.11.0-0 version using pyenv, and created 2 virtual environments using the setup steps described in the following [repository](https://github.com/ShenLab/PreMode). 
Specifically:
```
mamba env create -f PreMode.yaml
mamba env create -f r4-base.yaml
```

And .. now my bash doesn't work anymore. Whenever I try to open a new terminal htop shows the following command running `bash /home/user/.pyenv/libexec/pyenv-exec sed s/[^\^][&]/g;s/[\^]/\\&/g`. This runs for several minutes before the prompt shows up, and then again every time I type a command. 

EDIT:
Deleting the created environments resolves the issue and the above command doesn't seem to run (or at least runs so quickly I can't see it in htop)
```
rm -r ~/.pyenv/versions/miniforge3-23.11.0-0/envs/*
```

**Comment by native-api** [comment]
Trying to reproduce, but `pyenv install miniforge3-23.11.0-0` just keeps failing for me due to `conda install pip conda=<...>` hanging.

**Comment by seang123** [comment]
For me `pyenv install miniforge3-23.11.0-0` works fine. 
During creation it does warn that conda is outdated `current version: 23.11.0` `latest version: 24.5.0`.
It also downloads and updates 4 packages:
```
ca-certificates 2024.2.2
certifi-2024.2.2
openssl-3.3.0
pip-24.0
```
During install my default environment is `pyenv:3.9.16`, although I guess that shouldn't be relevant.
