### ISSUE TITLE
Please add support for authenticating with the address specified in the environment variable PYTHON_BUILD_MIRROR_URL

### ISSUE THREAD

**Issue by grepwood** [pyenv/pyenv#2973]
I'm running PyEnv inside an organization that only allows access to the Internet via Artifactory, but will reject all anonymous requests.

Does PyEnv even support authenticating with such a mirror?

**Comment by grepwood** [comment]
Alright I found out how to shoehorn the Artifactory credentials via PYTHON_BUILD_CURL_OPTS.

However, finding this solution wasn't very straight-forward. I've read the readme at https://github.com/pyenv/pyenv/blob/56956e9d90a279fed31af41f0610a81abe7bbbb7/README.md and found only an anecdotal mention of PYTHON_BUILD_ARIA2_OPTS:
```
Used to pass additional parameters to [aria2](https://aria2.github.io/).
If the aria2c binary is available on PATH, pyenv uses aria2c instead of curl or wget to download the Python Source code. If you have an unstable internet connection, you can use this variable to instruct aria2 to accelerate the download.
In most cases, you will only need to use -x 10 -k 1M as value to PYTHON_BUILD_ARIA2_OPTS environment variable
```

By following this link https://github.com/pyenv/pyenv/blob/56956e9d90a279fed31af41f0610a81abe7bbbb7/plugins/python-build/README.md#special-environment-variables I found a grand total of 0 mentions of the variable PYTHON_BUILD_ARIA2_OPTS. The remaining 18 mentions of PYTHON_BUILD_ do not imply that ARIA2_OPTS even exists or works.

So I searched the source code and I finally found what I was looking for:
- https://github.com/pyenv/pyenv/blob/56956e9d90a279fed31af41f0610a81abe7bbbb7/plugins/python-build/test/test_helper.bash#L2
- https://github.com/pyenv/pyenv/blob/56956e9d90a279fed31af41f0610a81abe7bbbb7/plugins/python-build/bin/python-build#L2275

At this point I think the original scope of this issue would be to improve pyenv's documentation.

**Comment by native-api** [comment]
Fully agree with adding documentation for the variables.

Still, I was wondering: couldn't you authenticate by putting the credentials right into the URL? Like: `https://user:pass@example.org/whatever`

**Comment by grepwood** [comment]
@native-api I can, but that would mean that I would have to write a script that injects and removes the credentials from this variable, and this creates 2 problems.

1. While I could do that with regex, I find it to be a method ripe for accidents. I would need to define a regex that's pretty much bulletproof. I don't want to do this on the off-chance that we have to inject a password that contains a delimiter like `@` or `:`, or a variable starter symbol like `$`, `@`, `${...}` or `%`, or comment markers like `#`, `//` or `/*`, or a Bash string ending like `'` or `"`. I have already been burned like this in my career. There's nothing stopping anybody or anything from having a password, or receiving a password generated by a machine, that breaks and escapes the URL encoding, like `"; '; ///*# \; }haha:parse@th.is/${`.
2. The credentials must fall from the sky to pyenv only in 2 events:
a. When we build the Docker image (with BuildKit) that uses pyenv to install Python.
b. When a user installs another version of Python with premeditation.
This means that in all other cases, the credentials must not be there.

**Comment by native-api** [comment]
Okay, understood. I was just wondering whether you considered that option in addition to looking for a Pyenv-specific solution.

In addition to the Pyenv-specific solution that you found, it may be easier from the maintenance standpoint to rather configure your system in such a way that standard Linux tools just work.
E.g. cURL has a [configuration file](https://everything.curl.dev/cmdline/configfile.html).
([A previous similar issue](https://github.com/pyenv/pyenv/issues/2750))
