### ISSUE TITLE
Add a nicer way to select a free-threaded build

### ISSUE THREAD

**Issue by ngoldbaum** [pyenv/pyenv#2984]
It would be nice if you could select a free-threaded build as a command-line option to `pyenv install`, e.g. `pyenv install --free-threaded`, just like `--debug`. Currently you need to set `CONFIGURE_OPTS=--disable-gil` in a `pyenv install` command. I also use `pyenv-version-suffix` to give it a useful name:

```
CONFIGURE_OPTS=--disable-gil PYENV_VERSION_SUFFIX='-free-threaded' pyenv install -f -v 3.13.0b2
```

So I can select it with e.g. `pyenv global 3.13.0b2-free-threaded`.

It would be nice if pyenv could handle this out of the box. It will probably be something people want to do increasly often starting with Python 3.13.

**Comment by native-api** [comment]
This is possbile with a shell alias:

```
$ alias pyenv_install_free_threaded="CONFIGURE_OPTS=--disable-gil PYENV_VERSION_SUFFIX='-free-threaded' pyenv install -f -v"
$ pyenv_install_free_threaded 3.13.0b2
Downloading Python-3.13.0b2.tar.xz...
<...>
```

**Comment by ngoldbaum** [comment]
Sure, that's not very discoverable though. IMO this is going to be popular enough `pyenv install` will eventually need to grow an option for it.

**Comment by native-api** [comment]
> IMO this is going to be popular enough `pyenv install` will eventually need to grow an option for it.

If that'll be the case, we'll probably add separate build scripts for nogil versions. That looks like the way with the least complexity ("special cases are not special enough to break the rules").

**Comment by ngoldbaum** [comment]
Alternate build scripts also fixes the problem and obviates the need for the manually-applied version suffix. That would be great.

**Comment by colesbury** [comment]
I've put up a PR that adds build scripts for the free-threaded Python versions: https://github.com/pyenv/pyenv/pull/2995.

I've named them as `3.13t-dev` and 3.14t-dev`, but we can change that if there is a preference for a different naming scheme.

**Comment by lysnikolaou** [comment]
Trying to install `3.13t-dev` fails for me with the following:

```
ERROR: invalid Python executable: /Users/lysnikolaou/.pyenv/versions/3.13t-dev-debug/bin/python3.13t

The python-build could not find proper executable of Python after successful build.
Please open an issue for future improvements.
https://github.com/pyenv/pyenv/issues

BUILD FAILED (OS X 14.5 using python-build 20180424)

Inspect or clean up the working tree at /Users/lysnikolaou/.pyenv/sources/3.13t-dev-debug
Results logged to /var/folders/qv/js92y9x526sdmsmjdrylwkx80000gn/T/python-build.20240705105624.99961.log

Last 10 log lines:
                esac; \
                DYLD_LIBRARY_PATH=/Users/lysnikolaou/.pyenv/sources/3.13t-dev-debug/Python-3.13-dev ./python.exe -E -m ensurepip \
                        $ensurepip --root=/ ; \
        fi
Looking in links: /var/folders/qv/js92y9x526sdmsmjdrylwkx80000gn/T/tmpqb47dzi9
Processing /var/folders/qv/js92y9x526sdmsmjdrylwkx80000gn/T/tmpqb47dzi9/pip-24.1.1-py3-none-any.whl
Installing collected packages: pip
  WARNING: The scripts pip3 and pip3.13 are installed in '/Users/lysnikolaou/.pyenv/versions/3.13t-dev-debug/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-24.1.1
```

I assume this is because 3.13t-dev basically uses 3.13-dev with an environment variable set and verification tries to locate a `python3.13` executable, but there is none.

**Comment by ngoldbaum** [comment]
I opened https://github.com/pyenv/pyenv/issues/3010 for that issue.
