### ISSUE TITLE
Build failed for python 3.4.4 on Mac OSX 14.5 x86_64

### ISSUE THREAD

**Issue by awkh88** [pyenv/pyenv#2987]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Max OS X 14.5
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 2.4.3
- [x] Python version: Specifically 3.4.4, but I tested other versions of 3.4, they all fail. I successfully installed 3.5, 3.10 and 3.12.
- [x] C Compiler information (e.g. gcc 7.3):  Apple clang version 15.0.0
- [x] Please attach the debug trace of the failing command as a gist: [trace.log](https://github.com/user-attachments/files/15900719/trace.log)
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory [python-build.20240619141502.73194.log](https://github.com/user-attachments/files/15900778/python-build.20240619141502.73194.log)

I really tried to dig around your past issues to see if I could find something similar. I really apologise if I overlooked something.

**Comment by native-api** [comment]
> * If you have a problem with installing Python, please also attach `config.log` from the build directory [python-build.20240619141502.73194.log](https://github.com/user-attachments/files/15900778/python-build.20240619141502.73194.log)

Not the build log. `config.log`. It should be inside the build directory (which is reported near the "BUILD FAILED" message.

**Comment by native-api** [comment]
> * Specifically 3.4.4, but I tested other versions of 3.4, they all fail

Those are long EOL and most probably don't support newer MacOS versions and compilers.

**Comment by native-api** [comment]
> Those are long EOL and most probably don't support newer MacOS versions and compilers.

If you're interested in making them work, we do accept compatibility patches, see [CONTRIBUTING.md](https://github.com/pyenv/pyenv/blob/master/CONTRIBUTING.md).

**Comment by awkh88** [comment]
Thank you for your input! Much appreciated. I will try to find a work around. If not, maybe I will explore a compatibility patch.
