### ISSUE TITLE
Install script unable to compile python(Python/fileutils.c:2398:9: error: implicit declaration of function ‘close_range’)

### ISSUE THREAD

**Issue by so1n** [pyenv/pyenv#2988]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): deepin V23 (6.6.25-amd64-desktop-hwe)  [image url](https://www.deepin.org/en/download/)
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 2.4.3
- [x] Python version: 3.10.4
- [x] C Compiler information (e.g. gcc 7.3): 13.2.0
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
      
[trace.log](https://github.com/user-attachments/files/15903711/trace.log)

- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
     
[config.log](https://github.com/user-attachments/files/15903715/config.log)

- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

**Comment by native-api** [comment]
WFM on a clean installation from https://cdimage.deepin.com/releases/23-Beta2/
The version on the link you gave is v20.9 .
**Please double-check which distro version you're running.**

For now, I dug up the following:

I see that `close_range` is defined in `/usr/include/unistd.h` if `__USE_GNU` is defined, which is defined in `/usr/include/features.h` if `_GNU_SOURCE` is defined, which is defined in generated `pyconfig.h`.

Please check that you don't have any bogus headers with those names on the compiler search path (e.g. in `/usr/local`), that the above is true for your versions, and if not, reinstall the packages that they belong to (find the package that a file belongs to with `dpkg -S <full path>`).

**Comment by native-api** [comment]
I see that the beta does have an upgrade to kernel 6.6.25, but upgrading with `apt dist-upgrade` bricks my VM.

**Comment by so1n** [comment]
I'm very sorry that I didn't make it clear that there are two versions of the download url provided in the image url. the url I used for the image is https://cdimage.deepin.com/releases/23-RC2/amd64/

I didn't have the computer with which I had the problem with me when I left the house today, I will try the following at a later:
```
Please check that you don't have any bogus headers with those names on the compiler search path (e.g. in /usr/local), that the above is true for your versions, and if not, reinstall the packages that they belong to (find the package that a file belongs to with dpkg -S <full path>).
```

**Comment by native-api** [comment]
> I'm very sorry that I didn't make it clear that there are two versions of the download url provided in the image url. the url I used for the image is https://cdimage.deepin.com/releases/23-RC2/amd64/

That surely helps! I was able to reproduce it.

`close_range` declaration is simply missing from `unistd.h`. I'm not completely sure how `configure` finds it. Looking at its test code, the test codes makes an alternative declaration and the runs it (without arguments). It probably works because it's a system call -- i.e. it's implemented in the kernel, so it would be found with any declaration.

Summarizing, **this is a problem with the distro, the `unistd.h` header doesn't match the kernel.**

**Comment by so1n** [comment]
@native-api  I think I found a good solution:

- 1: Find tmp dir from commod output:
  ```
  ➜  pyenv install 3.10.4
  Downloading Python-3.10.4.tar.xz...
  -> https://www.python.org/ftp/python/3.10.4/Python-3.10.4.tar.xz
  Installing Python-3.10.4...

  BUILD FAILED (Deepin 23 using python-build 2.4.3)

  Inspect or clean up the working tree at /tmp/python-build.20240622021759.359752
  Results logged to /tmp/python-build.20240622021759.359752.log
  ```
- 2: Go to the folder `/tmp/python-build.20240622021759.359752`
- 3: Find the error message via trace.log
  ```
  Python/fileutils.c:2398:9: error: implicit declaration of function ‘close_range’ [-Werror=implicit-function-declaration]
  ```
- 4:In the current path(`/tmp/python-build.20240622021759.359752`), open `Python/fileutils.c` and Jump to 2397 (2398 -1), enter the following code:
  ```
  extern int close_range(int first, int last, unsigned int flags);
  ```
- 5: Use `make & make altinstall`

Once the command has finished running, you can see the installed version through pyenv version:
```
➜  pyenv versions
* system (set by /home/so1n/.pyenv/version)
  3.8.16
  3.9.16
  3.10.4
```

**Comment by native-api** [comment]
> * 5: Use `make & make altinstall`

Nice find! 
This won't run postinstall steps though like creating aliases for `pythonX.Y`. You'd have to perform those by hand as well.

**Comment by so1n** [comment]
> > * 5: Use `make & make altinstall`
> 
> Nice find! This won't run postinstall steps though like creating aliases for `pythonX.Y`. You'd have to perform those by hand as well.

`pyenv sheel` and `pyenv virtualenv` Can't load properly into my installation of python 3.10.4.
But I can get up to version 3.10.4 properly in poetry, and that's enough for me.
