### ISSUE TITLE
feature request: add --pgo -o flag to pyenv install for building with profile guided optimisation 

### ISSUE THREAD

**Issue by pantheraleo-7** [pyenv/pyenv#2997]
The [wiki](https://github.com/pyenv/pyenv/wiki#suggested-build-environment) suggests a (very long) command for default (set of tests) PGO build. Of course one can always alias it but seeing that debug builds got its own flag `--debug` `-g` and [currently in development - free threaded builds - got their own build scripts](https://github.com/pyenv/pyenv/pull/2995) and that PGO builds are common and [fast enough](https://github.com/python/cpython/pull/14702) now, that some love should be shown to optimised builds too.

IMHO pyenv is all about easing the process of (multiple) python installations (of any build-kind) and this feature is a step towards that. I would like to know your opinions on this. I always install optimised builds, I would be very happy if this request gets accepted ✌️

PS. I ran some builds and found out that normal builds take about 3.5 minutes while optimised builds take 6.75 minutes. So the difference is a little less than x2 (at least on my machine).

**Comment by native-api** [comment]
Note that debug/free-threaded builds are fundamentally different from PGO:
* debug and free-threaded builds result in a different flavors of CPython that is not fully compatible with the regular one. And they are installed under different names for this reason.
* while a PGO build results in the same flavor and thus is not fundamentaly different from other build customizations

**Comment by native-api** [comment]
You don't have to type long invocations every time to make PGO builds, you can instead set those envvars permanently.

**Comment by native-api** [comment]
You don't have to type long invocations every time to make PGO builds, you can instead set those envvars permanently.

You can even make a plugin with a `before_install` hook for `pyenv install` if you'd rather set them just for the builds.

**Comment by pantheraleo-7** [comment]
nvm use [uv](https://github.com/astral-sh/uv)
