### ISSUE TITLE
Can you add pyenv completions

### ISSUE THREAD

**Issue by jamnaughty** [pyenv/pyenv#3006]
I dont see completions under the path specified in the docs

`This is entirely optional but pretty useful. Sourcing $(pyenv root)/completions/pyenv.bash`

Can you please add those?

**Comment by native-api** [comment]
As per the documentation, completions are supposed to be installed via `eval "$(pyenv init -)"`.

The path is given as an explanation and is correct for a git clone installation. If you installed Pyenv differently, downstream packaging may have mixed it up.
