### ISSUE TITLE
brew upgrade pyenv  *** FAIL for v2.4.5.tar.gz ***

### ISSUE THREAD

**Issue by jainraje** [pyenv/pyenv#3007]
brew upgrade pyenv

Error: pyenv: Failed to download resource "pyenv"
Download failed: https://github.com/pyenv/pyenv/archive/refs/tags/v2.4.5.tar.gz

Path to v2.4.5.tar.gz does not appear to be correct.

v2.4.5 was released 2 days ago. 

Please advise.

**Comment by native-api** [comment]
https://github.com/Homebrew/homebrew-core/pull/176288

The release was recalled and redone with a different tag due to an error while making it.

This shouldn't be affecting `brew install` because the formula has bottles for all supported MacOS versions. Are you in Linux?

**Comment by native-api** [comment]
Made https://github.com/pyenv/pyenv/releases/tag/v2.4.6 since there's been a nre CPython version added since. Whichever will be added to Homebrew first will make `brew install/upgrade` work.
