### ISSUE TITLE
Cannot install 3.13t-dev with --debug

### ISSUE THREAD

**Issue by ngoldbaum** [pyenv/pyenv#3010]
@lysnikolaou saw this and commented earlier [on another issue](https://github.com/pyenv/pyenv/issues/2984#issuecomment-2210549715).

```
$ pyenv install 3.13t-dev --debug
python-build: use openssl@3 from homebrew
python-build: use readline from homebrew
Cloning https://github.com/python/cpython...
Installing Python-3.13-dev...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use ncurses from homebrew
python-build: use zlib from homebrew
ERROR: invalid Python executable: /Users/goldbaum/.pyenv/versions/3.13t-dev-debug/bin/python3.13t

The python-build could not find proper executable of Python after successful build.
Please open an issue for future improvements.
https://github.com/pyenv/pyenv/issues

BUILD FAILED (OS X 14.5 using python-build 2.4.5-3-g38436116)
```

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): MacOS Sonoma
- [x] OS architecture (e.g. amd64): AARCH64
- [x] pyenv version: 2.4.5-3-g38436116
- [x] Python version: 3.13.0b3t
- [x] C Compiler information (e.g. gcc 7.3):  Apple Clang 15
- [x] Please attach the debug trace of the failing command as a gist: [trace.log](https://github.com/user-attachments/files/16109160/trace.log)
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory: [config.log](https://github.com/user-attachments/files/16109175/config.log)
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [x] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

**Comment by lysnikolaou** [comment]
Thanks for opening the issue @ngoldbaum!

> I assume this is because 3.13t-dev basically uses 3.13-dev with an environment variable set and the verification step tries to locate a python3.13 executable, but there is none.

I posted this on the other issue. It looks like I was wrong. The verification step looks for `python3.13t`, but cannot find it, cause there's only a `python3.13` and a `python3.13td` executable (remember it's a debug build).
