### ISSUE TITLE
[Question] Are the builds/results of pyenv install portable?

### ISSUE THREAD

**Issue by dillydill123** [pyenv/pyenv#3014]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

I had a general question that I could not find a good answer elsewhere. Apologies if this isn't the right place to ask but I was unsure. I want to install pyenv + some version of python on identical machines. My idea was to build python on one machine, compress it and send it to every machine. I tried this, but ran into an issue I believe with `LDFLAGS`. At runtime the interpreter wouldn't work since every home directory was different for each machine. If the home directory was the same then the interpreter did work.

I had a few ideas to solve this, like putting the python installation location in a common location like `/opt` or using `$HOME` in `LDFLAGS` (not sure if that's possible). Before I dig any further, I wanted to know if there are any pit falls to this approach. The main benefits I'm seeking are speed of installation and that no internet is required to install python.

Does this seem okay? If so, what would be the best way to fix `LDFLAGS`?

**Comment by native-api** [comment]
Pyenv-built Python links against [python build dependencies](https://github.com/pyenv/pyenv/wiki#suggested-build-environment) on your system.

You can check which external libraries the result uses by running:

```
find "$(pyenv prefix <version>)" -name \*.so | xargs ldd
```

So you can move it to another machine if it has the same system libraries.

**Comment by dillydill123** [comment]
Thank you, for my use case, this was sufficient. I did have to do some patching after installation to fix hard coded paths and update rpath using chrpath but overall it works very well. I also considered using [python-build-standalone](https://github.com/indygreg/python-build-standalone) which seems to take care of these problems as well.

In another comment you mentioned it's possible to install these custom prebuilt python interpreters using a plugin: https://github.com/pyenv/pyenv/issues/1417#issuecomment-845954847

Could you elaborate a bit more on how this would work?

**Comment by native-api** [comment]
> In another comment you mentioned it's possible to install these custom prebuilt python interpreters using a plugin: [#1417 (comment)](https://github.com/pyenv/pyenv/issues/1417#issuecomment-845954847)
> 
> Could you elaborate a bit more on how this would work?

https://github.com/pyenv/pyenv/tree/master/plugins/python-build#adding-definitions-with-a-pyenv-plugin
