### ISSUE TITLE
pyenv uninstall fails with version that is listed by pyenv version

### ISSUE THREAD

**Issue by nbbaier** [pyenv/pyenv#3017]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS 14.5
- [x] OS architecture (e.g. amd64): arm64
- [x] pyenv version: 2.4.7
- [x] Python version: 
```
$ pyenv versions
  system
  3.11.0
* 3.12.0 (set by /Users/nbbaier/.pyenv/version)
```
- [x] C Compiler information (e.g. gcc 7.3):
```
$ gcc -v
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
- [x] Please attach the debug trace of the failing command as a gist: https://gist.github.com/nbbaier/85e539d9ecf067651065175c0216e130
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory
- [x] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach

### The issue 

```
$ pyenv versions && pyenv uninstall 3.11.0
  system
  3.11.0
* 3.12.0 (set by /Users/nbbaier/.pyenv/version)
pyenv: version `3.11.0' not installed
```

**Comment by native-api** [comment]
In `/opt/homebrew/Cellar/pyenv/2.4.7/plugins/python-build/bin/pyenv-uninstall`, after `set -e`, please add a line

```
[ -n "$PYENV_DEBUG" ] && set -x
```

and make the trace log again.
For some reason, it's not present there unlike all the other subcommands, so I can't what's happening there.

**Comment by nbbaier** [comment]
Done, new log is here: https://gist.github.com/nbbaier/85e539d9ecf067651065175c0216e130#file-trace_new-log

**Comment by native-api** [comment]
```
+(/opt/homebrew/Cellar/pyenv/2.4.7/plugins/python-build/bin/pyenv-uninstall:73): uninstall-python(): '[' '!' -d /Users/nbbaier/.pyenv/versions/3.11.0 ']'
+(/opt/homebrew/Cellar/pyenv/2.4.7/plugins/python-build/bin/pyenv-uninstall:74): uninstall-python(): echo 'pyenv: version `3.11.0'\'' not installed'
```

Is `/Users/nbbaier/.pyenv/versions/3.11.0` NOT a directory?
Have you run `brew pyenv-sync` before, by any chance?

**Comment by nbbaier** [comment]
> Is `Users/nbbaier/.pyenv/versions/3.11.0` NOT a directory?

Something weird is happening with `Users/nbbaier/.pyenv/versions/3.11.0` because if I run `ls` on `Users/nbbaier/.pyenv/versions` I get the following output:

```
$ ls /Users/nbbaier/.pyenv/versions
3.11.0  3.12.0
```
But then `ls Users/nbbaier/.pyenv/versions/3.11.0` I get an error:

```
$ ls Users/nbbaier/.pyenv/versions/3.11.0
ls: Users/nbbaier/.pyenv/versions/3.11.0: No such file or directory
```

But finder also regcognizes it:

<img width="482" alt="Screenshot 2024-07-14 at 11 43 30 PM" src="https://github.com/user-attachments/assets/3240af29-8a40-4c60-8cc2-a87e33e6b16b">

> Have you run `brew pyenv-sync` before, by any chance?
I haven't, as far as I remember

**Comment by native-api** [comment]
> Something weird is happening with `Users/nbbaier/.pyenv/versions/3.11.0` because if I run `ls` on `Users/nbbaier/.pyenv/versions` I get the following output:
> 
> ```
> $ ls /Users/nbbaier/.pyenv/versions
> 3.11.0  3.12.0
> ```
> 
> But then `ls Users/nbbaier/.pyenv/versions/3.11.0` I get an error:
> 
> ```
> $ ls Users/nbbaier/.pyenv/versions/3.11.0
> ls: Users/nbbaier/.pyenv/versions/3.11.0: No such file or directory
> ```

That's the expected behavior is it's a broken symlink. Use `ls -l` to see details about what directori entry is what. If you have colors enabled with `ls`, it also typically shows broken symlinks in red.

I expected as much, the remaining question is: where does it point to? (`ls -l` will show that)

**Comment by nbbaier** [comment]
It's not actually a symlink, looks like. But the problem is almost certainly that there's somehow a space in the directory for 3.11.0:

<img width="445" alt="ls-l" src="https://github.com/user-attachments/assets/dfbb32db-94b0-441c-b14e-f81c6b95922f">

And removing the space fixed the issue:

<img width="713" alt="success" src="https://github.com/user-attachments/assets/326189c0-0f5a-43f5-8e5c-9c7670b644b6">
