### ISSUE TITLE
PyEnv should offer a "latest" tag

### ISSUE THREAD

**Issue by ordinaryindustries** [pyenv/pyenv#3025]
### Description
PyEnv should support a `latest` tag. I frequently need to install the latest version of Python which means I need to use `pyenv install --list` to find the version. I don't care about the version number so long as it is the most current. I have written a workaround:

```
latest_python_version=$(pyenv install --list | grep -E '^\s*[0-9]+(\.[0-9]+)*$' | tail -1 | tr -d ' ')
pyenv install -f $latest_python_version
pyenv global $latest_python_version
```

but this could be simplified if PyEnv handled the lookup. Running `pyenv install latest` should fetch the version info from the latest tag and install it.

### Info
- [*] Platform information (e.g. Ubuntu Linux 16.04): macOS 14.5
- [*] OS architecture (e.g. amd64): arm64
- [*] pyenv version: 2.4.8
- [*] Python version: 3.12.4
- [*] C Compiler information (e.g. gcc 7.3):  clang 15.0.0

**Comment by native-api** [comment]
`pyenv install 3`

**Comment by ordinaryindustries** [comment]
Ahh of course. Thank you.

**Comment by native-api** [comment]
Perhaps this is worth pointing out in the README (as a common use case) since it is technically documented but requires a logical hop to figure out.
