### ISSUE TITLE
Stuck while installing Python 3.12.2 using pyenv on WSL2

### ISSUE THREAD

**Issue by Kobayashi-Riku0226** [pyenv/pyenv#3027]
## My environment
* OS
  * WSL2 (Ubuntu 20.04)
* CPU Architecture
  * x86_64
* pyenv version
  * pyenv 2.4.8
* gcc version
  * gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
## problem

When I run the "pyenv install" command, it gets stuck at the following part and the status does not change for over an hour.
Are there any issues that could be the cause?
I would appreciate it if you could let me know if there are any other points that I should check.
```
pyenv install 3.12.2 -v
/tmp/python-build.20240729124510.22080 ~
Downloading Python-3.12.2.tar.xz...
-> https://www.python.org/ftp/python/3.12.2/Python-3.12.2.tar.xz
/tmp/python-build.20240729124510.22080/Python-3.12.2 /tmp/python-build.20240729124510.22080 ~
Installing Python-3.12.2...
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for Python interpreter freezing... ./_bootstrap_python
checking for python3.12... python3.12
checking Python for regen version...
```

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04):
- [x] OS architecture (e.g. amd64):
- [x] pyenv version:
- [x] Python version:
- [x] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [ ] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

**Comment by Kobayashi-Riku0226** [comment]
I restarted the installation of WSL2 and the installation was successful.
The cause is unknown, but there may have been some kind of conflict.

**Comment by native-api** [comment]
**The hanging command seems to be `python2.12 -V`.**

https://github.com/python/cpython/blob/v3.12.2/configure :

```sh
for ac_prog in python$PACKAGE_VERSION python3.12 python3.11 python3.10 python3 python
do
  # Extract the first word of "$ac_prog", so it can be a program name with args.
set dummy $ac_prog; ac_word=$2
{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
printf %s "checking for $ac_word... " >&6; }
<...>
    ac_cv_prog_PYTHON_FOR_REGEN="$ac_prog"
<...>
{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking Python for regen version" >&5
printf %s "checking Python for regen version... " >&6; }
if command -v "$PYTHON_FOR_REGEN" >/dev/null 2>&1; then
  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $($PYTHON_FOR_REGEN -V 2>/dev/null)" >&5
printf "%s\n" "$($PYTHON_FOR_REGEN -V 2>/dev/null)" >&6; }
```

**Comment by cinnamon17** [comment]
Hi, I was having the same problem. In my case, it was because the environment variable `PYTHON_FOR_REGEN` was not set!

If the command `echo $PYTHON_FOR_REGEN` returns nothing, you need to set it to the actual system Python version.

You can pass the environment variable like this:

`PYTHON_FOR_REGEN=/path/to/python pyenv install 3.11.6`

Replace` /path/to/python` with the actual system version of Python, which can be found using the command `which python` or` which python3`

Tested on WSL2 with Debian 12.

I hope this helps someone! 🙂

@Kobayashi-Riku0226 @native-api
