### ISSUE TITLE
pyenv install on macOS warns `The Python curses extension was not compiled. Missing the ncurses lib?` "/usr/local/include/stdlib.h: warning: pointer is missing a nullability type specifier"

### ISSUE THREAD

**Issue by Sped0n** [pyenv/pyenv#3035]
When installing Python 3.11, a warning showed up(exit code is normal)

```
❯ pyenv install 3.11
python-build: use openssl@3 from homebrew
python-build: use readline from homebrew
Downloading Python-3.11.9.tar.xz...
-> https://www.python.org/ftp/python/3.11.9/Python-3.11.9.tar.xz
Installing Python-3.11.9...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use ncurses from homebrew
python-build: use zlib from xcode sdk
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/spedon/.pyenv/versions/3.11.9/lib/python3.11/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
WARNING: The Python curses extension was not compiled. Missing the ncurses lib?
Installed Python-3.11.9 to /Users/spedon/.pyenv/versions/3.11.9
```

Older version fails too

```
❯ pyenv install 3.9
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.9.19.tar.xz...
-> https://www.python.org/ftp/python/3.9.19/Python-3.9.19.tar.xz
Installing Python-3.9.19...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use ncurses from homebrew
python-build: use zlib from xcode sdk
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/spedon/.pyenv/versions/3.9.19/lib/python3.9/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
WARNING: The Python curses extension was not compiled. Missing the ncurses lib?
Installed Python-3.9.19 to /Users/spedon/.pyenv/versions/3.9.19
```

But installation for Python 3.12 works fine

```
❯ pyenv install 3.12
python-build: use openssl@3 from homebrew
python-build: use readline from homebrew
Downloading Python-3.12.5.tar.xz...
-> https://www.python.org/ftp/python/3.12.5/Python-3.12.5.tar.xz
Installing Python-3.12.5...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use ncurses from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.12.5 to /Users/spedon/.pyenv/versions/3.12.5
```

---

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS Sonoma 14.6.1 (23G93)
- [x] OS architecture (e.g. amd64): arm64
- [x] pyenv version: 2.4.10
- [x] Python version: 3.11.9
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 15.0.0 (clang-1500.3.9.4)
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [x] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`: [trace.log](https://drive.google.com/file/d/1JjWwhvqOyy4silCrASo7uXBfYz9Gp_pD/view?usp=sharing)
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`: [config.log](https://github.com/user-attachments/files/16664216/config.log)

**Comment by native-api** [comment]
You have a bogus C stdlib installation in `/usr/include`. Delete it.

```
In file included from ./Include/Python.h:23:
/usr/local/include/stdlib.h:134:25: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
double   atof(const char *);
                         ^
```

**Comment by Sped0n** [comment]
The warning persists

[trace.log](https://github.com/user-attachments/files/16665118/trace.log)

**Comment by native-api** [comment]
Cannot reproduce.

> While the installation of 3.12 works fine

I see that 3.12 did away with `setup.py` completely. Judging by the error message, the fault happens there, inside `detect_readline_curses()`.

Most probably, there are some other extraneous bits on your system that confuse it.

I suggest to add debug printing to it [to find out where it goes wrong](https://stackoverflow.com/questions/78017188/finding-an-error-in-an-algorithm-with-a-loop-with-too-many-iterations-to-step-th/78017368#78017368).

1. Run `pyenv install -k <version>` to get the source code
2. Make a copy of `setup.py`: `cp ~/.pyenv/sources/<version>/Python*/setup.py .`
3. Edit the copy to add debug printing to the aforementioned function -- e.g. `vim setup.py`
4. `pyenv install -kvfp <version> 2>&1 < <(diff -u ~/.pyenv/sources/<version>/Python*/setup.py setup.py) | tee out.txt`
5. `less out.txt` and find your debug output in the log
6. Rinse and repeat steps 3-5 until you've pinpointed the immediate cause

**Comment by Sped0n** [comment]
Thanks, found out why. **The reason is that MATLAB's bundled `ldd` was used**. Previously, to use MATLAB's LSP in nvim, I added MATLAB's bin directory to the PATH, and it blow things up.

As we can see from the code, `setup.py` switched to using `ldd` when looking for `ncurses`. However, as seen from the regex below, the `ldd` approach (*.so) is actually for Linux.

<img width="1624" alt="SCR-20240822-nsmi" src="https://github.com/user-attachments/assets/8c665fa0-4a43-4f0f-92f7-e9e764db2947">

And it does not work for macOS's `dylib`. As a result, `curses_library` became `/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)` (which should be `curses` or `ncurses`).

After removing it from PATH everything works.
