### ISSUE TITLE
Add /usr/etc/pyenv.d as additional directory for hooks

### ISSUE THREAD

**Issue by tomschr** [pyenv/pyenv#3036]
It should be a fairly easy fix. :wink: 

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): openSUSE 15.5
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 2.4.10
- [x] Python version: 3.6
- [x] C Compiler information (e.g. gcc 7.3): 7.5.0

The directory `/usr/etc` is an optional directory and used by Fedora, RHEL 9, and openSUSE. The purpose of `/usr/etc` is to store distribution-provided configuration files that can be overridden by user-modified files in `/etc`.

### Proposal

I propose to add this directory to the `libexec/pyenv` file:

```diff
diff --git i/libexec/pyenv w/libexec/pyenv
index fdea4911..a4b0c3ae 100755
--- i/libexec/pyenv
+++ w/libexec/pyenv
@@ -94,7 +94,7 @@ if [ "${bin_path%/*}" != "$PYENV_ROOT" ]; then
   # Add pyenv's own `pyenv.d` unless pyenv was cloned to PYENV_ROOT
   PYENV_HOOK_PATH="${PYENV_HOOK_PATH}:${bin_path%/*}/pyenv.d"
 fi
-PYENV_HOOK_PATH="${PYENV_HOOK_PATH}:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks"
+PYENV_HOOK_PATH="${PYENV_HOOK_PATH}:/usr/etc/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks"
 for plugin_hook in "${PYENV_ROOT}/plugins/"*/etc/pyenv.d; do
   PYENV_HOOK_PATH="${PYENV_HOOK_PATH}:${plugin_hook}"
 done
```

Thank you!

**Comment by native-api** [comment]
[`/usr/etc` is not in FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04.html). What distros are using it? Could you refer to any docs?

**Comment by tomschr** [comment]
According to [Thorsten comment](https://github.com/thkukuk/atomic-updates_and_etc/issues/2#issuecomment-524848666) in regards to FHS:

> "_There are several requests from SUSE and RedHat, the oldest is I think 4-5 years old. Since there will not happen anything, we have to ignore that. See the discussions RedHat had with them and we had with them._
> _As the FHS is currently nearly as dead as LSB, we can only ignore it if we don't want to stop and kill all innovation. systemd e.g. is also violating the FHS ..._"

* openSUSE has something in its [Wiki](https://kubic.opensuse.org/blog/2019-12-05-usr-etc/) and its [Packaging Guide](https://en.opensuse.org/openSUSE:Packaging_UsrEtc)

* Fedora mention it in its [Documentation](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/7/html/storage_administration_guide/ch-filesystem#s3-filesystem-usr)

**Comment by native-api** [comment]
Authoritative enough! :+1: 

SGTM.

**Comment by tomschr** [comment]
@native-api Do you want me to open a pull request or is this issue enough for you? :slightly_smiling_face:

**Comment by native-api** [comment]
Yes, a PR is needed -- at the very least, to get this as an item in generated release notes, and to run CI (some tests may need adjusting).
