### ISSUE TITLE
Compilation error while installing Python: "ModuleNotFoundError: No module named '_curses', 'readline' and '_sqlite3'"

### ISSUE THREAD

**Issue by IllTamer** [pyenv/pyenv#3047]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Rocky Linux 9.3
- [x] OS architecture (e.g. amd64):  x86_64
- [x] pyenv version: pyenv 2.4.11
- [x] C Compiler information (e.g. gcc 7.3): gcc (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [ ] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [x] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log` [trace.log](https://github.com/user-attachments/files/16897993/trace.log)
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.  [config.log](https://github.com/user-attachments/files/16898009/config.log)

```shell
➜  ~ pyenv install 3.12.5 
Downloading Python-3.12.5.tar.xz...
-> https://www.python.org/ftp/python/3.12.5/Python-3.12.5.tar.xz
Installing Python-3.12.5...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/illtamer/.pyenv/versions/3.12.5/lib/python3.12/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
WARNING: The Python curses extension was not compiled. Missing the ncurses lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'readline'
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/illtamer/.pyenv/versions/3.12.5/lib/python3.12/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/home/illtamer/.pyenv/versions/3.12.5/lib/python3.12/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
Installed Python-3.12.5 to /home/illtamer/.pyenv/versions/3.12.5
```

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv?tab=readme-ov-file#install-python-build-dependencies

```checking for sqlite3 >= 3.7.15... no
checking for sqlite3.h... no
checking for --enable-loadable-sqlite-extensions... no
<...>
checking for readline... no
checking for readline/readline.h... no
checking how to link readline... no
<...>
checking for curses.h... no
checking for ncurses.h... no
checking curses module flags... no
```
