### ISSUE TITLE
The auto-resolution of latest versions feature doesn't work with `python-` prefixes (eg `python-3.12`)

### ISSUE THREAD

**Issue by edmorley** [pyenv/pyenv#3054]
### Summary

pyenv works fine when an explicit `python-` prefix is added to the Python version when full versions are specified (for example `python-3.12.6`), however, fails to find a matching Python version if the "auto-resolve latest version" feature is used with a `python-` prefix (such as `python-3.12`).

ie:
- Works: `3.12`, `3.12.6`, `python-3.12.6`
- Doesn't work: `python-3.12`

This appears to be due to the `python-` prefix removal here only covering the exact match case, and not the `pyenv-latest` code-path:
https://github.com/pyenv/pyenv/blob/1cabb6e02b1408b783038627a4ad1d30eabb7f10/libexec/pyenv-version-name#L32-L43

I will open a PR for this.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS 14.6.1
- [x] OS architecture (e.g. amd64): arm64
- [x] pyenv version: 2.4.12
- [x] Python version: 3.12.6
- [x] C Compiler information (e.g. gcc 7.3): N/A
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

1. `pyenv install 3.12.6`
2. `mkdir pyenv-test && cd $_`
3. `echo 'python-3.12' > .python-version`
4. `pyenv versions`

### Expected

```
$ pyenv versions
  system
* 3.12.6 (set by /Users/emorley/src/pyenv-test/.python-version)
```

ie: The same as if I had instead saved either `3.12` or `python-3.12.6` into the `.python-version` file (both of which work fine, unlike `python-3.12`).

### Actual

```
$ pyenv versions
pyenv: version `python-3.12' is not installed (set by /Users/emorley/src/pyenv-test/.python-version)
  system
  3.12.6
```

Trace: [trace.log](https://github.com/user-attachments/files/16930143/trace.log)

Though as mentioned above, the cause seems clear and I'm happy to open a PR for this :-)

**Comment by native-api** [comment]
Where did you get that idea of the "`python-`" prefix? There are no available versions in Pyenv named so -- so why should it ever work?

**Comment by edmorley** [comment]
I was implementing a parser of `.python-version` files, and wanted to know what syntax was valid, so was part reading the pyenv source/tests, and part trying things out - I can't remember via which of those means I first found that pyenv already supported the `python-` prefix for the full version format (`python-X.Y.Z`). The Heroku `runtime.txt` file format uses `python-X.Y.Z` so it's possible that also acted as inspiration.

As an alternative, I would also be fine with pyenv not supporting `python-` at all.

It's just at the moment it's supported inconsistently.

**Comment by native-api** [comment]
> that pyenv already supported the `python-` prefix for the full version format (`python-X.Y.Z`)

That's news to me. This never was a documented feature, there are no tests checking that.

**Comment by edmorley** [comment]
> there are no tests checking that.

There is an existing test for the `python-X.Y.Z` case on `master`:
https://github.com/pyenv/pyenv/blob/1cabb6e02b1408b783038627a4ad1d30eabb7f10/test/version-name.bats#L109-L115

Though as mentioned above, I have no strong feelings for this feature, I would just like to (a) be certain what syntax my parser of `.python-version` files needs to support, (b) avoid leaving partially implemented/consistent features around (ie: the `python-` syntax only working in some cases).

Do you have a preference out of:
1. Fix the existing incomplete `python-` feature so it works for the auto-resolution case too (ie: #3056).
2. Deprecate the existing `python-` feature (eg via pyenv printing a warning), but don't fix the implementation.
3. Remove the existing `python-` feature.

**Comment by edmorley** [comment]
Ah thank you.

That also explains why the current implementation uses a separate `elif` for the prefix case (vs consolidating the two, which I included in #3056), since the original rbenv implementation had to know when to show the warning or not.

For `.python-version` I don't know of any other tooling that only accepts the `python-` form, so I suspect the rbenv concern over showing warnings might not apply to Python/pyenv? And therefore it might be viable for us to add the warning back for pyenv?

**Comment by native-api** [comment]
CC @pyenv/pyenv-core-maintainers 

> Do you have a preference out of:

ATM I'm in favor of deprecation:
* This prefix as it is is pointless because everything in Pyenv is "python". It would make sense if it was "cpython" as opposed to other flavors.
  * The Rbenv commit message above even points out this hypocrisy _("Their logic is that MRI is "ruby" and other rubies are not "ruby", apparently.")_
* We cannot however plain-out remove it without bumping the major version because this is a breaking change.  
Last time we broke things, even with bumping the version, it was a train wreck. We definitely need to plan it ahead and take it up with the users this time.

**Comment by native-api** [comment]
For now, since this did turn out to be supported, we do need to fix it, and also document it. So the PR definitely goes in.

**Comment by edmorley** [comment]
Landing the fix and then deprecating after sounds good to me fwiw :-)
