### ISSUE TITLE
Python 3.9.20 checksum mismatch

### ISSUE THREAD

**Issue by willbowditch** [pyenv/pyenv#3057]
3.9.20 fails to install from the tar with the error:

```
#10 12.60 checksum mismatch: Python-3.9.20.tar.gz (file is corrupt)
#10 12.60 expected 9f2d5962c2583e67ef75924cd56d0c1af78bf45ec57035cf8a2cc09f74f4bf78, got 1e71f006222666e0a39f5a47be8221415c22c4dd8f25334cc41aee260b3d379e
```

Downloading the file I get the same md5 as the docs `896c19e5815ba990a3d1261502ea9f83`
![image](https://github.com/user-attachments/assets/d536d680-0ec9-4d45-811c-dfea03e821b3)

Which matches the sha256 above `1e71f006222666e0a39f5a47be8221415c22c4dd8f25334cc41aee260b3d379e`

**Comment by native-api** [comment]
It did pass CI in https://github.com/pyenv/pyenv/pull/3050.

Okay, the reason is that we don't actually test the `.tgz` version -- since CI machines have xz support.

Which means we need to check all the URLs in recent releases...
