### ISSUE TITLE
Missing the ncurses lib? Missing the GNU readline lib? Missing the OpenSSL lib? despite having installed dependencies using homebrew, and python-build says using those dependencies from homebrew.

### ISSUE THREAD

**Issue by qunm00** [pyenv/pyenv#3067]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS Sequoia 15.0
- [x] OS architecture (e.g. amd64): arm64-apple-darwin24.0.0, Apple Silicon/M3
- [x] pyenv version: 2.4.13
- [x] Python version: 3.10
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 16.0.0 
- [x] Please attach the debug trace of the failing command as a [debug-trace](https://gist.github.com/qunm00/4e2de223969403cc18ea288be8372375)
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory [config.log](https://gist.github.com/qunm00/873a531c3dd1ee413a1b8061ede92dc8)

**Comment by qunm00** [comment]
I solved this issue by installing dependencies with MacPort instead of homebrew.

**Comment by native-api** [comment]
**Unset any compiler-affecting envvars.**

In particular, you have LDFLAGS set pointing to x64 Homebrew -- while you're building for ARM64:

```
+(/Users/quan.nguyen/.pyenv/plugins/python-build/bin/python-build:2296): prepend_ldflags_libs -Wl,-rpath,/Users/quan.nguyen/.pyenv/versions/3.10.15/lib
+(/Users/quan.nguyen/.pyenv/plugins/python-build/bin/python-build:1414): prepend_ldflags_libs(): local args=-Wl,-rpath,/Users/quan.nguyen/.pyenv/versions/3.10.15/lib
+(/Users/quan.nguyen/.pyenv/plugins/python-build/bin/python-build:1415): prepend_ldflags_libs(): export 'LDFLAGS=-Wl,-rpath,/Users/quan.nguyen/.pyenv/versions/3.10.15/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/bzip2/lib -L/usr/local/opt/openssl@3/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/ncurses/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib'
```
