### ISSUE TITLE
How to load env variables

### ISSUE THREAD

**Issue by whatoeat2night** [pyenv/pyenv#3073]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ Yes ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ Yes ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ Yes ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ Yes ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ Yes ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ Ubuntu 22.04 ] Platform information (e.g. Ubuntu Linux 16.04):
- [ Intel ] OS architecture (e.g. amd64):
- [ 2.4.10 ] pyenv version:
- [ 3.11 ] Python version:
- [ 11.4.0 ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [ No ] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

pyenv activate my-version
source prod.env && python3 test.py

CANNOT load env variables 
I have some python libs from .so files. Usually I will manually change the PYTHONPATH and add my so files directory into PYTHONPATH, so that these libs could be load correctly. However, I CANNOT set PYTHONPATH for pyenv python version and I CANNOT set even a single environment variable. 

I REALLY don't understand.

**Comment by native-api** [comment]
You are supposed to place modules into `sys.path` directories for a Python interpreter to find them, the same as Pip does.

If you need per-version envvars, that's possible with a `pyenv-exec` hook:

`$PYENV_ROOT/plugins/<your_plugin_name>/pyenv.d/exec/<your_script_name.bash>`:
```
if [[ $PYENV_VERSION == "your_version_name" ]]; then
 MY_ENVVAR=foo
fi
```

this script will be sourced at https://github.com/pyenv/pyenv/blob/62fc392515d98067fcdd355eb6a3bc0bd08c2bc0/libexec/pyenv-exec#L40
