### ISSUE TITLE
pyenv uninstall does not remove /home/<user>/.pyenv/version if it was the global version

### ISSUE THREAD

**Issue by ramonvermeulen** [pyenv/pyenv#3074]
Platform information (e.g. Ubuntu Linux 16.04): **Ubuntu 24.04**
OS architecture (e.g. amd64): **amd64**
pyenv version: **2.4.13**

## Description

When installing and setting a certain Python version as global this version is set in the `/home/<user>/.pyenv/version` file, and can be retrieved using `pyenv python-version`. However when you perform an uninstall the `/home/<user>/.pyenv/version` file will not be reset, and I think it should.

I came across this issue while automating my own linux development environment via Ansible. If this is indeed not intended behavior I am willing to investigate and open a PR to resolve this issue.

## How to reproduce
> *NOTE `pyenv version-name` and `pyenv version` reproduce the same out for this issue*
```bash
pyenv install 3.12.6 && pyenv global 3.12.6

  Downloading Python-3.12.6.tar.xz...
  -> https://www.python.org/ftp/python/3.12.6/Python-3.12.6.tar.xz
  Installing Python-3.12.6...
  Installed Python-3.12.6 to /home/<user>/.pyenv/versions/3.12.6

pyenv version-name

  3.12.6

pyenv uninstall 3.12.6

  pyenv: remove /home/<user>/.pyenv/versions/3.12.6? [y|N] y
  pyenv: 3.12.6 uninstalled

pyenv version-name

  pyenv: version `3.12.6' is not installed (set by /home/<user>/.pyenv/version)
```

## Expected behavior
I would expect after the `pyenv uninstall 3.12.6` that the `pyenv version-name` would return `system`, at least it should imo delete the `/home/<user>/.pyenv/version` file, unless this is for a certain reason intended behavior.

## Fix
Check during `pyenv uninstall` first if the target version to uninstall is the global version, if this is the case also remove the `/home/<user>/.pyenv/version` file after the uninstall completed.

E.g. during this version loop-ing phase: https://github.com/pyenv/pyenv/blob/master/plugins/python-build/bin/pyenv-uninstall#L96

**Comment by native-api** [comment]
Do we also check the `shell` selection? Any `local` selections on the system? What if multiple versions are selected? What if the version is selected with an incomplete number via `pyenv latest` resolution?

**Comment by native-api** [comment]
It's possible to do this with a `pyenv-uninstall` `after_uninstall` hook:

`$PYENV_ROOT/plugins/<your_plugin_name>/pyenv.d/uninstall/<your_script_name.bash>`:

```
<my_hook_fn_name>() {
  if [[ $(pyenv global) == "$VERSION_NAME" ]]; then
    rm $(pyenv root)/version
  fi
}

after_uninstall <my_hook_fn_name>
```

**Comment by ramonvermeulen** [comment]
> It's possible to do this with a `pyenv-uninstall` `after_uninstall` hook:
> 
> `$PYENV_ROOT/plugins/<your_plugin_name>/pyenv.d/uninstall/<your_script_name.bash>`:
> 
> ```shell
> <my_hook_fn_name>() {
>   if [[ $(pyenv-global) == "$VERSION_NAME" ]]; then
>     rm $(pyenv-root)/version
>   fi
> }
> 
> after_uninstall <my_hook_fn_name>
> ```
> 
> this script will be sourced at
> 
> https://github.com/pyenv/pyenv/blob/62fc392515d98067fcdd355eb6a3bc0bd08c2bc0/plugins/python-build/bin/pyenv-uninstall#L64
> 
> and the function called at
> https://github.com/pyenv/pyenv/blob/62fc392515d98067fcdd355eb6a3bc0bd08c2bc0/plugins/python-build/bin/pyenv-uninstall#L93
> 
> .

Cool, I didn't knew there were hooks to configure invocations after/before you run certain commands. I was just wondering if it is expected behavior how the uninstall is now in this edge-case, if not I might look into a way to implement the removal of the `$(pyenv-root)/version` file for pyenv in general.

**Comment by native-api** [comment]
This "edge case" introduces an inconsistency, as I explained above. It'll be surprising that we do that in this case but not in other similar cases.

I suggest you make the above script into a plugin and post it on the [plugins wiki page](https://github.com/pyenv/pyenv/wiki/Plugins).

**Comment by native-api** [comment]
Moreover, if you make a plugin, other people may eventually come up with a more consistent way to handle the selected version becoming invalid.

**Comment by ramonvermeulen** [comment]
> Moreover, if you make a plugin, other people may eventually come up with and suggest a more consistent way to handle the selected version becoming invalid.

Yes I'd agree, I edited the Wiki page and created a plugin repository:

https://github.com/ramonvermeulen/pyenv-uninstall-global

Will close this issue 👍
