### ISSUE TITLE
PyEnv Unable to Install python macOS 15

### ISSUE THREAD

**Issue by PastaPastaPasta** [pyenv/pyenv#3084]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS 15
- [x] OS architecture (e.g. amd64): arm64
- [x] pyenv version: 2.4.14
```
> $ brew info pyenv                                                                                                                [±master ●●▴]
==> pyenv: stable 2.4.14 (bottled), HEAD
Python version management
https://github.com/pyenv/pyenv
Installed
/opt/homebrew/Cellar/pyenv/HEAD-6a7ecfe (1,233 files, 3.6MB) *
  Built from source on 2024-10-08 at 10:54:09
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/p/pyenv.rb
License: MIT
==> Dependencies
Required: autoconf ✔, openssl@3 ✔, pkg-config ✔, readline ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 118,347 (30 days), 324,273 (90 days), 1,234,311 (365 days)
install-on-request: 117,721 (30 days), 322,383 (90 days), 1,228,072 (365 days)
build-error: 120 (30 days)
```
- [x] Python version:
```
> $ python3 --version                                                                                                                           
Python 3.12.7
> $ which python                                                                                                                                
/Users/pasta/.pyenv/shims/python
```
- [x] C Compiler information (e.g. gcc 7.3): 
```
> $ gcc --version                                                                                                                               
Apple clang version 16.0.0 (clang-1600.0.26.3)
Target: arm64-apple-darwin24.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
  https://gist.github.com/PastaPastaPasta/f970e1abd09cb4848241da5b5931ef96
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
  https://gist.github.com/PastaPastaPasta/3719d7756d3cfeaac3e7f458f0f29ca7
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

**Comment by native-api** [comment]
```
PATH: /opt/homebrew/opt/llvm/bin/
```

https://github.com/pyenv/pyenv/wiki/Common-build-problems#keg-only-homebrew-packages-are-forcibly-linked--added-to-path

**Comment by PastaPastaPasta** [comment]
> https://github.com/pyenv/pyenv/wiki/Common-build-problems#keg-only-homebrew-packages-are-forcibly-linked--added-to-path

Hey @native-api,

Thanks for looking into this, I'm not sure if I am just being stupid, but it is not clear to me from the help text what I am actually supposed to do to be able to build! Sorry if I'm missing something obvious!

**Comment by native-api** [comment]
Remove `/opt/homebrew/opt/llvm/bin/` from PATH, wherever it is added there.

**Comment by native-api** [comment]
> (I also added a albeit small ish sponsorship to show my appreciation for ya'll!)

Thanks, we appreciate that! :100:
