### ISSUE TITLE
Unable to install Python 3.13.0

### ISSUE THREAD

**Issue by wyatt-wong** [pyenv/pyenv#3089]
I checked [Python 3.13.0](https://www.python.org/downloads/release/python-3130/) was available for a few days but I was unable to install it using pyenv, why ? I am already using pyenv 2.4.14

wyattwongMacBookPro ~ % pyenv install 3.13.0
python-build: definition not found: 3.13.0

The following versions contain `3.13.0' in the name:
  3.13.0rc3
  3.13.0rc3t

See all available versions with `pyenv install --list'.

If the version you need is missing, try upgrading pyenv:

  brew update && brew upgrade pyenv

**Comment by native-api** [comment]
https://github.com/orgs/pyenv/discussions/3088
