### ISSUE TITLE
Failure to build 3.13 with PGO

### ISSUE THREAD

**Issue by Erotemic** [pyenv/pyenv#3095]
I'm having an issue when attempting to build 3.13 with PGO on.  The main issue seems to be that `test_sqlite` and `test_unicode` have failed. 

```bash
env PYENV_DEBUG=1 \
  MAKE_OPTS="-j16" \
  PROFILE_TASK="-m test.regrtest --pgo test_array test_base64 test_binascii test_binop test_bisect test_bytes test_bz2 test_cmath test_codecs test_collections test_complex test_dataclasses test_datetime test_decimal test_difflib test_embed test_float test_fstring test_functools test_generators test_hashlib test_heapq test_int test_itertools test_json test_long test_lzma test_math test_memoryview test_operator test_ordered_dict test_pickle test_pprint test_re test_set test_sqlite test_statistics test_struct test_tabnanny test_time test_unicode test_xml_etree test_xml_etree_c"  \
  PYTHON_CFLAGS="-march=native -mtune=intel -O3 -pipe" \
  PYTHON_CONFIGURE_OPTS=" --enable-shared --enable-optimizations --with-computed-gotos --with-lto"  \
    pyenv install -f -k -v 3.13.0 -s --verbose 2>&1 | tee trace.log
```

From the logs I can see that there is an error with:

```
test_sqlite failed (uncaught exception)
test_unicode failed (uncaught exception)
```

If I dive into the specific failed build and run (based on the build logs) a simpler variant with test verbosity: 

```bash
LD_LIBRARY_PATH=/tmp/python-build.20241018162740.70490/Python-3.13.0:/home/joncrall/.local/opt/neovim/lib:/home/joncrall/.local/opt/node/lib:/home/joncrall/.local/lib::/usr/local/lib: \
    ./python -m test.regrtest --verbose3 test_sqlite test_unicode 
```

I can see the errors are caused by a ModuleNotFoundError:

```
0:00:00 load avg: 0.69 Run 2 tests sequentially in a single process
0:00:00 load avg: 0.69 [1/2] test_sqlite
test test_sqlite crashed -- Traceback (most recent call last):
ModuleNotFoundError: No module named 'test.test_sqlite'

0:00:00 load avg: 0.69 [2/2/1] test_unicode -- test_sqlite failed (uncaught exception)
test test_unicode crashed -- Traceback (most recent call last):
ModuleNotFoundError: No module named 'test.test_unicode'
```

I've never had an issue with Python 3.11 or 3.12 with the above commands. Did something change in 3.13 to remove those PGO tests, or am I do something wrong?

### Description
Pyenv Version: v2.4.16 - 770eb66ec886bb79669dae89dacf740d17fd6ed5
Platform information: Ubuntu 24.04
Arch: x64_)64
gcc: 13.2.0
[trace.log](https://github.com/user-attachments/files/17441088/trace.log)
[config.log](https://github.com/user-attachments/files/17441082/config.log)

**Comment by native-api** [comment]
Upstream problem.

`test_sqlite` is now called `test_sqlite3`, and `test_unicode` is now `test_str`.
Check `Lib/test/libregrtest/pgo.py `.

**Comment by native-api** [comment]
(edited the previous message. Not upstream problem but a problem in your `PROFILE_TASK`.

**Comment by ghost** [comment]
I'm having a similar issue in #3267 except the test I'm running is the right test, it just fails. :(
