### ISSUE TITLE
It seems shims are not working here

### ISSUE THREAD

**Issue by spacebuoy** [pyenv/pyenv#31]
MacOSX 10.8
Installed pyenv with home-brew

Added these lines to .profile

```
# For pyenv 2013-07-14
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
export PYENV_ROOT=/usr/local/opt/pyenv

Ceti$ echo $PATH
/Users/Ceti/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

But there are no shims in /Users/Ceti/.pyenv/shims

So I added the shims location to PATH in .profile /usr/local/Cellar/pyenv/shims:

```
Ceti$ echo $PATH
/Users/Ceti/.pyenv/shims:/usr/local/Cellar/pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

But commands are always sent to the system python in usr/bin

```
Ceti$ pyenv versions
* system (set by /usr/local/opt/pyenv/version)
  2.6.8
  2.7.5
  3.3.2
Ceti$ which python
/usr/bin/python
Ceti$ pyenv shell 2.7.5
Ceti$ pyenv versions
  system
  2.6.8
* 2.7.5 (set by PYENV_VERSION environment variable)
  3.3.2
Ceti$ which python
/usr/bin/python
Ceti$ python
Python 2.7.2 (default, Oct 11 2012, 20:14:37) 
[GCC 4.2.1 Compatible Apple Clang 4.0 (tags/Apple/clang-418.0.60)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Did I miss something?

Thanks in advance,
Gene

**Comment by idbill** [comment]
Something is very wrong... or you should clearly state 'this only works with Homebrew installations'

Ok... to start with... I don't (and won't) use Homebrew. (I had a very, very, very bad experience with it.)

I installed python 3.4 from the pkg installer from the python site, which puts python3 in /usr/local/bin/ as python3. (The install location cannot be changed.)

The default python installation is in /usr/bin/ as python.

pyenv versions only showed the 'system' version in /usr/bin

I couldn't figure out how to get the python 3.4 version added to the versions directory, and so it appeared that the rehash command wouldn't do anything.

I tried this and that, and something else... then finally the following:

- I added a ~/.pyenv/versions/3.4 dir ... rehash did nothing
- I added a link -s /usr/local/bin ~/.pyenv/versions/3.4/bin ... rehash still did nothing
- I then added a links -s /usr/local/bin/python3.4 /usr/local/bin/python ... finally...rehash created a bunch of links in the shim directory!
- It put a soft link for everything in that dir in shims.

At this point I don't see a benefit of pvenv over changing my path to have /usr/local/bin in front of /usr/bin
