### ISSUE TITLE
CMake might not find the correct python version

### ISSUE THREAD

**Issue by jgosmann** [pyenv/pyenv#310]
I am trying to compile a program which uses CMake. To locate Python CMake apparently looks in the normal search path for an executable file called `python?.?`. Unfortunately, with pyenv such a file might exist for a deactivated version which makes CMake think that it found a valid Python interpreter, but all that file is outputting is

```
pyenv: python2.6: command not found

The `python2.6' command exists in these Python versions:
  2.6.9
```

Would it be possible to have the shims for deactivated versions deleted entirely?
##

**Comment by Ivoz** [comment]
Straight why can't the `python2.6` just run the existing python 2.6.9 at ~/.pyenv/versions/2.6.9/bin/python2.6` ?

**Comment by jgosmann** [comment]
I'm getting the same problem when running `tox`. There might be even more programs trying to parse the version and expecting a specific output.

**Comment by yyuu** [comment]
It's not possible to hide shims of deactivated versions. It'd be better to run 'pythonX.Y --version' or so to test if the version is available or not.

**Comment by yyuu** [comment]
For tox, I'm using tox.ini as follows and it is working fine for me with pyenv. AFAIK, it would not try to find executables from PATH if it is  not configured so.

'''
[tox]
envlist = py27,py33,py34

[testenv]
commands=python setup.py test

[testenv:py27]
basepython=python2.7

[testenv:py33]
basepython=python3.3

[testenv:py34]
basepython=python3.4
'''

**Comment by jgosmann** [comment]
I have no control over the CMake issue and can't influence which command is run for the version detection. But I would assume that it runs `pythonX.Y --version` but gets confused by the output
```
pyenv: python2.6: command not found

The `python2.6' command exists in these Python versions:
  2.6.9
```
which is not the usual format. The availability of the `pythonX.Y` command seems to be tested prior and does not seem to rely on the return code.

Regarding the `tox` issue: In this case `tox` is configured to have a `py26` environment, but I was invoking `tox -e py27` and it still failed because of the deactivated `py26` shim.

**Comment by Ivoz** [comment]
@jgosmann you can try activating all your pythons at once.

    pyenv global 2.6.9 2.7.10 3.2.6 3.3.6 3.4.3

or as many as you'd like. at least then `python2.6` responds as a proper python.

**Comment by jgosmann** [comment]
Yes, that's a workaround. But it took me quite some time to figure out the problem in the first place.

**Comment by mecp** [comment]
I face the same issue. even after doing `pyenv global 3.3.0`, cmake still finds system default `2.7.10`

**Comment by Ivoz** [comment]
That problem is CMake is literally just looking for the very first python it can find; rather than the "best" python it can find.

What I've tended to do is just reconstruct my `$PATH` for shell I'm running CMAKE in, so it finds exactly the python I want it to.

**Comment by markblundeberg** [comment]
I've gotten a similar issue with cmake and pyenv. We have:
```find_package(PythonInterp 3.5 REQUIRED)```

This first goes for `python3.5` which spits out this stuff about which python 3.5.x are installed, and cmake barfs.

Solution 1 is as @Ivoz suggests: `pyenv global system 3.5.4 3.6.9 ...`

Solution 2 is that newer cmake (since 3.12) has a new python version finder system, and PythonInterp is deprecated. Instead you can do
```find_package(Python 3.5 COMPONENTS Interpreter REQUIRED)```

The benefit of solution 2 is that it will use the newest python3 version (in my case, `python3.7`). Solution 1 will actually grab and run with `python3.5`.

**Comment by native-api** [comment]
> I have no control over the CMake issue

But you do.

Use any of [the hints](https://cmake.org/cmake/help/latest/module/FindPython3.html#hints) to point CMake's Python finder to the right installation!

**Comment by paulromano** [comment]
For anyone running across this, if you are on [CMake 3.20+](https://cmake.org/cmake/help/latest/module/FindPython.html#hints), a good solution seems to be to use `Python3_FIND_UNVERSIONED_NAMES=FIRST` which will force it to try `python3` (i.e., the activated version) before trying the more specific versions (python3.6, python3.7, etc.).

**Comment by PiRK** [comment]
> Python3_FIND_UNVERSIONED_NAMES

This does not work for me. 
The error I'm getting (both with and without `set(Python3_FIND_UNVERSIONED_NAMES FIRST)`) is:
```
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python (missing: Python_EXECUTABLE Interpreter) (Required is
  at least version "3.6")

      Reason given by package:
          Interpreter: Cannot use the interpreter "/home/pierre/.pyenv/shims/python3.7"

Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindPython/Support.cmake:3180 (find_package_handle_standard_args)
  /usr/share/cmake-3.22/Modules/FindPython.cmake:519 (include)
  CMakeLists.txt:45 (find_package)

```

**Comment by gl-yziquel** [comment]
I'm having that exact same issue as PiRK when trying to build OpenCog Hyperon MeTTa from source with a pyenv.

This indeed seems to me to be an issue with cmake rather than pyenv. It is nonetheless a significant pain point of pyenv.

**Comment by Yaxit** [comment]
Agree, still an issue with CMake 3.30.

**Comment by native-api** [comment]
> > Python3_FIND_UNVERSIONED_NAMES
> 
> This does not work for me.

You're using `FindPython.cmake` rather than `FindPython3.cmake`. Thus the variable's name should be `Python_FIND_UNVERSIONED_NAMES`.
