### ISSUE TITLE
pg_config required when using sqlAlchemy

### ISSUE THREAD

**Issue by reskin89** [pyenv/pyenv#3101]
### Description

On some systems, the template should check to see if postgresql is installed, if it is not, the template render will fail when adding sqlalchemy, as in some instances, it won't be directly installed but utilized via a container.

- [MacOS] Platform information (e.g. Ubuntu Linux 16.04):
- [arm64] OS architecture (e.g. amd64):
- [ 2.4.14 ] pyenv version:
- [ 3.12.3] Python version:
- [ 15.0.0] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

```
 Error: pg_config executable not found.

      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
```

**Comment by native-api** [comment]
Not sure how this is relevant to Pyenv.
Looks like that `pg_config` executable is provided by some other software, so you need to add it to `PATH` if it's not there.
