### ISSUE TITLE
Command: `eval "$(pyenv virtualenv-init -)"` breaks Bash reverse-i-search functionality by making PS1 invalid

### ISSUE THREAD

**Issue by markuspaaso** [pyenv/pyenv#3111]
Command: `eval "$(pyenv virtualenv-init -)"` breaks Bash reverse-i-search functionality by making PS1 invalid

My environment:
Ubuntu 20.04.6 LTS
GNOME Terminal 3.36.2 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD
bash 5.0.17(1)-release (x86_64-pc-linux-gnu)
Python 3.12.5
pyenv 2.4.12-4-g6517caf5

Before activating pyenv PS1 env variable looks like this:

    \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ 

With that reverse-i-search (Ctrl+R) in Bash works smoothly without problems.

But when I add these lines into ~/.bashrc:

    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"

PS1 changes to:

    (py3125) \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ 

This breaks terminal's reverse-i-search functionality so that when editing selected search result there are extra characters added into the end of the command line.

To fix it the PS1 env should be made to look like this:

    \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}(py3125) \[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ 

With that reverse-i-search starts again to work well.

Quick workaround:

    PS1="$(echo "$PS1" | sed -E 's/^(\(.*\)) (.*\})(.*)$/\2\1 \3/')"

**Comment by native-api** [comment]
WFM in Ubuntu 24.04.1 .
Why would the added part cause any abnormabilties? It does not contain terminal control characters, not does it fall within `\[` and `\]`. So it should make the prompt longer, but Bash's calculation of how long the prompt is should stay correct. Moreover, why would _moving_ it within the prompt fix anything?

I suspect that the cause is rather some of the values that get into your prompt happen to contain terminal control characters -- so they distort the output when printed.

**Comment by native-api** [comment]
Try e.g. examining the stuff being printed with `xxd` to see if there are some extra invisible characters where they shouldn't be.

**Comment by markuspaaso** [comment]
I am using Ubuntu 20.04 default .bashrc unmodified. Here's the related .bashrc content

```
# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac
```


Here's a short clip about the issue.

https://github.com/user-attachments/assets/ea30bae1-8d63-4db0-ad4d-89efc5c4cde3

**Comment by native-api** [comment]
Reproduced the issue in Ubuntu 20.
Fixed it with `apt upgrade` and then replacing the stock Bash with one built from source from https://mirror.tochlab.net/pub/gnu/bash/bash-5.2.tar.gz (`bison` needed as a prerequisite).
