### ISSUE TITLE
`pyenv local system` setting wrong version on macOS

### ISSUE THREAD

**Issue by brunns** [pyenv/pyenv#3115]
### Description

- [x] macOS 15.1.1
- [x] pyenv 2.4.19 (installed via homebrew)

After setting `pyenv local system`, I am pointing at 3.13.0 for some reason.

```sh
$ python3 -V
Python 3.12.7

$ pyenv versions
  system
  3.9.20
  3.10.15
  3.11.10
* 3.12.7 (set by /Users/brunns/.pyenv/version)
  3.13.0

$ pyenv local system

$ pyenv versions
* system (set by /Users/brunns/temp/pyenv-system-test/.python-version)
  3.9.20
  3.10.15
  3.11.10
  3.12.7
  3.13.0

$ python3 -V
Python 3.13.0

$ pyenv which python3
/opt/homebrew/bin/python3

$ /usr/bin/python3 -V
Python 3.9.6
```

My `~/.zshrc` contains:

```sh
## pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```

**Comment by brunns** [comment]
What I'm seeing is `pyenv local system` doing nothing. I'm getting the same behavior as if I'd done `pyenv local --unset` i.e. I'm getting the global pyenv version.

**Comment by native-api** [comment]
> A special version name "system" means to use whatever Python is found on PATH after the shims PATH entry (in other words, whatever would be run if Pyenv shims weren't on PATH). Note that Pyenv considers those installations outside its control and does not attempt to inspect or distinguish them in any way.  So e.g. if you are on MacOS and have OS-bundled Python 3.8.9 and Homebrew-installed Python 3.9.12 and 3.10.2 -- for Pyenv, this is still a single "system" version, and whichever of those is first on PATH under the executable name you specified will be run.

```
$ pyenv which python3
/opt/homebrew/bin/python3
```

You're getting Python from Homebrew which is apparently the first `python3` further on PATH.

**Comment by brunns** [comment]
Ah, I see. Thanks.
