### ISSUE TITLE
pyenv cause empty lines while pressing the Enter key multiple times in the command line

### ISSUE THREAD

**Issue by GeofferyGeng** [pyenv/pyenv#3129]
### Prerequisite
- [√] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). 

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu Linux 22.04
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 2.3.36
- [x] Python version: 3.10
- [x] C Compiler information (e.g. gcc 7.3): gcc-9

before I install pyenv, press the Enter key multiple times is smooth, 
```bash
root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
```

**after install pyenv,  press the Enter key multiple times results empty line, like this**
```bash
root@host-2:~#
root@host-2:~#

root@host-2:~#

root@host-2:~#

root@host-2:~#




root@host-2:~#
root@host-2:~#






root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
root@host-2:~#
```

**Comment by native-api** [comment]
You probably install Pyenv with the installer. In this case, [this is most probably cause by the Pyenv-Virtualenv plugin](https://github.com/pyenv/pyenv-virtualenv/issues/259).

You can uninstall it if you're not using it.

**Comment by GeofferyGeng** [comment]
Thanks for your reply. I see, I'll weigh it up

> You probably install Pyenv with the installer. In this case, [this is most probably cause by the Pyenv-Virtualenv plugin](https://github.com/pyenv/pyenv-virtualenv/issues/259).
> 
> You can uninstall it if you're not using it.

Thanks for your reply. I see, I'll weigh it up
