### ISSUE TITLE
Fish shell support

### ISSUE THREAD

**Issue by fjarri** [pyenv/pyenv#32]
Is the support of fish shell planned? There are some mentions of fish on wiki, but currently pyenv does not work in it.

Namely, the problem is `pyenv init`, which tries to perform a bash `eval` inside fish, which, of course, fails. Installation/uninstallation of Python versions seems to work normally.

**Comment by lvh** [comment]
For posterity: pyenv now supports fish! Try `pyenv init` in a shell and it will tell you:

```
# Load pyenv automatically by adding
# the following to ~/.config/fish/config.fish:

status --is-interactive; and . (pyenv init -|psub)
```

**Comment by bucaran** [comment]
@yyuu `pyenv` is awesome, thanks.

I thought I would write up a small guide about what's happening here:

```fish
status --is-interactive; and . (pyenv init - | psub)
```

`status --is-interactive` sets the exit `$status` code to 0 (true) if the terminal is interactive, the type humans use reading from the keyboard. 

In Unix parlance, `-` is [usually means](http://unix.stackexchange.com/questions/16357/usage-of-dash-in-place-of-a-filename) standard input, but `pyenv` [uses](https://github.com/yyuu/pyenv/blob/master/libexec/pyenv-init#L339) it instead as a `silent` flag to skip printing a help message of how to add `pyenv` to your profile.

Now, `psub` is used for process substitution. Let me explain this via an example, say you want to `diff` two files:

```fish
diff file1 file2
```

and rather use strings:

```fish
echo $string | diff file1 -
```

but what about two strings?

```fish
diff (echo $s1 | psub) (echo $s2 | psub)
```

which in bash would be:

```bash
diff <($s1) <($s2)
```

Finally, `.` evaluates the output produced by `pyenv init...`, which is different from spawning a new process and running the output. This creates the directories at `$PYENV_ROOT` and evaluates other environment variables.

**Comment by aviddiviner** [comment]
@bucaran: Thanks for that awesome explanation! Taught me about how `psub` works.. cool!

**Comment by sooheon** [comment]
@brj with a recent version of fish, I'm getting `source: '.' command is deprecated, and doesn't work with STDIN anymore. Did you 
mean 'source' or './'?` What is the form of this incantation without using `.`, but `source` directly?

**Comment by brj** [comment]
@sooheon Yes, use `source`! 

`.` is history now :)

**Comment by sooheon** [comment]
Sorry but my question was just about the syntax of how to do that--directly replacing `.` with `source` gives an error.

**Comment by brj** [comment]
@sooheon Hmm, can you post the error?

An error could mean  `(pyenv init - | psub)` is not returning valid fish code anymore...

**Comment by sooheon** [comment]
I am now :). I had just copy pasted the snippet above in my fish.config before. Thanks.

**Comment by brj** [comment]
If you run into other issues, please create an issue in the plugin's repo, fisherman's issue tracker or just contact me directly. Happy fishing! :)

**Comment by halfnhalf** [comment]
Looks like fisherman is abandoned. Any new alternatives?

**Comment by Sphinxs** [comment]
Updates ?

**Comment by sdouche** [comment]
Fisher is alive: https://github.com/jorgebucaran/fisher

**Comment by halfnhalf** [comment]
Sorry, yes fisher is alive but what I meant was the pyenv fisher package is abandoned 
https://github.com/fisherman/pyenv

**Comment by Eduard-gan** [comment]
There's no need to use abandoned fisher plugin.

all you need is to pase this in **~/.config/fish/config.fish** :

```
set -x PYENV_ROOT $HOME/.pyenv
set -x PATH $PYENV_ROOT/bin $PATH
status --is-interactive; and . (pyenv init -|psub)
status --is-interactive; and . (pyenv virtualenv-init -|psub)
```
If you're pasting one line mentioned above:
status --is-interactive; and . (pyenv init -|psub)
you'll got the error:

> ~/.config/fish/config.fish (line 1): pyenv init -|psub
>                                      ^
> in command substitution
> 	called on line -1 of file ~/.config/fish/config.fish
> 
> from sourcing file ~/.config/fish/config.fish
> 	called during startup
> 
> source: '.' command is deprecated, and doesn't work with STDIN anymore. Did you mean 'source' or './'?
Setting of PYENV_ROOT and PATH enviroment variables before the line which mentions pyenv is crucial!

**Comment by ezdac** [comment]
This doesn't work anymore in fish 3.1.0:

> ```
> status --is-interactive; and . (pyenv init -|psub)
> status --is-interactive; and . (pyenv virtualenv-init -|psub)
> ```

And can be replaced until the issue is resolved (and it will work after that as well) with this in **~/.config/fish/config.fish**:

```
status --is-interactive; and pyenv init - | source
status --is-interactive; and pyenv virtualenv-init - | source
```

As of this issue comment:
https://github.com/fish-shell/fish-shell/issues/6613#issuecomment-588398405

**Comment by joshfriend** [comment]
The readme has already been updated to suggest `source` instead of `psub` for fish users.
