### ISSUE TITLE
"... command exists in these Python versions" even if there is only one version.

### ISSUE THREAD

**Issue by rnhmjoj** [pyenv/pyenv#34]
Unfortunately I have encountered another problem. 
I have installed python 2.7.5 with `pyenv install 2.7.5` and then `pyenv rehash`
Now if I type `python2.7` I get 

```
pyenv: python2.7: command not found
The `python2.7' command exists in these Python versions:
2.7.5
```

I think this message should appear if there are others pythonx.y or pythonx version and the command is ambiguous but I have only one python version.
If I set `pyenv local 2.7.5` then `python2` or `python2.7`will start python correctly. 

Am I missing something? Is possible to set the default pythonx version?

**Comment by cleocn** [comment]
pyenv local 2.7  3.4.7 

it's work for me.

https://github.com/samstav/circleci-python-sandbox/issues/1

**Comment by pedzed** [comment]
> I'm afraid that kind of implicit behaviour might introduce the confusions of Python versions on runtime. I don't like to change current behaviour.

That's fine, but at least provide a more friendly error message? Now people are required to look the problem up themselves...

**Comment by dmayle** [comment]
I develop my own command line tools in python in their own virtualenvs, so I want to be able to launch a shim in it's own environment if it exists in only one environment, so this is perfect for me.  Here's a modified version of the script that can handle  de-duping virtualenvs (e.g. a virtualenv called "MINE" shows up as both "MINE" and "X.Y.Z/envs/MINE")

```
if [ -n "$PYENV_COMMAND" ] && [ ! -x "$PYENV_COMMAND_PATH" ]; then
  # What versions are there for this command
  versions=($(pyenv-whence "${PYENV_COMMAND}" 2>/dev/null || true))
  dedup_versions=($(pyenv-whence "${PYENV_COMMAND}" 2>/dev/null || true))
  # Resolve symlinks in versions
  for index in ${!versions[*]}; do
    dedup_versions[$index]="$(greadlink -f "${PYENV_ROOT}/versions/${versions[$index]}")";
  done
  # De-dup the list of versions
  dedup_versions=($(echo "${dedup_versions[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
  if [ "${#dedup_versions[@]}" -eq 1 ]; then
    PYENV_COMMAND_PATH="${PYENV_ROOT}/versions/${versions[0]}/bin/${PYENV_COMMAND}"
  fi
fi
```

**Comment by abiro** [comment]
This is the simplest solution I've found to use 3.5-3.7 for testing with tox while using 3.6 as the default python:
```
pyenv install 3.6.6
pyenv install 3.5.6
pyenv install 3.7.0
pyenv global 3.6.6 3.5.6 3.7.0
```
After this:
```
python --version 
> Python 3.6.6

python3 --version
> Python 3.6.6

python3.6 --version
> Python 3.6.6

python3.5 --version
> Python 3.5.6

python3.7 --version
> Python 3.7.0
```
Hope this helps somebody!

**Comment by maffei2443** [comment]
Running 
```python
pyenv shell 3.X.X
```
before calling `idle` did solve the problem for me.

**Comment by petervandenabeele** [comment]
> This is the simplest solution I've found to use 3.5-3.7 for testing with tox while using 3.6 as the default python:
> 
> ```
> pyenv install 3.6.6
> pyenv install 3.5.6
> pyenv install 3.7.0
> pyenv global 3.6.6 3.5.6 3.7.0
> ```
> 
> After this:
> 
> ```
> python --version 
> > Python 3.6.6
> 
> python3 --version
> > Python 3.6.6
> 
> python3.6 --version
> > Python 3.6.6
> 
> python3.5 --version
> > Python 3.5.6
> 
> python3.7 --version
> > Python 3.7.0
> ```
> 
> Hope this helps somebody!

Something I found is that by reverting the order of the setting of the `pyenv global`, a consecutive `poetry install` will by default pick the first one (the most recent/highest version, 3.11.3 here), which I prefer:

```
pyenv global 3.11.3 3.10.11 3.9.16 3.8.16
```
