### ISSUE TITLE
pyenv shell command don't work with custom installation path

### ISSUE THREAD

**Issue by rodfersou** [pyenv/pyenv#46]
I use a custom path installation for my pyenv (look at these links https://bitbucket.org/rodfersou/brews/src/7bd0fa453735a420b0ada02fedf61b9c7ad5cfa3/install_pyenv.sh?at=default https://bitbucket.org/rodfersou/brews/src/7bd0fa453735a420b0ada02fedf61b9c7ad5cfa3/activate?at=default#cl-5 )

Everything looks fine but the pyenv shell command don't work with this configuration:

$ pyenv shell 2.4.6 
pyenv: no such command `shell'

**Comment by jangho** [comment]
Cool

**Comment by shoark7** [comment]
Thanks man, it works :)

**Comment by channprj** [comment]
Thanks. Sometimes I forgot adding init code and visit this page. :sweat_smile:

**Comment by sparkleholic** [comment]
🔑 to solve a problem.
Thanks!
