### ISSUE TITLE
After setting pyenv global system 3.5.0 3.4.3, pip3.4 claims to not exist

### ISSUE THREAD

**Issue by mpacer** [pyenv/pyenv#470]
So I've recently come across `pyenv`, which I've been trying to set up so that I can see why `virtualenv` is disallowing the use of `python3` as a python path (see http://serverfault.com/questions/707683/python3-virtualenv-importerror-no-module-named-configparser for a similar error). 

One of the things I tried to do in pursuing this is to install `virtualenv` using `pip3.4`, but when I did this, I ran into a different error that I think must be related to `pyenv` given its traceback:

```
/usr/local/Cellar/pyenv/20151103/libexec/pyenv-exec: /usr/local/bin/pip3.4: /usr/local/opt/python3/bin/python3.4: bad interpreter: No such file or directory
/usr/local/Cellar/pyenv/20151103/libexec/pyenv-exec: line 47: /usr/local/bin/pip3.4: Undefined error: 0
```

Which when i actually check that directory, doesn't have any file, directory or symlink linked to `python3.4`, but I can run `python3.4` as a command because it has an executable in `~/.pyenv/shims/python3.4` which includes the line 

```
exec "/usr/local/Cellar/pyenv/20151103/libexec/pyenv" exec "$program" "$@"
```

which I assume is where the `python3.4` executable is actually located, which suggests that somehow `pip3.4` is linked to a nonexistent `python3.4` that once existed under `python3`.

I ran `pyenv rehash` after seeing that suggested elsewhere, it doesn't do anything.
##

**Comment by yyuu** [comment]
@michaelpacer can you give me minimal command line to reproduce the problem you met?

**Comment by justinmakaila** [comment]
@yyuu I'm having a similar issue. No installed versions of `python` work, aside from the system version:

```
~ $ pyenv -v
pyenv 20160202
~ $ pyenv versions
  system
  2.7.10
* 2.7.11 (set by ~/.pyenv/version)
  3.5.0
~ $ pyenv global 2.7.10
~ $ python -V
/usr/local/Cellar/pyenv/20160202/libexec/pyenv-exec: line 47: /Users/MYUSER/.pyenv/versions/2.7.10/bin/python: No such file or directory
~ $ pyenv global system
~ $ python -V
Python 2.7.10
~ $ 
```
Any advice? I've tried `pyenv rehash`, but nothing changes.

**Comment by tjsoftworks** [comment]
I have had this issue also.... the issues are most often in the PATH but try looking thru all environment variables related to py*
>>env | grep -i py

Sat Mar 12 13:43:28 username@onA_Yosemite_based_Mac:~ >>env | grep -i py
PYENV_ROOT=/usr/local/opt/pyenv
PYENV_VIRTUALENV_INIT=1
PATH=/opt/chefdk/bin:/Users/tjadmin/.chefdk/gem/ruby/2.1.0/bin:/opt/chefdk/embedded/bin:**/usr/local/Cellar/pyenv-virtualenv/20160202/shims:/usr/local/opt/pyenv/libexec:/usr/local/opt/pyenv/plugins/python-build/bin:/usr/local/opt/pyenv/shims:/usr/local/opt/pyenv/bin**:/usr/local/var/rbenv/shims:/Users/tjadmin/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:
PYTHONSTARTUP=/Users/tjadmin/.pystartup
PYENV_SHELL=bash

**Comment by chrahunt** [comment]
For anyone running into this problem, please try the following:

1. Install the latest pyenv following the instructions in the README applicable for your platform
2. See the advice from @tjsoftworks concerning your PATH, cleaning it up if necessary

If these still do not help, then please feel free to open a new issue and provide details.
