### ISSUE TITLE
Test failures related to homebrew on Arch Linux

### ISSUE THREAD

**Issue by blueyed** [pyenv/pyenv#480]
I am getting the following test failures on an Arch Linux system:

```
cd plugins/python-build && /home/user/.pyenv/bats/bin/bats ${CI:+--tap} test
 ✓ not enough arguments for python-build
 ✓ extra arguments for python-build
 ✓ yaml is installed for python
 ✓ apply python patch before building
 ✓ apply python patch from git diff before building
 ✗ yaml is linked from Homebrew
   (from function `assert_success' in file test/test_helper.bash, line 86,
    in test file test/build.bats, line 152)
     `assert_success' failed
   command failed with exit status 1
   output: Downloading yaml-0.1.6.tar.gz...
   -> http://pyyaml.org/download/libyaml/yaml-0.1.6.tar.gz
   error: failed to download yaml-0.1.6.tar.gz

   BUILD FAILED (Arch rolling using python-build 20151105-4-g9ca7de5)
 ✗ readline is linked from Homebrew
   (from function `unstub' in file test/test_helper.bash, line 44,
    in test file test/build.bats, line 179)
     `unstub brew' failed
 ✗ readline is not linked from Homebrew when explicitly defined
   (from function `unstub' in file test/test_helper.bash, line 44,
    in test file test/build.bats, line 207)
     `unstub brew' failed
```
##

**Comment by yyuu** [comment]
brew failures on Linux? weird....

**Comment by blueyed** [comment]
Yeah.. there is no `brew` command installed, and I did not look to closely at the tests.

But I've found another issue, likely related to PATH ordering, which I've submitted to https://github.com/sstephenson/rbenv/pull/819 for now.

**Comment by yyuu** [comment]
Usually I'm running tests on Debian GNU/Linux and it is passing w/o any failures. There would be some environment specific problem on it. I'll try to reproduce this on Arch Linux image later.

BTW, I finally realized that there are some differences in test results on Linux and OS X.  `test/version-file-read.bats` never succeeded on my OS X 10.11.1, probably due to different behaviour of `sed` between BSD and GNU :disappointed: I'll try to fix it later....

**Comment by yyuu** [comment]
@blueyed can you provide me some minimum Docker image or Dockerfile to reproduce the issue?

**Comment by blueyed** [comment]
@yyuu 
Maybe just using this image is enough?
https://hub.docker.com/r/base/archlinux/

**Comment by blueyed** [comment]
I could not reproduce it with this Dockerfile:

```
FROM pritunl/archlinux
RUN pacman -Syu --noconfirm git make
RUN git clone https://github.com/yyuu/pyenv
RUN cd pyenv && make test
```

But it failed with another test:
```
not ok 79 non-writable shims directory
# (from function `flunk' in file test/test_helper.bash, line 41,
#  from function `assert_failure' in file test/test_helper.bash, line 54,
#  in test file test/rehash.bats, line 24)
#   `assert_failure "pyenv: cannot rehash: ${PYENV_ROOT}/shims isn't writable"' failed
# expected failed exit status
```

**Comment by blueyed** [comment]
I am seeing a test failure locally now also with the main tests:

```
 ✓ no executable found
/home/user/.pyenv/bats/libexec/bats-exec-test: line 197: sed: command not found
/home/user/.pyenv/bats/libexec/bats-exec-test: line 202: sed: command not found
/home/user/.pyenv/bats/libexec/bats-exec-test: line 260: sed: command not found
 ✗ no executable found for system version
   (from function `teardown' in file test/test_helper.bash, line 33,
    from function `bats_teardown_trap' in file bats/libexec/bats-exec-test, line 231,
    from function `main' in test file bats/libexec/bats-exec-test, line 1)
     `' failed with status 127
```

Echoing $PATH there shows it as:

> /tmp/pyenv.3Wt/root/shims:/home/user/.pyenv/test/libexec:/home/user/.pyenv/test/../libexec:/tmp/pyenv.3Wt/bin:/tmp/pyenv.3Wt/usr-bin:/tmp/pyenv.3Wt/bin:/tmp/pyenv.3Wt/usr-sbin:/tmp/pyenv.3Wt/sbin:/usr/local/bin

This is caused by 3405c4d0, according to git-bisect (`git bisect run sh -c 'PATH="./bats/bin:$PATH" bats test/which.bats`):

```
3405c4d03cc4b1e63c2829e2565f7651b09bebb1 is the first bad commit
commit 3405c4d03cc4b1e63c2829e2565f7651b09bebb1
Author: Mislav Marohnić <X>
Date:   Fri Nov 13 22:57:22 2015 -0500

    Fix error message when command is not found for "system" version
    
    If `foo` didn't exist and `RBENV_VERSION=system rbenv which foo` was
    called, the error message used to be misleading:
    
        rbenv: version `system' is not installed
    
    Instead, have the error message simply say that the command was not found.
    
    Fixes #770

:040000 040000 2ce66aaf64882bf2147a6a05369a7bfbbd79d86b a5d2ad4717762e534ea7c3126157550e3d2f3515 M	libexec
:040000 040000 ceff1f153d01cb0f8ae6d545b9570a9de25d2b15 f51fb92da9e329ce0abc03c34df7abe8a413dd4e M	test
bisect run success
```

**Comment by blueyed** [comment]
Hmm, not very useful probably, since it's a commit with rbenv stuff in there?!

**Comment by yyuu** [comment]
@blueyed I confirmed the reproduction of the failure of `non-writable shims directory` on Arch image....

I also confirmed that the weird behaviour on Arch. In this example, `touch` should fail since the current user doesn't have write permission to the directory.

This could be the cause of the test failure. I'm still not sure what is making this, though :disappointed: 

```sh
[root@240f1b3c795a ~]# mkdir -p /tmp/foo
[root@240f1b3c795a ~]# ls -ld /tmp/foo/
drwxr-xr-x 2 root root 4096 Dec 20 08:55 /tmp/foo//
[root@240f1b3c795a ~]# chmod -w /tmp/foo/
[root@240f1b3c795a ~]# ls -ld /tmp/foo/
dr-xr-xr-x 2 root root 4096 Dec 20 08:55 /tmp/foo//
[root@240f1b3c795a ~]# touch /tmp/foo/bar
[root@240f1b3c795a ~]# ls -l /tmp/foo/bar
-rw-r--r-- 1 root root 0 Dec 20 08:56 /tmp/foo/bar
```

**Comment by yyuu** [comment]
Ah, ^ isn't weird since the exec user was `root`. The test should not be ran by `root` to pass.

**Comment by yyuu** [comment]
It seems Arch has OpenSSL at `/bin/openssl` and it could be the cause of the failure related to `brew`. I expect the tests of rbenv and ruby-build will also fail due to same reason.

**Comment by blueyed** [comment]
Thanks!

I am still seeing the errors from the original issue though, and can reproduce them using this Dockerfile:

```
FROM pritunl/archlinux

RUN pacman -Syu --noconfirm git make

# ADD . pyenv
RUN git clone https://github.com/yyuu/pyenv
RUN chown -R nobody pyenv
RUN cd pyenv && su -s /bin/bash -c 'make test' nobody
```

```
not ok 6 yaml is linked from Homebrew
# (from function `assert_success' in file test/test_helper.bash, line 86,
#  in test file test/build.bats, line 152)
#   `assert_success' failed
# command failed with exit status 1
# output: Downloading yaml-0.1.6.tar.gz...
# -> http://pyyaml.org/download/libyaml/yaml-0.1.6.tar.gz
# error: failed to download yaml-0.1.6.tar.gz
# 
# BUILD FAILED (Linux 4.2.5-1-ARCH using python-build 20151210-33-g3031cb9)
not ok 7 readline is linked from Homebrew
# (from function `unstub' in file test/test_helper.bash, line 44,
#  in test file test/build.bats, line 179)
#   `unstub brew' failed
not ok 8 readline is not linked from Homebrew when explicitly defined
# (from function `unstub' in file test/test_helper.bash, line 44,
#  in test file test/build.bats, line 207)
#   `unstub brew' failed
```

**Comment by blueyed** [comment]
Poking around in the test, I've noticed that `curl` is stubbed (should it be `false`?!).

The failure comes from:

    install_fixture definitions/needs-yaml
    assert_success

**Comment by blueyed** [comment]
The first issue can be fixed by:
```diff
diff --git i/plugins/python-build/test/build.bats w/plugins/python-build/test/build.bats
index b8aa3ac..3b217d2 100644
--- i/plugins/python-build/test/build.bats
+++ w/plugins/python-build/test/build.bats
@@ -140,6 +140,7 @@ OUT
 }
 
 @test "yaml is linked from Homebrew" {
+  cached_tarball "yaml-0.1.6"
   cached_tarball "Python-3.2.1"
 
   brew_libdir="$TMP/homebrew-yaml"

```

**Comment by blueyed** [comment]
Does `unstub brew` maybe just fail because `brew` does not exist (and is not used by `make install`), and the expected stuff from the stub is not triggered?
Should the brew related tests get skipped in this case?

**Comment by blueyed** [comment]
> It seems Arch has OpenSSL at /bin/openssl

I have it at `/usr/bin/openssl`.

**Comment by yyuu** [comment]
Stubbing `curl` and `yaml` must not be a solution for "yaml is linked from Homebrew" case since it should not download & build `yaml`.

And, for `openssl` issue, I realized that there are 2 executables of `openssl` on Arch Linux.... I suspect the cause of the failure could be unmatched call count of `brew`. I'm still not sure why it happens, though.

```
[root@e7e946be78b9 /]# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[root@e7e946be78b9 /]# ls -l /bin/openssl /usr/bin/openssl
-rwxr-xr-x 1 root root 575832 Dec  3 19:23 /bin/openssl
-rwxr-xr-x 1 root root 575832 Dec  3 19:23 /usr/bin/openssl
[root@e7e946be78b9 /]# sha256sum /bin/openssl /usr/bin/openssl
271cf351ae8ff29254c7ce45dec36aa5c006737405cbc5f04231c3011a2ccdb9  /bin/openssl
271cf351ae8ff29254c7ce45dec36aa5c006737405cbc5f04231c3011a2ccdb9  /usr/bin/openssl
```

**Comment by tigerjack** [comment]
Still seeing the same errors. Can this be a source of problems?

**Comment by native-api** [comment]
A trace would be needed to get to the bottom of this. Bats is a set of Bash scripts so it can be traced.

* First reduce the test suite to a minimal reproducing example

* Then

```
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
bash -x <path-to>/bats test
```

**Comment by native-api** [comment]
Alternatively, `set -x` <...> `set +x` around the test code itself may be sufficient to see what exactly fails.
