### ISSUE TITLE
Installation of a copy of Python failed (Mac OS X 10.8.4)

### ISSUE THREAD

**Issue by Arbitrageur** [pyenv/pyenv#55]
My system is 
- Mac OS X 10.8.4
- Homebrew
- zsh 5.0.2

I installed Python 2.7.5 using precompiled installer from http://www.python.org.

After that, I tried to install Python 3.3.2 using pyenv with --enable-frameworks

> export CONFIGURE_OPTS=--enable-framework --enable-toolbox-glue --enable-ipv6 --enable-big-digits --enable-unicode --with-threads
> pyenv install 3.3.2

But failed and I got these messages:

Creating directory /Library/Frameworks/Python.framework/Versions/3.3/Resources/English.lproj
install: mkdir /Library/Frameworks/Python.framework/Versions/3.3: Permission denied
Creating directory /Library/Frameworks/Python.framework/Versions/3.3/lib
install: mkdir /Library/Frameworks/Python.framework/Versions/3.3: Permission denied
make: **\* [frameworkinstallstructure] Error 71

I think the files are expected to be installed in $PYENV_ROOT/versions.

When I tried with Python 2.7.5, I got the same result.

I also tried with --prefix=$HOME/.pyenv/versions
But I got nothing.

Thanks.

**Comment by rcarmo** [comment]
This is broken in 2018. See #1003.
