### ISSUE TITLE
Strange pyenv build issue with psycopg2 and symlinks

### ISSUE THREAD

**Issue by BradRuderman** [pyenv/pyenv#568]
Getting the following error. I think its related to the following resources:
https://github.com/yyuu/pyenv/issues/425
http://stackoverflow.com/questions/22450848/error-loading-psycopg2-module-when-installed-from-a-wheel

I think its related to pyenv though not sure. 

```
>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/opt/pyenv/versions/adwords/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: dlopen(/usr/local/opt/pyenv/versions/adwords/lib/python2.7/site-packages/psycopg2/_psycopg.so, 2): Symbol not found: _PyUnicodeUCS2_AsEncodedString
  Referenced from: /usr/local/opt/pyenv/versions/adwords/lib/python2.7/site-packages/psycopg2/_psycopg.so
  Expected in: flat namespace
 in /usr/local/opt/pyenv/versions/adwords/lib/python2.7/site-packages/psycopg2/_psycopg.so
```

I have pyenv, pyenv-virtualenv, and postgres all installed via home-brew on mac os x 10.11.4.

![1__python__python2_7__and_new_issue_ _psycopg_psycopg2](https://cloud.githubusercontent.com/assets/2366784/14336626/c8e57ce0-fc1a-11e5-820b-634edd1426a6.png)

In addition here is my homebrew list:

![1__bradruderman_brads-macbook-pro_____zsh_](https://cloud.githubusercontent.com/assets/2366784/14336646/01f20440-fc1b-11e5-9f6a-e4f7a87039e1.png)
##

**Comment by yyuu** [comment]
Did you specify some configure option (e.g. PYTHON_CONFIGURE_OPTS) when building CPython with pyenv?

**Comment by BradRuderman** [comment]
Nope! Just normal. I am using zsh with the pyenv plugin to activate.
B

Sent from my iPhone
On Wed, Apr 6, 2016 at 9:08 PM, Yamashita, Yuu <notifications@github.com> wrote:
Did you specify some configure option (e.g. PYTHON_CONFIGURE_OPTS) when building CPython with pyenv?

**Comment by cristiano2lopes** [comment]
I have the same problem. Created python versions with system python active. Created a virtualenv from python 2.7.11 and runned pip install. I then get the same error described above.

**Comment by bryan0** [comment]
Just tried using pyenv virtualenv and also get this same error with python 2.7.10, although using 2.7.12 works.  if i use my system 2.7.10 it builds without errors.  I installed everything using brew.

**Comment by bryan0** [comment]
ok upgrading to the latest version (2.6.2) works for me.

**Comment by john-k-rice** [comment]
Been battling this as well.  The only thing I found that worked is to symlink the Library/Frameworks python site-packages/psycopg2 to virtualenv site-packages/psycopg2.  For example (executed from the virtualenv lib/python3.4/site-packages directory): 
ln -s /opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/psycopg2 psycopg2

What did you upgrade to 2.6.2?

**Comment by bryan0** [comment]
@john-k-rice yeah I upgraded psycopg.  I edited my comment to clarify this.
