### ISSUE TITLE
boost::python and pyenv

### ISSUE THREAD

**Issue by tgy** [pyenv/pyenv#585]
I'd like to write a **C++** python module with **boost::python**.

What is the procedure to make it work with pyenv?

I am asking myself the following questions:
- Do I need to build boost::python specifically for every python version I installed with pyenv?
- If so, how do I do that?

Thanks! :smile: 
##

**Comment by yyuu** [comment]
I guess you need to build boost:: python against pyenv built python. Probablly boost::python's build script must be providing some configure option to specify path to python installation.

// I need some answer from active boost users...

**Comment by astocko** [comment]
You just need to set the path in a Boost.Build configuration file. 

# 3.6.0 example
```
echo "using python : : ~/.pyenv/versions/3.6.0/bin/python ;" > ~/user-config.jam
./bootstrap.sh
./b2
sudo ./b2 install
```

**Comment by chrahunt** [comment]
Thanks @astocko. @tgy, let us know if you need any more assistance with this.
