### ISSUE TITLE
Can't figure out how to build a python that uses the .SO file

### ISSUE THREAD

**Issue by mark0978** [pyenv/pyenv#65]
All of this is with 2.7.5

We are trying to build on Centos6, the python pyenv builds produces a libpython.a, but not a libpython.so

We have an importable module we build against python using libboostpython.  These need to link against a libpython.so

We also need to run under mod_wsgi in apache, so the shims situation is problemmatic.  I've set PYTHONHOME to point at the pyenv version of python, but it still goes after 2.6 modules on the main system.

Maybe I'm wrong here, but I am thinking if I could build python to use the .so library, and then link my extension against it, it would work (it does on Debian where I'm NOT using pyenv because I have 2.7 as the base python)

How do you get pyenv to build a python that is based on libpython.so instead of libpython.a?

python is 6MB on Centos, vs 2MB on Debian, I'm assuming that is because libpython.so makes up the other 4MB.

**Comment by pingsoli** [comment]
I use fish shell, what should I do ?

`env PYTHON_CONFIGURE_OPTS="--enable-shared" LD_LIBRARY_PATH=~/.pyenv/versions/2.7.5/lib/ pyenv install -k 2.7.5` works in bash shell, but not in fish shell.

**Comment by pingsoli** [comment]
I solved it.

`eval (YTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.6.5)` works in fish shell.
