### ISSUE TITLE
Install 32bit python on 64bit system

### ISSUE THREAD

**Issue by s1341** [pyenv/pyenv#66]
Some applications require a 32bit python. These apps link (dynamically) against the libpythonXX.so. 

I'm working on adding support for installing a 32bit python using pyenv install and will submit a pull request if necessary when I'm done. 

Is this something others are interested in?

**Comment by disconnect3d** [comment]
I know that this is old and closed but :+1: for 32 bit targets. Any possibility to rethink adding this into Pyenv?

Shouldn't pyenv be an ultimate and easy installer for any Python version?

**Comment by xoviat** [comment]
The posted solution on this issue did not work for me:

```
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?
```

Honestly the approach that this project has taken of shying away with dealing with these problems has simply pushed the problems downstream. And pyenv is in fact the only way on installing Python onto CI containers.
