### ISSUE TITLE
pyenv install -l slow compared to rbenv/nodenv

### ISSUE THREAD

**Issue by rlex** [pyenv/pyenv#675]
Not really an issue (it's still below one second and it's not something you do very often), but this still looks like a bug.

```
lex@lex-nb ❯ cat pyenv-list.sh
pyenv install -l
lex@lex-nb ❯ time ./pyenv-list.sh
./pyenv-list.sh  0.25s user 0.24s system 95% cpu 0.519 total
```

As i said, rbenv/nodenv performs much faster:
rbenv:
0.03s user 0.04s system 124% cpu 0.056 total
nodenv:
0.03s user 0.03s system 124% cpu 0.053 total

No additional plugins installed.
##

**Comment by chrahunt** [comment]
On the latest version of pyenv I see

```
real    0m0.080s
user    0m0.071s
sys     0m0.037s
```

the first time I run `pyenv install -l` and this is typical for subsequent runs

```
real    0m0.031s
user    0m0.031s
sys     0m0.013s
```

**Comment by chrahunt** [comment]
If you're still seeing this let us know and we can investigate.
