### ISSUE TITLE
Question with sqlite3

### ISSUE THREAD

**Issue by x1ah** [pyenv/pyenv#678]
Hello, just now, I have created a new virtualenv by `pyenv virtualenv foo 3.5.1` then switch to it(`pyenv local foo`), before this, already installed all [requirements](https://github.com/yyuu/pyenv/wiki/Common-build-problems#requirements) when installed pyenv,  when I run python shell and `import sqlite3`, It raise ImportError, 

``` python
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xiah/.pyenv/versions/3.5.1/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/home/xiah/.pyenv/versions/3.5.1/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3
```

I have Google this problem and most of answer is install `libsqlite3-dev`, but it already installed.
and then i change Python to system(Ubuntu 14.04)  python version, It worked.
So, Can you give me some suggests? THX!!
##

**Comment by Samureus** [comment]
@x1ah hi, do you still have this issue? I just tested using 3.5.3 on Ubuntu 16.04:

```python
$ pyenv local 3.5.3 
$ python
Python 3.5.3 (default, Jan 23 2017, 20:47:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _sqlite3
>>> dir(_sqlite3)
['Cache', 'Connection', 'Cursor', 'DataError', 'DatabaseError', 'Error', 'IntegrityError', 'InterfaceError', 'InternalError', 'NotSupportedError', 'OperationalError', 'OptimizedUnicode', 'PARSE_COLNAMES', 'PARSE_DECLTYPES', 'PrepareProtocol', 'ProgrammingError', 'Row', 'SQLITE_ALTER_TABLE', 'SQLITE_ANALYZE', 'SQLITE_ATTACH', 'SQLITE_CREATE_INDEX', 'SQLITE_CREATE_TABLE', 'SQLITE_CREATE_TEMP_INDEX', 'SQLITE_CREATE_TEMP_TABLE', 'SQLITE_CREATE_TEMP_TRIGGER', 'SQLITE_CREATE_TEMP_VIEW', 'SQLITE_CREATE_TRIGGER', 'SQLITE_CREATE_VIEW', 'SQLITE_DELETE', 'SQLITE_DENY', 'SQLITE_DETACH', 'SQLITE_DROP_INDEX', 'SQLITE_DROP_TABLE', 'SQLITE_DROP_TEMP_INDEX', 'SQLITE_DROP_TEMP_TABLE', 'SQLITE_DROP_TEMP_TRIGGER', 'SQLITE_DROP_TEMP_VIEW', 'SQLITE_DROP_TRIGGER', 'SQLITE_DROP_VIEW', 'SQLITE_IGNORE', 'SQLITE_INSERT', 'SQLITE_OK', 'SQLITE_PRAGMA', 'SQLITE_READ', 'SQLITE_REINDEX', 'SQLITE_SELECT', 'SQLITE_TRANSACTION', 'SQLITE_UPDATE', 'Statement', 'Warning', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'adapt', 'adapters', 'complete_statement', 'connect', 'converters', 'enable_callback_tracebacks', 'enable_shared_cache', 'register_adapter', 'register_converter', 'sqlite_version', 'version']
>>> 
```
CPython 3.5.X is built from source, so if you have `libsqlite3-dev` it should be detected at

https://github.com/pyenv/pyenv/blob/master/plugins/python-build/bin/python-build#L1634

**Comment by Samureus** [comment]
Closing for now, feel free to reopen issue if it happens again.

**Comment by vijay120** [comment]
I am having this problem as well on Ubuntu using Pyenv on 3.5.3:

```
>>> import _sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named '_sqlite3'
```

**Comment by lamenezes** [comment]
I've had the same problem using Ubuntu:

```python
$ pyenv local 3.6.1
$ python
Python 3.6.1 (default, Apr 26 2017, 22:04:06) 
[GCC 5.2.1 20151010] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named '_sqlite3'
```

Doing the following solved the problem:

1. Install `libsqlite3-dev`: `sudo apt install libsqlite3-dev`
2. Re-install pyenv: `pyenv install 3.6.1`

Maybe this can fix the issue for you @vijay120

**Comment by yuehaowang** [comment]
I met several warnings on missing dependencies while installing Python 3.5.4 via pyenv. Then I found I cannot import sqlite3. I tried to install all the requirements mentioned in [Common build problems](https://github.com/pyenv/pyenv/wiki/common-build-problems) and reinstall Python 3.5.4 via pyenv. I managed to import sqlite3 eventually in this way.

**Comment by hirusi** [comment]
> I met several warnings on missing dependencies while installing Python 3.5.4 via pyenv. Then I found I cannot import sqlite3. I tried to install all the requirements mentioned in [Common build problems](https://github.com/pyenv/pyenv/wiki/common-build-problems) and reinstall Python 3.5.4 via pyenv. I managed to import sqlite3 eventually in this way.

This still works in 2021 on Ubuntu 20.04 and Python 3.8.6. 🙃

**Comment by guettli** [comment]
Maybe this helps someone.

While installing python3.6.9 the output was:

```
guettli@yoga15:~/$ pyenv install 3.6.9

Downloading Python-3.6.9.tar.xz...
-> https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tar.xz
Installing Python-3.6.9...
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib? <==============
```

Then I did:

```
sudo apt install libsqlite3-dev
```

Then again:

```
user@host> pyenv install 3.6.9

pyenv: /home/guettli/.pyenv/versions/3.6.9 already exists
continue with installation? (y/N) y

Downloading Python-3.6.9.tar.xz...
-> https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tar.xz
Installing Python-3.6.9...
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Installed Python-3.6.9 to /home/guettli/.pyenv/versions/3.6.9
```

 ... and now the sqlite error is gone. :-)

**Comment by moshfiqrony** [comment]
> I've had the same problem using Ubuntu:
> 
> ```python
> $ pyenv local 3.6.1
> $ python
> Python 3.6.1 (default, Apr 26 2017, 22:04:06) 
> [GCC 5.2.1 20151010] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import _sqlite3
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named '_sqlite3'
> ```
> 
> Doing the following solved the problem:
> 
> 1. Install `libsqlite3-dev`: `sudo apt install libsqlite3-dev`
> 2. Re-install pyenv: `pyenv install 3.6.1`
> 
> Maybe this can fix the issue for you @vijay120

This worked for me like a charm

**Comment by jalajc** [comment]
> I've had the same problem using Ubuntu:
> 
> ```python
> $ pyenv local 3.6.1
> $ python
> Python 3.6.1 (default, Apr 26 2017, 22:04:06) 
> [GCC 5.2.1 20151010] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import _sqlite3
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named '_sqlite3'
> ```
> 
> Doing the following solved the problem:
> 
> 1. Install `libsqlite3-dev`: `sudo apt install libsqlite3-dev`
> 2. Re-install pyenv: `pyenv install 3.6.1`
> 
> Maybe this can fix the issue for you @vijay120

Perfectly worked in 2022 with even python 3.9.9

What I did
```
gama@c8d761326f2e:~$ sudo apt install libsqlite3-dev
	Reading package lists... Done
	Building dependency tree... Done
	Reading state information... Done
	Suggested packages:
	  sqlite3-doc
	The following NEW packages will be installed:
	  libsqlite3-dev
	0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
	Need to get 963 kB of archives.
	After this operation, 2,620 kB of additional disk space will be used.
	Get:1 http://deb.debian.org/debian bullseye/main amd64 libsqlite3-dev amd64 3.34.1-3 [963 kB]
	Fetched 963 kB in 1s (1,580 kB/s)  
	debconf: delaying package configuration, since apt-utils is not installed
	Selecting previously unselected package libsqlite3-dev:amd64.
	(Reading database ... 25168 files and directories currently installed.)
	Preparing to unpack .../libsqlite3-dev_3.34.1-3_amd64.deb ...
	Unpacking libsqlite3-dev:amd64 (3.34.1-3) ...
	Setting up libsqlite3-dev:amd64 (3.34.1-3) ...
gama@c8d761326f2e:~$ pyenv versions
	  system
	* 3.7.12 (set by /home/gama/.pyenv/version)
	* 3.9.9 (set by /home/gama/.pyenv/version)
gama@c8d761326f2e:~$ pyenv install 3.9.9
	pyenv: /home/gama/.pyenv/versions/3.9.9 already exists
	continue with installation? (y/N) y
	Downloading Python-3.9.9.tar.xz...
	-> https://www.python.org/ftp/python/3.9.9/Python-3.9.9.tar.xz
	Installing Python-3.9.9...
	WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
	WARNING: The Python curses extension was not compiled. Missing the ncurses lib?
	WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
	Installed Python-3.9.9 to /home/gama/.pyenv/versions/3.9.9
```

May be the glimpse of the WARNING for other extensions above give hint of what might have happened in past with sqlite3.

**Comment by e70838** [comment]
Same problem installing the latest python 2.7:
```
Downloading Python-2.7.18.tar.xz...
-> https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tar.xz
Installing Python-2.7.18...
...
patching file setup.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/opeint/.pyenv/versions/2.7.18/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/home/opeint/.pyenv/versions/2.7.18/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
Installed Python-2.7.18 to /home/opeint/.pyenv/versions/2.7.18

```

**Comment by acgc99** [comment]
Hi,

> sudo apt install libsqlite3-dev

Any solution for those without sudo privileges? I'm working on a computing cluster and I can't execute this command.

**Comment by moises-marques** [comment]
Estou tendo muita dificuldade em criar um executável com cx-Freeze
