### ISSUE TITLE
pyenv doesn't hash binaries under ~/Library/Python/2.7/bin

### ISSUE THREAD

**Issue by leira** [pyenv/pyenv#681]
In my setup, I have to use system python for most of the task, to keep things clean, I install packages using pip --user, so binaries will be under ~/Library/Python/2.7/bin, even pip is under it.

I started using pyenv, but seems pyenv doesn't hash shims from ~/Library/Python/2.7/bin. When I run pip after "pyenv shell system", pyenv complained command not found. Is it a supported setup?
##

**Comment by chrahunt** [comment]
I don't think we can support this - the purpose of the shims is to allow pyenv to manage resolution of Python versions given a particular utility is invoked from a particular directory under a given environment. `--user`-installed packages could have been installed from a pip associated with any pyenv Python (or the system Python or another external version), so we wouldn't be able to resolve to a specific one given only the name of the command and the knowledge that it is in the user's site-packages directory.

A cleaner approach would be to manage virtual environments for each use case you have and explicitly activate/deactivate them as needed or use some other tool to do it automatically (e.g. autoenv).

@yyuu, any thoughts?

**Comment by yyuu** [comment]
I tend to agree with your opinion in general 🤔 

What I can fair to say is that pyenv is meant to be a user-level tool to manage multiple Python versions. It means that all versions managed by pyenv, w/ exception of `system`, are all managed by the user. Its fundamental concept is actually conflicting with the `pip install --user` at all; we might be able to prepare _shims_ for executables installed in `~/Library/Python/*/bin`, but it'll require pyenv to maintain the extra mapping between pyenv-managed-pythons and libraries, and effectively it won't work. What I'd be able to recommend for the best to manage runtime environments derived from system python is same as @chrahunt, use virtual environments.

**Comment by chrahunt** [comment]
@leira, given the discussion so far we'll close this but do not hesitate to bring forward any other suggestions you have for pyenv. Thanks!
