### ISSUE TITLE
Problem with sqlite lib when installing python 3.5.1

### ISSUE THREAD

**Issue by seagullbird** [pyenv/pyenv#692]
Hello, 
My system is Mac OS X 10.11.6,
when I do 'pyenv install 3.5.1' I got everything right except this warning:

**WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?**

Firstly I ignored this and went on with my project till I met some sqlite problem.
I believe it is this problem that caused everything after.
I looked through the Internet and couldn't find my answer, nor a guidance on how to get 'the SQLite3 lib'. Also I searched homebrew for 'sqlite-dev' or 'pysqlite' or anything similar but no result.
Could you be so kind to help me out with this?
Plus, I can do 'brew install python3' and use python3(version 3.5.1) just fine. I just don't know if there is a way to directly add this "brew installed" python3 to my pyenv versions. 

Thanks a lot!
##

**Comment by kxxoling** [comment]
There's a lot of related issues here, but none of them fixed my problem. I reinstalled sqlite3 with brew, and this is what brew suggests:

```
Homebrew has detected an existing SQLite history file that was created
with the editline library. The current version of this formula is
built with Readline. To back up and convert your history file so that
it can be used with Readline, run:

  sed -i~ 's/\\040/ /g' ~/.sqlite_history

before using the `sqlite` command-line tool again. Otherwise, your
history will be lost.

This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides an older sqlite3.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.zshrc

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/sqlite/lib
    CPPFLAGS: -I/usr/local/opt/sqlite/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/sqlite/lib/pkgconfig
```

So I did:

```
10706  sed -i~ 's/\\040/ /g' ~/.sqlite_history
10707  export LDFLAGS="-L/usr/local/opt/sqlite/lib"
10708  export CPPFLAGS="-I/usr/local/opt/sqlite/include"
10709  pyenv install 2.7.14 # It's OK now.
```

I guess line 10706 is not necessary if you don't care your sqlite history.

**Comment by MarchLiu** [comment]
I use build configuration like this:
```
LDFLAGS="-L/usr/local/opt/zlib/lib -L/usr/local/opt/sqlite/lib"
CPPFLAGS="-I/usr/local/opt/zlib/include -I/usr/local/opt/sqlite/include"
```
