### ISSUE TITLE
Download indicator needed

### ISSUE THREAD

**Issue by itanoss** [pyenv/pyenv#693]
When a new version is installed using a command `pyenv install <version>` and a message that `Downloading Python-version.tar.gz` is shown, we don't know whether it normally processes downloading or not.
##

**Comment by joshfriend** [comment]
If you install `aria2c`, pyenv will use that instead of `curl` which should show a download progress indicator.

see: #534 #539

**Comment by jhermann** [comment]
"curl -#" could be used for the curl side of things.

**Comment by mandarvaze** [comment]
If the install fails due to **build errors**, does ``pyenv install``  download the same thing **again** ? (or is Downloading .. just a message, but uses already downloaded/cached version)
