### ISSUE TITLE
no module name "Enum" after distributing with vitualenv

### ISSUE THREAD

**Issue by Carreau** [pyenv/pyenv#711]
See https://github.com/travis-ci/travis-ci/issues/6613#issuecomment-247999258

If I pyenv install 3.6 beta, then 

```
mkdir distribute
virtualenv --python=~/.pyenv/versions/3.6.0b1/bin/python  distribute
```

The following works:

```
./distribute/bin/python -c 'None'
```

The following fails:

```
export  PYTHONWARNINGS='ignore';./distribute/bin/python -c 'None'
+ export PYTHONWARNINGS=ignore
+ PYTHONWARNINGS=ignore
+ ./distribute/bin/python -c None
'import warnings' failed; traceback:
Traceback (most recent call last):
  File "<path to distribute folder>/lib/python3.6/warnings.py", line 496, in <module>
    _processoptions(sys.warnoptions)
  File "<path to distribute folder>/lib/python3.6/warnings.py", line 178, in _processoptions
    _setoption(arg)
  File "<path to distribute folder>/lib/python3.6/warnings.py", line 184, in _setoption
    import re
  File "<path to distribute folder>/lib/python3.6/re.py", line 122, in <module>
    import enum
ModuleNotFoundError: No module named 'enum'
```

Not sure if it's a virtualenv or pyenv or python thing. 
##

**Comment by yyuu** [comment]
I believe this must be a CPython thing, but not sure what's broken at least for now.

**Comment by Carreau** [comment]
Thanks @yyuu ; is is worth for me to try to open an issue on pypa/virtualenv ? And maybe on core CPython ?

**Comment by yyuu** [comment]
I confirmed the reproduction with virtualenv created from 3.6.0b1 with using virtualenv v14.0.3. It'd worth reporting to pypa/virtualenv if there's no similar issues reported yet.

**Comment by yan12125** [comment]
Seems similar: #962
