### ISSUE TITLE
Install Python source from a local directory thru pyenv

### ISSUE THREAD

**Issue by ashank2010** [pyenv/pyenv#754]
Hi,

I am would like to install Python 3.4.0 from a local directory (since there is some issue with libffi library for which I have a separate patch ) through pyenv. Is it possible to point pyenv to use the python source from the directory I point to without checking online?

P.S: I am not sure if this question is already answered but there was none that I could find.

Thanks.

**Comment by sat1993** [comment]
wget http://mirrors.sohu.com/python/3.4.0/Python-3.4.0.tar.xz -P ~/.pyenv/cache/

export PYENV_ROOT=$HOME/.pyenv

pyenv install 3.4.0

MacOS

**Comment by ashank2010** [comment]
@sat1993 Thanks a lot

**Comment by sat1993** [comment]
when you install pyenv
```
To use Homebrew's directories rather than ~/.pyenv add to your profile:
  export PYENV_ROOT=/usr/local/var/pyenv

To enable shims and autocompletion add to your profile:
  if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
```
then,
wget  http://mirrors.sohu.com/python/3.4.0/Python-3.4.0.tar.xz -P $PYENV_ROOT/cache/
pyenv install 3.4.0

**Comment by Samureus** [comment]
Closing issue since the question has been answered already, thanks @sat1993!

**Comment by geohuz** [comment]
It doens't on my unbuntu 18.04 server, I"m seeing the command 'Downloading ...' after setup everything according to the suggestions.

**Comment by geohuz** [comment]
Well it's my problem of getting a broken tarball.

**Comment by hulleyrob** [comment]
wow just been looking for how to do this for ages and finally found the answer. Can it be added to the documentation?
