### ISSUE TITLE
pyenv fails to install on Ubuntu 16.04

### ISSUE THREAD

**Issue by ssbarnea** [pyenv/pyenv#755]
I have Unbuntu 16.04 with both py2.7 and py3.5 installed and both of them had critical packages updated using `pip[23] install -upgrade pip setuptools`

        error: option --single-version-externally-managed not recognized

Full error and pip freeze at https://gist.github.com/ssbarnea/1d135b29932580f00a48e786aeeaa68a

I tried on both py2/3, same error.

**Comment by joshfriend** [comment]
Did you install pyenv from pip? That version is **extremely** old. See also #387
