### ISSUE TITLE
gedit python plugins never load when using pyenv

### ISSUE THREAD

**Issue by SanketDG** [pyenv/pyenv#761]
I am a huge fan of pyenv and how it solved the "multiple versions" thing!

Today, I was trying out a new gedit plugin (just for fun) and realised it won't work, not on a venv, local or even global.

Is there a way around this?

gedit seems to be using the `Loader` variable in https://github.com/coala/coala-gedit/blob/master/coala.plugin but I am not sure what goes underneath.

**Comment by chrahunt** [comment]
Based on the activity in coala/coala-gedit#18 it looks like you were able to at least get past this issue, so I'll close this. Please update here if you think the solution may help others.
