### ISSUE TITLE
wrong pydoc is used when pyenv activates virtualenv 

### ISSUE THREAD

**Issue by jaloren** [pyenv/pyenv#768]
I am on Ubuntu 14.04.4 LTS. Here is what's in my bashrc. 

```bash
export PYENV_ROOT="${HOME}/.pyenv"
if [ -d "${PYENV_ROOT}" ]; then
    export PATH="${PYENV_ROOT}/bin:${PATH}"
    eval "$(pyenv init -)" 
    eval "$(pyenv virtualenv-init -)"
fi
```

The system installed python is 2.7.12. I also have python 2.7.12 installed in my pyenv directory. I configured the default version to be the python 2.7.12 in my pyenv directory.  When I execute the which command on pydoc it shows that the pydoc from pyenv is being picked up as expected. However, if i activate virtualenv from pyenv, then the pyenv which command returns the system installed version of pydoc.

Then when i run pydoc on a python script, pydoc complains that it can't import a module that does not exist even though that module exists in my activated virtual environment.

**Comment by cmcginty** [comment]
### Pydoc ignores current pyenv-virtualenv 

Seeing the same thing here. `pydoc` command in a virtualenv with python 3.4.5 uses the system python 2.7.12.

```
$ python -V
Python 3.4.5
$ pydoc sys |grep '^\s\+version ='
version = '2.7.13 (default, Dec 17 2016, 23:03:43) \n[GCC 4.2.1 Compat...
```

**Comment by rsd** [comment]
Try this:
`alias pydoc="python -m pydoc"`
[https://notoriousno.blogspot.com/2016/09/python-alias-commands-that-play-nice.html](url)

**Comment by native-api** [comment]
Virtualenv issue: https://github.com/pypa/virtualenv/issues/149
