### ISSUE TITLE
pyenv in combination with anaconda breaks calls to basic functions [$10]

### ISSUE THREAD

**Issue by Jeremias-Brand** [pyenv/pyenv#772]
Working on cent OS 6.
I installed anaconda3-4.1.1 through pyenv.
Now when I am not in anaconda calling functions contained in anaconda will cause an error:

```
$ clear
pyenv: clear: command not found

The `clear' command exists in these Python versions:
  anaconda3-4.1.1
```
Now I don't even know why anaconda would have its own clear command but that is beside the point. The problem also occurs with user installed functions.

```
$ TransDecoder.LongOrfs
pyenv: TransDecoder.LongOrfs: command not found

The `TransDecoder.LongOrfs' command exists in these Python versions:
  anaconda3-4.1.1

```
I have Transdecoder installed manually and in my path. 

Here are the relevant lines of my .bash_profile in case that is any help:

 ```
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
>---. ~/.bashrc
fi


# User specific environment and startup programs
export PYENV_ROOT=/home/jeremias/.linuxbrew/var/pyenv
# insert shims for pyenv in front of path
PATH="$HOME/.pyenv/shims:$PATH"

PATH="/usr/bin/R:/opt/bib/active/bin:$PATH"

PATH="$HOME/.linuxbrew/bin:$PATH"
PATH="$HOME/.linuxbrew/sbin:$PATH"


export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"

#####################################################################################

PATH="$PATH:$HOME/soft/last-658/src:/home/jeremias/soft/TransDecoder-2.0.1:/home/jeremias/soft/BUSCO_v1.1b1"
PATH="$PATH:$HOME/soft/EMBOSS/bin"
PATH="$PATH:$HOME/soft/hmmer-3.1b2-linux-intel-x86_64/binaries"
PATH="$PATH:$HOME/soft/transrate-1.0.2-linux-x86_64"
PATH="$PATH:$HOME/soft/Solexa"
PATH="$PATH:$HOME/soft/sqlite-autoconf-3150100"
PATH="$PATH:$HOME/soft/tmhmm-2.0c/bin"
PATH="$PATH:$HOME/soft/signalp-4.1"
PATH="$PATH:$HOME/soft/rnammer"
PATH="$PATH:$HOME/soft/Trinotate-3.0.1"
PATH="$PATH:$HOME/soft/Trinotate-3.0.1/util/rnammer_support"
PATH="$PATH:$HOME/soft/Trinotate-3.0.1/auto"
PATH="$PATH:$HOME/soft/rcorrector"
#PATH="$PATH:$HOME/soft/Trinotate-3.0.1" Export the entier PATH
export PATH=$PATH

# apparently this should be last
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
eval "$(pyenv virtualenv-init -)"
source /home/jeremias/perl5/perlbrew/etc/bashrc

```

Any help would really be appreciated.

**Comment by motivic** [comment]
@Reafdaw Isn't this resolved by the plugin: https://github.com/pyenv/pyenv-which-ext

At least it fixed this very problem for me.

**Comment by fny** [comment]
Can someone please merge that extension into pyenv? I see no reason to not have this as a default.

**Comment by amitmangalvedkar** [comment]
Is this resolved? I am also facing this issue and I am not sure which other basic commands have got 'over-ridden'.

**Comment by fny** [comment]
@amitmangalvedkar  You need to install another pyenv package: https://github.com/pyenv/pyenv-which-ext

By default, pyenv doesn't look beyond itself for other binaries. I feel like its wiser to perhaps make this an option rather than a default.

**Comment by shoichiaizawa** [comment]
As for the `clear` command, I [added it](https://github.com/pyenv/pyenv/pull/1082/commits/b64c445b61c0284120fae6d4019758754aef5a83) to the so-called [blacklist](https://github.com/pyenv/pyenv/blob/master/pyenv.d/rehash/conda.d/default.list), whose listed items are ignored and not to be created its shims when installing Anaconda anew. Please see [the comment](https://github.com/pyenv/pyenv/pull/992#issuecomment-333008248) by @yyuu regarding this issue.

Otherwise, as other people mentioned, the (pyenv/pyenv-which-ext)[https://github.com/pyenv/pyenv-which-ext] plugin should deal this phenomenon (though I have never used this).

As for the user installed functions you mentioned, I am not sure 😢

**Comment by martimlobao** [comment]
This has been open for more than two years, are there any updates?

You can keep adding commands to the [blacklist](https://github.com/pyenv/pyenv/blob/master/pyenv.d/rehash/conda.d/default.list), but this feels like continually putting band-aids on a problem that should be fixed at its root.

Recently, I also ran into the problem of `jupyter` (installed via Homebrew) no longer working as soon as I created a virtualenv which has `jupyter` installed.
```
$ jupyter
pyenv: jupyter: command not found

The `clear' command exists in these Python versions:
  miniconda3-latest
```
The [pyenv-which-ext](https://github.com/pyenv/pyenv-which-ext) package works, but I don't see why this isn't baked in to pyenv.

**Comment by chrahunt** [comment]
Personally I use pyenv as a Python version manager, symlinking `~/bin/python` to `~/.pyenv/shims/python` and keeping `~/bin` on my `PATH` (not `~/.pyenv/shims`). Virtual environments provide all utilities and are activated as-needed.

It could save some grief if the shims were opt-in or maybe provided as a plugin, but that's probably just adding an extra step for the large population of users that actually use them.

**Comment by cornfeedhobo** [comment]
> Now when I am not in anaconda calling functions contained in anaconda will cause an error:

This is intentional. I don't understand the issue. Either set your pyenv default ("system") version to anaconda, or move to a directory where you have set it locally.

> Now I don't even know why anaconda would have its own clear command but that is beside the point. The problem also occurs with user installed functions.

I honestly can't make any sense of this mess, but my guess is that it's related to above.

**Comment by native-api** [comment]
Fixed: now shims fall through to items further on PATH for executables that are not in active versions.
