### ISSUE TITLE
Prompt slow after pyenv-init

### ISSUE THREAD

**Issue by lanox** [pyenv/pyenv#784]
Hi 

I am running pyenv version 1.0.5, on macos sierra and I find it very slow when I press enter for my  prompt to return.

in my profile I have this

```
To enable shims and autocompletion add to your profile:
 if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
```

however If I remove above snippet my prompt responds almost instantly.

Is anyone else experiencing similar issue. ?

here is quick vid for demonstration.

https://asciinema.org/a/3w539ip9u1lrww6elj98cyfux

**Comment by notnami** [comment]
I have the same issue on Bash on WSL.

**Comment by lanox** [comment]
does anyone have any ideas ?

**Comment by yyuu** [comment]
It will run bunch of bash code. It may be slow on slower machine.

**Comment by notnami** [comment]
I was running it on a laptop from last year. I don't think my machine is
slow.

**Comment by lanox** [comment]
@yyuu thank you for all the work you do on pyenv it is great solution for python, however I find it little bizarre that you could make an assumption that I have slow hardware with out asking what hardware I have. 

I do not think this is due to hardware as my mac is only 1 year old its 2.7 core i5 with 16gb of ram, I am quiet sure that this is sufficient enough.

I also do not think that this issue should be closed.

**Comment by Gentux** [comment]
Hi,

I have the same issue.
My machine is a MacBook Pro, 2,9 GHz Intel Core i5 with 16Go RAM.

**Comment by Xuraiis** [comment]
Hi,

I have the same issue.
I also believe this should not be closed.

**Comment by blueyed** [comment]
Where do you add it to? `profile` or `rc`?
Are you using Bash or Zsh?

It is almost certainly better to add it to your profile / login shell only, and not your `rc`.
But that depends on how and when your login shell is started etc.

There is an issue about addressing this in the README, and IIRC it recommends to use `rc` since it will work in a new shell without relogin etc.

I agree in general, that pyenv's init is slow - that's why I am doing it only on demand, i.e. when a `pyenv` command is called.

**Comment by blueyed** [comment]
@lanox 
> pyenv causing prompt to be slow

That's not correct, is it?
It's not slowing down the prompt itself, i.e. after pressing Enter, is it?

**Comment by blueyed** [comment]
@lanox 
> 1 year old its 2.7 core i5 with 16gb of ram

SSD then also I assume?

For debugging, you can put `export PYENV_DEBUG=1` before the init.

Also make sure that you are not doing the `init` too often, i.e. more than once.
Also you might show us your `rc` or `profile` script.

**Comment by feigaoxyz** [comment]
I also have this problem with my fish and macOS settings.
After some digging, I find the `command pyenv rehash 2>/dev/null` (or your equivalence for other shells) to be the most time consuming part.
Therefore, I just manually put the rest of `pyenv init -` into my `rc` files (`config.fish` for fish). So far it works ok.

Hope this workaround helps. Before an official solution is provided.

**Comment by cmcginty** [comment]
I have two different macs with the same config and only 1 exhibits this issue.

**Comment by blueyed** [comment]
Well, as said before and in other issues: you should not have the init in your rc (e.g. .bashrc), but rather your profile (e.g. .profile), which gets run typically only once when logging in.
This is different on macos IIRC (which runs a login shell always).
Try adding some "echo profile" and "echo bashrc" to respective files to see what gets parsed when opening a new shell.

**Comment by blueyed** [comment]
@cmcginty 
Since it appears to be related to pyenv-virtualenv, please follow up on https://github.com/pyenv/pyenv-virtualenv/issues/132#issuecomment-383175244.

**Comment by cmcginty** [comment]
I have a fix I made against pyenv/pyenv-virtualenv#259

**Comment by sloria** [comment]
As pointed out in https://github.com/pyenv/pyenv/issues/784#issuecomment-356805124 , the slowest piece seems to be running `pyenv rehash` (which is run by `pyenv init -`).

I am running prezto on macOS High Sierra. I tried modifying [this line](https://github.com/sorin-ionescu/prezto/blob/e149367445d2bcb9faa6ada365dfd56efec39de8/modules/python/init.zsh#L19) in the prezto python module to:

```zsh
  eval "$(pyenv init - --no-rehash)"
```

And it improved startup time by ~400ms. Not sure what the right path forward is (change in prezto? optimize `pyenv rehash`?), but just thought I'd pass along that finding.

**Comment by blueyed** [comment]
@sloria 
Using `--no-rehash` is certainly a good idea, so it would make sense to put it upstream in prezto IMHO.

Optimizing `rehash` would also be good, of course - you can see what it does with `PYENV_DEBUG=1 pyenv rehash` already.

In case you are using pyenv-virtualenv, https://github.com/pyenv/pyenv-virtualenv/issues/274 is relevant: I think pyenv-virtualenv reruns it unnecessarily.

I have an experiment in https://github.com/pyenv/pyenv/pull/1185, which uses different shim directories per current version, which might be interesting in this regard, since it potentially means that you will have more, but smaller sets of shims (that need to be rehashed).

> ~400ms

Would be really interesting to see where this is coming from for you, since it is faster for me.

Using pyenv master and pyenv-virtualenv master:

10 loops, best of 3: 128 msec per loop

Without pyenv-virtualenv/etc/pyenv.d/rehash/envs.bash:

10 loops, best of 3: 89.9 msec per loop

(used `python -m timeit "__import__('subprocess').Popen(['pyenv', 'rehash']).communicate()"`)

**Comment by sloria** [comment]
Thanks @blueyed for the suggestions and for looking into further optimizations. I'll send a PR to prezto when I get a chance. I do use pyenv-virtualenv, so the issue you linked re: re-running `pyenv rehash` might be contributing to the `400ms`.

**Comment by blueyed** [comment]
Can you try the timeit command I've used.

I have created https://github.com/pyenv/pyenv-virtualenv/pull/275 for pyenv-virtualenv.
Are you using it?

**Comment by blueyed** [comment]
btw: I am using `eval "$("$PYENV_ROOT"/bin/pyenv init -)"` in my ~/.profile file, i.e. not for every new terminal, and then basically only define the `pyenv` function (that you get from it) in ~/.zshrc.

**Comment by sloria** [comment]
I won't have time to look into this today. I'll let you know if I end up trying that out, but please don't block the PR on my behalf. Thanks again for working on this.

**Comment by blueyed** [comment]
As for the original issue / reporter and people reacting to it with thumbs-up: you could `export PYENV_DEBUG=1` and then see what it does.

Please provide this info here then, and *please* also try to investigate yourself, i.e. use it without oh-my-zsh or other frameworks that might get into the way.

**Comment by blueyed** [comment]
btw: the original title is misleading ("Slow init/startup"), because it is slow on every prompt then, not only its startup.

**Comment by sloria** [comment]
@blueyed Yes, I'm using pyenv-virtualenv.

**Comment by lesterlo** [comment]
I have the same problem. I am using MacOS 10.13.6. Some people said this problem is caused by kaspersky internet security. Is it?

**Comment by lesterlo** [comment]
I solve this problem after I add .pyenv as a trusted zone on kaspersky internet security. This policy speeds up a little bit about each shell prompt. Then I change this statement on .bash_profile
```bash
eval "$(pyenv init - bash --no-rehash)"
```

Then the speed of the shell prompt become normal again. I am using macOS Mojave (10.14).

**Comment by diimdeep** [comment]
Startup time 
`if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi` ~ 300ms
`if which pyenv > /dev/null; then eval "$(pyenv init - zsh --no-rehash)"; fi` ~ 100ms

**Comment by hmngwy** [comment]
On zsh and on a teeny tiny computer this works:

```
export PATH="/home/pi/.pyenv/bin:$PATH"
eval "$(pyenv init - zsh --no-rehash)"
eval "$(pyenv virtualenv-init -)"```

**Comment by kakulukia** [comment]
This is kinda inconveniently closed while still slow.
But here is a neat trick i found: https://github.com/davidparsson/zsh-pyenv-lazy
Lazy loading pyenv is hardly adding anything to your startup time! :)

**Comment by melyux** [comment]
Using `eval "$(pyenv init - zsh --no-rehash)"` broke manual `pyenv rehash` for me, causing the error `basename: illegal option -- -`. So every time I'd update pyenv, it would break. I went back to the old init, sadly.

**Comment by Sybret** [comment]
For posterity, I'm running the following environment
```
OS: macOS Big Sur
Hardware: 2019 MacBook Pro (2.6Ghz 6-Core Intel Core i7)
Bash  version: GNU bash, version 5.1.4(1)-release (x86_64-apple-darwin20.2.0)
PyEnv version: master (version: 1.2.26-17-g54e58dc7)
```
and adding `bash --no-rehash` to the pyenv init cmd lowered `bash --login` times by ~1 second  on average (as measured by [hyperfine](https://github.com/sharkdp/hyperfine#hyperfine)).

However, that change does break `pyenv rehash` as @melyux pointed out above so I ended up going the lazy init route by replacing the eval in my .bash_profile with this:

```
function pyenv() {
    unset -f pyenv
    eval "$(command pyenv init -)"
    pyenv $@
}
```
which resulted in a total `bash --login` speedup of ~1.07 seconds.

I hope this is helpful for anyone else that comes across this issue.
