### ISSUE TITLE
python system version blocks when ~/.pyenv/version is not specified

### ISSUE THREAD

**Issue by Lordpeara** [pyenv/pyenv#833]
![image](https://cloud.githubusercontent.com/assets/6825249/22853968/84efee9a-f0a6-11e6-8546-edc31d9b051b.png)

but python works via absolute path like this

![image](https://cloud.githubusercontent.com/assets/6825249/22853993/ceed4862-f0a6-11e6-9edb-d8a11787fc1d.png)

Please tell me what goes on

**Comment by dummys** [comment]
its version with a s
