### ISSUE TITLE
How to install Python 3.6.0 with OpenSSL 1.1 on MacOS?

### ISSUE THREAD

**Issue by dimaqq** [pyenv/pyenv#839]
I can `brew install openssl@1.1` and get OpenSSL 1.1.0e (atm.)

I'd like to `pyenv install 3.6.0` with that OpenSSL, but it seems that pyenv overrides my choices of CPFLAGS, LDFLAGS, etc.

Is there a way to force its hand?

**Comment by cculianu** [comment]
Uh. I want to do the same. I can't get pyenv to link against openssl@1.1 no matter how hard I try.

What gives?  Openssl1.1 offers features like hashlib.scrypt which are needed by me.

**Comment by ThomasWaldmann** [comment]
Would a bounty help here?

**Comment by ThomasWaldmann** [comment]
Also strange: even if one has installed `readline` and `openssl` (1.0.2) before installing pyenv and building pythons with it, pyenv seems to download these again.

I would like to have pyenv use the existing packages, so I can influence (e.g. via PKG_CONFIG_PATH or compiler/linker flags env variable) which openssl version pyenv uses for building the pythons (because it should be the same version as I use to build borgbackup with).

**Comment by cculianu** [comment]
I'm in agreement here.

I may just put up a PR to handle these cases -- pyenv is pretty nicely architected so people not familiar with it can modify it. That's a good thing!

I really really need this feature too -- the features you describe and the ability to specify openssl 1.1, etc.

:/

**Comment by ThomasWaldmann** [comment]
my comment above was about travis-ci's macOS testing.

strange, in my vagrant-based testing, I see:
```
    darwin64: python-build: use openssl from homebrew
    darwin64: python-build: use readline from homebrew
    darwin64: Downloading Python-3.7.0.tar.xz...
    darwin64: -> https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz
    darwin64: Installing Python-3.7.0...
    darwin64: python-build: use readline from homebrew
    darwin64: Installed Python-3.7.0 to /Users/vagrant/.pyenv/versions/3.7.0
```
So, pyenv does not download readline and openssl, but picks it up from homebrew, as desired.

**Comment by cculianu** [comment]
Yeah but it picks up 1.0.2 even when you have 1.1.0 installed :'(

**Comment by ThomasWaldmann** [comment]
yeah, can confirm that (even though I pointed PKG_INFO_PATH at openssl@1.1).

**Comment by cculianu** [comment]
And if you uninstall 1.0.2 and just have 1.1 it fails and/or just compiles its own 1.0.2 from source.. refusing to see 1.1 even though python itself could use 1.1 no problem. So yeah. :'(

**Comment by ThomasWaldmann** [comment]
It is likely this code in `.pyenv/plugins/python-build/bin`:
```
use_homebrew_openssl() {
  local ssldir="$(brew --prefix openssl 2>/dev/null || true)"
  if [ -d "$ssldir" ]; then
    echo "python-build: use openssl from homebrew"
    export PKG_CONFIG_PATH="$ssldir/lib/pkgconfig/:${PKG_CONFIG_PATH}"
    export CPPFLAGS="-I$ssldir/include ${CPPFLAGS}"
    export LDFLAGS="-L$ssldir/lib ${LDFLAGS}"
  else
    return 1
  fi
}  
```

`brew --prefix openssl` queries the 1.0.x openssl.
`brew --prefix openssl@1.1` queries the 1.1.x openssl.

**Comment by ThomasWaldmann** [comment]
That seems to work:
```
use_homebrew_openssl() {
  local ssl11dir="$(brew --prefix openssl@1.1 2>/dev/null || true)"
  local ssl10dir="$(brew --prefix openssl 2>/dev/null || true)"
  if [ -d "$ssl11dir" ]; then
    echo "python-build: use openssl 1.1 from homebrew"
    local ssldir=$ssl11dir
  elif [ -d "$ssl10dir" ]; then
    echo "python-build: use openssl 1.0 from homebrew"
    local ssldir=$ssl10dir
  else
    return 1
  fi
  export PKG_CONFIG_PATH="$ssldir/lib/pkgconfig/:${PKG_CONFIG_PATH}"
  export CPPFLAGS="-I$ssldir/include ${CPPFLAGS}"
  export LDFLAGS="-L$ssldir/lib ${LDFLAGS}"
}
```

**Comment by cculianu** [comment]
can you submit this as a PR? I love you

**Comment by ThomasWaldmann** [comment]
Working on it.

**Comment by cculianu** [comment]
I said it before I'll say it again. I love you.

**Comment by ThomasWaldmann** [comment]
Considering #1302 is merged, close this?

**Comment by cculianu** [comment]
Yeah good point.
