### ISSUE TITLE
List of packages you need install on a newly installed distribution.

### ISSUE THREAD

**Issue by giornaledisistema** [pyenv/pyenv#84]
This is the list of packages you need install on a newly installed distribution.

Debian derived distributions:

sudo apt-get install build-essential libreadline-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev git

Fedora derived distributions:

yum install gcc zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel tk-devel gdbm-devel ncurses-devel glibc-devel git

**Comment by Raindeer44** [comment]
This solved all my problems on a new install of Ubuntu 17.04. The Common Build Problems didn't help me.
