### ISSUE TITLE
MacOS 10.12 + zsh install issue

### ISSUE THREAD

**Issue by aznfy** [pyenv/pyenv#846]
Under MacOS 10.12 + zsh
After clone from the repository,
If I do this:
$ echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshenv
$ echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshenv

The pyenv does not work normally.

But if I do this:
$ echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
$ echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
and add all the rest stuff to .zshrc, it will work perfectly.

**Comment by stdstart** [comment]
I had same issue.thanks!now it works!

**Comment by diazgilberto** [comment]
After you ran those commands...
`echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshenv`
`echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshenv`

you need run `exec $SHELL` every single time you want pyenv to take control. If you want pyenv tu run by default you need to run the following.

`echo 'eval "$(pyenv init -)"' >> ~/.zshrc`

Or, as an alternative, you can `echo` both and the `eval` to the `.zshrc`

**Comment by mitrx** [comment]
The thing is that `/etc/zprofile` is loaded after `~/.zshenv` and it overwrites `PATH`. The `~/.zshrc` is not the place to set environment variables, so, I think the proper solution would be to pop paths set by these commands:
```zsh
echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshenv
echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshenv
```
to the front in `~/.zprofile`. The solution I came to is [here](https://github.com/sorin-ionescu/prezto/issues/381#issuecomment-294549773).

**Comment by ryudice** [comment]
This needs to be in the readme.

**Comment by ivymarkwell** [comment]
Bump -- didn't want to run the `exec $SHELL` command every time (which is the problem I was trying to solve). Followed the explanations above and added paths and the eval statement to my `~/.zprofile` to look like this
```
# Setting up pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```

**Comment by tekumara** [comment]
+1 for updating the README. Similar issue https://github.com/pyenv/pyenv/issues/1400
