### ISSUE TITLE
pyenv global x.x.x not changing the python version

### ISSUE THREAD

**Issue by eligreg** [pyenv/pyenv#849]
Installed pyenv using homebrew and so far i've had no luck getting pyenv to switch python versions. These are the steps I took:

```
$ brew install pyenv (successful)
$ pyenv install 3.5.2 (successful)
$ python --version
Python 2.7.11
$ pyenv global 3.5.2
$ python --version
Python 2.7.11
```

```
$ echo $PATH
/opt/local/bin:/opt/local/sbin:/Users/Eli/.rvm/gems/ruby-2.2.1/bin:/Users/Eli/.rvm/gems/ruby-2.2.1@global/bin:/Users/Eli/.rvm/rubies/ruby-2.2.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/Eli/.rvm/bin

```

**Comment by cameres** [comment]
I don't see either of the following in your path, which leads me to believe `eval "$(pyenv init -)"` isn't being run on startup of your shell.
- `$PYENV_ROOT/shims`
- `$PYENV_ROOT/bin`

**Comment by eligreg** [comment]
That was it! Thank you.


~
Eli Gregory

**Comment by temiadesina** [comment]
Hi @blueyed 

Facing this same issue @eligreg please what was the fix, thanks!

**Comment by bascoe10** [comment]
@temiadesina 
Running the command `pyenv init ` and the do the following fixed the issue for me.
```
# Load pyenv automatically by appending
# the following to ~/.zshrc:

eval "$(pyenv init -)"
```

**Comment by zhouhao27** [comment]
Didn't work for me although `pyenv local xxx.xxx` works.

**Comment by sellers** [comment]
for some reason, this is not working for me:   
```if which pyenv-virtualenv-init > /dev/null
then 
    eval "$(pyenv virtualenv-init -)"
fi

```
so I had to remove the which conditions..... and start a new login shell and it then worked.   I do have pyenv-virtualenv-init installed but somehow the shell was borking.   In case others have similar issues.

**Comment by SirZach** [comment]
Based on the README I thought the steps in Basic Github Checkout were only if you didn't do a `brew install`. Running steps 2 and 3 after installing through brew fixed this problem for me.

**Comment by lpanebr** [comment]
For my the problem was that I had a file at `$HOME/.python-version` with a fixed version.

**Removing the file fixed it.**

**Comment by lei-cao** [comment]
In my case, the issue only happens in my WebStorm's (or other intellij IDE) terminal. ITerm2 is working correct.

**Comment by gsscoder** [comment]
Hi all, I'm experiment the same issue.
I've installed via `pyenv` python 3.8.0, but when I switch (using **local** or **global**) nothing changes: the system python is still the one used.

I've added this to my `.zshrc`, but nothing changed:
```
export PATH="/Users/giacomo/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

I'm using macOS **Mojave** 10.14.6. Terminal is **iTerm** and shell **zsh**.

Thanks in advance for any help.

**Comment by rony13** [comment]
if everything below doesn't work, maybe you can take a try of 
`
which python3
`
(this seems to be a joke, but it costs me hours to figure out.)

**Comment by gsscoder** [comment]
On my system:
```sh
$ which python3
/usr/local/bin/python3
```
And thanks for your tiem, @rony13.

**Comment by Waked** [comment]
If none of the above works, check whether your path to `pyenv` in PATH is relative, eg.:
```
/home/user/scripts/../.pyenv/bin
/home/user/scripts/../.pyenv/shims
```
In such case, `pyenv` will appear to be working properly, but the `python` binary won't actually be looked up in the shims directory. I've encountered this problem with `zsh`.

**Comment by gsscoder** [comment]
I tried again installing using **pyenv installer** instead of brew and I'm still in the same stiuation!

Just to let know.

**Comment by rollno55044** [comment]
Try this: eval "$(pyenv init -)

Example:

$ python -V
Python 2.7.9
mac:~ $ eval "$(pyenv init -)"
mac:~ $ python -V
Python 3.5.0

source :- https://stackoverflow.com/a/34156303/8885635

**Comment by gsscoder** [comment]
I solved with help in [another issue](https://github.com/pyenv/pyenv/issues/1446). _Simply_ creating a new user for Catalina.

It may take time, you need to remove all apps installed with `brew` and install everything again (without forgotting of backuping you **dot files**!).

**Comment by johachi** [comment]
I had this problem as well. Seems like `pyenv shell 3.8.1` runs every time I open the terminal. I fixed this by running `pyenv shell --unset`. Now I just have to find out why `pyenv shell 3.8.1` run every time I open the terminal in vs code...

```sh
pyenv shell --help
Usage: pyenv shell <version>...
       pyenv shell -
       pyenv shell --unset

Sets a shell-specific Python version by setting the `PYENV_VERSION`
environment variable in your shell. This version overrides local
application-specific versions and the global version.

<version> should be a string matching a Python version known to pyenv.
The special version string `system' will use your default system Python.
Run `pyenv versions' for a list of available Python versions.

When `-` is passed instead of the version string, the previously set
version will be restored. With `--unset`, the `PYENV_VERSION`
environment variable gets unset, restoring the environment to the
state before the first `pyenv shell` call.
```

**Comment by bburt** [comment]
I was having the same issue with fish and I couldn't figure it out for the life of me. I was about ready to destroy my user profile and start from scratch. Somewhere along the way of trying to get pyenv setup initially I somehow set local version in my user directory `~/.python-version` which looked very similar to `~/.python/version` so I didn't catch it when looking at `pyenv versions`.

If anyone else is an idiot like me, deleting the .python-version in your root user folder (or any current folder you might be in with a .python-version local config) will obviously fixed it...

**Comment by kunzhoudk** [comment]
> it may help others to know -
> 
> add the eval to the end of the .zshrc file

just add "eval "$(pyenv init -)"" to .zshrc is working for me. Remove if conditions

**Comment by YukunXia** [comment]
> I was having the same issue with fish and I couldn't figure it out for the life of me. I was about ready to destroy my user profile and start from scratch. Somewhere along the way of trying to get pyenv setup initially I somehow set local version in my user directory `~/.python-version` which looked very similar to `~/.python/version` so I didn't catch it when looking at `pyenv versions`.
> 
> If anyone else is an idiot like me, deleting the .python-version in your root user folder (or any current folder you might be in with a .python-version local config) will obviously fixed it...

I find the toxic file `~/.python-version` is created by `pyenv local` + `system` or any other python version name.

I checked this [link](https://stackoverflow.com/a/54114370/9556578), and run `pyenv local system`, trying to just deactivate the virtual env. The correct one is `pyenv global system`.

**Comment by ankush981** [comment]
If any bash users are struggling with this, add `eval "$(pyenv init -)"` to your `.bashrc` (or `.bash_profile`) instead of the long, complicated line you find in the setup instructions. And thanks to all the people who provided their inputs here!

**Comment by theRocket** [comment]
> I find the toxic file `~/.python-version` is created by `pyenv local`

This is working as intended. If you execute 'pyenv local 3.8.5' for example while at your HOME directory, you will create that hidden file which overrides global when you are running python from that location. It's supposed to go within a project folder. Yes, deleting it fixed my problem also, so thanks! I just think "toxic" is bit strong. User error is a better descriptor.

**Comment by lethinkrong** [comment]
> I tried again installing using **pyenv installer** instead of `brew` and I'm still in the same stiuation!
> 
> Just to let know.

hi, you can check if you have a .python-version file in your home directory, using"open -e .python-version".then remove it.

**Comment by thorimur** [comment]
I was having this same issue, but none of the above fixes worked for me. After puzzling over this for longer than I care to admit, I finally realized—`python` was an alias defined in my `.bash_profile`.

`*sigh*`

I don't remember putting it there, so I think something else I used might have done so. (For that matter, so was `pip`.) So, check your `.bashrc`, `.bashprofile`, `.zshrc`, `.zprofile`, `.zlogin`, etc. to make sure you don't waste the same time I did!

**Comment by ohahohah** [comment]
In my case, it doesn't work because of an alias in `.zshrc`.  

like this
```
alias python=python3
alias pip=pip3
```

or  like this (it's obviously)
```bash
 alias python=/usr/local/bin/python3
 alias pip=/usr/local/bin/pip3
```

(Ref. https://wilsonmar.github.io/pyenv/ - `Don’t alias with pyenv` part)

Thanks to the above comments, I was able to narrow down my problem cause. 
Thanks again, everyone 👍

**Comment by VincmacD** [comment]
> I don't see either of the following in your path, which leads me to believe `eval "$(pyenv init -)"` isn't being run on startup of your shell.
> 
> * `$PYENV_ROOT/shims`
> * `$PYENV_ROOT/bin`

Sorry, how do I implement this?

**Comment by biata122** [comment]
run the command 'pyenv init --path', paste the output in your shell (~/.zshrc) at the end line, to enable shims.
and after that add 'eval "$(pyenv init -)" '
source ~/.zshrc

only this worked for me!

**Comment by nuKs** [comment]
`eval "$(pyenv init -)"` did not make it for me (ubuntu 20.04, installed through `sudo apt install pyenv`)
`eval "$(pyenv init --path)"` did! (within ~/.bashrc, with the other standard instructions incl PATH. setup etc.)

**Comment by gavinschriver** [comment]
> run the command 'pyenv init --path', paste the output in your shell (~/.zshrc) at the end line, to enable shims.
> and after that add 'eval "$(pyenv init -)" '
> source ~/.zshrc
> 
> only this worked for me!

@nuKs THANK YOU! This was driving me insane, I feel like I had tried all the other configuration options and nothing worked.

**Comment by luisdiasdev** [comment]
> `eval "$(pyenv init -)"` did not make it for me (ubuntu 20.04, installed through `sudo apt install pyenv`)
> `eval "$(pyenv init --path)"` did! (within ~/.bashrc, with the other standard instructions incl PATH. setup etc.)

Just so other people see, it also worked for Pop! OS 21.04 + zsh, installed through the bash script.
Thank you!

**Comment by helenchg** [comment]
Got my Mac yesterday and wonder where is the .bashrc, .zshrc, bash_profile files.

**Comment by chriswininger** [comment]
> run the command 'pyenv init --path', paste the output in your shell (~/.zshrc) at the end line, to enable shims.
> and after that add 'eval "$(pyenv init -)" '
> source ~/.zshrc
> 
> only this worked for me!

Thank you, this is the only that has worked for me as well. Putting `eval "$(pyenv init -)"` in .zshrc by its self did nothing, but adding that output (in my case `export PATH="/Users/chris/.pyenv/shims:${PATH}"`)

Thx so much!

**Comment by hlombroso** [comment]
Thank you @om-ha , `eval "$(pyenv init --path)" ` worked for me:
- MacOS Majove v10.14.6
- Homebrew 3.2.5
- pyenv 2.0.4

**Comment by muhdamean** [comment]
> run the command 'pyenv init --path', paste the output in your shell (~/.zshrc) at the end line, to enable shims.
> and after that add 'eval "$(pyenv init -)" '
> source ~/.zshrc
> 
> only this worked for me!

this works for me.

**Comment by minifisk** [comment]
> /.zshrc

I don't really understand the steps here, can you explain it like I would been five?

**Comment by hlombroso** [comment]
@minifisk , 
I am not sure on which system you are trying to install pyven, but the following setup worked for me on Mac 
System:
MacOS Majove v10.14.6
Homebrew 3.2.5
pyenv 2.0.4

[How to install python with pyenv on mac.md](https://gist.github.com/hlombroso/e0ae9ae7728c3a7808bc5da995cf1650)

**Comment by dexios1** [comment]
> `eval "$(pyenv init -)"` did not make it for me (ubuntu 20.04, installed through `sudo apt install pyenv`)
> `eval "$(pyenv init --path)"` did! (within ~/.bashrc, with the other standard instructions incl PATH. setup etc.)

Thanks a milli!!!

**Comment by MrMino** [comment]
Not sure what changed in my environment, but I've just noticed (after week-long holidays) that `pyenv init -` stopped adding shims to `PATH` in my ZSH (was it ever doing that? I'm guessing it did, reading this thread).

✔ `eval "$(pyenv init --path)"` works
❌ `eval "$(pyenv init -)"` does not.

**Comment by DrJfrost** [comment]
I had to add `eval "$(pyenv init --path)"` on my `.zshrc` file to actually make it work on ubuntu

**Comment by native-api** [comment]
2all:

* if you're in Linux, make sure that you add ther `--path` invocation (and other envvar lines from README) to `~/.profile` as well as `~/.zprofile`, then fully log out and log in again
* if you're in MacOS, make sure that your terminal app is configured to run the shell as a login shell

**Comment by native-api** [comment]
2all:

* if you're in Linux, make sure that you add the `--path` invocation (and other envvar lines from the README) to `~/.profile` as well as `~/.zprofile`, then fully log out and log in again (just restarting the terminal emulator is not enough)
* if you're in MacOS, make sure that your terminal app is configured to run the shell as a login shell

**Comment by obsd** [comment]
put the next line in your ~/.bashrc | ~/.zshrc and it will do the magic [ Mac ]
eval "$(pyenv init --path)"
Does the magic

**Comment by native-api** [comment]
Please see the updated and hopefully clearer shell setup instructions in the README.

**Comment by guptamanish07** [comment]
add  this line into .zshrc not in .zprofile 
export PATH="$(pyenv root)/shims:$PATH"

**Comment by mayankshah1607** [comment]
> run the command 'pyenv init --path', paste the output in your shell (~/.zshrc) at the end line, to enable shims. and after that add 'eval "$(pyenv init -)" ' source ~/.zshrc
> 
> only this worked for me!

This worked for me! Thanks @biata122 :)

**Comment by MrMino** [comment]
@anton-petrov I'd like to propose locking this topic. Everything that was there to be said has been said, now it just generates lots of unnecessary "+1" comments and spam (FWIW I'm guilty of this too, because I missed the comments by @nuKs and @biata122 [[1]](https://github.com/pyenv/pyenv/issues/849#issuecomment-863456765) [[2]](https://github.com/pyenv/pyenv/issues/849#issuecomment-875875617)).
