### ISSUE TITLE
"unrelated files are untouched" relating to umask

### ISSUE THREAD

**Issue by madduck** [pyenv/pyenv#853]
I just tried to make this and got an error:

    cd plugins/python-build && /tmp/pyenv/bats/bin/bats ${CI:+--tap} test
     […]
     ✗ unrelated files are untouched
       (from function `assert_equal' in file test/test_helper.bash, line 139,
        in test file test/installer.bats, line 60)
         `assert_equal "r-x" "${output:4:3}"' failed
       expected: r-x
       actual:   ---

This is because I have umask set to 0077. If I set it to 0022, then the test
completes fine. I don't think it should be testing my shell setup, but instead
define umask, if it's so finnicky about it.

Could be a bug in bats, of course. Let me know…

**Comment by blueyed** [comment]
@madduck 
Good find.
I think it makes sense to set umask to 0022 for the tests.
Please consider creating a PR.

**Comment by madduck** [comment]
@blueyed shouldn't this be in bats even?

**Comment by blueyed** [comment]
Not sure..  /cc @yyuu / @sstephenson 

I would argue that its about the test setup, and while 0022 seems to be common sense, it would be still subjective when in bats?!

The test, for reference: https://github.com/pyenv/pyenv/blob/0e683164bdaf8d127d8dcf3f151d3794b2492c27/plugins/python-build/test/installer.bats#L46-L61
