### ISSUE TITLE
Named builds for miniconda3: 4.3.11 and 4.3.14

### ISSUE THREAD

**Issue by chebee7i** [pyenv/pyenv#854]
Can we get named builds for miniconda 4.3.11 and 4.3.14 (just a few days released now)?

**Comment by Samureus** [comment]
The latest seems to be 4.3.14, and we're behind, latest definition I see is 4.1.11, though it looks like you can upgrade to the latest version with `conda update` (sorry I don't use conda myself). Would you need both 4.3.11 **and** 4.3.14, or is it ok with just the latest release?

**Comment by Samureus** [comment]
Update: checking the downloads page at https://conda.io/miniconda.html, this can be done with `miniconda2-latest` and `miniconda3-latest` (to be updated with #881). Since it has a secure https connection and no published SHA256 checksum ATM, I'd rather refer you to try these instead.

**Comment by chebee7i** [comment]
Correct, but `*-latest` tags aren't reliable if you don't want the build to change out from under you the next time you set up pyenv since they may point to the next version of Python at that time.

**Comment by joshfriend** [comment]
Closing since both of these versions seem to be present now
