### ISSUE TITLE
pyenv: python-config: command not found

### ISSUE THREAD

**Issue by garar** [pyenv/pyenv#856]
Hi!

I would like to report a problem with pyenv, I'm not sure if it is a pyenv problem or a pyenv-virtualenv problem.

Pyenv is unable to find python-config even though it is there.

> $ python3.6-config 
> pyenv: python3.6-config: command not found
> 
> The `python3.6-config' command exists in these Python versions:
>  3.6.0

I'm in a virtualenv build from 3.6.0:

> $ pyenv local
> kindelist

> pyenv versions
> system
> 3.6.0/envs/kindelist

Python 3.6.0 was installed using pyenv install 3.6.0.

I think it is a problem only for python 3.X because my 2.7.13 environment is working correctly.

I think it is related to: https://github.com/pyenv/pyenv/issues/397 but the fix that was included in pyenv-virtualenv/etc/pyenv.d/which/python-config.bash is not working.

Thank you for all the hard work! I really love pyenv.

**Comment by stefanos82** [comment]
@garar To fix your problem run `pyenv shell 3.6.0`; now it should work. To confirm that is works, try `python-config --cflags` and you should see the path that points at pyenv's directory.

**Comment by hhstore** [comment]
@stefanos82 

```python
pyenv shell 3.6.0

```

fix for me. thx.
