### ISSUE TITLE
No such file or directory: $(pyenv root)/bin

### ISSUE THREAD

**Issue by 3rd3** [pyenv/pyenv#858]
I've installed `pyenv` via Homebrew and I followed all instructions, however the path `$(pyenv root)/bin` does not exist. For now I've added `$(pyenv prefix)/bin` to my `$PATH` instead.

**Comment by wbolster** [comment]
it seems your setup is incorrect. what does `pyenv root` output? and what is your exact setup? your question is too generic to expect useful answers.

**Comment by 3rd3** [comment]
`pyenv root` simply prints `/Users/me/.pyenv`. As I said, I simply followed the instructions by installing it via Homebrew on macOS.

**Comment by wbolster** [comment]
the only thing that seems to matter is that `pyenv` should be in the path. if homebrew already takes care of that, you should be good to go.

i think this issue can be closed.

**Comment by phazel** [comment]
Hi there. I also have this issue. Is there something missing from the setup directions, or possibly something misleading about them? The instructions seem to refer to locations such as `$(pyenv root)/versions`, however `~./pyenv` exists but it's an empty text file. All the directions seem to imply that it's a directory, but a text file is what was generated.

Am I supposed to put something in this text file? Am I supposed to replace it with a directory called `~/.pyenv`?

**Comment by ashith-cldr** [comment]
For anyone still looking for answers, ignore a lot of outdated articles around the web, and please refer to the [README ](https://github.com/pyenv/pyenv#readme) file for installation details. Make sure to follow through with OS-specific installation details as well.

**Comment by ashithwilson** [comment]
For anyone still looking for answers, ignore a lot of outdated articles around the web, and please refer to the README file for installation details. Make sure to follow through with OS-specific installation details as well.

**Comment by juhoautio** [comment]
Indeed rehash is automatically executed when pip is executed with pyenv, which adds newly installed commands to shims.

For me shims were not being added because I was invoking pip install as `python -m pip install` (no particular reason). Invoking plain `pip install` worked, adding shims as expected. I learned that it's the intended behavior: https://github.com/pyenv/pyenv/issues/908

**Comment by tboddyspargo** [comment]
Similar to OP: What I don't understand is why the README includes commands like this:

```sh
export PATH="$PYENV_ROOT/bin:$PATH"
```

Why would we ever need to add `$PYENV_ROOT/bin` to `$PATH`?

When installing via homebrew and following the basic shell setup instructions leads to a state where: `$PYENV_ROOT/bin` doesn't exist. Given that `export PATH="$PYENV_ROOT/bin:$PATH"` is only run if `command -v pyenv` fails, I think the instructions imply that `$PYENV_ROOT/bin/pyenv` is expected to exist, but that's not the case.

Is that interpretation correct? Is `$PYENV_ROOT/bin/pyenv` _still_ expected to exist? Is there any documentation on what `$PYENV_ROOT/bin` is expected to contain and in which circumstances?

**Comment by native-api** [comment]
> Similar to OP: What I don't understand is why the README includes commands like this:
> 
> ```shell
> export PATH="$PYENV_ROOT/bin:$PATH"
> ```

[The corresponding command in the README](https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv) looks like this:

```
echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
```

It only adds `$PYENV_ROOT/bin` to `PATH` if `pyenv` is not on `PATH`. If Pyenv is installed via Homebrew, `pyenv` is already on `PATH` and nothing gets added.
It's written like this to work in all officially supported installation scenarios.

**Comment by tboddyspargo** [comment]
Thanks for helping to connect the dots, @native-api!

What was missing for me was the fact that the [`pyenv-installer` script](https://github.com/pyenv/pyenv-installer/tree/86a08ac9e38ec3a267e4b5c758891caf1233a2e4) is the (only?) thing that populates `$PYENV_ROOT/bin` (and only with `pyenv` itself). Without reading that script, it was difficult to see the connection between any of the installation methods in the pyenv README and that specific path (and it was easy to feel like some features might not work if I _didn't_ add `$PYENV_ROOT/bin` to my `PATH`).

https://github.com/pyenv/pyenv-installer/blob/86a08ac9e38ec3a267e4b5c758891caf1233a2e4/bin/pyenv-installer#L88-L89

I'm afraid I don't have any specific suggestions to make, but it seems like there may be an opportunity for improvement here (either of docs or of installation consistency).

**Comment by marcospgp** [comment]
Installing pyenv with brew results in no `$PYENV_ROOT/bin` directory.

This means the lines added to `.zshrc` when following the installation documentation are incorrect, because they specifically check for the existence of this directory.

This is still broken for me.
