### ISSUE TITLE
pyenv builds Python twice when "--enable-optimizations" is specified

### ISSUE THREAD

**Issue by alberthdev** [pyenv/pyenv#861]
When running the pyenv installer with `CONFIGURE_OPTS="--enable-optimizations" pyenv install -f 3.5.3`, pyenv ends up building Python twice. To clarify, this is including the profiling stage and the optimization stage of the compilation.

A normal optimized build essentially looks like this:

- Build Python initially with `-fprofile-generate`
- Run testsuite to generate profiling data for Python
- Rebuild Python with `-fprofile-use -fprofile-correction` to use profiling data for optimized builds
- Install optimized Python

However, pyenv ended up duplicating all of these steps twice. My guess is that this happened:
- make:
   - Build Python initially with `-fprofile-generate`
   - Run testsuite to generate profiling data for Python
   - Rebuild Python with `-fprofile-use -fprofile-correction` to use profiling data for optimized builds
   - Install optimized Python
- make install: (trigger repeat step)
   - Build Python initially with `-fprofile-generate`
   - Run testsuite to generate profiling data for Python
   - Rebuild Python with `-fprofile-use -fprofile-correction` to use profiling data for optimized builds
   - Install optimized Python

I've attached the full build log - it's a pretty large ~1.5 MB log, so beware! 
[python-build.20170312113419.6172.log.txt](https://github.com/pyenv/pyenv/files/846454/python-build.20170312113419.6172.log.txt)

**Comment by yyuu** [comment]
Sounds weird 😞  `python-build` should build CPython with just like usual `./configure && make && make install`. I guess there's something wrong with `--enable-optimizations`....

https://github.com/pyenv/pyenv/blob/d1ff898a2bfbe44d74bf92c2b6c9f7652b1d3aaa/plugins/python-build/bin/python-build#L712-L749

**Comment by alberthdev** [comment]
I'm not 100% sure, but if `make` does perform the install, then this may be on Python's end... if that's the case, it might be useful to provide a temporary workaround, e.g. grep for `--enable-optimizations` and then only run `make` if it's detected.

I'll do some further testing to see if this is the case!

**Comment by thehesiod** [comment]
typically on windows builds if you enable whole program optimization (https://msdn.microsoft.com/en-us/library/0zza0de8.aspx) it needs to run the built binary once to collect run time statistics, and then re build/link to the optimal way.  This may be as designed.

**Comment by draeath** [comment]
PGO intentionally builds twice. First pass is instrumented and is fed a training workload.

This is then used to build the "final" pass, the optimizations derived from that instrumented training workload.

Really, --enable-optimizations should probably be enabled in pyenv by default...

**Comment by draeath** [comment]
Seems this causes weirdness with python 2.7.13 at least. pyenv treats the missing modules like `sunaudiodev` as a build error and bails out, even though these are not fatal errors (indeed sunaudiodev is useless when not on a Sun box).

Python 3.6.2 builds fine though, so I blame this on a problem/quirk with the 2.7.x makefiles (setup.py is supposed to check for sun hardware, in that particular case, so it shouldn't even whine about it)

**Comment by chaimleib** [comment]
I actually don't want `--enable-optimizations` by default. Instead of taking under 2 minutes, installing a new python version would take about 15 minutes. That's significant to me.
```
$ export CONFIGURE_OPTS="--enable-optimizations"
$ time pyenv install 3.7.1
python-build: use openssl from homebrew
python-build: use readline from homebrew
Installing Python-3.7.1...
python-build: use readline from homebrew
Installed Python-3.7.1 to /Users/chaimleib/.pyenv/versions/3.7.1


real	15m2.065s
user	10m0.922s
sys	1m32.359s


$ pyenv uninstall 3.7.1
pyenv: remove /Users/chaimleib/.pyenv/versions/3.7.1? y
$ export CONFIGURE_OPTS=
$ time pyenv install 3.7.1
python-build: use openssl from homebrew
python-build: use readline from homebrew
Installing Python-3.7.1...
python-build: use readline from homebrew
Installed Python-3.7.1 to /Users/chaimleib/.pyenv/versions/3.7.1


real	1m45.493s
user	2m18.823s
sys	0m30.319s
```

**Comment by draeath** [comment]
Keep in mind, the results can be big. On our HPC system, I've seen up to 15%-20% faster code execution in some cases.

Worth considering.

**Comment by Zddd97** [comment]
> 请记住，结果可能会很大。在我们的HPC系统上，在某些情况下，我看到的代码执行速度提高了15％-20％。
> 
> 值得考虑。

Excuse me, under what cases did you measure 10-15% faster optimization? Can you give me the test code if you can? Thank you so much！

**Comment by blopker** [comment]
A note about `enable-optimizations`, by default it runs the entire test suite to train the optimizer. However, this quickly gets to diminishing returns. It turns out you can limit the number of tests run and still get most (if not all) of the performance benefits. This is what the official Docker image people did: https://github.com/docker-library/python/issues/160

Specifically: https://github.com/docker-library/python/issues/160#issuecomment-509426916

**Comment by native-api** [comment]
This is by design. `--enable-optimizations` does a [PGO (profile-guilded optimization)](https://en.wikipedia.org/wiki/Profile-guided_optimization) which requires to build stuff twice.

You don't need to do anything special to get a regular optimized build -- as long as it's not a debug build, `-O2` is enabled.

**Comment by benedikt-mue** [comment]
> A note about `enable-optimizations`, by default it runs the entire test suite to train the optimizer. However, this quickly gets to diminishing returns. It turns out you can limit the number of tests run and still get most (if not all) of the performance benefits. This is what the official Docker image people did: [docker-library/python#160](https://github.com/docker-library/python/issues/160)
> 
> Specifically: [docker-library/python#160 (comment)](https://github.com/docker-library/python/issues/160#issuecomment-509426916)

Have you tried to integrate it during pyenv installation? I ran into an error ...
