### ISSUE TITLE
Update .gitignore to exclude .gitmodules and pyenv/plugins

### ISSUE THREAD

**Issue by ridhwaans** [pyenv/pyenv#862]
Installed pyenv plugins as submodules index becomes dirty:
```
HEAD detached at
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   .gitmodules
	new file:   plugins/pyenv-virtualenv
```
Can we update .gitignore to exclude affected files and keep the index clean?

**Comment by blueyed** [comment]
Why have you installed it as submodule?
That way you are changing the repo itself after all.

You should clone plugins in `plugins/` instead (AFAIK).

Closing, but feel free to respond/discuss of course.

**Comment by ridhwaans** [comment]
Yes, I had cloned plugins in `plugins/` originally, I need to modify it as a submodule because my dotfiles repo script installs .apps and plugins like pyenv as submodules

**Comment by blueyed** [comment]
Then add it to your repos `.git/info/exclude` maybe?
