### ISSUE TITLE
Add support for PyPy2 5.7 and PyPy3 5.7?

### ISSUE THREAD

**Issue by dstufft** [pyenv/pyenv#865]
It'd be great to get support for PyPy 5.7 with a new release to match. Thanks!

**Comment by Samureus** [comment]
Waiting on https://github.com/squeaky-pl/portable-pypy/issues/45 for the portable Linux binaries, might be ready in the evening after I return from work (unless somebody else beats me to it).

**Comment by TiberiumPY** [comment]
@Samureus it's done, waiting for pyenv :)

**Comment by Samureus** [comment]
Portable PyPy PRs: https://github.com/pyenv/pyenv/pull/868 (2.7) and https://github.com/pyenv/pyenv/pull/869 (3.5).

**Comment by Samureus** [comment]
PyPy 3.5: https://github.com/pyenv/pyenv/pull/871 (let's see if the laptop charge gives me enough time for PyPy 2.7)

**Comment by Samureus** [comment]
PyPy 2.7: https://github.com/pyenv/pyenv/pull/872 (yay!)

**Comment by alex** [comment]
Looks like these are all merged, yay! Any chance of cutting a release?

**Comment by Samureus** [comment]
@yyuu @joshfriend, would you like to do a new release? I was thinking on adding Stackless 2.7.13 when it's ready, but it's up to you.

**Comment by yyuu** [comment]
@Samureus could you create new release from current master branch? Let's create another release for Stackless as needed.

**Comment by Samureus** [comment]
@yyuu @joshfriend looks like there might be a PyPy 5.7.1 release "soonish" (or not)? https://mail.python.org/pipermail/pypy-dev/2017-March/015065.html (I'd rather defer the release process to you guys for now, my git fu is not that great)

**Comment by joshfriend** [comment]
The release of CPython 3.6.1 seems like a good enough reason to do a release now, even with a PyPy release (possibly?) pending. I can try to do it tonight.

**Comment by Samureus** [comment]
@joshfriend :P "Hold my beer moment" --> https://github.com/pyenv/pyenv/pull/877

**Comment by Samureus** [comment]
@dstufft @alex https://github.com/pyenv/pyenv/releases/tag/v1.0.9

**Comment by joshfriend** [comment]
@Samureus thanks, I got tied up yesterday :+1:
