### ISSUE TITLE
pyenv install by Homebrew latest release is 1.0.8, which not includes version 3.6.1

### ISSUE THREAD

**Issue by yawthinking** [pyenv/pyenv#874]
~> pyenv install 3.6.1
python-build: definition not found: 3.6.1

See all available versions with `pyenv install --list'.

If the version you need is missing, try upgrading pyenv:

  brew update && brew upgrade pyenv

**Comment by yyuu** [comment]
why you expect it's included in the version. don't create silly issues.
https://github.com/pyenv/pyenv/blob/master/CHANGELOG.md#108
