### ISSUE TITLE
Would you create a new release with anaconda 4.3.1

### ISSUE THREAD

**Issue by bkbncn** [pyenv/pyenv#878]
I found there is a new release, but can I bother you to create a new release include the request #876 ?

Thanks

**Comment by Samureus** [comment]
Sorry for not noticing this before, I just merged #876. I'd like to confirm if #843 can be fixed by upgrading. I'd also like to deal with #854. Is this something that you can workaround with `conda update`, cloning the repository, or would you need a full release for CI testing/ etc.

@yuu @joshfriend what do you think?

**Comment by yuu** [comment]
I think mention name is a mistake.

**Comment by blueyed** [comment]
Sorry, @yyuu was meant.

**Comment by yyuu** [comment]
We cannot fix all problems at once. Especially if it's some distribution specific issue.

Let's just create a release from latest master and close this. I don't believe recent changes in pyenv caused #843, and it must be at least safe to create a new release. Will work for it if I can get a chance in this week.

**Comment by bkbncn** [comment]
I think we are not talking about the same question, my question actually is not an issue, it is to create a release include anaconda 4.3.1.  current latest release 1.0.9 includes up to anaconda 4.3.0.
and when I created this issue, #876 was not merged, now already merged, it is should be safe to create a new release. @yuu @Samureus

**Comment by Vortander** [comment]
I have the same request. Please, add anaconda 4.3.1 to pyenv install list.  I'm having serious problems with previous versions of anaconda in mac OS Sierra.

**Comment by bkbncn** [comment]
Thanks @yuu
