### ISSUE TITLE
Deprecation policy?

### ISSUE THREAD

**Issue by Samureus** [pyenv/pyenv#882]
Currently there are +/-300 definitions inside python-build, some of them very old. There are projects, e.g. PyPy and Miniconda/Anaconda that update very often, or new source releases that no longer compile with old versions of Debian (e.g. Stackless) due to old dependencies.

It would be great to start publishing some sort of deprecation policy in advance, e.g, "distribution/package XX will no longer work after version XX", to at least follow upstream deprecation policies, like for example, Ubuntu 12.04 reaches EOL in April:
https://lists.ubuntu.com/archives/ubuntu-security-announce/2017-March/003777.html

Or, Fedora 23 is no longer supported, even though we still have instructions for it:
https://fedoraproject.org/wiki/Releases

Or what to do with CPython 2.1.3 - 2.6.9? Does anybody use any of these?

The idea is that we can at least start doing integration testing on pull requests using maybe #617 (maybe with containers? we don't have enough buzzwords) to avoid "it works on my machine" issues.

**Comment by joshfriend** [comment]
I just removed the `3.2-dev` and `3.3-dev` targets since those branches have reached EOL (37299c88511158983ceae7c819cfa75855f09119), as well as some very old pypy-dev branches (734c341c468e531c16902534dde237288fc21a2b).

> Or what to do with CPython 2.1.3 - 2.6.9? Does anybody use any of these?

I would like to talk about these too, I see people keep trying to install extremely old pythons (#910 for example). I think it would be totally ok to remove all pythons pre-2.6.x. (I think people absolutely do still use 2.6.x ☹️). There are also versions like `2.7` which a person might assume installs the latest version of the 2.7.x branch, but really it installs a version from 2010. I believe that all 3.x branches pre-3.4 are also EOL now. It may be a good idea to keep the last release from those branches around though (3.3.6, 3.2.6, and 2.6.9 for example?) 

> PyPy and Miniconda/Anaconda that update very often

Yes, it feels like these multiply at an exponential rate 😝 .

**Comment by Samureus** [comment]
>     PyPy and Miniconda/Anaconda that update very often
> > Yes, it feels like these multiply at an exponential rate 😝 .

I'd say we could treat PyPy and *Conda as "evergreen" releases the same as Chrome/Firefox work, that is, just keep the last 3 releases and drop the rest.

As for CPython 2.7, we can assume that the system Python bundled in the OS is "somehow" well maintained and drop anything below 2.7.9-ish? the one that added support for OpenSSL 1.1?

**Comment by jimmywan** [comment]
Assuming they still work, where "work" is defined as actually installs properly, maybe just hide them by default and add a flag for accessing old builds? Presumably any that was at one point an official release might still be of use to someone... somewhere...

**Comment by joshfriend** [comment]
I wonder if there could be an "archived versions" plugin that the old versions would move to?

**Comment by chrahunt** [comment]
Regarding removing versions - if someone needs an older version they can always check out an older version of the repository. I don't think we need to do anything special for that case.

**Comment by mattip** [comment]
> I'd say we could treat PyPy and *Conda as "evergreen" releases the same as Chrome/Firefox work, that is, just keep the last 3 releases and drop the rest.

(PyPy core dev here). At least from PyPy's perspective, that seems like a good approach. Note that each release of PyPy actually is at least two versions of Python, for instance the last v7.3.1 release had Python2.7 and Python3.6. The upcoming v7.3.2 will hopefully have Python2.7, Python3.6, and Python3.7

**Comment by native-api** [comment]
To find out where to draw the cut-off line, **we need to first decide _what audience we're targeting._** This will give us the answer of **what versions they need in their work.**

---

I see 3 kind of versions wrt user demand:

1. **Maintained versions**
    * used in mainstream production
    * users expect things to just work, breakages in common environments are our job

    Includes:
    * versions for which at least bugfixes are accepted
    * (?) + Non-EOL versions for which only some kind of fixes are accepted

1. **Legacy versions**
    * used in some production where the owners don't want to upgrade
    * users expect that some manual tweaking may be required for things to keep working (envvars, additional command-line arguments, custom-built dependecies), but without touching the codebase
    * users expect to still be able to use Net-based tools, including package repos

     Includes:

    * EOL versions supported by non-EOL environments
    * + EOL versions supported by "recently"-EOL environments
        * **Questions arise here: how far back do we want to go here?**
            * Do we include all officially supported environments, or just up to released N years ago? (3 years? 5 years?)
            * What do we consider "recently"-EOL? 1 year? 2 years? 3 years?
            * Alternatively, we can count the time from Python version release rather than distro release
                * that'll be less complicated since we build most versions from vanilla sources while legacy distros typically resort to downstream patches to keep old versions working

1. **Ancient versions**
    * only used in some select environments, e.g.:
        * old self-contained applications that already do everything they need so no need to change anything
    * users expect they might need to tweak the codebase and/or use an older version of it
    * users also expect to have to get all the dependencies manually and/or build them from old sources

---

Side querstion:

* **Do we need to keep _all_ micro releases, or only N most recent ones?**
    * Since micro releases are supposed to be backward compatible, there's little value for a user in being able to check out a non-recent one with unfixed bugs -- right?

* **Do we want to _delete_ dev scripts for EOL versions?**

**Comment by native-api** [comment]
@pyenv/pyenv-core-maintainers 

To find out where to draw the cut-off line, **we need to first decide _what audience we're targeting._** This will give us the answer of **what versions they need in their work.**

---

I see 3 kind of versions wrt user demand:

1. **Maintained versions**
    * used in mainstream production
    * users expect things to just work, breakages in common environments are our job

    Includes:
    * versions for which at least bugfixes are accepted
    * (?) + Non-EOL versions for which only some kind of fixes are accepted (extended support versions)
        * **Do these belong here or in the next category?**

1. **Legacy versions**
    * used in some production where the owners don't want to upgrade
    * users expect that some manual tweaking may be required for things to keep working (envvars, additional command-line arguments, custom-built dependecies), but without touching the codebase
    * users expect to still be able to use Net-based tools, including package repos

     Includes:

    * EOL versions supported by non-EOL environments
    * &ZeroWidthSpace;+ EOL versions supported by "recently"-EOL environments
        * **A question arises here: how far back do we want to go?**
            * Do we include all officially supported environments, or just up to released N years ago? (3 years? 5 years?)
            * What do we consider "recently"-EOL? 1 year? 2 years? 3 years?
            * Alternatively, we can count the time from Python version release rather than distro release
                * that'll be less complicated since we build most versions from vanilla sources while legacy distros typically resort to downstream patches to keep old versions working

1. **Ancient versions**
    * only used in some select environments, e.g.:
        * old self-contained applications that already do everything they need so no need to change anything
    * users expect they might need to tweak the codebase and/or use an older version of it
    * users also expect to have to get all the dependencies manually and/or build them from old sources

---

Side querstion:

* **Do we need to keep _all_ micro releases, or only N most recent ones?**
    * Since micro releases are supposed to be backward compatible, there's little value for a user in being able to check out a non-recent one with unfixed bugs -- right?

* **Do we want to _delete_ dev scripts for EOL versions?**

**Comment by molinav** [comment]
One of the very positive things that I find in `pyenv` is that one can really try to install *almost any* stable Python version, even those that are EOL. It is totally understandable that somebody should not expect that e.g. patches for EOL versions will be kept up-to-date forever by the `pyenv` maintainers, but I think that keeping the patches there just does not harm.

In my case for example, I still need to take care of maintaining systems with some EOL Pythons, and for these I use `pyenv` as part of my pipelines while developing, since `pyenv` + Docker makes it so easy to create test Python environments that will behave like in production.

From the side questions:
- Micro releases are supposed to be backwards compatible. However, it is a bit trickier when the OpenSSL version transitions take place (e.g. from 2.7.12 to 2.7.13, from 3.5.2 to 3.5.3). Python 2.7.13-18 and 3.5.3-3.5.10 will compile with OpenSSL 1.0.2 and 1.1.1, but Python 2.7.0-2.7.12 and 3.5.0-3.5.2 will fail if not using the older OpenSSL version (1.0.2).
- In the case of the dev scripts for EOL versions, I think it would be ok to delete them, since they were never stable versions.

What I did see these last days while playing with the Python 2.6/3.1 patches (#2047, #2049, #2051) is that there is a lot of redundancy in the patch files, but I do not know at the moment whether it could be possible (and sensible) to reduce this redundancy.

**Comment by tomschr** [comment]
> One of the very positive things that I find in `pyenv` is that one can really try to install _almost any_ stable Python version, even those that are EOL.

That's the case. Perhaps we could approach this from a different side?

Maybe it's not so the question of deprecation this or that, but listing what's available and supported?

For example, `pyenv install --list` gives me a _very long_ list of versions that I can install.  Even some _very old_ ones like 2.1.3.

Listing these exotic versions should be neither listed nor recommended. By default, `pyenv install --list` should exclude these very old versions. 

So here is my idea:

* List only supported versions by `pyenv install --list`.
* Hide EOL versions under an additional option. Let's say, with `--list-eol-only` you get only the versions which are EOL.
* Keep old versions as long as they compile and it's doesn't make any effort.
* Show a message and ask the user when someone wants a EOL version. This could look like this:

        $ pyenv install 2.1.3
        WARNING: Version 2.1.3 is end of life (EOL). No security issues or bugs are fixed.
        If this was an mistake, install a more recent version:
          * For Python2, use 2.7.x
          * For Python3, use any version >=3.6.x

        Continue (yes/NO)? 

It may not directly help with the original question. However, it's kind of "out of sight" and could improve what should go into the EOL list and what not.

Would that be an option?

**Comment by native-api** [comment]
I've authored a contribution guide. Interested parties and especially @pyenv/pyenv-core-maintainers , please review the text -- in particular, see if you agree with the presented policies and formulations (I suspect that the formulations might sound imposing and/or stricter than they actually are).

Also please see if I missed or failed to cover anything.
