### ISSUE TITLE
Update install documentation

### ISSUE THREAD

**Issue by fnscoder** [pyenv/pyenv#894]
I've problem trying to install pyenv on Linux Manjaro. I solved using the tip of step 2 about ubuntu and fedora.

Step 2 of installation. The observation about .bashrc and .bash_profile on ubuntu and fedora aplies to arch and manjaro too. [https://github.com/pyenv/pyenv#basic-github-checkout](url)

I suggest an update on documentation, Can I do it?

**Comment by yyuu** [comment]
Please just do and open a PR. Tnaks in advance.

**Comment by blueyed** [comment]
@fnscoder 
I think it really depends on if you want to have better performance (one-time init), vs. working right away (do it in rc).
IIRC there was some issue / discussion about improving the README in this regard, but I could not find it now.

**Comment by blueyed** [comment]
Related: https://github.com/pyenv/pyenv/issues/810 /cc @piotr-dobrogost

**Comment by blueyed** [comment]
@fnscoder 
So it might be nice, if you could try looking at previous issues / PRs in this regard (also in pyenv-virtualenv maybe), and then we should have it more generic, instead of based on distribution names.
