### ISSUE TITLE
pyenv doesn't switch python version

### ISSUE THREAD

**Issue by xareelee** [pyenv/pyenv#896]
After installing and using the latest python on **macOS**, the python version still is system version (2.7.12).

```sh
# Current version: system (2.7.12)
$ python --version
Python 2.7.12

$ pyenv versions
* system


# Install 3.6.1
$ pyenv install 3.6.1

$ pyenv versions
* system
  3.6.1 (set by /Users/Xaree/.python-version)


# Use 3.6.1
$ pyenv global 3.6.1
 
$ $ pyenv versions
  system
* 3.6.1 (set by /Users/Xaree/.python-version)


# Python still is system version (2.7.12)
$ python --version
Python 2.7.12

$ python
Python 2.7.12 (default, Oct 14 2016, 15:14:19) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Do I miss something?

**Comment by xareelee** [comment]
I found adding `eval "$(pyenv init -)"` in the `~/.bash_profile` solves this issue.

**Comment by edarioq** [comment]
If you use **zsh**, make sure to add @xareelee's answer to your `.zshrc`

**Comment by a8t** [comment]
for `fish` shell – https://github.com/pyenv/pyenv/issues/32#issuecomment-68543034

> ```
> # Load pyenv automatically by adding
> # the following to ~/.config/fish/config.fish:
> 
> status --is-interactive; and . (pyenv init -|psub)
> ```

**Comment by nickolasclarke** [comment]
> 
> 
> for `fish` shell – [#32 (comment)](https://github.com/pyenv/pyenv/issues/32#issuecomment-68543034)
> 
> > ```
> > # Load pyenv automatically by adding
> > # the following to ~/.config/fish/config.fish:
> > 
> > status --is-interactive; and . (pyenv init -|psub)
> > ```

this should now be: 

```
set -x PATH "/home/<YOUR USERNAME>/.pyenv/bin" $PATH
status --is-interactive; and pyenv init - | source
status --is-interactive; and pyenv virtualenv-init - | source
```

see [fish-shell/fish-shell/#6613](https://github.com/fish-shell/fish-shell/issues/6613)

**Comment by AkgunFatih** [comment]
i have this in my zshrc 
```
export PATH=$HOME/.pyenv/bin:$PATH
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

but still can't change the damn version

**Comment by nickarino** [comment]
After running
> echo $SHELL
/bin/bash

and putting this in .bashrc
export PATH=$HOME/.pyenv/bin:$PATH
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

source .bashrc

worked.

**Comment by Gatsby-Lee** [comment]
For me, on macOS, this works

added these into at the bottom of ~/.zshrc
```
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
```

**Comment by vitahoang** [comment]
> For me, on macOS + zsh, this works
> 
> added these into at the bottom of ~/.zshrc
> 
> ```
> eval "$(pyenv init --path)"
> eval "$(pyenv init -)"
> ```
Works for me

**Comment by davelee-weperson** [comment]
> For me, on macOS + zsh, this works
> 
> added these into at the bottom of ~/.zshrc
> 
> ```
> eval "$(pyenv init --path)"
> eval "$(pyenv init -)"
> ```
> 
> I saw a glist that says the config in ~/.zshrc should be like this. Honestly, I am not sure why I need other stuff the two lines I mentioned above.
> 
> ```
> export PYENV_ROOT="$HOME/.pyenv"
> export PATH="$PYENV_ROOT/bin:$PATH"
> export PIPENV_PYTHON="$PYENV_ROOT/shims/python"
> 
> plugin=(
>   pyenv
> )
> 
> eval "$(pyenv init --path)"
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```

eval "$(pyenv init --path)" worked like a charm! Thanks!
