### ISSUE TITLE
"ERROR: invalid Python executable" when installing 3.6 on osx

### ISSUE THREAD

**Issue by Daenyth** [pyenv/pyenv#900]
```
$> pyenv --version
pyenv 1.0.10
$> pyenv install 3.6-dev
Cloning https://hg.python.org/cpython...
Installing Python-3.6-dev...
ERROR: invalid Python executable: /Users/daenyth/.pyenv/versions/3.6-dev/bin/python3.6

The python-build could not find proper executable of Python after successful build.
Please open an issue for future improvements.
https://github.com/yyuu/pyenv/issues

BUILD FAILED (OS X 10.11.5 using python-build 1.0.0-18-g6601c34)

Inspect or clean up the working tree at /var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/python-build.20170428102316.12035
Results logged to /var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/python-build.20170428102316.12035.log

Last 10 log lines:
			upgrade) ensurepip="--upgrade" ;; \
			install|*) ensurepip="" ;; \
		esac; \
		 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0
```

**Comment by joshfriend** [comment]
How sure are you that the `3.6-dev` branch produces an executable successfully? It is a development branch after all...

@yyuu @blueyed I feel that we should just remove the `*-dev` options from pyenv. People probably only install them by accident since `3.6-dev` is the first thing that tab completes from `pyenv install 3.6`. They also just clutter an already lengthy list of available pythons to install.

**Comment by Daenyth** [comment]
I guess I'm not. The error message told me to report the bug here, so I did.

Why isn't there a 3.6.0 and 3.6.1 option?

**Comment by joshfriend** [comment]
> Why isn't there a 3.6.0 and 3.6.1 option?

Those options definitely exist, is pyenv up to date?

**Comment by Daenyth** [comment]
I have `pyenv 1.0.10` according to `--version`, it's the latest installable with homebrew. Though checking homebrew, it seems that homebrew versions pyenv at `20160509`.

Is that something you guys need to handle or should I bug homebrew to update their stuff?

**Comment by yyuu** [comment]
@joshfriend It's less often, but sometime I want to install from latest development HEAD for some testing.... 😕  I don't want to remove '*-dev' ig possible. Though I agreed that it'd be better if dev version is the first option in completion.

**Comment by Daenyth** [comment]
@joshfriend Looking at the releases tab on this repo it seems that I do have the latest release of pyenv, but I definitely don't have a 3.6.0 or 3.6.1

```
$> pyenv install -l | grep ' 3\.6'
  3.6.0a4
  3.6-dev
```

**Comment by yyuu** [comment]
@Daenyth it must be just a misconfiguration of your system. I guess you have 2 installations of pyenv in your system and they are conflicting somehow. I'd recommend you to once uninstalling pyenv from both brew and your ~/.pyenv, then reinstall again. See also README about installation instruction.

**Comment by Daenyth** [comment]
The installation instructions tell me to install it with homebrew.

I uninstalled it and deleted ~/.pyenv. After reinstalling I do see the current 3.6 versions, so I have no idea what went wrong there.

**Comment by weaming** [comment]
Same error, can't figure out what's going wrong :(
