### ISSUE TITLE
sha256sum in openwrt adds space at the end

### ISSUE THREAD

**Issue by fernand0** [pyenv/pyenv#902]
Hello,

I suppose it is a problem in openwrt (I'm trying to use pyenv in an Onion Omega 2 machine) implementation but when trying pyenv install it stops because sha256sum returns the hash plus some space and a '-'. 

I've solved it modifying the file:
     plugins/python-build/bin/python-build
in such a way that the line that computes the checksum is:
  local computed_checksum=`echo "$($checksum_command < "$filename")" | tr [A-Z] [a-z] | cut -d $' ' -f 1` 
That is, I've added | cut -d $' ' -f in order to deal with these extra characters...

I'm not sure about submitting a patch because I have not the adequate tools to test it now in other systems.

Best regards and keep up the good work!

**Comment by yyuu** [comment]
I'm not very familiar with OpenWRT, but I guess its `sha256sum` must be Busybox, not from GNU coreutils. I think you modified https://github.com/pyenv/pyenv/blob/v1.0.10/plugins/python-build/bin/python-build#L307 to remove unnecessary whitespaces.

For further investigation, could you show me the output of `echo foo | sha256sum -b | od -c` on your OpenWRT box? The following output is sample output from my Debian GNU/Linux amd64 box.

```
% echo foo | sha256sum -b | od -c
0000000   b   5   b   b   9   d   8   0   1   4   a   0   f   9   b   1
0000020   d   6   1   e   2   1   e   7   9   6   d   7   8   d   c   c
0000040   d   f   1   3   5   2   f   2   3   c   d   3   2   8   1   2
0000060   f   4   8   5   0   b   8   7   8   a   e   4   9   4   4   c
0000100       *   -  \n
0000104
```

Plus, if there are problem with BusyBox (or some OpenWRT's toolchain), it might be better to apply some patch to https://github.com/rbenv/ruby-build. Anyway please share the output from `sha256sum` command when you get a chance.

**Comment by fernand0** [comment]
Sorry, I'm not familiar with openwrt neither. Maybe it is the BusyBox you say. Just in case, there is no od available but I have hexdump. The result of `echo foo | sha256sum -b | hexdump -c' is:

```shell
0000000   b   5   b   b   9   d   8   0   1   4   a   0   f   9   b   1
0000010   d   6   1   e   2   1   e   7   9   6   d   7   8   d   c   c
0000020   d   f   1   3   5   2   f   2   3   c   d   3   2   8   1   2
0000030   f   4   8   5   0   b   8   7   8   a   e   4   9   4   4   c
0000040           -  \n                                                
0000044
```

It looks equal than your output and mine in an Ubuntu box.

**Comment by Gr1N** [comment]
Got same problem with `alpine:3.6`:

```
/usr/local/pyenv # ./bin/pyenv install 3.6.2
Downloading Python-3.6.2.tgz...
-> https://www.python.org/ftp/python/3.6.2/Python-3.6.2.tgz

BUILD FAILED (Alpine Linux 3.6.2 using python-build 1.1.3-23-gd92e190)

Inspect or clean up the working tree at /tmp/python-build.20170825154613.344
Results logged to /tmp/python-build.20170825154613.344.log

Last 10 log lines:
/tmp/python-build.20170825154613.344 /usr/local/pyenv

checksum mismatch: Python-3.6.2.tar.gz (file is corrupt)
expected 7919489310a5f17f7acbab64d731e46dca0702874840dadce8bd4b2b3b8e7a82, got 7919489310a5f17f7acbab64d731e46dca0702874840dadce8bd4b2b3b8e7a82 <-- extra space here
```

And output:
```
/usr/local/pyenv # echo foo | sha256sum -b | hexdump -c
0000000   b   5   b   b   9   d   8   0   1   4   a   0   f   9   b   1
0000010   d   6   1   e   2   1   e   7   9   6   d   7   8   d   c   c
0000020   d   f   1   3   5   2   f   2   3   c   d   3   2   8   1   2
0000030   f   4   8   5   0   b   8   7   8   a   e   4   9   4   4   c
0000040           -  \n
0000044
```

**Comment by Gr1N** [comment]
Details about sha256sum on alpine https://github.com/gliderlabs/docker-alpine/issues/174#issuecomment-222951567

**Comment by Gr1N** [comment]
@yyuu, could you please look? Maybe we can fix this on `pyenv` side?

**Comment by Gr1N** [comment]
Here is a simple fix:
```
diff --git a/plugins/python-build/bin/python-build b/plugins/python-build/bin/python-build
index 1037006..f48f8dd 100755
--- a/plugins/python-build/bin/python-build
+++ b/plugins/python-build/bin/python-build
@@ -282,7 +282,7 @@ has_checksum_support() {
 verify_checksum() {
   local checksum_command
   local filename="$1"
-  local expected_checksum="$(echo "$2" | tr [A-Z] [a-z])"
+  local expected_checksum="$(echo "$2" | tr [A-Z] [a-z] | tr -d " ")"
 
   # If the specified filename doesn't exist, return success
   [ -e "$filename" ] || return 0
@@ -304,7 +304,7 @@ verify_checksum() {
   has_checksum_support "$checksum_command" || return 0
 
   # If the computed checksum is empty, return failure
-  local computed_checksum=`echo "$($checksum_command < "$filename")" | tr [A-Z] [a-z]`
+  local computed_checksum=`echo "$($checksum_command < "$filename")" | tr [A-Z] [a-z] | tr -d " "`
   [ -n "$computed_checksum" ] || return 1
 
   if [ "$expected_checksum" != "$computed_checksum" ]; then

```
I can create PR if it looks good.

**Comment by yyuu** [comment]
@Gr1N I've not yet tested on alpine, but I guess just greedily removing characters after some whitespace must be sufficient.

```
diff --git a/plugins/python-build/bin/python-build b/plugins/python-build/bin/python-build
index 1037006..4f8b994 100755
--- a/plugins/python-build/bin/python-build
+++ b/plugins/python-build/bin/python-build
@@ -248,7 +248,7 @@ compute_sha2() {
     echo "${output##* }"
   elif type sha256sum &>/dev/null; then
     output="$(sha256sum -b)" || return 1
-    echo "${output% *}"
+    echo "${output%% *}"
   else
     return 1
   fi
@@ -263,7 +263,7 @@ compute_md5() {
     echo "${output##* }"
   elif type md5sum &>/dev/null; then
     output="$(md5sum -b)" || return 1
-    echo "${output% *}"
+    echo "${output%% *}"
   else
     return 1
   fi
```

Feel free to open PR. And, I want you to open same fix to https://github.com/rbenv/ruby-build as well.

**Comment by Gr1N** [comment]
PR and issue in https://github.com/rbenv/ruby-build were created.

**Comment by yyuu** [comment]
It seems that you opened rbenv/ruby-build#1126. I'll prepare a PR since most of the code around it is equivalent.

**Comment by Gr1N** [comment]
@yyuu @blueyed could you please release new version of pyenv with fix?

**Comment by joshfriend** [comment]
@Gr1N is there a reason you can't just use `master`?

**Comment by Gr1N** [comment]
Yes, for example, I want to build docker images with pyenv and I want stricly specify which version of pyenv I want to use. I don't want to use master because on each docker image rebuild I can possibly have new version of pyenv. This is a common practice to pin dependency versions.

**Comment by blueyed** [comment]
@Gr1N 
You can checkout a specific commit, too - in case you want to pin it.
Or just wait for the next release.. ;)

**Comment by Gr1N** [comment]
@blueyed do you have any release date?

**Comment by blueyed** [comment]
@Gr1N 
I am just a contributor - never did a release myself.

**Comment by Gr1N** [comment]
@blueyed oh, sorry.
