### ISSUE TITLE
[question] pyenv rehash on any shimmed command?

### ISSUE THREAD

**Issue by LarsFronius** [pyenv/pyenv#908]
While working on https://github.com/pyenv/pyenv/pull/907 I was wondering why we are so specific about when we are rehashing?
Seems like it was a deliberate choice for only pip/conda/easy_install to trigger a rehash and not any other command. Was there an issue for "any" command, that is shimmed to trigger a rehash?

I reckon a `python setup.py install` may install new executables in the bin folder, which is not being automatically rehashed at the moment, and there is probably many more ways, independent by the used executable that might need a rehash to be triggered, to make an installed executable available.

Would just like to hear everyone opinion on this. Thanks!

**Comment by yyuu** [comment]
Basically it's for performance. It's not a problem even if we do so on modern x86 systems with faster I/O drives. Though it could impose certain amount of overhead for all invocations of python executables on smaller systems, like Raspberry Pi.

**Comment by LarsFronius** [comment]
Good to know @yyuu - thanks for the insight! Do you want me to explore adding a flag or similar to do so?
Otherwise I might just patch pyenv on my end for my use-case.
Up to you whether you think this could be part of pyenv's core or not.

**Comment by yyuu** [comment]
I guess not so many users want to run rehash on every invocations of shims. At least for now, I'd recommend you to use your custom patch, or custom hook script to override original `pip-rehash.bash` (you can install your own custom hook script in `$PYENV_HOOK_PATH`; https://github.com/pyenv/pyenv/blob/v1.0.10/libexec/pyenv#L91) if you want to do so.

**Comment by LarsFronius** [comment]
Thanks @yyuu !
For anybody else who is interested in doing so, I published the code at and installation instructions at https://gist.github.com/LarsFronius/4d3167dfd0df168d2ab50576e3ebd315
