### ISSUE TITLE
can not install python versions 2.5.x. ( No module named _md5 )

### ISSUE THREAD

**Issue by aaronchn** [pyenv/pyenv#910]
- OS: ManjaroLinux 17.0.1 (arch)

- pyenv : 1.1.3

- PYENV_ROOT=/home/aaron/dev/pyenv

- System default python
Python: 3.6.2
Python2: 2.7.13

- Error:BUILD FAILED (ManjaroLinux 17.0.1 using python-build 20160602)

```Last 10 log lines:
    from setuptools.compat import numeric_types, basestring
  File "/tmp/python-build.20170515155335.15085/setuptools-1.4.2/setuptools/compat.py", line 31, in <module>
    import urllib2

  File "/home/aaron/dev/pyenv/versions/2.5/lib/python2.5/urllib2.py", line 88, in <module>
    import hashlib

  File "/home/aaron/dev/pyenv/versions/2.5/lib/python2.5/hashlib.py", line 104, in <module>
    md5 = __get_builtin_constructor('md5')

  File "/home/aaron/dev/pyenv/versions/2.5/lib/python2.5/hashlib.py", line 31, in __get_builtin_constructor
    import _md5
ImportError: No module named _md5```

**Comment by xsteadfastx** [comment]
the same for me. no new about this?

**Comment by aaronchn** [comment]
@xsteadfastx 
Sill bemused，none any going on this.
Is your PYENV_ROOT value "$HOME/.pyenv"in your path?

**Comment by joshfriend** [comment]
Why are you trying to use a python version that is 11 years old?

**Comment by aaronchn** [comment]
@joshfriend 
Thanks your attention.
Try to install python 2.5.6 (2011-05-26) will show the same error,try to install python 2.6.9(2013-10-29) 2.7.1(2010-11-27) will show "ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?"But openssl certainly installed in my OS.
`[aaron@hp ~]$ openssl`
`openssl      openssl-1.0`
`[aaron@hp ~]$`

**Comment by joshfriend** [comment]
Closing since I would agree with the assessment made by @xsteadfastx. You also should not:

1. expect versions of python that old to compile with the newest versions of openssl
2. use versions of python that are that ancient if you can at all help it
