### ISSUE TITLE
warning about --enable-unicode in configure phase of 3.6.1

### ISSUE THREAD

**Issue by wbolster** [pyenv/pyenv#912]
running `pyenv install 3.6.1 -v` shows (among normal `./configure` output) this warning:

```
configure: WARNING: unrecognized options: --enable-unicode
```

is this something that `pyenv` should address?

**Comment by wbolster** [comment]
the `Misc/HISTORY` for `cpython` contains this entry in the notes for an early 3.0 version:

```
- Renamed --enable-unicode configure flag to --with-wide-unicode,
  since Unicode strings can't be disabled anymore.
```

**Comment by methane** [comment]
Since Python 3.3, no options is needed.
Thanks to Flexible Unicode Representation, no "wide" and "narrow" build.

**Comment by yyuu** [comment]
This is adding the option as a configure options. It'd be better to skip it based on the building version....

https://github.com/pyenv/pyenv/blob/master/plugins/python-build/bin/python-build#L1978

**Comment by yyuu** [comment]
Just prepared a workaround. Though actually I've not yet tested it throughly.... Please try #978 if there's someone whom interested in this topic.
