### ISSUE TITLE
Pyenv don't see system python3 version on Fedora 25

### ISSUE THREAD

**Issue by Agmr** [pyenv/pyenv#914]
On Fedora 25 workstation system python version is 3.5.3

after installing pyenv
and installing python 2.7.13 with pyenv 

"pyenv versions" shows only 2.7.13:
$ pyenv versions
  2.7.13

after executing "pyenv global system":
$ pyenv global system
pyenv: system version not found in PATH

environment variables set up:
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

Also, when trying to install python 2.6.6 i am getting an error:
$ pyenv install 2.6.6
Downloading Python-2.6.6.tgz...
-> https://www.python.org/ftp/python/2.6.6/Python-2.6.6.tgz
Installing Python-2.6.6...
/home/mrnoone/.pyenv/plugins/python-build/bin/python-build: line 1487: patch: command not found

BUILD FAILED (Fedora 25 using python-build 1.0.10-22-g3292200)

Inspect or clean up the working tree at /tmp...

anybody knows how to solve this issues?
Thank you

**Comment by joshfriend** [comment]
For anyone that comes across this in the future, `patch: command not found` mean's you need the `patch` utility installed. Also, please stop using python 2.6.x, it's beyond dead at this point :P
