### ISSUE TITLE
Fails to build on Arch for older Python versions (related to openssl)

### ISSUE THREAD

**Issue by MaximilianKindshofer** [pyenv/pyenv#916]
Hi while installing any python version I get the following error:

Ignoring ensurepip failure: pip 7.1.2 requires SSL/TLS
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems

The wiki didn't came up with a solution, do you have any suggestions on how to solve this?

**Comment by rodneykeeling** [comment]
Also having this issue.

**Comment by blueyed** [comment]
Cannot confirm - just tried reinstalling `2.7.13`.

What openssl packages do you have installed?

```
% pacman -Q | grep openssl
lib32-openssl 1:1.1.0.e-1
openssl 1.1.0.e-1
openssl-1.0 1.0.2.k-3
python-pyopenssl 17.0.0-1
python2-pyopenssl 17.0.0-1
```

**Comment by rodneykeeling** [comment]
```
> pacman -Q | grep openssl       
lib32-openssl 1:1.1.0.e-1
libcurl-openssl-1.0 7.54.0-2
libopenssl-1.0-compat 1.0.2.k-3
openssl 1.1.0.e-1
openssl-1.0 1.0.2.k-3
python-pyopenssl 17.0.0-1
python2-pyopenssl 17.0.0-1
```
Interesting, though—2.7.13 installed just fine, but for the sake of testing, I just tried installing 2.7.9 (❌), 2.7.10 (❌), 2.7.11 (❌), and 2.7.12 (❌). So it only seems to be working (on my machine) for 2.7.13.

Here is the output for all of the failed versions:
```
> pyenv install 2.7.9 
Downloading Python-2.7.9.tar.xz...
-> https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tar.xz
Installing Python-2.7.9...
patching file ./Lib/site.py
patching file ./Lib/ssl.py
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (Arch Linux using python-build 1.0.10-22-g3292200)

Inspect or clean up the working tree at /tmp/python-build.20170519121640.18276
Results logged to /tmp/python-build.20170519121640.18276.log

Last 10 log lines:
rm -f /home/rodney/.pyenv/versions/2.7.9/share/man/man1/python.1
(cd /home/rodney/.pyenv/versions/2.7.9/share/man/man1; ln -s python2.1 python.1)
if test "xno" != "xno"  ; then \
	case no in \
		upgrade) ensurepip="--upgrade" ;; \
		install|*) ensurepip="" ;; \
	esac; \
	 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
```

**Comment by blueyed** [comment]
Yeah, so much much for being specific about "any version".

3.6.1 also worked fine.

Can confirm it for 2.7.9.
Looking at the build log it says:
```
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -IInclud
/tmp/python-build.20170519212756.11217/Python-2.7.9/Modules/_ssl.c: In function ‘_create_tuple_for_X509
/tmp/python-build.20170519212756.11217/Python-2.7.9/Modules/_ssl.c:675:35: error: dereferencing pointer
             if (rdn_level != entry->set) {
                                   ^~
```

**Comment by MaximilianKindshofer** [comment]
Ok I may not been any version (sorry I was frustrated at this point)
3.6.1 works for me too 3.5.1 fails (not sure if 3.5.1 qualifies as an older version)

But at least I am not the only one - I was getting mad over this

**Comment by KenMacD** [comment]
I ran in to this trying to install `3.3.6` and it installed using:

`LDFLAGS=-L/usr/lib/openssl-1.0 CFLAGS="-DOPENSSL_NO_SSL3 -I/usr/include/openssl-1.0" pyenv install -v 3.3.6`

**Comment by all3fox** [comment]
For me on Archlinux with current version of `pyenv` from github master, the following works:

`pyenv install 2.7.13`

But all these (as reported by @rodneykeeling) are failing: `2.7.9`, `2.7.10`, `2.7.11`, `2.7.12`. Additionally `pyenv install 2.7` also fails. The failure is the same as above: missing OpenSSL lib.

My pyenv is:
```
alex@k-2so ~ % pyenv --version
pyenv 1.0.10-48-g01d3985
```

**Comment by bbcoimbra** [comment]
:+1: for `pyenv install 2.7.13` as said by @all3fox 

it worked for
```
$ uname -a
Linux morgana 4.11.6-3-ARCH #1 SMP PREEMPT Thu Jun 22 12:21:46 CEST 2017 x86_64 GNU/Linux
$ pyenv --version
pyenv 1.1.1-5-g7467eec
```

**Comment by agireud** [comment]
Running on a fresh Arch Linux and encountered the same issue installing python 3.4.3.
Can confirm that @KenMacD's solution worked.

`LDFLAGS=-L/usr/lib/openssl-1.0 CFLAGS="-DOPENSSL_NO_SSL3 -I/usr/include/openssl-1.0" pyenv install -v 3.4.3`

**Comment by vlcinsky** [comment]
I had very similar issue on Ubuntu 16.04.
Initially all worked well (installed python 2.7.13 and 3.6.1 via pyenv), used it with tox.
After some moment (probably after some updates of the system) I was unable to install anything via pip with the error complaining about missing SSL/TLS support.

My solution: use pyenv to uninstall and install the python environment. Since then, it works.

**Comment by jimcrozier** [comment]
fwiw I solved this on centos by installing openssl-devel.

**Comment by aadeshere1** [comment]
OpenSSL 1.1.0
Can confirm @KenMacD solution works for `2.7.9` 👍

**Comment by dmarcoux** [comment]
I had the same issue and ended up using the following:

`LDFLAGS="-L/usr/lib/openssl-1.0" CFLAGS="-I/usr/include/openssl-1.0" pyenv install -v 3.4.3`

I added it to the [wiki's Common build problems page](https://github.com/pyenv/pyenv/wiki/Common-build-problems). Thanks to @KenMacD for the original solution. I only removed `-DOPENSSL_NO_SSL3` inside `CFLAGS` as it didn't make a difference.

**Comment by davidrios** [comment]
On Debian 9 the libssl-dev package is for version 1.1.0, to compile older Pythons you need to install libssl1.0-dev. But you can only have one installed, so install libssl1.0-dev to compile Python, then install libssl-dev to get the latest version again.

**Comment by urkh** [comment]
On Manjaro 18, v3.1.3 works with 

`LDFLAGS=-L/usr/lib/openssl-1.0 CFLAGS="-DOPENSSL_NO_SSL3 -I/usr/include/openssl-1.0" pyenv install -v 3.1.3`

**Comment by rgalbo** [comment]
> +1 for `pyenv install 2.7.13` as said by @all3fox
> 
> it worked for
> 
> ```
> $ uname -a
> Linux morgana 4.11.6-3-ARCH #1 SMP PREEMPT Thu Jun 22 12:21:46 CEST 2017 x86_64 GNU/Linux
> $ pyenv --version
> pyenv 1.1.1-5-g7467eec
> ```

this is actually hilarious that 2.7.7 wont install but 2.7.13 does :\

**Comment by blueyed** [comment]
> this is actually hilarious that 2.7.7 wont install but 2.7.13 does :\

2.7.7 is from 2014 - 2.7.13 2,5 years younger - so not really unexpected, is it? :)
(anyway, off topic)

**Comment by eepp** [comment]
> I had the same issue and ended up using the following:
> 
> `LDFLAGS="-L/usr/lib/openssl-1.0" CFLAGS="-I/usr/include/openssl-1.0" pyenv install -v 3.4.3`
> 
> I added it to the [wiki's Common build problems page](https://github.com/pyenv/pyenv/wiki/Common-build-problems). Thanks to @KenMacD for the original solution. I only removed `-DOPENSSL_NO_SSL3` inside `CFLAGS` as it didn't make a difference.

This is the correct solution.

**Comment by blueyed** [comment]
@eepp 
Can you provide more information about your system?

I wonder if https://github.com/pyenv/pyenv/pull/1312 would have helped there.

**Comment by anushageorge** [comment]
sudo apt-get install libssl1.0
This worked for me. Ubuntu 18.

**Comment by herculan0** [comment]
> I ran in to this trying to install `3.3.6` and it installed using:
> 
> `LDFLAGS=-L/usr/lib/openssl-1.0 CFLAGS="-DOPENSSL_NO_SSL3 -I/usr/include/openssl-1.0" pyenv install -v 3.3.6`

I'm having the same issue with pyenv install 2.7.9
Running on Manjaro 19.01
Then I install some packages that https://github.com/pyenv/pyenv/wiki/common-build-problems tell me to install

> pacman -S --needed base-devel openssl zlib bzip2 readline sqlite curl \
llvm ncurses xz tk libffi python-pyopenssl git
>
>yay -S ncurses5-compat-libs 


Then run:

>LDFLAGS=-L/usr/lib/openssl-1.0 CFLAGS="-I/usr/include/openssl-1.0" pyenv install 2.7.9

Works well now, thanks @KenMacD

**Comment by Anu2006-dev** [comment]
@KenMacD How did you find the solution? because I think this is the only place that has the answer. and you are not a contributer or author. did you study the code base or some thing. btw  thanks a world for your help.

**Comment by minaee** [comment]
> Cannot confirm - just tried reinstalling `2.7.13`.
> 
> What openssl packages do you have installed?
> 
> ```
> % pacman -Q | grep openssl
> lib32-openssl 1:1.1.0.e-1
> openssl 1.1.0.e-1
> openssl-1.0 1.0.2.k-3
> python-pyopenssl 17.0.0-1
> python2-pyopenssl 17.0.0-1
> ```

I get the same error after installed Python 3.4.2.
and the output of `pacman -Q | grep openssl` is:


    XIO:  fatal IO error 22 (Invalid argument) on X server ":0"
             after 5112 requests (5112 known processed) with 0 events remaining.

What should I do?

**Comment by Anu2006-dev** [comment]
for those guys who doesn't know you can set environment variables (`LDFLAGS=-L/usr/lib/openssl-1.0 CFLAGS="-I/usr/include/openssl-1.0" `) in your shell's config file or in my case I created a .env file and sourced it on my .zshrc. and call the `pyenv` command as usual. eg: `pyenv install 2.7.6`

**Comment by Anu2006-dev** [comment]
@minaee did you try [this](https://askubuntu.com/questions/1244408/fatal-io-error-22-invalid-argument-on-x-server-0)

**Comment by munim** [comment]
I just installed `2.7.18` in Archlinux, `2.7.9` failed.
