### ISSUE TITLE
libpython3.6m.so.1.0 is missing in python3.6.1

### ISSUE THREAD

**Issue by ignrub** [pyenv/pyenv#917]
After doing:
$ pyenv install 3.6.1
$ export PYENV_VERSION=3.6.1
$ pip install pyqt5 spyder
$ spyder3
gives the following error
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

**Comment by ignrub** [comment]
The solution was to uninstall Python:
$ pyenv uninstall 3.6.1
and then reinstall it with shared library support as:
$ CONFIGURE_OPTS=--enable-shared pyenv install 3.6.1
(https://github.com/pyenv/pyenv/issues/82)

**Comment by tango4j** [comment]
This would solve the problem. 
$ sudo apt-get install libpython3.6-dev 

https://www.thelinuxfaq.com/ubuntu/ubuntu-17-04-zesty-zapus/libpython3.6-dev

**Comment by indobits** [comment]
> CONFIGURE_OPTS=--enable-shared pyenv install 3.6.1

thanks, worked for me

**Comment by jessequinn** [comment]
Thanks for the code:
`CONFIGURE_OPTS=--enable-shared pyenv install `

Not to be a d*ck, but I love how everyone just assumes people use Ubuntu..
