### ISSUE TITLE
pyenv: no such command `shell'

### ISSUE THREAD

**Issue by kjcole** [pyenv/pyenv#918]
I've just installed, from this repo, pyenv on an Ubuntu 16.04 LTS box. 

    $ pyenv versions
    * system (set by /home/.../.pyenv/version)
      3.4.4

    $ pyenv --help
    Usage: pyenv <command> [<args>]
    
    Some useful pyenv commands are:
       commands    List all available pyenv commands
       local       Set or show the local application-specific Python version
       global      Set or show the global Python version
       shell       Set or show the shell-specific Python version
       install     Install a Python version using python-build
       uninstall   Uninstall a specific Python version
       rehash      Rehash pyenv shims (run this after installing executables)
       version     Show the current Python version and its origin
       versions    List all Python versions available to pyenv
       which       Display the full path to an executable
       whence      List all Python versions that contain the given executable
    
    See `pyenv help <command>' for information on a specific command.
    For full documentation, see: https://github.com/pyenv/pyenv#readme

Unfortunately:

    $ pyenv shell 3.4.4
    pyenv: no such command `shell'

**Comment by joshfriend** [comment]
https://github.com/pyenv/pyenv/issues/875#issuecomment-288855328
