### ISSUE TITLE
pyenv install without args fails with multiple versions in .python-version

### ISSUE THREAD

**Issue by stevecj** [pyenv/pyenv#919]
This is easy to work around, but…

If I specify multiple python versions using `pyenv local` or by manually entering them into .python-versions, then executing `pyenv install` fails with an error. It is apparently trying to use the entire list of versions as if it were a single version to try to match. I would have expected it to try to install each of the listed versions.

Example error output:

    $ pyenv install
    python-build: definition not found: 3.6.1
    3.5.3
    3.4.6
    3.3.6

    The following versions contain `3.6.1
    3.5.3
    3.4.6
    3.3.6' in the name:
      3.3.6
      3.4.6
      3.5.3
      3.6.1
    
    See all available versions with `pyenv install --list'.
    
    If the version you need is missing, try upgrading pyenv:
    
      brew update && brew upgrade pyenv

**Comment by jat255** [comment]
Just commenting an opinion that (as a user), if I specify interpreter versions that the project might use via `pyenv local X.Y.Z x.y.z ...`, I would naively expect that `pyenv install` would install all of those versions. It was unexpected to me as a newer user of `pyenv` that those commands were not compatible with each other, and the error message was unclear.

At the very least, I would suggest improving the error message that if `.python-version` has more than one line, tell the user this is unsupported/not implemented. A more proper solution (in my opinion) would be to just install each version contained in that file.

**Comment by colindean** [comment]
I found this issue when encountering this unexpected behavior. Because we've versioned `.python-version` and it was written by running `pyenv local 3.9.10 3.8.12 3.7.12 3.10.2` after having manually installed each of those, I would expect `pyenv install` to install all of what's in `.python-version`.

**Comment by phoenixuprising** [comment]
Going to echo that this is very weird behavior. Currently we are using pyenv to specify 2.7.18 and 3.8.11 as we need to maintain backwards compatibility with some packages a vendor has provided that won't be updated to 3.x. That is actually the exact use case specified by `pyenv local --help`

```
...

Example: To enable the python2.7 and python3.7 shims to find their
         respective executables you could set both versions with:

'pyenv local 3.7.0 2.7.15'
```
