### ISSUE TITLE
install_git doesn't seem to support tags?

### ISSUE THREAD

**Issue by scop** [pyenv/pyenv#922]
I thought I'd add micropython 1.9 with basically this:
```
#require_gcc
install_git micropython-1.9 https://github.com/micropython/micropython v1.9 micropython
```
But it doesn't work, maybe because `v1.9` is a tag and not a branch? Ditto for other micropython releases.
```
$ pyenv install -v micropython-1.9
/tmp/python-build.20170529121054.17363 ~
Cloning https://github.com/micropython/micropython...
~/workspace/pyenv/cache /tmp/python-build.20170529121054.17363 ~
error: cannot update the ref 'refs/heads/v1.9': Trying to write non-commit object a560ecca53514e0b44f9e758a995dbe4956c8066 to branch refs/heads/v1.9
From https://github.com/micropython/micropython
 ! [new tag]         v1.9       -> v1.9  (unable to update local ref)

BUILD FAILED (Fedora 25 using python-build 1.0.10-25-g55ab418)
```

**Comment by native-api** [comment]
Releases are supposed to be installed from tarballs (and checksum-verified). It's impossible to verify a Git checkout.

**Comment by scop** [comment]
install_git does support installing from branches, which are even more volatile than tags, so in that sense verifiability should not be a concern here.

Aside, verifying a git checkout is very much possible though. But that's not what was asked here.

But nevermind, haven't needed the ability to install from tags in a while.

**Comment by native-api** [comment]
I just explained that this functionality is simply not needed for how things are now.
You can propose it if you wish if you can justify the added complexity and address the drawbacks.
