### ISSUE TITLE
PyPy*-x.y.z naming convention

### ISSUE THREAD

**Issue by BanzaiMan** [pyenv/pyenv#931]
## Background

Travis CI relies on python-build to compile and archive language runtimes so that it can be used on Python builds.

## Problem

PyPy*-x.y.z definitions in https://github.com/pyenv/pyenv/tree/master/plugins/python-build/share/python-build are a little inconsistent.

As of https://github.com/pyenv/pyenv/commit/d5b193e5b09c7adeb09a321af839b3b4219ad097, there is [`pypy3.5-5.7.1-beta`](https://github.com/pyenv/pyenv/blob/08497763068c10b9075de1201a64572962ec2662/plugins/python-build/share/python-build/pypy3.5-5.7.1-beta) which really points to `pypy3.5-5.7.1` (for supported distros), and there is [`pypy3-5.7-beta`](https://github.com/pyenv/pyenv/blob/08497763068c10b9075de1201a64572962ec2662/plugins/python-build/share/python-build/pypy3.5-5.7-beta) which really points to `pypy3.5-5.7.0` (again, for supported distros).

## Proposal

Rename these files, or aliases so that the file names are consistent (less work for consumers of these files); `pypy3.5-5.7.1` for the former, `pypy3.5-5.7.0` for the latter.

**Comment by blueyed** [comment]
Sounds good to me.
IIRC they are based on the release tarball names?!
Aliases (symlinks?) seem to be a nice way to keep the old names.

**Comment by joshfriend** [comment]
> IIRC they are based on the release tarball names?!

I believe thats correct (or thats how i name them anyways)

> Aliases (symlinks?) seem to be a nice way to keep the old names.

We already have _tons_ of installable pythons, including numerous existing aliases (`pypy` vs `pypy2`). It would be very nice to have zero aliases, though I can understand the need for compatibility :)

**Comment by blueyed** [comment]
Ok, given that it's only about two files here really, I think renaming them would be fine.

**Comment by joshfriend** [comment]
Looks like the PyPy team named the latest minor version update `5.8.0` (even in the tar files) 👍

**Comment by Samureus** [comment]
In the middle of a PR for 5.8.0 right now (unless somebody else beats me to it), just to confirm what you'd need,

pypy2.7-5.8.0
pypy3.5-5.8.0

I kept adding alpha and beta to the pypy3 releases to maintain the PyPy project naming conventions.

**Comment by joshfriend** [comment]
@Samureus that sounds right, pypy3.5 is the only one that is beta though, just to clarify

**Comment by Samureus** [comment]
@joshfriend yes, at least from what I can gather from here:
https://bitbucket.org/pypy/extradoc/src/037575bb91dab60bb0ce51a80cffaf2814eb73c4/planning/py3.5/py35plan-milestones.rst?at=extradoc&fileviewer=file-view-default

and

https://bitbucket.org/pypy/extradoc/src/037575bb91dab60bb0ce51a80cffaf2814eb73c4/planning/py3.5/milestone-2-progress.rst?at=extradoc&fileviewer=file-view-default

Sorry, no coffee before git is always a bad idea.

**Comment by thedrow** [comment]
Isn't this issue resolved? I believe it should be closed.
