### ISSUE TITLE
pyenv install with support tkinter but using tcl/tk 8.6 on centos 7

### ISSUE THREAD

**Issue by arcanosam** [pyenv/pyenv#933]
Hi guys.

Maybe my doubt is more related to linux compiling than pyenv... but I hope you can help me.

CentOS 7 support only tcl/tk 8.5 yet and I want to use tcl/tk 8.6.

I try it to compile tcl/tk 8.6 only for my user (not wide-system like /usr and on and on...)

then I try to:

```
export CONFIGURE_OPTS="--with-tcltk-include=-'-I/home/myuser/Tools/tcltk866/include' --with-tcltk-libs='-L/home/myuser/Tools/tcltk866/lib'"

pyenv install 3.6.1
```

I try differents values for --with-tcltk-libs, but in resume, nothing works. 

The pyenv installation completes without problem, but when I enter in python shell and try to import tkinter I receive the following error: 

> ModuleNtoFoundError: No module name '__tkinter'

someone could me guide how can I fix this? 

how can I build tcl/tk 8.6 locally on my user and point pyenv to  build python using this installation?

Thanks all.

Samuel

**Comment by Samureus** [comment]
I *think* the correct environment variable should be `PYTHON_CONFIGURE_OPTS`:

`env PYTHON_CONFIGURE_OPTS="--with-tcltk-include=-'-I/home/myuser/Tools/tcltk866/include' --with-tcltk-libs='-L/home/myuser/Tools/tcltk866/lib'" pyenv install 3.6.1`

**Comment by arcanosam** [comment]
thanks for trying help me

still don't work. 

python is installed without error, but the same error persist when I try to import tkinter

my builds below:

- build tcl/tk on centos 7:
   - https://pastebin.com/nuZza4WM
- building python with pyenv:
   - https://pastebin.com/HSuvGNSH

**Comment by Samureus** [comment]
I don't use CentOS myself so I don't know what else could be wrong. Could you try adding the `--debug` flag and copy the output?
```
export PYTHON_CONFIGURE_OPTS=="--with-tcltk-include=-'-I/home/myuser/Tools/tcltk866/include' --with-tcltk-libs='-L/home/myuser/Tools/tcltk866/lib'"
pyenv --debug install 3.6.1
```

**Comment by arcanosam** [comment]
Hi! thanks for help and sorry for my delay...

Here the log:

https://pastebin.com/sS3jTVJP

hope help to find what problem...

sometimes I think it's a problem in how tcl/tk is builded for python use when it's building..
or some symbolic link for python after install...

**Comment by ruyingghost** [comment]
@arcanosam 
Did you solve you the problem of pyenv + python3 +tkinter?
I tried every answer from google and could not kill the error:
ModuleNtoFoundError: No module name '__tkinter'

**Comment by nakano-masahiro** [comment]
try python 3.5 but 3.6

**Comment by arcanosam** [comment]
@ruyingghost sorry, but I abandon this problem waiting here a solution.
For a while I will not have time to try once more... But I will in the future

And there I'll try the suggestino of @nakano-masahiro too thanks! 

Sorry for my delay in response...
