### ISSUE TITLE
Current stable release version?

### ISSUE THREAD

**Issue by ilovezfs** [pyenv/pyenv#937]
Based on https://github.com/pyenv/pyenv/releases it's not clear to me whether 1.0.9 or 1.1.0 is the current stable release version. Could you clarify which should be in Homebrew now? Thanks!

**Comment by Samureus** [comment]
This is a Github thing, you need to click on "Show 2 newer tags" to reveal v1.1.0:

https://github.com/pyenv/pyenv/releases/tag/v1.1.0

**Comment by ilovezfs** [comment]
@Samureus yes I know that hehe. I'm really making a request that you designate 1.1.0 as the latest release on GitHub as it's confusing to the Homebrew livecheck system if the newest tag != current GitHub release. We get one answer when consulting the tags and a different answer when consulting the API. In general, I will always defer to the API not the greatest tag, since if the API returns anything for the latest version, that means it was explicitly designated as a release by upstream. If the API returns nothing, then I would go with the greatest tag. In your case, there's a conflict between the two, hence this issue.

**Comment by Samureus** [comment]
Duh, after a lot of head scratching I was able to figure it out, it seems to me that the tag was published but not the release. Could you check it again?

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ latest pyenv
1.1.0
```
Much better! Thank you :)

**Comment by Samureus** [comment]
:thumbsup:

**Comment by ilovezfs** [comment]
@Samureus it seems they have diverged again. https://github.com/pyenv/pyenv/releases/latest is pointing to 1.1.2 but the most recent tag is 1.1.3.

**Comment by yyuu** [comment]
Created one https://github.com/pyenv/pyenv/releases/tag/v1.1.3

**Comment by ilovezfs** [comment]
@yyuu thanks!
