### ISSUE TITLE
How to config pyenv's pip ?

### ISSUE THREAD

**Issue by ZoomQuiet** [pyenv/pyenv#95]
# env
- MAC OS X 10.9.1
- Python 2.7.6 (default, Dec 31 2013, 08:51:05)
  [GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.79)] on darwin
# backgroung
- in China, there is [GFW](http://en.wikipedia.org/wiki/Great_Firewall_of_China) blocked pypi.python.org
- so in China internet can not base pip default source site download packagets
# question
- in system python, we can fixed `~/.pip/pip.conf` point mirror in china 
- but in pyenv it look like ingore `~/.pip/pip.conf` config ?

so make error like :

```
$ pyenv install 3.3.3
Downloading Python-3.3.3.tgz...
-> http://yyuu.github.io/pythons/831d59212568dc12c95df222865d3441
Installing Python-3.3.3...
Installed Python-3.3.3 to /Users/zoomq/.pyenv/versions/3.3.3

Downloading setuptools-2.0.1.tar.gz...
-> https://pypi.python.org/packages/source/s/setuptools/setuptools-2.0.1.tar.gz
error: failed to download setuptools-2.0.1.tar.gz

BUILD FAILED
```

**Comment by aleiphoenix** [comment]
Just for record. When installing Python 2.7.x (or maybe 2.x?), python-build would need to install setuptools by `https://bootstrap.pypa.io/ez_setup.py`, which has a `--download-base` argument specifying where to download the setuptools.

It can be passed to `EZ_SETUP_OPTS` environment variable, set it to self-hosted mirror to override the `DEFAULT_URL`.

```
$ export EZ_SETUP_OPTS="--download-base='http://your-mirror/'"

$ pyenv install 2.7.9
```

**Comment by drllr** [comment]
Hi. you can get config's exact path by typing ```pip config debug```

**Comment by jenguidanos** [comment]
I have solved this problem by configuring the pip.ini file.

In my company there is a firewall and handshake  with SSL certificates cannot be done. I work with Windows and the problems to install packages with pip are continuous.

I created the file `C:/Users/jenguidanos/pip/pip.ini` with the following info:

```ini
[global]
trusted-host = pypi.python.org
               pypi.org
               files.pythonhosted.org
```
