### ISSUE TITLE
error installing pypy3.5-5.8.0-src: libpypy-c.*:  No such file or directory

### ISSUE THREAD

**Issue by anthrotype** [pyenv/pyenv#955]
Hi,

I'm trying to build and install pypy3.5-5.8.0 from source on macOS 10.12.6.
When I do `pyenv install -v pypy3.5-5.8.0-src` the build seems to complete successfully, but the installation fails with this error:

```
mv: rename libpypy-c.* to bin/libpypy-c.*: No such file or directory
```

I think it has to do with the fact that on pypy3 the shared library is called `libpypy3-c.*`, and not `libpypy-c.*`.

**Comment by yyuu** [comment]
Ah, good catch. Will prepare a fix for it.

**Comment by yyuu** [comment]
@anthrotype I've opened #956 for workaround of the issue. Could you give it a try when you get a chance?

**Comment by anthrotype** [comment]
thanks!
still no luck with #956 though.

I'm running macOS Sierra 10.12.6; I installed gcc 7.1.0 via homebrew.
I run pyenv install with this command:

```
$ CFLAGS="-I$(brew --prefix openssl)/include" LDFLAGS="-L$(brew --prefix openssl)/lib" pyenv install -v pypy3.5-5.8.0-src
```

This are the last lines of the log:
```
[Timer] Timings:
[Timer] annotate                       ---  347.4 s
[Timer] rtype_lltype                   ---  343.9 s
[Timer] pyjitpl_lltype                 ---  615.1 s
[Timer] backendopt_lltype              ---  102.7 s
[Timer] stackcheckinsertion_lltype     ---   79.3 s
[Timer] database_c                     ---  244.0 s
[Timer] source_c                       ---  117.5 s
[Timer] compile_c                      ---  338.4 s
[Timer] build_cffi_imports             ---   18.1 s
[Timer] ===========================================
[Timer] Total:                         --- 2206.4 s
in get_rpath_flags, rel_libdirs is not fixed up ['/usr/lib']
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (OS X 10.12.6 using python-build 1.1.3-7-g269a702)

Inspect or clean up the working tree at /var/folders/7k/fl5q53lj51g0d8hxdkrx9_z80000gn/T/python-build.20170726115157.82572
```

I'm not sure where the error is. Maybe `in get_rpath_flags, rel_libdirs is not fixed up ['/usr/lib']` ?

Also, I wonder why it's warning about the ssl module not being compiled... I actually did pass the brew openssl CFLAGS and LDFLAGS as explained in "common build problems" wiki page; if I run the generated `bin/pypy3-c` from the temporary build directory and then `import ssl` it seems to work...

I also attach below the full build log:
[python-build.20170726115157.82572.log.txt](https://github.com/pyenv/pyenv/files/1176434/python-build.20170726115157.82572.log.txt)

**Comment by techdragon** [comment]
I've repeated this and gotten the exact same results. i'm not sure what the cause is though.
