### ISSUE TITLE
"cannot execute binary file" error

### ISSUE THREAD

**Issue by aiguofer** [pyenv/pyenv#957]
Hi, I'm suddenly getting the following error:

`~/.pyenv/shims/python: line 5: .: ~/.pyenv/versions/custard/bin/python: cannot execute binary file`

But I can successfully start a python shell with:

`~/.pyenv/versions/custard/bin/python`

The only thing I can think that changed was me updating `prezto` (I'm using zsh) and `pyenv` yesterday.

**Comment by blueyed** [comment]
What does `file ~/.pyenv/versions/custard/bin/python` and `ls -l ~/.pyenv/versions/custard/bin/python` give you?

**Comment by aiguofer** [comment]
btw, now I also get this when I open up a terminal:

```
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9182.
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9182.
~/.pyenv/versions/custard/bin/pip: line 7: from: command not found
~/.pyenv/versions/custard/bin/pip: line 10: syntax error near unexpected token `('
~/.pyenv/versions/custard/bin/pip: line 10: `    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])'
```

**Comment by aiguofer** [comment]
Not sure why this didn't occur to me earlier.... if I back up `.pyenv` and start from scratch, everything seems to be working fine... I just copied over my old `versions` dir into the new install and I'm good again. 

doing `diff --brief -Nr .pyenv .pyenv.bk` I see that all the files in `shims` are different... maybe they got corrupted during a pyenv update? ¯\_(ツ)_/¯

closing as this is solved now
