### ISSUE TITLE
safe to remove some pyenv shims?

### ISSUE THREAD

**Issue by kzidane** [pyenv/pyenv#958]
Is it safe to remove the shims without version suffix (e.g., `python`, `pip`, ...) and only keep the ones with version suffix (e.g., `python3`, `pip3`, ...) or might that break anything `pyenv` does? 

Goal is to keep using system's Python 2.7 (since it's already installed by default on my system) and only use `pyenv` for other versions (e..g, 3.6), but I want `python` to resolve to the system's python (e.g., `/usr/bin/python` or `/usr/local/bin/python`), not `pyenv`'s shim. Alternatively, might there be a way to configure the `python` shim to resolve to the system's `python` not `pyenv`'s?

**Comment by joshfriend** [comment]
See [the README](https://github.com/pyenv/pyenv#choosing-the-python-version) for how to activate multiple versions of python at once.

You can use a mix of system python and pyenv pythons with this method:

```
$ pyenv global system 3.6.2
```

This will set pyenv to use system python when you run `python` and pyenv's python3 when you run `python3`:

```
$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 0.9.8zh 14 Jan 2016'
$ python3
Python 3.6.2 (default, Jul 17 2017, 09:07:10)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.0.2k  26 Jan 2017'
```

That said, you should just use pyenv for both versions. Your system probably has an older version of python2 installed by default (I have 2.7.10 in macOS Sierra) that is probably also compiled against an older version of OpenSSL (see above). It is basically zero work to install a version of python2 if you already have pyenv working.

Also note that depending on how your system python is set up, you might not have a `python2` shim (I don't have one when i use `system` python on macOS).
