### ISSUE TITLE
Failed to run in Babun

### ISSUE THREAD

**Issue by beta** [pyenv/pyenv#961]
I have just made a fresh installation of [Babun](http://babun.github.io/), and keep zsh as the default shell. Then I installed pyenv with pyenv-installer (`$ curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | zsh`), and added the following lines into `~/.zshrc`:

```sh
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

After restarting babun, some error messages appeared:

```
: invalid options/beta/.pyenv/bin/pyenv: line 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
': not a valid identifier/.pyenv/bin/pyenv: line 3: unset: `CDPATH
/cygdrive/c/Users/beta/.pyenv/bin/pyenv: line 4: $'\r': command not found
/cygdrive/c/Users/beta/.pyenv/bin/pyenv: line 15: syntax error near unexpected token `$'{\r''
'cygdrive/c/Users/beta/.pyenv/bin/pyenv: line 15: `abort() {
: invalid options/beta/.pyenv/bin/pyenv: line 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
': not a valid identifier/.pyenv/bin/pyenv: line 3: unset: `CDPATH
/cygdrive/c/Users/beta/.pyenv/bin/pyenv: line 4: $'\r': command not found
/cygdrive/c/Users/beta/.pyenv/bin/pyenv: line 15: syntax error near unexpected token `$'{\r''
'cygdrive/c/Users/beta/.pyenv/bin/pyenv: line 15: `abort() {
```

Seems like the shell script doesn't work properly in Babun. However, when I manually type `$ set -e`, it works and no syntax error is found. Is this a problem with pyenv itself or Babun?

**Comment by joshfriend** [comment]
I wonder if it's because the files got checked out with windows line endings (CRLF - `\r\n`) instead of unix line endings (LF  -`\n`)

**Comment by beta** [comment]
Exactly it is. After `git config --global core.autocrlf input` and reinstalling pyenv it finally works. Thanks Josh you really save my day. :)
