### ISSUE TITLE
pydoc not found

### ISSUE THREAD

**Issue by olalonde** [pyenv/pyenv#963]
What is the recommended way to get `pydoc` to work when inside a pyenv virtualenv?

```
(rise) ~/rise$ python --version
Python 3.6.2
(rise) ~/rise$ pydoc3
pyenv: pydoc3: command not found

The `pydoc3' command exists in these Python versions:
  3.6.2

(rise) ~/rise$ pydoc
pyenv: pydoc: command not found

The `pydoc' command exists in these Python versions:
  3.6.2
```

**Comment by olalonde** [comment]
Anyone has a workaround for this? It's pretty annoying :(

**Comment by olalonde** [comment]
Think I found a workaround, replaced `~/.pyenv/shims/pydoc` with:

```python
#!/usr/bin/env python

import pydoc
if __name__ == '__main__':
    pydoc.cli()
```

**Comment by blueyed** [comment]
Related: https://github.com/pypa/virtualenv/issues/149 (and links from there).

**Comment by yyuu** [comment]
pyenv/pyenv-virtualenv#230 will generate pydoc executable. It should solve the issue.
