### ISSUE TITLE
upgraded pyenv via homebrew, now can't find my virtualenvs?

### ISSUE THREAD

**Issue by sheyman** [pyenv/pyenv#968]
Upgraded pyenv using brew update && brew upgrade pyenv

Now my pyenv virtualenvs shows nothing.  I do see the directories under /usr/local/Cellar/pyenv for 1.0.7 (old one) and 1.1.3 (new one).

My virtualenvs under 1.0.7 are the ones I want, but it only sees the ones under 1.1.3.

Any way to migrate them?  Copy them?  Seems really nasty that an upgrade of the tool would wipe out so much work.

Thanks!

**Comment by chrahunt** [comment]
While it is pyenv update that causes this, it would be better to have this conversation in [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv/issues). Please file an issue over there and we can look into ways to accommodate this concern.
