### ISSUE TITLE
stable tags?

### ISSUE THREAD

**Issue by draeath** [pyenv/pyenv#974]
I'd like to request that the most current "tags/v1.1.3" type of tag also be tagged something like "stable."

This would make it easier for users to track updates in an automated fashion (vs having to look up the tags manually).

This request would extend to the pyenv-virtualenv plugin as well.

**Comment by yyuu** [comment]
Mutable something should not represent as a tag. Anyway master is something like that at present. If you'd like to do some release management for yourself, do it yourself.

**Comment by draeath** [comment]
"master is something like that" what does this mean? Are changes pushed to the master branch without testing? That's my major concern, I'd like to be able to track master if it's "safe" to do so in an unattended manner.

**Comment by joshfriend** [comment]
Why wouldn't something like [this](https://stackoverflow.com/a/4277828/1255482) work?

```sh
git describe --tags $(git rev-list --tags --max-count=1)
```

**Comment by joshfriend** [comment]
Also, the only real usefulness that I see for tags in this project is to track what is currently released on Homebrew. You should just treat `master` as `latest`, as @yyuu was suggesting.

**Comment by draeath** [comment]
Thank you both!
