### ISSUE TITLE
pip install won't fetch package from https

### ISSUE THREAD

**Issue by bunhann** [pyenv/pyenv#975]
Hi, All.
I have a problem with pip install. It won't fetch data from https. It always shows this message as below when I try to install new packages. For example, pip install ezinstall

```
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting ezinstall
  Could not fetch URL https://pypi.python.org/simple/ezinstall/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
```
Does anyone know about this? How to fixed it?

**Comment by yyuu** [comment]
> pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.

As you can read from the message, your python installation doesn't have `ssl` module. It should be there if the version was built via `pyenv install` since there's a check for it.

https://github.com/pyenv/pyenv/blob/fd0b8fcfb312aac12efd9529aeb0e516972fa066/plugins/python-build/bin/python-build#L1658

Anyway it's a pip issue.

**Comment by johnesher** [comment]
I did
`pyenv install 3.6.4`
and have this issue

**Comment by n1ru4l** [comment]
I encountered this after upgrading pyenv (using brew), installing a newer python version and then switching back to the earlier version.

I fixed it by simply by reinstalling that version using `pyenv install <version-that-causes-this-issue>`

**Comment by shimamizu** [comment]
> I encountered this after upgrading pyenv (using brew), installing a newer python version and then switching back to the earlier version.
> 
> I fixed it by simply by reinstalling that version using `pyenv install <version-that-causes-this-issue>`.

This worked for me as well to fix the problem.
