### ISSUE TITLE
Fails for/with `virtualenv --python="$(which python)" FOO`

### ISSUE THREAD

**Issue by blueyed** [pyenv/pyenv#98]
When using the above code to create a virtualenv, it fails:

```
❯ virtualenv --python="$(which python)" FOO
Running virtualenv with interpreter /home/user/.pyenv/shims/python
New python executable in FOO/bin/python
ERROR: The executable FOO/bin/python is not functioning
ERROR: It thinks sys.prefix is u'/usr' (should be u'/home/user/src/pip-tools/FOO')
ERROR: virtualenv is not compatible with this system or executable
```

Since `virtualenv` itself is shimmed, a solution to this might be to replace instances to itself accordingly.

For example, the following tests make use of it:

```
https://github.com/nvie/pip-tools/blob/master/tests/dump.t
```

**Comment by tgalery** [comment]
hi guys, sorry to disturb you with this, but I'm pretty much having this issue when passing a miniconda python bin, e.g.

```
$ virtualenv env2 -p /home/ec2-user/.pyenv/versions/miniconda-3.10.1/bin/python --system-site-packages
Running virtualenv with interpreter /home/ec2-user/.pyenv/versions/miniconda-3.10.1/bin/python
New python executable in env2/bin/python
ERROR: The executable env2/bin/python is not functioning
ERROR: It thinks sys.prefix is u'/usr' (should be u'/home/ec2-user/ner/env2')
ERROR: virtualenv is not compatible with this system or executable
```

Any pointers?

**Comment by yyuu** [comment]
It might be an issue of [virtualenv](https://github.com/pypa/virtualenv) with miniconda's python executable. Anyway virtualenv is virtualenv, not pyenv.

**Comment by eregon** [comment]
@yyuu 
> It seems that the CPython's `sys.executable` requires the path to the `python` executable should be in `PATH`.

If that's a case, it sounds like a CPython bug.
But it doesn't seem to be the case for me:
```
$ which python    
/usr/bin/python
$ PATH=/nothing /usr/bin/python -c 'import sys; print(sys.executable)'
/usr/bin/python
```
Prepending `/usr/bin` causes many issues (#789, #1169), can we avoid it?

**Comment by blueyed** [comment]
> If that's a case, it sounds like a CPython bug.

Good point.

But it's still the case:

```
% (PATH=/nothing exec -a python /usr/bin/python -c 'import sys; print("exe", repr(sys.executable))';)                                                                            
exe ''
```
Python 3.7.4.

The problem here is the `exec -a`, removed in https://github.com/pyenv/pyenv/pull/1169/commits/c9805e30c0faac2e07676cda0c4c4ceb45d56779 (to be merged hopefully soon).

**Comment by efiop** [comment]
@yyuu @blueyed Hi Guys! Sorry, might be missing something obvious, but is there any info on that cpython bug? Like a ticket on bugs.python.org? If it could be fixed, and the solution is accepted, I'm pretty sure it will get backported quite quick, so pyenv no longer has to workaround that in never versions of cpython. I'm happy to help with that too :slightly_smiling_face:

**Comment by blueyed** [comment]
@efiop 
No reference is known here AFAIK.
Not too conviced it would be fixed or even backported quickly though anyway, since it changes behavior.

But please feel free to search for / create an issue over there (and link it from here then).
