### ISSUE TITLE
Pipfile support

### ISSUE THREAD

**Issue by sobolevn** [pyenv/pyenv#981]
`Pipfile` has a special section to specify required `python` version.

But for now I can not find any way to bundle `pyenv` with it.
New version of `pipenv` introduced partial support: http://docs.pipenv.org/en/latest/advanced.html#specifying-versions-of-python

Do you have any plans on supporting it?

**Comment by joshfriend** [comment]
pipenv can [use pyenv to install the specified python version in the `Pipfile`](http://docs.pipenv.org/en/latest/advanced.html#automatic-python-installation)

**Comment by eblume** [comment]
The URL for this info has changed: `https://docs.pipenv.org/advanced/#automatic-python-installation`

(As a side note, I think it is also broken, but I'm investigating that now.)

**Comment by joshfriend** [comment]
Thanks, I updated the link in my comment
