### ISSUE TITLE
BUILD FAILED (OS X 10.13 using python-build 20160602)

### ISSUE THREAD

**Issue by HuangYanQi** [pyenv/pyenv#988]
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

I'd try to use CFLAGS=-I/usr/include/openssl \                                     [9:53:06]
LDFLAGS=-L/usr/lib64 \  ,but useless

**Comment by AngularLock** [comment]
I also have this problem.Anyone can help?

**Comment by rlex** [comment]
I'm not sure but looks like OSX 10.13 doesn't ship openssl/libressl headers anymore. 

```
CFLAGS="-I$(brew --prefix openssl)/include" \
LDFLAGS="-L$(brew --prefix openssl)/lib" \
pyenv install 3.6.2
```
Worked for me with openssl from homebrew.

**Comment by yyuu** [comment]
Always don't forget to install Xcode Command Line Tools after upgrading macOS version.

**Comment by YoonseokOh** [comment]
I found the solution from http://digidememory.blogspot.com/2019/01/macos-mojave-10142python371.html

In my case, I solved by this command
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
