### ISSUE TITLE
pyenv should provide support for building framework variants of Python on MacOS X.

### ISSUE THREAD

**Issue by jasonbrent** [pyenv/pyenv#99]
Please reference issue#55 for a variant on this request.

Due to the requirements of modules like sip, pyqt and other things, I have the need to
build Python as a framework on MacOS (10.9.1, but I expect it doesn't matter much).

It looks like the real problem here is that Python2 (didn't test 3) does not appear to
have completely correct support for --enable-framework. This may actually just be
considered an upstream python bug/limitation when a value is provided to --enable-framework
and the default system location isn't used.

Ultimately, I was able to build this with pyenv, but only via manual interaction/install
after pyenv failed to build automatically.

Currently fails:

1) PYTHON_CONFIGURE_OPTS="--enable-framewok" pyenv install 2.7.6

Fails because it attempts to install to the system Python framework and doesn't have write access (non-root user).

2) PYTHON_CONFIGURE_OPTS="--enable-framework=$(pyenv root)/versions/2.7.6" pyenv install 2.7.6

Fails in the 'frameworkinstallmaclib' portion of the build/install due to the 'config' directory in the right hand side
of the path not existing:
..snip..
ln -fs "../../../$(PYTHONFRAMEWORK)" "$(DESTDIR)$(prefix)/lib/python$(VERSION)/config/libpython$(VERSION).a"
..snip..

If I run #2, then manually create the 'config' directory in the destination path above,
then manually continue the failed build/install, a usable installation of python results.

This fails on 2.7.4 and 2.7.6 at least

Manually making 'config' in the destination directory allows the build/install to complete and then function properly. I 
don't grok the python build system enough where to fix it in the makefile configuration itself.

Thanks,

-jbl

**Comment by msmummy** [comment]
I saw in pyenv source code that this (--enable-framework) is only supported on mac. Is it possible to enable it for Linux systems (such as Arch)?

**Comment by wdy1184** [comment]
@shuaimu linux should use this: `--enable-shared`

**Comment by floswald** [comment]
doesn't work for me:

```
➜  v0.6 env PYTHON_CONFIGURE_OPTS="--enable-framework CC=clang" pyenv install 2.7.10
pyenv: /Users/florian.oswald/.pyenv/versions/2.7.10 already exists
continue with installation? (y/N) y
Downloading Python-2.7.10.tgz...
-> https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
Installing Python-2.7.10...
patching file ./Lib/site.py

BUILD FAILED (OS X 10.13.2 using python-build 20160130)

Inspect or clean up the working tree at /var/folders/d2/hbd_ncyd6rg7jj25j7d4ht3h0000gp/T/python-build.20180120143645.1342
Results logged to /var/folders/d2/hbd_ncyd6rg7jj25j7d4ht3h0000gp/T/python-build.20180120143645.1342.log

Last 10 log lines:
changing mode of /Users/florian.oswald/.pyenv/versions/2.7.10/Python.framework/Versions/2.7/bin/2to3 to 755
changing mode of /Users/florian.oswald/.pyenv/versions/2.7.10/Python.framework/Versions/2.7/bin/pydoc to 755
changing mode of /Users/florian.oswald/.pyenv/versions/2.7.10/Python.framework/Versions/2.7/bin/smtpd.py to 755
running install_egg_info
Removing /Users/florian.oswald/.pyenv/versions/2.7.10/lib/python2.7/lib-dynload/Python-2.7.10-py2.7.egg-info
Writing /Users/florian.oswald/.pyenv/versions/2.7.10/lib/python2.7/lib-dynload/Python-2.7.10-py2.7.egg-info
rm /Users/florian.oswald/.pyenv/versions/2.7.10/lib/python2.7/lib-dynload/_sysconfigdata.py*
ln -fs "../../../Python" "/Users/florian.oswald/.pyenv/versions/2.7.10/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.a"
ln: /Users/florian.oswald/.pyenv/versions/2.7.10/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.a: No such file or directory
make: *** [frameworkinstallmaclib] Error 1
```

any idea what that could mean?

**Comment by programus** [comment]
@floswald I had exactly the same problem as yours. Uninstall the target version before install solved my problem. Hope this helps you too.

**Comment by toshi09** [comment]
Same problem, none of above works

**Comment by floswald** [comment]
yes @programus ! thanks for reporting back! does work indeed.

**Comment by fhennecker** [comment]
I had the same problem of failing at `[frameworkinstallmaclib]` and spent hours debugging where it came from. After some time I realised that my `$MAKEFLAGS` were set to `-j8`, which was breaking the compilation somehow. 

I did `export MAKEFLAGS=""`, re-tried installing python 3.7.1 using pyenv and it fixed it (if you ignore that I got one of the zlib errors mentioned in pyenv's common build problems and fixed it from there).

To any contributors, would it be possible that some dependencies are missing in the Makefile targets?

**Comment by WsK** [comment]
> Problem solved.
> 
> For some reasons, my computer doesn't like gcc-4.2 (which i installed via homebrew) and I have to change CC to clang
> 
> ```
> env PYTHON_CONFIGURE_OPTS="--enable-framework CC=clang" pyenv install 2.7.6
> ```

Thank you so much. This is still happening today in my system. OSX Catalina. the clang setting did the trick!

**Comment by reitermarkus** [comment]
Thanks @fhennecker, that was also my problem it seems. Was able to build it using

```bash
env MAKEFLAGS='' PYTHON_CONFIGURE_OPTS='--enable-framework' pyenv install 3.10.5
```
