### ISSUE TITLE
python-build not automatically installed

### ISSUE THREAD

**Issue by dfee** [pyenv/pyenv#990]
Reading the docs on [python-build](https://github.com/pyenv/pyenv/blob/32922007863c4a54feca2a95226c8307cfdfea3d/plugins/python-build/README.md)
> You need nothing to do since python-build is bundled with pyenv by default.

However, it's not found in my pyenv bin directory on my Debian container (`/root/.pyenv/bin`). So I've installed it manually, and it works fine... but are the docs wrong, or is something wrong on my Debian container?

**Comment by yyuu** [comment]
`pyenv` can find plugin executables in `$(pyenv root)/plugins/*/bin` by default. You don't have to have `python-build` in your `$PATH` outside `pyenv`.

https://github.com/pyenv/pyenv/blob/v1.1.4/libexec/pyenv#L85-L89
