### ISSUE TITLE
pyenv-install: pypy3.5-5.8.0-src: PyPy requires `genc' in 2.7.13 to build from source.

### ISSUE THREAD

**Issue by ssbarnea** [pyenv/pyenv#996]
While trying to install pypy3 from source on MacOS I ended up with this very confusing error:
```
$ pip install genc                                                                                                                                               Collecting genc
  Downloading genc-0.2.zip
Building wheels for collected packages: genc
  Running setup.py bdist_wheel for genc ... done
  Stored in directory: /Users/ssbarnea/Library/Caches/pip/wheels/a8/ca/8b/2078c595323d5df4bc0b5bf4e2a2e02f2a3346a5a39841ff91
Successfully built genc
Installing collected packages: genc
Successfully installed genc-0.2

$ pyenv install pypy3.5-5.8.0-src
pyenv-install: pypy3.5-5.8.0-src: PyPy requires `genc' in 2.7.13 to build from source.
```

**Comment by gagoman** [comment]
To build pypy you need to have python2.7 with `genc` and `pycparser` dependencies installed.

**Comment by joshfriend** [comment]
I would recommend installing PyPy from the binary versions if possible. Compiling it yourself takes FOREVER.

**Comment by mbdevpl** [comment]
@joshfriend I'm curious how much time it took in your case (and on what hardware)? I'm installing it now and it really takes forever... But in my case `pyenv install pypy3.5-5.8.0` says that on OS X I can't install binary, so here I am.
@ssbarnea `pip2.7 install genc pycparser` should get you going.

**Comment by MRigal** [comment]
I am having the same troubles with `pypy3.5-5.9.0`. It's basically ignoring my Python 2.7 install...

> $ pyenv install pypy3.5-5.9.0
ERROR: The binary distribution of PyPy is not available for osx64.
try 'pypy3.5-5.9.0-src' to build from source.
$ pyenv install pypy3.5-5.9.0-src
pyenv-install: pypy3.5-5.9.0-src: PyPy requires Python 2.7 to build from source.
$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15)

**Comment by mbdevpl** [comment]
My approach was more or less this:

    pyenv install 2.7.14
    pyenv global 2.7.14
    pip2.7 install -U pip wheel setuptools
    pip2.7 install genc pycparser
    pyenv install pypy3.5-5.8.0-src

Maybe the `global` did the trick?

Anyway, in my case it took around 2 hours to build (MacBook Pro 2016 13.3, Intel Core i5 2.9GHz).

**Comment by fny** [comment]
@mbdevpl It takes roughly an hour to build. Is there anyway to submit a prebuilt binary for PyEnv or have PyEnv make use of the Homebrew binaries?

**Comment by joshfriend** [comment]
@fny thats a pretty good idea.

They are on bintray [here](https://bintray.com/homebrew/bottles/pypy3), but we currently do not have a method of using them. We currently only use the official pypy binaries (which are linux64 only for pypy3.5, at least while in beta), or the (unofficial, and linux only) [portable pypy binaries](https://github.com/squeaky-pl/portable-pypy)

**Comment by sivel** [comment]
FWIW you need to have genc and pycparser installed in a python 2.7 install managed by pyenv.

I took a look through to find that error, and it gets it's candidates from roughly `pyenv versions --bare` and checks the version against `2.7*`

So the system python is insufficient.

something like:

```
pyenv install 2.7.14
pyenv shell 2.7.14
pip install genc pycparsing
pyenv install pypy3.5-5.9.0-src
```

Also you will want to have libffi from brew and added to CFLAGS

**Comment by sooheon** [comment]
@sivel What do you mean by this? 

> have libffi from brew and added to CFLAGS

**Comment by sivel** [comment]
@sooheon First you need to install libffi from homebrew such as:

`brew install libffi`

It now indicates:

```
For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/libffi/lib
```

`LDFLAGS` is an environment variable you would need to set.
