### ISSUE TITLE
wrong platform for pyenv build

### ISSUE THREAD

**Issue by uweschmitt** [pyenv/pyenv#998]
After installing `Python 2.7` with `pyenv` on my Mac with `OS X 10.11.6`, I get the following wrong result:

````
>>> import platform
>>> platform.mac_ver()
('10.11.6', ('', '', ''), 'i386')
````

This has the effect  that I can not install binary wheels created with the same Python interpreter because the platform tag in the wheels filename does not match.

If I use the `Python 2.7` which ships with my Mac I get instead

````
('10.11.6', ('', '', ''), 'x86_64')
````

I'm using `pyenv 1.1.4`

**Comment by joshfriend** [comment]
Which version of Python 2.7 did you install?

**Comment by uweschmitt** [comment]
Did `pyenv install 2.7`.

**Comment by joshfriend** [comment]
Yeah thats 2.7(.0), try installing a ancient version of 2.7.x, such as 2.7.14. I'd bet that 2.7(.0) has issues with the config that make it build a 32bit version instead of 64bit.

**Comment by chrahunt** [comment]
We can update the version identifier so this issue is less likely to happen in the future.
